### ISSUE TITLE
memory: Change `file` parameter into something more meaningful

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1011]
The current parameter `file` for `--memory` option is not fully appropriate as we don't really want to provide a specific file to back the VM's RAM. Whenever we use a backing file, the point is to be able to share this memory with other processes (case for `vhost-user`). And for these use cases we simply point to a special device such as `/dev/shm` or `/dev/hugepages`, so that one temporary file per memory region gets created in order to back the entire guest RAM.

The point is, because we don't have the use case for providing multiple files as the backing files, as this is only used in a special context of restoring a VM from a snapshot, we shouldn't even accept to receive a file as the backing source.

Two things need to be addressed:
- Check that the path provided points exclusively to a directory, return error otherwise
- Change parameter name `file` into something like `backing_dir` or `dir`

**Comment by sboeuf** [comment]
@likebreath I assigned this issue to you as I think this can be a good candidate to get started with some Cloud-Hypervisor contributions :)

**Comment by rbradford** [comment]
It doesn't actually need to be a file. If we use `memfd_create()` it's as if we did `/dev/shm` and if we use `MFD_HUGETLB` it's as if we did `/dev/hugepages`.

We could simply have `--memory shared=on|off,hugepages=on|off`

**Comment by sameo** [comment]
> It doesn't actually need to be a file. If we use `memfd_create()` it's as if we did `/dev/shm` and if we use `MFD_HUGETLB` it's as if we did `/dev/hugepages`.
> 
> We could simply have `--memory shared=on|off,hugepages=on|off`

Yes, that's pretty much all what we need the current `--memory file=` for, so I like that.

**Comment by sboeuf** [comment]
Yeah +1 from me on the `shared=on|off,hugepages=on|off`.
- If shared is `off` => mmap with `MAP_PRIVATE` and no backing file
- if shared is `on` => mmap with `MAP_SHARED` and we need a backing file

AND

- if hugepages is `off` => nothing is added
- if hugepages is `on` => add `MAP_HUGETLB` to the mmap flags

**Comment by sameo** [comment]
> Yeah +1 from me on the `shared=on|off,hugepages=on|off`.
> 
>     * If shared is `off` => mmap with `MAP_PRIVATE` and no backing file
> 
>     * if shared is `on` => mmap with `MAP_SHARED` and we need a backing file
> 
> 
> AND
> 
>     * if hugepages is `off` => nothing is added
> 
>     * if hugepages is `on` => add `MAP_HUGETLB` to the mmap flags

Or we _always_ create an fd with `memfd`, with MFD_HUGETLB if hugepages is on.
Once we have the fd, we either mmap it with `MAP_PRIVATE` or `MAP_SHARED`.

**Comment by likebreath** [comment]
@sboeuf Thanks for pointing me to the issue. I'd definitely want to take this issue, if the timeline works for the team. I am currently debugging on #816 #817, and want to finish those two first, as they are included for the next release. Any advises or questions, please don't hesitate to share.

If I got it correctly, we agreed that we want to simply the option as `--memory shared=on|off,hugepages=on|off`, from where the implementation can be also simplified as what you and/or @sameo mentioned above. This makes sense to me in general, but I think I will need some time to digest the code and implement that change (given I got quite a lot to pick up on rust-lang..).  Please bear with me on that...

**Comment by sboeuf** [comment]
No worries on the timeline @likebreath, there's no rush in getting this done, that's why I thought that was a good candidate for you since you can take your time to implement it.

**Comment by rbradford** [comment]
> No worries on the timeline @likebreath, there's no rush in getting this done, that's why I thought that was a good candidate for you since you can take your time to implement it.

Actually i'd like to see this included in the the 0.7.0 release.

- [ ] Add new parameters `shared` & `hugepages`
- [ ] Port `MemoryManager` to use those new options
- [ ] Map `file=/dev/shm` and `file=/dev/hugepages` to the approriate options
- [ ] Generate a deprecation warning if `file=` is used (or in the API)
- [ ] Remove after 0.7.0 release

This is important to get resolved for the release as #848 which this depends on this is in 0.7.0

**Comment by likebreath** [comment]
@rbradford @sboeuf I am switching my priority to this issue now. Let me see whether I can finish it before Thursday. If not I will shout and ask you to jump on it. Let me know whether it works for the timeline. Thanks a lot.
