### ISSUE TITLE
error: Could not boot the VM 

### ISSUE THREAD

**Issue by sunaru** [cloud-hypervisor/cloud-hypervisor#1014]
Hello,

Per Samuel Ortiz's advise, I am positing the issue here. 

When I ran below, I got the error "  thread 'main' panicked at 'Could not boot the VM: VmBoot(KvmNew(Error(13)))', src/libcore/result.rs:1188:5". I replaced disk path with "./eoan-server-cloudimg-amd" and I got the same error.

My OS is Ubuntu "18.04.2 LTS (Bionic Beaver)". I don't have kvm installed. Please advise.

./cloud-hypervisor/target/release/cloud-hypervisor \
	--kernel ./hypervisor-fw \
	--disk path=clear-31890-kvm.img \
	--cpus boot=4 \
	--memory size=1024M \
	--net "tap=,mac=,ip=,mask=" \
	--rng

Regards,
Sundaram

**Comment by iggy** [comment]
Did you try removing the args one at a time to see which one is causing it to fail?

**Comment by sameo** [comment]
@sunaru 
> I don't have kvm installed

Cloud Hypervisor won't work without KVM. You need to install it.

**Comment by rbradford** [comment]
You need a kernel with KVM enabled, appropriate permissions on `/dev/kvm` and hardware that supports it.
