### ISSUE TITLE
CLH exits when hotpluging memory based on backing file  

### ISSUE THREAD

**Issue by uMartinXu** [cloud-hypervisor/cloud-hypervisor#1031]
run CLH using below cmd
```
sudo cloud-hypervisor \
        --kernel vmlinux.bin \
        --console off \
        --serial tty \
        --disk path=clear-31890-kvm.img \
        --cmdline "memblock=debug console=ttyS0 reboot=k panic=1 nomodules i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd root=/dev/vda3 memhp_default_state=online" \
        --cpus boot=1 \
        --memory size=512M,file=/home/martin/t1,hotplug_method=acpi,hotplug_size=1024M \
        --net "tap=,mac=,ip=,mask=" \
        --rng
```
hotplug memory using the command below:
```
curl -H "Accept: application/json" -H "Content-Type: application/json" -i -XPUT --unix-socket /run/user/1000/cloud-hypervisor.4320 -d "{ \\"desired_ram\\" : $(((512 + 128)\*1024\*1024))}" http://localhost/api/v1/vm.resize
```

CLH will exit with below messge:
```
cloud-hypervisor: 36.581044851s: ERROR:vmm/src/cpu.rs:351 -- VCPU 0 error Error(14)
cloud-hypervisor: 36.581110104s: ERROR:vmm/src/cpu.rs:599 -- VCPU generated error: VcpuUnhandledKvmExit
Bus error 
```

The problem may come from boot mem and hotplug mem using the same backing file, when hotplugging memory the same backing file used by boot mem will be touched and trigger the VcpuUnhandledKvmExit and terminate CLH.

**Comment by sameo** [comment]
@uMartinXu Could you please clarify what you're trying to achieve here? What's your overall goal?

**Comment by uMartinXu** [comment]
@sameo I am investigating on the ways to hotplug the pmem from host to guest through CLH. One way I tried is to use backing file on daxfs. And I run into this issue. That is the reason I file the issue.

**Comment by uMartinXu** [comment]
@sameo  Thank you for pointing me issue #1011. I know the background.
Let me close the issue.
