### ISSUE TITLE
Track performance issues with MQ for virtio-blk and vhost-user-blk

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1037]
As mentioned in the discussion [here](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1033#discussion_r410052486) and [here](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1033#discussion_r410097100), we can improve the performances for both virtio-blk and vhost-user-blk when using multiqueue.
The current design creates a contention point around the `DiskFile` that is shared across different threads, where it should not. Instead, the shared file should be immutable as read()/write() syscalls are guaranteed to be atomic.

**Comment by sboeuf** [comment]
@slp 
I've starting to look into this issue, but before we think about improving the `virtio-blk` performance, I'm curious if the performance is equivalent to what we get with QEMU. I'm planning on using `fio`, but I'm really not sure about the most appropriate options I should use to get meaningful results.

In a second step, I'd like to discuss the design that would let us introduce `io_uring` to the codebase and how the asynchronicity would help with bypassing the need for a mutable `File`.

**Comment by slp** [comment]
> @slp
> I've starting to look into this issue, but before we think about improving the `virtio-blk` performance, I'm curious if the performance is equivalent to what we get with QEMU. I'm planning on using `fio`, but I'm really not sure about the most appropriate options I should use to get meaningful results.

For a synchronous workload (with `fio`, either using `ioengine=sync` or `iodepth=1`) the performance should be roughly equivalent. In fact, if it isn't, we should start fixing that first.

On the other hand, QEMU should win on pretty much every test generating an asynchronous workload (`ioengine=libaio` or `ioengine=io_uring` with `iodepth` > 2).

> In a second step, I'd like to discuss the design that would let us introduce `io_uring` to the codebase and how the asynchronicity would help with bypassing the need for a mutable `File`.

As it tends to happen with most filesystem abstractions provided by language libraries (including glibc's `FILE` itself), `File` is fine for conventional non-parallel I/O operations, but it basically becomes a nuisance (moving offsets, internal buffers...) when trying to work on the file from multiple threads.

If the idea is relying `io_uring`, I think it'd be more convenient to work directly with the `RawFd`, perhaps wrapping it into some object to close the `fd` it on `Drop`, and using `libc::writev` and `libc::readv` as a fallback when needed.

Another interesting aspect, is that given the simplicity of their block layer, both `virtio-blk` and `vhost-user-blk` should be able to support `io_uring` combined with actual `multiqueue`, something that it's currently not possible in QEMU (you can configure more than one queue, but all of them will be managed by a single `iothread`). This should enable them to invest more CPU is exchange for more bandwidth when working with very low-latency devices (i.e. enterprise-grade NVMe).

**Comment by sboeuf** [comment]
>For a synchronous workload (with fio, either using ioengine=sync or iodepth=1) the performance should be roughly equivalent. In fact, if it isn't, we should start fixing that first.

Here are the results:
```
#############################  
# FIO Command ioengine=sync #
#############################

$ sudo fio --filename=/dev/vdb --size=4G --direct=1 --rw=randrw --bs=4k --ioengine=sync --iodepth=1 --runtime=60 --numjobs=1 --time_based --group_reporting --name=iops-test-job --eta-newline=1

# CH 4G 4vCPUs 1 virtqueue queue_size=1024
##########################################

$ ./cloud-hypervisor --kernel bzImage --cmdline "root=/dev/vda1 console=hvc0 rw" --disk path=focal-server-cloudimg-amd64-custom.raw path=tmp.img,num_queues=1,queue_size=1024 --memory size=4G --cpus boot=4

READ: bw=131MiB/s (137MB/s), 131MiB/s-131MiB/s (137MB/s-137MB/s), io=7832MiB (8213MB), run=60001-60001msec
WRITE: bw=130MiB/s (137MB/s), 130MiB/s-130MiB/s (137MB/s-137MB/s), io=7823MiB (8204MB), run=60001-60001msec

# QEMU 4G 4vCPUs 1 virtqueue queue_size=1024
############################################

$ qemu-system-x86_64 -machine pc,accel=kvm -cpu host,host-phys-bits -m 4G -smp 4 -kernel bzImage -display none -nodefaults -serial stdio -append "console=ttyS0 root=/dev/vda1" -drive id=os,file=focal-server-cloudimg-amd64-custom.raw,if=none -device virtio-blk-pci,drive=os -drive id=test_disk,file=tmp.img,if=none -device virtio-blk-pci,drive=test_disk,num-queues=1,queue-size=1024

READ: bw=67.3MiB/s (70.6MB/s), 67.3MiB/s-67.3MiB/s (70.6MB/s-70.6MB/s), io=4037MiB (4233MB), run=60001-60001msec
WRITE: bw=67.2MiB/s (70.5MB/s), 67.2MiB/s-67.2MiB/s (70.5MB/s-70.5MB/s), io=4032MiB (4227MB), run=60001-60001msec
```
The test image was simply created with:
```
dd if=/dev/zero of=tmp.img bs=1M count=8192
```

>On the other hand, QEMU should win on pretty much every test generating an asynchronous workload (ioengine=libaio or ioengine=io_uring with iodepth > 2).

Here are the results:

```
###############################  
# FIO Command ioengine=libaio #
###############################

$ sudo fio --filename=/dev/vdb --size=4G --direct=1 --rw=randrw --bs=4k --ioengine=libaio --iodepth=256 --runtime=60 --numjobs=1 --time_based --group_reporting --name=iops-test-job --eta-newline=1

# CH 4G 4vCPUs 1 virtqueue queue_size=1024
##########################################

$ ./cloud-hypervisor --kernel bzImage --cmdline "root=/dev/vda1 console=hvc0 rw" --disk path=focal-server-cloudimg-amd64-custom.raw path=tmp.img,num_queues=1,queue_size=1024 --memory size=4G --cpus boot=4

READ: bw=340MiB/s (357MB/s), 340MiB/s-340MiB/s (357MB/s-357MB/s), io=19.0GiB (21.4GB), run=60001-60001msec
WRITE: bw=340MiB/s (357MB/s), 340MiB/s-340MiB/s (357MB/s-357MB/s), io=19.9GiB (21.4GB), run=60001-60001msec

# QEMU 4G 4vCPUs 1 virtqueue queue_size=1024
############################################

$ qemu-system-x86_64 -machine pc,accel=kvm -cpu host,host-phys-bits -m 4G -smp 4 -kernel bzImage -display none -nodefaults -serial stdio -append "console=ttyS0 root=/dev/vda1" -drive id=os,file=focal-server-cloudimg-amd64-custom.raw,if=none -device virtio-blk-pci,drive=os -drive id=test_disk,file=tmp.img,if=none -device virtio-blk-pci,drive=test_disk,num-queues=1,queue-size=1024

READ: bw=431MiB/s (452MB/s), 431MiB/s-431MiB/s (452MB/s-452MB/s), io=25.3GiB (27.1GB), run=60001-60001msec
WRITE: bw=431MiB/s (452MB/s), 431MiB/s-431MiB/s (452MB/s-452MB/s), io=25.2GiB (27.1GB), run=60001-60001msec
```

So this confirms that QEMU performs better with `libaio` engine, but it's weird that we get such a difference with the `sync` engine.
I don't get a good grasp about the reason why the libaio engine is performing better since we're talking about something running in the guest, which has no direct influence on the VMM?

>If the idea is relying io_uring, I think it'd be more convenient to work directly with the `RawFd`

Yes I agree we must use the RawFd if we want to bypass this limitation.

>Another interesting aspect, is that given the simplicity of their block layer, both virtio-blk and vhost-user-blk should be able to support `io_uring`

Yes. Another related question, should we extend the `vm-memory` to support async read/write or simply take a mutable slice from the memory and read/write to it through the io_uring API?

**Comment by rbradford** [comment]
> I don't get a good grasp about the reason why the libaio engine is performing better since we're talking about something running in the guest, which has no direct influence on the VMM?

I would theorise that each of the vCPU threads are now doing I/O requests. And although we are only processing them one at a time in the CH block thread we're making more progress as we're not maxing out one vCPU. You might see an indication of this if you looked the the vCPU and block threads (`htop` is good for this)

I also noticed you didn't use `O_DIRECT` so you do also have the effects of the host cache.

**Comment by rbradford** [comment]
If you tried libaio with just one vCPU I think you would see results closer to sync.

**Comment by sboeuf** [comment]
>I also noticed you didn't use O_DIRECT so you do also have the effects of the host cache.

Yes I forgot about host cache. I thought about guest cache by using `direct=1` from the `fio` command, but missed on the host side.

Here are the results with `O_DIRECT`:
```
#############################  
# FIO Command ioengine=sync #
#############################

$ sudo fio --filename=/dev/vdb --size=4G --direct=1 --rw=randrw --bs=4k --ioengine=sync --iodepth=1 --runtime=60 --numjobs=1 --time_based --group_reporting --name=iops-test-job --eta-newline=1

# CH 4G 4vCPUs 1 virtqueue queue_size=1024
##########################################

$ ./cloud-hypervisor --kernel bzImage --cmdline "root=/dev/vda1 console=hvc0 rw" --disk path=focal-server-cloudimg-amd64-custom.raw path=tmp.img,num_queues=1,queue_size=1024,direct=on --memory size=4G --cpus boot=4

READ: bw=24.1MiB/s (25.3MB/s), 24.1MiB/s-24.1MiB/s (25.3MB/s-25.3MB/s), io=1446MiB (1516MB), run=60001-60001msec
WRITE: bw=24.1MiB/s (25.2MB/s), 24.1MiB/s-24.1MiB/s (25.2MB/s-25.2MB/s), io=1444MiB (1514MB), run=60001-60001msec

# QEMU 4G 4vCPUs 1 virtqueue queue_size=1024
############################################

$ qemu-system-x86_64 -machine pc,accel=kvm -cpu host,host-phys-bits -m 4G -smp 4 -kernel bzImage -display none -nodefaults -serial stdio -append "console=ttyS0 root=/dev/vda1" -drive id=os,file=focal-server-cloudimg-amd64-custom.raw,if=none -device virtio-blk-pci,drive=os -drive id=test_disk,file=tmp.img,if=none,cache=none -device virtio-blk-pci,drive=test_disk,num-queues=1,queue-size=1024

READ: bw=17.5MiB/s (18.4MB/s), 17.5MiB/s-17.5MiB/s (18.4MB/s-18.4MB/s), io=1050MiB (1101MB), run=60001-60001msec
WRITE: bw=17.5MiB/s (18.4MB/s), 17.5MiB/s-17.5MiB/s (18.4MB/s-18.4MB/s), io=1052MiB (1103MB), run=60001-60001msec
```

**Comment by slp** [comment]
> # QEMU 4G 4vCPUs 1 virtqueue queue_size=1024
> ############################################
> 
> $ qemu-system-x86_64 -machine pc,accel=kvm -cpu host,host-phys-bits -m 4G -smp 4 -kernel bzImage -display none -nodefaults -serial stdio -append "console=ttyS0 root=/dev/vda1" -drive id=os,file=focal-server-cloudimg-amd64-custom.raw,if=none -device virtio-blk-pci,drive=os -drive id=test_disk,file=tmp.img,if=none -device virtio-blk-pci,drive=test_disk,num-queues=1,queue-size=1024

For a fair comparison, please enable `iothreads` in QEMU. Adding something like `-object iothread,id=iothread0` and `-device virtio-blk-pci,drive=test_disk,num-queues=1,queue-size=1024,iothread=iothread0` should do the trick.

> So this confirms that QEMU performs better with `libaio` engine, but it's weird that we get such a difference with the `sync` engine.
> I don't get a good grasp about the reason why the libaio engine is performing better since we're talking about something running in the guest, which has no direct influence on the VMM?

There are multiple variables in play here, but probably the one that makes the most difference is that with `libaio`, `fio` is able to maintain a higher number of pending requests in the `virtqueue`. This way, `virtio-blk` is always kept busy in a tight loop processing requests, while the guest vCPU is processing completions and pushing more requests, which is the ideal situation.

This is part of the reason why having an asynchronous backend is so important. Right now, in addition to processing the virtqueue, `virtio-blk` needs to process the I/O request itself, making both its code path and cache footprint longer and higher than ideal. With something like `io_uring`, each thread can focus on processing the `virtqueue` and the submission/completion queues.

> > Another interesting aspect, is that given the simplicity of their block layer, both virtio-blk and vhost-user-blk should be able to support `io_uring`
> 
> Yes. Another related question, should we extend the `vm-memory` to support async read/write or simply take a mutable slice from the memory and read/write to it through the io_uring API?

Hm... good question. Perhaps is something that should be discussed in the context of rust-vmm's `vm-memory` crate.

**Comment by sboeuf** [comment]
Ok so a quick summary here:

We could confirm that when performing synchronous I/O, both Cloud-Hypervisor and QEMU were producing similar numbers, which means nothing's wrong with the `virtio-blk` implementation of Cloud-Hypervisor.

We could also confirm that when performing asynchronous I/O (and still using a single queue), QEMU was outperforming Cloud-Hypervisor by 10x (Cloud-Hypervisor results were similar to the numbers obtained with synchronous I/O), as it implements asynchronous backends. The tests have been performed with `aio=io_uring`, as this is what Cloud-Hypervisor is looking at implementing.

Based on the asynchronous results, we're talking about very important improvements, hence we should really provide this feature out of the box when someone uses Cloud-Hypervisor. The plan for implementing it is the following:
- Port `io_uring` and `cros_async` from crosvm (or maybe use `tokyo-rs/io_uring` if something's missing) to Cloud-Hypervisor
- Factorize the epoll loop handling between `vhost-user-block` and `virtio-blk` into `block_util` crate
- Rely on a `RawFd` instead of `File`, this way we can get rid of the mutable requirement
- Change the epoll loop design. We must submit to the `io_uring` submit queue upon receiving a new event on the queue, and then as a second step, whenever we receive the notification about the completion, we can fill the descriptor and return it (mark it as used and send the interrupt).
- Continue to support synchronous design in case the host does not have a kernel recent enough, therefore doesn't support `io_uring`. The check should be done upon `Block` creation, and during the activate, we should run an `async` or `sync` thread, depending on the detected support.
- Still support `writeback=false` by flushing after each completion of a `write` operation.

**Comment by rbradford** [comment]
We have io_uring support in virtio-block that handles this very nicely. It's not enabled by default: #1561 but this issue itself can be closed.
