### ISSUE TITLE
Remove the MemoryConfig `file` field

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#1063]
We are now using the the `--memory shared=on|off,hugepages=on|off` options, instead of taking explicit backing file paths (e.g. `/dev/shm` or `/dev/hugepages`) from users. Ideally, we want to remove the deprecated `--memory file=` option completely.

**Comment by rbradford** [comment]
For now we have decided not to remove this option right now as there is some customer interest in using a feature like this. Most users should migrate `shared` and `hugepages` options.
