### ISSUE TITLE
Reboot doesn't work with virtio-vsock

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1083]
```
VMM thread failed VmReboot(DeviceManager(CreateVsockBackend(UnixBind(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))))

```

**Comment by rbradford** [comment]
I think this is the reopening of the existing file as the same thing happens if you boot with `sock=` pointing at an existing file.

**Comment by sboeuf** [comment]
Yes I think it's matter of implementing `shutdown()` from VirtioDevice. That means `vm-virtio/src/vsock/device.rs` must be expanded with `shutdown()` so that when called, it should remove the file.

**Comment by rbradford** [comment]
We don't remove the file for other things e.g. vhost-user socket. Instead it should tolerate the file already existing.

**Comment by rbradford** [comment]
> We don't remove the file for other things e.g. vhost-user socket. Instead it should tolerate the file already existing.

I was wrong here: `UnixListener::Bind` does not support reusing the same file.
