### ISSUE TITLE
Wrong HTTP 500 when shutdown VMM

### ISSUE THREAD

**Issue by linericyang** [cloud-hypervisor/cloud-hypervisor#1110]
After created the VM via API, it will return HTTP 500 with the response "VmmShutdown(VmmShutdown(VmNotRunning))" if try to shutdown the VMM.  The VMM process was terminated successfully. But [API doc](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/api.md#virtual-machine-manager-vmm-actions) only show that "The VMM is running" is only prerequisites to shut down VMM.

How to reproduce:
1. launch VMM and create a VM as usual
```
$ cloud-hypervisor --api-socket /tmp/cloud-hypervisor.sock
$ curl --unix-socket /tmp/cloud-hypervisor.sock -i \                                            
     -X PUT 'http://localhost/api/v1/vm.create'  \
     -H 'Accept: application/json'               \
     -H 'Content-Type: application/json'         \
     -d '{"cpus":{"boot_vcpus":2,"max_vcpus":2},"kernel":{"path":"/root/cloud-hypervisor/hypervisor-fw"},"cmdline":{"args":""},"disks":[{"path":"/root/cloud-hypervisor/clear-31890-cloudguest.img"}]}'
HTTP/1.1 204 
Server: Cloud Hypervisor API
Connection: keep-alive
```
2. Shutdown VMM at this point, it will return 500
```
$ curl --unix-socket /tmp/cloud-hypervisor.sock -i -X PUT 'http://localhost/api/v1/vmm.shutdown'
HTTP/1.1 500 
Server: Cloud Hypervisor API
Connection: keep-alive
Content-Type: application/json
Content-Length: 38

VmmShutdown(VmmShutdown(VmNotRunning))# 
```

Based on master branch commit eb3d9d15bfbd25a01d3ecb71ddc7cc158fee08af

**Comment by sboeuf** [comment]
Hi @linericyang 
You forgot to boot the VM after you created it. The flow is as follow:
- vm.create
- vm.boot
- vmm.shutdown

Please close this issue if this solves your problem :)

**Comment by linericyang** [comment]
@sboeuf Thanks for your reply.

So this is by desgin that user can only issue "vmm.shutdown" after "vm.boot"?  What's the reason to have this limitation?  One common workfolw to me is 

- vm.create
- vm.boot
- vm.shutdown
- vmm.shutdown

Another thing is ever it return 500, the process was terminated. Should it reject this request and keep the process running, if user is not allowed to shutdown vmm at that point?

**Comment by sboeuf** [comment]
@linericyang 
>So this is by desgin that user can only issue "vmm.shutdown" after "vm.boot"? What's the reason to have this limitation?

Yes you're right I didn't think about this case. It's not super high priority since I don't see why someone would create a VM without booting it, and then shut it down, but from a semantic standpoint, I agree it should work.

Feel free to tackle this issue by sending a pull request if you need this to be fixed rather sooner than later :)

**Comment by linericyang** [comment]
Right now in my libvirt driver implementation, I use SIGABRT signal to kill process instead of "vmm.shutdown" request. So this is not urgent one to me now :)

**Comment by rbradford** [comment]
I think vmm.shutdown not vm.shutdown should be possible at any time.
