### ISSUE TITLE
ch-remote usage is not right

### ISSUE THREAD

**Issue by teawater** [cloud-hypervisor/cloud-hypervisor#1117]
https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1116

**Comment by rbradford** [comment]
The usage is fine. You can either use with or without the "=". I've tested both. My thought is either something strange with your shell or that maybe you had copy and pasted a character that looks like a space but which isn't and so clap didn't see the separate parts.

**Comment by teawater** [comment]
That is weird.  I tried ch-remote in ubuntu and centos.  Both of them need "--api-socket=".

**Comment by rbradford** [comment]
Could it be your locale?

```
rob@artemis:~$ env | grep ^LANG
LANG=en_GB.UTF-8
```

**Comment by rbradford** [comment]
@teawater My apologies in turned out that when I was testing the advertised syntax I had the change in #1127 locally included. I think that this change has resolved the issue, would you be so kind as so test it?
