### ISSUE TITLE
Warning about how to reproduce integration tests locally

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#112]
I spent a lot of time debugging the integration tests today, trying to understand why on `master` I was not able to run successfully the tests on my machine.
The reason was very simple, the `clear-29810-cloud.img` located in my `$HOME/workloads` directory was already there from some previous testing, and I had used this image for some manual testing in the meantime associated with a `cloudinit.img` file.
The result is that the integration tests were reusing this image, despite the fact it was already provisioned by a previous `cloudinit` image. The freshly created `cloudinit` image from the test was simply ignored.

Should we enforce the removal of the `clear-29810-cloud.img` image from the script? Or should we at least put a warning notifying the user?

/cc @rbradford

**Comment by rbradford** [comment]
@sboeuf I think @sameo had the same problem with not realising a cloudinit runs at most once.

We could check the sha1sum of the images to make sure that they are "untainted". We'd probably want to distribute the raw version of the image if we do that in the azure bucket as qemu-img *might* not be deterministic.
