### ISSUE TITLE
specify memory size via API error

### ISSUE THREAD

**Issue by linericyang** [cloud-hypervisor/cloud-hypervisor#1122]
When I create VM with memory requirements **"memory":{"size":512}**, "vm.create" works as expected and return 204. But "vm.boot" returns 500 and error message "VmBoot(VmBoot(MemoryManager(SetUserMemoryRegion(Error(22)))))".

```
$ curl --unix-socket /tmp/cloud-hypervisor.sock -i \
     -X PUT 'http://localhost/api/v1/vm.create'  \
     -H 'Accept: application/json'               \
     -H 'Content-Type: application/json'         \
     -d '{"cpus":{"boot_vcpus":2,"max_vcpus":2},"memory":{"size":512},"kernel":{"path":"/root/cloud-hypervisor/hypervisor-fw"},"cmdline":{"args":""},"disks":[{"path":"/root/cloud-hypervisor/clear-31890-cloudguest.img"}]}'
HTTP/1.1 204 
Server: Cloud Hypervisor API
Connection: keep-alive

$ curl --unix-socket /tmp/cloud-hypervisor.sock -i -X PUT 'http://localhost/api/v1/vm.boot'
HTTP/1.1 500 
Server: Cloud Hypervisor API
Connection: keep-alive
Content-Type: application/json
Content-Length: 61

VmBoot(VmBoot(MemoryManager(SetUserMemoryRegion(Error(22)))))
```
I didn't find other restriction for memory from [API spec](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vmm/src/api/openapi/cloud-hypervisor.yaml#L378-L386). Any suggestion to fix it will be appreciated.

**Comment by sboeuf** [comment]
Try `512M` instead of `512`, otherwise it thinks you want to create a VM with 512 bytes of RAM.

**Comment by sboeuf** [comment]
Actually, you should provide `536870912` as `512M` won't work through the HTTP API.

**Comment by linericyang** [comment]
Thanks a lot, it works now. It would be better to document the only valid memory unit "byte" somewhere.
