### ISSUE TITLE
AArch64 support

### ISSUE THREAD

**Issue by michael2012z** [cloud-hypervisor/cloud-hypervisor#1125]
Hi, 

Henry(@MrXinWang) and I are developers of ARM. We are working to enable Cloud-hypervisor on AArch64. Now an initial version is ready, although all functionalities are not supported. 

As a minimal implementation, it supports a small set of devices: including serial device, RTC and Virtio devices with MMIO transport option. We are about to submit the code as a starting point, all other devices and functionalities will be added in steps.

Before coding, we made an analysis of the gap to fully support AArch64, which could be taken as a TODO list: (updated)

- [x] Build on AArch64: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1168
  - Fix build warnings and errors
  - Add cross-build workflows in PR Check
- [x] FDT and architecture specific devices: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1223
- [x] Device Manager:
  - Hide Port-IO
  - Add legacy devices to MMIO bus.
- [x] Allocators:
  - GsiAllocator: Update IRQ and GSI allocation algorithm.
- [x] Ioapic: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1232
  - Now Ioapic is directly referenced in device manager, but it is architecutre specific. A way to improve could be refactoring: introduce a architecture agnostic Interrupt Controller trait. Different architecture provides its own implementation: for X86 it's Ioapic; for Aarch64 it would be GIC.
- [x] Booting:
  - [x] A fundamental requirement for Aarch64 is: VCPU's have to be created before GIC. But in current Cloud-Hypervisor the VCPU's are created in late stage of booting. We need to refactor the steps in booting a guest to work with both architecture at first: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1238
  - [x] And populate Arm64 specific booting source code: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1126
- [x] Virtio:
  - [x] MMIO transport: Add device info to FDT
  - [x] PCI transport: Add PCI bus info to FDT
- [x] Migration:
  - Enable dependencies for AArch64: kvm-bindings, kvm-ioctls. 
- [x] Vhost-user-*:
  - To be tested and determined.
- [x] VFIO:
  - To be tested and determined.
- [x] CI:
  - Update Dockerfile.
  - Get guest disk images for integration tests.
  - Add and setup CI machines.
  - Enable Aarch64 CI.

**Comment by michael2012z** [comment]
With PR https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1126, now Cloud-hypervisor is enabled on AArch64 with a minimal functionality set.  Follow this [guide](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/arm64.md) if you want to taste.

Next we will focus on:
- Setup CI
- Support PCI
- Support Migration
- ...

**Comment by rbradford** [comment]
Hey @michael2012z @MrXinWang Just checking in to see if the todo list above is still correct.  I know you folks have been making lots of excellent progress on this recently.

**Comment by MrXinWang** [comment]
Hi @rbradford , recently me and @michael2012z had a discussion about the gap between arm64 and x86_64, it seems that arm64 are only missing these parts:

- vfio
- iommu (or SMMU for arm64)
- hotplug
- CPU Topology

Compared to other three, CPU Topology is rather small (but still on arm64 we need to support both ACPI and device tree).

**Comment by MrXinWang** [comment]
Hi @rbradford @michael2012z

With https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3513, we have finished all planned work in this issue. One thing we need to note that is currently the vfio framework is only verified by the `test_vfio_user` test case in our CI.

For now the only feature gap between x86_64 and AArch64 is the vCPU hotplug.

**Comment by rbradford** [comment]
@MrXinWang Cool. Is CPU hotplug possible with aarch64 in general? If not then this issue can be closed.

**Comment by MrXinWang** [comment]
> @MrXinWang Cool. Is CPU hotplug possible with aarch64 in general? If not then this issue can be closed.

It is (in a way), there are some custom implementations in kata-containers (https://github.com/kata-containers/kata-containers/pull/3292) but never merged to mainline, and also vCPU hotplug needs some kernel patches to support.

Maybe we can first investigate it.

**Comment by grass-lu** [comment]
@michael2012z @rbradford  hi， for aach64 ,hotplug pci device don't work , cloud you  help me , thanks.  the  discussion about it： https://github.com/cloud-hypervisor/cloud-hypervisor/discussions/5910
