### ISSUE TITLE
mptable overwrites ACPI table when boot vCPUS is >=41

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1132]
If `--cpus boot=41`  (or higher) is used the mptable corrupts the ACPI table by expanding over it. For some numbers e.g. 48 this in fact leads to an infinite boot cycle.

I propose only generating an mptable if not using ACPI.

**Comment by sameo** [comment]
`I propose only generating an mptable if not using ACPI.`

Definitely. We don't need both at the same time.
