### ISSUE TITLE
Improve VM introspection

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1167]
Through VM `info`, the user expects to get the information related to the running VM, which is partially true at the moment. Indeed, this command returns the VM config, but does not give all the information related to all the devices present in the system (CMOS, fwdebug, IOAPIC, ...). It neither provide the resources (address ranges, interrupts) associated with each device, nor the PCI topology and the placement of each device.

A lot of these missing information that a user can expect through a `vm.info` command can be made available now that the `DeviceManager` contains a `DeviceTree` which contains all these data.

**Comment by jcvenegas** [comment]
Hi, I will start to take a look to this, I will document the high level requirements and possible implementation details to get feedback.

**Comment by sboeuf** [comment]
https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1862 is a subtask of this issue.
