### ISSUE TITLE
ci: Fix test_snapshot_restore to support multiple vCPUs

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1176]
The integration test `test_snapshot_restore` behaves inconsistently when using more than one vCPU. We need to investigate this issue and find out what's going wrong wrt the multi-vCPU support along with snapshot/restore.

**Comment by sboeuf** [comment]
I found out that we get this kind of error from the guest kernel when the restore takes longer than usual:
```
[   79.237583] rcu: INFO: rcu_sched detected stalls on CPUs/tasks:
[   79.244596] rcu:     1-...!: (0 ticks this GP) idle=ae0/0/0x0 softirq=1613/1613 fqs=0
[   79.249281] rcu:     2-...!: (1 GPs behind) idle=a18/0/0x0 softirq=2534/2535 fqs=0
[   79.255201] rcu: rcu_sched kthread starved for 14752 jiffies! g305 f0x0 RCU_GP_WAIT_FQS(5) ->state=0x402 ->cpu=1
[   79.259746] rcu: RCU grace-period kthread stack dump:
```

Looks like the vCPUs are not correctly restored.

**Comment by sameo** [comment]
> I found out that we get this kind of error from the guest kernel when the restore takes longer than usual

In the above logs, it looks like the CPU was stalled for a *long* time. So I guess it's not that the restore takes longer than usual, but rather that the restore completed as expected (and probably in a reasonable amount of time) but vCPUs were not restored properly and are stalling.

**Comment by sboeuf** [comment]
Yes definitely. But I don't know what's missing and why the vCPUs are stalling :-/
And problem is, I can't reproduce it when I run it manually. It's always through the CI.
