### ISSUE TITLE
Rely on rust-vmm/event-manager crate

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1183]
We should consider moving the Cloud-Hypervisor codebase to the [rust-vmm/event-manager](https://github.com/rust-vmm/event-manager/) crate as it should let us remove a lot of duplicated code that is abstracted directly through the crate.

**Comment by rbradford** [comment]
@sboeuf Do you think this is still useful? Would you consider writing up a plan or proposing a PR?

**Comment by sboeuf** [comment]
Let me have a look into the event-manager, I'll assess if this makes sense.
