### ISSUE TITLE
AArch64 CI Enablement

### ISSUE THREAD

**Issue by MrXinWang** [cloud-hypervisor/cloud-hypervisor#1263]
Creating this issue as an extended issue from #1125. AArch64 CI related stuff can be discussed here.

### Background

The cloud-hypervisor community is accepting PRs to enable AArch64. Currently we are using a github action to cross-build AArch64 code on x86_64 machine in order to make sure these AArch64 PRs can be built. As these PRs are gradually being merged, it is necessary to set up AArch64 CI in order to test everything on real AArch64 platform.

### Current AArch64 CI Status

- [x] CI Machine: https://github.com/WorksOnArm/cluster/issues/205
- [x] Development container for AArch64: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1403
- [x] Unit test infrastructure: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1351
- [x] Integration test infrastructure: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1395
- [x] AArch64 cloud images
- [x] AArch64 musl toolchain support for rust: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1437
- [x] Add specific unit test cases for AArch64 
- [x] Add specific integration test cases for AArch64: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1463 https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1519 https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1522

**Comment by rbradford** [comment]
Yes I imagine you would need a completely different version of the integration test script as well as some refactoring and a subset of the integration test suite itself.

Our Jenkins CI can be configured to SSH into a machine to run the the script for each build.

**Comment by MrXinWang** [comment]
@rbradford Yes indeed. Separating arm64 integration test script will be good to make the code more readable.

One thing I noticed during my local test is that the clear linux distribution is x86_64 only, and we probably cannot test it in arm64 integration test. Also similarly to the libfdt-dev problem in https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1223#discussion_r43577346. The official ubuntu and alpine cloud image releases (for example [18.04](https://cloud-images.ubuntu.com/releases/bionic/)) varies very quickly. It seems that we need to also pin these images (like the community is doing now) to make sure the versions and UUIDs of the image are always the same, as they are hardcoded in current integration test scripts.

**Comment by rbradford** [comment]
I would focus on Ubuntu bionic and focal. As you point out consistency of test image is important.

**Comment by MrXinWang** [comment]
WorksOnArm/cluster [#205](https://github.com/WorksOnArm/cluster/issues/205) created for CI machine.

**Comment by MrXinWang** [comment]
An update: WorksOnArm/cluster [#205](https://github.com/WorksOnArm/cluster/issues/205) has been approved and I will contact the community maintainers as soon as I get the access of the machine.

**Comment by MrXinWang** [comment]
Hi @rbradford @sboeuf @sameo @michael2012z ! I've received an Ampere eMAG 8180 32-core @ 3.0Ghz, with 128GB RAM, 480GB SSD and 2 x 10Gbps Bonded Ports NIC bare metal AArch64 machine for the cloud-hypervisor community CI. For the CI enablement, as #1318 has been merged, I came up with 3 plans as following steps and I am wondering which of them you think is preferred:

1. Keep the current cross-build github action until any problem happens (for example the libfdt workaround will fail because the removal of specific version of libfdt-dev), and run the rest of CI (unit tests, integration tests, etc...) in the Jenkins.

2. Remove the cross-build github action first, and assign a pure AArch64 build github action to this machine using [github self-hosted runners](https://help.github.com/en/actions/hosting-your-own-runners). The other part of CI will be the same as 1. This (I think) will require the community maintainers to configure the github action part. Also we have done a very simple test in our own forked repository, and it seems that the self-hosted runner is not that stable as expected.

3. Put everything including the AArch64 build in Jenkins, and this will probably require us to maintain two separated CI scripts or code, and we cannot get the benefit of github action as mentioned in https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1223#discussion_r435782306.

Also does anyone need the access to this AArch64 machine? I think I also should give the access to this machine to the community. Therefore if you can provide your SSH public key and I can give access to you. Thanks!

**Comment by rbradford** [comment]
@MrXinWang I did some research on self-hosted runners for GitHub Actions and they do discourage the use on public repositories as there can be security issues. I would recommend we go with solution *3* (and keep *1* for now.)

You can see how we did that on NEMU here: https://github.com/intel/nemu/blob/topic/virt-x86/Jenkinsfile#L20

The first step is to construct a script that can be run to to run the tests (unit tests for now, but later using an integration test.)

I can add the machine to Jenkins as a fixed node once you have a working script that you want to run.

**Comment by MrXinWang** [comment]
@rbradford Thanks so much! The AArch64 unit tests can be run in the same way as x86_64, so the working script is already there as [run_unit_tests.sh](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/scripts/run_unit_tests.sh). 

I haven't check the code for running Jenkins so far but I think if x86_64 unit tests are triggered by
`./scripts/dev_cli.sh tests --unit`, there should be no difference between x86_64 and AArch64.

**Comment by rbradford** [comment]
All the checkboxes are closed on this issue so I think it can be resolved!
