### ISSUE TITLE
Should all virtio devices update its mem of EpollHandler?

### ISSUE THREAD

**Issue by teawater** [cloud-hypervisor/cloud-hypervisor#1264]
I am working on virtio-balloon in https://github.com/cloud-hypervisor/cloud-hypervisor/pull/947 .
And I found that clh balloon will crash after memory hotplug.
I think the reason is balloon.rs need use BalloonEpollHandler.mem to get the region of the memory.  And use the region get the real address of the memory.
After memory hotplug, the device_manager will add the new region to itself.
```
            if let Some(new_region) = &new_region {
                self.device_manager
                    .lock()
                    .unwrap()
                    .update_memory(&new_region)
                    .map_err(Error::DeviceManager)?;

                let memory_config = &self.config.lock().unwrap().memory;
                match memory_config.hotplug_method {
                    HotplugMethod::Acpi => {
                        self.device_manager
                            .lock()
                            .unwrap()
                            .notify_hotplug(HotPlugNotificationFlags::MEMORY_DEVICES_CHANGED)
                            .map_err(Error::DeviceManager)?;
                    }
                    HotplugMethod::VirtioMem => {}
                }
            }
```
The device can updated its mem with update_memory. For example:
```
    fn update_memory(&mut self, mem: &GuestMemoryMmap) -> std::result::Result<(), crate::Error> {
        update_mem_table(&mut self.vhost_user_blk, mem).map_err(crate::Error::VhostUserUpdateMemory)
    }
```

But I found that mem of EpollHandler is not updated.
If guest kernel use hotplug memory as the virtio transport memory, clh will cannot get the right date without new region info.

Should all virtio devices update its mem of EpollHandler?

**Comment by rbradford** [comment]
Code running inside the vmm (vhost-user devices are separate and they have `update_memory()` as part of the protocol) should never store a `GuestMemory` or `GuestMemoryMmap` and instead should fetch it every time it needs it from the stored `GuestMemoryAtomic`.

Have you reproduced this issue with another type of virtio device or is this exclusively related to virtio-balloon?

**Comment by sboeuf** [comment]
There's no need to do any special handling regarding the `GuestMemoryMmap` since it is encapsulated inside a `GuestMemoryAtomic<GuestMemoryMmap>`.
