### ISSUE TITLE
Run without CAP_NET_ADMIN

### ISSUE THREAD

**Issue by kylecarbs** [cloud-hypervisor/cloud-hypervisor#1273]
In [clone and build](https://github.com/cloud-hypervisor/cloud-hypervisor#clone-and-build) I see it's required to setup the tap interface.

Is it a strict requirement? Or is there a workaround?

**Comment by sboeuf** [comment]
>Is it a strict requirement? Or is there a workaround?

This is the best way to do it. Otherwise, you would use `root` privileges, which is far worse than `CAP_NET_ADMIN`.

**Comment by rbradford** [comment]
@kylecarbs You should be able to create and configure the tap device outside and then pass it in which means you do not need to run your binary with that privilege.

```
sudo ip tuntap add name tap0 mode tap
sudo ifconfig tap0 192.168.249.1 netmask 255.255.255.0
target/debug/cloud-hypervisor --serial tty --console off --kernel ~/src/rust-hypervisor-firmware/target/target/release/hypervisor-fw --disk path=~/workloads/clear-33190-kvm.img --api-socket=/tmp/api --memory size=1G --net tap=tap0 -v
```

However it looks like #1177 has broken this. So there is a new issue opened at #1274 which we use to try and resolve this issue.

**Comment by kylecarbs** [comment]
Awesome, thanks all!

I'll close this issue in favor of #1274.
