### ISSUE TITLE
Add support for vhost-user-blk

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#130]
In order to let cloud-hypervisor user select their virtio blk backend, we need to support vhost-user-blk.

Subtask from #7

**Comment by sameo** [comment]
I have a similar comment as in https://github.com/intel/cloud-hypervisor/issues/8#issuecomment-517682967 :

We want to have our own, Rust based, vhost-user-blk backend and not use SPDK by default.

**Comment by sameo** [comment]
cc @yangzhon

**Comment by sboeuf** [comment]
This has been solved, with the support of vhost-user-blk to cloud-hypervisor, and additionally with the introduction of a Rust based vhost-user-blk daemon.
