### ISSUE TITLE
Support PVH boot

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#131]
See https://github.com/rust-vmm/linux-loader/issues/3 and https://xenbits.xen.org/docs/unstable/misc/pvh.html

**Comment by aljimenezb** [comment]
Have working patches for this issue and https://github.com/rust-vmm/linux-loader/issues/3. ETA early next week

**Comment by sboeuf** [comment]
Oh that's cool :)
