### ISSUE TITLE
Complete Snapshot & Restore

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1312]
Finish the outstanding work so that this feature can be considered "complete".

This is the master issue. Here is the list of components missing snapshot/restore support:

- [x] `virtio-mem` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1595
- [x] `virtio-balloon` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1598
- [x] `vhost-user` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1599
- [x] `versioning` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1600

**Comment by rbradford** [comment]
@sboeuf What do you feel is missing on this before we can close this issue.

**Comment by sboeuf** [comment]
From the top of my head:
- `vhost-user` (if technically possible)
- `virtio-mem`
- `SGX`

**Comment by rbradford** [comment]
- VFIO devices

**Comment by sboeuf** [comment]
I thought we had agreed that VFIO devices were too complex to be handled through snapshot/restore?

**Comment by rbradford** [comment]
> I thought we had agreed that VFIO devices were too complex to be handled through snapshot/restore?

Yup, my mistake.

**Comment by sboeuf** [comment]
This is the master issue. Here is the list of components missing snapshot/restore support:
- [ ] `virtio-mem` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1595
- [ ] `virtio-balloon` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1598
- [ ] `vhost-user` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1599
- [ ] `SGX` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1597
- [ ] `versioning` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1600

**Comment by likebreath** [comment]
Looks like the items are all completed.
