### ISSUE TITLE
Windows guest support study

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#132]
2 high level steps:

* [ ] Define which windows we want to support
* [ ] Explore both the rust-hypervisor-firmware and the cloud-hypervisor consequences

**Comment by sameo** [comment]
cc @rbradford @sboeuf @chao-p

**Comment by sboeuf** [comment]
That sounds like an interesting task :)

**Comment by sboeuf** [comment]
@rbradford I know you started looking into this a few weeks ago.
Could you please summarize what you gathered from your researches on this topic?

**Comment by rbradford** [comment]
We now have early support for booting Windows 2019 Server on Cloud Hypervisor.
