### ISSUE TITLE
Extract the vhost-user backend code into its own repo

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#1361]
New repo created at: https://github.com/cloud-hypervisor/vhost-user-backend

**Comment by arronwy** [comment]
Hi @sameo @sboeuf, we found vhost-user-backend have dependency on internal vm-virtio crate which have many diffs compared with current rust-vmm version. vhost-user-backend will build on an external repo maybe vm-virtio ch branch in cloud hypervisor?  Gerry submitted two PRs: https://github.com/rust-vmm/vm-virtio/pulls which may fix the vhost-user-backend building issue, but when cloud hypervisor use this vhost-user-backend, there will be two versions of vm-virtio, do we have any plan to submit our internal vm-virtio patches to upstream or vm-virtio ch branch？

**Comment by rbradford** [comment]
We should split our vm-virtio crate into two. One for the general queue management aspect which is VMM agnostic (and is the direction rust-vmm vm-virtio) is going in and another with the implementation of the devices which is VMM specific.

After that split then we can try and move to rust-vmm vm-virtio for the virtio-devices crate and the vhost-user-backend crate.

**Comment by sameo** [comment]
> We should split our vm-virtio crate into two. One for the general queue management aspect which is VMM agnostic (and is the direction rust-vmm vm-virtio is going in)

I wouldn't say the direction is completely clear, as this was discussed (Without reaching any agreement...) in the Bucharest meeting (https://github.com/rust-vmm/community/issues/81). But I definitely agree the crate should be split. Do you agree the "core" virtio crate should also include the `VirtioDevice` trait?

> and another with the implementation of the devices which is VMM specific.

One suggestion from the community was to have a single `devices` crate including legacy and virtio devices.

> After that split then we can try and move to rust-vmm vm-virtio for the virtio-devices crate and the vhost-user-backend crate.

The rust-vmm vm-virtio is behind us in terms of functionalities, so we should upstream our changes first before we can switch to it.

One possible approach could be:

1. Split the internal cloud-hypervisor vm-virtio crate into `vm-virtio` and `virtio-devices` (or use the `devices` crate)
1. Rebase cloud-hypervisor `vm-virtio` crate on top of rust-vmm vm-virtio
1. Create a `clh` branch in https://github.com/cloud-hypervisor/vm-virtio to hold that rebase
1. Switch cloud-hypervisor to use https://github.com/cloud-hypervisor/vm-virtio/tree/clh
1. Upstream https://github.com/cloud-hypervisor/vm-virtio/tree/clh
1. Switch cloud-hypervisor to the rust-vmm vm-virtio crate.

@arronwy The `vhost-user-backend` could follow the same dependencies switch steps (steps 4 and 6) while initially depending on cloud-hypervisor's internal vm-virtio crate.

**Comment by rbradford** [comment]
> > We should split our vm-virtio crate into two. One for the general queue management aspect which is VMM agnostic (and is the direction rust-vmm vm-virtio is going in)
> 
> I wouldn't say the direction is completely clear, as this was discussed (Without reaching any agreement...) in the Bucharest meeting ([rust-vmm/community#81](https://github.com/rust-vmm/community/issues/81)). But I definitely agree the crate should be split. Do you agree the "core" virtio crate should also include the `VirtioDevice` trait?
> 

Yes, this is exactly what I was thinking of the way the split would work.

> > and another with the implementation of the devices which is VMM specific.
> 
> One suggestion from the community was to have a single `devices` crate including legacy and virtio devices.

The device implementations are very very strongly coupled to the VMM making decisions about what traits to implement e.g. Migratable or how to actually do the underlying work. I don't think this is something to think about right now.

> 
> > After that split then we can try and move to rust-vmm vm-virtio for the virtio-devices crate and the vhost-user-backend crate.
> 
> The rust-vmm vm-virtio is behind us in terms of functionalities, so we should upstream our changes first before we can switch to it.
> 
> One possible approach could be:
> 
>     1. Split the internal cloud-hypervisor vm-virtio crate into `vm-virtio` and `virtio-devices` (or use the `devices` crate)
> 
>     2. Rebase cloud-hypervisor `vm-virtio` crate on top of rust-vmm vm-virtio
> 
>     3. Create a `ch` branch in https://github.com/cloud-hypervisor/vm-virtio to hold that rebase
> 
>     4. Switch cloud-hypervisor to use https://github.com/cloud-hypervisor/vm-virtio/tree/ch
> 
>     5. Upstream https://github.com/cloud-hypervisor/vm-virtio/tree/ch
> 
>     6. Switch cloud-hypervisor to the rust-vmm vm-virtio crate.
> 
> 

(I edited your comment to use the correct branch name for our forks clh -> ch) I think this is fine and is what I was trying to propose when I said to split the current vm-virtio crate.

> @arronwy The `vhost-user-backend` could follow the same dependencies switch steps (steps 4 and 6) while initially depending on cloud-hypervisor's internal vm-virtio crate.

**Comment by jiangliu** [comment]
> We should split our vm-virtio crate into two. One for the general queue management aspect which is VMM agnostic (and is the direction rust-vmm vm-virtio is going in) and another with the implementation of the devices which is VMM specific.
> 
> After that split then we can try and move to rust-vmm vm-virtio for the virtio-devices crate and the vhost-user-backend crate.

We have done the same thing, actually we only use the vm-virtio/queue and do not use vm-virtio/device.

**Comment by rbradford** [comment]
I have a branch ready to switch to https://github.com/rust-vmm/vhost-user-backend but it depends on rust-vmm/vm-virtio#32

**Comment by rbradford** [comment]
vhost-user-backend is already in it's own repo and the issue to track to migrating to it is #2055
