### ISSUE TITLE
Sandbox the VMM

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#14]
To increase the security of the VMM process and threads, it needs to be properly isolated. This can happen through several mechanisms, where seccomp can be one of them.

**Comment by rbradford** [comment]
We have seccomp for everything now. Is there any other sandboxing we want to do?

**Comment by sboeuf** [comment]
I'm not sure. @sameo is there any you think about that would make sense for a VMM to enable?
