### ISSUE TITLE
Investigate how to support multiple PCI buses

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1400]
Supporting multiple PCI buses lets us have more than 32 device.

**Comment by rbradford** [comment]
I don't think we have a use case that requires this so we can close it for now.

**Comment by thillux** [comment]
Thanks for reopening this issue. I have a usecase which would possibly need more than 32 PCI devices.

I'm running a VPN gateway with a control plane VM managed by chv. Inside this VM multiple layer 3 forwarding domains (VRFs) can be used. Each VRFs gets assigned >= 4 vhost-user-net devices, which each use one BDF. Therefore the number of supported BDFs directly corresponds to the number of supported VRFs in my usecase.

**Comment by thillux** [comment]
Another use case would arise if using many virtual function (VF) representors on top of a switch inside a chv VM.

**Comment by thillux** [comment]
Great! Thanks a lot for working on this.
