### ISSUE TITLE
vm-virtio crate split

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#1411]
It would make sense to split the `vm-virtio` crate in 2 separate crates, roughly mapping the 2 main parts of the [VIRTIO spec](https://docs.oasis-open.org/virtio/virtio/v1.1/csprd01/virtio-v1.1-csprd01.html):

- The `vm-virtio` crate would only contain the virtio queue implementation and device trait definition
- The virtio devices implementation would be extracted out of the `vm-virtio` crate into e.g. a `devices` crate module.

There are several reasons why this split makes sense:

1. Both the vhost-user related crates and the `devices` one will depend on the core virtio implementation, as opposed to the current architecture where we end up having vhost-user depending on a crate that contains other virtio devices implementation.
1. This will match with the upstream `vm-virtio` crate that only contains virtio queues and the device trait. Not splitting the crate would make it really difficult for us to upstream our virtio changes and to eventually depend on the upsream rust-vmm virtio implementation
1. The virtio devices implementation (transport, actual devices, code architecture and optimization) is more of a VMM design decision and could depend on other VMM specific interfaces and APIs. Although there could be a simple, canonical upstream implementation for them, it should be optional and should not come locked with the virtio queue implementation.

Since part of the reason for the split is to be able to submit those changes upstream, the new `vm-virtio`crate should ideally be rebased on top of the [rust-vmm virtio crate](https://github.com/rust-vmm/vm-virtio).

**Comment by sameo** [comment]
cc @rbradford @sboeuf @jiangliu

**Comment by rbradford** [comment]
I've got a PR at #1412 (done before this issue was opened).

> It would make sense to split the `vm-virtio` crate in 2 separate crates, roughly mapping the 2 main parts of the [VIRTIO spec](https://docs.oasis-open.org/virtio/virtio/v1.1/csprd01/virtio-v1.1-csprd01.html):
> 
>     * The `vm-virtio` crate would only contain the virtio queue implementation and device trait definition
> 
>     * The virtio devices implementation would be extracted out of the `vm-virtio` crate into e.g. a `devices` crate module.
>

Currently the PR puts this into a new `virtio-devices` crate.

> 
> There are several reasons why this split makes sense:
> 
>     1. Both the vhost-user related crates and the `devices` one will depend on the core virtio implementation, as opposed to the current architecture where we end up having vhost-user depending on a crate that contains other virtio devices implementation.
> 

This is ambiguous. To be more precise:


* `vhost_user-_backend` which is the crate for implementing backends only depends on the new `vm-virtio::queue` and the `vhost-rs` crates

* `vhost_user_{block, net, fs}` depend on `virtio-devices`, `vm-virtio` and `vhost_user_backend`

>     2. This will match with the upstream `vm-virtio` crate that only contains virtio queues and the device trait. Not splitting the crate would make it really difficult for us to upstream our virtio changes and to eventually depend on the upsream rust-vmm virtio implementation
> 

The big difference between what you're proposing here and in PR #1412 is that the `VirtioDevice` trait is not in the vm-virtio crate as our version leaks VMM and device specific details.
