### ISSUE TITLE
Building / choosing different flavors of Cloud Hypervisor

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#1421]
Per my understanding, cloud hypervisor only supports one type of hypervisor in a single binary. Is the plan here to introduce features like `kvm` and `hyperv` to guard what code gets compiled?

Also somewhat related, I notice code like the following:

```
let kvm = hypervisor::kvm::KvmHypervisor::new().unwrap();
let hv: Arc<dyn hypervisor::Hypervisor> = Arc::new(kvm);
```

It seems a bit out of place to me. If only one type of hypervisor is supported at a time, can we do the following instead?

```
let hv = Arc::new(hypervisor::Hypervisor::new().unwrap());
```

That is, we shouldn't need to specify what hypervisor to use in code, given we already know in compile time what flavor we want.

**Comment by liuw** [comment]
Something like this: https://github.com/liuw/cloud-hypervisor/commit/c3a9cde4bd64e86fbdb2381e92cf6d6c5c687a9d

**Comment by sameo** [comment]
@liuw We don't plan to dynamically support multiple hypervisors. The hypervisor selection should be a build time decision and feature guarded.
