### ISSUE TITLE
Migrate to fuse-backend-rs crate

### ISSUE THREAD

**Issue by liubogithub** [cloud-hypervisor/cloud-hypervisor#1431]
Migrate to [fuse-backend-rs](https://github.com/cloud-hypervisor/fuse-backend-rs) which has everything that rust virtiofsd ("vhost-user-fs") needs.

**Comment by liubogithub** [comment]
I'll look into this if no one has done so.

**Comment by sboeuf** [comment]
@sameo @rbradford do we want CH to move to this crate? Since I don't think it's gonna be needed from CH, I'd rather keep pointing to `vhost-user-fs` crate directly as it is smaller.

**Comment by liubogithub** [comment]
> @sameo @rbradford do we want CH to move to this crate? Since I don't think it's gonna be needed from CH, I'd rather keep pointing to `vhost-user-fs` crate directly as it is smaller.

**Comment by rbradford** [comment]
Cloud Hypervisor is sticking to vhost-user-fs.
