### ISSUE TITLE
Using KVM feature guard in arch crate

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#1439]
There is a recently added `kvm` feature guard in the `hypervisor` crate. My attempt to use it in `arch` crate is not very satisfactory.

The problem is that `arch` only needs `hypervisor` in its test cases, because that's when it needs to create VMs. It seems a bit heavy-handed to me if we need to define a `kvm` feature guard for the `arch` crate. On the other hand, without defining `kvm` in `arch` makes test cases fail.

The example code is https://github.com/liuw/cloud-hypervisor/commit/e3a98b7c64b5ab40000752a54021d6033816b8fa. I would like to hear people's opinions on how to handle this.

**Comment by rbradford** [comment]
Maybe the solution is to move those tests from the arch crate to the hypervisor or vm crate.

**Comment by russell-islam** [comment]
Moving the test cases to hypervisor will loose the namespace. For example in the arch module we have test cases for interrupts , gic etc. wherein the hypervisor we don't have that many namespaces.

**Comment by liuw** [comment]
@russell-islam I experimented a bit with moving the test cases to `vmm` crate. The output for the moved test cases looks like:

```
running 23 tests
...
test cpu::tests::test_setup_regs ... ok
test cpu::tests::test_setup_msrs ... ok
test cpu::tests::test_setup_fpu ... ok
test cpu::tests::test_setlint ... ok
test vm::test_vm ... ok
test cpu::tests::test_setup_sregs ... ok
```

Is this not good enough to you?

**Comment by liuw** [comment]
BTW, if you really want more nested name spaces, one way of doing is to use modules inside test module.

```
mod test {
    mod foo {
        test1
    }
    mod bar {
        test2
    }
    test3
}
```

Should give you something like:
```
XXX::tests::foo::test1
XXX::tests::bar::test2
XXX::tests::test3

**Comment by liuw** [comment]
See #1440
