### ISSUE TITLE
vhost-user: Implement VHOST_USER_PROTOCOL_F_CONFIGURE_MEM_SLOTS

### ISSUE THREAD

**Issue by dagrh** [cloud-hypervisor/cloud-hypervisor#1460]
The vhost user protocol has a limit of ~8 memory slots it can handle; that's an issue when you add lots of DIMMs, e.g. in Kata when you have lots of containers in a pod: (Related to https://github.com/kata-containers/runtime/issues/2795 )
QEMU recently got support for VHOST_USER_PROTOCOL_F_CONFIGURE_MEM_SLOTS  which does away with the limit on the slots.
We need to get the same feature.

Easiest way to trigger it is to start a vhost_user_fs and then connect a qemu with:
```
   -m 2G,maxmem=16G,slots=16 -object memory-backend-memfd,id=mem1,size=256M,share=on -device pc-dimm,id=dimm1,memdev=mem1 -object memory-backend-memfd,id=mem2,size=256M,share=on -device pc-dimm,id=dimm2,memdev=mem2 -object memory-backend-memfd,id=mem3,size=256M,share=on -device pc-dimm,id=dimm3,memdev=mem3 -object memory-backend-memfd,id=mem4,size=256M,share=on -device pc-dimm,id=dimm4,memdev=mem4 -object memory-backend-memfd,id=mem5,size=256M,share=on -device pc-dimm,id=dimm5,memdev=mem5 -object memory-backend-memfd,id=mem6,size=256M,share=on -device pc-dimm,id=dimm6,memdev=mem6 -object memory-backend-memfd,id=mem7,size=256M,share=on -device pc-dimm,id=dimm7,memdev=mem7 -object memory-backend-memfd,id=mem8,size=256M,share=on -device pc-dimm,id=dimm8,memdev=mem8
```

**Comment by rbradford** [comment]
@slp I think this should be moved....

**Comment by slp** [comment]
@rbradford Yes, it'd be nice to have this one in https://github.com/rust-vmm/vhost. Do you have the possibility to move this issue there to avoid creating it from scratch?

**Comment by rbradford** [comment]
No, GitHub does not let you move across organisations.

**Comment by slp** [comment]
@rbradford Ouch. Well, I created a new issue manually https://github.com/rust-vmm/vhost/issues/17

I think this one can be closed.
