### ISSUE TITLE
The Hypervisor cfg #[cfg(feature = "kvm")] may lead to compile failed on AARCH64 platform!

### ISSUE THREAD

**Issue by Apokleos** [cloud-hypervisor/cloud-hypervisor#1469]
Problem Description:
When I complile the newest code from the registry on AARCH64 platform, it fails! 

Operations as below：
```
root@hacker:/home/CLOUDH/cloud-hypervisor# 
root@hacker:/home/CLOUDH/cloud-hypervisor# cargo version
cargo 1.44.1 (88ba85757 2020-06-11)

root@hacker:/home/CLOUDH/cloud-hypervisor# git describe
v0.8.0-236-gd80e383

root@hacker:/home/CLOUDH/cloud-hypervisor# cargo build --no-default-features --features "mmio"
   Compiling hypervisor v0.1.0 (/home/RustProjects/cloud-hypervisor/hypervisor)
error[E0425]: cannot find value `hv` in this scope
  --> hypervisor/src/lib.rs:53:17
   |
53 |     Ok(Arc::new(hv))
   |                 ^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `hypervisor`.

To learn more, run the command again with --verbose.
```

But， when I shield the `#[cfg(feature = "kvm")]` ,and then do the compiling, it works fine. 
So, In my test  `#[cfg(feature = "kvm")]` in hypervisor/src/lib.rs may cause compiling failure.

I do not know why!

My solution, shield the `#[cfg(feature = "kvm")]` as below:
```
pub fn new() -> std::result::Result<Arc<dyn Hypervisor>, HypervisorError> {
    //#[cfg(feature = "kvm")]
    let hv = kvm::KvmHypervisor::new()?;

    Ok(Arc::new(hv))
}
```
`

**Comment by sameo** [comment]
You have to build with the `kvm` feature enabled:

```
root@hacker:/home/CLOUDH/cloud-hypervisor# cargo build --no-default-features --features "mmio,kvm"
```

I'd advise using the `dev_cli.sh` tool to build Cloud Hypervisor, as it's always using the right default build values and options.
If you can't use it, you can see it as a reference for choosing the correct build commands.

**Comment by Apokleos** [comment]
Thank you @sameo
I have done it successfully as your advice.  

I followed the [docs/arm64.md](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/arm64.md) before. Maybe It should be updated now.

**Comment by sboeuf** [comment]
>I followed the docs/arm64.md before. Maybe It should be updated now.

/cc @michael2012z @MrXinWang

**Comment by MrXinWang** [comment]
@Apokleos @sboeuf  Thanks for noticing this :) PR to fix this is on the way.
