### ISSUE TITLE
test_vhost_user_blk_* test cases random failure on AArch64

### ISSUE THREAD

**Issue by michael2012z** [cloud-hypervisor/cloud-hypervisor#1505]
I am trying to enable more integration test cases on AArch64, but found some `vhost_user_blk` related cases quite prone to fail.
The failure was random. And it was same with either PCI or MMIO. 

I managed to capture some log files when the problem happened.
[ch.cs0WGO9L4gHA.log.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/4980339/ch.cs0WGO9L4gHA.log.log)
[ch.cs0WGO9L4gHA.serial.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/4980340/ch.cs0WGO9L4gHA.serial.log)

The test cases failed due to fail to connect the guest:

> ERROR: ip: 192.168.7.2, command: lsblk | grep vdc | grep -c 16M, error: Connection(Os { code: 113, kind: Other, message: "No route to host" })

The VMM log was short, it looks like the virtio devices stopped or failed to start somehow. (While the serial log looks quite normal.)

> cloud-hypervisor: 2.313043ms: INFO:vmm/src/memory_manager.rs:757 -- Created userspace mapping: 80000000 -> ffff8c000000 20000000
cloud-hypervisor: 76.344619ms: INFO:vmm/src/cpu.rs:762 -- Request to create new vCPUs: desired = 2, max = 2, allocated = 0, present = 0
cloud-hypervisor: 76.47657ms: INFO:vmm/src/cpu.rs:701 -- Creating vCPU: cpu_id = 0
cloud-hypervisor: 76.614671ms: INFO:vmm/src/cpu.rs:701 -- Creating vCPU: cpu_id = 1
cloud-hypervisor: 80.120523ms: INFO:vmm/src/cpu.rs:880 -- Starting vCPUs: desired = 2, allocated = 2, present = 0
cloud-hypervisor: 80.221124ms: INFO:vmm/src/cpu.rs:798 -- Starting vCPU: cpu_id = 0
cloud-hypervisor: 80.3737ms: INFO:vmm/src/cpu.rs:798 -- Starting vCPU: cpu_id = 1
cloud-hypervisor: 422.357135ms: INFO:virtio-devices/src/block.rs:459 -- Changing cache mode to writeback
cloud-hypervisor: 423.717645ms: INFO:vm-virtio/src/queue.rs:715 -- Needs notification: true
cloud-hypervisor: 424.537627ms: INFO:vm-virtio/src/queue.rs:704 -- used_event = 1 used_idx = 2 old_idx = 1
cloud-hypervisor: 424.682553ms: INFO:vm-virtio/src/queue.rs:715 -- Needs notification: true
cloud-hypervisor: 425.474509ms: INFO:vm-virtio/src/queue.rs:704 -- used_event = 2 used_idx = 3 old_idx = 2
cloud-hypervisor: 425.56861ms: INFO:vm-virtio/src/queue.rs:715 -- Needs notification: true
cloud-hypervisor: 426.326891ms: INFO:vm-virtio/src/queue.rs:704 -- used_event = 3 used_idx = 4 old_idx = 3
cloud-hypervisor: 426.420941ms: INFO:vm-virtio/src/queue.rs:715 -- Needs notification: true
cloud-hypervisor: 427.176347ms: INFO:vm-virtio/src/queue.rs:704 -- used_event = 4 used_idx = 5 old_idx = 4
cloud-hypervisor: 427.268473ms: INFO:vm-virtio/src/queue.rs:715 -- Needs notification: true
cloud-hypervisor: 428.19088ms: INFO:vm-virtio/src/queue.rs:704 -- used_event = 5 used_idx = 6 old_idx = 5
cloud-hypervisor: 428.289156ms: INFO:vm-virtio/src/queue.rs:715 -- Needs notification: true
cloud-hypervisor: 428.481932ms: INFO:vm-virtio/src/queue.rs:704 -- used_event = 6 used_idx = 7 old_idx = 6
cloud-hypervisor: 428.563858ms: INFO:vm-virtio/src/queue.rs:715 -- Needs notification: true
cloud-hypervisor: 428.77191ms: INFO:vm-virtio/src/queue.rs:704 -- used_event = 7 used_idx = 8 old_idx = 7
cloud-hypervisor: 428.85521ms: INFO:vm-virtio/src/queue.rs:715 -- Needs notification: true
cloud-hypervisor: 429.028337ms: INFO:vm-virtio/src/queue.rs:704 -- used_event = 8 used_idx = 9 old_idx = 8
cloud-hypervisor: 429.109937ms: INFO:vm-virtio/src/queue.rs:715 -- Needs notification: true
cloud-hypervisor: 429.725267ms: INFO:vm-virtio/src/queue.rs:704 -- used_event = 9 used_idx = 10 old_idx = 9
cloud-hypervisor: 429.818068ms: INFO:vm-virtio/src/queue.rs:715 -- Needs notification: true
cloud-hypervisor: 438.620611ms: INFO:virtio-devices/src/block.rs:459 -- Changing cache mode to writeback
cloud-hypervisor: 440.967204ms: INFO:vm-virtio/src/queue.rs:715 -- Needs notification: true

**Comment by michael2012z** [comment]
The failure was seen on test_vhost_user_net_* cases as well. In a local server, the possibility to trigger the fault was about 1/5.

But after changing the container networking `bridge` mode (https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1511), I haven't been able to capture the error in about 40 runs. The problem seems related to container environment.

**Comment by rbradford** [comment]
Seems to be resolved.
