### ISSUE TITLE
Ensure multiple ARM64 builds can be run in parallel

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1507]
The number of executors on this machine is now 2. Some state is shared between containers in the workloads directory. As such it might be a good idea to either stop sharing those files or "lock" the directory. The actual running of the integration tests should be already be safe.

**Comment by MrXinWang** [comment]
Hi @rbradford! Thanks for your help in adding another executor. We managed to implement the "lock" of the `workloads` directory in #1511 and it seems that both executor worked well. However we think the shared container network in this way (`--network=host`) will probably lead to another problem: For example, if 2 containers start at exactly same time,  the VMs in the integration test will probably be allocated same IP address and lead to conflicts? Do you think manually setting the container network would be better?

In the mean time, I will probably find a way to get another machine, and if so, this would be the best :)

**Comment by rbradford** [comment]
Yes `--network=host` is not a good idea. @sameo do you know why we do that?

**Comment by michael2012z** [comment]
I guess `VFIO` is the reason. I tested using `bridge` for container network, the test case `test_vfio` failed.

But at least `bridge` is an ideal solution for AArch64 in current stage.
