### ISSUE TITLE
Virtio-devices: Port to EpollHelper

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#1549]
@rbradford introduced `EpollHelper` recently to virtio-devices crate. This issue is to track status of porting the worker threads to EpollHelper.

- [x] balloon
- [x] block
- [x] block_io_uring
- [x] console
- [x] iommu
- [x] mem
- [x] net
- [x] pmem
- [x] rng
- [x] vhost_user
- [x] vsock

**Comment by likebreath** [comment]
@rbradford `virtio-console` is the only one that has seccomp but not yet ported to EpollHelper.

**Comment by likebreath** [comment]
As mentioned by @rbradford, along with the port to use EpollHelpers for our virtio-devices worker threads, we may also want to refactor the function `fn run(&mut self, paused: Arc<AtomicBool>)` to accept `seccomp_filters::Thread` and `seccomp:SecomppAction` as inputs. In this way, we can handle seccomp filter lookup and application in the `EpollHelpers::run()` function, instead of repeat the code in all worker threads. This can be a separate issue/refactoring.

**Comment by sboeuf** [comment]
Took care of this issue. All devices are now ported to the epoll helper.
