### ISSUE TITLE
virtio-block: Enable io_uring by default

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1561]
- [x] Needs 5.6 kernel (needs groovy in Azure to be updated)
- [x] Make io_uring default.
- [ ] Add option to force non-io_uring (for testing only)

**Comment by sboeuf** [comment]
Just posting one `fio` command for generating synchronous I/O 
```
sudo fio --filename=/dev/vdb --size=4G --direct=1 --rw=randrw --bs=4k --ioengine=sync --iodepth=1 --runtime=60 --numjobs=1 --time_based --group_reporting --name=iops-test-job --eta-newline=1
```
and the counterpart for asynchronous I/O
```
sudo fio --filename=/dev/vdb --size=4G --direct=1 --rw=randrw --bs=4k --ioengine=io_uring --iodepth=256 --runtime=60 --numjobs=1 --time_based --group_reporting --name=iops-test-job --eta-newline=1
```

**Comment by sboeuf** [comment]
Ubuntu Groovy Gorilla (20.10) should be released on Oct 22nd. After that, we should have some stable Azure images available to move the CI to it.
