### ISSUE TITLE
VmCreate(No such file or directory (os error 2))', src/main.rs:304:22

### ISSUE THREAD

**Issue by Ruilkyu** [cloud-hypervisor/cloud-hypervisor#1568]
RUST_BACKTRACE=full ./cloud-hypervisor/target/release/cloud-hypervisor --kernel ./hypervisor-fw --disk path=focal-server-cloudimg-amd64.raw --cpus boot=2 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VmCreate(No such file or directory (os error 2))', src/main.rs:304:22

**Comment by rbradford** [comment]
You haven't got a `/dev/kvm`. Please review your host configuration to ensure that you have KVM enabled and permission to open that file.
