### ISSUE TITLE
Define and implement versioning for snapshot/restore

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1600]
We must define and implement versioning to support proper snapshot/restore between different versions of Cloud-Hypervisor without breaking compatibility.

**Comment by sboeuf** [comment]
@sameo please edit the issue and extend it with all your thoughts on the topic :)

**Comment by rbradford** [comment]
Everything that I think we can version is now versioned. DeviceManager's `DeviceTree` isn't (based on Rust enums that are unsupported). The vCPU state is also not versioned but that comes directly from KVM and I don't think that needs to versioned as those structures are designed to be forward compatible.
