### ISSUE TITLE
Add Hypervisor specific VM info to snapshot and restore path

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/cloud-hypervisor#1608]
While we are implementing hypervisor traits for Microsoft Hyper-V we understood that we need to maintain some state in the hypervisor/VM struct. At least we need to store HyperCall Page info in the state. This is one page that the guest is using for reading/writing through HyperCall MSR.  More info on this MSR: https://github.com/Microsoft/Virtualization-Documentation/raw/master/tlfs/Requirements%20for%20Implementing%20the%20Microsoft%20Hypervisor%20Interface.pdf

Since this HyperCall page info needs to be saved and restored I was thinking a way to add this to snapshot and restore path.

One way to support this is to define a VmState in hypervisor crate and add two functions to the VM trait. But KVM does not need this to be saved or restored.

Either we could make this conditional to HyperV or we can just use empty struct for KVM and make these functions visible to both KVM and HyperV. For HyperV, we will store required data in the state.

**Comment by sboeuf** [comment]
That sounds better to implement it for both, and do nothing in KVM case. Simply because the caller is not supposed to know if something must be snapshot or not depending on hypervisor.
