### ISSUE TITLE
Query about validating virtio device queues

### ISSUE THREAD

**Issue by glitzflitz** [cloud-hypervisor/cloud-hypervisor#1611]
In function https://github.com/cloud-hypervisor/cloud-hypervisor/blob/17a0733527624341aae37c91d33402abe6d3867c/virtio-devices/src/transport/pci_device.rs#L509 and https://github.com/cloud-hypervisor/cloud-hypervisor/blob/17a0733527624341aae37c91d33402abe6d3867c/virtio-devices/src/transport/mmio.rs#L221  on the line
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/17a0733527624341aae37c91d33402abe6d3867c/virtio-devices/src/transport/pci_device.rs#L511
Is there any reason for all the queues(used and non used in block with multiple queues) being validated?
According to [virtio specification](https://docs.oasis-open.org/virtio/virtio/v1.1/virtio-v1.1.pdf), on Page 51 from section Virtqueue configuration I guess driver which starts the device will set this field https://github.com/cloud-hypervisor/cloud-hypervisor/blob/17a0733527624341aae37c91d33402abe6d3867c/vm-virtio/src/queue.rs#L404 which could be used to determine if a queue is in use or not. So can we simply ignore non used queues?

**Comment by sboeuf** [comment]
Yes, the driver is expected to set this field, that's why we check if each queue is valid by reading from the guest memory. We don't want to end up processing a queue that's not validated by the driver.

**Comment by glitzflitz** [comment]
@sboeuf My question is can we ignore validating non ready queues by doing something like `self.queues.iter().filter(|q| q.ready).all(|q| q.is_valid(&mem.memory()))`?

**Comment by sboeuf** [comment]
@glitzflitz the check you are suggesting is already part of `is_valid()` implementation. Have a look here: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vm-virtio/src/queue.rs#L499-L501.
We consider a queue that is not ready as being not valid.

**Comment by glitzflitz** [comment]
@sboeuf Ah I missed that. Thanks for clarification

**Comment by glitzflitz** [comment]
closed #1611
