### ISSUE TITLE
make bzImage -j `nproc`

### ISSUE THREAD

**Issue by Ruilkyu** [cloud-hypervisor/cloud-hypervisor#1612]
Makefile:614: include/config/auto.conf: No such file or directory
Makefile:660: include/config/auto.conf.cmd: No such file or directory
  LEX     scripts/kconfig/lexer.lex.c
/bin/sh: 1: flex: not found
scripts/Makefile.host:9: recipe for target 'scripts/kconfig/lexer.lex.c' failed
make[2]: *** [scripts/kconfig/lexer.lex.c] Error 127
make[2]: *** Waiting for unfinished jobs....
  YACC    scripts/kconfig/parser.tab.[ch]
/bin/sh: 1: bison: not found
scripts/Makefile.host:17: recipe for target 'scripts/kconfig/parser.tab.h' failed
make[2]: *** [scripts/kconfig/parser.tab.h] Error 127
Makefile:568: recipe for target 'syncconfig' failed
make[1]: *** [syncconfig] Error 2
Makefile:678: recipe for target 'include/config/auto.conf.cmd' failed
make: *** [include/config/auto.conf.cmd] Error 2

**Comment by sboeuf** [comment]
Could you please be more exhaustive about the problem and how you obtained these logs?

**Comment by Ruilkyu** [comment]
自定义内核和磁盘镜像
pushd $CLOUDH
git clone --depth 1 https://github.com/cloud-hypervisor/linux.git -b virtio-fs-virtio-iommu-virtio-mem-5.6-rc4 linux-cloud-hypervisor
pushd linux-cloud-hypervisor
cp $CLOUDH/cloud-hypervisor/resources/linux-config-x86_64 .config
make bzImage -j `nproc`
popd
pushd $CLOUDH
wget https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
qemu-img convert -p -f qcow2 -O raw focal-server-cloudimg-amd64.img focal-server-cloudimg-amd64.raw
popd

**Comment by sboeuf** [comment]
@Ruilkyu please use `virtio-fs-virtio-iommu-5.8-rc4` instead of `virtio-fs-virtio-iommu-virtio-mem-5.6-rc4`.

**Comment by Ruilkyu** [comment]
Thanks!

**Comment by sboeuf** [comment]
@Ruilkyu np! Please close the issue if there's no more errors on your side.
