### ISSUE TITLE
Extract the vhost-user-fs crates into their own repo

### ISSUE THREAD

**Issue by slp** [cloud-hypervisor/cloud-hypervisor#1627]
We'd like to package the ```vhost-user-fs``` binary, and I think the cleanest way to do that would be to move the crate into their own repository, registering the crate in [crates.io](https://crates.io), and then creating an spec for the package.

I've noticed there's already an open issue #1361 for extracting the ```vhost-user``` backend code. In fact, I've just gave a quick try, and was able to build an independent ```vhost-user-fs``` crate by replacing the dependencies with [vhost-user-backend](https://github.com/cloud-hypervisor/vhost-user-backend) and [vm-virtio](https://github.com/cloud-hypervisor/vm-virtio/) (```dragonball``` branch). It needs some changes to adopt the new ```vm_memory::Queue``` API, and adding some missing pieces to ```vm-virtio```, but nothing too serious.

Is this something you were already planning to do? Is there some prerequisite you'd like to see fulfilled before attempting to do this?

**Comment by sboeuf** [comment]
@slp 
>We'd like to package the vhost-user-fs binary

Sounds great!

>and I think the cleanest way to do that would be to move the crate into their own repository, registering the crate in crates.io, and then creating an spec for the package.

I think we all agree on that!

> I've noticed there's already an open issue #1361 for extracting the vhost-user backend code. In fact, I've just gave a quick try, and was able to build an independent vhost-user-fs crate by replacing the dependencies with vhost-user-backend and vm-virtio (dragonball branch). It needs some changes to adopt the new vm_memory::Queue API, and adding some missing pieces to vm-virtio, but nothing too serious.

I'll let @sameo give more feedback, but overall yes I think that's what needs to happen.

>Is this something you were already planning to do? Is there some prerequisite you'd like to see fulfilled before attempting to do this?

I don't think we have the bandwidth to look at it right now, therefore if you think you can take care of it, please do :)

**Comment by sameo** [comment]
> We'd like to package the `vhost-user-fs` binary, and I think the cleanest way to do that would be to move the crate into their own repository, registering the crate in [crates.io](https://crates.io), and then creating an spec for the package.
> 

Excellent!
Do you want to include `main.rs` to the crates.io publishing?

> I've noticed there's already an open issue #1361 for extracting the `vhost-user` backend code. In fact, I've just gave a quick try, and was able to build an independent `vhost-user-fs` crate by replacing the dependencies with [vhost-user-backend](https://github.com/cloud-hypervisor/vhost-user-backend) and [vm-virtio](https://github.com/cloud-hypervisor/vm-virtio/) (`dragonball` branch). It needs some changes to adopt the new `vm_memory::Queue` API, 

Did you mean `vm_virtio::Queue` API?

The `vhost_user_fs` crate would depend on 2 crates (vm-virtio and vhost_user_backend) that are not published in crates.io. I guess that's fine?

> and adding some missing pieces to `vm-virtio`, but nothing too serious.

From a CI perspective, every time we're changing the `vhost_user_fs` code, we run a complete cloud-hypervisor CI run against it, which is a good way to test the code changes themselves and to make sure that we did not break clh compatibility. That would be lost when moving to a separate repo, unless either we find a way to trigger a clh CI run when PR are submitted against this new repo or we build a specific CI for it.

FWIW, I've tried to make cloud-hypervisor move to use something that is much closer to the [vm-virtio](https://github.com/cloud-hypervisor/vm-virtio/) `dragonball` branch here: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1446 but CI is failing.

> Is this something you were already planning to do? 

We want to do it, but we dont have anyone looking at it at the moment. Feel free to own it if you can :)

**Comment by slp** [comment]
> > We'd like to package the `vhost-user-fs` binary, and I think the cleanest way to do that would be to move the crate into their own repository, registering the crate in [crates.io](https://crates.io), and then creating an spec for the package.
> 
> Excellent!
> Do you want to include `main.rs` to the crates.io publishing?

Yes, I think going with an hybrid library/binary crate would make sense in this case.

> > I've noticed there's already an open issue #1361 for extracting the `vhost-user` backend code. In fact, I've just gave a quick try, and was able to build an independent `vhost-user-fs` crate by replacing the dependencies with [vhost-user-backend](https://github.com/cloud-hypervisor/vhost-user-backend) and [vm-virtio](https://github.com/cloud-hypervisor/vm-virtio/) (`dragonball` branch). It needs some changes to adopt the new `vm_memory::Queue` API,
> 
> Did you mean `vm_virtio::Queue` API?

Yup, I always mix up those two crates...

> The `vhost_user_fs` crate would depend on 2 crates (vm-virtio and vhost_user_backend) that are not published in crates.io. I guess that's fine?

Ideally, all crates should be published in crates.io. For `vhost_user_backend` (and `vhost`, on which it depends) this shouldn't be a problem, as we can consider the repositories in the Cloud-Hypervisor organization as the main source for the crates.

The problem comes with `vm-virtio`, for which the `rust-vmm` version should probably be considered the authoritative source, but it's lagging behind CH's version. Luckily, seems like @jiangliu is working on closing the gap.

This brings us to the next question. I see that [vm-memory](https://crates.io/crates/vm-memory) is owned by the `rust-vmm` gatekeepers team. Have you already published some crate as the `Cloud-Hypervisor` organization? Would it make sense to publish `vhost_user_backend` and `vhost` with the `Cloud-Hypervisor` gatekeepers team as the owner or should we move them first to `rust-vmm`?

BTW, this could be an excellent opportunity to establish those crates as the standard infrastructure for building Rust-based vhost-user devices, given that the QEMU Community [is also considering to increase the adoption of this strategy](https://lists.gnu.org/archive/html/qemu-devel/2020-08/msg00800.html). 

> > and adding some missing pieces to `vm-virtio`, but nothing too serious.
> 
> From a CI perspective, every time we're changing the `vhost_user_fs` code, we run a complete cloud-hypervisor CI run against it, which is a good way to test the code changes themselves and to make sure that we did not break clh compatibility. That would be lost when moving to a separate repo, unless either we find a way to trigger a clh CI run when PR are submitted against this new repo or we build a specific CI for it.

What about an strategy like this:

* For each PR in `vhost-user-fs`, either a Jenkins task or a GitHub Action is triggered to run the `vhost-user-fs` tests from CH's integration testsuite (or a some variant of them).

* On a daily basis, CH executes the full integration testsuite, including the tests requiring external components.

Additionally, the code quality tests should also be kept in sync between CH and the external components.

> FWIW, I've tried to make cloud-hypervisor move to use something that is much closer to the [vm-virtio](https://github.com/cloud-hypervisor/vm-virtio/) `dragonball` branch here: #1446 but CI is failing.
> 
> > Is this something you were already planning to do?
> 
> We want to do it, but we dont have anyone looking at it at the moment. Feel free to own it if you can :)

Sure, let's see if we can find a solution for the `vm-virtio` issue, and I'll start a clean repo with current `vhost_user_fs` code.

**Comment by jiangliu** [comment]
We have enhanced the fuse implementation from crosvm/cloud hypervisor, please take look at https://github.com/cloud-hypervisor/fuse-backend-rs
Basically the fuse-backend-rs crate could be used to implement virtio-fs device, vhost-user-fs daemon and normal fuse daemon.

**Comment by jiangliu** [comment]
> > > We'd like to package the `vhost-user-fs` binary, and I think the cleanest way to do that would be to move the crate into their own repository, registering the crate in [crates.io](https://crates.io), and then creating an spec for the package.
> > 
> > 
> > Excellent!
> > Do you want to include `main.rs` to the crates.io publishing?
> 
> Yes, I think going with an hybrid library/binary crate would make sense in this case.
> 
> > > I've noticed there's already an open issue #1361 for extracting the `vhost-user` backend code. In fact, I've just gave a quick try, and was able to build an independent `vhost-user-fs` crate by replacing the dependencies with [vhost-user-backend](https://github.com/cloud-hypervisor/vhost-user-backend) and [vm-virtio](https://github.com/cloud-hypervisor/vm-virtio/) (`dragonball` branch). It needs some changes to adopt the new `vm_memory::Queue` API,
> > 
> > 
> > Did you mean `vm_virtio::Queue` API?
> 
> Yup, I always mix up those two crates...
> 
> > The `vhost_user_fs` crate would depend on 2 crates (vm-virtio and vhost_user_backend) that are not published in crates.io. I guess that's fine?
> 
> Ideally, all crates should be published in crates.io. For `vhost_user_backend` (and `vhost`, on which it depends) this shouldn't be a problem, as we can consider the repositories in the Cloud-Hypervisor organization as the main source for the crates.
> 
> The problem comes with `vm-virtio`, for which the `rust-vmm` version should probably be considered the authoritative source, but it's lagging behind CH's version. Luckily, seems like @jiangliu is working on closing the gap.
> 
> This brings us to the next question. I see that [vm-memory](https://crates.io/crates/vm-memory) is owned by the `rust-vmm` gatekeepers team. Have you already published some crate as the `Cloud-Hypervisor` organization? Would it make sense to publish `vhost_user_backend` and `vhost` with the `Cloud-Hypervisor` gatekeepers team as the owner or should we move them first to `rust-vmm`?
> 
> BTW, this could be an excellent opportunity to establish those crates as the standard infrastructure for building Rust-based vhost-user devices, given that the QEMU Community [is also considering to increase the adoption of this strategy](https://lists.gnu.org/archive/html/qemu-devel/2020-08/msg00800.html).
> 
> > > and adding some missing pieces to `vm-virtio`, but nothing too serious.
> > 
> > 
> > From a CI perspective, every time we're changing the `vhost_user_fs` code, we run a complete cloud-hypervisor CI run against it, which is a good way to test the code changes themselves and to make sure that we did not break clh compatibility. That would be lost when moving to a separate repo, unless either we find a way to trigger a clh CI run when PR are submitted against this new repo or we build a specific CI for it.
> 
> What about an strategy like this:
> 
> * For each PR in `vhost-user-fs`, either a Jenkins task or a GitHub Action is triggered to run the `vhost-user-fs` tests from CH's integration testsuite (or a some variant of them).
> * On a daily basis, CH executes the full integration testsuite, including the tests requiring external components.
> 
> Additionally, the code quality tests should also be kept in sync between CH and the external components.
> 
> > FWIW, I've tried to make cloud-hypervisor move to use something that is much closer to the [vm-virtio](https://github.com/cloud-hypervisor/vm-virtio/) `dragonball` branch here: #1446 but CI is failing.
> > > Is this something you were already planning to do?
> > 
> > 
> > We want to do it, but we dont have anyone looking at it at the moment. Feel free to own it if you can :)
> 
> Sure, let's see if we can find a solution for the `vm-virtio` issue, and I'll start a clean repo with current `vhost_user_fs` code.



> > > We'd like to package the `vhost-user-fs` binary, and I think the cleanest way to do that would be to move the crate into their own repository, registering the crate in [crates.io](https://crates.io), and then creating an spec for the package.
> > 
> > 
> > Excellent!
> > Do you want to include `main.rs` to the crates.io publishing?
> 
> Yes, I think going with an hybrid library/binary crate would make sense in this case.
> 
> > > I've noticed there's already an open issue #1361 for extracting the `vhost-user` backend code. In fact, I've just gave a quick try, and was able to build an independent `vhost-user-fs` crate by replacing the dependencies with [vhost-user-backend](https://github.com/cloud-hypervisor/vhost-user-backend) and [vm-virtio](https://github.com/cloud-hypervisor/vm-virtio/) (`dragonball` branch). It needs some changes to adopt the new `vm_memory::Queue` API,
> > 
> > 
> > Did you mean `vm_virtio::Queue` API?
> 
> Yup, I always mix up those two crates...
> 
> > The `vhost_user_fs` crate would depend on 2 crates (vm-virtio and vhost_user_backend) that are not published in crates.io. I guess that's fine?
> 
> Ideally, all crates should be published in crates.io. For `vhost_user_backend` (and `vhost`, on which it depends) this shouldn't be a problem, as we can consider the repositories in the Cloud-Hypervisor organization as the main source for the crates.
> 
> The problem comes with `vm-virtio`, for which the `rust-vmm` version should probably be considered the authoritative source, but it's lagging behind CH's version. Luckily, seems like @jiangliu is working on closing the gap.
> 
> This brings us to the next question. I see that [vm-memory](https://crates.io/crates/vm-memory) is owned by the `rust-vmm` gatekeepers team. Have you already published some crate as the `Cloud-Hypervisor` organization? Would it make sense to publish `vhost_user_backend` and `vhost` with the `Cloud-Hypervisor` gatekeepers team as the owner or should we move them first to `rust-vmm`?
> 
> BTW, this could be an excellent opportunity to establish those crates as the standard infrastructure for building Rust-based vhost-user devices, given that the QEMU Community [is also considering to increase the adoption of this strategy](https://lists.gnu.org/archive/html/qemu-devel/2020-08/msg00800.html).
We should publish all dependent crates, and how about hosting crates as below:
rust-vmm: vm-memory, vm-virtio
cloud hypervisor: fuse-backend-rs, vhost, vhost-user-backend

**Comment by slp** [comment]
> We have enhanced the fuse implementation from crosvm/cloud hypervisor, please take look at https://github.com/cloud-hypervisor/fuse-backend-rs
> Basically the fuse-backend-rs crate could be used to implement virtio-fs device, vhost-user-fs daemon and normal fuse daemon.

Sounds interesting, but on the other hand, we already have a number of fixes and enhancements commited into `cloud-hypervisor/vhost-user-fs`. Does `fuse-backend-rs` provide a significant advantage over it? I'm interested in seeing if it would be worth porting the changes.

**Comment by slp** [comment]
> > BTW, this could be an excellent opportunity to establish those crates as the standard infrastructure for building Rust-based vhost-user devices, given that the QEMU Community [is also considering to increase the adoption of this strategy](https://lists.gnu.org/archive/html/qemu-devel/2020-08/msg00800.html).
> 
> We should publish all dependent crates, and how about hosting crates as below:
> rust-vmm: vm-memory, vm-virtio
> cloud hypervisor: fuse-backend-rs, vhost, vhost-user-backend

This sounds reasonable to me. @sameo @sboeuf @rbradford what do you think?

**Comment by andreeaflorescu** [comment]
@jiangliu @sameo @slp Any reason for not hosting vhost, vhost-user-backend in rust-vmm as well? I see that there is already a vhost repository in rust-vmm, but changes have not been committed to that repository in a long time.

**Comment by liubogithub** [comment]
> > We have enhanced the fuse implementation from crosvm/cloud hypervisor, please take look at https://github.com/cloud-hypervisor/fuse-backend-rs
> > Basically the fuse-backend-rs crate could be used to implement virtio-fs device, vhost-user-fs daemon and normal fuse daemon.
> 
> Sounds interesting, but on the other hand, we already have a number of fixes and enhancements commited into `cloud-hypervisor/vhost-user-fs`. Does `fuse-backend-rs` provide a significant advantage over it? I'm interested in seeing if it would be worth porting the changes.

Hi Sergio,

Besides the support for `cloud-hypervisor/vhost-user-fs` (IIUC, virtiofsd's rust version),  fuse-backend-rs is also able to support a different filesystem format which helps us do on-demand-load tricks for `rootfs` of container on booting (instead of waiting seconds/minutes for downloading image).  More details are available at [this post](https://github.com/dragonflyoss/community/issues/9)

**Comment by slp** [comment]
> Besides the support for `cloud-hypervisor/vhost-user-fs` (IIUC, virtiofsd's rust version), fuse-backend-rs is also able to support a different filesystem format which helps us do on-demand-load tricks for `rootfs` of container on booting (instead of waiting seconds/minutes for downloading image). More details are available at [this post](https://github.com/dragonflyoss/community/issues/9)

Thanks for the explanation. I'll take a deeper look at the crate next week.

**Comment by slp** [comment]
> @jiangliu @sameo @slp Any reason for not hosting vhost, vhost-user-backend in rust-vmm as well? I see that there is already a vhost repository in rust-vmm, but changes have not been committed to that repository in a long time.

@andreeaflorescu Personally, I got the feeling that `rust-vmm` is for mature crates that move slowly. Perhaps I'm wrong about this, and in that case, IMO, it would be preferable to have all those crates under `rust-vmm`.

**Comment by jiangliu** [comment]
> > @jiangliu @sameo @slp Any reason for not hosting vhost, vhost-user-backend in rust-vmm as well? I see that there is already a vhost repository in rust-vmm, but changes have not been committed to that repository in a long time.
> 
> @andreeaflorescu Personally, I got the feeling that `rust-vmm` is for mature crates that move slowly. Perhaps I'm wrong about this, and in that case, IMO, it would be preferable to have all those crates under `rust-vmm`.

Yes

**Comment by andreeaflorescu** [comment]
I would say that it is preferable for components to evolve in rust-vmm, rather than dump thousands of lines in there at some point when we believe they're ready. We do not have any requirement for crates to be mature to live in rust-vmm, we just want to make sure that once they get on crates.io they meet the quality bar that we set for components to be [production-ready](https://github.com/rust-vmm/community#publishing-on-cratesio---requirements-list).

Having design discussions in a separate place seems like a duplication of effort because there is a high likelihood of having the same questions asked again when moving the components to rust-vmm. IMHO, the goal of rust-vmm is to avoid the duplication.

I would be happy to chat to see if there are some issues that we can address in rust-vmm that would allow you to move at the speed that you need. What do you say?

**Comment by slp** [comment]
> I would say that it is preferable for components to evolve in rust-vmm, rather than dump thousands of lines in there at some point when we believe they're ready. We do not have any requirement for crates to be mature to live in rust-vmm, we just want to make sure that once they get on crates.io they meet the quality bar that we set for components to be [production-ready](https://github.com/rust-vmm/community#publishing-on-cratesio---requirements-list).
> 
> Having design discussions in a separate place seems like a duplication of effort because there is a high likelihood of having the same questions asked again when moving the components to rust-vmm. IMHO, the goal of rust-vmm is to avoid the duplication.

IMHO, this is a very good point.

**Comment by andreeaflorescu** [comment]
@jiangliu @sameo @slp @sboeuf ping.

Did you have time to discuss any path forward here?

If you do not have anything against hosting them in rust-vmm instead, we would need to:
- vhost: just post a PR, the repository already exists: https://github.com/rust-vmm/vhost; It also looks like there is already a PR open that was doing some sort of sync: https://github.com/rust-vmm/vhost/pull/10
- fuse-backend-rs: create an issue in rust-vmm/community (and then we'll create a repository)
- vhost-user-backend: same as fuse-backend-rs

**Comment by sameo** [comment]
> @jiangliu @sameo @slp @sboeuf ping.
> 
> Did you have time to discuss any path forward here?
> 
> If you do not have anything against hosting them in rust-vmm instead, we would need to:
> 
>     * vhost: just post a PR, the repository already exists: https://github.com/rust-vmm/vhost; It also looks like there is already a PR open that was doing some sort of sync: [rust-vmm/vhost#10](https://github.com/rust-vmm/vhost/pull/10)
> 

Can we start with the vhost crate first? It is quite stable and fairly stale. Then we could at least have the other crates switching to the rust-vmm vhost and then we can start discussing about hosting the other ones in rust-vmm.
I'll ping @arronwy to see if he can rebase and refresh the PR and address your initial comments. Does that sound ok as a first step?

**Comment by andreeaflorescu** [comment]
Awesome! :100:

**Comment by jiangliu** [comment]
Sounds like a plan, let’s get start with the ghost crate. Then we could improve the host crate with better tests and documentations.

**Comment by arronwy** [comment]
> > @jiangliu @sameo @slp @sboeuf ping.
> > Did you have time to discuss any path forward here?
> > If you do not have anything against hosting them in rust-vmm instead, we would need to:
> > ```
> > * vhost: just post a PR, the repository already exists: https://github.com/rust-vmm/vhost; It also looks like there is already a PR open that was doing some sort of sync: [rust-vmm/vhost#10](https://github.com/rust-vmm/vhost/pull/10)
> > ```
> 
> Can we start with the vhost crate first? It is quite stable and fairly stale. Then we could at least have the other crates switching to the rust-vmm vhost and then we can start discussing about hosting the other ones in rust-vmm.
> I'll ping @arronwy to see if he can rebase and refresh the PR and address your initial comments. Does that sound ok as a first step?

I'll refresh that PR and fix the comments.

**Comment by rbradford** [comment]
I think this is all completed now. With virtio-fs moved to https://gitlab.com/virtio-fs/virtiofsd-rs
