### ISSUE TITLE
Basic VM snapshot/restore support for AArch64

### ISSUE THREAD

**Issue by MrXinWang** [cloud-hypervisor/cloud-hypervisor#1644]
As we current have the VM snapshot/restore functionality for x86_64 VM, it is good to also implement this for AArch64.

PS: I think to implement this, the `ch` branch of [cloud-hypervisor/kvm-bindings](https://github.com/cloud-hypervisor/kvm-bindings) and [cloud-hypervisor/kvm-ioctls](https://github.com/cloud-hypervisor/kvm-ioctls) need an update to ensure that https://github.com/rust-vmm/kvm-bindings/commit/595a21c07929a1d0cb878ae94b9967c212511eaf and https://github.com/rust-vmm/kvm-ioctls/commit/bc85674ceddd7ca9b259605138d24fab3a033327 are in. Can I ask a little favor for syncing these repositories please @sboeuf @rbradford ? Thanks!

**Comment by MrXinWang** [comment]
https://github.com/cloud-hypervisor/kvm-bindings/pull/2 created as the first step, but the commit tree of this PR looks a little bit messy without syncing the `ch` branch of [cloud-hypervisor/kvm-bindings](https://github.com/cloud-hypervisor/kvm-bindings) though...

**Comment by MrXinWang** [comment]
@michael2012z  FYI

**Comment by sboeuf** [comment]
@MrXinWang once we get cloud-hypervisor/kvm-bindings#2 merged, please send the needed PR for cloud-hypervisor/kvm-ioctls and then I think you'll be good to move forward with snapshot/restore for aarch64 :)

**Comment by MrXinWang** [comment]
Thanks @sboeuf.  https://github.com/cloud-hypervisor/kvm-ioctls/pull/2 created for the ioctl to move forward :) thanks!

**Comment by sboeuf** [comment]
cloud-hypervisor/kvm-ioctls#2 is now merged!
