### ISSUE TITLE
Document the flow of the VFIO implementation

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#165]
It would be very nice to create an architectural/technical document about how VFIO works behind the scene, how it is tied to KVM for some use cases, and how the VMM implementation leverages both VFIO and KVM APIs in practice.

**Comment by mythi** [comment]
Additional "end user" feedback: I ran into a problem that my user `LimitMEMLOCK` was not enough for VFIO/device assignment to work correctly. The driver init printed an error and host dmesg had an entry 
`[  365.159219] vfio_pin_pages_remote: RLIMIT_MEMLOCK (4194304) exceeded`

It'd be nice to have notes/pointers about:
- how to estimate the needed limit (per device?)
- usage of hugepages for this(?)
(- ways to set the limit)

**Comment by sboeuf** [comment]
@mythi it's about how much RAM you allocate to your VM, as the entire guest RAM is pinned for each device. And by default, if you're not using hugepages, you get a bunch of 4k mappings. Lowering the amount of RAM can solve that (just as a test of course), but the long term solutions are:
- Using hugepages with the following option in the CH CLI `--memory size=16G,file=/dev/hugepages` (of course make sure you have enough hugepages on the host)
- Loading the vfio driver with an extra parameter to specify the maximum amount of entries allowed

**Comment by rbradford** [comment]
@sboeuf Do you think this is still a relevant issue to keep open? Is it appropriate and actionable?

**Comment by sboeuf** [comment]
No I think that's actually quite hard, so we can close it.
