### ISSUE TITLE
Test case test_vhost_user_net_self_spawning failure on AArch64

### ISSUE THREAD

**Issue by michael2012z** [cloud-hypervisor/cloud-hypervisor#1650]
integration test case `test_vhost_user_net_self_spawning` had been failing on AArch64. 2 problems exist:

1. The back-end process didn't start successfully due to seccomp trapping. After appending "--seccomp log" option in command line, `dmesg` log revealed the blocked syscalls in launching the back-end.
2. When the guest was shutting down, there were also some syscalls blocked.

The `dmesg` log showed:

> [712142.037998] kauditd_printk_skb: 70 callbacks suppressed
> [712142.038003] audit: type=1326 audit(1598709948.812:318): auid=4294967295 uid=0 gid=101 ses=4294967295 subj==unconfined pid=170622 comm="cloud-hyperviso" exe="/cloud-hypervisor/target/aarch64-unknown-linux-gnu/release/cloud-hypervisor" sig=0 arch=c00000b7 syscall=48 compat=0 ip=0xffffb6083a3c code=0x7ffc0000
> [712142.038015] audit: type=1326 audit(1598709948.812:319): auid=4294967295 uid=0 gid=101 ses=4294967295 subj==unconfined pid=170622 comm="cloud-hyperviso" exe="/cloud-hypervisor/target/aarch64-unknown-linux-gnu/release/cloud-hypervisor" sig=0 arch=c00000b7 syscall=48 compat=0 ip=0xffffb608db18 code=0x7ffc0000
> [712142.038083] audit: type=1326 audit(1598709948.812:320): auid=4294967295 uid=0 gid=101 ses=4294967295 subj==unconfined pid=170622 comm="cloud-hyperviso" exe="/cloud-hypervisor/target/aarch64-unknown-linux-gnu/release/cloud-hypervisor" sig=0 arch=c00000b7 syscall=79 compat=0 ip=0xffffb608d884 code=0x7ffc0000
> [712142.038093] audit: type=1326 audit(1598709948.812:321): auid=4294967295 uid=0 gid=101 ses=4294967295 subj==unconfined pid=170622 comm="cloud-hyperviso" exe="/cloud-hypervisor/target/aarch64-unknown-linux-gnu/release/cloud-hypervisor" sig=0 arch=c00000b7 syscall=79 compat=0 ip=0xffffb608d884 code=0x7ffc0000
> ... skip ...

When I tested with following command on X86: 

> sudo ../cloud-hypervisor/target/debug/cloud-hypervisor --cpus boot=2 --memory size=512M,hotplug_size=2048M,shared=on --kernel ~/workloads/vmlinux --disk path=osdisk.img path=cloudinit --net vhost_user=true,mac=12:34:56:78:90:01,mask=255.255.255.0,num_queues=4,queue_size=1024 --cmdline "root=/dev/vda1 console=ttyS0 console=hvc0 rw"

Same problem exist in the final stage of guest shutdown: 

> [  OK  ] Finished Power-Off.
> [  OK  ] Reached target Power-Off.
> [   14.690790] reboot: Power down
> [1]    33042 invalid system call
>

**Comment by sboeuf** [comment]
Thanks for spotting this issue :+1:
