### ISSUE TITLE
Extended VcpuExit Handling

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/cloud-hypervisor#1660]
While handling VcpuExits in hypervisor module, we need a better mechanism to access several resources from VMM module like:

* Guest Physical Memory (read, write)
* mmio (read, write)
* pio (in, out)

Following KVM hypervisor implementation, we could return Ok(cpu::VMExit::func) from vcpu.run in hypervisor module. This approach returns control back to vcpu.run() in VMM module and hypervisor will not be able further process data it gathered from above listed resources.

Also, if we were to adopt above approach, we will have to maintain some state in our hypervisor module to resume execution from previous VcpuExit, which could get hairy. 

https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1416 is a solution @liuw suggested for this issue. If that isn't acceptable can anyone suggest a different approach we could adopt for this issue?

**Comment by sameo** [comment]
> While handling VcpuExits in hypervisor module, we need a better mechanism to access several resources from VMM module like:
> 
>     * Guest Physical Memory (read, write)
> 
>     * mmio (read, write)
> 
>     * pio (in, out)

I can see how the hypervisor could need a reference to the guest address space, and it would make sense to pass a reference to it through `run()`. But I wonder why it'd need to access to the IO buses and the device model. In which case would the hypervisor want to basically override a device that claimed ownership of an IO region? Maybe I'm missing something here.

**Comment by liuw** [comment]
> 
> 
> > While handling VcpuExits in hypervisor module, we need a better mechanism to access several resources from VMM module like:
> > ```
> > * Guest Physical Memory (read, write)
> > 
> > * mmio (read, write)
> > 
> > * pio (in, out)
> > ```
> 
> I can see how the hypervisor could need a reference to the guest address space, and it would make sense to pass a reference to it through `run()`. But I wonder why it'd need to access to the IO buses and the device model. In which case would the hypervisor want to basically override a device that claimed ownership of an IO region? Maybe I'm missing something here.

The hypervisor will not claim ownership of an IO region.

We want to process the data returned from the VMM module before (re-)scheduling the vcpu.

It should be doable by either hand-roll a (big-ish) state machine in the Hyper-V module or use some available state machine libraries. The approach requires quite a bit of work though. That's why I suggested Praveen start a discussion here to reach a consensus.

KVM doesn't have such an issue because the state machine is inside the kernel. It keeps track of which `VcpuExit` it produces and processes the data returned from cloud hypervisor. The complexity is hidden from CH. But in our implementation we don't have such luxury.

Hope this helps. Happy to provide more context if necessary.

**Comment by praveen-pk** [comment]
Passing references to guest memory, IO_bus, mmio_bus to vcpu in hypervisor is an option. Instead passing there references one-by-one all the way to vcpu in hypervisor module, I am guessing we can bundle them into a trait object and pass it?

A trait (IoMemAccess) could be implemented for vcpu in vmm module and the trait object would be passed to vcpu in hypervisor module. This would also address the requirement of not implementing traits from hypervisor module in vmm module.

**Comment by sameo** [comment]
Thanks @praveen-pk and @liuw for the context. Taking that into account, I can't see a better way to address what is a valid use case than providing some sort of callbacks into the VMM. 
This would be very similar to PR #1416 but a little more generic by not making the naming either CPU or IO specific, something like `VmmOps`. That would allow for extending that interface more cleanly in the future, if we ever need something not IO specific from the VMM.

**Comment by praveen-pk** [comment]
Sounds good! I will start working on it.

**Comment by praveen-pk** [comment]
As I look to implement this trait, I have a basic question. If the new trait should allow hypervisor module access to:

* guest memory
* IO 
* shutdown/reset

I am wondering what object (Vm, VMM, Vcpu) in vmm module would implement the trait. In vmm module,  Vmm object can handle shutdown/reset, while Vm object has access to memory_manager/guest_memory and Vcpu Object has access to io_bus, mmio_bus.

I could implement the trait on Vcpu object (in vmm), but that means I have to pass references to Vm and Vmm object down to the Vcpu Object. Does that sound reasonable? @sboeuf @rbradford

**Comment by rbradford** [comment]
Probably `Vm` object but we might need to refactor to support it.

**Comment by sameo** [comment]
> Probably `Vm` object but we might need to refactor to support it.

Implementing the interface from the `Vm` object makes sense to me.

**Comment by rbradford** [comment]
@praveen-pk I think this is done?

**Comment by liuw** [comment]
@rbradford He's out of office until end of October. I can confirm this can be closed.
