### ISSUE TITLE
Rearrange NUMA nodes parameters and options

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1665]
Based on the observation that ACPI defines NUMA nodes equally from a CPU, memory or IO perspective, I'm not sure NUMA nodes should be defined from `--memory-zone`, but directly from `--numa` parameter instead. This would allow for the description of a node with no particular memory range attached to it, but we could still define CPUs and distances if needed.

If we agree on the first aspect, and in order to prevent redundant declarations from the CLI, we could also simplify the `--memory-zone` parameter by removing `guest_numa_node=`, and instead refer the memory zone from `--numa` with the option `memory_zones=`. This new option would provide a list of memory zones attached to the current NUMA node. This would require the `--memory-zone` parameter to be extended with a mandatory parameter `id=`, as it would be essential to be capable of identifying each zone distinctly. Given that we *might* want to be able to remove memory zones (hot-unplug), the `id` parameter would be needed anyway, which is also one of the reason why I'm proposing this approach.

@rbradford @sameo let me know what you think about all this!

**Comment by rbradford** [comment]
:+1:

**Comment by sameo** [comment]
> @rbradford @sameo let me know what you think about all this!

I'm fine with the proposals.
