### ISSUE TITLE
Released binaries do not print the right version information

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#1669]
Until our latest release ([v0.9.0](https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v0.9.0)), the binaries we generated won't report the right version information with `--version` option. The output is missing the actual version number as shown below. It is likely to be related to the implementation of our [`build.rs`](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/build.rs) which replies only on `git describe` to get the version number.

```
$ ./cloud-hypervisor-static  --version                                                                                                                                                          
cloud-hypervisor 
```

**Comment by alindima** [comment]
Hello. If this is related to the `build.rs` file, this might be because you are not checking the status code returned by the git command.
This may silently fail, by having an empty stdout, and returning an `Ok` value, for example when not in a git repository folder.

You could try calling `git_out.status.success()` for checking the return code.

**Comment by likebreath** [comment]
> Hello. If this is related to the `build.rs` file, this might be because you are not checking the status code returned by the git command.
> This may silently fail, by having an empty stdout, and returning an `Ok` value, for example when not in a git repository folder.
> 
> You could try calling `git_out.status.success()` for checking the return code.

I am suspecting the same thing. The part I am not sure is whether the GitHub Action for releasing is actually going to mess up with the git tags, because it indeed checked out the repo (e.g. for the last release [here](https://github.com/cloud-hypervisor/cloud-hypervisor/runs/954151850?check_suite_focus=true#step:2:363)).

I can definitely add a check on the `git_out` and fall back to use the `crate_version` when `git` failed. But I am not sure how I would be able to test it, especially for the GH release action. Any thoughts? @alindima @rbradford

**Comment by rbradford** [comment]
@likebreath Try creating a release on your own fork
