### ISSUE TITLE
Memory zones must not be contiguous

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1685]
Memory zones must not be contiguous either because of a natural gap (i.e. 3-4GiB) or with an artificially added one. This is to make sure the kernel does not use memory spanning the zones (and cause issues with vm-memory.)

It's probably a good idea to align the start on 128MiB too.

**Comment by sboeuf** [comment]
Closing as this is not necessary, since the `vm-memory` code can handle contiguous zones.
