### ISSUE TITLE
Move to rust-vmm kvm-ioctls

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1706]
Use a `.patch` in the Cargo.toml to point at our custom kvm-bindings repo.

**Comment by sboeuf** [comment]
That's too complex to resolve since there's a lot of dependencies between `kvm-ioctls` and `kvm-bindings` from other crates as well (vfio-ioctls for instance). It'll be easier to fully move to both `kvm-ioctls` and `kvm-bindings` from rust-vmm at the same time, when this will be possible.
