### ISSUE TITLE
CI is flaky due to test_boot_from_vhost_user_blk_self_spawning

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1709]
Both https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/master/5509/pipeline and https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/master/5512/pipeline are example showing the test `test_boot_from_vhost_user_blk_self_spawning` is failing with `--libc musl`.

**Comment by sboeuf** [comment]
Just a note this might be caused by the same issue reported by @likebreath on #1707.

**Comment by sboeuf** [comment]
After some investigations, I think the problem might be coming from the fact that under high load, it might take some time for the self spawned backend to be listening onto the socket.
Or the second option would be that the backend is terminated by a `SIGSYS` because we would be missing a syscall in the seccomp list.
Problem is, it's not reproducible :(

**Comment by sboeuf** [comment]
@rbradford suggested that we could have a dedicated `fd=` option added to the `--block-backend` and `net-backend` parameters. This means the VMM process would be passing a file descriptor instead of a vhost-user socket path. This `fd` would refer to the socket without requiring the backend to open the given path and start listening on it.
This would prevent from concurrency issues where the backend might not be listening yet.

Before jumping into any implementation, we must validate the problem is solved if we increase the wait time or if we don't run this test under high load.

**Comment by rbradford** [comment]
Self spawning has been removed.
