### ISSUE TITLE
Discuss removing self spawning vhost-user-net/vhost-user-block

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1724]
This was added for convenience of our users and for testing. However with retrospect I think this adds quite a lot of complexity to the code for very little gain. I think we openly need to consider whether this feature is still useful.

**Comment by sboeuf** [comment]
I'm in favor of removing it.

**Comment by sameo** [comment]
I'm ok with removing it as well. Users interested with using vhost backends for block/network will likely use their own backend, we understand that now in retrospective.

**Comment by rbradford** [comment]
It's been dropped.
