### ISSUE TITLE
Measure block I/O performance

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1730]
In the global effort to assess how Cloud-Hypervisor performs (https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1727), we want to measure the `virtio-blk` implementations (including `io_uring`) from Cloud-Hypervisor.
We need to get the same kind of information from QEMU, and based on the comparison of the results, we'll assess if taking any action is needed.

**Comment by sboeuf** [comment]
For each VMM, two types of configuration have been tested, one with a single `virtio-blk` queue, and one with 2 queues.
Tests have been performed with Cloud Hypervisor v0.13.0 and QEMU v5.2.0.

Prior to testing, a test file of 8GiB is created on the host:
```
dd if=/dev/zero of=/tmp/tmp.img bs=1M count=8192
```

### Single queue testing
First test is to run a VMM with 4vCPUs, 4GiB of RAM, 1 `virtio-blk` queue.
Two tests are run from the guest with this configuration:
- One to perform synchronous accesses to the `virtio-blk` device.
- One to perform asynchronous accesses to the `virtio-blk` device.

#### Cloud Hypervisor command line
```
./target/release/cloud-hypervisor \
    --cpus boot=4 \
    --memory size=4G \
    --kernel bzImage \
    --cmdline "root=/dev/vda1 console=hvc0 rw" \
    --disk path=focal-server-cloudimg-amd64-custom.raw \
    path=tmp.img,num_queues=1,queue_size=1024,direct=on
```

#### QEMU command line
```
qemu-system-x86_64 \
    -machine pc,accel=kvm \
    -cpu host,host-phys-bits \
    -smp 4 \
    -m 4G \
    -kernel bzImage \
    -display none \
    -nodefaults \
    -serial mon:stdio \
    -append "console=ttyS0 root=/dev/vda1 rw" \
    -drive id=os,file=focal-server-cloudimg-amd64-custom.raw,if=none \
    -device virtio-blk-pci,drive=os \
    -drive id=test_disk,file=tmp.img,format=raw,if=none,cache=none,aio=io_uring \
    -device virtio-blk-pci,drive=test_disk,num-queues=1,queue-size=1024
```

#### Synchronous test
```
sudo fio --filename=/dev/vdb --size=4G --direct=1 --rw=randrw --bs=4k --ioengine=sync --iodepth=1 --runtime=180 --numjobs=1 --time_based --group_reporting --name=iops-test-job --eta-newline=1
```

#### Asynchronous test
```
sudo fio --filename=/dev/vdb --size=4G --direct=1 --rw=randrw --bs=4k --ioengine=io_uring --iodepth=64 --runtime=180 --numjobs=1 --time_based --group_reporting --name=iops-test-job --eta-newline=1
```

### Multi queue testing
Second test is to run a VMM with 4vCPUs, 4GiB of RAM, 2 `virtio-blk` queues.
Two tests are run from the guest with this configuration:
- One to perform synchronous accesses to the `virtio-blk` device.
- One to perform asynchronous accesses to the `virtio-blk` device.

#### Cloud Hypervisor command line
```
./target/release/cloud-hypervisor \
    --cpus boot=4 \
    --memory size=4G \
    --kernel bzImage \
    --cmdline "root=/dev/vda1 console=hvc0 rw" \
    --disk path=focal-server-cloudimg-amd64-custom.raw \
    path=tmp.img,num_queues=2,queue_size=1024,direct=on
```

#### QEMU command line
```
qemu-system-x86_64 \
    -machine pc,accel=kvm \
    -cpu host,host-phys-bits \
    -smp 4 \
    -m 4G \
    -kernel bzImage \
    -display none \
    -nodefaults \
    -serial mon:stdio \
    -append "console=ttyS0 root=/dev/vda1 rw" \
    -drive id=os,file=focal-server-cloudimg-amd64-custom.raw,if=none \
    -device virtio-blk-pci,drive=os \
    -drive id=test_disk,file=tmp.img,format=raw,if=none,cache=none,aio=io_uring \
    -device virtio-blk-pci,drive=test_disk,num-queues=2,queue-size=1024
```

#### Synchronous test
```
sudo fio --filename=/dev/vdb --size=4G --direct=1 --rw=randrw --bs=4k --ioengine=sync --iodepth=1 --runtime=180 --numjobs=2 --time_based --group_reporting --name=iops-test-job --eta-newline=1
```

#### Asynchronous test
```
sudo fio --filename=/dev/vdb --size=4G --direct=1 --rw=randrw --bs=4k --ioengine=io_uring --iodepth=64 --runtime=180 --numjobs=2 --time_based --group_reporting --name=iops-test-job --eta-newline=1
```

### Results

| | Cloud Hypervisor | QEMU |
| --- | --- | --- |
| __Single queue__ | | |
| Synchronous | 22 MiB/s | 22 MiB/s |
| Asynchronous (io_uring) | 315 MiB/s | 325 MiB/s |
| __Multi queue__ | | |
| Synchronous | 43 MiB/s | 44 MiB/s |
| Asynchronous (io_uring) | 420 MiB/s | 400 MiB/s |

#### Comments about results

Results are very similar, which means Cloud Hypervisor is on parity with QEMU regarding the `virtio-blk` implementation relying on `io_uring`, therefore no further action is needed.

**Comment by sboeuf** [comment]
@rbradford should we close this issue? Or do you expect something else from this?

**Comment by rbradford** [comment]
> @rbradford should we close this issue? Or do you expect something else from this?

Yes, I think this is great work. Thanks for doing it :rocket:
