### ISSUE TITLE
Measure network I/O performance

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1731]
In the global effort to assess how Cloud-Hypervisor performs (https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1727), we want to measure the `virtio-net` implementation from Cloud-Hypervisor.
We need to get the same kind of information from QEMU, and based on the comparison of the results, we'll assess if taking any action is needed.

**Comment by rbradford** [comment]
Could reuse https://github.com/firecracker-microvm/firecracker/pull/271/commits/142a91f9616e44d73daf46baed9554784f482048#diff-a1e3b4f2cdf5d755f3968cc44b6a0c6ad3324a6a7e0bdc297ebe6ed1e87a2aa0 to give a token bucket to allow us to ratelimit.

**Comment by sboeuf** [comment]
For each VMM, two types of tests have been run, one with a single virtio-net queue, and one with 8 queues.
Tests have been performed with Cloud Hypervisor v0.13.0 and QEMU v5.2.0.

### Single queue testing
First test is to run a VMM with 4vCPUs, 4GiB of RAM, 1 virtio-net queue pair (tx/rx), and one `iperf3` client running in the guest, connected to one `iperf3` server on the host.
A TAP interface has been created for this test:
```
sudo ip tuntap add name virttap0 mode tap
sudo ip addr add 192.168.249.1/24 dev virttap0
sudo ip link set up dev virttap0
```

#### Cloud Hypervisor command line
```
./target/release/cloud-hypervisor \
    --cpus boot=4 \
    --memory size=4G \
    --kernel bzImage \
    --cmdline "root=/dev/vda1 console=hvc0 rw" \
    --disk path=focal-server-cloudimg-amd64-custom.raw \
    --net tap=virttap0
```

#### QEMU command line
```
qemu-system-x86_64 \
    -machine pc,accel=kvm \
    -cpu host,host-phys-bits \
    -smp 4 \
    -m 4G \
    -kernel bzImage \
    -display none \
    -nodefaults \
    -serial mon:stdio \
    -append "console=ttyS0 root=/dev/vda1 rw" \
    -drive id=os,file=focal-server-cloudimg-amd64-custom.raw,if=none \
    -device virtio-blk-pci,drive=os \
    -netdev tap,id=mynet0,ifname=virttap0,script=no,downscript=no \
    -device virtio-net-pci,netdev=mynet0
```

#### Guest commands
```
# Set network interface
sudo ip addr add 192.168.249.2/24 dev ens3
sudo ip link set up dev ens3

# Run iperf client for 60 seconds
iperf3 -c 192.168.249.1 -t 60
```

### Multi queue testing
Second test is to run a VMM with 8vCPUs, 4GiB of RAM, 8 virtio-net queue pair (tx/rx), and 8 `iperf3` clients running in the guest, connected to 8 `iperf3` servers on the host.
A TAP interface has been created for this test:
```
sudo ip tuntap add name virttap0 mode tap multi_queue
sudo ip addr add 192.168.249.1/24 dev virttap0
sudo ip link set up dev virttap0
```

#### Cloud Hypervisor command line
```
./target/release/cloud-hypervisor \
    --cpus boot=8 \
    --memory size=4G \
    --kernel bzImage \
    --cmdline "root=/dev/vda1 console=hvc0 rw" \
    --disk path=focal-server-cloudimg-amd64-custom.raw \
    --net tap=virttap0,num_queues=16
```

#### QEMU command line
```
qemu-system-x86_64 \
    -machine pc,accel=kvm \
    -cpu host,host-phys-bits \
    -smp 8 \
    -m 4G \
    -kernel bzImage \
    -display none \
    -nodefaults \
    -serial mon:stdio \
    -append "console=ttyS0 root=/dev/vda1 rw" \
    -drive id=os,file=focal-server-cloudimg-amd64-custom.raw,if=none \
    -device virtio-blk-pci,drive=os \
    -netdev tap,id=mynet0,ifname=virttap0,script=no,downscript=no,queues=8 \
    -device virtio-net-pci,netdev=mynet0
```

#### Guest commands
```
# Set network interface
sudo ip addr add 192.168.249.2/24 dev ens3
sudo ip link set up dev ens3

# Run iperf client for 60 seconds
iperf3 -c 192.168.249.1 -p 5201 -t 60 &
iperf3 -c 192.168.249.1 -p 5202 -t 60 &
iperf3 -c 192.168.249.1 -p 5203 -t 60 &
iperf3 -c 192.168.249.1 -p 5204 -t 60 &
iperf3 -c 192.168.249.1 -p 5205 -t 60 &
iperf3 -c 192.168.249.1 -p 5206 -t 60 &
iperf3 -c 192.168.249.1 -p 5207 -t 60 &
iperf3 -c 192.168.249.1 -p 5208 -t 60 &
```

### Results

| | Cloud Hypervisor | QEMU |
| --- | --- | --- |
| Single queue | 36 Gbits/s | 43 Gbits/s |
| Multi queue | 44~48 Gbits/s | 28 Gbits/s |

#### Comments about results

- QEMU is performing better on single queue (7 Gbits/s), which means it'd be worth identifying what is slowing down the Cloud Hypervisor implementation.
- Cloud Hypervisor is performing better with multiple queues, which is good news. By having `htop` running while the iperf tests are running, we can see all threads related to virtio-net queues being used. However, I noticed they never reach full CPU consumption, so I'm wondering what's holding them back.
- Overall comment, the performance improvement when using multiple queues is not huge (barely 1.3x), so I'm wondering if that's expected or if something's wrong?

@rbradford @sameo Please let me know your thoughts on this.

**Comment by rbradford** [comment]
@sboeuf Good work.

As well as throughput can you look at:
* latency
* CPU usage during the max throughput.

QEMU has some options to let you disable VIRTIO features, it might be worth turning off the QEMU VIRTIO features we don't support.

There are some instructions in the docs/ directory about running perf against Cloud Hypervisor. This would show any hot spots.

**Comment by sboeuf** [comment]
@rbradford 
>As well as throughput can you look at:
    - latency
    - CPU usage during the max throughput.

Can `iperf3` give me latency? Or do I need a different tool? I remember I used https://github.com/microsoft/ethr tool once, it was quite good.

About CPU usage, during the tests, what would be the preferred way to capture such information?

>QEMU has some options to let you disable VIRTIO features, it might be worth turning off the QEMU VIRTIO features we don't support.

Good point, let's see if this reduces the performances.

>There are some instructions in the docs/ directory about running perf against Cloud Hypervisor. This would show any hot spots.

Sounds good!

**Comment by rbradford** [comment]
Not sure your MQ config is right for QEMU: https://www.linux-kvm.org/page/Multiqueue

> 
     enable mq for tap (suppose N queue pairs) -netdev tap,vhost=on,queues=N
    enable mq and specify msix vectors in qemu cmdline (2N+2 vectors, N for tx queues, N for rx queues, 1 for config, and one for possible control vq): -device virtio-net-pci,mq=on,vectors=2N+2...
    enable mq in guest by 'ethtool -L eth0 combined $queue_num'

**Comment by rbradford** [comment]
@sboeuf That `ethr` tool look quite cool. Is the depth of the queues the same between CH and QEMU?

**Comment by rbradford** [comment]
I hope your host system has at least 16 cores. You're maxing out 8 vCPU threads and also 8 on the host.

**Comment by sboeuf** [comment]
@rbradford I think it'd be best to redo the tests with 4 queues instead of 8.

**Comment by sboeuf** [comment]
So I've tried with 2 queues instead of 8, and 4vCPUs instead of 8. I've made sure the queue size was 1024 for both CH and QEMU.
This leads to a similar trend, the numbers don't change much.
About latency, I've got around 50us for CH, while QEMU is oscillating between 50us and 100us. This test has been performed with the `ethr` tool:
```
ethr -c 192.168.249.1 -t l -n 1 -d 60s
```

**Comment by rbradford** [comment]
I think we need to focus on our 1 queue pair performance; try disabling the QEMU VIRTIO features to match CH.

**Comment by sboeuf** [comment]
I think once https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2275 is merged, we can simply close this issue. The Cloud-Hypervisor implementation for `virtio-net` will be now very simple and that's what matters the most. In terms of performances, QEMU is doing a better job with throughput (about 15% better) but not regarding latency (50% higher).
I think simplicity of the implementation is far more important than pure performance here as we're talking about `virtio-net`. What I mean to say is that any user who would like to use Cloud Hypervisor in production won't use `virtio-net` to obtain outstanding networking performances. What matters the most is that `virtio-net` is reliable and easily maintained (goes with simplicity of the code).
