### ISSUE TITLE
Missing vhost-user-client support

### ISSUE THREAD

**Issue by cHolzberger** [cloud-hypervisor/cloud-hypervisor#1745]
how to use vhost-user in vhost-user-client mode? 

e.g. for open-vswitch:
[Openvswitch Docu](https://docs.openvswitch.org/en/latest/topics/dpdk/vhost-user/?highlight=dpdk%20vhost)

> vhost-user vs. vhost-user-client¶
> Open vSwitch provides two types of vHost User ports:
> 
> vhost-user (dpdkvhostuser)
> vhost-user-client (dpdkvhostuserclient)
> vHost User uses a client-server model. The server creates/manages/destroys the vHost User sockets, and the client connects to the server. Depending on which port type you use, dpdkvhostuser or dpdkvhostuserclient, a different configuration of the client-server model is used.
> 
> For vhost-user ports, Open vSwitch acts as the server and QEMU the client. This means if OVS dies, all VMs must be restarted. On the other hand, for vhost-user-client ports, OVS acts as the client and QEMU the server. This means OVS can die and be restarted without issue, and it is also possible to restart an instance itself. For this reason, vhost-user-client ports are the preferred type for all known use cases; the only limitation is that vhost-user client mode ports require QEMU version 2.7. Ports of type vhost-user are currently deprecated and will be removed in a future release.
>

**Comment by sboeuf** [comment]
We don't have the support for a vhost-user backend acting as a client, but thanks for opening this issue, this is something we should definitely put on our roadmap :)

**Comment by sboeuf** [comment]
@rbradford I was thinking we should add an new option `mode=` in both `--net` and `--blk` to specify if we want CH to act as a `server` or a `client`. By default it would act as a `client` (how it works now), which means we wouldn't need to modify the current way the CLI works, but by providing `mode=server`, this would let CH know that both vhost-user-net and vhost-user-blk threads in the VMM should run as servers. I think the `vhost` crate already handles most of these things, which should limit the amount of work from a CH perspective.

**Comment by rbradford** [comment]
@sboeuf As our resident  vhost-user expert, do you think this is something we should do?

**Comment by sboeuf** [comment]
I think since we care about the cloud ecosystem, we care about the OVS use case. And for that reason, we should implement this feature since the default `vhost-user` server on the VMM side is deprecated.

**Comment by sboeuf** [comment]
We need to think about how reboot would work (maybe cloning the fd).
