### ISSUE TITLE
Change default "verbose" level to include warnings

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1779]
I think we should adjust the default verbose level to include warnings (currently hidden under just one `-v`).

@sboeuf @sameo WDYT?

**Comment by sboeuf** [comment]
@rbradford that sounds okay with me, but aren't you concerned that we might get some occurrence of:
```
cloud-hypervisor: 21.301577ms: WARN:vmm/src/cpu.rs:392 -- Guest PIO write to unregistered address 0xXXXX
```
more often. I guess this will force us to fix them more quickly, but I'm just a bit worried about user reporting a lot of these depending on the type of kernel they use and other variable in their environment.

**Comment by rbradford** [comment]
@sboeuf We don't get that with our default kernel any longer, right?

**Comment by sboeuf** [comment]
No I confirm we don't. (I haven't tried all the possibilities tough :))
