### ISSUE TITLE
Windows memory hotplug

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1800]
Adding memory does not work:

![image](https://user-images.githubusercontent.com/588224/94910800-1e520380-049d-11eb-87a8-f1086a976ab2.png)

![image](https://user-images.githubusercontent.com/588224/94910841-2b6ef280-049d-11eb-92aa-791715ac975c.png)

**Comment by sboeuf** [comment]
Same question here, does it work with QEMU?

**Comment by rbradford** [comment]
@liuw @weltling Can you look into this?

**Comment by liuw** [comment]
Can you provide the exact commands that you used?

**Comment by sboeuf** [comment]
Here is how the VM is booted:
```
./target/debug/cloud-hypervisor --kernel OVMF.fd --disk path=windows.raw --cpus boot=1,kvm_hyperv=on --memory size=1G,hotplug_size=3G --serial tty --console off --net tap= --api-socket=/tmp/ch.sock
```
And here is how the memory resizing is performed:
```
./target/debug/ch-remote --api-socket=/tmp/ch.sock resize --memory 2G
```

**Comment by davidhildenbrand** [comment]
> Same question here, does it work with QEMU?

The error in the guest might indicate that the boot/initial memory size of 1 GiB might not be big enough (maybe it refuses to use DMA memory for metadata allocation?). Just a wild guess.

Might be worth trying with more initial memory (e.g., 4..8GB).

**Comment by sboeuf** [comment]
>Might be worth trying with more initial memory (e.g., 4..8GB).

I gave this a quick try, but no luck with more initial memory either.

**Comment by davidhildenbrand** [comment]
> > Might be worth trying with more initial memory (e.g., 4..8GB).
> 
> I gave this a quick try, but no luck with more initial memory either.

Just to make sure, you guys are setting the whole hotpluggable region in the SRAT as MEM_AFFINITY_HOTPLUGGABLE | MEM_AFFINITY_ENABLED, like QEMU, correct?

Without that, Windows hotplug won't work, and Linux SWIOTLB won't be activated automatically (visible when having only DMA memory when booting up).

See https://github.com/qemu/qemu/blob/4c41341af76cfc85b5a6c0f87de4838672ab9f89/hw/i386/acpi-build.c#L2089

**Comment by sboeuf** [comment]
>Just to make sure, you guys are setting the whole hotpluggable region in the SRAT as MEM_AFFINITY_HOTPLUGGABLE | MEM_AFFINITY_ENABLED, like QEMU, correct?

Ah that's interesting! No we're not (I need to double check but I'm pretty we don't do that), I thought this was only used for NUMA. But that should be an easy fix if that's the problem!

**Comment by davidhildenbrand** [comment]
For this reason, QEMU forces NUMA to on (one fake node) with a memory device region (for memory devices like virito-mem,virtio-pmem,DIMMs,NVDIMMs) for this very reason.

Also note that QEMU won't
1. Add any hotplugged memory to e820 after a reboot (also DIMMs). I think you realized that that's also toxic for virtio-mem (I saw you guys fixing a related reboot issue).
2. Adjusting the SRAT with actual PXM of hotplugged memory after a reboot (the whole memory device region is always exposed as mentioned below). I remember there once were patches to change that but caused trouble with Windows guests.

**Comment by sboeuf** [comment]
@davidhildenbrand I hacked the current code to force 0-3G range to be `MEM_AFFINITY_ENABLED`, and 4G-8G range to be `MEM_AFFINITY_ENABLED | MEM_AFFINITY_HOTPLUGGABLE`, but still getting the same error :(

I have verified my hack by booting a Linux VM and dumping my `SRAT` table, it looks fine.

My DSDT shows that each memory slot (we have 8 of them) has a `_PXM` method return 0, which is my proximity domain.

**Comment by davidhildenbrand** [comment]
Hmm, so I'm pretty sure it works under QEMU (although I've never tried myself). SRAT should definitely be required, but maybe there is something else missing?

The error regarding "free resources" and "disable one of the other..." still confuses me TBH.

**Comment by sboeuf** [comment]
@liuw @weltling any idea what this issue might mean? Or maybe you know someone that might help with this?

**Comment by weltling** [comment]
I went for a quick check with QEMU

```
# qemu-system-x86_64 --version
QEMU emulator version 5.2.0 (openSUSE Tumbleweed)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
# uname -a
Linux fringe 5.10.7-1-default #1 SMP Wed Jan 13 06:08:43 UTC 2021 (1c33a89) x86_64 x86_64 x86_64 GNU/Linux
```

The steps listed in the [QEMU documentation](https://github.com/qemu/qemu/blob/master/docs/memory-hotplug.txt) show memory hot add to be functional. The essential parts are 

- The console invocation has to specify the details on the virtual slots, start and maxmemory amount like `-m 1G,slots=3,maxmem=4G`
- In the monitor, the commands below do the job
```
object_add memory-backend-ram,id=mem1,size=1G
device_add pc-dimm,id=dimm1,memdev=mem1 
```

This makes the task manager to immediately show an additional 1G of RAM and the RAM is usable right at the moment.

The second part with hot remove, as particularized in the docs, didn't work as expected on my side. While the `pc-dimm` device could be removed, the memory couldn't. The error text revealed the mem object is in use and cannot be removed.

At this point, seems there's at least the hot plug for Windows guest that can be improved under CH compared to QEMU, while the hot remove might be tricky.

Thanks

**Comment by davidhildenbrand** [comment]
You should check whether removal actually succeeded: „info memory-devices“

„device_del ...“ merely corresponds to an ACPI request to asynchronously remove the device. The request can simply be ignored by the guest and „device_del“ itself won‘t fail. 

Most likely it didn‘t work, because Windows does not support unplug of DIMMs.

**Comment by weltling** [comment]
Thanks for the hint, I can see described behavior. After invoking `device_del dimm1`, `info memory-devices` still shows that device present. The device_del command doesn't show any errors, however.

When running `object_add`/`object_del` without adding a dimm device, there is no error. So it looks like if the dimm device is present, the memory can't be freed.

I made one more check and rebooted QEMU, however the dimm device still can't be deleted. But, might it actually be, that it's QEMU that doesn't want to remove the dimm device? At this point, should probably check same with  a Linux guest and lookup the corresponding code with QEMU.

Thanks.

**Comment by davidhildenbrand** [comment]
AFAIR, QEMU waits for the guest to trigger the eject, which never happens in case of Windows guest.

Anyhow, the focus with Windows guests should be hotplug for now, that‘s what Windows supports.

**Comment by weltling** [comment]
That's true, the hotplug part is where the parity is obvious to be achieved.

Thanks.

**Comment by rbradford** [comment]
We not and probably never will support unplug with for memory with ACPI.

**Comment by davidhildenbrand** [comment]
As a side note: virtio-mem might be coming to Windows at some point.

https://ourwindowsman.wordpress.com/2020/11/03/virtio-mem-goes-to-windows/

https://devconfcz2021.sched.com/event/gmPD/virtio-mem-goes-to-windows

Would be interesting if virtio-mem would have similar issues as ACPI hotplug under CH as described in this thread.
