### ISSUE TITLE
Hotplug size limit check is wrong

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1803]
Boot with 1G and 1G of hotplug space:

```
target/debug/cloud-hypervisor --kernel ~/src/linux/vmlinux --disk path=~/workloads/focal.raw --cpus boot=1 --memory size=1G,hotplug_size=1G --cmdline "root=/dev/vda1 console=ttyS0" --serial tty --console off --api-socket=/tmp/api -v
```

This suggests the maximum ram should be 2GiB...
```
rob@artemis:~/src/cloud-hypervisor (master)$ target/debug/ch-remote --api-socket=/tmp/api resize --memory 2G
Error running command: Server responded with an error: InternalServerError: VmResize(VmResize(MemoryManager(InsufficientHotplugRAM)))
rob@artemis:~/src/cloud-hypervisor (master)$ 
rob@artemis:~/src/cloud-hypervisor (master)$ target/debug/ch-remote --api-socket=/tmp/api resize --memory 2048M
Error running command: Server responded with an error: InternalServerError: VmResize(VmResize(MemoryManager(InsufficientHotplugRAM)))
```

But the next lowest size (2048M - 128M) works:

```
rob@artemis:~/src/cloud-hypervisor (master)$ target/debug/ch-remote --api-socket=/tmp/api resize --memory 1920M
```

**Comment by sboeuf** [comment]
Yes and I think this is only wrong with ACPI hotplug. Please give this a try with virtio-mem.

**Comment by likebreath** [comment]
@sboeuf Right, it only happens w/ ACPI hotplug. Rob's example works fine w/ `virtio-mem`. I will dig into this tomorrow.

**Comment by likebreath** [comment]
I also noticed a similar bug. When booting with 4G and 1G of hotplug space, users will only be able to resize memory update to `5G - 256M` (even `5G - 256M - 128M` with the bug reported in this issue).

I put up a fix for both issues, based on my (basic) understanding the layout for our guest memory. Please correct me if I am wrong. Thanks.
