### ISSUE TITLE
GitHub cross-build check is failing for aarch64 & musl

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1839]
See https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1838/checks?check_run_id=1226485678

```
  = note: /target/debug/deps/libfdt.a(fdt_ro.o): In function `fdt_get_name':
          (.text+0x388): undefined reference to `strrchr'
          collect2: error: ld returned 1 exit status
```

**Comment by rbradford** [comment]
I'm marking this as not-required for the time being.

**Comment by sboeuf** [comment]
This issue has been worked around by pinning the cross-build to rust version 1.46.0, but eventually we want to move back to `stable` once this will have been fixed upstream.

**Comment by rbradford** [comment]
We don't do cross-build as a GH action any longer.
