### ISSUE TITLE
Remove virtio MMIO transport layer

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#1843]
Since we have very few (none?) use cases for non PCI platforms, and supporting both PCI and MMIO as transport layers adds both code and testing/CI complexity, we could remove that feature from the code base.

/cc @cloud-hypervisor/architecture-committee

**Comment by slp** [comment]
This makes sense to me. It will also lead to an interesting scenario in the Rust VMM landscape, with Firecracker and libkrun supporting only MMIO, and Cloud-Hypervisor supporting only PCI.

**Comment by jiangliu** [comment]
Make sense to me, though our dragonball VMM only uses MMIO transport too:)

**Comment by russell-islam** [comment]
Seems reasonable to me.

**Comment by liuw** [comment]
Sounds reasonable to me.

**Comment by michael2012z** [comment]
Sounds a good idea. 

The major impact to AArch64 would be losing the support of GICv2. Because GICv2 doesn't support MSI which is used for virtio-pci. But I think this is OK, after all GICv2 is OLD and not popular in modern servers.
