### ISSUE TITLE
Enable vm.info API to include pid/tid details of vcpu/io/emulator threads

### ISSUE THREAD

**Issue by vineethrp** [cloud-hypervisor/cloud-hypervisor#1862]
While implementing cpupin support in libvirt driver for CH, pid/tid details was a requirement. I am currently parsing procfs to get the details of the threads. 

I think it would be great to have vm.info return the details as:
- we already call vm.info and having this information would avoid parsing procfs
- remote driver support would be easy with vm.info having the details.

**Comment by rbradford** [comment]
I've been looking into this and although we can get a pthread_t for all the threads we create there is no way to map that back to TID or PGID. A thread can find it's own with `gettid()` however we have no way of correctly sharing that back to the main thread and making sure it is current (in terms of threads going away as they will do when a device is reset.)

The best way to this is to parse /proc and use the predictable naming changes we made in the recent PR: #2163
