### ISSUE TITLE
ci: Dynamically assign IP addresses to Windows guest

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1891]
In order to improve the Windows guest CI, it'd be useful to figure out how to run multiple VMs in parallel without running into conflicts from an IP address perspective. The point is, if we can use SAC to reprogram the IP address in the guest, we will be able to assign unique IP subnets to VMs running in parallel, which will let us speed up the CI time.

**Comment by liuw** [comment]
cc @weltling  FYI

**Comment by weltling** [comment]
Certainly it is possible to use SAC. I was using it as documented

`SAC>i 10 192.168.249.2 255.255.255.0 192.168.249.1`

so then one wouldn't need to boot into the OS.

But the serial communication will need to be implemented somehow.

Thanks.

**Comment by liuw** [comment]
> 
> 
> Certainly it is possible to use SAC. I was using it as documented
> 
> `SAC>i 10 192.168.249.2 255.255.255.0 192.168.249.1`
> 
> so then one wouldn't need to boot into the OS.
> 
> But the serial communication will need to be implemented somehow.
> 
> Thanks.

And on top of that, the base image should be updated to not have a statically assigned IP.

**Comment by sboeuf** [comment]
>And on top of that, the base image should be updated to not have a statically assigned IP.

Oh? Is it not possible to replace/override a pre-setup IP address?

**Comment by liuw** [comment]
> 
> 
> > And on top of that, the base image should be updated to not have a statically assigned IP.
> 
> Oh? Is it not possible to replace/override a pre-setup IP address?

We should be able to override the IP address. But that still leaves a small window in which the guest has a statically configured IP address. That may lead to races that are hard to debug, unless the CI can make sure that IP address will never be part of the dynamically allocated range.

**Comment by sboeuf** [comment]
>We should be able to override the IP address. But that still leaves a small window in which the guest has a statically configured IP address. That may lead to races that are hard to debug, unless the CI can make sure that IP address will never be part of the dynamically allocated range.

We discussed that with @rbradford and it's totally okay to make the CI avoid the statically assigned IP, this way we will never run into any race condition.

**Comment by weltling** [comment]
The command i mentioned will override the IP address in the guest, that's what i mean. There is no need to boot into the guest or pre-configure it - the IP configuration there will be just reset. It is only about a way to run this SAC command after the boot.

It need to be matching with the TAP device, probably. The TAP device will be the gateway. Probably the second part is on whether just passing `--tap=` is good enough.

Thanks.

**Comment by sboeuf** [comment]
@weltling try to rely as much as possible on the existing framework that we're using for other integration tests. Here is how the network is setup: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/tests/integration.rs#L671-L676
Be careful that the subnet don't match the statically assigned IP: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/tests/integration.rs#L664
