### ISSUE TITLE
Add more Windows integration tests

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1916]
Take inspiration from the current integration tests, but at the very least should add:

- [ ] Multiple block devices
- [ ] Multiple network devices
- [ ] Block hotplug test (#2539)
- [x] Net hotplug test

**Comment by rbradford** [comment]
@weltling I think we're getting close on this, if not done, are there any tests you think that should be added that are still missing?

**Comment by weltling** [comment]
@rbradford there's nothing big i'd name OTTOMH, the lists you've created previously are good and i'd pursue the remaining items if no one beats me to it. I had some other plans regarding revising hyper-v enlightenments and some AML pieces i saw while comparing with QEMU, but I'd guess that would demand tests as it is being done, couldn't tell which would show as necessary

Thanks

**Comment by weltling** [comment]
@rbradford the third item from the description is actually done, see the linked ticket. I planned to implement the first two items for this month, if no one beats me to it.

Thanks.
