### ISSUE TITLE
fail to cargo build --release cloud hypervisor  in arch64

### ISSUE THREAD

**Issue by magnate3** [cloud-hypervisor/cloud-hypervisor#1920]
root@cloud:~/hyper/cloud-hypervisor# lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  1
Core(s) per socket:  32
Socket(s):           2
NUMA node(s):        4
Vendor ID:           ARM
Model:               2
Model name:          Cortex-A72
Stepping:            r0p2
BogoMIPS:            100.00
L1d cache:           32K
L1i cache:           48K
L2 cache:            1024K
L3 cache:            16384K
NUMA node0 CPU(s):   0-15
NUMA node1 CPU(s):   16-31
NUMA node2 CPU(s):   32-47
NUMA node3 CPU(s):   48-63
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
root@cloud:~/hyper/cloud-hypervisor# uname -a
Linux cloud 5.5.19-050519-generic #202004210831 SMP Tue Apr 21 08:49:56 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
root@cloud:~/hyper/cloud-hypervisor# 

**cloud-hypervisor#  cargo build --release**
   Compiling vm-device v0.1.0 (/root/hyper/cloud-hypervisor/vm-device)
   Compiling net_gen v0.1.0 (/root/hyper/cloud-hypervisor/net_gen)
   Compiling block_util v0.1.0 (/root/hyper/cloud-hypervisor/block_util)
   Compiling qcow v0.1.0 (/root/hyper/cloud-hypervisor/qcow)
   Compiling devices v0.1.0 (/root/hyper/cloud-hypervisor/devices)
   Compiling net_util v0.1.0 (/root/hyper/cloud-hypervisor/net_util)
   Compiling vhost_user_backend v0.1.0 (/root/hyper/cloud-hypervisor/vhost_user_backend)
   Compiling kvm-ioctls v0.5.0 (https://github.com/cloud-hypervisor/kvm-ioctls?branch=ch#64427395)
   Compiling vhost_user_block v0.1.0 (/root/hyper/cloud-hypervisor/vhost_user_block)
   Compiling vhost_user_net v0.1.0 (/root/hyper/cloud-hypervisor/vhost_user_net)
   Compiling hypervisor v0.1.0 (/root/hyper/cloud-hypervisor/hypervisor)
   Compiling vfio-ioctls v0.1.0 (https://github.com/cloud-hypervisor/vfio-ioctls?branch=ch#49cc3626)
   Compiling arch v0.1.0 (/root/hyper/cloud-hypervisor/arch)
   Compiling vm-allocator v0.1.0 (/root/hyper/cloud-hypervisor/vm-allocator)
   Compiling pci v0.1.0 (/root/hyper/cloud-hypervisor/pci)
   Compiling virtio-devices v0.1.0 (/root/hyper/cloud-hypervisor/virtio-devices)
   Compiling vmm v0.1.0 (/root/hyper/cloud-hypervisor/vmm)
error[E0425]: cannot find value `APIC_START` in module `layout`
    --> vmm/src/cpu.rs:1004:32
     |
1004 |         madt.write(36, layout::APIC_START);
     |                                ^^^^^^^^^^ not found in `layout`

error[E0425]: cannot find value `IOAPIC_START` in module `layout`
    --> vmm/src/cpu.rs:1025:35
     |
1025 |             apic_address: layout::IOAPIC_START.0 as u32,
     |                                   ^^^^^^^^^^^^ not found in `layout`

error[E0425]: cannot find value `RSDP_POINTER` in module `layout`
   --> vmm/src/acpi.rs:118:31
    |
118 |     let rsdp_offset = layout::RSDP_POINTER;
    |                               ^^^^^^^^^^^^ not found in `layout`

error[E0599]: no method named `allocate_io_addresses` found for struct `std::sync::MutexGuard<'_, vm::vm_allocator::SystemAllocator>` in the current scope
   --> vmm/src/device_manager.rs:870:14
    |
870 |             .allocate_io_addresses(Some(GuestAddress(0xae00)), 0x10, None)
    |              ^^^^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `allocate_mmio_addresses`

error[E0609]: no field `io_bus` on type `std::sync::Arc<device_manager::AddressManager>`
   --> vmm/src/device_manager.rs:877:14
    |
877 |             .io_bus
    |              ^^^^^^ unknown field

error[E0599]: no method named `allocate_io_addresses` found for struct `std::sync::MutexGuard<'_, vm::vm_allocator::SystemAllocator>` in the current scope
   --> vmm/src/device_manager.rs:906:14
    |
906 |             .allocate_io_addresses(Some(GuestAddress(0x0a00)), 0x18, None)
    |              ^^^^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `allocate_mmio_addresses`

error[E0609]: no field `io_bus` on type `std::sync::Arc<device_manager::AddressManager>`
   --> vmm/src/device_manager.rs:911:14
    |
911 |             .io_bus
    |              ^^^^^^ unknown field

error[E0599]: no method named `allocate_io_addresses` found for struct `std::sync::MutexGuard<'_, vm::vm_allocator::SystemAllocator>` in the current scope
    --> vmm/src/device_manager.rs:1203:14
     |
1203 |             .allocate_io_addresses(Some(GuestAddress(0x3c0)), 0x8, None)
     |              ^^^^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `allocate_mmio_addresses`

error[E0609]: no field `io_bus` on type `std::sync::Arc<device_manager::AddressManager>`
    --> vmm/src/device_manager.rs:1207:14
     |
1207 |             .io_bus
     |              ^^^^^^ unknown field

error[E0599]: no method named `allocate_io_addresses` found for struct `std::sync::MutexGuard<'_, vm::vm_allocator::SystemAllocator>` in the current scope
    --> vmm/src/device_manager.rs:1237:14
     |
1237 |             .allocate_io_addresses(Some(GuestAddress(0xb000)), 0x1, None)
     |              ^^^^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `allocate_mmio_addresses`

error[E0609]: no field `io_bus` on type `std::sync::Arc<device_manager::AddressManager>`
    --> vmm/src/device_manager.rs:1241:14
     |
1241 |             .io_bus
     |              ^^^^^^ unknown field

error[E0599]: no method named `allocate_io_addresses` found for struct `std::sync::MutexGuard<'_, vm::vm_allocator::SystemAllocator>` in the current scope
    --> vmm/src/device_manager.rs:1254:14
     |
1254 |             .allocate_io_addresses(Some(GuestAddress(0xb008)), 0x4, None)
     |              ^^^^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `allocate_mmio_addresses`

error[E0609]: no field `io_bus` on type `std::sync::Arc<device_manager::AddressManager>`
    --> vmm/src/device_manager.rs:1258:14
     |
1258 |             .io_bus
     |              ^^^^^^ unknown field

error: aborting due to 13 previous errors

Some errors have detailed explanations: E0425, E0599, E0609.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `vmm`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by MrXinWang** [comment]
Hi @magnate3 

I think the problem comes from the command that you used to build cloud-hypervisor. It should be:
```
cargo build --release --no-default-features --features kvm
```

Highly recommended to read the [document](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/arm64.md).

**Comment by MrXinWang** [comment]
Closing this as addressed

**Comment by MrXinWang** [comment]
@rbradford

**Comment by rbradford** [comment]
@MrXinWang Do you want to see if you can do something like: https://github.com/rust-lang/cargo/issues/1197#issuecomment-268203727 to set the default features for each arch?

**Comment by MrXinWang** [comment]
@rbradford Yes I would love to do this :) I will start to try to work on it now.

**Comment by magnate3** [comment]
I still can not solve the problem
root@cloud:~/hyper/cloud-hypervisor# cargo build --release --no-default-features --features kvm
    Finished release [optimized] target(s) in 0.15s
root@cloud:~/hyper/cloud-hypervisor# cargo build --release --target=aarch64-unknown-linux-musl --all
warning: use of deprecated type alias `libc::time_t`: This type is changed to 64-bit in musl 1.2.0, we'll follow that change in the future release. See #1848 for more info.
 --> devices/src/legacy/cmos.rs:5:37
  |
5 | use libc::{clock_gettime, gmtime_r, time_t, timespec, tm, CLOCK_REALTIME};
  |                                     ^^^^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: use of deprecated type alias `libc::time_t`: This type is changed to 64-bit in musl 1.2.0, we'll follow that change in the future release. See #1848 for more info.
  --> devices/src/legacy/cmos.rs:86:30
   |
86 |                     let now: time_t = timespec.tv_sec;
   |                              ^^^^^^

warning: 2 warnings emitted

   Compiling vhost_user_net v0.1.0 (/root/hyper/cloud-hypervisor/vhost_user_net)
   Compiling vhost_user_block v0.1.0 (/root/hyper/cloud-hypervisor/vhost_user_block)
   Compiling vmm v0.1.0 (/root/hyper/cloud-hypervisor/vmm)
   Compiling vhost_user_fs v0.1.0 (/root/hyper/cloud-hypervisor/vhost_user_fs)
error[E0425]: cannot find value `APIC_START` in module `layout`
    --> vmm/src/cpu.rs:1004:32
     |
1004 |         madt.write(36, layout::APIC_START);
     |                                ^^^^^^^^^^ not found in `layout`

error[E0425]: cannot find value `IOAPIC_START` in module `layout`
    --> vmm/src/cpu.rs:1025:35
     |
1025 |             apic_address: layout::IOAPIC_START.0 as u32,
     |                                   ^^^^^^^^^^^^ not found in `layout`

error[E0425]: cannot find value `RSDP_POINTER` in module `layout`
   --> vmm/src/acpi.rs:118:31
    |
118 |     let rsdp_offset = layout::RSDP_POINTER;
    |                               ^^^^^^^^^^^^ not found in `layout`

error[E0599]: no method named `allocate_io_addresses` found for struct `std::sync::MutexGuard<'_, vm::vm_allocator::SystemAllocator>` in the current scope
   --> vmm/src/device_manager.rs:870:14
    |
870 |             .allocate_io_addresses(Some(GuestAddress(0xae00)), 0x10, None)
    |              ^^^^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `allocate_mmio_addresses`

error[E0609]: no field `io_bus` on type `std::sync::Arc<device_manager::AddressManager>`
   --> vmm/src/device_manager.rs:877:14
    |
877 |             .io_bus
    |              ^^^^^^ unknown field

error[E0599]: no method named `allocate_io_addresses` found for struct `std::sync::MutexGuard<'_, vm::vm_allocator::SystemAllocator>` in the current scope
   --> vmm/src/device_manager.rs:906:14
    |
906 |             .allocate_io_addresses(Some(GuestAddress(0x0a00)), 0x18, None)
    |              ^^^^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `allocate_mmio_addresses`

error[E0609]: no field `io_bus` on type `std::sync::Arc<device_manager::AddressManager>`
   --> vmm/src/device_manager.rs:911:14
    |
911 |             .io_bus
    |              ^^^^^^ unknown field

error[E0599]: no method named `allocate_io_addresses` found for struct `std::sync::MutexGuard<'_, vm::vm_allocator::SystemAllocator>` in the current scope
    --> vmm/src/device_manager.rs:1203:14
     |
1203 |             .allocate_io_addresses(Some(GuestAddress(0x3c0)), 0x8, None)
     |              ^^^^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `allocate_mmio_addresses`

error[E0609]: no field `io_bus` on type `std::sync::Arc<device_manager::AddressManager>`
    --> vmm/src/device_manager.rs:1207:14
     |
1207 |             .io_bus
     |              ^^^^^^ unknown field

error[E0599]: no method named `allocate_io_addresses` found for struct `std::sync::MutexGuard<'_, vm::vm_allocator::SystemAllocator>` in the current scope
    --> vmm/src/device_manager.rs:1237:14
     |
1237 |             .allocate_io_addresses(Some(GuestAddress(0xb000)), 0x1, None)
     |              ^^^^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `allocate_mmio_addresses`

error[E0609]: no field `io_bus` on type `std::sync::Arc<device_manager::AddressManager>`
    --> vmm/src/device_manager.rs:1241:14
     |
1241 |             .io_bus
     |              ^^^^^^ unknown field

error[E0599]: no method named `allocate_io_addresses` found for struct `std::sync::MutexGuard<'_, vm::vm_allocator::SystemAllocator>` in the current scope
    --> vmm/src/device_manager.rs:1254:14
     |
1254 |             .allocate_io_addresses(Some(GuestAddress(0xb008)), 0x4, None)
     |              ^^^^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `allocate_mmio_addresses`

error[E0609]: no field `io_bus` on type `std::sync::Arc<device_manager::AddressManager>`
    --> vmm/src/device_manager.rs:1258:14
     |
1258 |             .io_bus
     |              ^^^^^^ unknown field

error: aborting due to 13 previous errors

Some errors have detailed explanations: E0425, E0599, E0609.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `vmm`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish..

= note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--eh-frame-hdr" "-nostartfiles" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crti.o" "-L" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib" "-L" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained" "/root/hyper/cloud-hypervisor/target/aarch64-unknown-linux-musl/release/deps/vhost_user_net-7ab81a3d9faf691c.vhost_user_net.f8lxph0z-cgu.2.rcgu.o" "-o" "/root/hyper/cloud-hypervisor/target/aarch64-unknown-linux-musl/release/deps/vhost_user_net-7ab81a3d9faf691c" "-Wl,--gc-sections" "-static" "-no-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/root/hyper/cloud-hypervisor/target/aarch64-unknown-linux-musl/release/deps" "-L" "/root/hyper/cloud-hypervisor/target/release/deps" "-L" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/tmp/rustckLIXtK/libunwind-7a7db0d68fb707fa.rlib" "/tmp/rustckLIXtK/liblibc-f904a5ce7e6fe846.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/libcompiler_builtins-64ce58124784d85c.rlib" "-Wl,-Bdynamic" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crtn.o"
  = note: /tmp/rustckLIXtK/liblibc-f904a5ce7e6fe846.rlib(vfprintf.lo): In function `fmt_fp':
          /build/musl-1.1.24/src/stdio/vfprintf.c:210: undefined reference to `__addtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:225: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:228: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:229: undefined reference to `__addtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:232: undefined reference to `__addtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:233: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:246: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:246: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:268: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:275: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:275: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:331: undefined reference to `__addtf3'
          /tmp/rustckLIXtK/liblibc-f904a5ce7e6fe846.rlib(frexpl.lo): In function `frexpl':
          /build/musl-1.1.24/src/math/frexpl.c:16: undefined reference to `__multf3'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--eh-frame-hdr" "-nostartfiles" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crti.o" "-L" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib" "-L" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained" "/root/hyper/cloud-hypervisor/target/aarch64-unknown-linux-musl/release/deps/vhost_user_block-bd3dc1d0902e68d3.vhost_user_block.1oaasaby-cgu.2.rcgu.o" "-o" "/root/hyper/cloud-hypervisor/target/aarch64-unknown-linux-musl/release/deps/vhost_user_block-bd3dc1d0902e68d3" "-Wl,--gc-sections" "-static" "-no-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/root/hyper/cloud-hypervisor/target/aarch64-unknown-linux-musl/release/deps" "-L" "/root/hyper/cloud-hypervisor/target/release/deps" "-L" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/tmp/rustchsP07g/libunwind-7a7db0d68fb707fa.rlib" "/tmp/rustchsP07g/liblibc-f904a5ce7e6fe846.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/libcompiler_builtins-64ce58124784d85c.rlib" "-Wl,-Bdynamic" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crtn.o"
  = note: /tmp/rustchsP07g/liblibc-f904a5ce7e6fe846.rlib(vfprintf.lo): In function `fmt_fp':
          /build/musl-1.1.24/src/stdio/vfprintf.c:210: undefined reference to `__addtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:225: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:228: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:229: undefined reference to `__addtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:232: undefined reference to `__addtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:233: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:246: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:246: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:268: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:275: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:275: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:331: undefined reference to `__addtf3'
          /tmp/rustchsP07g/liblibc-f904a5ce7e6fe846.rlib(frexpl.lo): In function `frexpl':
          /build/musl-1.1.24/src/math/frexpl.c:16: undefined reference to `__multf3'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--eh-frame-hdr" "-nostartfiles" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crti.o" "-L" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib" "-L" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained" "/root/hyper/cloud-hypervisor/target/aarch64-unknown-linux-musl/release/deps/vhost_user_fs-1f224d06ad54fbd2.vhost_user_fs.cuk03e44-cgu.15.rcgu.o" "-o" "/root/hyper/cloud-hypervisor/target/aarch64-unknown-linux-musl/release/deps/vhost_user_fs-1f224d06ad54fbd2" "-Wl,--gc-sections" "-static" "-no-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/root/hyper/cloud-hypervisor/target/aarch64-unknown-linux-musl/release/deps" "-L" "/root/hyper/cloud-hypervisor/target/release/deps" "-L" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/tmp/rustc8nBzqL/libunwind-7a7db0d68fb707fa.rlib" "/tmp/rustc8nBzqL/liblibc-f904a5ce7e6fe846.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/libcompiler_builtins-64ce58124784d85c.rlib" "-Wl,-Bdynamic" "-lfdt" "/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crtn.o"
  = note: /tmp/rustc8nBzqL/liblibc-f904a5ce7e6fe846.rlib(vfprintf.lo): In function `fmt_fp':
          /build/musl-1.1.24/src/stdio/vfprintf.c:210: undefined reference to `__addtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:225: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:228: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:229: undefined reference to `__addtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:232: undefined reference to `__addtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:233: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:246: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:246: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:268: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:275: undefined reference to `__subtf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:275: undefined reference to `__multf3'
          /build/musl-1.1.24/src/stdio/vfprintf.c:331: undefined reference to `__addtf3'
          /tmp/rustc8nBzqL/liblibc-f904a5ce7e6fe846.rlib(frexpl.lo): In function `frexpl':
          /build/musl-1.1.24/src/math/frexpl.c:16: undefined reference to `__multf3'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: build failed

**Comment by MrXinWang** [comment]
@magnate3 Can you please use the container to build the musl target instead of using the cargo command line?

Try this in the cloud-hypervisor directory:
```
sudo ./scripts/dev_cli.sh build --release --libc musl
```

**Comment by magnate3** [comment]
there is no problem when  I build  in container with  ./scripts/dev_cli.sh build --release .
