### ISSUE TITLE
Drop max_phys_bits option?

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#1975]
It was added to work around an issue for booting Windows. The issue has been fixed by https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1969.

**Comment by rbradford** [comment]
@sameo Any benefit in keeping this? We have seen other bugs in the past when running nested due to incorrect physical bits being reported inside the L1 VM.

**Comment by liuw** [comment]
Closing this since nothing much has happened in this discussion.
