### ISSUE TITLE
Drop QCOW support

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1985]
Should we still keep it? The code only implements a subset of features (in particular no compressed blocks) which means it can't be used for images out of the box from Ubuntu. We also do not have support for using it with io_uring which means it cannot perform as well as raw images.

@liuw Do you care about QCOW support?

**Comment by iggy** [comment]
Just a user over here, but I do have a couple of disk images that are using qcow2. While I _can_ convert them, I intentionally made them fairly large based on the fact that they were qcow2. But I also understand if it's a maintenance burden.

**Comment by liuw** [comment]
No. I don't really care about QCOW support. Dropping this incomplete implementation from Cloud Hypervisor would be fine by me.

It would be good to clarify how we can add support for disk formats though. When / if someone decides QCOW support is important and is willing to put effort into it, there should be a path forward.

**Comment by rbradford** [comment]
Okay. Let's keep QCOW support and instead we need to work towards a solution with an asynchronous file backend.

**Comment by rbradford** [comment]
I want to revisit this. I was trying to fix the qcow2 code for the vmm-sys-util update and I realised that I didn't understand it, that I never would want to understand it or even care about it. Given that it doesn't actually support any supported distros images out of the box (no compressed support.) I would strongly push for removing this.

**Comment by sameo** [comment]
> I want to revisit this. I was trying to fix the qcow2 code for the vmm-sys-util update and I realised that I didn't understand it, that I never would want to understand it or even care about it. Given that it doesn't actually support any supported distros images out of the box (no compressed support.) I would strongly push for removing this.

Let's remove it.
