### ISSUE TITLE
VmExit::Reset during Ubuntu boot causes all vcpu threads to respawn

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/cloud-hypervisor#2003]
While booting to '''focal-server-cloudimg-amd64-custom.qcow2''' image recommended at https://github.com/cloud-hypervisor/rust-hypervisor-firmware/issues/77 I am noticing an unexpected behavior.

Guest Kernel reports the following failure:

```
[    0.211737] hctosys: unable to open rtc device (rtc0)
[    0.212385] md: Waiting for all devices to be available before autodetect
[    0.212924] md: If you don't use raid, use raid=noautodetect
[    0.213501] md: Autodetecting RAID arrays.
[    0.213815] md: autorun ...
[    0.213993] md: ... autorun DONE.
[    0.214258] VFS: Cannot open root device "PARTUUID=c1789075-d188-466c-b2a8-af2a999514f9" or unknown-block(0,0): error -6
[    0.214957] Please append a correct "root=" boot option; here are the available partitions:
[    0.215475] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    0.216078] CPU: 1 PID: 1 Comm: swapper/0 Not tainted 5.4.0-39-generic #43-Ubuntu
[    0.216731] Call Trace:
[    0.216929]  dump_stack+0x6d/0x9a
[    0.217139]  panic+0x101/0x2e3
[    0.217346]  mount_block_root+0x23f/0x2e8
[    0.217598]  mount_root+0x38/0x3a
[    0.217808]  prepare_namespace+0x13f/0x194
[    0.218064]  kernel_init_freeable+0x231/0x255
[    0.218341]  ? rest_init+0xb0/0xb0
[    0.218565]  kernel_init+0xe/0x100
[    0.218864]  ret_from_fork+0x1f/0x40
[    0.219146] Kernel Offset: 0x14800000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
```

After this failure the guest goes through VmExit:Reset and '''boots just fine the next time'''. I also confirm the PARTUUID passed to kernel is correct.

```
testuser@chtestvm:~$ blkid
/dev/vda1: LABEL="cloudimg-rootfs" UUID="ee1d5a01-5dc6-4332-89e2-b9820a7b26f0" TYPE="ext4" PARTUUID="c1789075-d188-466c-b2a8-af2a999514f9"
/dev/vda15: LABEL_FATBOOT="UEFI" LABEL="UEFI" UUID="3204-608D" TYPE="vfat" PARTUUID="fd590f07-ec4c-4833-ad22-a3cc81e38e9e"
/dev/vdb: SEC_TYPE="msdos" LABEL_FATBOOT="CIDATA" LABEL="CIDATA" UUID="1BAB-A03D" TYPE="vfat"
```

Please find attached serial.log and verbose (focal-custom.log) logs from Cloud-hypervisor. These logs capture a complete boot and shutdown of the guest. I commented out various debug! statements in cloud-hypervisor code to create a smaller verbose log from CH.

[serial.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/5592984/serial.log)
[focal-custom-ch.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/5592985/focal-custom-ch.log)

I only see this behavior with focal images and not with bionic images. I am not sure if this is an issue with Guest image alone, as the guest VM boots just fine after a reset.

**Comment by rbradford** [comment]
This is the way the Ubuntu image boots. The first time it boots without and initrd and then fails and the second time it boots with the initrd and succeeds (the initrd contains the virtio-block module needed to boot.) The grub config is updated so that subsequent boots will always use the initrd. As you spotted this not the case in bionic (it was in fact added in eoan.)

**Comment by rbradford** [comment]
(They do this to try and boot quicker by having a core set of drivers built into a smaller kernel which should let most hardware boot.)

**Comment by rbradford** [comment]
Closing as this is expected Ubuntu boot behaviour.

**Comment by praveen-pk** [comment]
I confirmed the same behavior while booting the same image with qemu in UEFI mode while using virtio-blk disk.
