### ISSUE TITLE
Migrate to upstream vm-virtio and vhost-user-backend

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2055]
The code that is shared between vhost-user-net and vhost-user-block backends and their virtio equivalents depends on vm-virtio. This means that we cannot migrate to upstream vhost-user-backend without also migrating to upstream vm-virtio.

**Comment by rbradford** [comment]
@sameo I know you tried this in the past with https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1446

We need to make a decision as to whether:

1. We move to upstream vm-virtio and vhost-user-backend and all the changes that entails
2. Move the vhost-user-net and vhost-user-block backends to their own repository/repositories forking the shared code and switching them over to depend on upstream vhost-user-backend and vm-virtio
3. Delete vhost-user-net/vhost-user-block backends. We would probably need to drop the VMM side as we wouldn't be able to easily test them.
4. Status quo maintain in-tree forks of these crates indefinitely.

**Comment by sameo** [comment]
We should aim at moving to upstream vm-virtio and vhost-user-backend, migrating our virtio and vhost-user backends to them.

For now, I think we want to keep our net and block vhost-user backends.

**Comment by rbradford** [comment]
@sameo I agree. I propose that we create a new module called `transition` inside our vm-virtio crate/directory that re-exposes vm-virtio `Queue` and related structures via `pub use`. That would give us a path to transition in smaller steps.

**Comment by rbradford** [comment]
Partially completed by #3652. Do we still want to go ahead and do the same for vhost-user-backend?

**Comment by sboeuf** [comment]
> Partially completed by #3652. Do we still want to go ahead and do the same for vhost-user-backend?

If this doesn't require too much changes, then yes. Let me assess and I'll get back to you.
