### ISSUE TITLE
Update vhost-user-(blk|net)-testing docs

### ISSUE THREAD

**Issue by iggy** [cloud-hypervisor/cloud-hypervisor#2064]
Since the code to autolaunch the `vhost-user-(blk|net)` backends was removed, the docs for testing that functionality should be updated to include manually launching them.

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/vhost-user-blk-testing.md
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/vhost-user-net-testing.md

**Comment by rbradford** [comment]
Hi @iggy, thanks for opening a bug. I read through those documents and both seem to use a separate daemon rather than relying on the autolaunch functionality. In fact i'm pretty certain they haven't been changed since that functionality was added! :-)

**Comment by iggy** [comment]
Ahh. I think I got confused when looking at those docs. I thought all that was to setup the system to be able to run the backend. I didn't realize that was the process just to run the backend. No wonder you wanted to ditch that code :rofl:. Thanks for looking at it for me.
