### ISSUE TITLE
Dedicated iothreads

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/cloud-hypervisor#2077]
Qemu supports creating dedicated iothreads per guest device to allow I/O workload to be distributed across chosen host CPUs.
More info at https://github.com/qemu/qemu/blob/master/docs/devel/multiple-iothreads.txt

Is this feature on Cloud-hypervisor's roadmap?

**Comment by rbradford** [comment]
@praveen-pk What do you mean? We already have separate threads for each queue with virtio-block when it runs with multiple queues. (Similarly for queue pairs for virtio-net.)

**Comment by praveen-pk** [comment]
Seems like my ask was not clear from above, let me restate.

Qemu allows iothreads to be defined (with polling parameters) via an input arguments. Guest devices are in turn assigned to these iothreads. Following being the options for defining an iothread:

-object iothread,id=id,poll-max-ns=poll-max-ns,poll-grow=poll-grow,poll-shrink=poll-shrink 

This approach of being able to configure iothreads from input arguments allows libvirt to be able to support iothread management with the following settings:
```
<domain>
  ...
  <iothreads>4</iothreads>
  <iothreadids>
    <iothread id="2"/>
    <iothread id="4"/>
    <iothread id="6"/>
    <iothread id="8"/>
  </iothreadids>
  <iothreadpin iothread="1" cpuset="5,6"/>
  <iothreadpin iothread="2" cpuset="7,8"/>
  <iothread_period>1000000</iothread_period>
  <iothread_quota>-1</iothread_quota>
  ...
</domain>
```
Right now, cloud-hypervisor does create dedicated I/O threads. In order to iothread pinning (and other settings), there is no way to map the iothread settings in libvirt's VM definition to iothreads in cloud-hypervisor.

If cloud-hypervisor could allow iothreads to be defined via input arguments, libvirt can spawn cloud-hypervisor with appropriate input parameters. This allow libvirt to have a clear mapping between iothreads defined in input VM definition to the threads spawned by cloud-hypervisor.

**Comment by rbradford** [comment]
Having discussed this with you offline what we need is a predictable naming scheme for the threads. We currently create one thread per queue for most virtio devices. The caveat being virtio-net where this is one thread per queue of rx/tx plus an optional thread if the MQ control thread is enabled.

**Comment by rbradford** [comment]
I'm thinking we name the threads after the virtio devices's id and append a suffix so that the threads are deterministically named and differentiable from each other.
