### ISSUE TITLE
More flexible serial/console handling

### ISSUE THREAD

**Issue by iggy** [cloud-hypervisor/cloud-hypervisor#2084]
It would be nice to be able to route the input/output of serial separately. For example, one use case I have currently is to send the serial output to a file and get the input from a socket/pipe/etc.

Currently the option exists to use a file as the output, but there's no way to then get any input into the serial port.

Similar functionality for the console might be nice too.

I'll look at how other hypervisors handle this and update this issue with some of my findings.

**Comment by rbradford** [comment]
@iggy Okay sounds good, PTY support is being added for libvirt so this might be useful for your use case.

**Comment by iggy** [comment]
This tab got lost in the shuffle. Just making it back around to it.

As far as what other hypervisors do, it looks like qemu is the most featureful.

Qemu features:
* Host devices can be one-way or two-way
* Supported two-way connections
  * pipe - creates 2 pipes; `.in` (host -> guest) and `.out` (guest -> host)
  * socket - tcp/unix; can act as a server or a client
  * stdio - similar to CH's existing console/serial support, but supports mux'ing (as mentioned below)
  * pty - coming soon to CH
  * some others that are specific to Qemu
* Supported one-way connections
  * UDP - send all guest output to a server
  * ringbuf - write guest output to a ringbuf
  * file - write guest output to a file
  * serial - write guest output to a serial device/tty
* Has the ability to mux multiple host outputs into a single "pane"
  * i.e. serial output and the qemu "monitor" on the same host output
  * or serial outpu and console output on stdio
  * uses escape sequences to switch between

While I doubt all of this should be supported some of it could definitely be useful.

**Comment by rbradford** [comment]
Since we now can work with a PTY this can be combined with `socat` to achieve all of the above, don't you think so @iggy?

**Comment by russell-islam** [comment]
Is there any security concern if we use socat outside of CLH? Also need to somehow kill the socat process after CLH shutdown.
