### ISSUE TITLE
in arm64 , build rust-hypervisor-firmware fail

### ISSUE THREAD

**Issue by magnate3** [cloud-hypervisor/cloud-hypervisor#2093]
rust-hypervisor-firmware# cargo build --release --target target.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem
   Compiling hypervisor-fw v0.1.0 (/root/hyper/rust-hypervisor-firmware)
error: instruction requires: Not 64-bit mode
    movl %eax, %cr3
    ^
error: instruction requires: Not 64-bit mode
    movl %cr4, %eax
    ^
error: instruction requires: Not 64-bit mode
    movl %eax, %cr4
    ^
error: instruction requires: Not 64-bit mode
    movl %cr0, %eax
    ^
error: instruction requires: Not 64-bit mode
    movl %eax, %cr0
    ^
error: instruction requires: Not 64-bit mode
    lgdtl GDT64_PTR
    ^
error: instruction requires: Not 64-bit mode
    ljmpl $0x08, $rust64_start
    ^
error: instruction requires: Not 64-bit mode
   |
note: instantiated into assembly here
  --> <inline asm>:24:5
   |
24 |     movl %eax, %cr3
   |     ^

error: instruction requires: Not 64-bit mode
   |
note: instantiated into assembly here
  --> <inline asm>:27:5
   |
27 |     movl %cr4, %eax
   |     ^

error: instruction requires: Not 64-bit mode
   |
note: instantiated into assembly here
  --> <inline asm>:29:5
   |
29 |     movl %eax, %cr4
   |     ^

error: instruction requires: Not 64-bit mode
   |
note: instantiated into assembly here
  --> <inline asm>:36:5
   |
36 |     movl %cr0, %eax
   |     ^

error: instruction requires: Not 64-bit mode
   |
note: instantiated into assembly here
  --> <inline asm>:38:5
   |
38 |     movl %eax, %cr0
   |     ^

error: instruction requires: Not 64-bit mode
   |
note: instantiated into assembly here
  --> <inline asm>:43:5
   |
43 |     lgdtl GDT64_PTR
   |     ^

error: instruction requires: Not 64-bit mode
   |
note: instantiated into assembly here
  --> <inline asm>:48:5
   |
48 |     ljmpl $0x08, $rust64_start
   |     ^

error: aborting due to 7 previous errors

error: could not compile `hypervisor-fw`

To learn more, run the command again with --verbose.

**Comment by rbradford** [comment]
rust-hypervisor-fw only works on x86_64. There are no plans to port it.
