### ISSUE TITLE
vCPU thread SIGSYS on RHEL7

### ISSUE THREAD

**Issue by dyoung23** [cloud-hypervisor/cloud-hypervisor#2111]
I'm new about CLH.So I followed the README.md guide to run a vm.
```
$ pushd $CLOUDH
$ wget https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
$ qemu-img convert -p -f qcow2 -O raw focal-server-cloudimg-amd64.img focal-server-cloudimg-amd64.raw
$ wget https://github.com/cloud-hypervisor/rust-hypervisor-firmware/releases/download/0.2.8/hypervisor-fw
$ popd
$ pushd $CLOUDH
$ sudo setcap cap_net_admin+ep ./cloud-hypervisor/target/release/cloud-hypervisor
$ ./cloud-hypervisor/target/release/cloud-hypervisor \
	--kernel ./hypervisor-fw \
	--disk path=focal-server-cloudimg-amd64.raw \
	--cpus boot=4 \
	--memory size=1024M \
	--net "tap=,mac=,ip=,mask=" \
	--rng
$ popd
```
After that,I found a new nic named vmtap0 with IP 192.168.249.1.I'm very confused about how to connect to this vm.And if using ssh,which password I should use.
Thanks for your any help.

**Comment by sboeuf** [comment]
Hi @dyoung23 
First thing, make sure you boot the VM with a `cloudinit` disk attached, so that it will provision the VM with the user `cloud` and password `cloud123`. Run the following script `./scripts/create-cloud-init.sh` to generate the `cloudinit` image. You'll find the image in `/tmp/ubuntu-cloudinit.img` on your machine.
Your Cloud-Hypervisor command line will look like:
```
...
--disk path=focal-server-cloudimg-amd64.raw path=/tmp/ubuntu-cloudinit.img
...
```

Once the VM is booted, assign an IP address to the network interface (assuming the interface name is `ens3`):
```
$ sudo ip addr add 192.168.249.2/24 dev ens3
$ sudo ip link set up ens3
```
At this point, you should be able to ssh from the host into the guest:
```
$ ssh cloud@192.168.249.2
```

**Comment by dyoung23** [comment]
Thank you @sboeuf.
Following your guide,I create the image `ubuntu-cloudinit.img`,and run clh command below.
```
./cloud-hypervisor/target/release/cloud-hypervisor --kernel ./hypervisor-fw --disk path=focal-server-cloudimg-amd64.raw path=/tmp/ubuntu-cloudinit.img  --cpus boot=4 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng
```
As the result,it did not create a new interface except vmtap0,so I ssh to the IP `192.168.249.1` ,but permisson denied again.
```
# ssh ubuntu@192.168.249.1
ubuntu@192.168.249.1's password:
Permission denied, please try again.
```
Btw,are there any other ways to log in the vm,like by console?

**Comment by sboeuf** [comment]
>As the result,it did not create a new interface except vmtap0,so I ssh to the IP 192.168.249.1 ,but permisson denied again.

You must set an IP address for the interface in the guest. It does not make sense to ssh into `192.168.249.1` as it relates to the TAP interface on the host.

>Btw,are there any other ways to log in the vm,like by console?

Of course, I expect you get prompted to enter the login and password after you ran the Cloud-Hypervisor command line. Make sure you use a clean RAW image (QCOW2 works as well), and wait for about 10 seconds for the following prompt shows up:
```
Ubuntu 20.04 LTS cloud hvc0

cloud login:
```

**Comment by dyoung23** [comment]
@sboeuf 
What a pity,I guess I was in a wrong state all the time.Because after I ran Cloud-Hypervisor command line,I just got this output,and it was stuck there without any prompt -- I think it's in stuck as it still like that after 1 hour.
```
# ./cloud-hypervisor/target/release/cloud-hypervisor --kernel ./hypervisor-fw --disk path=focal-server-cloudimg-amd64.raw path=/tmp/ubuntu-cloudinit.img --cpus boot=4 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng 
Cloud Hypervisor Guest
	API server: /run/cloud-hypervisor.22890
	vCPUs: 4
	Memory: 1024 MB
	Kernel: Some(KernelConfig { path: "./hypervisor-fw" })
	Initramfs: None
	Kernel cmdline: 
	Disk(s): Some([DiskConfig { path: Some("focal-server-cloudimg-amd64.raw"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, id: None, disable_io_uring: false }, DiskConfig { path: Some("/tmp/ubuntu-cloudinit.img"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, id: None, disable_io_uring: false }])




```

**Comment by sboeuf** [comment]
Just realized you're using off the shelf ubuntu image. There's a limitation with that, so please use the custom one instead `https://cloudhypervisorstorage.blob.core.windows.net/images/focal-server-cloudimg-amd64-custom.raw`

**Comment by dyoung23** [comment]
@sboeuf This time I use the custom image which you said `focal-server-cloudimg-amd64-custom.raw`,but get core dumped error. oops.
```
# ./cloud-hypervisor/target/release/cloud-hypervisor --kernel ./hypervisor-fw --disk path=focal-server-cloudimg-amd64-custom.raw path=/tmp/ubuntu-cloudinit.img --cpus boot=4 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng 
Cloud Hypervisor Guest
	API server: /run/cloud-hypervisor.5168
	vCPUs: 4
	Memory: 1024 MB
	Kernel: Some(KernelConfig { path: "./hypervisor-fw" })
	Initramfs: None
	Kernel cmdline: 
	Disk(s): Some([DiskConfig { path: Some("focal-server-cloudimg-amd64-custom.raw"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, id: None, disable_io_uring: false }, DiskConfig { path: Some("/tmp/ubuntu-cloudinit.img"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, id: None, disable_io_uring: false }])
Bad system call (core dumped)
```

**Comment by sboeuf** [comment]
Weird, that means there's a system call missing in the seccomp list.
Append `--seccomp false` to the Cloud-Hypervisor command line, this should do the trick.
If that works, could you please identify which syscall is missing by running `strace -f ./cloud-hypervisor ...`, and paste the output here?

**Comment by dyoung23** [comment]
@sboeuf  It does works by appending `--seccomp false`.
The output of `strace` is like below
```
...
[pid 12761] ioctl(76, KVM_RUN, 0)       = 0
[pid 12761] ioctl(76, KVM_RUN, 0)       = 0
[pid 12761] open("/etc/localtime", O_RDONLY|O_CLOEXEC) = 2
[pid 12761] --- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7f3f18ef5760, si_syscall=__NR_open, si_arch=AUDIT_ARCH_X86_64} ---
[pid 12808] <... epoll_wait resumed> )  = ? <unavailable>
[pid 12808] +++ killed by SIGSYS (core dumped) +++
[pid 12765] +++ killed by SIGSYS (core dumped) +++
[pid 12763] +++ killed by SIGSYS (core dumped) +++
[pid 12762] +++ killed by SIGSYS (core dumped) +++
[pid 12761] +++ killed by SIGSYS (core dumped) +++
[pid 12760] +++ killed by SIGSYS (core dumped) +++
[pid 12753] +++ killed by SIGSYS (core dumped) +++
[pid 12752] +++ killed by SIGSYS (core dumped) +++
+++ killed by SIGSYS (core dumped) +++
```

**Comment by sboeuf** [comment]
>It does works by appending --seccomp false.

Ok that's good.

Thanks for the logs, the problem is obviously coming from a missing `open(2)` syscall. Now the question is, which thread should have it enabled. Could you run `pstree -t -p $(pidof cloud-hypervisor)` first, and then run the `strace` one more time. This will help us find out which thread is missing the syscall.

**Comment by dyoung23** [comment]
@sboeuf What's the version of `pstree` in your environment,I use `pstree (PSmisc) 22.20 ` but have no `-t` option.
So I just run `strace` first, then run `pstree -p $(pidof cloud-hypervisor)`  and get this output.
```
cloud-hyperviso(3826)─┬─{cloud-hyperviso}(3827)
                      ├─{cloud-hyperviso}(3828)
                      ├─{cloud-hyperviso}(3835)
                      ├─{cloud-hyperviso}(3836)
                      ├─{cloud-hyperviso}(3838)
                      ├─{cloud-hyperviso}(3839)
                      ├─{cloud-hyperviso}(3840)
                      └─{cloud-hyperviso}(3862)
```

**Comment by sboeuf** [comment]
My version number is `UNKNOWN`, that's weird :)
Try in your version to find out how to print thread names.
This comes from the help in my version:
```
-t, --thread-names  show full thread names
```

**Comment by dyoung23** [comment]
@sboeuf I found it seems to have no options to print thread names. 
```
# pstree -H
pstree: option requires an argument -- 'H'
Usage: pstree [ -a ] [ -c ] [ -h | -H PID ] [ -l ] [ -n ] [ -p ] [ -g ] [ -u ]
              [ -A | -G | -U ] [ PID | USER ]
       pstree -V
Display a tree of processes.

  -a, --arguments     show command line arguments
  -A, --ascii         use ASCII line drawing characters
  -c, --compact       don't compact identical subtrees
  -h, --highlight-all highlight current process and its ancestors
  -H PID,
  --highlight-pid=PID highlight this process and its ancestors
  -g, --show-pgids    show process group ids; implies -c
  -G, --vt100         use VT100 line drawing characters
  -l, --long          don't truncate long lines
  -n, --numeric-sort  sort output by PID
  -N type,
  --ns-sort=type      sort by namespace type (ipc, mnt, net, pid, user, uts)
  -p, --show-pids     show PIDs; implies -c
  -s, --show-parents  show parents of the selected process
  -S, --ns-changes    show namespace transitions
  -u, --uid-changes   show uid transitions
  -U, --unicode       use UTF-8 (Unicode) line drawing characters
  -V, --version       display version information
  -Z,
  --security-context   show SELinux security contexts
  PID    start at this PID; default is 1 (init)
  USER   show only trees rooted at processes of this user

```

**Comment by rbradford** [comment]
`KVM_RUN` shows this is vCPU thread

**Comment by dyoung23** [comment]
@rbradford So what shoud I do?

**Comment by rbradford** [comment]
@dyoung23 If you have further support questions please use https://github.com/cloud-hypervisor/cloud-hypervisor/discussions/new under "Q&A"
