### ISSUE TITLE
Use device mapper to improve images copy for integration tests

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#2132]
We should try to use device mapper in order to snapshot images used from integration tests, avoiding the copy of the entire image each time we spawn a new test.

**Comment by rbradford** [comment]
@sboeuf Did you want to update this issue and close it for completeness?

**Comment by sboeuf** [comment]
After implementing the solution for this issue, it turned out device mapper wasn't behaving consistently under high load, and couldn't find the solution for that.
Let's keep the current solution as it is quite fast and stable.
