### ISSUE TITLE
Refactor test_memory_mergeable

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2138]
This test seems to be the only flaky test we have remaining. It has some very complex logic to work out if there are pages shared by looking at the PSS. Maybe instead we should just ask the kernel if it has shared any pages:

https://www.kernel.org/doc/Documentation/vm/ksm.txt:

```
The effectiveness of KSM and MADV_MERGEABLE is shown in /sys/kernel/mm/ksm/:

pages_shared     - how many shared pages are being used
pages_sharing    - how many more sites are sharing them i.e. how much saved
pages_unshared   - how many pages unique but repeatedly checked for merging
pages_volatile   - how many pages changing too fast to be placed in a tree
full_scans       - how many times all mergeable areas have been scanned
```

**Comment by sboeuf** [comment]
This is definitely worth a shot.

**Comment by rbradford** [comment]
@likebreath Can you look into this?
