### ISSUE TITLE
Add clean shutdown using ACPI button

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2140]
Investigate adding an ACPI button to trigger a clean shutdown. We could reuse the existing vm.shutdown API entry point as there is some definitely some confusion on its behaviour. A vm.terminate entry point could be used to hard kill the vm.

**Comment by iggy** [comment]
From what I read quickly online, there's specific functionality called out for this in the case of "hardware reduced ACPI platforms". There is a Control Method Power Button. 

https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/hardware-requirements-for-soc-based-platforms#hardware-reduced-acpi-platforms
