### ISSUE TITLE
Is there any tool for accessing the console associated with a Cloud-Hypervisor virtual machine?

### ISSUE THREAD

**Issue by eeldy** [cloud-hypervisor/cloud-hypervisor#2152]
Is there any tool or helper for accessing the serial tty or virtio-console associated with a Cloud-Hypervisor virtual machine seperately other than directly enter in console or serial by running ./cloud-hypervisor CLI? Like virt-viewer, vnc viewer or libvirt virsh console command which can be used to connect to the text console of a guest, etc? Thanks a lot.

**Comment by rbradford** [comment]
I think this is something that @bryteise is working on for libvirt enabling.

**Comment by bryteise** [comment]
@eeldy see #2168 for details on what I'm looking to enable.

**Comment by rbradford** [comment]
This is done. via `--console pty` or `--serial pty`
