### ISSUE TITLE
Integration test is failing in Master branch

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/cloud-hypervisor#2157]
In our msft internal pipeline three tests are failing with upstream master branch:
2021-01-13T01:33:40.8944559Z failures:
2021-01-13T01:33:40.8944882Z     tests::parallel::test_snapshot_restore
2021-01-13T01:33:40.8945252Z     tests::parallel::test_vfio
2021-01-13T01:33:40.8945609Z     tests::parallel::test_virtio_iommu

**Comment by russell-islam** [comment]
[pipline-log.txt](https://github.com/cloud-hypervisor/cloud-hypervisor/files/5805969/pipline-log.txt)

**Comment by russell-islam** [comment]
Any suggestions. I am not sure if anything wrong with our Ubuntu Host. Rust version 1.49.0

**Comment by liuw** [comment]
All three tests failed with out of bounds access.

```2021-01-13T01:33:40.8474201Z cloud-hypervisor: 772.467713ms: <vcpu3> ERROR:vm-virtio/src/queue.rs:516 -- virtio queue descriptor table goes out of bounds: start:0xfffff000 size:0x00000800```

I wonder why upstream CI never sees this though.

**Comment by liuw** [comment]
What are the differences between Microsoft's internal pipeline vs upstream pipeline when testing KVM?

As I understand it is also using the set of tests. The only difference I know is the internal pipeline runs on a real machine while the upstream one runs on nested KVM. Is there something else that's worthy of mentioning?

**Comment by russell-islam** [comment]
> What are the differences between Microsoft's internal pipeline vs upstream pipeline when testing KVM?
> 
> As I understand it is also using the set of tests. The only difference I know is the internal pipeline runs on a real machine while the upstream one runs on nested KVM. Is there something else that's worthy of mentioning?

You are right. Kernel version might be different but that should not fail the tests. Also I was wondering upstream CI has ane extra configurations on the host.
@rbradford any thoughts?

**Comment by rbradford** [comment]
@russell-islam We run the Azure groovy image on the CI systems.

It looks like the kernel has placed the queues at the top of the guest memory (it can place them anywhere) but vm-memory thinks that's not valid. I would start by debugging what is going on with vm-memory.

**Comment by liuw** [comment]
Another thing comes to mind. The failures are recent. If Cloud Hypervisor is the only variable in our setup, you can pick a random point in the past in history as the baseline and start bisecting. Once you pin point a change in Cloud Hypervisor that triggers the failures, we have a better chance to understand the problem.

**Comment by russell-islam** [comment]
Looks like it is an internal pipeline issue. We have cancelled some jobs but it was not cleaned properly by pipeline service. Spcfically the CLH scripts. Sp closing this issue.
