### ISSUE TITLE
Migrate ARM64 support to ACPI

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2178]
Currently the ARM64 support used Device Tree requiring the dependency on the libfdt library. With the removal of virtio-mmio and GICv2 support it should be possible to move to ACPI only. This might give some hotplug support for free but most importantly simplify our code base.

@MrXinWang  @michael2012z  Happy for this change to go ahead?

**Comment by MrXinWang** [comment]
@rbradford Of course yes. (Just out of curiosity - Does the community already have a roadmap for doing this or we are just planning?)

**Comment by rbradford** [comment]
@MrXinWang  This is that plan. :-)

**Comment by michael2012z** [comment]
Hi, @rbradford 

Indeed, ACPI is the next most important thing we need to support. Regarding the plan for AArch64, Henry and me are going along these major roadmap items:
- Giv3-ITS migration - Drafted code, but there is still some problem. Debugging now.
- Firmware - Finished early investigation. Now implementing.
- ACPI - Did some early investigation, will begin the implementation after Firmware support.

ACPI would be a big job, so we leave it the last one.

**Comment by rbradford** [comment]
Hi @michael2012z. This sounds fine. I think you might find firmware more challenging than ACPI but that's up to you. We're you going to try using https://github.com/cloud-hypervisor/edk2 ? or https://github.com/cloud-hypevisor/rust-hypervisor-firmware ?

In terms of ACPI. Let me help you make a start by making sure any x86 specific stuff is gated so that it makes it possible to turn on the feature.

**Comment by rbradford** [comment]
I just checked the Linux code. Unlike on x86 the only supported method for getting the ACPI tables is the firmware. This is confirmed by the documentation:
```
Booting using ACPI tables
-------------------------
The only defined method for passing ACPI tables to the kernel on ARMv8
is via the UEFI system configuration table.  Just so it is explicit, this
means that ACPI is only supported on platforms that boot via UEFI.
```

**Comment by michael2012z** [comment]
@rbradford We are trying rust-hypervisor-firmware. I thought it is not that hard to add the AArch64 support. But please correct me if I haven't realized the real challenges in it. 

Will rust-hypervisor-firmware keep developing? Why are there 2 firmware repo's (`edk2` and `rust-hypervisor-firmware`) in cloud-hypervisor, will one of them be skipped in future?

**Comment by rbradford** [comment]
The edk2 repository was added to provide support for Windows and for booting non-EFI guests using MBR boot. Since there is already edk2 support for aarch64 and the number of changes needed to support CH there is quite small you might find it easier. However rust-hypervisor-firmware is a smaller code base to work with. It's a difficult decision to make but i'll support you either way.

**Comment by michael2012z** [comment]
The plan for AArch64 support of ACPI:

1. Build

> - Thanks @rbradford for creating the PR for this: #2197.

2. Refactor `configure_system()` to handle ACPI tables

> - Normally, for the kernel to get the correct RSDP table, UEFI implementation is needed. But before AArch64 support is ready in rust-hypervisor-firmware, we can try to get away by appending `acpi_rsdp=` in kernel commandline. This sounds like a hack, but we can get start in this way.

3. Support mandatory tables:

> - Architecture-specific. MADT requires total implementation on AArch64 as it is related with GIC. DSDT implementation need to be customized on AArch64 for some devices.
> > 1. MADT, 
> > 2. DSDT, 
> - Newly implement. The following 2 tables below are required by AArch64, but not X86. So they were not implemented.
> > 1. GTDT, 
> > 2. SPCR, 
> - Architecture-agnostic. The 3 tables below should be common on both architectures.
> > 1. FADT, 
> > 2. MCFG, 
> > 3. XSDT

**Comment by sboeuf** [comment]
Nice summary @michael2012z 
About using acpi_rsdp= in the command line at first, that sounds completely fine to me.
We should even maintain this as a valid solution long term, as I don't think we want ACPI to be tied to UEFI and therefore rust-hypervisor-firmware.

**Comment by rbradford** [comment]
@sboeuf That will be useful for testing. The only official support is via EFI (see my earlier comment.)

CONFIG_KEXEC=y will be needed as usually "acpi_rsdp=" parsing is restricted to the x86 code: https://github.com/torvalds/linux/blob/85f94020033f931a5918ab26281b2afbe4d68b73/drivers/acpi/osl.c#L198 and https://github.com/torvalds/linux/blob/40ba9309c76f29d012a5cc0cf938f8ff7dc6fef2/arch/x86/boot/compressed/acpi.c#L316

**Comment by sboeuf** [comment]
Got it!

**Comment by michael2012z** [comment]
Update of the progress: 

1. Refactor `configure_system()` to handle ACPI tables

> - Append `acpi_rsdp=` to kernel cmddline for test - Draft code ready, testing

2. Support mandatory tables:

> - Architecture-specific. MADT requires total implementation on AArch64 as it is related with GIC. DSDT implementation need to be customized on AArch64 for some devices.
> > 1. MADT - Draft code ready, testing
> > 2. DSDT - TODO
> - Newly implement. The following 2 tables below are required by AArch64, but not X86. So they were not implemented.
> > 1. GTDT - Draft code ready, testing
> > 2. SPCR - Draft code ready, testing
> - Architecture-agnostic. The 3 tables below should be common on both architectures.
> > 1. FADT - To test
> > 2. MCFG - To test
> > 3. XSDT - To test

By current booting log, guest kernel stopped at initializing serial device. That is because DSDT has not been ready, and that is what we will work on.

As everything is still in testing, I haven't been able to create a PR for review. But it's better to update what  is on-going.

**Comment by michael2012z** [comment]
We (@MrXinWang , @jongwu and me) have been updating the progress of UEFI+ACPI on AArch64 with a prototype PR https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2241. Now a minimal functionality set has been implemented. On AArch64, CLH can boot successfully with EDK2 (EDK2 code change is on review and discussion). But hot-plug has not been ready. We will test and plan hot-plug after the basic ACPI support ready on master.

Next, we will polish the code and split the big PR to smaller ones to review. Plan:
- [ ] PR for changing memory layout
- [ ] PR(s) for creating ACPI tables
- [ ] PR for integrating with EDK2

**Comment by rbradford** [comment]
With the ACPI support merged can be remove the FDT support?

**Comment by michael2012z** [comment]
@rbradford, as far as I know, UEFI (I mean EDK2 here) on arm64 need to get system information from FDT. So FDT is still needed.

But I think FDT is no longer a pain. Now we use a rust FDT crate to handle it, not the local libfdt lib.

CC @jongwu .

**Comment by michael2012z** [comment]
Yes, you are right. :)

**Comment by rbradford** [comment]
We now support ACPI on ARM64. :rocket: We also need to continue to support FDT for direct kernel boot so we can close this issue.
