### ISSUE TITLE
Add support for the VHD disk image format

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#2185]
[As specified by Microsoft](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/dd323654(v=vs.85)) and used by Azure.

We only want to support fixed VHD for now.

**Comment by rbradford** [comment]
Spec download: http://go.microsoft.com/fwlink/p/?linkid=137171

**Comment by russell-islam** [comment]
@sboeuf  Is the scope of the work is to support VHD only or vhdx also?
