### ISSUE TITLE
ch process stucked when strarup

### ISSUE THREAD

**Issue by eeldy** [cloud-hypervisor/cloud-hypervisor#2210]
Follow the instructions in readme to start the ch guest, but ch process stucked:
$ ./cloud-hypervisor/target/debug/cloud-hypervisor \
     --kernel /home/hypervisor-fw \
     --disk path=/var/focal-server-cloudimg-amd64.raw \
     --cmdline "console=ttyS0 root=/dev/vda1 rw" \
     --cpus boot=4 \
     --memory size=2048M \
     --serial tty \
     --console off \
     --net "tap=,mac=,ip=,mask=" \
     --rng
Cloud Hypervisor Guest
        API server: /run/cloud-hypervisor.1453998
        vCPUs: 4
        Memory: 2048 MB
        Kernel: Some(KernelConfig { path: "/home/hypervisor-fw" })
        Initramfs: None
        Kernel cmdline: console=ttyS0 root=/dev/vda1 rw
        Disk(s): Some([DiskConfig { path: Some("/var/focal-server-cloudimg-amd64.raw"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, id: None, disable_io_uring: false }])

Booting via PVH Boot Protocol
Setting up 4 GiB identity mapping
Page tables setup
Found PCI device vendor=8086 device=d57 in slot=0
Found PCI device vendor=1af4 device=1042 in slot=1
Found PCI device vendor=1af4 device=1041 in slot=2
Found PCI device vendor=1af4 device=1044 in slot=3
PCI Device: 0:1.0 1af4:1042
Bar: type=MemorySpace32 address=e7f80000
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=Unused address=0
Virtio block device configured. Capacity: 4612096 sectors
Found EFI partition
Filesystem ready
Error loading default entry: FileError(NotFound)
Using EFI boot.
Found bootloader (BOOTX64.EFI)
Executable loaded
Failed to set MokListRT: Unsupported
Could not create MokListRT: Unsupported
Something has gone seriously wrong: import_mok_state() failed
: Unsupported
TPM logging failed: Unsupported
**Failed to allocate memory for 'gdt'
efi_main() failed!**

Need help to see where the problem is and how to resolve it? Thanks a lot!

**Comment by rbradford** [comment]
Hi @eeldy thanks for opening this issue. This is a regression in the upstream Ubuntu image. Please see https://github.com/cloud-hypervisor/rust-hypervisor-firmware/issues/77 for details and a mitigation for using our custom image.
