### ISSUE TITLE
Add integration test to mimic macvtap

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2215]
Add an integration test that replicates the macvtap instructions from docs/macvtap-bridge.md

**Comment by rbradford** [comment]
@likebreath Fancy taking this on?

**Comment by likebreath** [comment]
@rbradford Will I able to reach (e.g. `ping`)  the host from the guest with the setup as instructed from the [docs/macvtap-bridge.md](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/macvtap-bridge.md)?

I got a WIP integration test here https://github.com/likebreath/cloud-hypervisor/commit/2349e871ae3b543614e16c1c14182c5cfd289622. I believe it replicates the instructions from document in the right way, but it looks like the guest can't reach the host (causing `notify-booted` failing) while the host can't ssh into the guest neither.  Any additional setup I should have to make guest reachable?

**Comment by rbradford** [comment]
@likebreath You need to change the mode if you want the host to be able to reach the guest: https://backreference.org/2014/03/20/some-notes-on-macvlanmacvtap/
