### ISSUE TITLE
hugepages does not support 1GB pages

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#2230]
The `hugepages` `--memory` option is a toggle to use 2MB pages instead of 4K ones. 1GB is not supported.
It should let the user choose between 2MB and 1GB.

**Comment by rbradford** [comment]
Alternatively to providing a control to the user we could see if the region is a multiple of 1GiB and use those pages instead. Let me experiment with that first.

**Comment by rbradford** [comment]
> Alternatively to providing a control to the user we could see if the region is a multiple of 1GiB and use those pages instead. Let me experiment with that first.

Sadly we can't do that as the hugepage size available is set a boot time with `hugepagesz=1G` on the kernel. So we will need to give the user full control of the option.
