### ISSUE TITLE
Removing "LinuxBoot" protocol support

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2231]
Now that we support the PVH protocol it is probably worth considering removing the support for the unofficial and unsupported "LinuxBoot" support. Anybody using direct kernel boot is doing so because they want to use their own kernel and as such is it completely reasonable to expect it to support this feature.

**Comment by rbradford** [comment]
@likebreath Kata is the main user of direct kernel boot. Can you check it's using PVH based boot.

**Comment by likebreath** [comment]
I think kata is using PVH based boot (at least on x86-64 platforms), given the fact that the `CONFIG_PVH=y` is always enabled while generating kata's custom kernel images (on x86-64 platforms) for both in kata-runtime [here](https://github.com/kata-containers/packaging/blob/master/kernel/configs/fragments/x86_64/base.conf#L22) and kata-2.0 [here](https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/configs/fragments/x86_64/base.conf#L22). So removing the "LinuxBoot" protocol in cloud-hypervisor should be fine for kata's usage cases. 

In case I am missing some context, please correct me. @devimc @jcvenegas @egernst

**Comment by devimc** [comment]
@likebreath you're right, performance is better when the raw kernel is used

**Comment by jcvenegas** [comment]
@likebreath @rbradford sounds good, as the kernel is already compiled with that flag, I assume that is using PVH today, correct? 
I am not sure what is the preference order that it uses. 

And as @devimc mention we use it for better boot time, that leads me to a more informative question is there any perf difference with both methods? I think both load an uncompressed kernel but, in practice the codepath takes makes any boot time difference (I guess not but I not familiar with the internals)?

**Comment by rbradford** [comment]
No, shouldn't see any performance difference between PVH and LinuxBoot. But if you're concerned your should compile the kernel without CONFIG_PVH=y and compare.

**Comment by rbradford** [comment]
Deprecated in 0.14.0. Remove in 0.16.0.
