### ISSUE TITLE
Simplify ACPI interface exposed when no resizing possible

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2232]
Consider if we should remove the DSDT logic if:
* For CPU hotplug when: max vCPUs is boot vCPUs
* For memory hotplug when: hotpluggable_memory == 0 or using virtio-mem

(Always keep PCI hotplug logic.)

I think this might speed up our boot by not having the kernel interrogate the MemoryManager/CpuManager and by having less DSDT data to generate and parse.

**Comment by rbradford** [comment]
I wanted to see what the potential boot time improvement was if we were to do this. I tested this by comparing the time to "init" (using port 0x80 output). With CH built with:

`cargo build --no-default-features --features "cmos,fwdebug,io_uring,kvm" --release` vs
`cargo build --no-default-features --features "cmos,fwdebug,io_uring,kvm,acpi" --release`

I could see no difference with a command line like:

`target/release/cloud-hypervisor --disk path=/home/rob/images/focal-server-cloudimg-amd64.raw --kernel ~/src/linux/vmlinux --cmdline "root=/dev/vda1 console=hvc0 quiet panic=1 init=/foo" --api-socket /tmp/api`

In both cases when running nested on an Azure D32s_v4 I see time to init of ~ 260ms. Any difference between the two build configs is within the range of values seen. The implication of this is that the handling of the ACPI tables in the guest kernel nor the construction of the tables has any appreciable impact on the boot time.

**Comment by sboeuf** [comment]
Ok and you've seen in the kernel logs that ACPI is not setup at all in the first case?
Just want to make sure we don't have any bug related to opt-out `acpi` feature.

**Comment by rbradford** [comment]
@sboeuf Yeh, we don't generate the tables at all and ACPI features like shutdown don't work.

**Comment by sboeuf** [comment]
Ok well I'd say close this issue then, since there's nothing to improve.

**Comment by rbradford** [comment]
Closing as there is no noticeable improvement and it's not worth the added code complexity.
