### ISSUE TITLE
Is there any way to set bootindex in CH?

### ISSUE THREAD

**Issue by glitzflitz** [cloud-hypervisor/cloud-hypervisor#2240]
I'm testing my vhost-user-scsi implementation which currently only supports simple data disks. 
Is there any way to set bootindex in CH so that I can  use another image as a simple data disk?

**Comment by iggy** [comment]
cloud-hypervisor doesn't have the concept of bootindex because it doesn't provide any sort of bios integration. If you are using something like hypervisor-fw, I think it just uses the first drive specified. If you are using your own kernel, you just set the boot device using `--cmdline` args.

**Comment by rbradford** [comment]
The order of the disks specified by `--disk` will be replicated in the PCI device order which will help you determine which device any firmware will try and use first.
