### ISSUE TITLE
Cloud Hypervisor stuck trying to get PCI configuration.

### ISSUE THREAD

**Issue by rishirsinha** [cloud-hypervisor/cloud-hypervisor#2258]
I have been trying to run cloud hypervisor on my linux physical machines and virtual machines based on the instructions on the home page, but have not been able to successfully bring up a logged in VM yet. I have been using the instructions for both the custom kernel image and the standard kernel image.

I used the commands listed on the main cloud-hypervisor page. The cloud hypervisor process comes up and stays up. When I do ps I see kvm-nx-lpage-re process indicating that the VM has bootstrapped, but the cloud-hypervisor does not log into the VM.

On enabling verbose logging, I see the following line repeated again and again.

cloud-hypervisor: 23.039996ms: <vcpu0> DEBUG:virtio-devices/src/transport/pci_common_config.rs:154 -- read_common_config_word: offset 0x1e

The last set of lines before this line is:

cloud-hypervisor: 21.466642ms: <vcpu0> INFO:vmm/src/vm.rs:423 -- Waiting for barrier
cloud-hypervisor: 21.449023ms: <vmm> INFO:vmm/src/lib.rs:1111 -- Trying to activate pending virtio devices: count = 1
cloud-hypervisor: 21.639226ms: <vmm> INFO:virtio-devices/src/block.rs:428 -- Changing cache mode to writethrough
cloud-hypervisor: 21.774451ms: <vmm> INFO:virtio-devices/src/transport/pci_device.rs:672 -- _virtio-pci-_disk0: Waiting for barrier
cloud-hypervisor: 21.872583ms: <vmm> INFO:virtio-devices/src/transport/pci_device.rs:674 -- _virtio-pci-_disk0: Barrier released
cloud-hypervisor: 21.999616ms: <vmm> INFO:virtio-devices/src/transport/pci_device.rs:676 -- _virtio-pci-_rng: Device does not need activation
cloud-hypervisor: 22.119794ms: <vmm> INFO:virtio-devices/src/transport/pci_device.rs:676 -- _virtio-pci-_console: Device does not need activation
cloud-hypervisor: 21.880494ms: <vcpu0> INFO:vmm/src/vm.rs:425 -- Barrier released

Any help will be greatly appreciated.

**Comment by iggy** [comment]
What cloud-hypervisor command line args are you using?

What kernel version?

What's the diff between your kernel config and the one in the [repo](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/resources/linux-config-x86_64)?

In general, I think the devs prefer using the [Discussions](https://github.com/cloud-hypervisor/cloud-hypervisor/discussions) GitHub feature for support questions rather than issues.

**Comment by rishirsinha** [comment]
I will start a discussion and close this issue.

**Comment by rishirsinha** [comment]
Moved the question to here: 

https://github.com/cloud-hypervisor/cloud-hypervisor/discussions/2261

Am closing this issue.
