### ISSUE TITLE
HTTP callback API for notifying state changes of a VM

### ISSUE THREAD

**Issue by vineethrp** [cloud-hypervisor/cloud-hypervisor#2273]
The request is to have an HTTP callback API so that cloud-hypervisor can notify the consumers of this API whenever a state change happens. State changes of potential interests are:
- VM shutdown, reboot/reset, crash
- cpu online offline
- device activation, device reset etc

This is in continuation with the discussions here:
https://github.com/cloud-hypervisor/libvirt/issues/30

The temporary fix for the above issue is to have a thread parse procfs to detect the thread changes: https://github.com/cloud-hypervisor/libvirt/pull/40

Libvirt CLH driver could benefit a lot. Instead of continuously monitoring the procfs, the driver can wait for notification from cloud-hypervisor and then parse procfs only when needed.

**Comment by rbradford** [comment]
Resolved via the event fd monitor
