### ISSUE TITLE
Add VHDX disk format support

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/cloud-hypervisor#2282]
As we have support for VHD fix format we are planning to add the vhdx support. This issue is for tracking that work.

**Comment by rbradford** [comment]
@russell-islam @fazlamehrab has started looking into this.

**Comment by sboeuf** [comment]
@russell-islam can you clarify which types should be handled? `Fixed`, `Dynamic`, `Differencing`?

**Comment by russell-islam** [comment]
> @russell-islam can you clarify which types should be handled? `Fixed`, `Dynamic`, `Differencing`?

In parity with QEMU we should have both `Fixed`, `Dynamic`. First we can focus on fixed, after that Dynamic.
