### ISSUE TITLE
suggestion: be compatible with qemu's interactive interface (command line/qmp)

### ISSUE THREAD

**Issue by terenceli** [cloud-hypervisor/cloud-hypervisor#23]
I think it will be more convenient if cloud-hypervisor can be compatible with qemu's interactive interface, such as the command line and qmp and so on. So the openstack/libvirt/qemu solution be replaced openstack/libvirt/cloud-hypervisor transparently.

Thanks,
Li Qiang

**Comment by sameo** [comment]
@terenceli I'd rather add support to cloud-hypervisor into libvirt rather than trying to follow the QEMU command line.
And for an equivalent of QMP, we'll eventually have a rust-vmm REST interface, hopefully based on a rust-vmm driven definition.

**Comment by terenceli** [comment]
@sameo Also a good point.

**Comment by sboeuf** [comment]
Closing this issue as this has been solved by adding HTTP API, similarly to the way Firecracker works.
