### ISSUE TITLE
If there is a requirement to add a new interface for firmware?

### ISSUE THREAD

**Issue by jongwu** [cloud-hypervisor/cloud-hypervisor#2304]
Hello @rbradford @sboeuf @MrXinWang @michael2012z @justin-he

As firmware enablement is in the roadmap, I wonder if cloud-hypervisor has got ready to welcome it. No options distinctly used for accepting firmware image as input is found under cloud-hypervisor.  However, I find the following use case:
`$ ./cloud-hypervisor/target/release/cloud-hypervisor \
	--kernel ./hypervisor-fw \
	--disk path=focal-server-cloudimg-amd64.raw \
	--cpus boot=4 \
	--memory size=1024M \
	--net "tap=,mac=,ip=,mask=" \
	--rng`
 "--kernel" may be occupied for accepting a image seeming like a firmware rom. If that's true, it really confuses me that why use a "firmeware" as "kernel". I think it's better to add a "--bios" or "--firmware" for firmware boot to make it clear. WDYT?

**Comment by rbradford** [comment]
> Hello @rbradford @sboeuf @MrXinWang @michael2012z @justin-he
> 
> As firmware enablement is in the roadmap, I wonder if cloud-hypervisor has got ready to welcome it. No options distinctly used for accepting firmware image as input is found under cloud-hypervisor.  However, I find the following use case:
> `$ ./cloud-hypervisor/target/release/cloud-hypervisor \
> 	--kernel ./hypervisor-fw \
> 	--disk path=focal-server-cloudimg-amd64.raw \
> 	--cpus boot=4 \
> 	--memory size=1024M \
> 	--net "tap=,mac=,ip=,mask=" \
> 	--rng`
>  "--kernel" may be occupied for accepting a image seeming like a firmware rom. If that's true, it really confuses me that why use a "firmeware" as "kernel". I think it's better to add a "--bios" or "--firmware" for firmware boot to make it clear. WDYT?
> 
> 

We package our firmware as a PVH ELF binary so the same code is used to load it as a Linux kernel.

**Comment by rbradford** [comment]
(Maybe the ambiguity is that we're using the term kernel in the most generic sense not referring to the Linux kernel)

**Comment by jongwu** [comment]
Thanks @rbradford -, so only firmware in format of ELF can be used in cloud-hypervisor now. Is there any plan from you about supporting some generic firmware like edk2? I have no idea how clh can make use of it for now.

**Comment by rbradford** [comment]
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/uefi.md has details about our version of edk2 that works on CH.
