### ISSUE TITLE
Migrate to upstream kvm-bindings 

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2305]
We've been on forked versions too long. We need to either work out how to upstream the serde bits or have an alternative approach that we use inside Cloud Hypervisor.

**Comment by andreeaflorescu** [comment]
Consuming kvm-ioctls should be pretty straightforward even with a fork of kvm-bindings. The solution we (temporarily) adopted in Firecracker is to do a patch of kvm-bindings such that we consume the one with versionize, and use the upstream kvm-ioctls.

Here is the PR that does that for Firecracker: https://github.com/firecracker-microvm/firecracker/pull/2319

The kvm-bindings maintenance should be low effort for now.

**Comment by rbradford** [comment]
We are now on upstream kvm-ioctls, turns out the requirement for our fork was obsolete.

**Comment by sboeuf** [comment]
@rbradford Should we simply close this issue since I don't think this will ever happen. We'll always have to generate our own bindings on top of the upstream ones to ensure we have the Versionize support.
