### ISSUE TITLE
Run sequential tests on the master build only

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#2388]
To reduce the CI time running for each PR, we may consider to run our sequential tests on the master build only. Also, this will allow us to add (more) performance tests which normally are sensitive to the executing environment and require to be executed sequentially. On such example is the integration/performance test to verify [the I/O throttling](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/io_throttling.md) capability introduced recently.

**Comment by rbradford** [comment]
I disagree with running the current sequential test on the master branch only. If there are some new new performance metric tests then we can re-evaluate that then.

**Comment by rbradford** [comment]
If we get an I/O throttling test then I think we can re-evaluate this but for now i'm closing this.
