### ISSUE TITLE
Panic if api-socket path is not found

### ISSUE THREAD

**Issue by deathly809** [cloud-hypervisor/cloud-hypervisor#2395]
If the api-socket path does not exist then we output this error message,

```
thread 'http-server' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', vmm/src/api/http.rs:275:59
```

Was not very helpful so I added expect(&format("Path not found: {}", path) instead of unwrap and got this instead,

```
thread 'http-server' panicked at 'Path not found: /run/user/1000/cloud-hypervisor.8066: IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', vmm/src/api/http.rs:277:59
```

Tracked this down and it appears that the default api-socket is constructed from uid + tid.

I really have three questions:

1. Should we validate that the path exists before we make it all the way to creating the vmm thread?
2. Replace unwraps with somewhat helpful error messages using expect where it makes sense?
3. If the thread created in start_vmm_thread panics don't continue but exit?

**Comment by rbradford** [comment]
The file will be created if not present but I guess on your platform there is no `/run/user/1000` ?

**Comment by deathly809** [comment]
Correct there is no /run/user/1000.  I am using the WSL + Debian with the new nested virtualization support.  Let me do some digging, maybe I can create it manually or perhaps cloud-hypervisor can create it if it does not exist (seems kinda iffy though).

**Comment by rbradford** [comment]
@deathly809 Creating the API socket if there is none specified there is for convenience. I will open a PR for it to not try and create it if that directory is not present.

**Comment by deathly809** [comment]
Awesome.  One other thing is should the http thread "silently" fail and just continue?

**Comment by rbradford** [comment]
Yeh, so I won't start the HTTP thread (no need if you don't have a socket.)

**Comment by deathly809** [comment]
I have confirmed with WSL folks that they do not use systemd so that is why the folder does not exist.
