### ISSUE TITLE
Nicely handle munmap()ing virtio-pmem/fs regions

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#240]
Currently we accumulate a list of regions to munmap() that need to be dropped to cleanly reboot the VM: https://github.com/intel/cloud-hypervisor/blob/master/vmm/src/vm.rs#L638

Ideally we would do it some other way, probably by using rust-vmm/vm-memory#43 to have the regions "owned" by vm-memory.

**Comment by sboeuf** [comment]
rust-vmm/vm-memory#42 and  rust-vmm/vm-memory#43 will allow `virtio-pmem` and `virtio-fs` memory mapped regions to be handled by `vm-memory`.

**Comment by sboeuf** [comment]
Just a note that rust-vmm/vm-memory#42 and rust-vmm/vm-memory#43 have been closed.
The way to handle this issue is to define an extra GuestMemoryMmap for `virtio-fs` and another one for `virtio-pmem`. This way, when the object will be dropped, the unmap will happen automatically.
