### ISSUE TITLE
CpuManager adds wrong number of CPUs

### ISSUE THREAD

**Issue by weltling** [cloud-hypervisor/cloud-hypervisor#2437]
There seems to be a bug in CpuManager introduced in 55a3a38e140c32748ed49acdacf6d54e59933048. The number of CPUs in the VM is tripled from what is passed in `boot=`. The bug can be reproduced at least with Windows guests. There are also warnings like below

`WARN:vmm/src/cpu.rs:454 -- Unexpected offset for accessing CPU manager device: 0`

This seems to be related to the switch to MMIO usage in the CpuManager in the aforementioned commit.

**Comment by liuw** [comment]
How did you find out that the number of CPUs is tripled? Any indication in Windows? Or did you get that information from a debugging session?

**Comment by weltling** [comment]
In Windows the number is shown in the device manager. Say i'd pass `boot=2`, then the device manager would show 6 CPUs. However, the task manager shows the correct number passed. Still, when adding CPUs, it doesn't reflect the correct number of CPUs.

The further procedure then, when adding a CPU through the API call, continues the wrong numbering. The warning shown is also shown `*3`. When the mentioned commit is reverted, the issue doesn't exist hotadd of CPU seems to work correctly. There must be something in the MMIO mechanism Windows doesn't like, at least to my current observation.

Thanks
