### ISSUE TITLE
Reconsider how network device creation from tap file descriptors is exposed over the API

### ISSUE THREAD

**Issue by alyssais** [cloud-hypervisor/cloud-hypervisor#2488]
Specifying file descriptors by number makes sense for the CLI, because the user can set up the file descriptors however they want before `exec`-ing cloud-hypervisor.  And adding network devices from tap FDs at runtime is certainly a useful feature, but the way it's currently implemented makes it almost useless.

Currently, the API works just like CLI. You send it `{"fds":[3]}`, for example, and it'll try to use descriptor 3 as a tap to back a new virtio-net device.  But that requires there to already be a tap on descriptor 3 in cloud-hypervisor's descriptor table -- it'd have to have been put there before cloud-hypervisor was started, so the only use case this serves is the one where you have a tap device available and set up ahead of time, but for some reason don't want to attach the virtio-net device to the guest until later.  The layout of a running process's file descriptors should really be an implementation detail.  Exposing this makes some abuses possible too: if I have a VM with a serial console, I can send it `{"fds":[1]}`, which will cause it to try to do a tuntap ioctl on stdout, and then close it when the ioctl fails.  Now stdout is closed, but cloud-hypervisor still thinks it's open.  When it does anything else that opens a file descriptor, that new descriptor will become descriptor 1, so further writes to the serial console will instead go to that new descriptor, causing who knows what to happen.

It would be much more useful, and more correct, to allow other processes to actually send file descriptors to cloud-hypervisor using SCM_RIGHTS. (I have a use-case that could really use this feature!)  Failing that, I think that the potential utility of exposing `fds` over the API is so small that it's far outweighed by the downsides of letting other processes tell cloud-hypervisor how to interpret file descriptors at runtime, that it should probably be CLI-only.

**Comment by sboeuf** [comment]
Hi @alyssais, thanks for opening this issue. Could you move this to [Github discussions](https://github.com/cloud-hypervisor/cloud-hypervisor/discussions) ?

So you're suggesting to use ancillary data and the OOB mechanism to send some file descriptors to Cloud Hypervisor, right? The problem I see with this approach is that you need some kind of protocol to be defined by Cloud Hypervisor in order to know, as a separate process, how to connect and send these file descriptors.

Any management layer process making use of a VMM like Cloud Hypervisor is in charge of spawning the VMM's process, therefore it is fully capable of opening the TAP itself and share it with the VMM. I'm not sure why you can't leverage this in your case?

**Comment by alyssais** [comment]
> Hi @alyssais, thanks for opening this issue. Could you move this to [Github discussions](https://github.com/cloud-hypervisor/cloud-hypervisor/discussions) ?

I don't see an option in GitHub to do that. Perhaps it requires repository write access?

> So you're suggesting to use ancillary data and the OOB mechanism to send some file descriptors to Cloud Hypervisor, right? The problem I see with this approach is that you need some kind of protocol to be defined by Cloud Hypervisor in order to know, as a separate process, how to connect and send these file descriptors.

Correct.  I'm not sure I understand the second sentence here.  Can you rephrase the problem?

> Any management layer process making use of a VMM like Cloud Hypervisor is in charge of spawning the VMM's process, therefore it is fully capable of opening the TAP itself and share it with the VMM. I'm not sure why you can't leverage this in your case?

What do you mean by "share it with the VMM"?  Do you mean just tell cloud-hypervisor the name of the TAP and have it open it itself?  Or do you mean open a TAP file descriptor and share that with the VM?  In the former case, it means I can't take advantage of the benefits of using a file descriptor for the TAP device.  One such benefit is that I can set the TAP to be non-persistent before giving it to cloud-hypervisor, and then the kernel will clean it up when cloud-hypervisor closes it.  In the latter case, I don't believe it's possible to add file descriptors to another process at runtime without cooperation from that process, and even if it were, the sending process wouldn't know the descriptor number, so still wouldn't be able to tell cloud hypervisor which descriptor to look at.

**Comment by sboeuf** [comment]
>I don't see an option in GitHub to do that. Perhaps it requires repository write access?

Can you see/click this [link](https://github.com/cloud-hypervisor/cloud-hypervisor/discussions/new) ?

>Correct. I'm not sure I understand the second sentence here. Can you rephrase the problem?

Nevermind, I think I was thinking in terms of CLI while you were explaining the problem with the HTTP API. So basically yes I think we could leverage OOB mechanism to send some fds over the API socket. Cloud Hypervisor could expect to receive such ancillary data only in case `net` would be present.
We could also decide to have a dedicated option in order to send fds through the HTTP API, and we could identify these fds with unique identifiers. Then from the `net` option, we would refer to this id so that Cloud Hypervisor can retrieve the right fd.

**Comment by alyssais** [comment]
>>I don't see an option in GitHub to do that. Perhaps it requires repository write access?
>
> Can you see/click this [link](https://github.com/cloud-hypervisor/cloud-hypervisor/discussions/new) ?

Ah, yes, I can create a new discussion, but I can't convert this issue
into a discussion with this feature:
https://github.com/github/feedback/discussions/2861

Did you mean for me to just close this issue and open a new discussion?

>>Correct. I'm not sure I understand the second sentence here. Can you rephrase the problem?
>
> Nevermind, I think I was thinking in terms of CLI while you were
> explaining the problem with the HTTP API. So basically yes I think we
> could leverage OOB mechanism to send some fds over the API
> socket. Cloud Hypervisor could expect to receive such ancillary data
> only in case `net` would be present.  We could also decide to have a
> dedicated option in order to send fds through the HTTP API, and we
> could identify these fds with unique identifiers. Then from the `net`
> option, we would refer to this id so that Cloud Hypervisor can
> retrieve the right fd.

By "OOB", do you mean MSG_OOB?  If so, unix(7) says:

> UNIX domain sockets do not support the transmission of out-of-band
> data (the MSG_OOB flag for send(2) and recv(2)).

But that seems to be a different thing to sending file descriptors with
SCM_RIGHTS, which I'd expect an API client to just add to its sendmsg
call when it sends the HTTP request to the socket.
