### ISSUE TITLE
Linux virtio-net driver doesn't check feature flags before reprogramming offloads

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/cloud-hypervisor#2528]
While I was trying to create a k8s cluster using libvirt and CLH , I ran into the kenrel soft lock in virtio_net driver on the Guest VM. It actually driven by kubelet --> systemd-udevd --> virtionet.

Host: Mariner ECF baremetal
Guest: Ubuntu Focal Image

After creating the k8s cluster both kubelet and systemd-udevd eating the CPU time 100%.
Any network operation hangs i.e ping ethtool etc.

Just for clarity, in order to reproduce the bug we don't need to create the whole cluster but the master node only. Here are the steps I followed. https://computingforgeeks.com/deploy-kubernetes-cluster-on-ubuntu-with-kubeadm/

**Comment by russell-islam** [comment]
[virtio-net-bug.txt](https://github.com/cloud-hypervisor/cloud-hypervisor/files/6368736/virtio-net-bug.txt)

**Comment by rbradford** [comment]
Can you find out what ethtool command is being running so we can reproduce it in a simpler stack.

**Comment by rbradford** [comment]
I think this is a kernel bug that results in it trying to reprogram the offload even though we don't support it through the feature `VIRTIO_NET_F_CTRL_GUEST_OFFLOADS`. The code in virtio-net doesn't correctly check if the device supports that feature:

https://github.com/torvalds/linux/blob/master/drivers/net/virtio_net.c#L2526

Since we can't really expect everyone to run an updated kernel the easiest solution would be to support reprogramming the offload via the control queue.

You should have seen the follow error in the CH log:

`failed to process ctrl queue: InvalidCtlClass`

**Comment by russell-islam** [comment]
@rbradford Yes I saw this error in ch log. 
`
cloud-hypervisor: 167.037610922s: <_net2_ctrl> ERROR:virtio-devices/src/net_util.rs:172 -- failed to process ctrl queue: InvalidCtlClass
`

**Comment by rbradford** [comment]
@russell-islam Sadly not. Would be good to get the kernel bug fixed too. Since not everyone can run the latest kernel i'm planning to setup a workaround.

**Comment by russell-islam** [comment]
That PR does not fix it. I can still see the same :
`top - 18:55:11 up 7 min,  1 user,  load average: 26.14, 14.55, 6.06
Tasks: 177 total,   6 running, 171 sleeping,   0 stopped,   0 zombie
%Cpu(s):  9.8 us, 43.7 sy,  0.0 ni,  0.0 id, 46.6 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   3934.8 total,   2027.3 free,    869.4 used,   1038.1 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   2836.3 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    697 root      20   0 2299596 102392  65532 S 101.3   2.5   2:33.68 kubelet
`

**Comment by rbradford** [comment]
@russell-islam I never claimed that that PR would fix it. Can you try with this kernel patch: https://github.com/rbradford/linux/commit/6f8a39cb0a87d20605deef982b83f63e613e64f1

**Comment by russell-islam** [comment]
With the updated Kernel, I can see docker is not able to pull the images after initiating the master node. 

`root@kernel-patch-test:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                                        READY   STATUS                  RESTARTS   AGE
kube-system   calico-kube-controllers-d7c67954f-mxmrd     0/1     Pending                 0          7m17s
kube-system   calico-node-gftfl                           0/1     Init:ImagePullBackOff   0          7m18s
kube-system   coredns-558bd4d5db-7zftv                    0/1     Pending                 0          8m34s
kube-system   coredns-558bd4d5db-ks48l                    0/1     Pending                 0          8m35s
kube-system   etcd-kernel-patch-test                      1/1     Running                 0          9m11s
kube-system   kube-apiserver-kernel-patch-test            1/1     Running                 0          9m11s
kube-system   kube-controller-manager-kernel-patch-test   1/1     Running                 0          9m11s
kube-system   kube-proxy-8tm6l                            1/1     Running                 0          8m35s
kube-system   kube-scheduler-kernel-patch-test            1/1     Running                 0          9m11s
root@kernel-patch-test:~#
`

**Comment by rbradford** [comment]
Trivial repro (with unmodified kernel). Note this is a warning and the underlying code does not error out:

```
cloud@cloud:~$ sudo dmesg -c>/dev/null; echo 1  |sudo tee /proc/sys/net/ipv4/ip_forward; sudo dmesg
1
[    9.010404] ------------[ cut here ]------------
[    9.010408] netdevice: ens3: failed to disable LRO!
[    9.010457] WARNING: CPU: 0 PID: 1660 at dev_disable_lro+0x10e/0x150
[    9.010490] CPU: 0 PID: 1660 Comm: tee Not tainted 5.12.0+ #67
[    9.010492] Hardware name: Cloud Hypervisor cloud-hypervisor, BIOS 0 
[    9.010494] RIP: 0010:dev_disable_lro+0x10e/0x150
[    9.010496] Code: e4 81 74 14 be 25 00 00 00 48 89 df e8 ab 9b 0f 00 48 85 c0 4c 0f 44 e3 4c 89 ea 4c 89 e6 48 c7 c7 b0 2a e7 81 e8 a1 d9 10 00 <0f> 0b e9 2b ff ff ff 80 3d 1e 02 13 01 00 49 c7 c5 88 7f e4 81 75
[    9.010498] RSP: 0018:ffffc900003f7cf8 EFLAGS: 00010282
[    9.010503] RAX: 0000000000000000 RBX: ffff888003c76000 RCX: ffff88801f4172d8
[    9.010505] RDX: 00000000ffffffd8 RSI: 0000000000000027 RDI: ffff88801f4172d0
[    9.010506] RBP: ffffc900003f7d28 R08: 0000000000000000 R09: ffffc900003f7ad8
[    9.010507] R10: ffffc900003f7ad0 R11: ffffffff8274d808 R12: ffff888003c76000
[    9.010508] R13: ffffffff81e38211 R14: ffffffff827880c0 R15: 0000000000000000
[    9.010509] FS:  00007f28c2065580(0000) GS:ffff88801f400000(0000) knlGS:0000000000000000
[    9.010511] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    9.010512] CR2: 00007ffcef80d818 CR3: 0000000012410001 CR4: 00000000003706b0
[    9.010516] Call Trace:
[    9.010517]  inet_forward_change+0xd5/0xe0
[    9.010525]  devinet_sysctl_forward+0xf4/0x120
[    9.010527]  proc_sys_call_handler+0x11f/0x210
[    9.010540]  proc_sys_write+0xe/0x10
[    9.010543]  new_sync_write+0x10f/0x1a0
[    9.010547]  vfs_write+0x1b7/0x270
[    9.010549]  ksys_write+0x62/0xe0
[    9.010550]  __x64_sys_write+0x15/0x20
[    9.010552]  do_syscall_64+0x38/0x50
[    9.010563]  entry_SYSCALL_64_after_hwframe+0x44/0xae
[    9.010572] RIP: 0033:0x7f28c1f831e7
[    9.010574] Code: 64 89 02 48 c7 c0 ff ff ff ff eb bb 0f 1f 80 00 00 00 00 f3 0f 1e fa 64 8b 04 25 18 00 00 00 85 c0 75 10 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 51 c3 48 83 ec 28 48 89 54 24 18 48 89 74 24
[    9.010575] RSP: 002b:00007ffcef80d708 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
[    9.010577] RAX: ffffffffffffffda RBX: 0000000000000002 RCX: 00007f28c1f831e7
[    9.010579] RDX: 0000000000000002 RSI: 00007ffcef80d800 RDI: 0000000000000003
[    9.010580] RBP: 00007ffcef80d800 R08: 0000000000000002 R09: 0000000000000001
[    9.010581] R10: 00000000000001b6 R11: 0000000000000246 R12: 0000000000000002
[    9.010582] R13: 00005613e0d7c2c0 R14: 0000000000000002 R15: 00007f28c205e8a0
[    9.010583] ---[ end trace 745d70986a10fa44 ]---

```

I think we need to go ahead and implement the support for the offload changing in the control queue.

**Comment by rbradford** [comment]
@russell-islam Can you test if #2551 addresses this issue. No need to use a custom kernel.

**Comment by russell-islam** [comment]
> @russell-islam Can you test if #2551 addresses this issue. No need to use a custom kernel.

Will do that and keep you updated.

**Comment by russell-islam** [comment]
Verified that latest CLH resolves this issue.

root@k8s-master:~# kubectl get nodes
NAME          STATUS   ROLES                  AGE     VERSION
k8s-master    Ready    control-plane,master   6d22h   v1.21.0
k8s-worker1   Ready    <none>                 6d22h   v1.21.0
k8s-worker2   Ready    <none>                 6d22h   v1.21.0
root@k8s-master:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@k8s-master:~#
