### ISSUE TITLE
Limit http thread syscalls when passing a FD

### ISSUE THREAD

**Issue by bryteise** [cloud-hypervisor/cloud-hypervisor#2534]
From https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2495#discussion_r620612694 when using an FD instead of a path for the http socket file, additional filters can be added for socket, bind and listen syscalls.

**Comment by rbradford** [comment]
If the `socket/bind/listen` is done the in vmm thread then we can reduce the seccomp filter for the http thread.

**Comment by bryteise** [comment]
Oh, do you want to always use the fd to open the socket?
