### ISSUE TITLE
Fails to boot with OVMF & virtio-net MQ

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/cloud-hypervisor#2578]
**Describe the bug**
VM does not start when we use OVMF(custom build that is used by CI). If I remove the network option from libvirt config file
vm starts fine and doesn't panic. 

The same configuration with network-enabled works just fine using rust hypervisor-fw.

**To Reproduce**
Create a vm and start is using the attached config file master.txt

**Version**

Output of `cloud-hypervisor --version`:

muislam@cbl-mariner-muislam-desktop [ ~/dev/libvirt/cloud-hypervisor ]$ /usr/bin/cloud-hypervisor --version
cloud-hypervisor v15.0-1-ge3efa9a5
muislam@cbl-mariner-muislam-desktop [ ~/dev/libvirt/cloud-hypervisor ]$

Did you build from source, if so build command line (e.g. features): cargo build --all

**VM configuration**

See attached

Guest OS version details:
Reproduced with both Focal and Mariner image
Host OS version details:
Mariner OS
**Logs**

thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', vmm/src/device_manager.rs:3999:27
stack backtrace:
==== seccomp violation ====
Try running with `strace -ff` to identify the cause and open an issue: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/new

After modifying device_manager
muislam@cbl-mariner-muislam-desktop [ ~/dev/libvirt/cloud-hypervisor ]$ git diff
```
diff --git a/vmm/src/device_manager.rs b/vmm/src/device_manager.rs
index 48f66c3f..6b90563e 100644
--- a/vmm/src/device_manager.rs
+++ b/vmm/src/device_manager.rs
@@ -3996,7 +3996,13 @@ impl BusDevice for DeviceManager {
 impl Drop for DeviceManager {
     fn drop(&mut self) {
         for (device, _, _) in self.virtio_devices.drain(..) {
-            device.lock().unwrap().shutdown();
+            //device.lock().unwrap().shutdown();
+            if let Ok(mut d) = device.lock() {
+                d.shutdown();
+            } else {
+                error!("muislam device unwrap error");
+            }
+
         }
     }
 }
```
Log:
sudo vim /var/log/libvirt/ch/k8s-master.log
thread 'vmm' panicked at 'removal index (is 0) should be < len (is 0)', library/alloc/src/vec/mod.rs:1349:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
cloud-hypervisor: 2.375953118s: <vmm> ERROR:vmm/src/device_manager.rs:4003 -- muislam device unwrap error
Failed to join on VMM thread: Any

Linux kernel output:

**Comment by russell-islam** [comment]
[master.txt](https://github.com/cloud-hypervisor/cloud-hypervisor/files/6418304/master.txt)

**Comment by liuw** [comment]
This suggests that the mutex is poisoned somehow. Does this work without libvirt? That is, you run Cloud Hypervisor with the same command line options with the same image.

**Comment by liuw** [comment]
Are you able to do `strace -ff`? I guess that's not easy since libvirt is involved?

Is there anything in dmesg that starts with `audit`?

**Comment by rbradford** [comment]
@russell-islam Please provide the following details:

* The latest master will now output the config used to create the VM at info level. Provide the CH logs for the VM booting correctly and incorrectly with (`-v`)
* The output from the serial port (and since you're using OVMF compile CH with `fwdebug` feature)
* Run with `RUST_BACKTRACE=full` and `--seccomp=false` to allow the backtrace to be printed
* Can you reproduce the issue by attempting to run cloud-hypervisor directly and passing the parameters on the command line.

**Comment by rbradford** [comment]
> Are you able to do `strace -ff`? I guess that's not easy since libvirt is involved?
> 
> Is there anything in dmesg that starts with `audit`?

The seccomp issue may be a misdirection as this is typically what will be seen in unprivileged threads when Rust tries to print a backtrace.

**Comment by russell-islam** [comment]
> This suggests that the mutex is poisoned somehow. Does this work without libvirt? That is, you run Cloud Hypervisor with the same command line options with the same image.

I have to exclude the tap FDs as libvirt creates the FDs and executes the command along with that.

**Comment by rbradford** [comment]
> > This suggests that the mutex is poisoned somehow. Does this work without libvirt? That is, you run Cloud Hypervisor with the same command line options with the same image.
> 
> I have to exclude the tap FDs as libvirt creates the FDs and executes the command along with that.

Just have bash open the fd (see docs/macvtap-bridge.md for details)

**Comment by russell-islam** [comment]
[serial-log.txt](https://github.com/cloud-hypervisor/cloud-hypervisor/files/6423402/serial-log.txt)

**Comment by russell-islam** [comment]
[vm_k8s-master.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/6423408/vm_k8s-master.log)

**Comment by russell-islam** [comment]
@rbradford Logs attached.

**Comment by liuw** [comment]
```
17:     0x61662215a838 - <virtio_devices::net::Net as virtio_devices::device::VirtioDevice>::activate::h459cce61d176e44b
                               at /home/muislam/dev/libvirt/cloud-hypervisor/virtio-devices/src/net.rs:554:39
```

This looks interesting in `vm_k8s-master.log`.

**Comment by russell-islam** [comment]
Following script runs the vm just fine:
`
 # The MAC address must be attached to the macvtap and be used inside the guest
  2 mac="c2:67:4f:53:29:cb"
  3 # Host network adapter to bridge the guest onto
  4 host_net="eno1"
  5
  6 # Create the macvtap0 as a new virtual MAC associated with the host network
  7 sudo ip link add link "$host_net" name macvtap0 type macvtap
  8 sudo ip link set macvtap0 address "$mac" up
  9 sudo ip link show macvtap0
 10
 11 # A new character device is created for this interface
 12 tapindex=$(< /sys/class/net/macvtap0/ifindex)
 13 tapdevice="/dev/tap$tapindex"
 14
 15 # Ensure that we can access this device
 16 sudo chown "$UID.$UID" "$tapdevice"
 17
 18 # Use --net fd=3 to point to fd 3 which the shell has opened to point to the /dev/tapN device
 19 target/debug/cloud-hypervisor \
 20     --kernel /home/muislam/dev/libvirt/vm/OVMF-master.fd \
 21     --disk path=/home/muislam/dev/libvirt/vm/focal-server-cloudimg-amd64-master.raw \
 22     --cpus boot=1 --memory size=512M \
 23         --net fd=3,mac=$mac 3<>$"$tapdevice"

`

**Comment by rbradford** [comment]
Your standalone test doesn't replicate the number of queues.

**Comment by rbradford** [comment]
@russell-islam I also recommend you don't use virtio-iommu unless you know you need it.

**Comment by russell-islam** [comment]
> @russell-islam I also recommend you don't use virtio-iommu unless you know you need it.

Ack. :)

**Comment by russell-islam** [comment]
I can confirm, VM boots fine with those fixes.

**Comment by russell-islam** [comment]
Mariner guest boots fine now. Thank for quick turn around.
