### ISSUE TITLE
Emulating NVMe disks

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#2594]
QEMU is able to emulate NVMe disks for the guest and plug in any backend storage. It would be good if Cloud Hypervisor can do the same.

This is an issue to gather ideas and discuss possible designs.

**Comment by rbradford** [comment]
From our offline discussion this feature is about exposing a NVMe controller in the guest where the backend is across a socket running in another process where it can handle the specific logic. The mechanism for operation would be very similar for vhost-user but be more efficient if the underlying storage is itself NVMe as the individual I/O queues could possibly be directly mapped by using something like SPDK.

**Comment by rbradford** [comment]
I think the best approach might be doing something like `vfio-user` to support running the PCI device in another process. An NVMe controller is in fact one of the examples: https://github.com/nutanix/libvfio-user#nvmfvfio-user

**Comment by sboeuf** [comment]
I agree this sounds like a good approach as it could also be a good fit for other devices that needs to be emulated and exposed directly to the guest.

**Comment by rbradford** [comment]
Using the vfio-user and the SPDK provided NVMe device then it is possible to boot a VM using NVME device (including as rootfs). I think this is sufficient for your use case.

**Comment by rbradford** [comment]
With the SPDK vfio-user NVMe device plus the new vfio-user support in Cloud Hypervisor (`--user-device`) I think we can close this issue. As well as backing the device with a plain file you can back it by more complex solutions. How to use this with CH is documented here: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vfio-user.md

**Comment by iggy** [comment]
The only downside I see to this is SPDK's extreme use of CPU to handle those userspace devices. I don't think any cloud provider is going to want to burn an entire core for each emulated device. I tried doing this to test Ceph RBD and the default config used 2 cores for every device. The best I was able to manage was getting it down to one core per device.

**Comment by jlevon** [comment]
We are actively working on fixing that. Let me know if you want to try things out ;)
