### ISSUE TITLE
Support for sheepdog

### ISSUE THREAD

**Issue by arafatms** [cloud-hypervisor/cloud-hypervisor#2621]
hii～
I think cloudhypervisor supports the sheepdog protocol, it would be a good idea to expand the support for distributed block storage. Do you have any plans for this in the future?

**Comment by sboeuf** [comment]
Hi, we didn't do any specific work for supporting sheepdog, but as long as it can expose the backing storage as a block device, Cloud Hypervisor should simply work fine with it.

**Comment by arafatms** [comment]
got it. thanks~
