### ISSUE TITLE
Consideration of the interrupt model

### ISSUE THREAD

**Issue by terenceli** [cloud-hypervisor/cloud-hypervisor#265]
Hi all,
I want to know what's the consideration for using userspace ioapic(irqsplit) model as default?
IIRC, the qemu/kvm will always try to put the irqchip in kernel. Isn't it more efficient putting the irqchip in kernel?

Thanks,
Li Qiang

**Comment by sameo** [comment]
It's a security concern. The IOAPIC code is not used very often, basically at device setup time. It's not on the hot path, so moving it away from the kernel removes potential security concerns while having very minimal (if any) performance impact.

An interesting read:
http://events17.linuxfoundation.org/sites/events/files/slides/Performant%20Security%20Hardening_0.pdf
