### ISSUE TITLE
lsmod error

### ISSUE THREAD

**Issue by xiaofeng0303** [cloud-hypervisor/cloud-hypervisor#2695]
I start a vm(centos7)by cloud-hypervisor,
when exec `lsmod` in vm output an error:
```
 libkmod: kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
```
how do i know this guest kernel modules

**Comment by iggy** [comment]
You didn't say what kernel you were using or how you started cloud-hypervisor.
