### ISSUE TITLE
vfio-user support

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2718]
vfio-user supports running PCI devices in another process

Use cases: supporting NVMe controller / TPM device 
Protocol: https://github.com/nutanix/libvfio-user/blob/master/docs/vfio-user.rst

API addition:

`--user-device socket=<socket>` and equivalent JSON API.

Initial implementation focussed only on client (i.e VMM side). Server side support might be useful for testing.

**Comment by rbradford** [comment]
QEMU now has support for a multi-process model (limited to just one type of SCSI controller at the moment) that is very similar to vifio-user:

Documentation: https://github.com/qemu/qemu/blob/master/docs/system/multi-process.rst
Protocol: https://github.com/qemu/qemu/blob/master/include/hw/remote/mpqemu-link.h
Proxy: https://github.com/qemu/qemu/blob/master/hw/remote/proxy.c

There is a comment in the protocol definition:

```
 * This uses a private protocol between QEMU and the remote process. vfio-user
 * protocol would supersede this in the future.
```

**Comment by sboeuf** [comment]
Hi @tmakatos @jlevon @swapnili
We've recently implemented the `vfio-user` protocol as part of Cloud Hypervisor. We've been testing this with both the GPIO example as well as the SPDK/NVMe one. For the NVMe case, we get the following error everytime we boot a VM:
```
ctrlr.c:2583:nvmf_ctrlr_identify: *ERROR*: Identify command with unsupported CNS 0x06
```
Do you have any idea what this error indicates?

**Comment by jlevon** [comment]
@sboeuf which guest are you running? SPDK is lacking support for that command ("I/O Command Set Specific Identify Controller data structure") but we haven't seen this ourselves.

cc @changpe1

**Comment by jlevon** [comment]
Also, does nvme within the guest still function, or is that a fatal error for you?

**Comment by jlevon** [comment]
Also, FYI, don't know if you're aware, but MPQEMU move to vfio-user protocol is actively underway by Oracle.

**Comment by sboeuf** [comment]
@jlevon 
>which guest are you running? SPDK is lacking support for that command ("I/O Command Set Specific Identify Controller data structure") but we haven't seen this ourselves.
A focal Ubuntu image with 5.13 kernel.

> Also, does nvme within the guest still function, or is that a fatal error for you?

It's not a fatal error. I see some corruption issues though, but I'm not sure this is related.

>Also, FYI, don't know if you're aware, but MPQEMU move to vfio-user protocol is actively underway by Oracle.

That's good. Do you know if they ran into any similar issues when using QEMU? Especially the vIOMMU use case, do you know if someone have already tried it?

**Comment by jlevon** [comment]
cc @jraman567

I'm not sure myself on viommu

**Comment by jraman567** [comment]
@sbouf @jlevon We haven't tested vIOMMU yet - will test and get back to you shortly. Thank you!

**Comment by sboeuf** [comment]
@jraman567 
>We haven't tested vIOMMU yet - will test and get back to you shortly. Thank you!

Oh okay, but do you expect something to be handled differently from the server side? I thought it should be transparent.

**Comment by jraman567** [comment]
@sboeuf I don't believe special handling necessary on the server side.

The client exposes the parts of the RAM that are necessary for the device (running on the server) to perform DMA. When vIOMMU is enabled, the client only exposes parts of the RAM that are mapped to the device via the vIOMMU - as such I don't believe the server needs to perform any special handling.

**Comment by sboeuf** [comment]
I fully agree. Please keep me posted on your experiments as I'm having some issues with vIOMMU :-/

**Comment by changpe1** [comment]
> @sboeuf which guest are you running? SPDK is lacking support for that command ("I/O Command Set Specific Identify Controller data structure") but we haven't seen this ourselves.
> 
> cc @changpe1

this is a NVMe 2.0 command, it doesn't matter not to support it.

**Comment by sboeuf** [comment]
A quick summary of the vfio-user status here:
- Running the NVME/SPDK backend fails with multiple threads, which is a known issue: https://github.com/spdk/spdk/issues/2074
- There is a pending patch that helps supporting multiple regions in `libvfio-user`: https://github.com/nutanix/libvfio-user/pull/586
- The vIOMMU has not been tested yet (@jraman567 working on it), but on my side I've hit multiple issues related to the ability to handle multiple regions, for which I opened two issues: https://github.com/spdk/spdk/issues/2101 and https://github.com/nutanix/libvfio-user/issues/588.

I think it'd be a good idea to let things settle down on both `vfio-user` and `spdk/nvme` side of things since it's still under active development and stabilization.

**Comment by jlevon** [comment]
Just for clarity, is vIOMMU a strict requirement for your use cases?

**Comment by sboeuf** [comment]
@jlevon 
>Just for clarity, is vIOMMU a strict requirement for your use cases?

I don't think we have a strict requirement at the moment for `vfio-user` with vIOMMU, but we want to give that possibility to our users in case they might run nested, or even internally to perform some VFIO tests on the PCI device that is exposed by vfio-user.
Just trying to cover all the potential use cases :)

**Comment by jlevon** [comment]
Understood, thanks for the context. (More of a side note, but we've successfully used SPDK/VFIO in unsafe mode (i.e. no iommu) inside a guest.)

**Comment by tmakatos** [comment]
@sboeuf I've succesfully used a vIOMMU on SPDK not too long ago, the major problems I had were:

1. figuring out the correct QEMU command line, I guess you've already solved that in your case
2. making sure that SPDK doesn't have to map multiple DMA segments when setting up queues or handling a request: https://review.spdk.io/gerrit/c/spdk/spdk/+/7934

These were the main bits, do let me know if you need more help and I'll try to dig out more information. JJ from Oracle is also knowledgeable on this.

**Comment by rbradford** [comment]
I think this issue can be closed. We are already tracking the migration in a separate issue.
