### ISSUE TITLE
sgx: support conditional provisioning key setting for guests

### ISSUE THREAD

**Issue by mythi** [cloud-hypervisor/cloud-hypervisor#2756]
Guests must have SGX provisioning keys conditionally enabled. This is done via `KVM_CAP_SGX_ATTRIBUTE`.

**Comment by sboeuf** [comment]
I'll look into this next week!

**Comment by sboeuf** [comment]
I think all we need to support this is listed through the following patch: https://github.com/intel/qemu-sgx/commit/0e514e27da3a10a8198bc4afa8aecdb844297d33
First we need to check `KVM_CAP_SGX_ATTRIBUTE` is supported on the host, and if that's the case, we'll open `/dev/sgx_provision` and provide the file descriptor when enabling `KVM_CAP_SGX_ATTRIBUTE`.
And from a guest perspective, it needs to know that `PROVISIONKEY` is supported, which means we must patch the guest CPUID accordingly.

@mythi could you confirm if this is what you had in mind before I proceed with the implementation?
