### ISSUE TITLE
Support multiple --fs flags for providing multiple virtiofs filesystems

### ISSUE THREAD

**Issue by FireyFly** [cloud-hypervisor/cloud-hypervisor#2791]
Currently (as of the v16.0 release, at least) the `--fs` flag setting up a virtiofs filesystem mapping can only be passed once.

    error: The argument '--fs <fs>' was provided more than once, but cannot be used multiple times

I don't see any technical reason for why that would be the case (quite the contrary, given the 'tag' parameter), so consider this a feature request for being able to supply multiple `--fs` mappings when spawning a VM.

**Comment by sboeuf** [comment]
This actually works if you use the CLI correctly:
```
--fs tag=myfs,socket=/tmp/vu_fs.sock tag=myfs2,socket=/tmp/vu_fs_2.sock
```

**Comment by FireyFly** [comment]
Ohh... my bad! I didn't realise that's how multiple mappings were meant to be passed.

I think the -h output could probably make that a bit more clear, and docs/fs.md could probably mention how to map multiple filesystems. I could put together a PR later with a proposal for some changes to hopefully avoid others misunderstanding the options syntax like I did. :)

I'll close this for now since it's invalid/not actually an issue. Thanks!

**Comment by iggy** [comment]
I personally would like to see a PR about that. I've run into that exact problem before and ended up code diving to figure out what the right format was. And that's saying a lot since I'm terrible with Rust.
