### ISSUE TITLE
Migration support for vhost-user

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#2813]
In order to support live migration for vhost-user devices, we need Cloud Hypervisor to support some extra vhost-user commands and specific protocol features.
The specification gives the details [here](https://github.com/qemu/qemu/blob/master/docs/interop/vhost-user.rst#migration) about what needs to happen to make this work.
In particular, the following commands will need to be implemented as part of the vhost crate and called in the right places from Cloud Hypervisor codebase.

**Comment by sboeuf** [comment]
After some investigations, here is a proposal about what should be done in order to support live migration for vhost-user devices.

First of all, we must get vhost-user devices to support snapshot/restore. Looking at the code, I don't think there's much to do, the only thing might be to "stop" the queues when the VM is paused, and re-"start" them when the VM is resumed.

Then we need the support for logging the pages that might have been dirtied by a vhost-user device:
- We need a way to let vhost-user devices (actually could be all devices) know the migration has started/stopped. This will be translated into vhost-user specific commands (first `SET_LOG_BASE`, then `SET_FEATURES` with `VHOST_F_LOG_ALL`, and then `SET_VRING_ADDR` with `VHOST_VRING_F_LOG`). This means when migration is started, we set the log shared file, we update the feature set, and we update the vring with the flag indicating the logging can start.
- From vhost-user perspective, once the migration has been started, that means the logging has been enabled, which leads to 2 possibilities on how to retrieve the dirty pages:
  - Either we create an extra function to let the devices know they should update the dirty bitmaps (which will be directly marked through vm-memory)
  - Or we create a function to ask each device to return a dirty bitmap, which will need to be merged with the ones generated from `MemoryManager`

About these two options, I'd rather do the first one, meaning we directly update through guest memory regions. Maybe we can leverage the `Migratable` trait by extending the trait definition with some extra functions:
- `start()`
- `stop()`
- `log_dirty_pages()` (or `update_dirty_pages()`)

PS: We don't need any of the postcopy commands using the `userfaultfd` mechanism since the way the migration is implemented in Cloud Hypervisor does not require any of this. The destination VM is only started after the memory has been fully migrated, meaning we avoid a bunch of complexity on the destination code path.

@rbradford @likebreath please give me some feedback before I jump into the implementation :)

**Comment by rbradford** [comment]
> From vhost-user perspective, once the migration has been started, that means the logging has been enabled, which leads to 2 possibilities on how to retrieve the dirty pages:
> 
>     * Either we create an extra function to let the devices know they should update the dirty bitmaps (which will be directly marked through vm-memory)
> 

How does that work? Does `vm-memory` have a manual update this page method?

>     * Or we create a function to ask each device to return a dirty bitmap, which will need to be merged with the ones generated from `MemoryManager`

This was how I was thinking it would work. Would also be easier to tweak the algorithm and gather stats if the different dirty page sources were separate.

**Comment by sboeuf** [comment]
>How does that work? Does vm-memory have a manual update this page method?

That's how we do this for `virtio-block` already: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/block_util/src/lib.rs#L340-L343

**Comment by rbradford** [comment]
> > How does that work? Does vm-memory have a manual update this page method?
> 
> That's how we do this for `virtio-block` already: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/block_util/src/lib.rs#L340-L343

Yup I remember now. Your call! It will be much easier that way rather than trying to propagate the dirty page list from the device all the way up to the `Vm` object

**Comment by sboeuf** [comment]
>Yup I remember now. Your call! It will be much easier that way rather than trying to propagate the dirty page list from the device all the way up to the Vm object

Yes that's why this was my preferred option :)

Can I have your opinion about this as well:
>Maybe we can leverage the Migratable trait by extending the trait definition with some extra functions:
>  -  start()
>  -  stop()
>  -  log_dirty_pages() (or update_dirty_pages())

**Comment by rbradford** [comment]
> > Yup I remember now. Your call! It will be much easier that way rather than trying to propagate the dirty page list from the device all the way up to the Vm object
> 
> Yes that's why this was my preferred option :)
> 
> Can I have your opinion about this as well:
> 
> > Maybe we can leverage the Migratable trait by extending the trait definition with some extra functions:
> > 
> > * start()
> > * stop()
> > * log_dirty_pages() (or update_dirty_pages())

I'm not sure. Currently the `Migratable` trait isn't really used and we discussed dropping it. Is that `start/stop` actually `start_dirty_page_logging()` ? because otherwise it's very similar to `pause()`. I would prefer you create a new trait for the purpose.

**Comment by sboeuf** [comment]
>I'm not sure. Currently the Migratable trait isn't really used and we discussed dropping it. Is that start/stop actually start_dirty_page_logging() ? because otherwise it's very similar to pause(). I would prefer you create a new trait for the purpose.

It's not gonna be easy to drop `Migratable` since it's used to understand if a device can be migrated or not. And since it's completely empty, it's like starting with a new trait.
Yes the start/stop is about logging. So you suggest we could rely on `pause()` and `resume()` to trigger the logging?

**Comment by rbradford** [comment]
I just think the name `start()/stop()` is too vague.

**Comment by rbradford** [comment]
(Also I would first worry about implementing the state restoration of the vhost-user in snapshot()/restore() rather than advanced features like when to enable page logging for the live migration case.)

**Comment by sboeuf** [comment]
>(Also I would first worry about implementing the state restoration of the vhost-user in snapshot()/restore() rather than advanced features like when to enable page logging for the live migration case.)

Of course, I'm actively working on this at the moment, but I'm trying to clarify the next step for when snapshot/restore will properly work.

**Comment by sboeuf** [comment]
Still some functional issues.
