### ISSUE TITLE
Support for remote control

### ISSUE THREAD

**Issue by arafatms** [cloud-hypervisor/cloud-hypervisor#2820]
hii, Is there any methods to remote control cloud hypervisor VM suck as Qemu VNC? Especially when Im running windows server, I cannot do remote control.

**Comment by iggy** [comment]
cloud-hypervisor doesn't emulate any sort of graphics device. The intent is for you to control it via serial, virtio console, or more than likely just remotely via whatever means your guest offers. For example, the Windows unit tests for cloud-hypervisor use SSH to talk to the guest.

**Comment by sboeuf** [comment]
You can start a Windows server VM with a `virtio-net` attached to it. As long as you know the IP inside the guest, you can use RDP to connect to your Windows guest.
