### ISSUE TITLE
Support for PACKED RING

### ISSUE THREAD

**Issue by arafatms** [cloud-hypervisor/cloud-hypervisor#2836]
hiii~, I am studying PACKED RING recently. PACKED RING is a trend. QEMU, virtio1.1 and some vhost backends such as SPDK have been supported. I think the cloud hypervisor should also support this feature.

Qemu patch:
https://patchew.org/QEMU/20200522171726.648279-1-stefanha@redhat.com/

SPDK patch:
https://review.spdk.io/gerrit/c/spdk/spdk/+/2821

SPDK performance report:
https://ci.spdk.io/download/performance-reports/SPDK_vhost_perf_report_2010.pdf

@sboeuf @rbradford

**Comment by sboeuf** [comment]
Just a quick note that we could get this for free by moving Cloud Hypervisor to https://github.com/rust-vmm/vm-virtio/

**Comment by sboeuf** [comment]
@rbradford I don't think we want to support this. And if this was ever happening, it'd have to be done in `virtio-queue` crate from `rust-vmm` anyway.
