### ISSUE TITLE
Dirty page tracking always on

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#2858]
Cloud Hypervisor currently turns on dirty page tracking when constructing the guest. That incurs performance hit.

How about making it only turn on dirty page tracking when necessary?

CC @russell-islam

**Comment by russell-islam** [comment]
Yes. I found this while I was implementing live migration for MSHV. For MSHV we plan to enable this while we start live migration and disable it after completion.

**Comment by likebreath** [comment]
Thanks for opening this issue. With a quick glance of KVM API doc, it looks like we can modify the flag of user memory regions with `KVM_SET_USER_MEMORY_REGION`, e.g. turning on/off flag `KVM_MEM_LOG_DIRTY_PAGES`. 

We will also need some (small) refactoring/extensions to the live-migration code path to support this, e.g. adding APIs to disable or enable `dirty-page-tracking` to the `Hypervisor::Vm` Trait and integrating them to the current migration code. After that, we can have different implementations of the APIs for kvm and mshv. 

@russell-islam I assume you were/are working on similar refactoring mentioned above. How is the refactoring going on your side? If you need any help or need me to take the first shot on the refactoring, please just let me know. ( I will certainly take care the kvm related changes.)

Also, for the "dirty-page-tracking" from the `vm-memory` crate, I believe it does not provide a way to disable/enable the "dirty-page-tracking" as the `bitmap` is a part of the `GuestMemory*` structs. I will double check on that.

Any thoughts or questions, please share. Thank you. @liuw @sboeuf

**Comment by liuw** [comment]
FWIW I think the dirty page tracking is less detrimental since it does not involve making memory read-only and then processing page faults.

**Comment by russell-islam** [comment]
@likebreath I have implemented two API in the hypervisor VM implementation for MSHV.
1. enable_dirty_page_tracking
2. disable_dirty_page_tracking
Also two different functions start_live_migration and complete_live_migration in the memory manager , eventually these two functions can call hypervisor-specific functions. I can create a PR next week.

**Comment by likebreath** [comment]
@russell-islam Sounds good. Look forward to your PR. Feel free to share if you need any inputs from us. 

As mentioned earlier, I will take care the kvm-specific changes after landing your PR. Assigning the issue to both of us. Thank you.

**Comment by rbradford** [comment]
Can we get some numbers for the overhead for the KVM bitmap tracking.

**Comment by likebreath** [comment]
> Can we get some numbers for the overhead for the KVM bitmap tracking.

@rbradford I can do it. But I will need some advises on what is a good setup/workload for this kind of measurements. Any suggestions?

**Comment by liuw** [comment]
STREAM can test sustained memory bandwidth https://github.com/jeffhammond/STREAM https://www.cs.virginia.edu/stream/ref.html

**Comment by rbradford** [comment]
> > Can we get some numbers for the overhead for the KVM bitmap tracking.
> 
> @rbradford I can do it. But I will need some advises on what is a good setup/workload for this kind of measurements. Any suggestions? 

I believe that under KVM the write detection is handled as part of the paging in and once written too goes through the usual fast path until reset.

Typical metrics we like are: boot time, iperf with virtio-net and fio. 

With boot time we already see that the paging behaviour is very costly (compare page size to see this) so I don't think it would make much difference there.

That being said if the change to dynamically control that is not too intrusive I'd be happy to see that before the metrics.

**Comment by likebreath** [comment]
> That being said if the change to dynamically control that is not too intrusive I'd be happy to see that before the metrics.

Based on my comments to PR #2887, I did a quick draft for dynamically control of dirty-logging with KVM. The changes looks to be fairly small (non-intrusive), and adding mshv support should be straightforward/small (with providing mshv-specific APIs). My draft is [here](https://github.com/likebreath/cloud-hypervisor/commits/0721/dynamic_dirty_page_logging). Please let me know your thoughts or questions. 

Major changes to the vmm crate are:
1) Add calls to `hypervisor::vm::enable_dirty_log()` from `MemoryManager::start_memory_dirty_log()` ([draft](https://github.com/likebreath/cloud-hypervisor/blob/5e91e590c342ea0516fd5bf509334d28c8d5f505/vmm/src/memory_manager.rs#L1574-L1578)).
2) Add to "Vmm::vm_send_migration()" a new step `Vm::complete_memory_dirty_log()` after sending the last set of dirty pages ([draft](https://github.com/likebreath/cloud-hypervisor/blob/5e91e590c342ea0516fd5bf509334d28c8d5f505/vmm/src/lib.rs#L1052-L1053)), which will call into `hypervisor::vm::disable_dirty_log()` ([draft](https://github.com/likebreath/cloud-hypervisor/blob/0721/dynamic_dirty_page_logging/vmm/src/memory_manager.rs#L1599-L1603))

I also did a quick test by enforcing the creation of guest RAM memory regions without "dirty-logging", and it worked for "local" live-migration on my dev machine. 

It also allows us to further simplify `MemoryManager::create_userspace_mapping()` as we will always create guest memory regions without `dirty-logging` (for both kvm and mshv).
