### ISSUE TITLE
E820/ACPI table generation code assumes GuestMemoryMmap is RAM

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#289]
This currently holds but will not hold when we fix #240. Ideally we should generated the E820 table from the `arch_memory_regions()` call which already had details of the gaps so that is it not necessary to calculate that again.

This call can also be used to provide the calculate the start of the device area for the ACPI tables.

**Comment by sboeuf** [comment]
@rbradford I think we could close this one since we now know that we won't have different types of memory. So as long as we're providing the GuestMemoryMmap instance corresponding to RAM only, I think the code is safe.

**Comment by rbradford** [comment]
@sboeuf - ACK!
