### ISSUE TITLE
Preferred behavior of source VM post live-migration

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#2895]
For now, the source VM can be either paused or running after live-migration. More specially, the source VM will stay being `Running` when an error occurs after before we pause the VM while sending migration [here](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/e6db59990767aceca90bc3fc4505dc0064cd8ce0/vmm/src/lib.rs#L1047); otherwise, the source VM will stay being `Paused`, e.g., when the live-migration is completed successfully or when an error occurs after the we pause the VM. 

We may need to revisit what is the preferred behavior of source VM post live-migration. Some of my questions/opens:

1. Do we want to keep the source VM at all? Now we can resume the source VM when a live-migration is completed successfully? 
2. If we decide to keep the source VM, we should at least ensure the consistency of the source VM state upon failed migration: either always `Paused` or always `Running`. It sounds better to me if we keep the source VM `Running`, as we don't want to interrupt the guest workload when migration failed.
2. Assuming the dynamic control of dirty-pages logging is landed (#2894 ), we need to decide whether/when we want to stop dirty-pages logging. 

/cc @rbradford @sboeuf @russell-islam @liuw

**Comment by likebreath** [comment]
I put up a quick draft PR here https://github.com/likebreath/cloud-hypervisor/pull/11 to ensure the source VM behavior is more consistent with the situations mentioned above. In short, it ensures the following:

1. The source VM will be paused only when the migration is completed successfully, or otherwise it will keep running;

2. The source VM will always stop dirty pages logging; 

Any comments or questions, please let me know. Thank you.

**Comment by rbradford** [comment]
> I put up a quick draft PR [likebreath#11](https://github.com/likebreath/cloud-hypervisor/pull/11) based on (PR #2894) to ensure the source VM behavior is more consistent with the situations mentioned above. In short, it ensures the following:
> 
>     1. The source VM will be paused only when the migration is completed successfully, or otherwise it will keep running;
>     2. The source VM will always stop dirty pages logging;

This sounds correct to me and what I was going to suggest is the right answer to your question! :rocket:
