### ISSUE TITLE
Pinning vcpu on cpu

### ISSUE THREAD

**Issue by D1abloRUS** [cloud-hypervisor/cloud-hypervisor#2908]
Hi! Is it possible to create vcpu pinning on cpu? QEMU has an [implementation](https://lists.nongnu.org/archive/html/qemu-discuss/2016-01/msg00058.html)

**Comment by sboeuf** [comment]
There's no special command line option for Cloud Hypervisor. The proper way to perform CPU pinning is by identifying the vcpu threads run by the Cloud Hypervisor process. Once you identified the threads, you can use cgroups to pin them to the physical CPUs you want.

**Comment by D1abloRUS** [comment]
@sboeuf yes it works, thanks!
