### ISSUE TITLE
Move to rust-vmm/seccompiler crate

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#2929]
The following PR https://github.com/rust-vmm/seccompiler/pull/7 is the upstream version of the `seccompiler` crate we use. We need to check the PR works well with Cloud Hypervisor and give some feedback before it gets merged.
Once merged, we should move Cloud Hypervisor fully to this crate.

**Comment by sboeuf** [comment]
@likebreath could you please have a try, the point is to make sure there's no breaking changes in this new version that would prevent CH from using it.

**Comment by likebreath** [comment]
Of course. I took a quick glance of the PR yesterday and it looks good to me. I will try it with CH and provide feedback.

**Comment by sboeuf** [comment]
Thanks Bo!

**Comment by sboeuf** [comment]
@likebreath please provide your feedback on the PR directly, and report on this issue as well what needs to be done from our perspective.

**Comment by likebreath** [comment]
@sboeuf @rbradford A working draft is up [here](https://github.com/likebreath/cloud-hypervisor/pull/14). Only two minor issues left:  1) fix cargo fuzz build failure; 2) accommodate with the fact the `apply_filter` API now returns Error on empty filter. I will address them when the seccompiler PR is landed.

Overall, I found the new interfaces are cleaner, while it did require quite more changes than I originally expected. No functional changes needed in CH code base, and all changes are needed to migrate to the new APIs and types.  Any comments or questions, please let me know. Thanks.

/cc @alindima

**Comment by sboeuf** [comment]
That's great! Thanks for confirming the new version of the `seccompiler` crate will work just fine with Cloud Hypervisor. Let's now wait for the PR to be merged as part of rust-vmm and then we can use your draft to move Cloud Hypervisor to the upstream version.
