### ISSUE TITLE
Document experiments on live-migration

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#2958]
Experiments to cover:
- [x] Local migration and nested migration on a single machine (as descripted in the [document](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/live_migration.md))
- [x] Cross two Azure VMs with the same configuration (platform/CPU and host OS)
- [x] Cross two Azure VMs with different host kernel version (same platform/CPU), e.g. between `v5.4.0-1055-azure` (Ubuntu 18.04), `v5.8.0-1039-azure` (Ubuntu 20.10), and `v5.11.0-1005-azure` (Ubuntu 21.04)
- [x] Cross two Azure VMs with different platform/CPU, e.g. from `Azure Dv3-series with Skyelake/Ive Bridge CPU` to `Azure Dv4-series VM with CascadeLake CPU`
- [x] Additional notes on the guest workload being tested with live-migration:
    - [x] Linux  guest (with intensive virtio-block workload as mentioned in the document)
    - [x] Windows  guest (as descripted in the [document](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/windows.md))
- [x] Migration with advanced features
    - [x] vhost-user-net (with ovs-dpdk)
    - [x] huge-pages/shared-pages
    - [x] NUMA/memory-zones
    - [x] virtio-mem
- [x] Migration across different Cloud Hypervisor versions (partially done from #3970 and more to add tracked from #3949 )

Additional notes:
1. Migration from older-generation of CPU to newer generation can be intentionally rejected by the CPU feature check, e.g. migration from CascadeLake platforms to Skylake ones will be rejected as destination platform is missing some CPU features (e.g. `clwb`, `avx512_vnni`); 
2. Migration with guest workload running nested VMs was failed with tests on Azure VMs.
3. ~~Migration with guest using "memory-zones" and "memory hotplug" is expected to fail, as it requires snapshot/restore of virtio-mem (https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1595).~~

**Comment by likebreath** [comment]
@rbradford @sboeuf Please take a look and feel free to extend/revise (e.g. the one on vhos-user-net w/ ovs-dpdk).

**Comment by sboeuf** [comment]
The list seems accurate to me :)
