### ISSUE TITLE
Improving debuggability and observability

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#3002]
One use case I have in mind is the Bring-You-Own-Images type of service. In such a service, each vendor brings their verified images on our platform.

Per my understanding this is perhaps different from the original use case Cloud Hypervisor has in mind, in which the images are controlled by the platform and more homogeneous.

For the BYOI use case, we have a desire to improve Cloud Hypervisor's ability to observe and debug those VMs. For the moment I think there are only two ways:

  1. Configure the VM to use the emulated serial port (VirtIO console doesn't cut it for early boot).
  2. Use the built-in counters from Cloud Hypervisor.

I think we can do better here. Two things I can think of:

  1. Provide a simple framebuffer and input support via vfio-user, to provide a basic console for trouble shooting.
  2. Support guest core dump compatible with `crash` utility.

What else can be done?

**Comment by weltling** [comment]
A framebuffer would be great point to break the dependency on serial, IMO that's both thumbs up.

For serial however, the current `--serial tty --console off` is only usable for debugging in conjunction with `socat`. That's not very sustainable, unfortunately. Expanding on the serial implementation would be great to improve the debug experience, points below: 

- Serial through TCP client/server infrastructure.
- Serial <> PTY.
- Serial <> PIPE, maybe?
- Serial <> `/dev/ttyS*` on host pass through?

The first two is what I'd see as a great improvement to make debugging on serial self enclosed. I had no pretense yet to use a serial console so couldn't tell it's indeed usable, but i guess having the cmdline configured correctly it should be possible to use an interactive serial console, too.


Perhaps it would also make sense to have a dedicated specification for the BYOI scenario. Or maybe there could be an image specification in general, so then requirements would be transparent and having automated tooling to verify an image would become simpler to implement. For example, core dump support might be done by some convention, so then post-factual teh core file could be retrieved from the image after the VM shutdown.

Thanks

**Comment by weltling** [comment]
One note on the network availability also, as that's where i'm not sure. Another good debugging option could be to ensure the very early availability of the network device, as some debugging could be network based. However, serial <> tcp would cover that, even though serial is slower so have bottlenecks in some case.

Thanks

**Comment by rbradford** [comment]
@weltling We have support for connecting a serial to the PTY. 

In terms of kernel debugging: gdb stub support is a possibility https://www.kernel.org/doc/html/v4.11/dev-tools/gdb-kernel-debugging.html

**Comment by liuw** [comment]
@weltling I think it would be better to keep Cloud Hypervisor small. It shouldn't burden itself with the the complexity of maintaining a TCP connection. I think using the newly added (not actually that new, but added after we debugged Windows) PTY support and `socat` should do all the things you want.

Here is a command I use to fish out the PTS device.

```
ch-remote --api-socket $SOCK info | jq -r '.config.serial.file'
```

Nowadays I use minicom or picocom to connect to the PTY port.

```
minicom -D $(ch-remote --api-socket $SOCK info | jq -r '.config.serial.file')
```

It is much better than using TTY because there is no escape from the guest console on TTY. You can easily replace minicom / picocom with anything you like, including but not limited to `socat`.

**Comment by weltling** [comment]
@rbradford @liuw thanks for pointing out regarding the PTY availability, seems i've overseen this addition. I earlier came up with using a command like this:

```bash
#!/bin/sh
# File ch.kgdb
cloud-hypervisor \
--cpus boot=4 \
--memory size=4G \
--kernel ./vmlinux \
--cmdline "console=tty0 kgdboc=ttyS0,115200n8 nokaslr kgdbwait root=/dev/vda1 rw" \
--disk path=./focal-server-cloudimg-amd64-custom-20210106-1.raw  \
--serial tty \
--console off
```

And then capturing and converting with like:

`socat SYSTEM:"./ch.kgdb",openpty,rawer PTY,link=./gdb_pty,rawer`

That PTY was worky, but the whole wrapping process seems wobbly. I'm gonna try out the PTY mechanism then, too. And especially with an interactive serial console, like adding once more `console=ttyS0,115200n8` + minicom, would make it almost as easy and usual as a Raspberry Pi :)

Thanks

**Comment by weltling** [comment]
@liuw For TCP - it wouldn't seem that it would increase the binary size a lot. The dependencies for the network layer are already linked due the API socket. So far the experience with `socat` and the wrapping mechanism isn't something i'd call 100% stable. 

Perhaps one should see a debug over network in general - either TCP client/server or at least debug through network device. Linux supports kgdboe (even if not the latest kernel), Windows supports network debug, too. Serial over TCP is however platform agnostic, which is another plus in the story.

Sure a debug over network is a more rare scenario, but it came up several times. For example there was already the case with the CPU addressable space that only came up on a nested Azure VM. If a VM to be debugged is remote and the bug is not reproducible locally, it'll most likely cause many levels of indirection which are probably much more of burden. For Windows serial over TCP and socat seems the only way, whereby the new info about the exposed PTY might help but needs some experiment.

Thanks

**Comment by weltling** [comment]
Reporting on the PTY part. When `kgdbwait` is involved, I'm able to use `--serial pty` and lookup the PTY by using the API call as suggested. That PTY is usable with GDB directly, no socat is needed.

Thanks

**Comment by rbradford** [comment]
Is there anything actionable still in this issue? It looks like the PTY support solves @weltling's issue?

**Comment by retrage** [comment]
I'm working on GDB support on CH for the pre-boot environment, especially debugging Rust Hypervisor Firmware. The fundamental functionalities work, but the code quality is not ready for being reviewed. I'm afraid that my design is not suitable for upstreaming. Could you check the design if I submit a draft PR?

Working Branch: https://github.com/retrage/cloud-hypervisor/tree/gdbstub-support

**Comment by sboeuf** [comment]
Sounds awesome @retrage. Please submit the PR, we'll review there and give you some guidance!
