### ISSUE TITLE
Serial port buffering stalls guest boot

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#3004]
**Describe the bug**

When the buffer for serial port is full guest is stalled. Guest will only continue if I connect 

**To Reproduce**

Run Cloud Hypervisor with `--serial pty --console tty` and also configure Linux kernel with `console=ttyS0 console=hvc0`.

VirtIO console output runs for a while then stops. Output continues once picocom connects to the PTS used by the serial port (which drains its buffer).

**Version**

cloud-hypervisor v17.0-176-g76003110

Build from source with default configuration.

**VM configuration**

 ./target/debug/cloud-hypervisor --kernel /root/data/ch-ref-vmlinux.bin --log-file ../x.log --seccomp false --disk path=/root/demo/g1-disks/focal-server-cloudimg-amd64.raw path=/root/demo/g1-disks/data.raw --cmdline "root=/dev/vda1 rw apic=verbose console=hvc0 console=ttyS0" --cpus boot=1 --memory size=2048M --serial pty --console tty -vvvvv --api-socket /tmp/ch.sock

**Comment by rbradford** [comment]
This is due to the Linux kernel behaviour. I think this could be handled for the PTY case by modifying the PTY handling code to:

a.) Make the fd non-blocking
b.) Upon write add the data to write (i.e. output) to a vector and then try and write the whole vector. If it comes back -EWOULDBLOCK then do nothing otherwise clear the buffered vector.

This would mean the output data would be buffered and it would be available upon connect. However since it's only triggered on write then it could be that it is never written so it would need to be combined with an epoll to find when the fd is writable. I think this could be handled with the vmm thread if the abstractions allow it.

**Comment by rbradford** [comment]
@bryteise Any thoughts on this?

**Comment by liuw** [comment]
> This is due to the Linux kernel behaviour. I think this could be handled for the PTY case by modifying the PTY handling code to:
> 
> a.) Make the fd non-blocking
> b.) Upon write add the data to write (i.e. output) to a vector and then try and write the whole vector. If it comes back -EWOULDBLOCK then do nothing otherwise clear the buffered vector.
> 

For b) I want to add that the buffer size should not be unbounded. I think a simple circular buffer is what we need here. The circular buffer can be implemented with vector.

**Comment by liuw** [comment]
Also, is this really only about PTY handling? If TTY (stdout) is redirected, it can potentially be blocked too.

**Comment by rbradford** [comment]
> Also, is this really only about PTY handling? If TTY (stdout) is redirected, it can potentially be blocked too.

Yeh, I think that's a possibility so any solution should handle both.

**Comment by rbradford** [comment]
If we're not worried about losing output and more worried about the boot then the simplest solution is to skip the buffering (which adds complexity) and just make the fd writes non-blocking and ignore `-EWOULDBLOCK`. Maybe that could be our first solution.

**Comment by liuw** [comment]
> If we're not worried about losing output and more worried about the boot then the simplest solution is to skip the buffering (which adds complexity) and just make the fd writes non-blocking and ignore `-EWOULDBLOCK`. Maybe that could be our first solution.

This would be fine as a first step. I would like to have an option to switch it back to blocking though. When the console is used as a transport for data intended for machine consumption, we don't want its data to get lost. Examples are debuggers connected via the emulated serial ports or guest agents connected via virtio consoles.

**Comment by bryteise** [comment]
Having an option for blocking would be nice. I think in some cases loggers get attached to serial ports for these cloud instances and being able to ensure all the content is available is important. Just want to be sure it can be configured per port.
