### ISSUE TITLE
Keyboard input pushed to wrong place

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#3005]
**Describe the bug**

My key strokes from TTY are for VirtIO console but they end up being pushed to serial console.

I can see this when I type in one Window but characters start appearing in the other.

**To Reproduce**

Run Cloud Hypervisor with `--serial pty --console tty` and also configure Linux kernel with `console=ttyS0 console=hvc0`. Make sure Linux spawns a login prompt for each of them.

Open another terminal window, fish out the PTY for serial with `ch-remote` and use picocom / minicom to connect to it.

Type in the original terminal which shows the VirtIO console, then look for characters shown in the other terminal.

**Version**

cloud-hypervisor v17.0-176-g76003110

Build from source with default configuration.

**VM configuration**

./target/debug/cloud-hypervisor --kernel /root/data/ch-ref-vmlinux.bin --log-file ../x.log --seccomp false --disk path=/root/demo/g1-disks/focal-server-cloudimg-amd64.raw path=/root/demo/g1-disks/data.raw --cmdline "root=/dev/vda1 rw apic=verbose console=hvc0 console=ttyS0" --cpus boot=1 --memory size=2048M --serial pty --console tty -vvvvv --api-socket /tmp/ch.sock

**Comment by rbradford** [comment]
@liuw Thanks for the excellent bug report. I was able to reproduce and identify the cause and fix the issue. :rocket: Please see #3011 for details.
