### ISSUE TITLE
Adding RESTful endpoints for serial and console

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#3006]
I have the need to figure out how serial and console are configured for a guest.

Currently I just used the `vm.info` endpoint and then parse the JSON data.

I'm wondering if people would be interested in adding two more endpoints, one for serial, the other for console.

**Comment by liuw** [comment]
For reference the command line I use to extract information is like

```
ch-remote --api-socket socket info | jq '.config.serial.file'
```

**Comment by rbradford** [comment]
We talked about this during the development of the PTY support (as that was the first time that it was needed) and came to the conclusion that patching the config was the best plan as then it was also useful for snapshot/restore.

**Comment by rbradford** [comment]
I think a prettier output from the ch-remove info command would probably be useful :-)

**Comment by liuw** [comment]
Thanks for you reply. `jq` does the job just fine, so our energy is better spent elsewhere on more important things.
