### ISSUE TITLE
Serial buffer not flushed until write

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3058]
Following on from #3057 when connecting to the PTY the serial buffer should be immediately flushed.

**Comment by rbradford** [comment]
Depends on #3059 otherwise it will be a bit messy.

**Comment by bryteise** [comment]
@rbradford I think I'm a little confused as to what behavior this requires. I thought this was to flush when another process opens the pty but the more I think about that the less that makes sense to me. Detecting another process has opened the PTY is a bit tricky as epoll won't see an event for open and I can only think of painful seeming ways to handle that.

I'm probably being dumb and missing something obvious though.

**Comment by rbradford** [comment]
If and only if serial buffer has something in -> add an epoll even for the fd to be writable. Upon said event: flush serial buffer. Remove after flushing the serial buffer if the serial buffer is now empty. You don't want the writable epoll event around for any longer than strictly necessary - using a one shot might be easier (you'll need to add it again after the flush if the buffer wasn't fully emptied.)

**Comment by rbradford** [comment]
This means you'll need to move the serial buffer into `SerialManager`.
