### ISSUE TITLE
Partially pass through iommu group is allowed / Cannot pass through multiple devices in one iommu group

### ISSUE THREAD

**Issue by Kethen** [cloud-hypervisor/cloud-hypervisor#3078]
**Describe the bug**
1. passing a single device through in a multi device iommu group to boot a vm is allowed, this is likely unsafe to host?
2. passing through a graphic card and it's audio card will result in cloud-hypervisor attempting to open the same vfio device twice through rust-vmm/vfio-ioctls

**To Reproduce**
```
--device path=/sys/bus/pci/devices/0000:01:00.0/
# will boot with a partial iommu group
--device path=/sys/bus/pci/devices/0000:01:00.0/ path=/sys/bus/pci/devices/0000:01:00.1/
# will prompt an error as the second attempt of accessing the one vfio device(group) fails
```

The current code base simply does not attempt to take care of iommu groups, it'll only try to dma each pci device's iommu group
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/4d52a84ef7ce751f583053b259df6077bf02394f/vmm/src/device_manager.rs#L2946

**Version**
cloud-hypervisor v17.0-dirty

built from source after changing a few cargo files pointing to rust-vmm, with their recent branch name change

**Comment by rbradford** [comment]
Thank you @Kethen for opening an issue. @sboeuf our resident VFIO expert will be back in a few days to look at this issue you raised.

**Comment by sboeuf** [comment]
@Kethen I confirm this is an issue I could reproduce on my side. I'll investigate how I can properly fix it.

**Comment by sboeuf** [comment]
@Kethen could you please check if #3123 is fixing the issue you were seeing. It fixes it for me, but I'd like your confirmation.
