### ISSUE TITLE
Aarch64 release code doesn't work

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3099]
The second workflow for the aarch64 release creates a 2nd release from the same tag so that the artifacts end up being split. I think it needs to be merged into the one workflow with just one release created from the tag.

**Comment by rbradford** [comment]
@MrXinWang @michael2012z FYI.

**Comment by MrXinWang** [comment]
Thanks @rbradford. So far looks good.

(My original thought was to split the AArch64 out so that if the Arm64 has some build issue in github action, at least we would not block x86, but for now I think merging them to a single workflow is fine. Thanks again!)
