### ISSUE TITLE
Blocking API calls

### ISSUE THREAD

**Issue by weltling** [cloud-hypervisor/cloud-hypervisor#3146]
Currently API calls seem to be always non blocking. However, there are several cases where waiting for an API in a blocking manner or at least having a possibility to poll to receive a result would make sense. In most case it would be about an operation with an open ended timeline that might fail or succeed.

As an example - `snapshot`, `resume`, `resize` would be a candidate to use a blocking API call and retrieve the result. While in some cases errors are reported by `ch-remote`, success or the end of an operation are not. Looking at the integration tests, they often rely on hardcoded timeouts. It would be great to hear opinions on this topic.

Thanks

**Comment by sboeuf** [comment]
I'm not opposed to introduce some logic to make a few API calls blocking, but we need an exhaustive list of commands for which this would make sense. For instance, even if you're blocking on the `resize` call, you have no guarantee how long it will take in the guest kernel to expose a new CPU, even when everything has been properly done on the host side.
I think the most challenging part for some commands will be about knowing when they're properly completed.

**Comment by liuw** [comment]
Just to toss some ideas around:

1. these blocking calls should also come with a timeout (however large it is) and should not blocked indefinitely.
2. Avoid blocking things that require guest cooperation all together.
3. Instead of going the blocking API route, CH can provide APIs that return the status of the operation. API users can poll its completion status and decide whether to wait or move on.

**Comment by weltling** [comment]
Thanks for checking. Potentially any command could use such a mechanism. Perhaps these for the start:

- snapshot
- resume
- shutdown

Potentially it's any operation where in the integration tests `thread::sleep()` call is deliberately used. On my side, the question just came up while investigating some issues with snapshot/restore where 

Saying there are challenges on knowing the proper completion is a good point, as it depends on the guest handling like hardware addition/removal, on the guest OS, etc. Many cases could still be implemented, given the mechanism would exist. But yeah, looking at the full subcommand list from `ch-remote`, many cases would need to be handled a guest specific way. 

Perhaps if not blocking, another option could be to track the operation status or similar. This would make `ch-remote` a bit more predictable and allow better event driven scenario. Also thinking about dozens/hundreds of VMs would need to be served on one host, this might be helpful. Maybe there is a better idea on the approach, that why i thought filing an issue would be useful to ask for opinions. 

Thanks

**Comment by weltling** [comment]
For 3. - that would imply some queue would be used to store the incomplete operations? Say one could issue multiple operations non blocking, then poll on them in parallel.

Thanks

**Comment by rbradford** [comment]
The reason those API calls block is due to a fundamental design choice. The low privilege API thread takes the request (and this applies to all requests) and sends a message to the high priviliege vmm thread to get an answer. The vmm thread acts as a serialiser in this case. 

If you don't want your client code to block on long running API calls then you should start those in a thread. But bear in mind that you won't be able to make any other API requests as the API thread will be busy servicing the long running request and even if you could the vmm thread as it would still be busy on the long running task.

I don't think the added complexity is worth it since the vmm thread is still the fundamental serialiser (and this is intentional for safety, security and to ensure that state is consistent.)

The sleeps in the integration tests are there to wait for the guest code in the VM to do it's thing (e.g. the Linux kernel brings CPUs online asynchronously) not for any API reasons.

**Comment by rbradford** [comment]
(Also I like that the HTTP requests block since it makes client implementation much easier.)

**Comment by weltling** [comment]
Oh, so what i read is that API socket calls would still be blocking? This means what i initially took as a non blocking call is the asynchronicity of the further handling in the guest, as mentioned here:

> The sleeps in the integration tests are there to wait for the guest code in the VM to do it's thing (e.g. the Linux kernel brings CPUs online asynchronously) not for any API reasons.

Would it then imply anytime `ch-remote` issued a call, the requested job in `cloud-hypervisor` is fully completed and the remaining operation is up to the guest to complete? 

Perhaps another approach could be to have a kind of daemon running within the guest to communicate such things with the host? For example, [waagent](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/agent-linux) exists on Azure, but most likely similar things exist for any other hypervisor solutions.

Thanks

**Comment by weltling** [comment]
> Would it then imply anytime ch-remote issued a call, the requested job in cloud-hypervisor is fully completed and the remaining operation is up to the guest to complete?

After reading twice, i think this is answered by:
> But bear in mind that you won't be able to make any other API requests as the API thread will be busy servicing the long running request

So probably my initial question clarified at this point. Perhaps we could still exchange on possible ways to retrieve the information from guest on real completion, if that makes sense.

Thanks

**Comment by rbradford** [comment]
Oh, sorry I realised i'd completely misinterpreted your issue. You want the commands to block until the the actions are complete. Some of the commands you mentioned already do that:

e.g. shutdown goes to `Vm::vm_shutdown()` which does a join on the threads that the VM has spawned so waits for those to exit. With a few extra logs you can clearly see that the API response is only returned once everything has shutdown
```
cloud-hypervisor: 4.047469952s: <vmm> INFO:vmm/src/lib.rs:1302 -- API request event: VmShutdown(Sender { .. })
cloud-hypervisor: 4.047679181s: <vmm> INFO:virtio-devices/src/device.rs:356 -- Resuming virtio-block
cloud-hypervisor: 4.047744939s: <vmm> INFO:virtio-devices/src/device.rs:356 -- Resuming virtio-rng
cloud-hypervisor: 4.047824492s: <vmm> INFO:virtio-devices/src/device.rs:356 -- Resuming virtio-console
cloud-hypervisor: 4.048071322s: <vcpu0> INFO:vmm/src/cpu.rs:827 -- vCPU exited
cloud-hypervisor: 4.049574271s: <_disk0_q0> INFO:virtio-devices/src/epoll_helper.rs:134 -- KILL_EVENT received, stopping epoll loop
cloud-hypervisor: 4.049652751s: <_rng> INFO:virtio-devices/src/epoll_helper.rs:134 -- KILL_EVENT received, stopping epoll loop
cloud-hypervisor: 4.049890159s: <_console> INFO:virtio-devices/src/epoll_helper.rs:134 -- KILL_EVENT received, stopping epoll loop
cloud-hypervisor: 4.050253406s: <http-server> INFO:vmm/src/api/mod.rs:458 -- Returning from vm_shutdown
```

In the case of resize we have to wait for the userspace in the guest to react to online the CPUs and then we get a notification via an ACPI function that they are in use. This is something that has to be done manually.

Again for the snapshot case it only returns once all the snapshot is written.

**Comment by rbradford** [comment]
> Would it then imply anytime `ch-remote` issued a call, the requested job in `cloud-hypervisor` is fully completed and the remaining operation is up to the guest to complete?

Yes.

**Comment by weltling** [comment]
ACK, yeah, so the HTTP request itself is blocking, but that's irrelevant because the response won't always indicate the full completion. Operations like `snapshot` don't depend on the guest, so the response indicates the real completion.

In other cases where the guest is in the game, there might be still some job not fully completed. Like in the case with hotplug, there would be currently no reliable event. Just to depict what is clarified till now on examples.

Resize call:
* `ch-remote` call to hotplug CPU (HTTP request blocking)
  * `cloud-hypervisor` adds CPU (mutex protected operation)
  * `cloud-hypervisor` sends response to `ch-remote`
* `ch-remote` returns, guest status unknown on the `ch-remote` side

Shutdown call:
* `ch-remote` call to shutdown (HTTP request blocking)
  * `cloud-hypervisor` sends shutdown request and waits for threads to join (mutex protected operation)
  * `cloud-hypervisor` sends response to `ch-remote`
* `ch-remote` returns, guest status complete on the `ch-remote` side

For the snapshot/restore call seems then, it's same as shutdown.

So for the calls like resize, where guest is involved, having a way to have to poll like:
* `ch-remote` call to hotplug CPU (HTTP request blocking)
  * `cloud-hypervisor` adds CPU (mutex protected operation)
  * `cloud-hypervisor` sends response with status `pending` to `ch-remote`
* `ch-remote` returns, guest status unknown on the `ch-remote` side
* `ch-remote` starts polling
  * `ch-remote` calls to retrieve the operation status
    * `cloud-hypervisor` issues ACPI call (HTTP request blocking)
    * `cloud-hypervisor` sends response with status `success` or `failure` to `ch-remote` 
* `ch-remote` returns, guest status complete on the `ch-remote` side

Or otherwise, for example if a daemon is running within the guest, the status could be read from there. Again, i just came to this from some snapshot/restore work while seeing hardcoded timeouts and realizing we use them extensively in the integration tests. So this looked like an area we could discuss ways to improve for a better event driven design.
 
thanks

**Comment by rbradford** [comment]
Is there anything actionable in this issue?

**Comment by weltling** [comment]
Thanks for the reminder, Robert. From what has been said on the thread, the there might be the following:

- Some API calls might require a guest daemon (for example hotplug) to deliver the real data from the guest.
- Some API calls might require either a complex multi request approach or a kind of a queue so then the real status can be retrieved later or polled on (for example restore).

At this point, one might probably document, that some operation might only deliver a one way status but not the real operation result. An action in terms of coding would probably need some more clarification and planning, but AFAIR things like guest daemon would be rather not happening soon, if at all. So probably could only add some doc for now?

Thanks.
