### ISSUE TITLE
Virtual address-backed guest machines on Linux MSHV

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/cloud-hypervisor#3171]
After this support we can enable all the Dax related integration test cases and try to fix at least we have any issue.

**Comment by rbradford** [comment]
What do you mean by "Virtual address-backed guest machines"? This phrase makes no sense to me.

**Comment by NunoDasNeves** [comment]
Our driver's current memory mapping implementation populates and pins all the guest memory.
Pinning the pages is not possible e.g. if the memory is backed by a file.
The DAX tests do (something like?) this, which throws an error when we try to pin the pages.

By "Virtual address-backed guest machines", we mean hooking our driver into the kernel memory management system so guest pages don't need to be pinned, and can be backed by files, swapped out, migrated etc.

**Comment by sboeuf** [comment]
Ok so this is not really a CH issue. IIUC, you're waiting for your driver to be improved before you can enable the DAX related tests.

**Comment by NunoDasNeves** [comment]
Yes, exactly

**Comment by sboeuf** [comment]
What's the status on this?

**Comment by liuw** [comment]
We have a developer looking into it but it is the the highest priority for us right now.

**Comment by liuw** [comment]
This is still WIP. I don't expect we need to track it here. I expect CH to just work after we implement the required machinery in the kernel.
