### ISSUE TITLE
Guest agent support

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#3196]
QEMU has a guest agent that runs inside the guest to do various things.

Is there appetite for introducing a guest agent to Cloud Hypervisor?

Some of things that can be useful are:

1. Ask guest to shutdown properly.
2. Return guest's IP address.
3. Freeze guest in preparation for host side backup.
4. Execute commands.

**Comment by rbradford** [comment]
@liuw We already handle "1." with the ACPI power button which causes systemd to shutdown.

**Comment by liuw** [comment]
> @liuw We already handle "1." with the ACPI power button which causes systemd to shutdown.

I know. But I also hear some people complain that it depends on guest's configuration -- some guests can choose to ignore that event -- hence it is not reliable.

**Comment by rbradford** [comment]
Given that nobody has proposed an implementation for a guest agent I guess there is no demand as such; further such an agent seems very specific to how Cloud Hypervisor is deployed rather than something that makes sense for a generic solution.

**Comment by linuxjefeprive** [comment]
I would say there is demand, atleast more than enough to implement this. For example; for kubevirt integration. But also proper signaling to shutdown is simply something that is needed in production.  Clipboards? Remoting? switching in/out drivers for example? It wouldn't hurt to at the very least implement the bare minimum, then at the very least we have an point of presence so to speak.

**Comment by maxpain** [comment]
We also need this
