### ISSUE TITLE
Libvirt migration support

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#3206]
I'm looking into what is needed to implement migration support for Cloud Hypervisor in libvirt.

For an overview of libvirt's internal protocol see https://libvirt.org/kbase/migrationinternals.html#version-3-protocol-sequence.

One thing that stands out when I read libvirt's code is that it has the ability to manipulate the guest's config (in its own XML format). The destination can create a guest based on the potentially changed config, and then make that guest accept migration data stream.

Cloud Hypervisor at the moment embeds its guest config in the migration stream. If libvirt's behaviour is desired, CH needs to break its migration support to more fine-grained steps.

CC @bryteise @likebreath @praveen-pk

**Comment by likebreath** [comment]
@liuw Thanks for starting this issue. Can you please elaborate more on what are the benefits of following libvirt's behavior, e.g. sending the updated config (instead of initial config) to the destination VM at the beginning of migration?

Also, based on libvirt's protocol, it looks like we don't have gaps from Cloud Hypervisor side to support libvirt migration if we decide to keep our current behavior of sending initial config, right?

/cc @rbradford @sboeuf

**Comment by liuw** [comment]
> @liuw Thanks for starting this issue. Can you please elaborate more on what are the benefits of following libvirt's behavior, e.g. sending the updated config (instead of initial config) to the destination VM at the beginning of migration?
> 

It is difficult to tell whether people really do that or how they in practice. If anything they may choose to rename the guest somehow, but that's not going to affect the guest. They may also choose to tune some of the settings that are visible to the backend but requires VMM coordination. I can imagine someone may want to redirect the serial port elsewhere.

One important note is that libvirt does not modify configuration files by default. Administrators need to be very explicit about that.

> Also, based on libvirt's protocol, it looks like we don't have gaps from Cloud Hypervisor side to support libvirt migration if we decide to keep our current behavior of sending initial config, right?
> 
> /cc @rbradford @sboeuf

I think what is now in Cloud Hypervisor should be enough for implementing an initial version. Anything more complicated requires a bit more thinking.

**Comment by praveen-pk** [comment]
Libvirt usually setups up the network on the destination host before starting guest with cloud-hypervisor. If cloud-hypervisor were to start the guest, based on the configuration it received from source cloud-hypervisor, we could run into some race conditions.

For example, cloud-hypervisor could start the guest assuming a tap device is already setup by libvirt, while libvirt is still setting it up on the host.

May be add a flag to cloud-hypervisor to not send guest configuration if selected?

**Comment by rbradford** [comment]
Definitely never a TCP stream. Doing it over an existing FD might be tricky for the receiving side.

**Comment by rbradford** [comment]
I think you could prototype having the code pass the fds across for send/receive migration.

**Comment by sboeuf** [comment]
>Should I go ahead and track an issue to implement "TCP Stream" support in cloud-hypervisor?

So basically we're talking about extending the current UNIX socket support into a TCP socket support for live migrating across machines without the need for socat, right?

**Comment by praveen-pk** [comment]
> So basically we're talking about extending the current UNIX socket support into a TCP socket support for live migrating across machines without the need for socat, right?
Yes, Exactly

**Comment by rbradford** [comment]
I wouldn't support implementing `TcpStream` handling in Cloud Hypervisor - the semantics of the way it works with sockets is quite different to the UNIX socket and the current design was chosen as it allows the maximum flexibility of the management layer to implement TLS, authentication and authorization on top.

To clarify: the way migration is designed to work was that the management layer, libvirt in this case, would proxy the transport into the UNIX socket probably from an TLS and authenticated stream into the UNIX socket. The use of `socat` in the documentation is there as a stand in for that management layer and not what should be used in production.

**Comment by rbradford** [comment]
We intentionally don't want to implement TLS and authentication and TCP socket management in Cloud Hypervisor as that is huge complexity that is a burden for anyone that doesn't need to use live migration.

**Comment by praveen-pk** [comment]
> To clarify: the way migration is designed to work was that the management layer, libvirt in this case, would proxy the transport into the UNIX socket probably from an TLS and authenticated stream into the UNIX socket. The use of `socat` in the documentation is there as a stand in for that management layer and not what should be used in production.

Thanks for the prompt response. I understand adding support for TCP Stream could add to the maintenance burden of the project.
We can re-visit this if the proposed vm-live-migration (https://github.com/rust-vmm/community/issues/67) crate gets developed under rust-vmm project. This design proposes TCP also as a supported transport.

**Comment by cicdteam** [comment]
> We intentionally don't want to implement TLS and authentication and TCP socket management in Cloud Hypervisor as that is huge complexity that is a burden for anyone that doesn't need to use live migration.

UnixStream + socat solution as well not secure (yes, I know it's just an example), so why do not add insecure option for TcpStream ? It useful if network alrerady secured  (like private subnet in VPC)

**Comment by rbradford** [comment]
> > We intentionally don't want to implement TLS and authentication and TCP socket management in Cloud Hypervisor as that is huge complexity that is a burden for anyone that doesn't need to use live migration.
> 
> UnixStream + socat solution as well not secure (yes, I know it's just an example), so why do not add insecure option for TcpStream ? It useful if network alrerady secured (like private subnet in VPC)

socat is there for testing and demonstration. In fact you can use socat with TLS if you want by using the `OPENSSL` and `OPENSSL-LISTEN` targets. The big differentiator for Cloud Hypervisor is that it is trying to be designed with security in mind. I don't think that adding an unencrypted TCP stream is good for security. A proposal to add a TLS solution might persuade me more but there is a lot of complexity around that of CAs and extra dependencies. It still also doesn't solve the authentication problem but client certificates could potentially do that.
