### ISSUE TITLE
VmBoot(KernelMissingPvhHeader) error with custom kernel

### ISSUE THREAD

**Issue by henryksloan** [cloud-hypervisor/cloud-hypervisor#3222]
**Describe the bug**
Compiling and running the forked Linux kernel (https://github.com/cloud-hypervisor/linux.git) does not seem to work as described in the README. It prints only "Error booting VM: VmBoot(KernelMissingPvhHeader)", indicating that either the instructions are outdated, or the `PvhEntryPresent` detection is not compatible with the described process.

**To Reproduce**
Steps to reproduce the behaviour:
Follow the steps described in the [custom kernel](https://github.com/cloud-hypervisor/cloud-hypervisor#custom-kernel-and-disk-image) README section.

**Version**
`git rev-parse HEAD` => `d0bafc72f8c5491e434b262b81d00fa46a6530fb`

Output of `cloud-hypervisor --version`:
`cloud-hypervisor v18.0-136-gd0bafc72`

Did you build from source, if so build command line (e.g. features):
`cargo build --release`

**VM configuration**

What command line did you run (or JSON config data):
As described in the README.

Guest OS version details:
`focal-server-cloudimg-amd64`, as described in the README.

Host OS version details:
Arch Linux, kernel 5.14.8-arch1-1

**Logs**

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:
```
cloud-hypervisor: 2.307513ms: <vmm> INFO:vmm/src/lib.rs:1297 -- API request event: VmCreate(Mutex { data: VmConfig { cpus: CpusConfig { boot_vcpus: 4, max_vcpus: 4, topology: None, kvm_hyperv: false, max_phys_bits: 46 }, memory: MemoryConfig { size: 1073741824, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None }, kernel: Some(KernelConfig { path: "/home/henry/dev/kernel/linux-cloud-hypervisor/arch/x86/boot/compressed/vmlinux.bin" }), initramfs: None, cmdline: CmdlineConfig { args: "console=hvc0 root=/dev/vda1 rw" }, disks: Some([DiskConfig { path: Some("cloud-hypervisor/focal-server-cloudimg-amd64.raw"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: None, disable_io_uring: false }]), net: Some([NetConfig { tap: None, ip: 192.168.249.1, mask: 255.255.255.0, mac: MacAddr { bytes: [46, 4, 205, 105, 21, 245] }, host_mac: None, iommu: false, num_queues: 2, queue_size: 256, vhost_user: false, vhost_socket: None, vhost_mode: Client, id: None, fds: None, rate_limiter_config: None }]), rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Null, iommu: false }, console: ConsoleConfig { file: None, mode: Tty, iommu: false }, devices: None, user_devices: None, vsock: None, iommu: false, sgx_epc: None, numa: None, watchdog: false }, poisoned: false, .. }, Sender { .. })
cloud-hypervisor: 3.580784ms: <vmm> INFO:vmm/src/lib.rs:1297 -- API request event: VmBoot(Sender { .. })
cloud-hypervisor: 6.214521ms: <vmm> INFO:vmm/src/memory_manager.rs:1458 -- Created userspace mapping: 0 -> 7f1684000000 40000000
cloud-hypervisor: 6.235798ms: <vmm> INFO:vmm/src/vm.rs:528 -- Booting VM from config: Mutex { data: VmConfig { cpus: CpusConfig { boot_vcpus: 4, max_vcpus: 4, topology: None, kvm_hyperv: false, max_phys_bits: 46 }, memory: MemoryConfig { size: 1073741824, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None }, kernel: Some(KernelConfig { path: "/home/henry/dev/kernel/linux-cloud-hypervisor/arch/x86/boot/compressed/vmlinux.bin" }), initramfs: None, cmdline: CmdlineConfig { args: "console=hvc0 root=/dev/vda1 rw" }, disks: Some([DiskConfig { path: Some("cloud-hypervisor/focal-server-cloudimg-amd64.raw"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: None, disable_io_uring: false }]), net: Some([NetConfig { tap: None, ip: 192.168.249.1, mask: 255.255.255.0, mac: MacAddr { bytes: [46, 4, 205, 105, 21, 245] }, host_mac: None, iommu: false, num_queues: 2, queue_size: 256, vhost_user: false, vhost_socket: None, vhost_mode: Client, id: None, fds: None, rate_limiter_config: None }]), rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Null, iommu: false }, console: ConsoleConfig { file: None, mode: Tty, iommu: false }, devices: None, user_devices: None, vsock: None, iommu: false, sgx_epc: None, numa: None, watchdog: false }, poisoned: false, .. }
cloud-hypervisor: 6.76902ms: <vmm> INFO:vmm/src/pci_segment.rs:84 -- Adding PCI segment: id=0, PCI MMIO config address: 0xe8000000
cloud-hypervisor: 7.074275ms: <vmm> INFO:vmm/src/device_manager.rs:1830 -- Creating virtio-block device: DiskConfig { path: Some("cloud-hypervisor/focal-server-cloudimg-amd64.raw"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: Some("_disk0"), disable_io_uring: false }
cloud-hypervisor: 26.756594ms: <vmm> INFO:vmm/src/device_manager.rs:1911 -- Using asynchronous RAW disk file (io_uring)
cloud-hypervisor: 26.836899ms: <vmm> INFO:vmm/src/device_manager.rs:1998 -- Creating virtio-net device: NetConfig { tap: None, ip: 192.168.249.1, mask: 255.255.255.0, mac: MacAddr { bytes: [46, 4, 205, 105, 21, 245] }, host_mac: None, iommu: false, num_queues: 2, queue_size: 256, vhost_user: false, vhost_socket: None, vhost_mode: Client, id: Some("_net1"), fds: None, rate_limiter_config: None }
cloud-hypervisor: 27.70843ms: <vmm> INFO:vmm/src/device_manager.rs:2142 -- Creating virtio-rng device: RngConfig { src: "/dev/urandom", iommu: false }
cloud-hypervisor: 61.070315ms: <vmm> INFO:vmm/src/vm.rs:1898 -- Booting VM
cloud-hypervisor: 61.1539ms: <vmm> INFO:vmm/src/vm.rs:967 -- Loading kernel
Error booting VM: VmBoot(KernelMissingPvhHeader)
```

Linux kernel output:
Seemingly nothing relevant from `dmesg`; I assume KVM isn't invoked until after the kernel file is validated.

**Comment by rbradford** [comment]
Can you double check that you copied the config file from: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/resources/linux-config-x86_64 in as .config? That adds the `CONFIG_PVH=y`

**Comment by henryksloan** [comment]
I did copy that config, and the `.config` file in the kernel directory does have `CONFIG_PVH=y`

**Comment by sboeuf** [comment]
Are you using the `vmlinux` file that gets created at the root of the kernel source directory?
And are you correctly using `--kernel /path/to/your/vmlinux`?

**Comment by henryksloan** [comment]
@thillux Ah, thanks for clarifying, I realized I might have done that incorrectly. However, after running `make clean` and then the exact command you included in your comment, I am getting the same results from both `readelf` and the hypervisor.

**Comment by henryksloan** [comment]
I was able to build the kernel in a Xubuntu virtual machine with the README instructions, and it boots just fine. I'd be happy to provide further info if you all are interested in why it behaves differently on my Arch laptop, otherwise feel free to close. Thanks for the help!

**Comment by liuw** [comment]
@henryksloan did you make any change to Arch's toolchain?

**Comment by liuw** [comment]
Well, I don't think there is anything wrong with Cloud Hypervisor's build instructions. You will find the same instructions anywhere you look. The problem is with Arch / Manjaro's toolchain. You need to explicitly disable a feature there.

Use this ` KCFLAGS="-Wa,-mx86-used-note=no" make bzImage -j$(nproc)`.

```
[root@27b05e130918 linux-cloud-hypervisor]# readelf -n vmlinux

Displaying notes found in: .notes
  Owner                Data size        Description
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 245d239993a957e49bae10e55c38442d365c9ee3
  Linux                0x00000004       func
   description data: 00 00 00 00
  Linux                0x00000001       OPEN
   description data: 00
  Xen                  0x00000008       Unknown note type: (0x00000012)
   description data: 50 07 00 01 00 00 00 00
```

The Xen note is what you need to boot a PVH kernel. You can see mine is intact.

**Comment by henryksloan** [comment]
Yup, that works, thanks. thillux thought of that solution above, I guess the environment variable name was just incorrect. Thanks everyone, maybe I'll look into why Arch's toolchain is different in this respect.

**Comment by iggy** [comment]
Fwiw, this happens on latest Alpine as well. Thinking a note in the main readme might be useful.

**Comment by sboeuf** [comment]
> Fwiw, this happens on latest Alpine as well. Thinking a note in the main readme might be useful.

What kind of note? I'll be happy to submit a PR for it, unless you want to take care of it.
