### ISSUE TITLE
VFIO: Missing VFIO_REGION_INFO_CAP_MSIX_MAPPABLE support for mapping BAR containing MSI-X table

### ISSUE THREAD

**Issue by my-glhf** [cloud-hypervisor/cloud-hypervisor#3237]
**Describe the bug**
I want to use VFIO to passthrough the network device created by SRIOV. But the IO performance is not as expected. I execute redis-benchmark for redis-server on host and guest respectively. The results of redis-benchmark are as follows. Except ip, other parameters are the same.

**Redis-server on Host:**
SET: 425713.06 requests per second
GET: 463499.41 requests per second
**Redis-server on Guest:**
SET: 577034.06 requests per second
GET: 720461.06 requests per second

Under normal circumstances, the pass-through device should not lead to such a high performance loss. When I run redis-benchmark for redis-server on guest. There are many vm-exits for EPT_MISCONFIG when I use `perf kvm stat live` on host.
**Perf kvm stat live**
EPT_MISCONFIG       1585    96.53%    99.98%      3.80us   7501.77us    176.44us ( +-  13.77% )

**To Reproduce**
Create VF device:
`echo  4 > /sys/class/net/eth0/device/sriov_numvfs`
`ip link set dev eth0 up`
`echo 0000:60:00.2 > /sys/bus/pci/devices/0000\:60\:00.2/driver/unbind`
`echo 15b3 1018 > /sys/bus/pci/drivers/vfio-pci/new_id `

`lspci | grep net`:
60:00.0 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
60:00.1 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
60:00.2 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5 Virtual Function]
60:00.3 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5 Virtual Function]
60:00.4 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5 Virtual Function]
60:00.5 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5 Virtual Function]

Add configuration for VM:
./cloud-hypervisor \
...
--device path=/sys/bus/pci/devices/0000:60:00.2/

I can see the VF when I use lspci on the guest:
00:00.0 Host bridge: Intel Corporation Device 0d57
00:01.0 Unassigned class [ffff]: Red Hat, Inc. Virtio console (rev 01)
00:02.0 Mass storage controller: Red Hat, Inc. Virtio block device (rev 01)
00:03.0 Unassigned class [ffff]: Red Hat, Inc. Virtio RNG (rev 01)
00:04.0 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5 Virtual Function]

Also I can use this VF to connect to the network.

**Version**
cloud-hypervisor v18.0-146-g52df97e6

**GDB**
I use GDB to debug. But it looks like that the mmio_regions is empty before entering the function map_mmio_regions() on device_manager.rs. As a result, the function does not successfully mmap.

**Comment by my-glhf** [comment]
This problem doesn't seem to be related to hugepages. I thought that access to the mmio_region of the pass-through device should not trigger ept_misconfig. When I use the same pass-through device on qemu, ept_misconfigs did not appear under the same test parameters.

**Comment by my-glhf** [comment]
I tried this patch, but it didn't work. Now, the mmio_regions is not empty, but In function map_mmio_regions, the region.index and msix.cap.table_bir() are also 0. It will execute the `continue` command. As a result, the map operation is not actually performed.

```       
        let fd = self.device.as_raw_fd();
        for region in self.common.mmio_regions.iter_mut() {
            // We want to skip the mapping of the BAR containing the MSI-X
            // table even if it is mappable. The reason is we need to trap
            // any access to the MSI-X table and update the GSI routing
            // accordingly.
            if let Some(msix) = &self.common.interrupt.msix {
                if region.index == msix.cap.table_bir() || region.index == msix.cap.pba_bir() {
                    continue;
                }
            }
```
**The content of msix.cap printed by gdb**
>cap: pci::msix::MsixCap {msg_ctl: 11, table: 8192, pba: 12288},

**Comment by sboeuf** [comment]
I've just tried with a NIC I have on my system which supports MSI-X, and I end up with 5 regions in total, with one region *not* being mapped, but the rest of the regions are mapped.

Could you apply this small change in order to print the information from your regions:
```diff
diff --git a/pci/src/vfio.rs b/pci/src/vfio.rs
index 465a341d..181ae19e 100644
--- a/pci/src/vfio.rs
+++ b/pci/src/vfio.rs
@@ -208,7 +208,7 @@ impl Interrupt {
     }
 }

-#[derive(Copy, Clone)]
+#[derive(Copy, Clone, Debug)]
 pub struct MmioRegion {
     pub start: GuestAddress,
     pub length: GuestUsize,
@@ -1017,6 +1017,7 @@ impl VfioPciDevice {
     {
         let fd = self.device.as_raw_fd();

+        println!("{} MMIO regions", self.common.mmio_regions.len());
         for region in self.common.mmio_regions.iter_mut() {
             // We want to skip the mapping of the BAR containing the MSI-X
             // table even if it is mappable. The reason is we need to trap
@@ -1024,9 +1025,11 @@ impl VfioPciDevice {
             // accordingly.
             if let Some(msix) = &self.common.interrupt.msix {
                 if region.index == msix.cap.table_bir() || region.index == msix.cap.pba_bir() {
+                    println!("### NOT MAPPED MMIO region:\n{:#?}", region);
                     continue;
                 }
             }
+            println!("### MAPPED MMIO region:\n{:#?}", region);

             let region_flags = self.device.get_region_flags(region.index);
             if region_flags & VFIO_REGION_INFO_FLAG_MMAP != 0 {
```

I don't think *not* mapping the region corresponding to the BAR containing the MSI-X table would cause a drop in performance. More than that, we want to trap the changes about MSI-X interrupts made by the guest, hence we can't afford to mmap this region.

**Comment by sboeuf** [comment]
That's interesting and definitely something to consider. I will need to make some more research to understand how this works and how we can integrate it with Cloud Hypervisor :)

**Comment by sboeuf** [comment]
Hi @my-glhf 
Have you been able to do more testing? Is everything working correctly?

Also, could you please have a try with this patch https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3283, as I would like to make sure it's not breaking anything for you.

**Comment by my-glhf** [comment]
> Hi @my-glhf Have you been able to do more testing? Is everything working correctly?

It may take a while for me to do more testing in other environments. But at least in my own environment, everything works fine.
> Also, could you please have a try with this patch #3283, as I would like to make sure it's not breaking anything for you.

No problem, I will try this patch as soon as possible.

**Comment by my-glhf** [comment]
I tried this latest patch in my own environment. There were no obvious problems during the test, and the performance is in line with expectations.

**Comment by sboeuf** [comment]
>I tried this latest patch in my own environment. There were no obvious problems during the test, and the performance is in line with expectations.

That's great, thanks for your confirmation :)

**Comment by rbradford** [comment]
@sboeuf Can this be closed now?

**Comment by sboeuf** [comment]
Yes!
