### ISSUE TITLE
AArch64 unit test got blocked frequently in CI

### ISSUE THREAD

**Issue by michael2012z** [cloud-hypervisor/cloud-hypervisor#3261]
In recent weeks (not sure when it began), the AArch64 unit test job got pending frequently. When this happened, all subsequent PR CI were blocked. And we have to login to the CI server and kill the pending containers manually.

An example: https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-3236/4/pipeline/248

Any idea why this happen? Could it be a cargo issue?

**Comment by michael2012z** [comment]
More observation:
- The issue is really random. I used a 100-time-loop to run the unit test, the problem was reproduced at the 79th shot.
- It was only seen on the CI server. I run the unit test for hundreds times on my local server, never saw it.

I attached to the cargo process when it was pending, seemingly it stopped at a WRITE syscal: https://code.woboq.org/userspace/glibc/sysdeps/unix/sysv/linux/write.c.html#26

See the gdb printings: [gdb.txt](https://github.com/cloud-hypervisor/cloud-hypervisor/files/7394287/gdb.txt)

**Comment by rbradford** [comment]
> Done that.
> 
> By the way, I received some feedback from cargo community about the solution/workaround to resolve the pending issue. Will try that later today.

Any update on this?

**Comment by michael2012z** [comment]
@rbradford Just now I installed kernel 5.16 on the arm64 CI server and rebooted. Could you help recover the Jenkins on it?

I will monitor if the new kernel can fix the pending issue in following days.

**Comment by michael2012z** [comment]
The problem was not seen again after upgrading the kernel. I think it's time to close this issue.
