### ISSUE TITLE
CPU pinning

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#3298]
__Goal__

Pin a specific vCPU to a set of host CPUs. This is useful in the context of NUMA, making sure vCPUs and memory are consistently assigned for different NUMA nodes.

__Technical details__

From each vCPU thread, we're going to call `sched_setaffinity()` based on the value provided by the user, or simply don't invoke this syscall if nothing was specified.

__User interface__

- The most versatile option would be to give the user a way to describe the host cpuset for each vCPU. We could add `affinity=` option to the `cpus` parameter. An example would be `--cpus boot=2,affinity=0@0x3:1@0xc`, meaning vCPU 0 will be running on host CPU 0 or 1, while vCPU 1 will be running on host CPU 2 or 3.
- Another option would be to allow a host NUMA node to be specified for each vCPU. We could add `host_numa_node=` option to the `cpus` parameter. An example would be `--cpus boot=2,host_numa_node=0@1:1@0`, meaning vCPU 0 will be running on host CPUs from host NUMA node 1, while vCPU 1 will be running on host CPUs from host NUMA node 0.

Since CPU pinning is really a user superpower option, my opinion is that we shouldn't try to be too smart about it and simply give the user the tools to apply it. That's why the first option looks the most appropriate to me.

**Comment by sboeuf** [comment]
@rbradford WDYT?

**Comment by rbradford** [comment]
Why would you want to specify multiple alternative host CPUs per vCPU (i.e. the use of the bitmap.)

For the second option can you create your own "host numa node" via the OS or does this only apply when the platform has given you multiple NUMA nodes?

**Comment by sboeuf** [comment]
>Why would you want to specify multiple alternative host CPUs per vCPU (i.e. the use of the bitmap.)

Because you might not want to run the vCPU exclusively on one host CPU. In case you're trying to run the VM on a specific host NUMA node, you would specify each vCPU as allowed to run on a set of host CPUs corresponding to the list of cores attached to the corresponding NUMA node.

>For the second option can you create your own "host numa node" via the OS or does this only apply when the platform has given you multiple NUMA nodes?

No we can't create a host NUMA node, we simply rely on what is available on the platform.

**Comment by rbradford** [comment]
> > Why would you want to specify multiple alternative host CPUs per vCPU (i.e. the use of the bitmap.)
> 
> Because you might not want to run the vCPU exclusively on one host CPU. In case you're trying to run the VM on a specific host NUMA node, you would specify each vCPU as allowed to run on a set of host CPUs corresponding to the list of cores attached to the corresponding NUMA node.

OK.

> > For the second option can you create your own "host numa node" via the OS or does this only apply when the platform has given you multiple NUMA nodes?
> 
> No we can't create a host NUMA node, we simply rely on what is available on the platform.

Then I think you need to do the former option. One of the main uses of CPU pinning is to carve up the physical CPU across the tenants to guarantee latency and the VM might only be a few vCPUs so not multiple NUMA nodes.
