### ISSUE TITLE
Potential undefined behaviors in code

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#3311]
Nightly clippy has this https://rust-lang.github.io/rust-clippy/master/index.html#uninit_vec and flags three places.

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/vm-migration/src/protocol.rs#L232
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/vmm/src/lib.rs#L765
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/vmm/src/lib.rs#L823

That reveals an issue. If somehow `read_exact` returns an error, a vector with uninitialized values will be dropped. Dropping uninitialized values is Undefined Behavior in Rust.

All three places are perhaps fine in practice, because dropping uninitialized `u8` and `MemoryRange` doesn't require calling destructors that touch (uninitialized) memory. Nonetheless it would be good if we can avoid the Undefined Behavior in the first place.

**Comment by sboeuf** [comment]
Good catch. Please review #3315
