### ISSUE TITLE
const array when borrow needs '&'

### ISSUE THREAD

**Issue by Apokleos** [cloud-hypervisor/cloud-hypervisor#3348]
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/46953db3ca206f42ad981ba524bee2427ba7adbc/vmm/src/vm.rs#L1596

the correct:
```bash
...
        for sig in &HANDLED_SIGNALS {
            unblock_signal(*sig).unwrap();
        }
...
```

the same correcting method does at     https://github.com/cloud-hypervisor/cloud-hypervisor/blob/46953db3ca206f42ad981ba524bee2427ba7adbc/src/main.rs#L516
```bash
...
    for sig in &vmm::vm::HANDLED_SIGNALS {
        if let Err(e) = block_signal(*sig) {
...
```

**Comment by liuw** [comment]
The difference between with and without `&` is calling `into_iter()` or `iter()`. The former gives you `T` while the latter gives you `&T`. For `i32` it doesn't make a difference right?

Or is there anything that is related to `const` that I'm not aware of?

**Comment by sboeuf** [comment]
Since `HANDLED_SIGNALS` is a list of `i32`, we don't want to take a reference, a copy is performed, which is actually faster for that kind of type.

**Comment by brho** [comment]
hi -

i'm ignorant of the details of rust, but i was unable to build due to this issue with HANDLED_SIGNALS:

```
error[E0277]: `[i32; 3]` is not an iterator
    --> vmm/src/vm.rs:1657:20
     |
1657 |         for sig in HANDLED_SIGNALS {
     |                    ^^^^^^^^^^^^^^^ borrow the array with `&` or call `.iter()` on it to iterate over it
     |
     = help: the trait `Iterator` is not implemented for `[i32; 3]`
     = note: arrays are not iterators, but slices like the following are: `&[1, 2, 3]`
     = note: required because of the requirements on the impl of `IntoIterator` for `[i32; 3]`
     = note: required by `into_iter
```

if i hack in the &, i get another issue later on:

```
   --> src/main.rs:516:16
    |
516 |     for sig in vmm::vm::HANDLED_SIGNALS {
    |                ^^^^^^^^^^^^^^^^^^^^^^^^ borrow the array with `&` or call `.iter()` on it to iterate over it
    |
```
rustc 1.50.0
at commit b519975fc859 ("build: Use Ubuntu impish (21.10) for workers")
