### ISSUE TITLE
Define a VM state payload

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#337]
In order to support migration and live migration, we need to work on 2 things:

1) Identify which part of a VM should define its state, with the goal of being able to restore it based on that state.
2) Define a JSON payload that would carry that VM state

The VM state payload should also contain the VM config structure, in order to be able to reboot a restored VM.

**Comment by sameo** [comment]
cc @yisun-git

**Comment by yisun-git** [comment]
Hi,

On 19-10-11 01:38:34, Samuel Ortiz wrote:
> In order to support migration and live migration, we need to work on 2 things:
> 
> 1) Identify which part of a VM should define its state, with the goal of being able to restore it based on that state.

I have listed the states and corresponding data structures in #75.
Please check it.

> 2) Define a JSON payload that would carry that VM state
> 
I have implemented infrastructure of MigrationDataFile which supports
read/write buffer under multi-thread condition. I think it can be the
payload to carry VM state. The buffer is Vec<u8> now and it is easy
to save JSON payload.

**Comment by sameo** [comment]
On Fri, Oct 11, 2019 at 07:49:23PM -0700, yisun-git wrote:
> Hi,
> 
> On 19-10-11 01:38:34, Samuel Ortiz wrote:
> > In order to support migration and live migration, we need to work on 2 things:
> > 
> > 1) Identify which part of a VM should define its state, with the goal of being able to restore it based on that state.
> 
> I have listed the states and corresponding data structures in #75.
> Please check it.
>

Yes, I saw that. It looks good to me.

> > 2) Define a JSON payload that would carry that VM state
> > 
> I have implemented infrastructure of MigrationDataFile which supports
> read/write buffer under multi-thread condition. I think it can be the
> payload to carry VM state.

It's hard to tell without seeing the code. Could you please share it?

**Comment by yisun-git** [comment]
> > 2) Define a JSON payload that would carry that VM state > I have implemented infrastructure of MigrationDataFile which supports read/write buffer under multi-thread condition. I think it can be the payload to carry VM state.
> It's hard to tell without seeing the code. Could you please share it?

Please refer prototype codes: https://github.com/intel/cloud-hypervisor/pull/347

**Comment by sameo** [comment]
Closed with PR #998
