### ISSUE TITLE
Implement VM state dumping

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#338]
Add a VM  `/api/v1/vm.dump` HTTP endpoint that would return a VM complete state.
Calling `PUT` on this endpoint will fail if the VM is not in the `Paused` state.

This HTTP request response body will be a VM state JSON payload (See #337). It's up to the caller to decide what to do with that HTTP body (store it on a filesystem, etc).

**Comment by yisun-git** [comment]
Hi,

On 19-10-11 01:40:31, Samuel Ortiz wrote:
> Add a VM  `/api/v1/vm.dump` HTTP endpoint that would return a VM complete state.

What DYM complete state? Does it like snapshot which contains all states
and ram data?

**Comment by sameo** [comment]
Hi Yi,

On Fri, Oct 11, 2019 at 08:15:20PM -0700, yisun-git wrote:
> Hi,
> 
> On 19-10-11 01:40:31, Samuel Ortiz wrote:
> > Add a VM  `/api/v1/vm.dump` HTTP endpoint that would return a VM complete state.
> 
> What DYM complete state? Does it like snapshot which contains all states
> and ram data?
>

Pretty much, yes. Something simpler that assumes the migrated VM is
paused, and something local. No transport implementation, etc. Just a
snapshot that you can re-use and e.g. call `cloud-hypervisor --vm-state
<vm-state.json>` or `curl -X PUT http://localhost/api/v1/vm.restore -d {vm-state} \`
to locally create an identical VM.

**Comment by sameo** [comment]
Closed with PR #998
