### ISSUE TITLE
Fix potential virtio deadlock when resuming a VM

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#341]
From @rbradford https://github.com/intel/cloud-hypervisor/pull/334#pullrequestreview-300726469:

> I think we could enter a network blockage situation here. Imagine a situation where the VM's kernel has already consumed all the packets in the queue (so all the descriptors are available for use by the network thread.
>
> The network thread will continue to consume descriptors for all the incoming packets on the TAP and try to signal to the VM (via the interrupt) that there are new descriptors available. Eventually the TAP code will use up all the descriptors (which are no longer being freed as the VM kernel is not running). It will then stop looking for new packets on the TAP socket and freeze itself waiting for the kernel to consume the packets.
>
> When the VM in unpaused the kernel has no reason to check if there are any frames to consume as it would only do so when it gets an interrupt. This will result in a possible deadlock where the guest kernel will not consume frames from the descriptor and the network backend will not trigger interrupts as there are no free descriptors for it to use.

**Comment by sameo** [comment]
Quick thoughts from @rbradford and myself: Either we try to pause the virtio threads as well, or we collect and coalesce interrupts and then deliver them at resume time.

**Comment by sboeuf** [comment]
Pausing the virtio threads looks to me like the right approach. I wonder if the vcpu thread should be paused first or if the virtio threads ones. Cause in one case we might miss some events/data.

**Comment by sameo** [comment]
Yes, pausing makes sense, especially since we're going to dump the virtio threads as well.
