### ISSUE TITLE
Make OVMF binary public

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3415]
The OVMF binary can (now) be public so it can be moved to the CDN. This will restore the ability to run the Linux guest integration tests for everyone as currently they require access to that binary. Alternatively we could use a GH action to build the binary upon tag in our edk2 fork repo and fetch it from there (like Rust Hypervisor Firmware.)

**Comment by sboeuf** [comment]
>The OVMF binary can (now) be public so it can be moved to the CDN. This will restore the ability to run the Linux guest integration tests for everyone as currently they require access to that binary.

Yes well only once the patches will be accepted upstream (which shouldn't take too long).

>Alternatively we could use a GH action to build the binary upon tag in our edk2 fork repo and fetch it from there (like Rust Hypervisor Firmware.)

Yes I thought about this one and it makes more sense, especially since we already do the same for RHF.
