### ISSUE TITLE
High memory consumption on aarch64 observed (Linux guest on the i.MX8M EVK)

### ISSUE THREAD

**Issue by ms-mahuber** [cloud-hypervisor/cloud-hypervisor#3419]
**Describe the bug**
CLH on aarch64 allocates a large shared memory region when running a VM, resulting in almost double the memory consumption as the VM memory size: Starting a 512MB VM costs ~913MB, starting a 1024 MB VM costs ~1816MB.
I'm running a Linux VM on a Linux host, with minimal CLH configuration/parameters on the i.MX8M EVK (see details below).

Comparing x86 and aarch64 behavior, I observe the difference with 'free -m', looking at the 'shared' column.

Before running the guest:
![image](https://user-images.githubusercontent.com/60939654/144894642-5122ba26-85ce-42bb-9bc2-5cbe57e9889a.png)
While running the guest:
![image](https://user-images.githubusercontent.com/60939654/144894688-bd203f5c-39df-4752-87f1-f18ee7afa8f4.png)
![image](https://user-images.githubusercontent.com/60939654/144894706-7b3427b2-bc64-4a3d-b846-82efbc933aa0.png)

During boot-up I can see how the (shared) memory consumption goes up piece by piece within a few seconds (the reverse is observed upon VM shutdown, until consumption is back to it's normal state).

No repro for the same setup on an x86 Mariner host OS running a Mariner guest OS. The memory consumption is low as expected.
Before:
![image](https://user-images.githubusercontent.com/60939654/144895245-f9201c5c-7e2e-4a19-852e-88d800ffdbed.png)
During run:
![image](https://user-images.githubusercontent.com/60939654/144895254-63956946-c6e4-4480-ac46-58ae34d44a37.png)
![image](https://user-images.githubusercontent.com/60939654/144895294-bfd3281c-f000-409a-a53e-1f8438b08191.png)

Further observations:
- Interestingly, my x86 Mariner host has 0 MB shared memory allocated after the guest boots.
- Take a look at the buff/cache column for the i.MX Mariner guest run, it also increased significantly in contrast to the x86 setup
- Minor: no new tmpfs mount entries are created and 'df -h' does not show any increases in tmpfs use

**To Reproduce**
Start a VM on aarch64 - observed at least on the i.MX8M EVK (https://www.nxp.com/design/development-boards/i-mx-evaluation-and-development-boards/evaluation-kit-for-the-i-mx-8m-applications-processor:MCIMX8M-EVK).

**Version**

Build from master branch: 419870ae45389e275dd44a2b1ffbf24297f7a5a6
cloud-hypervisor v19.0-198-g419870ae

**VM configuration**

Only an example:
<pathto>/cloud-hypervisor/target/release/cloud-hypervisor --api-socket /tmp/cloud-hypervisor.sock --kernel <pathto>/CLOUDHV_EFI.fd --disk path=<pathto>/vdisk-linux.raw --cpus boot=4 --memory size=1024M --net tap= --rng

Also tried with the debug build - OVMF was built manually (latest master), as well with debug and release configuration.

Guest OS version details:

Mariner Linux with kernel 5.10.64 (https://github.com/microsoft/CBL-Mariner)

Sidenote: I was also starting the Ubuntu server focal image with 1GB RAM.  I see an allocation of 576MB in the 'shared' memory column of 'free -m'

Host OS version details:

Same as guest OS

**Logs**

[clh-log-memory-aarch64.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/7662522/clh-log-memory-aarch64.log)

Linux kernel output:

Did not produce any dmesg output on the host

**Comment by rbradford** [comment]
`/proc/`pidof cloud-hypervisor`/smaps` will show you what the process address space looks like

**Comment by michael2012z** [comment]
@ms-mahuber Thank you for sharing the test result. Good observation! We are looking into this.

**Comment by michael2012z** [comment]
I have been trying to reproduce the issue on my server (Ubuntu 18.04, kernel 5.14), but didn't manage to see the exact situation.

Tested Cloud-hypervisor version: 
> main branch commit 419870ae45389e275dd44a2b1ffbf24297f7a5a6
> latest main branch
> Release v20 binary

Guest: 
> The Focal guest image used in CI (kernel 5.14)

Tested memory size: 
> 512M, 
> 1024M, 
> 8192M, 
> 16384M

Observation: (1024M as an example)

(Command:)
sudo RUST_BACKTRACE=1 ../cloud-hypervisor/target/debug/cloud-hypervisor --api-socket /tmp/cloud-hypervisor.sock --kernel /home/michael/workloads/CLOUDHV_EFI.fd --disk path=focal-server-cloudimg-arm64-custom-20210929-0-update-kernel.raw path=cloudinit-20210929-0.img --cpus boot=4 --memory size=1024M --serial tty --console off --log-file log.log -vvv --net tap=,mac=12:34:56:78:90:01,ip=192.168.1.1,mask=255.255.255.0 tap=,mac=8a:6b:6f:5a:de:ac,ip=192.168.3.1,mask=255.255.255.0

(Before starting VM)
➜  demo free -m
              total        used        free      shared  buff/cache   available
Mem:         128547       22814       75897           5       29835      104782
Swap:          2047           0        2047

(When VM is running)
➜  demo free -m
              total        used        free      shared  buff/cache   available
Mem:         128547       23164       75213         338       30169      104099
Swap:          2047           0        2047


The change in "free" field looks reasonable. 

There was obverse change in "shared" memory. And it increased if I assigned more memory to the guest. According to the man page of "free" command. "Shared" memory is probably used by tmpfs. But I am not sure what it was used for exactly. I will dig more about it. Appreciate if anybody can tell about that.

@ms-mahuber  I noticed that your test was done on a board which has limited amount of memory. And the memory consumption caused significant increase in "buff/cache" (memory was cached, not really consumed). Could it be the reason that the "free" field abnormal?

**Comment by michael2012z** [comment]
@ms-mahuber By the way, can you try to start 2 VMs (each assigned 1024M memory)?  If each of them really consume ~1800M memory, it should be impossible to start both successfully.

**Comment by ms-mahuber** [comment]
Thanks Rob, Michael for getting back to me so quickly and apologies for the delay.

@michael2012z : I have 3 GB of RAM on my device and when I assign the VM 2 GB of RAM, the VM gets "Killed" after a few seconds. Before it gets killed I see a constant increase of "Shared" memory in 'free -m' and my 'available' memory goes basically down to zero which is when the CLH process gets killed. Note that with QEMU I can successfully start my guest with 2GB (or even 2.5GB) assigned.

@rbradford : I'll take a closer look into the smaps output but wanted to share it right ahead with you: [smaps-output.txt](https://github.com/cloud-hypervisor/cloud-hypervisor/files/7671405/smaps-output.txt)
 
There's a very interesting section:
```
fa3870400000-fa38b0000000 rw-p 00000000 00:01 1049                       /memfd:ch_ram (deleted)
Size:            1044480 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:              966064 kB
Pss:              966064 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:    966064 kB
Referenced:       966064 kB
Anonymous:        966064 kB
LazyFree:              0 kB
```

**Comment by michael2012z** [comment]
More investigation update on this issue:

**A test on x86**

I run a VM on a x86 Ubuntu desktop, assigned 512M memory. The `free -m` output before and on the test was:

```
(Before)
              total        used        free      shared  buff/cache   available
Mem:          15791        3637        1869          35       10284       11978
Swap:             0           0           0

(Running)
root@57745418b91b:/cloud-hypervisor# free -m
              total        used        free      shared  buff/cache   available
Mem:          15791        3924         749        2548       11118        9174
Swap:             0           0           0
```


And in `/proc/X/smaps` there was the `/memfd:ch_ram (deleted)` section:
```
7fb190000000-7fb1b0000000 rw-p 00000000 00:01 8528                       /memfd:ch_ram (deleted)
Size:             524288 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:              267240 kB
Pss:              267240 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:       196 kB
Private_Dirty:    267044 kB
Referenced:       267220 kB
Anonymous:        267044 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
FilePmdMapped:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
THPeligible:    0
VmFlags: rd wr mr mw me nr

```

**Regarding `memfd_create`**

In Cloud Hypervisor we use `memfd_create` to allocate guest memory. `"The memfd_create() system call provides a simple alternative to manually mounting a tmpfs(5) filesystem and creating and opening a file in that filesystem."` That's why we see "shared" memory increase in `free -m`, because it takes tmpfs into account. And for the same reason, seeing "/memfd:ch_ram" in "/proc/X/smaps" is expected. The `Rss` size reflects the real memory consumption in "/memfd:ch_ram". 

In the test aforementioned, 267240 kB was actually consumed by the guest out of 524288 kB total ram. In your case, 465084 kB of 520192 kB ram was in use. It also make sense.

I don't know why the `shared` memory and `/memfd:ch_ram` was not seen in your test, if the guest ram was not file backed.


**Interpreting `free -m` output** 

Considering:
- "used" = "total" - "free" + "buff/cache" 
- "available" doesn't include the reclaimable memory in "buff/cache"

calculation on "used" or "available" doesnot tell the real memory consumption, because there is unknown amount of reclaimable memory in "buff/cache". While in the screenshots from the AArch64 test, "buff/cache" increased a lot.


Putting all together, I am still not sure there is a problem in the memory footprint.

**Comment by ms-mahuber** [comment]
Thanks Michael for those insights. I'd like to get back to the i.MX8M case - with your explanations in mind we can assume that the memory increase in 'shared' is expected. However, there is still the problem that when I start a 2GB guest my CLH process gets killed as the system runs out of memory (this does not happen with QEMU). I think my observations are still valid, potentially 'shared' not being the culprit though.

**Comment by ms-mahuber** [comment]
Dmesg tells me that the OOM killer got active, here's the relevant dmesg log output:
[dmesg-tail.txt](https://github.com/cloud-hypervisor/cloud-hypervisor/files/7688663/dmesg-tail.txt)

**Comment by ms-mahuber** [comment]
When I start the guest with 1.5 GB RAM assigned it doesn't crash but I'm not even getting to the guest login prompt. The whole system becomes almost unresponsive. Running 'free -m', it sells me that the amount of memory in 'free' or 'available' is quite low...:
![image](https://user-images.githubusercontent.com/60939654/145482121-9aae3d4b-e0bd-4369-9324-2d97ece8c27d.png)

**Comment by michael2012z** [comment]
Thanks, @ms-mahuber. I will keep looking into this. Next, I am going to compare the "smaps" data of Qemu and CLH on aarch64.

**Comment by ms-mahuber** [comment]
Thanks, @michael2012z for all your investigations. 

I definitely can not repro the issue on x86 (with the same kernel version and same CLH version) - I was spinning up a VM with CLH that consumed almost all available memory and it just works - in contrast to my aarch64 environment. My major observation on x86 is still that 'shared' remains 0 and buff/cache does not increase - just 'used'. Even though 'shared' may not be the culprit, it is an interesting diff not seeing an increase on x86 and seeing an increase on aarch64.

How can I better contribute with the investigation on aarch64? I was trying to use valgrind but it tells me:
`Warning: Can't execute setuid/setgid/setcap executable`.

Me going through the smaps output, the only real chunk of memory allocated is the memfd section. Also looking at the cloud-hypervisor process using top (here, for a 1GB VM):
![image](https://user-images.githubusercontent.com/60939654/145618382-3c867385-aabd-4626-bba3-d84c4dc24a4e.png)
Looks generally fine: The RES value is ~948MB. VIRT looks quite high but that is just virtual memory.
On x86 I'm seeing pretty much the same for a 1GB machine:
![image](https://user-images.githubusercontent.com/60939654/145618695-a09b6af9-9630-4e9f-91ff-a3e6fb05c579.png)
In both cases no other processes that show extensive memory usage.

**Comment by ms-mahuber** [comment]
Here is some more statistics. Left before starting a 1 GB VM, right after starting the 1 GB VM:
![image](https://user-images.githubusercontent.com/60939654/145621626-a4949c5f-d576-46c7-9a86-3c8a27c69166.png)

**Comment by ms-mahuber** [comment]
Again, on x86 I see that increase in Anon pages but not in Shmem:
![image](https://user-images.githubusercontent.com/60939654/145622372-963c2505-1d6e-4104-af8a-ec738316fcfd.png)

**Comment by michael2012z** [comment]
@ms-mahuber Thank you for adding more observation details. And it's a good point to compare with Qemu. I can reproduce the issue you found on both my AArch64 and X86_64 machines.

I compared the memory changes before and after starting a VM with Qemu (AArch64), Cloud Hypervisor (AArch64) and Cloud Hypervisor (X86_64), trying to identify some patterns:
```
Qemu:
(Before)
              total        used        free      shared  buff/cache   available
Mem:         128547       24865       61278         273       42404      102464
Swap:          2047           0        2047
(After)
              total        used        free      shared  buff/cache   available
Mem:         128547       25142       61000         273       42404      102186
Swap:          2047           0        2047

Cloud Hypervisor AArch64:
(Before)
              total        used        free      shared  buff/cache   available
Mem:         128547       24843       61299         273       42404      102485
Swap:          2047           0        2047
(After)
              total        used        free      shared  buff/cache   available
Mem:         128547       25209       60533         672       42803      101720
Swap:          2047           0        2047

Cloud Hypervisor X86_64:
(Before)
              total        used        free      shared  buff/cache   available
Mem:          15791        3476       10333        1236        1981       10911
Swap:             0           0           0
(After)
              total        used        free      shared  buff/cache   available
Mem:          15791        3750        9741        1506        2299       10366
Swap:             0           0           0
```

Facts:
- The change caused by QEMU was simple: "free" decreased by ~300MB, "available" decreased by ~300MB, "used" increased by ~300MB.
- The change by CLH (AArch64) was more complex: "free" decreased ~800MB, "shared" increased ~400MB, "buff/cache" increased ~400MB, "available" decreased ~800MB, "used" increased ~400MB.
- The change by CLH (X86_64) was also complex: "free" decreased ~600MB, "shared" increased ~300MB, "buff/cache" increased ~300MB, "available" decreased ~600MB, "used" increased ~300MB.

The pattern looks like:
- The increments in "shared" and "buff/cache" was seen in CLH only, but not in Qemu. 
- On CLH, the delta in "shared" and "buff/cache" value was similar.
- The memory decreased in "available" looks the summary of "shared" and "buff/cache". The decreased value of "available" on CLH looks 2 times than that on Qemu.

@rbradford Any idea about this? Is that possible that we are consuming double amount of memory by using `memfd`?

**Comment by rbradford** [comment]
I don't think if something is listed in shared + used then it is double allocated. The useful source of data is that from the smaps file. If that shows reasonable allocations then everything is fine.

@ms-mahuber Can you try `sudo mount -o remount,size=100% /dev/shm/` to see if that resolves your OOM issue/inability to start a VM that is more than 1/2 your RAM. (By default tmpfs is limited to 1/2 the RAM.)

**Comment by michael2012z** [comment]
I checked the output of `pmap` (which summarizes smaps data), it looks quite normal. 

@ms-mahuber , another thing you can try is applying `sysctl -w vm.drop_caches=3` when `shared` or `buff/cache` is high. The command should release a big portion of them and increase the `available` memory.

**Comment by ms-mahuber** [comment]
@rbradford : The /dev/shm remount didn't have any visible effect - the process gets still killed, see screenshot.

![shm-remount](https://user-images.githubusercontent.com/60939654/146053343-df3439f9-6dc3-47ee-a7a0-2ace20076215.png)

@michael2012z : 
- I've also looked into pmap (very useful tool) - it looks quite normal on my end as well.
- With the right timing, a call to `sysctl -w vm.drop_caches=3` results in the VM booting successfully up (e.g. at the example of a 2 GB VM which previously caused the crash).

I'd like to gain a bit of a better understanding of what is going on, especially what is the difference to QEMU and what is the part that may be dependent on my Linux distro - I guess it's not an elegant solution to manually clear the page cache (and friends). :)

**Comment by ms-mahuber** [comment]
1 GB VM - comparison between lsof with CLH and QEMU.

lsof -p pidofclh:
```
COMMAND    PID USER   FD      TYPE             DEVICE   SIZE/OFF    NODE NAME
...
cloud-hyp 2462 root   22u      REG                0,1    4194304      60 /memfd:ch_ram (deleted)
cloud-hyp 2462 root   23u      REG                0,1 1069547520      61 /memfd:ch_ram (deleted)
...
cloud-hyp 2462 root   67u      REG                8,1 2147483648      41 /ssd/disks/vdisk-linux.raw
...
```

lsof -p pidofqemu:
```
COMMAND    PID USER   FD      TYPE             DEVICE   SIZE/OFF    NODE NAME
...
qemu-syst 2644 root   10u      REG                8,1 2033057792     40 /ssd/disks/vdisk-linux.img
...
```

**Comment by ms-mahuber** [comment]
We were taking another look. We enabled swap on an internal MMC partition - after that the 2 GB guest would boot up. See 'free -m' before and after VM boot:
![image](https://user-images.githubusercontent.com/60939654/146072998-20e40c48-4b4b-432c-8f8e-45b1831a760a.png)

All it takes to run the 2 GB VM is 1 MB of swap.

I think using memfd_create for memory allocations for the VM leads in my case to the situation where the tmpfs is used while the page cache grows leading to no more available memory. In this case most likely the kernel cannot successfully remove pages from the page cache and can only help itself by killing the cloud-hypervisor process - the memory pressure is just to high. With a bit of swap, the kernel logic has enough resources to e.g. drop pages from the page cache which would explain the output of the second 'free -m' statement

**Comment by ms-mahuber** [comment]
Similar to QEMU I can now even boot a 2.5 GB VM with cloud-hypervisor. Now I see an increase in swap by 14 MB:
![image](https://user-images.githubusercontent.com/60939654/146074387-38e2b87f-c68d-456f-8828-825cea392031.png)

**Comment by michael2012z** [comment]
@ms-mahuber Indeed `drop_cache` is not a good solution, you need to issue the command while the `available` memory is dropping quickly. I was trying to find some option under `/proc/sys/vm` to keep the cache memory in lower level, but I didn't  get a good one.

It's great you've found the solution. :)

I have no idea how Qemu allocate memory for the guest. It's a good topic to dig more.

**Comment by ms-mahuber** [comment]
I think my scenario with a device with a low amount of memory hits kind of a corner case but I guess it can occur on any system without swap where you allocate nearly as much memory for the guest as is still free on the host (using cloud-hypervisor). 

I believe by default QEMU would allocate memory for its guests using mmap().

I still haven't fully grasped yet what happens with 'free'. On my x86 setup in my initial post, the 'shared' column is zero after the guest started. Only on aarch64 I saw 'shared' to grow almost as large as the VM size. However now with enabling swap, the figure in the 'shared' column is now not always a large as before, it probably gets cleared when we hit the memory limit and some free'ing of the page cache (and friends) happens....

While I think the whole memory allocation story for cloud-hypervisor won't change, it may be good to keep this issue in mind and potentially add some documentation notes around it. The size of `/dev/shm` is certainly some interesting aspect that should be kept in mind (`mount -o remount,size=100% /dev/shm/`). In theory if the size is not sufficient for a guest and if there is no swap it should not possible to start the guest.

**Comment by MrXinWang** [comment]
> While I think the whole memory allocation story for cloud-hypervisor won't change, it may be good to keep this issue in mind and potentially add some documentation notes around it. 

Maybe creating a "Note" or "Known issues" session in here https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/arm64.md would be a good choice?

**Comment by michael2012z** [comment]
Considering the confusion we've got during the trouble-shooting of this issue, there must be something can be improved:
- Regarding the shmem and cache memory usage, I don't think it's a problem. But is it something we should improve? @rbradford, what do you think?
- In the arm64 document, we can add about "swap".

**Comment by ms-mahuber** [comment]
I think this scenario is most likely occur with devices that have constrained RAM resources + creation of a VM that consumes most of the memory. Once the memory gets allocated and more pages are in the page cache (e.g., for reading the disk image), we run out of memory and the oom kill is not able to free up the sufficient little additional memory to resolve this situation and drop pages. Hence the kill of cloud-hypervisor without swap and the allocation of a minor amount of RAM when swap is available (resulting in the expected free memory after caches are cleared).

I leave it up to the experts how/if want to document this. I can provide my input to documentation if you like.
