### ISSUE TITLE
Add ch-remote-static binary to releases?

### ISSUE THREAD

**Issue by fengye87** [cloud-hypervisor/cloud-hypervisor#3425]
There's a `ch-remote` binary and a `ch-remote-static-aarch64` binary, but no `ch-remote-static` binary. Since there's a `cloud-hypervisor-static` binary in each release, it's reasonable to also include a `ch-remote-static` binary too? It could be quite handy when using it inside Alpine image.

**Comment by sboeuf** [comment]
>Since there's a cloud-hypervisor-static binary in each release, it's reasonable to also include a ch-remote-static binary too? It could be quite handy when using it inside Alpine image.

I agree! Feel free to send a PR for that :)
