### ISSUE TITLE
External API for live migration?

### ISSUE THREAD

**Issue by fengye87** [cloud-hypervisor/cloud-hypervisor#3426]
Is `ch-remote` the only way to do a live migration now? Will there be an external API for live migration?

**Comment by sboeuf** [comment]
You can perform migration by issuing HTTP request directly to the API socket, but `ch-remote` makes things simpler as it's handling this for you.

**Comment by fengye87** [comment]
I could not find any migration related API endpoints in the [OpenAPI doc](https://raw.githubusercontent.com/cloud-hypervisor/cloud-hypervisor/master/vmm/src/api/openapi/cloud-hypervisor.yaml). Maybe the doc is out-of-date? @sboeuf

**Comment by likebreath** [comment]
> I could not find any migration related API endpoints in the [OpenAPI doc](https://raw.githubusercontent.com/cloud-hypervisor/cloud-hypervisor/master/vmm/src/api/openapi/cloud-hypervisor.yaml).

Good catch. I just sent a PR to add the missing endpoints to our openapi spec file. As you know, these missing endpoints from the sepc file does not prevent you from using them with HTTP requests to the API socket.
