### ISSUE TITLE
dev_cli.sh fails

### ISSUE THREAD

**Issue by loxal** [cloud-hypervisor/cloud-hypervisor#3437]
![Screenshot_20211209_125946](https://user-images.githubusercontent.com/87507/145392773-b375db11-6a63-4c63-b48b-ac1517bd24c6.png)

**Comment by liuw** [comment]
The same rune works for me.

Perhaps the volume mapping is not working correctly on your system?

**Comment by loxal** [comment]
I am on Fedora and usually when mapping volumes I need to append `:z` like `-v /volume-container:/volume-host:z`. This is difference between running containers in Ubuntu vs Fedora which is not even using `docker` but `podman` to run containers behind the scenes.

**Comment by liuw** [comment]
Ah, my system is Debian. Perhaps other people who use Fedora can comment on whether this is an issue for them.

**Comment by liuw** [comment]
BTW I have been building CH natively and seldom used containers. Looks like you already have Rust installed on your system so that should work for you too.

**Comment by loxal** [comment]
I just opened the script and appended `:z` to all volume mappings and I got one step further:
![Screenshot_20211209_140900](https://user-images.githubusercontent.com/87507/145402422-b8a68b94-65bf-468b-b48a-65d39dd5bfeb.png)

**Comment by loxal** [comment]
![Screenshot_20211209_142109](https://user-images.githubusercontent.com/87507/145404023-717fdd8c-4c3c-4d68-ba3e-17bd424f5d25.png)

**Comment by rbradford** [comment]
If you're on Fedora did you disable selinux? The podman/docker selinux rules won't allow you to access those files.

**Comment by loxal** [comment]
I just disabled SELinux: 

![Screenshot_20211209_144258](https://user-images.githubusercontent.com/87507/145407309-921e3808-9f20-43fd-a8bc-2d07a21df4ff.png)

**Comment by loxal** [comment]
Looks like an outdated Rust version issue? ...although I am not quite familiar with Rust.

**Comment by loxal** [comment]
Rust is a bit like a JavaScript library: if you update it, you break your code because there are another ton of backwards-incompatible features; I've updated to `rustup update` > `v1.57.0` and got this:
![Screenshot_20211209_145628](https://user-images.githubusercontent.com/87507/145409572-88cb3ed5-e390-405a-ad5c-0672b5addbc7.png)

**Comment by liuw** [comment]
Hmm... I'm also using 1.57 and it works fine for me.

Can you do a `cargo clean` to remove all generated artefacts?

**Comment by rbradford** [comment]
The error message you get it because you have two version of `vm-memory` being compiled. Could you have a local change that is resulting in that?

**Comment by rbradford** [comment]
(I see if I do a `cargo update` before the build a 2nd version of vm-memory is pulled in.)

**Comment by loxal** [comment]
Thanks @liuw, I issued `cargo clean` on the screenshot above but apparently this was not sufficient but `git reset --hard HEAD` did resolve the problem. So having a rebuild CH I still get:

> ❯ ./scripts/dev_cli.sh build --release
> Trying to pull docker.io/cloudhypervisor/dev:latest...
> Getting image source signatures
> Copying blob 9564fceb82ea skipped: already exists
> Copying blob e9cfecc51bc3 skipped: already exists
> Copying blob 6ad1605c7154 skipped: already exists
> Copying blob 99f5e13544d8 skipped: already exists
> Copying blob d0ae771fe8d7 skipped: already exists
> Copying blob d7e375dc6111 skipped: already exists
> Copying blob 07327dc00ec3 skipped: already exists
> Copying blob 7b1a6ab2e44d skipped: already exists
> Copying blob e6fa6bec8e45 skipped: already exists
> Copying config 7332edffe5 done
> Writing manifest to image destination
> Storing signatures
> 7332edffe5bad96491c03606955f5d66f59853761181e276aa211f6fda958b95
> warning: patch for `kvm-bindings` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
> Updating git repository `https://github.com/cloud-hypervisor/kvm-bindings`
> error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`
> 
> Caused by:
> failed to load source for dependency `kvm-bindings`
> 
> Caused by:
> Unable to update https://github.com/cloud-hypervisor/kvm-bindings?branch=ch-v0.5.0#9c497710
> 
> Caused by:
> failed to create directory `/usr/local/rust/git/db/kvm-bindings-c6b55506be61a061`
> 
> Caused by:
> Permission denied (os error 13)

**Comment by rbradford** [comment]
(If you already have a the Rust toolchain installed i'm not sure using dev_cli.sh will give you any benefit for building.)

**Comment by liuw** [comment]
You're both using the `dev_cli.sh` and native build. Can you stick with native build for now?

I can see your rust directory is under /usr/local/rust, which means you perhaps specified that path when running rustup. I would suggest you check if you really have permission to create directories or files under it by creating some dummy directories and files under that path.

**Comment by loxal** [comment]
@liuw I extra created `/usr/local/rust` and gave r/w permissions to my user but I'll go ahead w/o containers. Thanks a lot for your support @rbradford & @liuw!

**Comment by rbradford** [comment]
I just tested on F35 and it works fine:

```
marvin:~/src/cloud-hypervisor (main)$ scripts/dev_cli.sh build --release
latest: Pulling from cloudhypervisor/dev
7b1a6ab2e44d: Already exists 
e9cfecc51bc3: Pull complete 
99f5e13544d8: Pull complete 
d0ae771fe8d7: Pull complete 
6ad1605c7154: Pull complete 
9564fceb82ea: Pull complete 
d7e375dc6111: Pull complete 
07327dc00ec3: Pull complete 
e6fa6bec8e45: Pull complete 
Digest: sha256:800ef5afc279976c48f8a66476e42d7796c8adc6b0659c8e895f683aee48ef67
Status: Downloaded newer image for cloudhypervisor/dev:latest
docker.io/cloudhypervisor/dev:latest
error: could not find `Cargo.toml` in `/cloud-hypervisor` or any parent directory
marvin:~/src/cloud-hypervisor (main)$ sudo setenforce 0
marvin:~/src/cloud-hypervisor (main)$ scripts/dev_cli.sh build --release
latest: Pulling from cloudhypervisor/dev
Digest: sha256:800ef5afc279976c48f8a66476e42d7796c8adc6b0659c8e895f683aee48ef67
Status: Image is up to date for cloudhypervisor/dev:latest
docker.io/cloudhypervisor/dev:latest
warning: patch for `kvm-bindings` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
    Updating git repository `https://github.com/cloud-hypervisor/kvm-bindings`
    Updating git submodule `https://github.com/rust-vmm/rust-vmm-ci.git`
    Updating git repository `https://github.com/rust-vmm/kvm-ioctls`
    Updating git submodule `https://github.com/rust-vmm/rust-vmm-ci.git`
    Updating git repository `https://github.com/cloud-hypervisor/versionize_derive`
    Updating git submodule `https://github.com/rust-vmm/rust-vmm-ci.git`
    Updating crates.io index
....
   Compiling vmm v0.1.0 (/cloud-hypervisor/vmm)
   Finished release [optimized] target(s) in 2m 43s
[Cloud Hypervisor] Binaries placed under /home/rob/src/cloud-hypervisor/build/cargo_target/x86_64-unknown-linux-gnu/release
```

**Comment by rbradford** [comment]
(Notice how I had to disable selinux to allow it to see the downloaded source code.)

**Comment by loxal** [comment]
> (Notice how I had to disable selinux to allow it to see the downloaded source code.)

...for the container to see the source host on your host? I guess this is what I did by appending `:z` to the volume mappings inside the `dev_cli.sh` script.

**Comment by rbradford** [comment]
I was unable to reproduce this failure on F35 when using docker (not podman) which the script was designed to use. Please reopen if you have further insight on this issue.
