### ISSUE TITLE
Support TD Shim

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#3444]
Here is the list of things we need to implement in order to support TD Shim with Cloud Hypervisor:
- The CLI must accept `--kernel` and `--cmdline` to be provided along with `--tdx` so that we can specify a payload (`vmlinux` kernel) along with its boot parameters.
- Parse the TD Shim metadata to identify if `Payload` and `PayloadParam` sections can be found. If that's the case, retrieve the value about where to load/copy them.
- For each ACPI table (static ones only), add an entry to the HOB that contains the table itself.
- Create an E820 table with a list of entries that can be passed through the HOB.
- Create a payload info table that can be passed through the HOB, containing information about the image type as well as the loading address.

**Comment by rbradford** [comment]
I think we need to have more discussion with the TD shim spec authors before going ahead with this implementation. As I think there are some important gaps.

>     * For each ACPI table (static ones only), add an entry to the HOB that contains the table itself.

Not including the DSDT is, from my understanding, motivated by not wanting to support hotplug. However the DSDT serves multiple purposes in Cloud Hypervisor beyond hotplug:

* PCI routing information
* Serial port IRQ setup
* Multiple PCI segment support
* Specifying the value for the ACPI HW reduced shutdown register to trigger a shutdown
* Power button triggering through GED 

Further I think that it is possible to support PCI device hotplug with TDX.

The DSDT is specified as part of the FADT/FACP so the kernel will find it anyway if you give it the FADT table unless the TD shim to manually create it's own RSDP and FADT tables.

A much simpler approach would be to just specify the RSDP address in the HOB (as per the TDVF based boot.)

**Comment by sboeuf** [comment]
Sounds good, let's have this discussion.

**Comment by sboeuf** [comment]
Discussion moved over to https://github.com/confidential-containers/td-shim/issues/8
