### ISSUE TITLE
Networking performance regression

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3450]
With

```
58d25b3cccff967aa10a56f8f87692ca946aad7d is the first bad commit
commit 58d25b3cccff967aa10a56f8f87692ca946aad7d
Author: Sebastien Boeuf <sebastien.boeuf@intel.com>
Date:   Wed Nov 3 17:22:03 2021 +0100

    virtio-devices: net: Improve throughput with virtio features
    
    By merging receive buffers through the VIRTIO_NET_F_MRG_RXBUF feature,
    as well as enabling the use of indirect descriptors through
    VIRTIO_RING_F_INDIRECT_DESC feature, we achieve better throughput for
    the virtio-net device without hurting its latency.
    
    Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

 virtio-devices/src/net.rs | 6 +++++-

```

I also see a networking performance regression that becomes apparent based on the iperf direction

On the commit before this one:

```
marvin:~/src/cloud-hypervisor ((495d4eb8...))$ iperf  -c 192.168.249.2
------------------------------------------------------------
Client connecting to 192.168.249.2, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  1] local 192.168.249.1 port 47076 connected with 192.168.249.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  1] 0.00-10.02 sec  53.6 GBytes  45.9 Gbits/sec
marvin:~/src/cloud-hypervisor ((495d4eb8...))$ iperf -s
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size:  128 KByte (default)
------------------------------------------------------------
[  1] local 192.168.249.1 port 5001 connected with 192.168.249.2 port 45618
[ ID] Interval       Transfer     Bandwidth
[  1] 0.00-10.02 sec  48.2 GBytes  41.3 Gbits/sec
```

But with the commit in question:

```
marvin:~/src/cloud-hypervisor ((58d25b3c...))$ iperf  -c 192.168.249.2
------------------------------------------------------------
Client connecting to 192.168.249.2, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  1] local 192.168.249.1 port 47078 connected with 192.168.249.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  1] 0.00-10.40 sec  14.0 MBytes  11.3 Mbits/sec
marvin:~/src/cloud-hypervisor ((58d25b3c...))$ iperf -s
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size:  128 KByte (default)
------------------------------------------------------------
[  1] local 192.168.249.1 port 5001 connected with 192.168.249.2 port 42866
[ ID] Interval       Transfer     Bandwidth
[  1] 0.00-10.01 sec  51.2 GBytes  44.0 Gbits/sec
```

I can see the slight improvement this commit is trying to achieve where the guest is the client and the host is the server. However in the reverse direction the reduction is more than 1000x.

_Originally posted by @rbradford in https://github.com/cloud-hypervisor/cloud-hypervisor/discussions/3449#discussioncomment-1793047_

**Comment by rbradford** [comment]
We should probably revert and spin a v20.1 release since this quite a significant regression that would affect folks using CH in production where it is acting as the server

**Comment by sboeuf** [comment]
>We should probably revert and spin a v20.1 release since this quite a significant regression that would affect folks using CH in production where it is acting as the server.

Yes I agree a `v20.1` would be appropriate in this situation.

**Comment by rbradford** [comment]
@sboeuf The reason that this the networking performance regressed with the `VIRTIO_NET_F_MRG_RXBUF` feature enabled was the feature was not implemented fully.

When this feature is enabled the guest may provide significantly smaller buffers (A buffer is formed of multiple descriptors in a chain i.e. it is a chain head.):

> 
    If VIRTIO_NET_F_MRG_RXBUF is not negotiated:
        If VIRTIO_NET_F_GUEST_TSO4, VIRTIO_NET_F_GUEST_TSO6 or VIRTIO_NET_F_GUEST_UFO are negotiated, the driver SHOULD populate the receive queue(s) with buffers of at least 65562 bytes.
        Otherwise, the driver SHOULD populate the receive queue(s) with buffers of at least 1526 bytes.
    If VIRTIO_NET_F_MRG_RXBUF is negotiated, each buffer MUST be at least the size of the struct virtio_net_hdr.

And then the device is responsible for placing the full packet (as read from TAP) across multiple buffers (these buffers may be formed from multiple descriptors) and then setting `num_buffers` in the header of the first buffer to say how many are used.

However since we do not use an intermediate buffer to store the full packet read from TAP we cannot spread it across multiple buffers (it will be spread over the multiple desciptors forming the single large buffer using iovecs). This is because we do not know how big the TAP packet will be until we've read it all and thus don't know how many buffers will be needed to read it into. 

Reading into an intermediate buffer would allow us to implement `VIRTIO_NET_F_MRG_RXBUF` since then we could spread the packet over multiple buffers however I would rather stick with our efficient one copy approach rather then add a second copy.

**Comment by sboeuf** [comment]
>The reason that this the networking performance regressed with the VIRTIO_NET_F_MRG_RXBUF feature enabled was the feature was not implemented fully.

Ah yeah I forgot about that!

>Reading into an intermediate buffer would allow us to implement VIRTIO_NET_F_MRG_RXBUF since then we could spread the packet over multiple buffers however I would rather stick with our efficient one copy approach rather then add a second copy.

Oh yes I'd rather stick with the "simple" approach as well rather than coming back to the intermediate buffer implementation as I believe it would bring potential bugs.

One a side note, I guess you can try re-enabling VIRTIO_RING_F_INDIRECT_DESC as this might give us some improvements without any drawbacks.
