### ISSUE TITLE
use --console pty start cloud-hypervisor failed

### ISSUE THREAD

**Issue by Lxiaoyouling** [cloud-hypervisor/cloud-hypervisor#3456]
**Describe the bug**
When use --console pty start cloud-hypervisor, report error. 

thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 38, kind: Unsupported, message: "Function not implemented" }', vmm/src/device_manager.rs:1670:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error booting VM: ResponseRecv(RecvError)

**To Reproduce**
 cloud-hypervisor --kernel *** vmlinux --disk path=***.raw --cpus boot=2 --memory size=4G --cmdline "root=/dev/vda1 console=ttyS0" --serial tty --api-socket=/tmp/api1 --log-file log.log -vvv --console pty

**Version**
v19.0, v20.0
Use v17.0, there is no this error.

**Logs**
cloud-hypervisor: 4.330322ms: <vmm> INFO:vmm/src/vm.rs:528 -- Booting VM from config: Mutex { data: VmConfig { c
pus: CpusConfig { boot_vcpus: 2, max_vcpus: 2, topology: None, kvm_hyperv: false, max_phys_bits: 46 }, memory: M
emoryConfig { size: 4294967296, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: Non
e, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None }, kernel: Some(KernelConf
ig { path: "/vm_data/cloud-hypervisor/vmlinux" }), initramfs: None, cmdline: CmdlineConfig { args: "root=/dev/vd
a1 console=ttyS0" }, disks: Some([DiskConfig { path: Some("/vm_data/cloud-hypervisor/centos_7.6.raw"), readonly:
 false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll
_queue: true, rate_limiter_config: None, id: None, disable_io_uring: false }]), net: None, rng: RngConfig { src:
 "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode:
Tty, iommu: false }, console: ConsoleConfig { file: None, mode: Pty, iommu: false }, devices: None, user_devices
: None, vsock: None, iommu: false, sgx_epc: None, numa: None, watchdog: false }, poisoned: false, .. }
cloud-hypervisor: 4.679385ms: <vmm> INFO:vmm/src/pci_segment.rs:84 -- Adding PCI segment: id=0, PCI MMIO config
address: 0xe8000000
cloud-hypervisor: 5.035404ms: <serial-manager> INFO:vmm/src/serial_manager.rs:244 -- KILL event received, stoppi
ng epoll loop

**Comment by rbradford** [comment]
Pleaser can you run with `RUST_BACKTRACE=1` to get the full BT. You might need `--seccomp false` for the backtrace printing.

**Comment by alyssais** [comment]
Assuming the error message above is from 19.0 (because on 20.0 the line number doesn't make much sense), this error is coming from `start_sigwinch_listener`, and is ENOSYS.  That suggests cloud-hypervisor is using a syscall your kernel doesn't implement.  What version of Linux is your host machine running?

**Comment by rbradford** [comment]
That code uses `CLONE_CLEAR_SIGHAND` which was added in Linux v5.5 and `clone3` that was added in v5.3. That's relatively new, perhaps we can have soft fail where the PTY resize code doesn't work on these older kernels rather than just rejecting it.

**Comment by alyssais** [comment]
There might be an even easier win, depending on what kernel @Lxiaoyouling wants to use — we're using the 5.7 version of `struct clone_args`, but not using any features that are newer than `CLONE_CLEAR_SIGHAND` from 5.5.  So the code as written doesn't work on 5.6 or 5.7 for basically no reason, and we should be able to solve that by just deleting the `cgroup` member from our definition of the `clone_args` struct.

We could also work around a lack of `CLONE_CLEAR_SIGHAND`/`clone3` by manually looping through every possible signal and resetting them, which would be inefficient but still work.  It comes down to where we want to draw the line between support for older kernels and maintainability.  I think knowing which kernel @Lxiaoyouling would help with that call, so we don't end up going out of our way to support a kernel nobody actually wants to use with cloud-hypervisor.

**Comment by rbradford** [comment]
Ubuntu 20.04 ships with 5.3 which is definitely an OS we want to support. I think it's very reasonable to just not have this SIGWINCH handling on older kernels.

**Comment by alyssais** [comment]
That makes sense.  I think it would be good to have a kernel version policy documented (e.g. it could say "we want to support the latest Ubuntu LTS, but it's okay if some features require newer kernels to work"), because I remember wondering about this when writing the SIGWINCH process stuff.  What do you think?

**Comment by Lxiaoyouling** [comment]
> Please can you run with `RUST_BACKTRACE=1` to get the full BT. You might need `--seccomp false` for the backtrace printing.

I use RUST_BACKTRACE=1 and --seccomp false, there is the following print:

thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 38, kind: Unsupported, message: "Function not implemented" }', vmm/src/device_manager.rs:1670:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: vmm::device_manager::DeviceManager::add_console_device
   4: vmm::device_manager::DeviceManager::create_devices
   5: vmm::vm::Vm::new
   6: vmm::Vmm::control_loop
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error booting VM: ResponseRecv(RecvError)

use RUST_BACKTRACE=full, there is the following print:
thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 38, kind: Unsupported, message: "Function not implemented" }', vmm/src/device_manager.rs:1670:59
stack backtrace:
   0:           0x4e91b5 - std::backtrace_rs::backtrace::libunwind::trace::hb16dbf761681cfc0
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:           0x4e91b5 - std::backtrace_rs::backtrace::trace_unsynchronized::h53bc5f57122de54d
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:           0x4e91b5 - std::sys_common::backtrace::_print_fmt::h7e86959aa36cde43
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:           0x4e91b5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf42958820747a8ac
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:           0x49594c - core::fmt::write::h6f5ededa5074697e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:           0x4e76a4 - std::io::Write::write_fmt::hdb84dc6c28fda870
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:           0x4e81eb - std::sys_common::backtrace::_print::hbb646398d13d0dcb
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:           0x4e81eb - std::sys_common::backtrace::print::ha3796c9cf0c5a732
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:           0x4e81eb - std::panicking::default_hook::{{closure}}::hb85a09d7e9a16432
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:           0x4e72a9 - std::panicking::default_hook::hdc924e74cb190bbb
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:           0x4e72a9 - std::panicking::rust_panic_with_hook::hd63b080e78590a80
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:           0x500b58 - std::panicking::begin_panic_handler::{{closure}}::h27bfba1f7e931f90
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  12:           0x500acc - std::sys_common::backtrace::__rust_end_short_backtrace::h2cc025f6c95b1f82
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:           0x500a7d - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:           0x401c10 - core::panicking::panic_fmt::h9f5a85773697c5f5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
  15:           0x401f42 - core::result::unwrap_failed::h43465fb8e3273283
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
  16:           0x688776 - vmm::device_manager::DeviceManager::add_console_device::h6dc166ad9da30e20
  17:           0x6821e9 - vmm::device_manager::DeviceManager::create_devices::h1164ba8c9786de27
  18:           0x650c64 - vmm::vm::Vm::new::h27dc9936496d5006
  19:           0x6bc963 - vmm::Vmm::control_loop::hb376f4850ba93504
  20:           0x73370b - std::sys_common::backtrace::__rust_begin_short_backtrace::h17a5a18954a850d0
  21:           0x61bda0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h09fe1e4b94bd5735
  22:           0x509336 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4b43062ddf86e957
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  23:           0x509336 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h140d9feeaae0eb97
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  24:           0x509336 - std::sys::unix::thread::Thread::new::thread_start::hf02895d7c8c67d27
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
Error booting VM: ResponseRecv(RecvError)

**Comment by Lxiaoyouling** [comment]
> Assuming the error message above is from 19.0 (because on 20.0 the line number doesn't make much sense), this error is coming from `start_sigwinch_listener`, and is ENOSYS. That suggests cloud-hypervisor is using a syscall your kernel doesn't implement. What version of Linux is your host machine running?

Yes, I'm using cloud-hypervisor v19.0 here. 
My host machine linux version is 4.18，os is centos8.2. Virtual machine linux version is linux-5.6-rc4

**Comment by Lxiaoyouling** [comment]
> 

My host machine linux version is 4.18，os is centos8.2. Virtual machine linux version is linux-5.6-rc4.
Does this mean that I should upgrade my host kernel version or virtual machine kernel version to get around this bug?

**Comment by Lxiaoyouling** [comment]
> There might be an even easier win, depending on what kernel @Lxiaoyouling wants to use — we're using the 5.7 version of `struct clone_args`, but not using any features that are newer than `CLONE_CLEAR_SIGHAND` from 5.5. So the code as written doesn't work on 5.6 or 5.7 for basically no reason, and we should be able to solve that by just deleting the `cgroup` member from our definition of the `clone_args` struct.
> 
> We could also work around a lack of `CLONE_CLEAR_SIGHAND`/`clone3` by manually looping through every possible signal and resetting them, which would be inefficient but still work. It comes down to where we want to draw the line between support for older kernels and maintainability. I think knowing which kernel @Lxiaoyouling would help with that call, so we don't end up going out of our way to support a kernel nobody actually wants to use with cloud-hypervisor.

My host machine linux version is 4.18，os is centos8.2. Virtual machine linux version is linux-5.6-rc4.
Does this mean that I should upgrade my host kernel version or virtual machine kernel version to get around this bug?

**Comment by Lxiaoyouling** [comment]
My host uses the 5.4 linux kernel, and cloud-hypervisor can start normally.
But when --console pty is set in command line, two cloud-hypervisor processes are started, is this normal?

pstree -apnh
 ├─sshd,11571 -D
  │   ├─sshd,12011
  │   │   └─sshd,12013,lxiaoyouling
  │   │       └─bash,12014
  │   │           └─sudo,12045,root su
  │   │               └─su,12046
  │   │                   └─bash,12047
  │   │                       └─cloud-hyperviso,12095 --kernel /vm_data/lxiaoyouling/cloud-hypervisor/vmlinux --disk path=/vm_data/lxiaoyouling/cloud-hypervisor/centos_7.6.raw --cpus boot=2 --memory size=4G --cmdlineroot=/dev/vda1 conso
  │   │                           ├─{cloud-hyperviso},12096
  │   │                           ├─{cloud-hyperviso},12097
  │   │                           ├─{cloud-hyperviso},12098
  │   │                           ├─{cloud-hyperviso},12102
  │   │                           ├─vmm,12103 --kernel /vm_data/lxiaoyouling/cloud-hypervisor/vmlinux --disk path=/vm_data/lxiaoyouling/cloud-hypervisor/centos_7.6.raw --cpus boot=2 --memory size=4G --cmdlineroot=/dev/vda1 conso
  │   │                           ├─{cloud-hyperviso},12104
  │   │                           ├─{cloud-hyperviso},12105
  │   │                           ├─{cloud-hyperviso},12106
  │   │                           ├─{cloud-hyperviso},12107
  │   │                           ├─{cloud-hyperviso},12108
  │   │                           ├─{cloud-hyperviso},12109
  │   │                           └─{cloud-hyperviso},12110

**Comment by Lxiaoyouling** [comment]
My host uses the 5.4 linux kernel, and cloud-hypervisor can start normally.
But when --console pty is set in command line, two cloud-hypervisor processes are started, is this normal?

pstree -apnh
  │   │                   └─bash,12047
  │   │                       └─cloud-hyperviso,12095 --kernel /vm_data/lizhaoxin1/cloud-hypervisor/vmlinux --disk path=/vm_data/lizhaoxin1/cloud-hypervisor/centos_7.6.raw --cpus boot=2 --memory size=4G --cmdlineroot=/dev/vda1 conso
  │   │                           ├─{cloud-hyperviso},12096
  │   │                           ├─{cloud-hyperviso},12097
  │   │                           ├─{cloud-hyperviso},12098
  │   │                           ├─{cloud-hyperviso},12102
  │   │                           ├─vmm,12103 --kernel /vm_data/lizhaoxin1/cloud-hypervisor/vmlinux --disk path=/vm_data/lizhaoxin1/cloud-hypervisor/centos_7.6.raw --cpus boot=2 --memory size=4G --cmdlineroot=/dev/vda1 conso
  │   │                           ├─{cloud-hyperviso},12104
  │   │                           ├─{cloud-hyperviso},12105
  │   │                           ├─{cloud-hyperviso},12106
  │   │                           ├─{cloud-hyperviso},12107
  │   │                           ├─{cloud-hyperviso},12108
  │   │                           ├─{cloud-hyperviso},12109
  │   │                           └─{cloud-hyperviso},12110

**Comment by Lxiaoyouling** [comment]
My host uses the 5.4 linux kernel, and cloud-hypervisor can start normally.
But when --console pty is set in command line, two cloud-hypervisor processes are started, is this normal?

`  │   │                   └─bash,12047
  │   │                       └─cloud-hyperviso,12095 --kernel /vm_data/lizhaoxin1/cloud-hypervisor/vmlinux --disk path=/vm_data/lizhaoxin1/cloud-hypervisor/centos_7.6.raw --cpus boot=2 --memory size=4G --cmdlineroot=/dev/vda1 conso
  │   │                           ├─{cloud-hyperviso},12096
  │   │                           ├─{cloud-hyperviso},12097
  │   │                           ├─{cloud-hyperviso},12098
  │   │                           ├─{cloud-hyperviso},12102
  │   │                           ├─vmm,12103 --kernel /vm_data/lizhaoxin1/cloud-hypervisor/vmlinux --disk path=/vm_data/lizhaoxin1/cloud-hypervisor/centos_7.6.raw --cpus boot=2 --memory size=4G --cmdlineroot=/dev/vda1 conso
  │   │                           ├─{cloud-hyperviso},12104
  │   │                           ├─{cloud-hyperviso},12105
  │   │                           ├─{cloud-hyperviso},12106
  │   │                           ├─{cloud-hyperviso},12107
  │   │                           ├─{cloud-hyperviso},12108
  │   │                           ├─{cloud-hyperviso},12109
  │   │                           └─{cloud-hyperviso},12110`

**Comment by Lxiaoyouling** [comment]
My host uses the 5.4 linux kernel, and cloud-hypervisor can start normally.
But when --console pty is set in command line, two cloud-hypervisor processes are started, is this normal?

  │   │              └─bash,12047
  │   │                       └─cloud-hyperviso,12095 --kernel /vm_data/lizhaoxin1/cloud-hypervisor/vmlinux --disk path=/vm_data/lizhaoxin1/cloud-hypervisor/centos_7.6.raw --cpus boot=2 --memory size=4G --cmdlineroot=/dev/vda1 conso
  │   │                           ├─{cloud-hyperviso},12096
  │   │                           ├─{cloud-hyperviso},12097
  │   │                           ├─{cloud-hyperviso},12098
  │   │                           ├─{cloud-hyperviso},12102
  │   │                           ├─vmm,12103 --kernel /vm_data/lizhaoxin1/cloud-hypervisor/vmlinux --disk path=/vm_data/lizhaoxin1/cloud-hypervisor/centos_7.6.raw --cpus boot=2 --memory size=4G --cmdlineroot=/dev/vda1 conso
  │   │                           ├─{cloud-hyperviso},12104
  │   │                           ├─{cloud-hyperviso},12105
  │   │                           ├─{cloud-hyperviso},12106
  │   │                           ├─{cloud-hyperviso},12107
  │   │                           ├─{cloud-hyperviso},12108
  │   │                           ├─{cloud-hyperviso},12109
  │   │                           └─{cloud-hyperviso},12110

**Comment by Lxiaoyouling** [comment]
My host uses the 5.4 linux kernel, and cloud-hypervisor can start normally.
But when --console pty is set in command line, two cloud-hypervisor processes are started, is this normal?

Using pstree -apnh, one cloud-hypervisor processe is a child process of another cloud-hypervisor

**Comment by rbradford** [comment]
> My host uses the 5.4 linux kernel, and cloud-hypervisor can start normally. But when --console pty is set in command line, two cloud-hypervisor processes are started, is this normal?
>

Yes, you would expect that.

**Comment by Lxiaoyouling** [comment]
> My host uses the 5.4 linux kernel, and cloud-hypervisor can start normally. But when --console pty is set in command line, two cloud-hypervisor processes are started, is this normal?
> 
> Using pstree -apnh, one cloud-hypervisor processe is a child process of another cloud-hypervisor

Sorry, I made a mistake here. My host machine linux version is 5.13

**Comment by rbradford** [comment]
> > My host uses the 5.4 linux kernel, and cloud-hypervisor can start normally. But when --console pty is set in command line, two cloud-hypervisor processes are started, is this normal?
> > Using pstree -apnh, one cloud-hypervisor processe is a child process of another cloud-hypervisor
> 
> Sorry, I made a mistake here. My host machine linux version is 5.13

Upgrading your host kernel from 4.18 to 5.3+ would make the panic go away as the PTY resize logic would be working which calls `clone3()` as part of the process.

**Comment by rbradford** [comment]
@Lxiaoyouling Can you test the patch in #3468 on your older host kernel to avoid the panic.

**Comment by Lxiaoyouling** [comment]
> @Lxiaoyouling Can you test the patch in #3468 on your older host kernel to avoid the panic.

Cloud-hypervisor-v19.0 now works properly in 4.18 linux kernel when use --console pty.
@rbradford Thanks very much.
