### ISSUE TITLE
vfio user device hotplug causes panic on AArch64

### ISSUE THREAD

**Issue by MrXinWang** [cloud-hypervisor/cloud-hypervisor#3479]
When trying to hotplug the SPDK NVME device on AArch64, a "not implemented" panic will happen at the BAR allocation time:
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/3f0a33a50f905b148422019e946a9ca814b0ddee/pci/src/vfio.rs#L437
which looks reasonable as there should be no IO BAR on AArch64.

Tried to add some prints:
```rust
// Is this an IO BAR?
println!("----------vfio: allocate_bars: VFIO_PCI_ROM_REGION_INDEX = {} --------", VFIO_PCI_ROM_REGION_INDEX);
println!("----------vfio: allocate_bars: flags = {} --------", flags);
println!("----------vfio: allocate_bars: flags & PCI_CONFIG_IO_BAR = {} --------", flags & PCI_CONFIG_IO_BAR);
println!("----------vfio: allocate_bars: PCI_CONFIG_IO_BAR = {} --------", PCI_CONFIG_IO_BAR);
let io_bar = if bar_id != VFIO_PCI_ROM_REGION_INDEX {
    matches!(flags & PCI_CONFIG_IO_BAR, PCI_CONFIG_IO_BAR)
} else {
    false
};
```
```
root@ubuntu:~# ----------vfio: allocate_bars: bar_id = 0 --------
----------vfio: allocate_bars: VFIO_PCI_ROM_REGION_INDEX = 6 --------
----------vfio: allocate_bars: flags = 0 --------
----------vfio: allocate_bars: flags & PCI_CONFIG_IO_BAR = 0 --------
----------vfio: allocate_bars: PCI_CONFIG_IO_BAR = 1 --------
----------vfio: allocate_bars: VFIO_PCI_ROM_REGION_INDEX = 6 --------
----------vfio: allocate_bars: flags = 0 --------
----------vfio: allocate_bars: flags & PCI_CONFIG_IO_BAR = 0 --------
----------vfio: allocate_bars: PCI_CONFIG_IO_BAR = 1 --------
----------vfio: allocate_bars: VFIO_PCI_ROM_REGION_INDEX = 6 --------
----------vfio: allocate_bars: flags = 1 --------
----------vfio: allocate_bars: flags & PCI_CONFIG_IO_BAR = 1 --------
----------vfio: allocate_bars: PCI_CONFIG_IO_BAR = 1 --------
thread 'vmm' panicked at 'not implemented', pci/src/vfio.rs:442:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Failed to join on VMM thread: Any { .. }
```

Since I am not quite familiar with the vfio and the SPDK, I would have some questions for the vfio and SPDK experts in the community:
1. Where does the `flags` or the VFIO device config come from, does it come from the VMM or the device? If the config is from the device, is there any method to disable the IO of the SPDK and use MMIO instead?
2. Is IOMMU being a "must" in VFIO/VFIO-user?

Thanks a lot in advance!

**Comment by likebreath** [comment]
Here is my inputs. Please correct me if I am mistaken @sboeuf .

> Where does the flags or the VFIO device config come from, does it come from the VMM or the device?

I think it is from the device (e.g. the SPDK/NVMe backend for this case). The `flags` is from the device's config region through function [`Vfio::read_config()`](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/pci/src/vfio.rs#L264) -> [`Vfio::region_read()`](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/pci/src/vfio_user.rs#L292-L298)(for vfio_user in this case).

> If the config is from the device, is there any method to disable the IO of the SPDK and use MMIO instead?

Good question. I think it is better to ask the SPDK/NVMe maintainers. Can you please open an issue in https://github.com/spdk/spdk and ask about the current support of the SPDK/NVMe on Aarch64 platforms?

>Is IOMMU being a "must" in VFIO/VFIO-user?

I don't think so. Also, I think the `vfio-user` devices (with the `user-device` option) does not even allow to enable `iommu` while you can with VFIO devices (with the `device` option).

**Comment by likebreath** [comment]
Also, have you tried to boot with the SPDK/NVMe device as a cold-plugged vfio-user device (with `--user-device` option)? Does this work for Aarch64?

**Comment by MrXinWang** [comment]
Hi @likebreath, thank you very much for the information, really useful.

> I think it is from the device (e.g. the SPDK/NVMe backend for this case). 

That makes great sense. Then I will try to ask some SPDK experts and see if they know how to use the SPDK properly on Arm64 (I think the SPDK should be supported on Arm64, and it is likely to be a problem of how to use it properly).

>  I think the vfio-user devices (with the user-device option) does not even allow to enable iommu while you can with VFIO devices (with the device option).

Thanks for the clarification, one more thing that I do not need to worry about :)))

> have you tried to boot with the SPDK/NVMe device as a cold-plugged vfio-user device (with --user-device option)? Does this work for Aarch64?

No I didn't, but this is actually a good method and I will definitely try it.
