### ISSUE TITLE
use --console pty start cloud-hypervisor，reboot failed in linux-4.18

### ISSUE THREAD

**Issue by Lxiaoyouling** [cloud-hypervisor/cloud-hypervisor#3496]
**Describe the bug**
Host os version: centos 8.2，host linux kernel version:linux-4.18，cloud-hypervisor version: v20.1

I started a VM using the --console pty, then connected to the VM using screen /dev/pts/***, and  ran reboot in the VM. 
VM reboot failed and the cloud-hypervisor process was killed.

I reported a problem earlier #3456 

**To Reproduce**
(1) cloud-hypervisor --kernel *** vmlinux --disk path=***.raw --cpus boot=2 --memory size=4G --cmdline "root=/dev/vda1 console=ttyS0" --serial tty --api-socket=/tmp/api1 --log-file log.log -vvv --console pty
(2) screen /dev/pts/***
(3) reboot in VM

**Version**
cloud-hypervisor version: v20.1，host os version: centos 8.2，host linux kernel version:linux-4.18

**Logs**
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:50:5
   3: vmm::device_manager::DeviceManager::add_console_device
   4: vmm::device_manager::DeviceManager::create_devices
   5: vmm::vm::Vm::new
   6: vmm::Vmm::vm_reboot
   7: vmm::Vmm::control_loop

I get some information from the output，but I don't know how to fix it.
in vmm/src/device_manager.rs，
fn add_virtio_console_device(
        &mut self,
        virtio_devices: &mut Vec<(VirtioDeviceArc, bool, String, u16)>,
        console_pty: Option<PtyPair>,
        resize_pipe: Option<File>,
    ) -> DeviceManagerResult<Option<Arc<virtio_devices::ConsoleResizer>>> {
    ...
            ConsoleOutputMode::Pty => {
                if let Some(pty) = console_pty {                             // execute here on reboot                      
                    info!("lzx add_virtio_console_device console_pty");
                    self.config.lock().unwrap().console.file = Some(pty.path.clone());
                    let file = pty.main.try_clone().unwrap();
                    self.console_pty = Some(Arc::new(Mutex::new(pty)));
                    self.console_resize_pipe = Some(Arc::new(resize_pipe.unwrap()));
                    Endpoint::FilePair(file.try_clone().unwrap(), file)
                } else {                                                                    // execute here on start
                    info!("lzx add_virtio_console_device else 2");
                    let (main, mut sub, path) =
                        create_pty(false).map_err(DeviceManagerError::ConsolePtyOpen)?;
                    self.set_raw_mode(&mut sub)
                        .map_err(DeviceManagerError::SetPtyRaw)?;
                    self.config.lock().unwrap().console.file = Some(path.clone());
                    let file = main.try_clone().unwrap();
                    assert!(resize_pipe.is_none());
                    self.listen_for_sigwinch_on_tty(&sub).unwrap();
                    self.console_pty = Some(Arc::new(Mutex::new(PtyPair { main, sub, path })));
                    Endpoint::FilePair(file.try_clone().unwrap(), file)
                }
            }
    ...
}

**Comment by Lxiaoyouling** [comment]
I annotation self.console_resize_pipe = Some(Arc::new(resize_pipe.unwrap())); ，reboot work normally. Are there any hidden dangers in doing this?

`            ConsoleOutputMode::Pty => {
                if let Some(pty) = console_pty {
                    self.config.lock().unwrap().console.file = Some(pty.path.clone());
                    let file = pty.main.try_clone().unwrap();
                    self.console_pty = Some(Arc::new(Mutex::new(pty)));
                    //self.console_resize_pipe = Some(Arc::new(resize_pipe.unwrap()));      // annotation here
                    Endpoint::FilePair(file.try_clone().unwrap(), file)
                } else {
                    let (main, mut sub, path) =
                        create_pty(false).map_err(DeviceManagerError::ConsolePtyOpen)?;
                    self.set_raw_mode(&mut sub)
                        .map_err(DeviceManagerError::SetPtyRaw)?;
                    self.config.lock().unwrap().console.file = Some(path.clone());
                    let file = main.try_clone().unwrap();
                    assert!(resize_pipe.is_none());
                    self.listen_for_sigwinch_on_tty(&sub).unwrap();
                    self.console_pty = Some(Arc::new(Mutex::new(PtyPair { main, sub, path })));
                    Endpoint::FilePair(file.try_clone().unwrap(), file)
                }
            }`

**Comment by Lxiaoyouling** [comment]
I annotation self.console_resize_pipe = Some(Arc::new(resize_pipe.unwrap())); ，reboot work normally. Are there any hidden dangers in doing this?

ConsoleOutputMode::Pty => { 
    if let Some(pty) = console_pty { 
        self.config.lock().unwrap().console.file = Some(pty.path.clone()); 
        let file = pty.main.try_clone().unwrap(); 
        self.console_pty = Some(Arc::new(Mutex::new(pty))); 
        //self.console_resize_pipe = Some(Arc::new(resize_pipe.unwrap())); // annotation here 
       Endpoint::FilePair(file.try_clone().unwrap(), file) 
    } else { 
        let (main, mut sub, path) = create_pty(false).map_err(DeviceManagerError::ConsolePtyOpen)?; 
        self.set_raw_mode(&mut sub) .map_err(DeviceManagerError::SetPtyRaw)?; 
        self.config.lock().unwrap().console.file = Some(path.clone()); 
        let file = main.try_clone().unwrap(); assert!(resize_pipe.is_none()); 
        self.listen_for_sigwinch_on_tty(&sub).unwrap(); 
        self.console_pty = Some(Arc::new(Mutex::new(PtyPair { main, sub, path }))); 
        Endpoint::FilePair(file.try_clone().unwrap(), file) 
    } 
}

**Comment by rbradford** [comment]
Please test #3527.
