### ISSUE TITLE
vsock: unexpected EWOULDBLOCK while reading from backing stream

### ISSUE THREAD

**Issue by jackloomen** [cloud-hypervisor/cloud-hypervisor#3497]
cloud-hypervisor v20.1.0

--vsock cid=3,socket=/path/v.sock

Reproduced with streaming uncompressed video/assets over waypipe (wayland over sockets)
Frequency of occurrence depends on size of window (and therefore bandwidth)

On host:
waypipe --socket /path/v.sock_5000 client &

On guest:
socat UNIX-LISTEN:/tmp/waypipe-server.sock,reuseaddr,fork VSOCK-CONNECT:2:5000,forever &
waypipe --no-gpu --socket /tmp/waypipe-server.sock --control /tmp/waypipe-ctrl.pipe --display /tmp/wayland-0 server -- sleep inf &
WAYLAND_DISPLAY=/tmp/wayland-0 mpv /path/to/4k_video.mp4

```
cloud-hypervisor: 1155.939756072s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.142021665s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.1425842s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.143808813s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.189278481s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.412921305s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.563153059s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
cloud-hypervisor: 1156.564757199s: <_vsock2> WARN:virtio-devices/src/vsock/csm/connection.rs:239 -- vsock: unexpected EWOULDBLOCK while reading from backing stream: lp=2000, pp=630240254, err=Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
```
This times 1000.

**Comment by sboeuf** [comment]
Hi @jackloomen 
Have you tried this with `firecracker`? I'm asking because the `vsock` device has been ported from the firecracker repository and this might be a common issue that would be better to fix there and then backport to Cloud Hypervisor.
That being said, if the issue is specific to Cloud Hypervisor, I'll be happy to look into it.

**Comment by andreeaflorescu** [comment]
We fixed a few months ago a problem with the vsock (not sure if it's the same one), but you can check this commit: https://github.com/firecracker-microvm/firecracker/commit/38bc78bd66d0bf410f26026426505e3e748d6634.

Btw, we are now looking at upstreaming the vsock building blocks as part of rust-vmm. We will soon publish a design document. @sboeuf do you think you could also take a look?

**Comment by sboeuf** [comment]
>Btw, we are now looking at upstreaming the vsock building blocks as part of rust-vmm. We will soon publish a design document. @sboeuf do you think you could also take a look?

Definitely! Sounds great!

**Comment by sboeuf** [comment]
@jackloomen could you have a quick try with https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3517 and let me know if that fixes the issue for you?

**Comment by jackloomen** [comment]
> @jackloomen could you have a quick try with #3517 and let me know if that fixes the issue for you?

After applying the patch to 20.1 the issue could not be reproduced.

**Comment by lauralt** [comment]
> > Btw, we are now looking at upstreaming the vsock building blocks as part of rust-vmm. We will soon publish a design document. @sboeuf do you think you could also take a look?
> 
> Definitely! Sounds great!

Hi @sboeuf; I just opened [an issue](https://github.com/rust-vmm/vm-virtio/issues/128) with a proposal for the vsock packet abstraction. Can you also have a look? Thank you!
