### ISSUE TITLE
vhost-user-blk migration failed

### ISSUE THREAD

**Issue by Lxiaoyouling** [cloud-hypervisor/cloud-hypervisor#3503]
**Describe the bug**
vhost-user-blk migration failed.
When I executed ch-remote send-migration, migration process hang.

**To Reproduce**
spdk:
(1) HUGEMEM=2048 scripts/setup.sh
(2) ./build/bin/vhost -S /var/tmp -s 1024 -m 0x3 &
(3) scripts/rpc.py bdev_malloc_create 512 512 -b Malloc0
(4) scripts/rpc.py vhost_create_blk_controller --cpumask 0x1 vhost.1 Malloc0
cloud-hypervisor
(5) ./cloud-hypervisor --kernel /vm_data/cloud-hypervisor/hypervisor-fw --disk path=/vm_data/cloud-hypervisor/focal-server-cloudimg-amd64.raw vhost_user=true,socket=/var/tmp/vhost.1,num_queues=2,queue_size=128 --cpus boot=4 --memory size=1024M,hugepages=on,shared=true --cmdline "console=ttyS0 root=/dev/vda1 rw iommu=off" --serial tty --console off --api-socket=/tmp/api1 --log-file log.log -vvv
(6) execute migration

**Version**
spdk: v21.10-rc1, commit 9e4350b6fb615b5499d8a2a623c9bda5885f92cc
cloud-hypervisor: v20.1, commit d7ba8ad1faf37b3e29af9d8a6c12d116bd6f083e
os: Ubuntu 18.04.5 LTS
linux kernel version: 5.4.0-91-generic

**Logs**
destination cloud-hypervisor log:
cloud-hypervisor: 9.242298547s: <vmm> INFO:vmm/src/lib.rs:1283 -- API request event: VmReceiveMigration(VmReceiveMigrationData { receiver_url: "unix:/tmp/sock45" }, Sender { .. })
cloud-hypervisor: 9.242364925s: <vmm> INFO:vmm/src/lib.rs:874 -- Receiving migration: receiver_url = unix:/tmp/sock45
cloud-hypervisor: 11.832514229s: <vmm> INFO:vmm/src/lib.rs:1283 -- API request event: VmReceiveMigration(VmReceiveMigrationData { receiver_url: "unix:/tmp/sock47" }, Sender { .. })
cloud-hypervisor: 11.832565612s: <vmm> INFO:vmm/src/lib.rs:874 -- Receiving migration: receiver_url = unix:/tmp/sock47
cloud-hypervisor: 85.059848533s: <vmm> INFO:vmm/src/lib.rs:898 -- Start Command Received
cloud-hypervisor: 85.060001597s: <vmm> INFO:vmm/src/lib.rs:904 -- Config Command Received
cloud-hypervisor: 85.060153453s: <vmm> INFO:arch/src/x86_64/mod.rs:552 -- No CPU incompatibility detected.
cloud-hypervisor: 85.060477223s: <vmm> INFO:vmm/src/memory_manager.rs:1447 -- Creating userspace mapping: 0 -> 7ffb9c000000 40000000, slot 1
cloud-hypervisor: 85.060697005s: <vmm> INFO:vmm/src/memory_manager.rs:1481 -- Created userspace mapping: 0 -> 7ffb9c000000 40000000
cloud-hypervisor: 85.060750609s: <vmm> INFO:vmm/src/vm.rs:541 -- Booting VM from config: Mutex { data: VmConfig { cpus: CpusConfig { boot_vcpus: 4, max_vcpus: 4, topology: None, kvm_hyperv: false, max_phys_bits: 46, affinity: None },
 memory: MemoryConfig { size: 1073741824, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: true, hugepages: true, hugepage_size: None, prefault: false, zones: None }, kernel: Some(KernelConfi
g { path: "/vm_data/cloud-hypervisor/hypervisor-fw" }), initramfs: None, cmdline: CmdlineConfig { args: "console=ttyS0 root=/dev/vda1 rw iommu=off" }, disks: Some([DiskConfig { path: Some("/vm_data/cloud-hypervisor/focal-server-cloud
img-amd64.raw.1"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: Some("_disk0"), disable_io_uring: false, pci_seg
ment: 0 }, DiskConfig { path: None, readonly: false, direct: false, iommu: false, num_queues: 2, queue_size: 128, vhost_user: true, vhost_socket: Some("/var/tmp/vhost.1"), poll_queue: true, rate_limiter_config: None, id: Some("_disk1
"), disable_io_uring: false, pci_segment: 0 }]), net: None, rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Tty, iommu: false }, console: ConsoleCon
fig { file: None, mode: Off, iommu: false }, devices: None, user_devices: None, vsock: None, iommu: false, sgx_epc: None, numa: None, watchdog: false, platform: None }, poisoned: false, .. }
cloud-hypervisor: 85.061806278s: <vmm> INFO:vmm/src/pci_segment.rs:92 -- Adding PCI segment: id=0, PCI MMIO config address: 0xe8000000, device area [0x100000000-0x7effffffff

spdk:
When start cloud-hypervisor:
VHOST_CONFIG: new vhost user connection is 536
VHOST_CONFIG: new device, handle is 0
VHOST_CONFIG: read message VHOST_USER_SET_OWNER
VHOST_CONFIG: read message VHOST_USER_GET_FEATURES
VHOST_CONFIG: read message VHOST_USER_GET_PROTOCOL_FEATURES
VHOST_CONFIG: read message VHOST_USER_SET_PROTOCOL_FEATURES
VHOST_CONFIG: negotiated Vhost-user protocol features: 0x120b
VHOST_CONFIG: read message VHOST_USER_GET_QUEUE_NUM
VHOST_CONFIG: read message VHOST_USER_SET_FEATURES
VHOST_CONFIG: negotiated Virtio features: 0x150007646
VHOST_CONFIG: read message VHOST_USER_SET_MEM_TABLE
VHOST_CONFIG: guest memory region size: 0x40000000
         guest physical addr: 0x0
         guest virtual  addr: 0x7f4ee4000000
         host  virtual  addr: 0x7f4904000000
         mmap addr : 0x7f4904000000
         mmap size : 0x40000000
         mmap align: 0x200000
         mmap off  : 0x0
VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
VHOST_CONFIG: read message VHOST_USER_GET_INFLIGHT_FD
VHOST_CONFIG: get_inflight_fd num_queues: 2
VHOST_CONFIG: get_inflight_fd queue_size: 128
VHOST_CONFIG: send inflight mmap_size: 4224
VHOST_CONFIG: send inflight mmap_offset: 0
VHOST_CONFIG: send inflight fd: 541
VHOST_CONFIG: read message VHOST_USER_SET_INFLIGHT_FD
VHOST_CONFIG: set_inflight_fd mmap_size: 4224
VHOST_CONFIG: set_inflight_fd mmap_offset: 0
VHOST_CONFIG: set_inflight_fd num_queues: 2
VHOST_CONFIG: set_inflight_fd queue_size: 128
VHOST_CONFIG: set_inflight_fd fd: 542
VHOST_CONFIG: set_inflight_fd pervq_inflight_size: 2112
VHOST_CONFIG: read message VHOST_USER_SET_VRING_ADDR
VHOST_CONFIG: read message VHOST_USER_SET_VRING_BASE
VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:0 file:541
VHOST_CONFIG: read message VHOST_USER_SET_VRING_KICK
VHOST_CONFIG: vring kick idx:0 file:543
VHOST_CONFIG: read message VHOST_USER_SET_VRING_ADDR
VHOST_CONFIG: read message VHOST_USER_SET_VRING_BASE
VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:1 file:544
VHOST_CONFIG: read message VHOST_USER_SET_VRING_KICK
VHOST_CONFIG: vring kick idx:1 file:545
VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
VHOST_CONFIG: set queue enable: 1 to qp idx: 0
VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
VHOST_CONFIG: set queue enable: 1 to qp idx: 1
VHOST_CONFIG: virtio is now ready for processing.

When execute send-migration:
VHOST_CONFIG: read message VHOST_USER_SET_LOG_BASE
VHOST_CONFIG: log mmap size: 32768, offset: 0

**Comment by Lxiaoyouling** [comment]
It's stuck in the update_log_base function，in virtio-devices/src/vhost_user/vu_common_ctrl.rs.
fn update_log_base(&mut self, last_ram_addr: u64) -> Result<Option<Arc<MmapRegion>>> {
...
self.vu
            .set_log_base(0, Some(log))
            .map_err(Error::VhostUserSetLogBase)?;
...
}

**Comment by sboeuf** [comment]
Hi @Lxiaoyouling 
Have you found a way to fix the issue? If this is a fix that can benefit everybody, feel free to open a pull request on the `cloud-hypervisor` repository :)
