### ISSUE TITLE
Add support for ACPI based PCI hotplug

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#353]
Implement PCI hotplug using ACPI. Depends on: #352

**Comment by sboeuf** [comment]
Just summarizing the offline discussion:
- As a first step, we want to support hotplug of `vfio-pci` devices as this should be more straightforward.
  - [ ] Implement ACPI missing parts (update DSDT table and GED device)
  - [ ] Update OpenAPI with `add-device` command, which will trigger the creation of a new VFIO device
- As a second step, and once the validation that hotplugging VFIO devices works correctly, we want to tackle virtio devices. Therefore, for each virtio device we need to:
  - [ ] Keep track of existing backend related to the virtio device
  - [ ] Update OpenAPI with a new command `add-...` related to the device
  - [ ] Validate that the parameters to create the new virtio device don't conflict with existing devices

**Comment by rbradford** [comment]
virtio-net/pmem/block can now be plugged and unplugged thanks to #1030 and #954, #964, #960
