### ISSUE TITLE
vmm: net: can't use file descriptors for the `tuntap` device

### ISSUE THREAD

**Issue by fidencio** [cloud-hypervisor/cloud-hypervisor#3554]
**Describe the bug**

When used with Kata Containers, the virtio-net device is always created using the `tap` field of the `NetConfig` structure, even when this is not set, completely ignoring file descriptors of an already opened device.

[Although we have code that only tries to create the `tuntap` device using the `tap` field only when it's set, fallbacking to using file descriptors if those are set](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/6738e45b37968ffaddd6a338021db953325fd5da/vmm/src/device_manager.rs#L2161-L2217), the code does **not** work when used with Kata Containers.

The reason the code doesn't work is because the client code, a golang code, [initialises the NetConfig structure as shown below](https://github.com/kata-containers/kata-containers/blob/97e18cf2d0d1a83b139c5117299c1766b6365a22/src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go#L39-L58):
```
func NewNetConfig() *NetConfig {
	this := NetConfig{}
	var tap string = ""
	this.Tap = &tap
	var ip string = "192.168.249.1"
	this.Ip = &ip
	var mask string = "255.255.255.0"
	this.Mask = &mask
	var iommu bool = false
	this.Iommu = &iommu
	var numQueues int32 = 2
	this.NumQueues = &numQueues
	var queueSize int32 = 256
	this.QueueSize = &queueSize
	var vhostUser bool = false
	this.VhostUser = &vhostUser
	var vhostMode string = "Client"
	this.VhostMode = &vhostMode
	return &this
}
```

Looking at that it's simple to understand that `tap` will never ever be **None**, but rather an `empty` `Some`, and that this case should be properly treated (probably?) on the cloud-hypervisor side.

**To Reproduce**
I don't have a simple reproducer handy, but I've been working on passing the file descriptors down to cloud-hypervisor as part of https://github.com/fidencio/kata-containers/tree/wip/clh-selinux, but that's still a work-in-progress as there are more things to check and fix (including this issue), before submitting that branch as a PR for Kata Containers.

**Version**

Output of `cloud-hypervisor --version`:
```
$ cloud-hypervisor --version
cloud-hypervisor v20.0.0
```

The binary used was downloaded from the project's GitHub.  Looking at the code, the issue is still present on `main`.

**VM configuration**

What command line did you run (or JSON config data):
```
{'cmdline': {'args': 'root=/dev/pmem0p1 panic=1 no_timer_check noreplace-smp rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 quiet systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket'},
 'console': {'iommu': False, 'mode': 'Off'},
 'cpus': {'boot_vcpus': 1,
  'max_vcpus': 4,
  'topology': {'cores_per_die': 4,
   'dies_per_package': 1,
   'packages': 1,
   'threads_per_core': 1}},
 'fs': [{'cache_size': 0,
   'dax': False,
   'num_queues': 1,
   'queue_size': 1024,
   'socket': '/run/vc/vm/688ada6f50b88115d6f0d86e760a8419fde09158fbe57f227a677c69a765c7e2/virtiofsd.sock',
   'tag': 'kataShared'}],
 'iommu': False,
 'kernel': {'path': '/usr/share/kata-containers/vmlinux.container'},
 'memory': {'hotplug_method': 'Acpi',
  'hotplug_size': 16601276416,
  'hugepages': False,
  'mergeable': False,
  'prefault': False,
  'shared': True,
  'size': 2147483648},
 'net': [{'fd': [19],
   'iommu': False,
   'ip': '192.168.249.1',
   'mac': '7e:4e:c8:dd:1c:d1',
   'mask': '255.255.255.0',
   'num_queues': 2,
   'queue_size': 256,
   'tap': '',
   'vhost_mode': 'Client',
   'vhost_user': False}],
 'pmem': [{'discard_writes': True,
   'file': '/usr/share/kata-containers/kata-containers.img',
   'iommu': False,
   'mergeable': False}],
 'rng': {'iommu': False, 'src': '/dev/urandom'},
 'serial': {'iommu': False, 'mode': 'Off'},
 'vsock': {'cid': 3,
  'iommu': False,
  'socket': '/run/vc/vm/688ada6f50b88115d6f0d86e760a8419fde09158fbe57f227a677c69a765c7e2/clh.sock'},
 'watchdog': False}
```

Guest OS version details:
Not relevant

Host OS version details:
Not relevant

**Logs**
`kubectl describe pod` shows me:
```
  Warning  FailedCreatePodSandBox  6s (x23 over 4m53s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: error: 500  reason: VmBoot(VmBoot(DeviceManager(CreateVirtioNet(OpenTap(TapGetMac(IoctlError(Os { code: 19, kind: Uncategorized, message: "No such device" }))))))): unknown
```

**Comment by fidencio** [comment]
@rbradford, please, assign this issue to me as I already am testing a possible fix for this one.

Also, I'm opening a more generic issue as we may need to ensure other parts of the integration with Kata Containers won't hit similar issues.

**Comment by rbradford** [comment]
@fidencio The `tap` field is already an `Option<String>`. I think the bug is in the Kata side for providing an empty string rather than not specifying the field at all. When the field is not specified the default should be `None` from: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/70af81d755ad1f961684cf6bf7a57f9e9674bb45/vmm/src/config.rs#L1082

IIRC the Go JSON code will map `nil` to not specifying the field so the correct fix is to remove 

```	
var tap string = ""
this.Tap = &tap
```

**Comment by fidencio** [comment]
> @fidencio The `tap` field is already an `Option<String>`. I think the bug is in the Kata side for providing an empty string rather than not specifying the field at all. When the field is not specified the default should be `None` from:
> 
> https://github.com/cloud-hypervisor/cloud-hypervisor/blob/70af81d755ad1f961684cf6bf7a57f9e9674bb45/vmm/src/config.rs#L1082
> 
> IIRC the Go JSON code will map `nil` to not specifying the field so the correct fix is to remove
> 
> ```
> var tap string = ""
> this.Tap = &tap
> ```
> 
> If you want to use file descriptors.

@rbradford, https://github.com/kata-containers/kata-containers/blob/97e18cf2d0d1a83b139c5117299c1766b6365a22/src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go#L39-L58 is auto generated by openapi-generator tool, so the error is probably coming from there.

I have a possible work-around for that on the cloud-hypervisor side (spoiler, not tested yet: https://github.com/fidencio/cloud-hypervisor/commit/52ff240853da1c22cb40ac604d6e9b2c6314a0f8), but I totally agree that it'd be papering over a semantic issue we actually have with the openapi-generator.  Please, let's keep this one open while I also investigate what can be done on the Open API side.

**Comment by rbradford** [comment]
Testing for the empty string will break the recommended "I don't care what tap interface name I get" for `--net tap=` on the command line.

**Comment by fidencio** [comment]
> Testing for the empty string will break the recommended "I don't care what tap interface name I get" for `--net tap=` on the command line.

Aha, I was not aware of `--net tap=`.

It seems the openapi-generator is the part to fix.  I am closing the issue here and I will point it out on the issue opened on the openapi-generator side.

Thanks for the input @rbradford.
