### ISSUE TITLE
Abandoned vfio-ioctls as dependency

### ISSUE THREAD

**Issue by blitz** [cloud-hypervisor/cloud-hypervisor#3673]
**Describe the bug**

cloud-hypervisor uses the abandoned [vfio-ioctls](https://github.com/rust-vmm/vfio-ioctls) crate as a dependency. This crate will never be updated anymore. This is a security problem.

It looks like this crate was replaced by: https://github.com/rust-vmm/vfio

**Version**

All versions up to master (e5bc5e632d159dbe82e3865034ee294498f9b34a).

**Comment by sboeuf** [comment]
Good catch, I'll fix ASAP.

**Comment by sboeuf** [comment]
> Good catch, I'll fix ASAP.

It's actually a bit more complicated than that since the `mshv` feature hasn't been re-enabled yet on `rust-vmm/vfio`.
There's a discussion there: https://github.com/rust-vmm/vfio/pull/3
