### ISSUE TITLE
Unify virtio-net and vhost-user-net code

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#368]
The code in the vhost-user-net code is mostly a duplicate of the virtio-net code with the exception that the `Vring` is passed into the functions rather than accessed through a member.

This might well require refactoring of the generic virtio code to have the ring external but that will also accelerate the implementation of #173 as it will also be derived from the virtio-blk code.

**Comment by bjzhjing** [comment]
[Factorize vm-virtio duplicated code #214 ]( #214 )
