### ISSUE TITLE
Analyse performance gaps with QEMU's virtio-net implementation

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#369]
Non-vhost, not-multiqeue QEMU:

```
qemu-system-x86_64 -machine q35,accel=kvm,kernel_irqchip -cpu host -m 512 -bios ~/Downloads/OVMF.fd -device virtio-blk-pci,drive=root -drive if=none,id=root,file=/home/rob/workloads/clear-30800-kvm.img -nodefaults -device virtio-net-pci,netdev=mynet0 -netdev tap,id=mynet0,ifname=tap0,script=no,downscript=no,vhost=off -serial stdio
```

iperf3 result:

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  26.3 GBytes  22.6 Gbits/sec    0             sender
[  5]   0.00-10.00  sec  26.3 GBytes  22.6 Gbits/sec                  receiver
```

vs CH with virtio-net:

```
target/debug/cloud-hypervisor  --kernel ~/src/rust-hypervisor-firmware/target/target/release/hypervisor-fw --serial tty --console off --disk path=~/workloads/clear-30800-kvm.img --net tap=tap0,mac=12:34:56:78:90:ab --memory size=512M
```

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  9.25 GBytes  7.94 Gbits/sec    0             sender
[  5]   0.00-10.00  sec  9.25 GBytes  7.94 Gbits/sec                  receiver
```

i.e. Cloud Hypervisor's peformance is ~ 35% of QEMU.

**Comment by ZideChen0** [comment]
Probably you can try target/release/cloud-hypervisor. In my setup, it's iperf throughput is closed to QEMU.

**Comment by bjzhjing** [comment]
Awesome! I run the same case, and yes, the release version will gain better performance result. Refer to the following link https://doc.rust-lang.org/book/ch14-01-release-profiles.html, it seems to be caused by the compiler optimization level while compile code. For the debug version, the default opt-level is 0, while for release version, it's 3.

**Comment by bjzhjing** [comment]
Start 2 VMs with vhost-user-net device, connecting to vhost-user ports provided by OVS + DPDK, run iperf3 -s and iperf3 -c respectively on each of them, not-multiple queue. cloud-hypervisor is running with release version. Here is the result:

qemu (server) - qemu (sender)
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  16.7 GBytes  14.3 Gbits/sec  107778             sender
[  5]   0.00-10.04  sec  16.7 GBytes  14.3 Gbits/sec                  receiver

cloud-hypervisor (server) - cloud-hypervisor (sender)
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  13.7 GBytes  11.8 Gbits/sec  68605             sender
[  5]   0.00-10.04  sec  13.7 GBytes  11.7 Gbits/sec                  receiver

cloud-hypervisor (server) - qemu (client)
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  14.9 GBytes  12.8 Gbits/sec  73405             sender
[  5]   0.00-10.04  sec  14.9 GBytes  12.8 Gbits/sec                  receiver

cloud-hypervisor (client) - qemu (server)
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  16.4 GBytes  14.1 Gbits/sec  113077             sender
[  5]   0.00-10.04  sec  16.4 GBytes  14.0 Gbits/sec                  receiver

For transmit direction, cloud-hypervisor with vhost-user-net device has a similar performance with qemu, but for receive direction, cloud-hypervisor with vhost-user-net device has performance dropped compared to qemu.

**Comment by bjzhjing** [comment]
Change rx/tx queue_size to be 1024 in both qemu and cloud-hypervisor. Do the same simple test with iperf3, get the following performance result.

> cloud-hypervisor vm (client) -> cloud-hypervisor vm (server)

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  15.2 GBytes  13.1 Gbits/sec  1896             sender
[  5]   0.00-10.04  sec  15.2 GBytes  13.0 Gbits/sec                  receiver
```

> qemu vm (client) -> qemu vm (server)

```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  16.4 GBytes  14.0 Gbits/sec  3835             sender
[  5]   0.00-10.04  sec  16.4 GBytes  14.0 Gbits/sec                  receiver
```
get a similar performance, there is ~7% performance gap.

**Comment by sboeuf** [comment]
@bjzhjing @rbradford we might need to change the default queue size. 256 is not enough IMO. And I'm thinking we should add some option so that the user can specify the queue size.

**Comment by bjzhjing** [comment]
@sboeuf Change rx/tx queue_size to be 1024 is for vhost-user-net, not for virtio-net, virtio-net is still with 256. The interesting thing I noticed is that the change for queue_size has no effect on qemu with vhost-user-net, but increase the performance of cloud-hypervisor with vhost-user-net. Not sure if it's related the language itself, or caused by memory handling, or any other element.

**Comment by sboeuf** [comment]
@bjzhjing ok but I think @rbradford was trying with `virtio-net`, so it'd be interesting to look at the gain if we were bumping to 1024 as the default.
And actually I think we should bump to 1024 by default for all virtio devices.

**Comment by sboeuf** [comment]
@rbradford @bjzhjing FYI, I opened #646 to increase the default queue size to 1024.

**Comment by rbradford** [comment]
See #1731
