### ISSUE TITLE
cannot use ovmf release from cloud-hypervisor/edk2 repo with cloud-hypervisor on x86_64

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/cloud-hypervisor#3696]
**Describe the bug**
CLOUDHV.fd published at https://github.com/cloud-hypervisor/edk2/releases/tag/ch-cad5f05068 cannot be used with cloud-hypervisor on x86_64 arch.

```

$ file CLOUDHV.fd
CLOUDHV.fd: data

$ md5sum CLOUDHV.fd
cd452718dae08838d525ae4d28f7372c  CLOUDHV.fd
```

I compiled the binary using **cad5f05068** commit in **cloud-hypervisor/edk2** repo. The resultant file format is of "data" format which cloud-hypervisor doesn't accept for _--kernel_ argument.

**To Reproduce**

1) git checkout cad5f05068  in cloud-hypervisor/edk2 repo.
2) OvmfPkg/build.sh -p OvmfPkg/CloudHv/CloudHvX64.dsc -a X64 -b DEBUG  # Build OVMF
```

$ file Build/CloudHvX64/DEBUG_GCC5/FV/CLOUDHV_CODE.fd
Build/CloudHvX64/DEBUG_GCC5/FV/CLOUDHV_CODE.fd: data

```

**Comment by sboeuf** [comment]
The generated binary is `edk2/Build/CloudHvX64/DEBUG_GCC5/FV/CLOUDHV.fd`, which contains `data`.
But this is supported by Cloud Hypervisor since version `v20.0`. You might be using an older version.

**Comment by rbradford** [comment]
Looks like @praveen-pk was using the wrong file from the FV directory.

**Comment by praveen-pk** [comment]
Thanks for the prompt response. I was using v16.0, confirmed I can use the firmware with v20.0.
