### ISSUE TITLE
ch-remote info subcommand pci devices pci_bdf need to be human stylized

### ISSUE THREAD

**Issue by Marshalzxy** [cloud-hypervisor/cloud-hypervisor#3711]
My cloud hypervisor and ch-remote are 21.0 .
When I used ch-remote info subcommand to dump my vm infomation, I found that pci device's pci_bdf field was not
human readable.
It is dump was u32, which is machine style.
Is that possible to show pci_bdf field  of pic devices as bus:device:function format in ch-remote ?
For example 00:09:01 ?

**Comment by sboeuf** [comment]
That's very good feedback, we'll address it as soon as possible.
