### ISSUE TITLE
RFC: Exclusively test virtiofsd-rs

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3729]
Our current virtiofsd (C based) testing is based on an old branch: https://gitlab.com/virtio-fs/qemu/-/tree/qemu5.0-virtiofs-dax. This has since been moved into QEMU proper and also deprecated in favour of the Rust based one:https://gitlab.com/stefanha/qemu/-/commit/34deee7b6a1418f3d62a91ff0a9d156e60a788a5

Currently Kata is using the version from within qemu which is newer than what we test and is working to move towards the Rust version:https://github.com/kata-containers/kata-containers/issues/3036

Since they already have integration test coverage of the C based virtiofsd rather than try and move our testing to a newer version that is already deprecated we should drop our virtiofsd testing.

**Comment by fidencio** [comment]
I've discussed this with @rbradford, and knowing that Kata Containers will move to the rust version of virtiofsd in a few weeks (as soon as we start the 2.5 development cycle) this sounds like the right move.

**Comment by sboeuf** [comment]
That makes lots of sense. This will simplify our testing matrix.
It's nice to see the move to the Rust version happening, and since Kata Containers is the only project we know of that is using both Cloud Hypervisor and `virtio-fs`, we should be good to go!
