### ISSUE TITLE
ACPI: AARCH64: PPTT table isn't filled correctly

### ISSUE THREAD

**Issue by weltling** [cloud-hypervisor/cloud-hypervisor#3733]
The issue is observed with Windows 11 IoT guest, where just passing `--cpu boot=3` isn't sufficient and would lead to an OS crash. The guest would expect the PPTT table to be present, however it would be only generated if an explicit topology argument has been passed. See the current implementation at https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/arch/src/aarch64/fdt.rs#L222 .

According to the ARM Base Requirements 1.0 document:

```
8.3.1 Mandatory ACPI tables
...................................
8.3.1.10 PPTT
• Processor Properties Topology Table (PPTT), ACPI § 5.2.29.
o This table describes the topological structure of processors that are controlled by the OSPM and 
their shared resources.
```
Thus, this table is required for the compliance with this specification and its absence is to be seen as a bug. A meaningful topology might need to be generated, even if none has been passed explicitly, in order PPTT table to be filled correctly. Also, compared to x86_64, no explicit CPU topology argument should be required.

/cc @liuw @michael2012z @MrXinWang @jongwu 

Thanks

**Comment by liuw** [comment]
Can you try this untested patch? https://github.com/liuw/cloud-hypervisor/commit/f2eebbe939c9dafc8e31c5fa2387b1b7543e95d9

**Comment by michael2012z** [comment]
@weltling What happen if you remove the whole PPTT table here: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/5d55070ceb0d1be616d425363d96613be5680c6c/vmm/src/acpi.rs#L625 ?

**Comment by michael2012z** [comment]
Aha, you found a bug in building PPTT. Good catch.

I created a PR to fix the error. The solution is to apply a default VCPU topology in PPTT when not specified. Could you try it?

Alternative solution could be omitting PPTT totally if topology is not set. But I am not sure if Windows 11 works that way.

**Comment by weltling** [comment]
Thanks for the quick checking. Wei, Michael, it looks like both patches go into the same direction, so we'd probably be fine focusing on the latest PR state. I'll check the patch on the PR and post a feedback there.

Thanks
