### ISSUE TITLE
`local` field of `SendMigrationData` should be required in open-api spec

### ISSUE THREAD

**Issue by fengye87** [cloud-hypervisor/cloud-hypervisor#3756]
It seems that a new field `local` has been added to `SendMigrationData` in API since recent releases. When calling `send-migration` API without this new field, the server would return an error saying SerdeJsonDeserialize(Error(\"missing field `local`\", line: 1, column: 54)). Due to this behaviour, this field should really be marked as required in the open-api spec (I'm using this open-api spec to generate Golang client-side code, so I'm depending on this doc's accuracy here). Or if this behaviour is not intended, maybe we should then change the server implementation to make it optional and false by default.

Would like to send a PR here, just let me know which way to go.

**Comment by rbradford** [comment]
I think you can default it to off:

```rust
#[derive(Clone, Deserialize, Serialize, Default, Debug)]
pub struct VmSendMigrationData {
    /// URL to migrate the VM to
    pub destination_url: String,
    /// Send memory across socket without copying
    #[serde(default)]
    pub local: bool,
}
```

And then including it in the openapi yaml file as optional (i.e. not `required`)

**Comment by fengye87** [comment]
@rbradford Thanks for your suggestion. I've opened a PR to do what you said above, care to give it a review?
