### ISSUE TITLE
scripts: `--test-filter` doesn't work with `dev_cli.sh`

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#3787]
I was using the following:
```
./scripts/dev_cli.sh tests --metrics -- --test-filter boot_time_
```
hoping it would run both `boot_time_s` and `boot_time_pmem_s` from the metrics CI, but it ran every single test.
This needs to be fixed.

**Comment by likebreath** [comment]
The above command does not work as expected, as the options provided after the first `--` (like the `--test-filter` above) to "dev_cli.sh" are for the test scripts (e.g. "run_integration_*.sh", "run_metrics.sh", etc). To pass arguments to the test binary (e.g. `cargo test` or `performance-metrics`), we need to provide these arguments after the __second__ `--` to "dev_cli.sh". 

@sboeuf Can you please try the following command and see whether it works as expected? 
`$ ./scripts/dev_cli.sh tests --metrics -- -- --test-filter boot_time_`. 

This [commit message](https://github.com/cloud-hypervisor/cloud-hypervisor/commit/4552d07a80dcdd93cf4ff8c466592a36497d0c51) contains some more details of the 'dev_cli.sh' CLI syntax with few examples. Also, here is the context why it was designed in this way ( https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3752#discussion_r813421044 and https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3752#discussion_r813424522). I can understand the current CLI syntax can be confusing at the first glance. Any ideas to improve it, please don't hesitate to share. Thank you.

**Comment by rbradford** [comment]
@likebreath You're not wrong but it is also inconsistent with the integration test scripts that use it in that position. The argument is being parsed and placed in the `test_filter` variable so it should be honoured.

**Comment by likebreath** [comment]
That makes sense. Opened PR #3803 to achieve the desired behavior with some explanations and exmaples.
