### ISSUE TITLE
Move to released `vm-virtio` and `vhost-user-backend`

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3800]
See https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3798#issuecomment-1058305434

We should move to some new released versions to avoid turbulence!

**Comment by rbradford** [comment]
@sboeuf Please open issues with these crates to get new releases made.

**Comment by sboeuf** [comment]
Yes let me handle that.

**Comment by sboeuf** [comment]
Here are the issues:
- https://github.com/rust-vmm/vhost-user-backend/issues/62
- https://github.com/rust-vmm/vm-virtio/issues/145
