### ISSUE TITLE
virtiofs documentation error, dax needs to be enabled on the guest

### ISSUE THREAD

**Issue by wolfboxpen** [cloud-hypervisor/cloud-hypervisor#3826]
cloud hypervisor virtiofs documentation says:

> 
> The cache=never option should be the default when using virtiofsd with the cloud-hypervisor VMM. This prevents from using the guest page cache, which reduces the memory footprint of the guest. When running multiple virtual machines on the same host, this will let the host deal with page cache, which will increase the density of virtual machines which can be launched.
> 
> The cache=always option will allow for the guest page cache to be used, which will increase the memory footprint of the guest. This option should be used only for specific use cases where a single VM is going to be running on a host.

cache=never will disable mmap on the guest even when dax=on is used, which suggests DAX was never used to begin with.
DAX should suppress guest page cache usage by itself.

virtiofs on the guest should be mounted with -o dax  or when booting virtiofs add rootflags=dax

mmap now works on the guest with cache=never
cache=auto does not increase guest cache usage

**Comment by sboeuf** [comment]
I can see how the documentation is misleading given that the option `cache=` from `virtiofsd` is about the cache on the host.
But it's totally valid to run `virtiofsd` with `--cache=never` while using the DAX region through the VMM, and mounting the filesystem with DAX in the guest VM.
By default the DAX region is enabled with Cloud Hypervisor, therefore you only have to mount the filesystem with `-o dax` in the guest, that's it.

**Comment by wolfboxpen** [comment]
> The cache=never option is the default when using virtiofsd with Cloud Hypervisor. This prevents from using the host page cache, reducing the overall footprint on host memory. This increases the maximum density of virtual machines that can be launched on a single host.
> 
> The cache=always option will allow the host page cache to be used, which can result in better performance for the guest's workload at the cost of increasing the footprint on host memory.

I feel like there may be some lacking information.

When dax is enabled in the VMM and the guest, cache=auto/never/always becomes just lifetime control for metadata on the guest.
When cache=never and dax=off, mmap is no longer functional in the guest. Which can break the guest if it relies on booting from virtiofs (depending on rootfs, init scripts, started software etc.)

**Comment by sboeuf** [comment]
From my understanding, the ability to mmap is only related to the usage of DAX. The cache= option has nothing to do with this.
If you think the documentation is not complete enough, feel free to send a PR, and/or add a link to an existing virtio-fs documentation.

**Comment by wolfboxpen** [comment]
Try cache=none or cache=never (depending virtiofsd version), mount with no dax and attempt to use software which uses mmap. You will get an error.

It is not surprisingly because virtiofs suppresses page cache usage despite dax, and if dax isn't on then there is nothing to mmap.
