### ISSUE TITLE
Improve test_config_validation()

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3879]
By adding `#[derive(PartialEq)]` to `ValidationError`, we can precisely assert on the error we are expecting, e.g. `assert_eq!(invalid_config.validate(), Err(ValidationError::OnIommuSegment(1)))`, which would be better?

_Originally posted by @likebreath in https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3870#discussion_r831454096_

**Comment by likebreath** [comment]
@rbradford Thank you for opening the issue. I can take this issue, if you haven't started.
