### ISSUE TITLE
DSDT contains memory related logic with hotplug_method=virtio-mem

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3883]
The DSDT logic shouldn't be included when running with `--memory hotplug_method=virtio-mem`. The challenge is that the GED device will still need to have an `MSCN` symbol available to it. This could be an empty function like `CSCN` is in the case of non-dynamic `CpuManager`

**Comment by sboeuf** [comment]
>The DSDT logic shouldn't be included when running with `--memory hotplug_method=virtio-mem`.

I agree.

>The challenge is that the GED device will still need to have an `MSCN` symbol available to it. This could be an empty function like `CSCN` is in the case of non-dynamic `CpuManager`.

The alternative would be to generate the GED according to the `CpuManager` and `MemoryManager` being dynamic or not.

**Comment by rbradford** [comment]
> > The challenge is that the GED device will still need to have an `MSCN` symbol available to it. This could be an empty function like `CSCN` is in the case of non-dynamic `CpuManager`.
> 
> The alternative would be to generate the GED according to the `CpuManager` and `MemoryManager` being dynamic or not.

I would love that but the `DeviceManager` does not know if the `CpuManager` or `MemoryManager` are dynamic and I think the added complexity is not worth it compared to having an empty function in the table.

**Comment by sboeuf** [comment]
> > > The challenge is that the GED device will still need to have an `MSCN` symbol available to it. This could be an empty function like `CSCN` is in the case of non-dynamic `CpuManager`.
> > 
> > 
> > The alternative would be to generate the GED according to the `CpuManager` and `MemoryManager` being dynamic or not.
> 
> I would love that but the `DeviceManager` does not know if the `CpuManager` or `MemoryManager` are dynamic and I think the added complexity is not worth it compared to having an empty function in the table.

I understand.
