### ISSUE TITLE
Create mmio hole for TPM TIS device in aarch64 memory layout

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/cloud-hypervisor#3890]
**Describe the bug**
TPM TIS requires **0xfed40000-0xfed44fff** MMIO region. reference: https://qemu.readthedocs.io/en/latest/specs/tpm.html. What is the best way to address this requirement in aarch64 memory layout?

One option is to push out Device Area further out from Guest Ram Area. Currently Device Area starts right after Guest Ram following, https://github.com/praveen-pk/cloud-hypervisor/blob/3a4e8ea4023bde86778483a33af480e8b41a7db3/vmm/src/memory_manager.rs#L910. Does it make sense to set start_of_device_area to 0x100000000 on aarch64?

Details of the error I noticed are as follows:

While using 2GB guest memory, I see the following in **/proc/iomem** of Ubuntu Focal aarch64 Guest
```
$ cat /proc/iomem
....

bfc00000-ffbfbfffff : PCI Bus 0000:00
  fed40000-fed44fff : MSFT0101:00
    fed40000-fed44fff : MSFT0101:00 MSFT0101:00
  200000000-20007ffff : 0000:00:04.0
    200000000-20007ffff : virtio-pci-modern
  200080000-2000fffff : 0000:00:03.0
    200080000-2000fffff : virtio-pci-moder
```
Even with the above overlap Linux guests detects TPM device correctly. But aarch64 windows Guest reports an error and doesn't detect the TPM device.

on x86_64, irrespective of guest memory being 2G or 4G, I see PCI Bus is mapped at 0x1_0000_0000, so I do not see this issue.
```
# on x86_64 Linux Guest with 2G Memory
00000000-00000fff : Reserved
00001000-0009ffff : System RAM
000f0000-000fffff : System ROM
00100000-0013ffff : Reserved
00140000-7fffffff : System RAM
  28000000-28e03136 : Kernel code
  29000000-29519fff : Kernel rodata
  29600000-29959f3f : Kernel data
  29bb8000-29dfffff : Kernel bss
  53000000-5affffff : Crash kernel
c0000000-e7ffffff : PCI Bus 0000:00
  e7f00000-e7f7ffff : 0000:00:02.0
    e7f00000-e7f7ffff : virtio-pci-modern
  e7f80000-e7ffffff : 0000:00:01.0
    e7f80000-e7ffffff : virtio-pci-modern
e8000000-e80fffff : PCI MMCONFIG 0000 [bus 00-00]
  e8000000-e80fffff : PCI Bus 0000:00
    e8000000-e80fffff : pnp 00:00
fec00000-fec003ff : IOAPIC 0
fed40000-fed44fff : MSFT0101:00
  fed40000-fed44fff : MSFT0101:00 MSFT0101:00
fee00000-fee00fff : Local APIC
100000000-7effffffff : PCI Bus 0000:00
  7efff00000-7efff7ffff : 0000:00:04.0
    7efff00000-7efff7ffff : virtio-pci-modern
  7efff80000-7effffffff : 0000:00:03.0
    7efff80000-7effffffff : virtio-pci-modern


# on x86_64 Linux Guest with 4G Memory

00000000-00000fff : Reserved
00001000-0009ffff : System RAM
000f0000-000fffff : System ROM
00100000-0013ffff : Reserved
00140000-bfffffff : System RAM
  b8000000-bfffffff : Crash kernel
c0000000-e7ffffff : PCI Bus 0000:00
  e7f00000-e7f7ffff : 0000:00:02.0
    e7f00000-e7f7ffff : virtio-pci-modern
  e7f80000-e7ffffff : 0000:00:01.0
    e7f80000-e7ffffff : virtio-pci-modern
e8000000-e80fffff : PCI MMCONFIG 0000 [bus 00-00]
  e8000000-e80fffff : PCI Bus 0000:00
    e8000000-e80fffff : pnp 00:00
fec00000-fec003ff : IOAPIC 0
fed40000-fed44fff : MSFT0101:00
  fed40000-fed44fff : MSFT0101:00 MSFT0101:00
fee00000-fee00fff : Local APIC
100000000-13fffffff : System RAM
  125000000-125e03136 : Kernel code
  126000000-126519fff : Kernel rodata
  126600000-126959f3f : Kernel data
  126bb8000-126dfffff : Kernel bss
140000000-7f3fffffff : PCI Bus 0000:00
  7f3ff00000-7f3ff7ffff : 0000:00:04.0
    7f3ff00000-7f3ff7ffff : virtio-pci-modern
  7f3ff80000-7f3fffffff : 0000:00:03.0
    7f3ff80000-7f3fffffff : virtio-pci-modern
```

**To Reproduce**
vtpm for cloud-hypervisor is being developed at **https://github.com/praveen-pk/cloud-hypervisor/tree/vtpm**. I just have a working prototype here. The code needs a bit of clean up and restructuring.

1) Start swtpm with the following command:
```
swtpm \
 socket --tpmstate dir=/tmp/swtpm \
 --ctrl type=unixio,path=/tmp/swtpm/swtpm-sock \
 --tpm2 \
 --flags not-need-init,startup-clear

```
2) Start cloud-hypervisor version at the above link 
```


cloud-hypervisor  \
   --cpus boot=3,max=3,topology=1:1:1:3  \
   --kernel ${FW} \
  --disk path=${IMAGE} \
        --memory size=2048M \
        --net "tap=vmtap0,mac=2e:de:7a:2e:5d:e0,ip=192.168.249.1,mask=255.255.255.0" \
        --serial tty \
        --console off
```
**Version**

$ cloud-hypervisor --version
cloud-hypervisor v21.0-154-g3a4e8ea4-dirty

I built cloud-hypervisor from source using https://github.com/praveen-pk/cloud-hypervisor/tree/vtpm.

**VM configuration**

Guest OS version details:
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux chtestvm 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:50:13 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

```

Host OS version details:
```
# cat /etc/os-release
NAME="Common Base Linux Mariner"
VERSION="1.0.20211207"
ID=mariner
VERSION_ID=1.0
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"
```
# uname -a
Linux demo_imx8 5.10.93.1-4.cm1 #1 SMP Sat Feb 19 10:57:16 UTC 2022 aarch64 aarch64 aarch64 GNU/Linu

**Logs**

As TPM on Linux guest works, there are no failure logs
```
$ sudo dmesg | grep -i tpm
[    0.000000] ACPI: TPM2 0x00000000BBFEF518 000034 (v03 CLOUDH CHTPM2   00000001 CLDH 00000000)
[    2.209489] tpm_tis MSFT0101:00: 2.0 TPM (device-id 0x1, rev-id 1)
[    2.464455] tpm tpm0: A TPM error (256) occurred attempting the self test
[    2.474792] tpm tpm0: starting up the TPM manually
```

**Comment by michael2012z** [comment]
Hi, @praveen-pk 

AArch64 and X86 has different memory layout under the device area. For AArch64, the ram starts at 1G, and the device area follows the ram. So if the memory is 2G, the device area starts around 3G address. Could you increase the memory to let the device area reach the location you need?

Another thing to note is the start address of the device area on AArch64, in your test it is:
`bfc00000-ffbfbfffff : PCI Bus 0000:00`
According to the calculation above, the start address should be `c000_0000` instead of `bfc00000`. This is a trick we played in  UEFI booting. EDK2 requires a small piece of memory at address `0`. As a temporary solution, we hide 4 MB ram from the guest for this. So the end of ram you saw is `bfc00000`, 4 MB prior `c000_0000`. This is not a good solution, we will continue to explore a better one.

Can you try memory size `--memory size=3076M` (3GB + 4MB)? This way you should be able to see the required iomem range:
`100000000-ffefffffff : PCI Bus 0000:00`

**Comment by praveen-pk** [comment]
@michael2012z unfortunately, my hardware configuration does not allow passing 3G memory to Guest. What is the downside of hardcoding the device start area to 100000000?
To be precise, if the guest memory is less than 3G, we can set the device start area to 100000000. If guest memory is >= 3G, we can let the device area start after the guest RAM.

**Comment by michael2012z** [comment]
I don't think it's good idea to push `start_of_device_area` above a fixed address 0x1_0000_0000, because:
1. A gap is left if the ram is less than 3G. The gap needs to be taken care. That adds some complexity.
2. Your case seems a very particular one, because the device has to be somewhere. It seems not a very strong reason to change the generic logic of calculating `start_of_device_area`.

The calculation of `start_of_device_area` takes the hotplug size into account as well. In your case, if you cannot provide more memory to the guest, can you try to reserve some space before `start_of_device_area` by adding a hotplug option like: `--memory size=2048M,hotplug_size=1024M`? This way 1024M space should be added after the memory, the device area will be pushed behind 0x1_0000_0000, and you don't consume more memory.

**Comment by liuw** [comment]
The TPM device has to be in that location because its specification says so. We can move it to arbitrary address but that may cause other issues,

If TPM is to be officially supported by the project, users shouldn't have to play with `--memory` and hope things work by chance. That's prone to error if Cloud Hypervisor changes its internal at some point. When user specifies `--tpm`, Cloud Hypervisor should just work.

Does adding a gap really add complexity? The gap shouldn't be touched by the guest.

**Comment by michael2012z** [comment]
Is this change requirement (adjusting `start_of_device_area`) aarch64 specific or common to both architectures? 

On X86, if the memory is less than 2G, is there a same problem?

**Comment by liuw** [comment]
I think both architectures will require some work. Things happen to work on x86.

**Comment by michael2012z** [comment]
If it's common, I suppose the potential adjustment could be placed around here (after calculating the hot-plug area): https://github.com/praveen-pk/cloud-hypervisor/blob/3a4e8ea4023bde86778483a33af480e8b41a7db3/vmm/src/memory_manager.rs#L1037

I did a quick try days ago. FDT went well. But the VM didn't boot successfully with EDK2, I didn't dig further. That's why I said it could impact a little more.

Now that it also for X86, ping @rbradford . What do you think?

**Comment by rbradford** [comment]
To be clear: like the IOAPIC this doesn't need to be in the device area it can be hardcoded.

**Comment by rbradford** [comment]
For aarch64 it might be easier to start the high ram at 4GiB vs 1GiB?

**Comment by michael2012z** [comment]
Starting from 4GiB is possible, but avoiding the whole 3G space before 4GiB seems a waste. I prefer to adjust the border.

**Comment by michael2012z** [comment]
@liuw I can try to work out a proposal and look into the EDK2 issue. Then let's continue the discussion with a PR.

Could you evaluate the feasibility of moving TPM somewhere under 1GiB as well?

**Comment by liuw** [comment]
Windows' TPM driver has a check for the location of the device. I think once that restriction is removed (plus another unrelated bug fix), arbitrary location should work. That's out of spec, but *shrugs*. It takes some time to make that change to the TPM driver and we also need buy-in from Windows' side.

Linux doesn't particularly care about the exact location.

Not sure what other operating systems expect.

**Comment by praveen-pk** [comment]
Below are the memory maps from 2G and 4G VMs from x86_64 architecture:

```$ sudo cat /proc/iomem
00000000-00000fff : Reserved
00001000-0009ffff : System RAM
000f0000-000fffff : System ROM
00100000-0013ffff : Reserved
00140000-7fffffff : System RAM
  28000000-28e03136 : Kernel code
  29000000-29519fff : Kernel rodata
  29600000-29959f3f : Kernel data
  29bb8000-29dfffff : Kernel bss
  53000000-5affffff : Crash kernel
c0000000-e7ffffff : PCI Bus 0000:00
  e7f00000-e7f7ffff : 0000:00:02.0
    e7f00000-e7f7ffff : virtio-pci-modern
  e7f80000-e7ffffff : 0000:00:01.0
    e7f80000-e7ffffff : virtio-pci-modern
e8000000-e80fffff : PCI MMCONFIG 0000 [bus 00-00]
  e8000000-e80fffff : PCI Bus 0000:00
    e8000000-e80fffff : pnp 00:00
fec00000-fec003ff : IOAPIC 0
fed40000-fed44fff : MSFT0101:00
  fed40000-fed44fff : MSFT0101:00 MSFT0101:00
fee00000-fee00fff : Local APIC
100000000-7effffffff : PCI Bus 0000:00
  7efff00000-7efff7ffff : 0000:00:04.0
    7efff00000-7efff7ffff : virtio-pci-modern
  7efff80000-7effffffff : 0000:00:03.0
    7efff80000-7effffffff : virtio-pci-modern```

```$ sudo cat /proc/iomem
00000000-00000fff : Reserved
00001000-0009ffff : System RAM
000f0000-000fffff : System ROM
00100000-0013ffff : Reserved
00140000-bfffffff : System RAM
  b8000000-bfffffff : Crash kernel
c0000000-e7ffffff : PCI Bus 0000:00
  e7f00000-e7f7ffff : 0000:00:02.0
    e7f00000-e7f7ffff : virtio-pci-modern
  e7f80000-e7ffffff : 0000:00:01.0
    e7f80000-e7ffffff : virtio-pci-modern
e8000000-e80fffff : PCI MMCONFIG 0000 [bus 00-00]
  e8000000-e80fffff : PCI Bus 0000:00
    e8000000-e80fffff : pnp 00:00
fec00000-fec003ff : IOAPIC 0
fed40000-fed44fff : MSFT0101:00
  fed40000-fed44fff : MSFT0101:00 MSFT0101:00
fee00000-fee00fff : Local APIC
100000000-13fffffff : System RAM
  125000000-125e03136 : Kernel code
  126000000-126519fff : Kernel rodata
  126600000-126959f3f : Kernel data
  126bb8000-126dfffff : Kernel bss
140000000-7f3fffffff : PCI Bus 0000:00
  7f3ff00000-7f3ff7ffff : 0000:00:04.0
    7f3ff00000-7f3ff7ffff : virtio-pci-modern
  7f3ff80000-7f3fffffff : 0000:00:03.0
    7f3ff80000-7f3fffffff : virtio-pci-modern```

In both cases there are some gaps. Following the above logic, I hardcoded `start_of_device_area` to `0xFF00_0000` in my test and was able to boot windows Guest just fine.

**Comment by rbradford** [comment]
> Starting from 4GiB is possible, but avoiding the whole 3G space before 4GiB seems a waste. I prefer to adjust the border.

Well, if the spec says the address is fixed then there isn't much that can be done about that. It would be perfectly reasonable for the RAM to run from 1GiB to 0xfed40000 and then from 0xfee0000 to its size when more is needed. The device area doesn't need to be particularly big so you could place that from 0xfee0000 or end of ram onwards.

**Comment by praveen-pk** [comment]
> > In both cases there are some gaps. Following the above logic, I hardcoded `start_of_device_area` to `0xFF00_0000` in my test and was able to boot windows Guest just fine.
> 
> On x86_64 you shouldn't need to make any memory layout changes as we already don't have RAM there.

Agreed, no need to make any changes to x86_64 mem layout. Above change is specific to aarch64.

**Comment by michael2012z** [comment]
@praveen-pk I created a PR for the layout change, can you try it: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3920 ?

A hole was reserved before 4GiB, which covers the address range required by TPM.

Now arm64 shares the similar algorithm in handling the RAM regions, that's what @rbradford had described in comment https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3890#issuecomment-1082201414.

I tested the code with EDK2 manually, the bus address was as expected. There are integration tests to fix. But before doing that, could you feedback whether it works with TPM.

**Comment by praveen-pk** [comment]
@michael2012z thanks for driving this feature forward. I will give this PR a try and report back today.

**Comment by praveen-pk** [comment]
@michael2012z after rebasing to the https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3920, I see the following memory layout:

```
## 1GB Memory to Guest

testuser@chtestvm:~$ sudo cat /proc/iomem
09000000-09000fff : ARMH0011:00
  09000000-09000fff : ARMH0011:00 ARMH0011:00
10000000-2fffffff : PCI Bus 0000:00
  10000000-1007ffff : 0000:00:02.0
    10000000-1007ffff : virtio-pci-modern
  10080000-100fffff : 0000:00:01.0
    10080000-100fffff : virtio-pci-modern
30000000-300fffff : PCI ECAM
40000000-7bf9ffff : System RAM
  424b0000-43dbffff : Kernel code
  43dc0000-4448ffff : reserved
  44490000-447dcfff : Kernel data
  686d2000-6a19afff : reserved
  79000000-7affffff : reserved
  7bf7a000-7bf7afff : reserved
7bfa0000-7bfdffff : reserved
7bfe0000-7bfeffff : System RAM
  7bfe0000-7bfeffff : reserved
7bff0000-7c1bffff : reserved
7c1c0000-7f49ffff : System RAM
  7c1c3000-7c1c3fff : reserved
  7ce00000-7de00fff : reserved
  7e700000-7e700fff : reserved
7f4a0000-7f52ffff : reserved
7f530000-7f56ffff : System RAM
7f570000-7f65ffff : reserved
7f660000-7fbfffff : System RAM
  7f77c000-7f77cfff : reserved
  7f7b0000-7f7bffff : reserved
  7f7c0000-7f7cffff : reserved
  7f7d0000-7f7dffff : reserved
  7f7e0000-7f7effff : reserved
  7f813000-7f993fff : reserved
  7f994000-7f9f6fff : reserved
  7f9f9000-7f9fafff : reserved
  7f9fb000-7f9fbfff : reserved
  7f9fc000-7fbfffff : reserved
fed40000-fed44fff : MSFT0101:00
  fed40000-fed44fff : MSFT0101:00 MSFT0101:00
100000000-feffffffff : PCI Bus 0000:00
  200000000-20007ffff : 0000:00:04.0
    200000000-20007ffff : virtio-pci-modern
  200080000-2000fffff : 0000:00:03.0
    200080000-2000fffff : virtio-pci-modern
	


## 2GB Memory to Guest

testuser@chtestvm:~$ sudo cat /proc/iomem
09000000-09000fff : ARMH0011:00
  09000000-09000fff : ARMH0011:00 ARMH0011:00
10000000-2fffffff : PCI Bus 0000:00
  10000000-1007ffff : 0000:00:02.0
    10000000-1007ffff : virtio-pci-modern
  10080000-100fffff : 0000:00:01.0
    10080000-100fffff : virtio-pci-modern
30000000-300fffff : PCI ECAM
40000000-bbf9ffff : System RAM
  5b2d0000-5cbdffff : Kernel code
  5cbe0000-5d2affff : reserved
  5d2b0000-5d5fcfff : Kernel data
  986d2000-9a19afff : reserved
  b60e8000-b60e8fff : reserved
  b6120000-b612ffff : reserved
  b6130000-b613ffff : reserved
  b6140000-b614ffff : reserved
  b6150000-b615ffff : reserved
  b7000000-baffffff : reserved
  bbf7a000-bbf7afff : reserved
bbfa0000-bbfdffff : reserved
bbfe0000-bbfeffff : System RAM
  bbfe0000-bbfeffff : reserved
bbff0000-bc1bffff : reserved
bc1c0000-bf49ffff : System RAM
  bc1c3000-bc1c3fff : reserved
  bde00000-bde00fff : reserved
  be700000-be700fff : reserved
  bf2a0000-bf49ffff : reserved
bf4a0000-bf52ffff : reserved
bf530000-bf56ffff : System RAM
bf570000-bf65ffff : reserved
bf660000-bfbfffff : System RAM
  bf692000-bf792fff : reserved
  bf793000-bf7f5fff : reserved
  bf7f8000-bf7f9fff : reserved
  bf7fa000-bf7fafff : reserved
  bf7fb000-bfbfffff : reserved
fed40000-fed44fff : MSFT0101:00
  fed40000-fed44fff : MSFT0101:00 MSFT0101:00
100000000-feffffffff : PCI Bus 0000:00
  200000000-20007ffff : 0000:00:04.0
    200000000-20007ffff : virtio-pci-modern
  200080000-2000fffff : 0000:00:03.0
    200080000-2000fffff : virtio-pci-modern

## 4GB Memory to Guest
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3901         146        3481           0         273        3608
Swap:             0           0           0

$ sudo cat /proc/iomem
09000000-09000fff : ARMH0011:00
  09000000-09000fff : ARMH0011:00 ARMH0011:00
10000000-2fffffff : PCI Bus 0000:00
  10000000-1007ffff : 0000:00:02.0
    10000000-1007ffff : virtio-pci-modern
  10080000-100fffff : 0000:00:01.0
    10080000-100fffff : virtio-pci-modern
30000000-300fffff : PCI ECAM
40000000-f839ffff : System RAM
  769f0000-782fffff : Kernel code
  78300000-789cffff : reserved
  789d0000-78d1cfff : Kernel data
  b4ad3000-b659bfff : reserved
  f2000000-f7ffffff : reserved
  f837a000-f837afff : reserved
f83a0000-f83dffff : reserved
f83e0000-f83effff : System RAM
  f83e0000-f83effff : reserved
f83f0000-f85bffff : reserved
f85c0000-fb89ffff : System RAM
  f85c3000-f85c3fff : reserved
  faaf3000-faaf3fff : reserved
fb8a0000-fb92ffff : reserved
fb930000-fb96ffff : System RAM
fb970000-fba5ffff : reserved
fba60000-fbffffff : System RAM
fed40000-fed44fff : MSFT0101:00
  fed40000-fed44fff : MSFT0101:00 MSFT0101:00
100000000-143bfffff : System RAM
  13c15b000-13c15bfff : reserved
  13c190000-13c19ffff : reserved
  13c1a0000-13c1affff : reserved
  13c1b0000-13c1bffff : reserved
  13c1c0000-13c1cffff : reserved
  13da00000-13e1fffff : reserved
  13e3f6000-13e3f7fff : reserved
  13e400000-1431fffff : reserved
  143333000-1433f5fff : reserved
  1433f8000-1433f8fff : reserved
  1433f9000-143800fff : reserved
  143801000-143bfffff : reserved
143c00000-ff43bfffff : PCI Bus 0000:00
  200000000-20007ffff : 0000:00:04.0
    200000000-20007ffff : virtio-pci-modern
  200080000-2000fffff : 0000:00:03.0
    200080000-2000fffff : virtio-pci-modern

```

In all these cases, I do not see any region overlaps that I intially reported.

**Comment by michael2012z** [comment]
> In all these cases, I do not see any region overlaps that I intially reported.

Thank you for testing it. So, the new layout of the PR works with TPM as expected, right?

OK, I will continue the work. Now there is still a test case failure in migration scenario.
