### ISSUE TITLE
LTS Release Proposal

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3926]
We're proposing to make 23.0 or 24.0 an LTS release. We're currently proposing to support the LTS release for 18 months from release.

The LTS would include security fixes for Cloud Hypervisor and any of its dependencies (crates that it uses.)

**Comment by rbradford** [comment]
I would like feedback from @cloud-hypervisor/cloud-hypervisor-maintainers  and the wider community if this is something that is desired or whether the scope needs to be different.

**Comment by liuw** [comment]
What is the cadence of picking an LTS release? I don't think maintaining too many LTS releases is economical. I do think having overlapping-in-time LTS releases are important.

**Comment by rbradford** [comment]
> What is the cadence of picking an LTS release? I don't think maintaining too many LTS releases is economical. I do think having overlapping-in-time LTS releases are important.

Great question. What about 1 per year? Which would give 6 months overlap.

**Comment by likebreath** [comment]
I wonder how do we regularly check security fixes for all our dependencies? Is there an "easy" way to do it automatically?

**Comment by sboeuf** [comment]
We need to define clearly what it means to pull security fixes for the dependencies. Are we gonna update the dependencies based on the patch version or the minor version? I assume we won't bump a dependency main version?
About how to track this I guess we can configure dependabot to report these things.

**Comment by rbradford** [comment]
> We need to define clearly what it means to pull security fixes for the dependencies. Are we gonna update the dependencies based on the patch version or the minor version? I assume we won't bump a dependency main version? About how to track this I guess we can configure dependabot to report these things.

Yeh using dependabot with the "security fixes" only option is the best plan. I think we'll just have to use the best version available to us. If a dependency doesn't backport to old versions then we might have to go forward. Fortunately we have good CI coverage.

**Comment by liuw** [comment]
> > What is the cadence of picking an LTS release? I don't think maintaining too many LTS releases is economical. I do think having overlapping-in-time LTS releases are important.
> 
> Great question. What about 1 per year? Which would give 6 months overlap.

Yes, time wise this sounds fine to me. One potential down side for fixed cadence is now people know which release is going to be an LTS there will be a tendency to rush things into those releases. There is no one best solution for managing LTS releases. I guess we can just go with this model for now. It can always be changed in the future.

A follow-up question is what is the support status for compatibility between N and N+1 LTS releases? We need to assume people will skip all intermediate releases.

**Comment by rbradford** [comment]
> > > What is the cadence of picking an LTS release? I don't think maintaining too many LTS releases is economical. I do think having overlapping-in-time LTS releases are important.
> > 
> > 
> > Great question. What about 1 per year? Which would give 6 months overlap.
> 
> Yes, time wise this sounds fine to me. One potential down side for fixed cadence is now people know which release is going to be an LTS there will be a tendency to rush things into those releases. There is no one best solution for managing LTS releases. I guess we can just go with this model for now. It can always be changed in the future.
> 

Yes, that is definitely a risk. Hopefully that is not something that will come up too often.

> A follow-up question is what is the support status for compatibility between N and N+1 LTS releases? We need to assume people will skip all intermediate releases.

That is a good point. There will inevitably be deprecations/removals of features across that period. I'm not sure trying to guarantee that you can live migration across 7 intermediate releases (assuming we stick with our current cadence) is really sustainable.

**Comment by weltling** [comment]
Based on the discussion till now, perhaps it's time to have a more precise definition of what is stability in the context of Cloud Hypervisor. Which concrete technical aspects are involved, etc.

Also given that we don't have a patch version in tags, there should be probably a concrete guidance to read the stability from the version string? I'd in general suggest to formalize these points and present them as an RFC document that can be referred to and that will guide consumers, developers, downstream maintainers, etc. and make the process as transparent as possible.

Thanks

**Comment by rbradford** [comment]
@weltling The README lists our current guarantees: https://github.com/cloud-hypervisor/cloud-hypervisor/#3-status

> Cloud Hypervisor is under active development. The following stability guarantees
> are currently made:
> 
> * The API (including command line options) will not be removed or changed in a
>   breaking way without a minimum of 2 releases notice. Where possible warnings
>   will be given about the use of deprecated functionality and the deprecations
>   will be documented in the release notes.
> * Point releases will be made between individual releases where there are
>   substantial bug fixes or security issues that need to be fixed.
> 
> Currently the following items are **not** guaranteed across updates:
> 
> * Snapshot/restore is not supported across different versions
> * Live migration is not supported across different versions
> * The following features are considered experimental and may change
>   substantially between releases: TDX, SGX.
>

**Comment by rbradford** [comment]
> Also given that we don't have a patch version in tags, there should be probably a concrete guidance to read the stability from the version string?

What does this mean?

**Comment by weltling** [comment]
@rbradford oh, that's a good point on some technical stability details, thanks for pointing to that.

It also does some clarification on the version handling. For the versioning, I was referring to the prevalent semver approach where patch version would mean it's just a bugfix but minor would mean possibly a feature added. With just major and minor version, it's not immediately obvious what is to expect. There are still questions i'd like to ask:

> The API (including command line options) will not be removed or changed in a
breaking way without a minimum of 2 releases notice.
- Is this about 2 point releases or major releases?
> Where possible warnings
will be given about the use of deprecated functionality and the deprecations
will be documented in the release notes.
- Are deprecations allowed in point releases, in major releases or both?
- Are deprecations allowed in LTS?

Further questions:
- LTS: Can be features added/removed?
- LTS: Rust compatibility promise? Define the range or strategy to fix? How essential is a compiler change?
- LTS: An accompanying topic - security issue in a dependency, where a security fix might target an incompatible Rust version only. Strategy?
- Security issues in the compiler? This is probably out of scope as can't be influenced by the project.
- What are release timelines? Alpha, beta, RC, finals.
- LTS: Security fixes that would justify BC breaches? Perhaps should be announced explicitly?
- Differentiate between BC in code and in user space? Say, there would be a feature based on crate X. Is it allowed to replace the crate X with the crate Y, if the feature would stay unchanged. (An example better understanding - libcurl can use gnutls or OpenSSL to implement TLS functionality. While replacing the dependency, libcurl API to the consumer would stay same). There can be similar cases.

Perhaps also in addition to LTS, one could think to define the regular release cadence, too.  There might be more points to make the processes more transparent and plannable in general, while using LTS as a factual pretence.

Thanks

**Comment by liuw** [comment]
Not Robert but I will try to answer some of the questions. These are my own opinions only.

> @rbradford oh, that's a good point on some technical stability details, thanks for pointing to that.
> 
> It also does some clarification on the version handling. For the versioning, I was referring to the prevalent semver approach where patch version would mean it's just a bugfix but minor would mean possibly a feature added. With just major and minor version, it's not immediately obvious what is to expect. There are still questions i'd like to ask:
> 
> > The API (including command line options) will not be removed or changed in a
> > breaking way without a minimum of 2 releases notice.
> 
> * Is this about 2 point releases or major releases?
> 

These will be major releases.

It doesn't make sense in this context to talk about point releases, because point releases, unless under exceptional circumstances, should not add or remove features. I think this is the norm for upstream open source projects.

> > Where possible warnings
> > will be given about the use of deprecated functionality and the deprecations
> > will be documented in the release notes.
> 
> * Are deprecations allowed in point releases, in major releases or both?

Major releases only.

> * Are deprecations allowed in LTS?

No. Deprecations are neither bug fixes nor security fixes.

> 
> Further questions:
> 
> * LTS: Can be features added/removed?

No, only under exceptional circumstances. The default answer is always "no".

> * LTS: Rust compatibility promise? Define the range or strategy to fix? How essential is a compiler change?

Minimum supported rust version should stay the same unless there is an exceptional circumstance.

The compatibility between rust compiler versions is not our concern. If two versions are incompatible (in the sense that it does not build existing code) that's a compiler bug.

> * LTS: An accompanying topic - security issue in a dependency, where a security fix might target an incompatible Rust version only. Strategy?

Then I think it is a bug in the dependency or compiler. Ask them to not use fancy compiler features?

> * Security issues in the compiler? This is probably out of scope as can't be influenced by the project.

This is, like you said, out of scope. It is none of our business.

> * What are release timelines? Alpha, beta, RC, finals.

I don't a clear answer to this.

> * LTS: Security fixes that would justify BC breaches? Perhaps should be announced explicitly?

What is "BC breaches"?

> * Differentiate between BC in code and in user space? Say, there would be a feature based on crate X. Is it allowed to replace the crate X with the crate Y, if the feature would stay unchanged. (An example better understanding - libcurl can use gnutls or OpenSSL to implement TLS functionality. While replacing the dependency, libcurl API to the consumer would stay same). There can be similar cases.
> 

I think the question is why is there is a need to replace a dependency in the first place. The project has specified its dependencies. If people change those they are on their own.

> Perhaps also in addition to LTS, one could think to define the regular release cadence, too. There might be more points to make the processes more transparent and plannable in general, while using LTS as a factual pretence.
> 

Regular release cadence is hopefully well-known at this point. But yes it should be documented if not already.

**Comment by weltling** [comment]
Thanks for taking time, Wei. I'm basically on the same page in most case, touching a couple of things to clarify more or make a suggestion.

> What are release timelines? Alpha, beta, RC, finals.
I don't a clear answer to this.

Perhaps having some pre-release cycle would add to predictability. Especially in LTS where the guarantees would be expected more strictly. Users can test and report issues before the final.

> LTS: Security fixes that would justify BC breaches? Perhaps should be announced explicitly?
What is "BC breaches"?

Yeah, that was my exact question in the first post - "it's time to have a more precise definition of what is stability in the context of Cloud Hypervisor" :) Robert pointed to a couple of things that are already defined, but there are probably more factors, thus my questions, too.  

> Differentiate between BC in code and in user space? Say, there would be a feature based on crate X. Is it allowed to replace the crate X with the crate Y, if the feature would stay unchanged. (An example better understanding - libcurl can use gnutls or OpenSSL to implement TLS functionality. While replacing the dependency, libcurl API to the consumer would stay same). There can be similar cases.
I think the question is why is there is a need to replace a dependency in the first place. The project has specified its dependencies. If people change those they are on their own.

What I meant here was actually the other way round - would it be allowed for Cloud Hypervisor to break the code compatibility, in this context particularly in LTS.

Another question that we didn't have yet also - what about the KVM compatibility? Probably LTS would mean no new KVM features can be used, but still - would there be some range defined or requirements explicitly mentioned?   

Looking from the POV of say a package maintainer in Ubuntu LTS or any other downstream, some firm definitions would make the life easier. Why I think a document defining the related matters would be good to have is because for one it would give a predictable base for the consumer and would also spare additional questions. Having it in a kind of RFC style so then it could be extended by the discussion and perhaps made voted or alike might help ensure the approach is solid.

Thanks

**Comment by liuw** [comment]
> Thanks for taking time, Wei. I'm basically on the same page in most case, touching a couple of things to clarify more or make a suggestion.
> 
> > What are release timelines? Alpha, beta, RC, finals.
> > I don't a clear answer to this.
> 
> Perhaps having some pre-release cycle would add to predictability. Especially in LTS where the guarantees would be expected more strictly. Users can test and report issues before the final.
> 

I'm two minded here. Given the short regular release cycle, having RCs will either prolong the cycle or prematurely cut off feature acceptance. This is something the community needs to collectively decide.

> > LTS: Security fixes that would justify BC breaches? Perhaps should be announced explicitly?
> > What is "BC breaches"?
> 
> Yeah, that was my exact question in the first post - "it's time to have a more precise definition of what is stability in the context of Cloud Hypervisor" :) Robert pointed to a couple of things that are already defined, but there are probably more factors, thus my questions, too.

I still don't understand what "BC breaches" is unfortunately.

> 
> > Differentiate between BC in code and in user space? Say, there would be a feature based on crate X. Is it allowed to replace the crate X with the crate Y, if the feature would stay unchanged. (An example better understanding - libcurl can use gnutls or OpenSSL to implement TLS functionality. While replacing the dependency, libcurl API to the consumer would stay same). There can be similar cases.
> > I think the question is why is there is a need to replace a dependency in the first place. The project has specified its dependencies. If people change those they are on their own.
> 
> What I meant here was actually the other way round - would it be allowed for Cloud Hypervisor to break the code compatibility, in this context particularly in LTS.
> 

How does your example break code compatibility?

> Another question that we didn't have yet also - what about the KVM compatibility? Probably LTS would mean no new KVM features can be used, but still - would there be some range defined or requirements explicitly mentioned?
> 

If using a new KVM feature requires explicit enabling in Cloud Hypervisor, then it is by default a "no". If it doesn't require enabling, then it is a non-issue for us.

> Looking from the POV of say a package maintainer in Ubuntu LTS or any other downstream, some firm definitions would make the life easier. Why I think a document defining the related matters would be good to have is because for one it would give a predictable base for the consumer and would also spare additional questions. Having it in a kind of RFC style so then it could be extended by the discussion and perhaps made voted or alike might help ensure the approach is solid.
> 

Perhaps I'm making too many assumptions here, but my understanding for people's need for an LTS release is stability, not shiny new things. It is a solid base that doesn't give you surprises. Downstream can take it as-is or do any crazy things to it. In both cases, the last thing I want to see is new behaviours or intrusive changes. Guiding by this principle, a lot of the questions have a natural answer and doesn't need explicitly calling out.

Can you start this RFC document to list the things you think should be there?

**Comment by weltling** [comment]
> > > LTS: Security fixes that would justify BC breaches? Perhaps should be announced explicitly?
> > > What is "BC breaches"?
> > 
> > 
> > Yeah, that was my exact question in the first post - "it's time to have a more precise definition of what is stability in the context of Cloud Hypervisor" :) Robert pointed to a couple of things that are already defined, but there are probably more factors, thus my questions, too.
> 
> I still don't understand what "BC breaches" is unfortunately.
> 
This was my exact question in the first post :) Terms like `compatibility between N and N+1`, `BC breach`, stability are probably talk about same, but seem not defined quite precisely for the Cloud Hypervisor context. Simplistically saying, a BC breach means some change in behavior or interface that is not compatible to previous versions of the same software.

Say when talking about a reusable library written in C, one can talk about API, ABI, not removing symbols, C standard and so on. These are concrete items that can be listed as a commited statement. Similar way, in the context of CH, besides what is mentioned with regard to the API, snap/restore, hotplug and so on are statements of this kind. Further items could be for example - there wouldn't be any change to ACPI, device tree, device list, disk format, dependencies, Hyper-V enlightenments, etc. The more complete the list, the less questions or doubts the consumer would have.

> > > Differentiate between BC in code and in user space? Say, there would be a feature based on crate X. Is it allowed to replace the crate X with the crate Y, if the feature would stay unchanged. (An example better understanding - libcurl can use gnutls or OpenSSL to implement TLS functionality. While replacing the dependency, libcurl API to the consumer would stay same). There can be similar cases.
> > > I think the question is why is there is a need to replace a dependency in the first place. The project has specified its dependencies. If people change those they are on their own.
> > 
> > 
> > What I meant here was actually the other way round - would it be allowed for Cloud Hypervisor to break the code compatibility, in this context particularly in LTS.
> 
> How does your example break code compatibility?
> 
Well, in various ways. For example, changes in a dependency would imply changes in build jobs (ofc on the consumer side). Changing a dependency itself can change the final behavior, too. 

> > Another question that we didn't have yet also - what about the KVM compatibility? Probably LTS would mean no new KVM features can be used, but still - would there be some range defined or requirements explicitly mentioned?
> 
> If using a new KVM feature requires explicit enabling in Cloud Hypervisor, then it is by default a "no". If it doesn't require enabling, then it is a non-issue for us.
> 
If i understand correctly, this should be a good enough strategy. KVM features, that don't require explicit enablement in Cloud Hypervisor, should be generic enough to be compatible "everywhere".

BTW while talking about KVM, another important dependency that pops in my mind is also UEFI :)

> > Looking from the POV of say a package maintainer in Ubuntu LTS or any other downstream, some firm definitions would make the life easier. Why I think a document defining the related matters would be good to have is because for one it would give a predictable base for the consumer and would also spare additional questions. Having it in a kind of RFC style so then it could be extended by the discussion and perhaps made voted or alike might help ensure the approach is solid.
> 
> Perhaps I'm making too many assumptions here, but my understanding for people's need for an LTS release is stability, not shiny new things. It is a solid base that doesn't give you surprises. Downstream can take it as-is or do any crazy things to it. In both cases, the last thing I want to see is new behaviours or intrusive changes. Guiding by this principle, a lot of the questions have a natural answer and doesn't need explicitly calling out.
> 
Yes, "avoid surprises" is in general a strategy. As in any project, being a contributor is however something different from being just a user. Things might be clear right away for those knowing internals, but for a usual customer case IMHO it is still better to have an explicit commitment.

> Can you start this RFC document to list the things you think should be there?

Sure, if this approach sounds plausible, i could start writing it based on what has been discussed and mentioned here.

Thanks

**Comment by weltling** [comment]
@rbradford thanks for going through this. I'd then start writing based on this discussion to have some release definition. 

One question yet - for the current release cadence, it looks like there would be a major release every ~6 weeks, but i couldn't tell the cadence for point releases. Could you please clarify with regard to the current procedure?

Thanks

**Comment by rbradford** [comment]
> @rbradford thanks for going through this. I'd then start writing based on this discussion to have some release definition.
> 
> One question yet - for the current release cadence, it looks like there would be a major release every ~6 weeks, but i couldn't tell the cadence for point releases. Could you please clarify with regard to the current procedure?

Great question. Currently there is no fixed cadence for point releases and they've been made when a critical bug has been fixed in the main branch and the patch backported. I would like to formalise it more.

**Comment by sboeuf** [comment]
> Thanks to @weltling we have some good documentation on releases. Can we restart the conversation about LTS releases. I'm thinking about making v25.0 since we have some deprecations that will be removed in that cycle (after having been deprecated for 2 releases). What does the rest of the team think?

I agree it's a good place to start our first LTS. Especially since we shouldn't have any other deprecation in the pipe. And we got to start somewhere and try in order to assess if the LTS format we've described is viable.

**Comment by liuw** [comment]
> 



> > Thanks to @weltling we have some good documentation on releases. Can we restart the conversation about LTS releases. I'm thinking about making v25.0 since we have some deprecations that will be removed in that cycle (after having been deprecated for 2 releases). What does the rest of the team think?
> 
> I agree it's a good place to start our first LTS. Especially since we shouldn't have any other deprecation in the pipe. And we got to start somewhere and try in order to assess if the LTS format we've described is viable.

+1

**Comment by likebreath** [comment]
I wonder what's the plan for supporting live-upgrade across different versions? Are we looking at across two stable releases or even across two LTS releases?

**Comment by sdake** [comment]
> Perhaps having some pre-release cycle would add to predictability. Especially in LTS where the guarantees would be expected more strictly. Users can test and report issues before the final.
> 
> > LTS: Security fixes that would justify BC breaches? Perhaps should be announced explicitly?
> > What is "BC breaches"?
> 
> Yeah, that was my exact question in the first post - "it's time to have a more precise definition of what is stability in the context of Cloud Hypervisor" :) Robert pointed to a couple of things that are already defined, but there are probably more factors, thus my questions, too.

In order to have a precise definition of support *guarantees*, a list of `APIs` and their associated features must be produced. As part of the feature list, stealing from the cloud-native ecosystem for the cloud-hypervisor :), I participated n the development of this release and support model for  [Istio](https://istio.io) and think it can work pretty well, with the proper test and release (or just release) team in place.

- `DEVELOPMENT`: The feature is in development, may or may not be usable, and is highly suitable for developer participation
- `EXPERIMENTAL`: The feature is developed, may not be finalized, and absolutely no support guarantees, including API guarantees, are provided
- `ALPHA`: The feature is ready for evaluation, but the feature may be removed from a future release
- `BETA`: The feature is ready for production workloads, and some basic support guarantees are made such as the feature will not be removed in the N-1 (eg last LTS release).
- `STABLE`: The feature is finalized, documented, tested both unit and functional, and strong guarantees are made about the API and its associated functionality. Any deprecation will be announced, and the feature will not be fully removed from the project until `LTS+1`, or `LTS+2`.
- `DEPRECATED`: The feature progresses from `ALPHA`, `BETA`, or `STABLE` to `DEPRECATED` meaning the feature was in the project but now part of the bit bucket.

I am working this strawman into two PRs to submit against issue #4121.

Thank you,
-steve

**Comment by rbradford** [comment]
@sdake Cool, thanks for sharing your ideas.

**Comment by rbradford** [comment]
I think we should make v28.0 our first LTS release. Any disagreement?

**Comment by weltling** [comment]
With regard to the MSHV part things are still moving fast, but given essential pieces (hypervisor at least) not public yet it should be probably good enough. I think I'd till cater to KVM for the public RPM builds. Just for awareness /cc @liuw @jinankjain.

Thanks

**Comment by rbradford** [comment]
I think we established that v28.0 would be our first LTS release and what this means has been documented (thanks @weltling)
