### ISSUE TITLE
Add live migration/live upgrade compatibility test

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3949]
Boot a VM with the last released stable binary and then migrate it to the version under test. This will help us work towards supporting live upgrades between major releases. 

This might need to be multiple tests in order to fully exercise all the functionality.

**Comment by likebreath** [comment]
For the existing integration tests, they are all testing live-migration between the same CH version, covering NUMA, vhost-user (OVS-DPDK), and local-migration. Do you think it would be enough to have a similar set of compatibility tests? Anything more you  would like to cover?
