### ISSUE TITLE
virtio-block VIRTIO_BLK_T_FLUSH implementation

### ISSUE THREAD

**Issue by ZideChen0** [cloud-hypervisor/cloud-hypervisor#399]
Currently Cloud-hypervisor call disk.flush for guest VIRTIO_BLK_T_FLUSH request:

 RequestType::Flush => match disk.flush() {
 }

Which actually doesn't nothing:
https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/fs.rs#L791
pub fn flush(&self) -> io::Result<()> { Ok(()) }

Probably this is not compliant with virtio spec:
"If the device is backed by persistent storage, the device MUST ensure that stable writes are committed to it, before reporting completion of the write (cases 1 and 2) or the flush (case 3). Failure to do so can cause data loss in case of a crash."

I'd like to propose to use nix::sys::aio::fsync() for this purpose, which has better performance then the synchronous counterpart std::fs::File::sync_all()/sync_data().

**Comment by rbradford** [comment]
No dependency on nix please. Use libc directly: https://docs.rs/nix/0.11.0/src/nix/sys/aio.rs.html#827

```
    pub fn fsync(&mut self, mode: AioFsyncMode) -> Result<()> {
        let p: *mut libc::aiocb = &mut self.aiocb;
        Errno::result(unsafe {
                libc::aio_fsync(mode as libc::c_int, p)
        }).map(|_| {
            self.in_progress = true;
        })
    }
```

**Comment by sboeuf** [comment]
@ZideChen0 yes feel free to open a PR to tackle this issue, and follow @rbradford advice about `nix`.

**Comment by ZideChen0** [comment]
@rbradford Thanks for the comment! Yes, this makes sense.
@sboeuf Sure, I can cook a patch for that.
