### ISSUE TITLE
Implement Snapshot for VfioCommon

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#3997]
Independently of how the VFIO migration API look like, some things can be tackled first:
- [x] The logic present in `add_virtio_pci_device()` from `vmm/src/device_manager.rs` restoring the PCI segment, PCI b/d/f and PCI BAR address must be applied for both `VFIO` and `vfio-user` devices. We need to identify if some factorization can happen, meaning this logic could be pushed down to a PCI generic function such as `add_pci_device()` or so. (#3952)
- [x] `VfioCommon` must implement the `Snapshottable` trait so that both `VFIO` and `vfio-user` devices can benefit from it.
- [x] `Interrupt` must implement `Snapshottable` as well, so that all three types of interrupts can be stored.
- [x] `MsixConfig` already implements `Snapshottable`, I think we need the same for `MsiConfig`. `INTx` might not need anything as most of it is handled through the IOAPIC already.

_Originally posted by @sboeuf in https://github.com/cloud-hypervisor/cloud-hypervisor/issues/2251#issuecomment-1090323607_

**Comment by rbradford** [comment]
@sboeuf To what extent is this work completed?

**Comment by sboeuf** [comment]
This is complete, it can be closed.
