### ISSUE TITLE
cloud-hypervisor delete the file api-socket

### ISSUE THREAD

**Issue by xyz-li** [cloud-hypervisor/cloud-hypervisor#4026]
**Describe the bug**
Run command `cloud-hypervisor --api-socket /tmp/ch.sock`,  then run the command `cloud-hypervisor --api-socket /tmp/ch.sock` again. The second instance deletes the file `/tmp/ch.sock` blindly and we could not connect to the first instance now. 
Is this a bug or does it work as designed?

**To Reproduce**
Run command `cloud-hypervisor --api-socket /tmp/ch.sock` twice.

**Comment by rbradford** [comment]
It's intentional that we cleanup files that we created. However it does sound like a bug if the cleanup is happening in the second process. It should just fail to start if the address is already in use.
