### ISSUE TITLE
Unified binary for all hypervisors

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#4079]
I want to revisit the approach Cloud Hypervisor is built. At the moment only KVM or MSHV can be enabled at one time. I think that's a limiting factor for our use cases.

Is the any concern for supporting a unified binary?

I understand the desire to keep the binary small, but we can still put things under feature gates (`kvm` or `mshv` or whatever else may come in the future) to keep the binary small. Folks who want KVM only can still get exactly what they want by specifying `kvm` only.

On the technical side, trait objects are easy to deal with. What is problematic is the proliferation of reexported types. This needs a good solution. Off the top of my head The easiest solution is to provide wrapper types in the `hypervisor` crate.

**Comment by rbradford** [comment]
I support this approach. I tried to prototype this a some time back and ran into difficulties with types that were redefinitions internal structures leaking across the hypervisor crate boundary.

**Comment by liuw** [comment]
> I support this approach. I tried to prototype this a some time back and ran into difficulties with types that were redefinitions internal structures leaking across the hypervisor crate boundary.

Thanks for your support. ;-)

I will try to cobble together a prototype when I have some free cycles.

CC @russell-islam @praveen-pk

**Comment by liuw** [comment]
I think leaking dependency details is a bad practice. It makes `hypervisor` hard to be used independently.

I have not written any code, but potentially we have two ways to provide wrapper types.

```
#[repr(transparent)]
struct X(KvmX)

impl From<MshvX> for X {...}
```

```
struct X { ...fields... }

impl From<KvmX> for X {...}
impl From<MshvX> for X {...}
```

Conceptually, the first approach uses KVM's X as the base structure and other hypervisors should translate to it. The second approach defines our own structure (although in practice it is very likely to be a 1:1 copy with KVM).

Which one does people prefer? Any other ideas?

**Comment by rbradford** [comment]
I looked into this to. And I think that there are two approaches for two different situations.

1. In the case where we need to actually use the contents e.g. `StandardRegisters` outside the crate I think it makes sense to define our own struct that is hypervisor independent and then convert inside the hypervisor crate to the hypervisor specific version
2. For something where the contents are not directly used outside the hypervisor crate (e.g. `VmState`) I think that we could have a struct with a private member that is an enum (or union) for the different hypervisors.

For the former there will end up being a lot of boilerplate code or unsafe struct copy but I think it is cleanest. The latter is mostly relevant for state being used for snapshot/restore & migration.

**Comment by liuw** [comment]
Aarch64 is using `kvm_bindings` outside of the `hypervisor` crate. Any opinions on if that needs changing? @michael2012z

**Comment by michael2012z** [comment]
Indeed `arch/src/aarch64` uses a lot of reexported things from `hypervisor`. I am happy to refactor it to align with other parts.

And to support more hypervisors in future, it's better to make `aarch64` independent from concrete hypervisor.

**Comment by liuw** [comment]
For Aarch64, `gicv3.rs` and `gicv3_its` code is enclosed in a `kvm` module. Perhaps it can be moved wholesale under `hypervisor`. 

`dist_attr_access` in `dist_regs.rs` is not gated. I don't know what sort of abstraction inside `hypervisor` is right for it.

**Comment by michael2012z** [comment]
I am considering a way to refactor:

- Define a new trait `Gic` or `HypervisorGic` in `hypervisor/src/arch/aarch64`, which serves as the hypervisor-agnostic GIC interface. `HypervisorGic` is exported form `hypervisor` (mainly to `arch/src/aarch64/`).
- Move the kvm specific code in `arch/src/aarch64/gic/` to `hypervisor/src/kvm/aarch64/gic`. For example `KvmGicV3` will be here, and it implements `HypervisorGic` and `hypervisor::Device`.
- A thin wrapper layer will remain in `arch/src/aarch64/gic/`. It is the comsumer of HypervisorGic.

Regarding `dist_attr_access`, we should be able to hide it internal in `hypervisor/src/kvm/aarch64/gic` this way.

What do you think? @liuw

**Comment by liuw** [comment]
Sounds good to me.

**Comment by liuw** [comment]
On our side Dev Rajput @thesantatitan is going to look into this in the next 8 weeks. He is an intern who just started today.

Jinank @jinankjain will help him out.

**Comment by michael2012z** [comment]
I am going to begin the aarch64 part from next week. Let's keep communicating. :)

**Comment by jinankjain** [comment]
@MrXinWang I think this issue is wrongly closed. Could you please reopen it?

**Comment by MrXinWang** [comment]
@jinankjain Oh I guess when I merge the https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4162, the "Partially fixes https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4079 ." incorrectly closed this issue...

**Comment by rbradford** [comment]
Use "See: #<>" which won't trigger a close.

**Comment by liuw** [comment]
This is now done with https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4345.
