### ISSUE TITLE
Instructions to build custom kernel modules?

### ISSUE THREAD

**Issue by fengye87** [cloud-hypervisor/cloud-hypervisor#4096]
[Here](https://github.com/cloud-hypervisor/cloud-hypervisor#building-your-kernel) in the README doc, we can find detailed instructions about how to build custom kernel to use in direct kernel boot. However, it won't build corresponding kernel modules, which are required (in the rootfs image) if we would depend on any kernel module in the booted VM. Adding instructions about how to further build kernel modules to the README doc would be nice.

**Comment by sboeuf** [comment]
@fengye87 good point. Do you think you can take care of it?

**Comment by rbradford** [comment]
This isn't necessary. Our kernel has nothing compiled as modules: 

```
marvin:~/src/cloud-hypervisor (main)$ grep -c =m resources/linux-config-x86_64 
0
```

**Comment by fengye87** [comment]
@rbradford I see. Then what's the recommended way to add additional kernel modules to the VM? By 1) adding them in the config and compile it into kernel, or 2) adding them as modules? FYI, the additional kernel modules I'm talking about here is ISO9660_FS and BRIDGE_NETFILTER. I'm actually trying to boot a K8s node using direct kernel boot and cloud-init here.

@sboeuf As much as I want to, I'm still struggling here. I'll surely send a PR when things work out for me. Meanwhile, any directions would be helpful.

**Comment by rbradford** [comment]
@fengye87 Firstly for your use case have you considered Kata Containers? It already integrates between Cloud Hypervisor and k8s. 

The kernel we provide is a reference (principally for testing). If you need extra functionality you can copy it and and modify it to your needs. I would recommend you build that functionality in as keeping modules in sync will be quite tedious.

**Comment by fengye87** [comment]
@rbradford Kata Containers doesn't quite fit our use case, we want to run on any canonical K8s clusters.

I'll try including these modules in my kernel builds then, thank you for your advice.
