### ISSUE TITLE
AArch64 CI stuck occasionally

### ISSUE THREAD

**Issue by michael2012z** [cloud-hypervisor/cloud-hypervisor#4103]
AArch64 CI may stuck occasionally. 

When checking `docker ps`, some zombie integration works were seen.

This problem was seen before, but disappeared for months since updating to host kernel v5.16.

However the issue came back a week ago:

```
root@ci-cloud-hypervisor-arm64-02:~# docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED         STATUS         PORTS     NAMES
1e561f60946c   cloudhypervisor/dev:20220405-0   "./scripts/run_integ…"   8 minutes ago   Up 8 minutes             frosty_hermann
74ce9963e8e9   cloudhypervisor/dev:20220405-0   "./scripts/run_integ…"   4 days ago      Up 4 days                mystifying_jang
69c4441bb9e8   cloudhypervisor/dev:20220405-0   "./scripts/run_integ…"   6 days ago      Up 6 days                interesting_faraday
9d08f292852a   cloudhypervisor/dev:20220405-0   "./scripts/run_integ…"   6 days ago      Up 6 days                trusting_bartik

```

**Comment by sboeuf** [comment]
@michael2012z is this still happening? If not, feel free to close the issue.

**Comment by michael2012z** [comment]
Yes, the problem is still seen from time to time. But it's not frequent, only once every a few weeks.

**Comment by michael2012z** [comment]
As the problem doesn't impact much, and we don't have plan to invest more effort in fixing it recently. So I think it's time to close this issue.
