### ISSUE TITLE
Open to the idea of a features list?

### ISSUE THREAD

**Issue by sdake** [cloud-hypervisor/cloud-hypervisor#4121]
Hi Gang,

First off, cloud-hypervisor is pretty awesome. Like many open source projects, the documentation could use a bit of a tuneup. The biggest impact feature I can think of that would help people get moving is, strangely, a feature list.

As my first foray into producing a useful contribution to this project, I'd like to do this basic feature list. I assembled this feature list for Istio: https://istio.io/latest/docs/releases/feature-stages/

If one of the maintainers would be so kind as to accept this proposal by assigning this issue to me, I would appreciate it.

Cheers,
-steve

**Comment by iggy** [comment]
Looks like a good addition. I'd personally put the definitions below the actual list, but I can see it both ways

**Comment by sdake** [comment]
@iggy right. When I did the original work, there were only a few definitions. Now there are like 20 :) - I think we could start smaller, and tune to our liking.

Cheers,
-steve

**Comment by rbradford** [comment]
@sdake Sounds good. Looking forward to your contribution!

**Comment by sdake** [comment]
Hi @rbradford - I will be getting on this today and have a preliminary PR for review. today or tmr Thanks again for supporting this work as a reviewer. I know it may appear to be low value work. Believe me when I say it is super high value and helps steer people in the right direction on an evaluation of the projectr.

Cheers,
-steve

**Comment by sdake** [comment]
@weltling Would you be adversely affected if I worked to lift the unstable features and better define the stability guarantees from a few parts excellent release document in PR #3957.

I don't want to duplicate work, although I do want to formalize the feature list in this issue and precisely define the feature maturity as part of that list. I plan to do this as three PRs that can independently review - which can merge into one or merge independently.

- maturity model - see https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3926#issuecomment-1135004590 for a strawman.
- feature catalog - a list of features in the project
- feature maturity - a list of the feature sin the project defined with the maturity model.

For an example of what this looks like taken to the extreme, see the [Istio feature stages](https://istio.io/latest/docs/releases/feature-stages/). I am not a fan of the overly ambitious support model of Istio, but I am a fan of defining for our users exactly what the upstream support model is.

Thank you,
-steve

**Comment by sdake** [comment]
I am not big on technical writing, but it must be done to learn the codebase and the project, so thank you in advance for tolerating my sub-par technical writing expertise.

As to not cross streams with the LTS proposal, here is the initial very very basic strawman proposal. I will produce a PR of this work as a starting point for review. I will call this file `docs/feature-states.md`. This file may end up being merged with `features.md` - up to the reviewers over time. For now, I would like to keep them separate so that the PRs can be independently reviewed.

| --- | --- |
| State | Description |
| 
| DEVELOPMENT | The feature is in development, may or may not be usable, and is highly suitable for developer participation |
| EXPERIMENTAL | The feature is developed, may not be finalized, and absolutely no support guarantees, including API guarantees, are provided | 
| ALPHA | The feature is ready for evaluation, but the feature may be removed from a future release. | 
| BETA |The feature is ready for production workloads, and some basic support guarantees are made such as the feature will not be removed in the N-1 (eg last LTS release). | 
| STABLE | The feature is finalized, documented, tested both unit and functional, and strong guarantees are made about the API and its associated functionality. Any deprecation will be announced, and the feature will not be fully removed from the project until LTS+1, or LTS+2. | 
| DEPRECATED | The feature progresses from ALPHA, BETA, or STABLE to DEPRECATED meaning the feature was in the project but now part of the bit bucket. | 

This proposal was copeid from the (initial strawman proposal](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3926#issuecomment-1135004590). Please note that when we undertook this exercise in Istio, this `features.md` file was **super** hotly debated, not out of contention, but out of sheer interest, so expect a high degree of iteration before we really have the right answer for this project and its community and its scope. That ieration may need to take place over multiple PRs over multiple release cycles. FYI 👍 

Thank you,
-steve

**Comment by rbradford** [comment]
@sdake You should also look at https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/device_model.md for more inspiration (it's somewhat out of date though.)

**Comment by sdake** [comment]
@rbradford,

Thank you. I have read and read the docs directory as well as reading the src code, especially config.rs, I have plenty of notes, and working on organizing them into a PR, definitely today.

One thing that is undocumented, and I am not sure if it is intentional or not, are the perf and scale expected behaviors. I would have liked to see the performance (memory, CPU, network) with vhost user net - i.e., https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vhost-user-net-testing.md

I have found https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/performance_metrics.md of course, but I rather test the bring-up with the howtos.

If you have suggestions here, welcome to hear em. :)

Cheers,
-steve

**Comment by rbradford** [comment]
@sdake The performance you get with vhost-user-net is highly dependent on how you configure that backend you talk to with it. DPDK is the most common one and has a huge number of options for configuring it including using userspace drivers for the network interface. As the VMM we don't really provide recommendations on how the customer can use the code.

**Comment by sdake** [comment]
@rbradford thanks, I will not add scale and perf to the feature list. Also thank you for the keyword `backend` - [so obvious](https://qemu.readthedocs.io/en/latest/interop/vhost-user.html#front-end-message-types). Still, and forever, learning.

Cheers,
-steve

**Comment by weltling** [comment]
@sdake thanks for looking into this effort. Yes, a reified commitment to stability was  one of the goals in the release doc discussion. With regard to the features also - connecting feature stability to the release cycle would be a promise definition to be given to the consumer.

With the table listing the stage terminology of dev, alpha, beta and so on - i would know it more related to the release cycle as that's where it's applied to the versioning to indicate stablity. An alpha release would refer to the product version as a whole. Nevertheless, the idea of defining features stability separately could be applicable, too.

Perhaps this should be conditioned by the fact that the default features (eg. `cargo build`) would need to be always stable. Perhaps some selectors could be implemented to say "enable all alpha features" or similar. Otherwise, say modifying a default feature list to add a single `experimental` feature could be a way to go, too. In the case of the table, perhaps a table of the features would need to be updated for every release, in that case one wolud think on how to ease that to be done automatically. Having a detailed statement on the feature stability would be IMO profitable for the user to increase the project transparency.

Thanks
