### ISSUE TITLE
Hypervisor Monitor / Node Monitor design

### ISSUE THREAD

**Issue by sdake** [cloud-hypervisor/cloud-hypervisor#4242]
CHV's (desired, IMO) model, as many know, is as follows:
- generate hypervisor
- generate 1 or more storage backends
- generate 1 or more network backends
- potentially restore any CPU and memory state
- bind the hypervisor, storage, and networking backends, with any storage or CPU state into a unified thing.

These unified things, which I will call a virtual environment, need to be managed (create, delete, pause, unpause). I have proposed an addition to CHV that models the cloud-hypervisor approach (separation of concerns), in the long-term future of large-scale systems that may have 50k processors or more.

First, a diagram to see if people agree with the approach, in a separate PR.

Cheers,
-steve

**Comment by rbradford** [comment]
The term "virtual environment" is already used by https://docs.python.org/3/tutorial/venv.html so I don't think that it a good name.

**Comment by sdake** [comment]
I reused this term from Istio; served as an environmental workgroup lead. The word is fairly nebulous but in short it means, in the context of Istio, any environment where Istio could run.

Open to a different name; I think the term virtual machine is a little outdated and clunky. What chv really does is run workloads on portable environments that are virtual.

But as you have implied naming is hard; open to other ideas.
