### ISSUE TITLE
Packaging, distro support and QA for existing RPM spec

### ISSUE THREAD

**Issue by weltling** [cloud-hypervisor/cloud-hypervisor#4257]
I'd like to suggest and discuss a possible process to handle the distro availability and accompanying topics concerning the RPM spec. Last time, when I went to contribute support for several things in the existing RPM spec, it turned out the spec is not actually used for builds by the cloud-hypervisor org. There was also a suggestion to possibly exclude the spec into a separate repository.

Some experiment with help of [Open Build Service](https://build.opensuse.org/) has shown a possibility to have a separate repo on GitHub to carry the spec, while using OBS to actually build the package. OBS would also allow to reuse the same spec to support various RPM based distributions and create repositories for them. It can also build based on DEB specs, however this possibility might need to be explored more (perhaps launchpad might be another option for DEBs).

The components used for the experiment:
- OBS
  - Project and package definitions on OBS: https://build.opensuse.org/package/show/home:weltling:cloud-hypervisor/cloud-hypervisor
  - Note the `_service` file which among other tasks can carry fetch instructions
- Github 
 - https://github.com/weltling/cloud-hypervisor-obs.git

A repo generated for OpenSUSE:
https://download.opensuse.org/repositories/home:/weltling:/cloud-hypervisor/openSUSE_Tumbleweed/

Thus, it seems possible to use OBS and Github to produce packages either for QA or for production use. This can be done in a transparent manner, so then
- The latest Cloud Hypervisor releases can be made available through a repository
- Other pieces can be provided, too (fe EDK2, rust firmware, etc.)

Pro:
- Expanding the availability of the Cloud Hypervisor project
- Simple access to all needed pieces without having to compile everything by hand or dig in github repos
- Additional QA for RPMs and other specs
- Building and running on different distributions can reveal more bugs
- Specs being on github are easy to be contributed to

Contra:
- Additional effort maintaining github repo
- Additional effort maintaining build service

If this is found useful, I'd sure step up for the OBS and Github parts. OBS can have multiple users on projects, so that can be handled at the org level, too.

Thanks

**Comment by weltling** [comment]
/cc @fidencio.

Thanks

**Comment by rbradford** [comment]
Seems like a great plan to me. I can create you a repository under the `cloud-hypervisor` organisation.

**Comment by weltling** [comment]
Thanks for the check, Robert. Would it perhaps make sense to register Cloud Hypervisor to OBS? Then the package repository URLs would look like 

<pre>
https://download.opensuse.org/repositories/home:/<b>cloud-hypervisor</b>/openSUSE_Tumbleweed/
</pre>

As that would be the only home project and the official location. Right now it's a subproject under my account there, thus the corresponding URL segment. OBS also allows to add more folks to the project, that would probably make sense at some point. 


Perhaps the way forward would be then for me to continue adding more packages and distros. It might be also best using same Rust version for all and see for other dependencies, so the outcome is most consistent. once there's some more packages and distros supported, one could move the Github repo with specs under the `cloud-hypervisor` organization and see what would suit best to handle things under OBS.

Thanks!

**Comment by rbradford** [comment]
> Thanks for the check, Robert. Would it perhaps make sense to register Cloud Hypervisor to OBS? Then the package repository URLs would look like
> 

Yes, sounds good to me!

**Comment by rbradford** [comment]
@weltling Good work. Let me know if you need me to take any action.

**Comment by bkircher** [comment]
@weltling I could help with Fedora and possibly CentOS Stream. A cross-distribution spec file would be great.

For Fedora, I could start testing with a copr (https://copr.fedorainfracloud.org/) and when everything works start the review process to get it into the next Fedora release

**Comment by weltling** [comment]
Thanks, @bkircher, that's a great suggestion! I'll definitely ping you in this regard.

**Comment by weltling** [comment]
An update on the last progress:

- Pulled an upgrade to CloudyHypervisor 25.0 
- Builds for Fedora 35, 36 and Rawhide are available
- Added EDK2 package

Still keeping things in my personal subproject:

https://download.opensuse.org/repositories/home:/weltling:/cloud-hypervisor/

Next I'd go for:

- Add Ubuntu and maybe Debian
- Possibly add CentOS stream
- Possibly add OpenSUSE 15.3

For Debian based, the issue is that the Rust toolchain in the distro is not really maintained, 1.59.0 is only kept alive to build Firefox. From a previous experiment, it seems also some other (and almost older distro versions) would have no suitable Rust toolchain version. I'd tend to package an official binary toolchain for those cases, but still experimenting on that. Seems also some other dependencies might need an extra work - one i saw issues wis was an older `iasl` version that would be not suitable for EDK2.

Anyway, that's the progress for today. Once i sorted the Rust toolchain and there are at least Ubuntu builds, I'd move things to the cloud-hypervisor home project, as discussed before. 

@bkircher for the Fedora builds - those available today should be already usable, so `dnf install cloud-hypervisor edk2-cloud-hypervisor` would pull all things needed for the checks.

Thanks!

**Comment by weltling** [comment]
Status update below.

- Packaged the latest CH version
- Packaged EDK2
- Packaged hypervisor-fw (x86 and binary only)

Package availability: 

- Debian 10 to unstable and Ubuntu 18.04 to the latest LTS
- CentOS 9 stream
- OpenSUSE 15.3 and 15.4 

The installation instructions for various package managers are in the [README](https://github.com/weltling/cloud-hypervisor-obs).

With the previously available OpenSUSE and Fedora, seems the base is good to start moving forward the previously reserved https://build.opensuse.org/project/show/home:cloud-hypervisor. More distros can be added later, if required. For now, the coverage seems fine for the most popular.

Note, that due to the lack of the proper Rust toolchain support in Debian based distros, i went for packaging the official Rust binaries. Currently using 1.62.1. All other supported distro versions have at least 1.60.0, so using the distro provided toolchain builds there. The vendored crates are same in all cases. Also, some backports was needed for dependencies to get things done (iasl, nasm). Those backported packages won't be published as long as they're not needed at the runtime. The current OBS project is here https://build.opensuse.org/project/show/home:weltling:cloud-hypervisor.

Next steps would be these:
- Checks on available packages and distro versions would be great, please see [README](https://github.com/weltling/cloud-hypervisor-obs)
- Moving [cloud-hypervisor-obs](https://github.com/weltling/cloud-hypervisor-obs) under cloud-hypervisor org
- Moving all the work to https://build.opensuse.org/project/show/home:cloud-hypervisor (i'll still keep the one in my account as a playground)
- Adding more folks to the OBS project

In a further perspective, integrating github actions to trigger an OBS build would be on the plate. While doable, seems some points might need more clarification prior doing it. For now, the github repo with the specs can sure accept contributions, however the OBS part needs to be handled separately, including sometimes build triggered manually.

Please let me know, if i miss something.

Thanks

**Comment by weltling** [comment]
I've now filled all the packages from my toy project into the `cloud-hypervisor` account in OBS:

https://download.opensuse.org/repositories/home:/cloud-hypervisor/

It would be great to hear any feedback after any package has been installed on any distro.

At this point, moving https://github.com/weltling/cloud-hypervisor-obs under the `cloud-hypervisor` org on github should be convenient.

I keep all the packages forked in my personal account, which i'll use as an intermediate playground. In parallel, i'm also discovering the staging process in OBS and a way to trigger builds from github. There is a documentation around this, but it needs some excercise, i think:

https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.source_service.html#sec.obs.sserv.token_usage

Once cloud-hypervisor-obs is moved, one could probably proceed with adding some documentation and user notes and closing this issue.

Probably also, it wolud make sense someone from the github org to join OBS project. Basically, creating an OBS account, one could be added to users https://build.opensuse.org/project/users/home:cloud-hypervisor.

Thanks

**Comment by rbradford** [comment]
@weltling I created the repo for you and gave you permission

**Comment by weltling** [comment]
@rbradford thanks! I'll move the existing specs there and continue on that base.

Thanks

**Comment by weltling** [comment]
With regard to the OBS efforts - it looks like this issue nears the finalization. All the SPECs are migrated to the dedicated `obs-packaging` repo. Last week also, I've pulled the update to CH 26.0. At this point, I'd see some points to finalize yet:

- Document the presence of the disro package
- Remove the bundled SPEC??
- Possibly add more folks to the OBS project

For the doc - not sure it deserves a separate page or just a short note on the readme, please advise.

Maybe there's more, from my POV at least those above would make sense. Further work on the OBS project will be then happening and tracked in the `obs-packaging` repo. There are already some tickets to be implemented there. 

Thanks

**Comment by rbradford** [comment]
Cool, please open a PR to remove the bundled spec file.
