### ISSUE TITLE
VM can't boot from spdk bdevs

### ISSUE THREAD

**Issue by maydaycc** [cloud-hypervisor/cloud-hypervisor#4285]
**Describe the bug**
I tried to start a VM from spdk bdev with rust-hypervisor-firmware, but the firmware reports can't find EFI partition.
This seems to be caused by the spdk vhost backend not knowing the correct queue length.
After modify the setup_vhost_user func as below，the bootloader can be executed successfully, but spdk vhost will crash after receive "VHOST_USER_RESET_OWNER" message.

```
self.vu.set_vring_num(queue_index, queue.max_size()) ->  self.vu.set_vring_num(queue_index, queue.state.size)

queue_size: queues[0].max_size()  ->  queue_size: queues[0].state.size
```

**To Reproduce**
start a vm from spdk bdev

**Version**
latest

**Comment by liuw** [comment]
> > > Thanks for opening this issue! Could you please describe the setup you used for creating the SPDK bdev? And second thing, have you tried using direct kernel boot to see if it makes a difference?
> > 
> > 
> > SPDK bdev was created like this
> > ./build/bin/vhost -S /var/tmp -s 1024 -m 0x3 &
> > ./scripts/rpc.py bdev_rbd_create rbd rbd_1 512 -b Ceph0
> > ./scripts/rpc.py vhost_create_blk_controller --cpumask 0x1 vhost.0 Ceph0
> 
> Ok thanks for the reference.
> 
> > I have tried using "--kernel vmlinux.bin" boot a Linux VM successfully, but I can't boot Windows VM with "-- kernel CLOUDHV.fd". The rust-hypervisor-firmware can boot both Linux and Windows VM when boot disk not a SPDK bdev.
> 
> Are you sure `CLOUDHV.fd` cannot boot Windows VMs? Our CI validates Windows VMs can be booted, that's why I'm surprised you had some issues with that.

The Windows image needs to have VirtIO drivers baked in. Stock Windows does not ship VirtIO drivers.

**Comment by maydaycc** [comment]
> > > > Thanks for opening this issue! Could you please describe the setup you used for creating the SPDK bdev? And second thing, have you tried using direct kernel boot to see if it makes a difference?
> > > 
> > > 
> > > SPDK bdev was created like this
> > > ./build/bin/vhost -S /var/tmp -s 1024 -m 0x3 &
> > > ./scripts/rpc.py bdev_rbd_create rbd rbd_1 512 -b Ceph0
> > > ./scripts/rpc.py vhost_create_blk_controller --cpumask 0x1 vhost.0 Ceph0
> > 
> > 
> > Ok thanks for the reference.
> > > I have tried using "--kernel vmlinux.bin" boot a Linux VM successfully, but I can't boot Windows VM with "-- kernel CLOUDHV.fd". The rust-hypervisor-firmware can boot both Linux and Windows VM when boot disk not a SPDK bdev.
> > 
> > 
> > Are you sure `CLOUDHV.fd` cannot boot Windows VMs? Our CI validates Windows VMs can be booted, that's why I'm surprised you had some issues with that.
> 
> The Windows image needs to have VirtIO drivers baked in. Stock Windows does not ship VirtIO drivers.

I'm sure the Windows image has virtio driver, I can boot it using--disk path_to_image_file.

**Comment by sboeuf** [comment]
@maydaycc I think I fixed your issue with the following PR: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4286
Please confirm it works on your side.

**Comment by sboeuf** [comment]
Just posting the list of commands I had to run in order to create a SPDK backend backed by a RAW image called `jammy-server-cloudimg.raw` on my system:
```
git clone https://github.com/spdk/spdk
cd spdk
git submodule update --init
sudo ./scripts/pkgdep.sh
./configure
make
echo 4096 | sudo tee /proc/sys/vm/nr_hugepages
sudo HUGEMEM=2048 scripts/setup.sh
sudo ./build/bin/vhost -S /var/tmp -s 1024 -m 0x3 &
sudo scripts/rpc.py bdev_aio_create /home/user/jammy-server-cloudimg.raw aio0 512
sudo scripts/rpc.py vhost_create_blk_controller --cpumask 0x1 vhost.1 aio0
```
And here is the Cloud Hypervisor command I used to boot from this backend with the Rust Hypervisor Firmware:
```
sudo ./target/debug/cloud-hypervisor \
--cpus boot=2 \
--memory size=1G,hugepages=on,shared=on \
--kernel /home/user/hypervisor-fw \
--disk vhost_user=true,socket=/var/tmp/vhost.1,num_queues=1,queue_size=1024 \
--console off \
--serial tty
```

**Comment by maydaycc** [comment]
@sboeuf 

If I use hypervisor-fw boot Windows VM I will meet bluescreen problem and if I use CLOUDHV.fd  vring will stuck in disabled status until I killed  the cloud-hypervisor。

**Comment by maydaycc** [comment]
> @sboeuf
> 
> If I use hypervisor-fw boot Windows VM I will meet bluescreen problem and if I use CLOUDHV.fd vring will stuck in disabled status until I killed the cloud-hypervisor。

It seems that the image file is corrupt.

**Comment by maydaycc** [comment]
![spdk bdev](https://user-images.githubusercontent.com/26605513/177823917-b7543955-24fc-4d72-b14e-a1a6400faa6d.png)
@sboeuf @rbradford @liuw

**Comment by liuw** [comment]
Does this only happen on Windows?

**Comment by maydaycc** [comment]
> had a wrong assumption about the number of scatter-gathered list in its block backend. It was never discovered because virtio-blk worked differently on Linux.

QEMU is a little different. It can pass the MD5 verification test, but each time the NTFS file system is formatted, different free space can be obtained. For example, 100GB disk may only have 30GB free space for the first format, and 60GB for the second format.

**Comment by maydaycc** [comment]
![qemu-spdk](https://user-images.githubusercontent.com/26605513/177980136-77ca1e0d-40eb-421b-9542-057772f322c1.png)

**Comment by maydaycc** [comment]
![qemu-spdk-2](https://user-images.githubusercontent.com/26605513/177980346-97e7d743-622e-4b5f-ade6-8d9773cd72b6.png)

**Comment by liuw** [comment]
This is unfortunate. It seems that Windows QEMU is buggy in a different way.

I cannot say for sure if this is an issue in QEMU/CH or in the VirtIO driver for Windows. When I searched "windows guest spdk bdev disk", it showed me quite a issues. I'm no SPDK experts to discern if they are relevant.

At this point I think it requires hooking up debuggers to figure out what's wrong.

**Comment by rbradford** [comment]
What's the status on this issue? Does the title need updating?

**Comment by sboeuf** [comment]
@maydaycc please update the issue title, or simply close it if you found out a way to fix it.

**Comment by rbradford** [comment]
Closing this issue as there is no response.
