### ISSUE TITLE
Be more conservative in bumping MSRV

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#4318]
MSRV was recently bumped from 1.56 to 1.60 due to `pnet`, but `pnet` is only a dev dependency used in tests.

I suggest if that happens we should stick to a lower version of the crate so that we don't have to bump MSRV. That seems to be a worthy cost to pay to ease the adoption of CH, because upgrading Rust toolchains in any production environment requires validation.

Thoughts?

CC @russell-islam

**Comment by jinankjain** [comment]
Shouldn't we be bit more proactive in testing Rust's latest stable versions? I mean this time it was test dependency but in future some major crate might decide to move to future stable versions. To make this process smooth may be we should start running the CI on latest stable version of Rust as well to catch the issues/regression in advance. And once have fair confidence in a new stable version we can decide to bump it.

**Comment by liuw** [comment]
> Shouldn't we be bit more proactive in testing Rust's latest stable versions? I mean this time it was test dependency but in future some major crate might decide to move to future stable versions. To make this process smooth may be we should start running the CI on latest stable version of Rust as well to catch the issues/regression in advance. And once have fair confidence in a new stable version we can decide to bump it.

Testing is another story. Upstream CI does update its Rust compiler quite often. There are even beta compiler tests.

This is orthogonal to what the MSRV should be. 1.62 should compiles code that works with 1.56 just fine.

**Comment by rbradford** [comment]
So in the dev-dependencies/pnet case I can see two paths forward to lowering the MSRV:

1. (My preference) remove the pnet dependency
2. Don't test the buildability of tests with MSRV - this seems like it would increase the complexity of our test matrix and let bad stuff in.

Long term, perhaps we could say that we try to limit MSRV bumps to once a year (perhaps when there is a new Rust edition out with features we want to use.

**Comment by liuw** [comment]
> So in the dev-dependencies/pnet case I can see two paths forward to lowering the MSRV:
> 
> 1. (My preference) remove the pnet dependency
> 2. Don't test the buildability of tests with MSRV - this seems like it would increase the complexity of our test matrix and let bad stuff in.
> 
> Long term, perhaps we could say that we try to limit MSRV bumps to once a year (perhaps when there is a new Rust edition out with features we want to use.

I think 1 is also my preference.

I would avoid setting a fixed timeline for MSRV bump, rather, like you said, make it dependent on if there are features we want. Whatever bumps we do should be weighted carefully.

P.S. I've been waiting for async fn in trait to see what we can achieve with (at least partially) turn the I/O path into async -- this is a bold idea which warrants its own tracking issue.

**Comment by russell-islam** [comment]
Most the versions are updated by bot blindly without considering a big feature. It is good for development but when it comes to production it's a burden. Lots of vendor are behind of the rust latest. Typically Linux Ditsro uses a bit lower version than upstream.

**Comment by rbradford** [comment]
> Most the versions are updated by bot blindly without considering a big feature. It is good for development but when it comes to production it's a burden. Lots of vendor are behind of the rust latest. Typically Linux Ditsro uses a bit lower version than upstream.

Using the latest versions for dependencies is something that is required by our security process.

**Comment by rbradford** [comment]
I did some investigation on whether the pnet issue was transient. Unfortunately the newly added dependency on `serde_with` also doesn't compile with 1.56. 1.60 added support optional feature dependencies so I expect many crates will set their MSRV to that: https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features

**Comment by liuw** [comment]
> I did some investigation on whether the pnet issue was transient. Unfortunately the newly added dependency on `serde_with` also doesn't compile with 1.56. 1.60 added support optional feature dependencies so I expect many crates will set their MSRV to that: https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features

Yep, it decided to use the new optional feature dependency. That's nice but does not directly affect the correctness of the code.

I would actually like to refer to this https://gitlab.torproject.org/tpo/core/arti#minimum-supported-rust-version. The tor project clearly spell out their MSRV policy. Cloud Hypervisor should do the same for whatever policy that may be.

**Comment by rbradford** [comment]
> > I did some investigation on whether the pnet issue was transient. Unfortunately the newly added dependency on `serde_with` also doesn't compile with 1.56. 1.60 added support optional feature dependencies so I expect many crates will set their MSRV to that: https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features
> 
> Yep, it decided to use the new optional feature dependency. That's nice but does not directly affect the correctness of the code.

Right but we can't update to dependency versions that have a newer MSRV (the build fails in a frustratingly cryptic way). I think we'll see a bunch of bumps to 1.62 in libraries as there is now this `#[derive(Default)]` for enums. 

> I would actually like to refer to this https://gitlab.torproject.org/tpo/core/arti#minimum-supported-rust-version. The tor project clearly spells out their MSRV policy. Cloud Hypervisor should do the same for whatever policy that may be.

I would propose we update MSRV if:

a.) A dependency requires it,
b.) If we want to use a new feature and that MSRV is at least 6 months old,
c.) There is a security issue that is addressed by the toolchain update

**Comment by jinankjain** [comment]
> a.) A dependency requires it,

We can be a bit more conservative around dependencies. Only real dev dependency updates should call for MSRV updates if they need it. For the test framework, we can afford to stick to the older version.

**Comment by rbradford** [comment]
> > a.) A dependency requires it,
> 
> We can be a bit more conservative around dependencies. Only real dev dependency updates should call for MSRV updates if they need it. For the test framework, we can afford to stick to the older version.

I was going to agree with you about `dev-dependencies`. But it seems that you can't compile even if you only try and build a single binary:

```
marvin:~/src/cloud-hypervisor (main)$ cargo rustc --locked --bin cloud-hypervisor -- -D warnings
    Updating crates.io index
error: failed to select a version for the requirement `pnet = "=0.31.0"`
candidate versions found which didn't match: 0.29.0, 0.28.0, 0.27.2, ...
location searched: crates.io index
required by package `net_util v0.1.0 (/home/rob/src/cloud-hypervisor/net_util)`
```

So unless i'm missing something having such a rule doesn't really help.

**Comment by rbradford** [comment]
> I would propose we update MSRV if:
> 
> a.) A dependency requires it, b.) If we want to use a new feature and that MSRV is at least 6 months old, c.) There is a security issue that is addressed by the toolchain update

Is everyone happy with this as our MSRV policy?

**Comment by sboeuf** [comment]
> > I would propose we update MSRV if:
> > a.) A dependency requires it, b.) If we want to use a new feature and that MSRV is at least 6 months old, c.) There is a security issue that is addressed by the toolchain update
> 
> Is everyone happy with this as our MSRV policy?

Sounds good to me!
