### ISSUE TITLE
Passing data blob via SMBIOS type 11 OEM string

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#4319]
Lennart (of systemd fame) reached out and told me about a scheme the systemd folks have been working on.

They have this concept of "credentials" in systemd http://systemd.io/CREDENTIALS/. They think that using SMBIOS type 11 OEM string to pass data to VM is superior to `fw_cfg` or other mechanisms (over the network, ephemeral disk, CD drive).

The systemd PR is here https://github.com/systemd/systemd/pull/24005. QEMU already supports this scheme per Lennart.

One concern I have is it effectively locks up a portion of the guest's memory, but he says there is a cap right now. And the expectation is the interface is only used to pass configuration / secrets, which is supposed to be small in nature.

Is there an interest to do this in Cloud Hypervisor? It doesn't look too complex on the surface -- what we need is to make that SMBIOS string configurable by users.

**Comment by rbradford** [comment]
@liuw There is some SMBIOS control through options on `--platform` so that would be the logical place I think.

**Comment by cryptoknight** [comment]
Is this how QEMU secrets are passed?: https://www.qemu.org/docs/master/system/secrets.html

Having something analogous to that API would be nice.

**Comment by liuw** [comment]
> Is this how QEMU secrets are passed?: https://www.qemu.org/docs/master/system/secrets.html
> 
> Having something analogous to that API would be nice.

I don't think so.

There are some examples in systemd's PR to show how it is used with QEMU.

**Comment by liuw** [comment]
Cool. I will find someone to implement this.

**Comment by liuw** [comment]
@rbradford @sboeuf what would be your preferred syntax? Users should be able to specify multiple strings.

```
--platform oem_string="ABC",oem_string="This is a string"
```

**Comment by rbradford** [comment]
> @rbradford @sboeuf what would be your preferred syntax? Users should be able to specify multiple strings.
> 
> ```
> --platform oem_string="ABC",oem_string="This is a string"
> ```
> 

I think we've used `[...,...]` syntax in the past for similar lists. I guess this would need to be a ` Vec<String>` in `PlatformConfig` ?

**Comment by sboeuf** [comment]
> > @rbradford @sboeuf what would be your preferred syntax? Users should be able to specify multiple strings.
> > ```
> > --platform oem_string="ABC",oem_string="This is a string"
> > ```
> 
> I think we've used `[...,...]` syntax in the past for similar lists. I guess this would need to be a ` Vec<String>` in `PlatformConfig` ?

Yes you can rely on https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/memory.md#cpus as an example.

**Comment by liuw** [comment]
> > > @rbradford @sboeuf what would be your preferred syntax? Users should be able to specify multiple strings.
> > > ```
> > > --platform oem_string="ABC",oem_string="This is a string"
> > > ```
> > 
> > 
> > I think we've used `[...,...]` syntax in the past for similar lists. I guess this would need to be a ` Vec<String>` in `PlatformConfig` ?
> 
> Yes you can rely on https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/memory.md#cpus as an example.

Like this

```
--platform iommu_segments=1,num_pci_segments=2,oem_string=["first string","second string"]
```

?

**Comment by sboeuf** [comment]
> > > > @rbradford @sboeuf what would be your preferred syntax? Users should be able to specify multiple strings.
> > > > ```
> > > > --platform oem_string="ABC",oem_string="This is a string"
> > > > ```
> > > 
> > > 
> > > I think we've used `[...,...]` syntax in the past for similar lists. I guess this would need to be a ` Vec<String>` in `PlatformConfig` ?
> > 
> > 
> > Yes you can rely on https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/memory.md#cpus as an example.
> 
> Like this
> 
> ```
> --platform iommu_segments=1,num_pci_segments=2,oem_string=["first string","second string"]
> ```
> 
> ?

That's the idea but I'm worried the space between `first` and `string` won't be handled correctly by the parser.
