### ISSUE TITLE
Port Cloud Hypervisor to run on Windows

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#4330]
I thought about this today. It does not seem to difficult to use Windows Hypervisor Platform (https://docs.microsoft.com/en-us/virtualization/api/hypervisor-platform/hypervisor-platform) to run a basic guest without any I/O -- like booting a kernel and a ramdisk and a busybox process.

One useful crate is https://github.com/insula-rs/libwhp.git. It provides some bindings, which should be enough to get us started.

I'm not very familiar with Windows' I/O machineries. More to add once I figured something out.

**Comment by liuw** [comment]
> The interaction with the underlying hypervisor is only one piece of the problem. There's a lot of work to ensure you can abstract the system calls between Linux and Windows.

I don't follow. Cloud Hypervisor does not issue that many system calls directly, right?

**Comment by sboeuf** [comment]
> > The interaction with the underlying hypervisor is only one piece of the problem. There's a lot of work to ensure you can abstract the system calls between Linux and Windows.
> 
> I don't follow. Cloud Hypervisor does not issue that many system calls directly, right?

You're right I didn't realize Rust already provides the abstraction for most of these. From the top of my head I can think about passing a file descriptor with SCM_RIGHTS is Linux specific, but I think there are other Linux specific operations in there. You would also have to look at the crates we depend on to make sure they don't issue direct system calls and that they don't expect Linux only.

**Comment by liuw** [comment]
I gave it a shot. The first obstacle is `micro_http`, which is UNIX only. :-)

**Comment by rbradford** [comment]
Although i'm sure this would be fun experiment and probably doable I think it would come at a great cost of code complexity. Do you think there is demand from CSPs to do this?

**Comment by liuw** [comment]
No, there is no need right now. It is an experiment for us at MSFT as well.

I expect someone will want to run Cloud Hypervisor on Windows at some point. We may as well try to list the gaps while we can.

**Comment by jinankjain** [comment]
Once we remove micro-http server there are few more crates which would need refactoring:

- epoll
- seccompiler
- io-uring

**Comment by rbradford** [comment]
@liuw Do you have a plan for action on this? Or could this issue be closed?

**Comment by liuw** [comment]
Closing this for now. I didn't have the time to look into this yet..
