### ISSUE TITLE
test_virtio_balloon_deflate_on_oom is flaky

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#4336]
See: 

https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/job/cloud-hypervisor/job/main/1297/execution/node/189/log/
https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/job/cloud-hypervisor/job/main/1294/execution/node/223/log/

And I think it was reported flaky on some PR builds too.

**Comment by liuw** [comment]
Yes I encountered its flakiness during my development work for the unified binary.

**Comment by rbradford** [comment]
Still flaky: https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/job/cloud-hypervisor/job/main/1315/execution/node/226/log/

**Comment by sboeuf** [comment]
Oh... Well maybe it's related to the fact the `stress` command we run in the guest isn't always triggering the OOM.

**Comment by rbradford** [comment]
> 

I would enhance the debugging of the test to see where the true cause of the failure is.

**Comment by liuw** [comment]
Have you tried using `echo f > /proc/sysrq`?

**Comment by sboeuf** [comment]
I guess you meant `echo f > /proc/sysrq-trigger`, right?
I didn't know about this but it seems to be a very convenient way to trigger a manual OOM and I can see the balloon being slightly deflated after each time I trigger the OOM. This might be a better approach than using `stress`.

**Comment by liuw** [comment]
Yes. I meant `sysrq-trigger`. I was doing other things while reading this issue. :-(

**Comment by rbradford** [comment]
Fixed by #4361
