### ISSUE TITLE
VFIO issues with NVIDIA T4 card

### ISSUE THREAD

**Issue by Cordius** [cloud-hypervisor/cloud-hypervisor#434]
I am reading the code in the vfio library and I'm curious about I can't find anywhere to handle intx type interrupts.   
Can anyone help me understand how the interrupt worked with vfio here?  

In addition, I feel we need a new field in struct VfioPciDevice to indicate the current interrupt type we used as below:  
```rust
enum VfioPciInterruptType {
    VFIO_INT_INTx,
    VFIO_INT_MSI,
    VFIO_INT_MSIX
}

pub struct VfioPciDevice {
    ...
    current_irq_type: VfioPciInterruptType,
}
``` 
Then we update the field eachtime we disable/enable msi/msix/intx. Finally we can disable interrupts correctly in `Drop for VfioPciDevice` instead of reporting a error "Could not disable MSI-X". Of course, the flag in `disable_irq` is wrong which should be `ACTION_TRIGGER | DATA_NONE` .

@sboeuf

**Comment by sboeuf** [comment]
Hi @Cordius 
Thanks for looking at the code related to MSI.
>I am reading the code in the vfio library and I'm curious about I can't find anywhere to handle intx type interrupts.
Can anyone help me understand how the interrupt worked with vfio here?

It's simple, we decided not to support INTx for VFIO, and we're not planning to do so because we think that all recent PCI devices support MSI or MSI-X.

>In addition, I feel we need a new field in struct VfioPciDevice to indicate the current interrupt type we used

If you feel there's something that need to fixed, please go ahead and send a PR, it'll be easier for the team to review it.
And I'm glad to see you're fixing some error/warnings that I've been seeing but haven't had the time to fix so far :)

**Comment by Cordius** [comment]
> 
> 
> Hi @Cordius
> Thanks for looking at the code related to MSI.
> 
> > I am reading the code in the vfio library and I'm curious about I can't find anywhere to handle intx type interrupts.
> > Can anyone help me understand how the interrupt worked with vfio here?
> 
> It's simple, we decided not to support INTx for VFIO, and we're not planning to do so because we think that all recent PCI devices support MSI or MSI-X.
Well, it seems that NVIDIA GPUs use the INTx instead of MSI/MSI-X currently.

**Comment by sboeuf** [comment]
@Cordius 
>Well, it seems that NVIDIA GPUs use the INTx instead of MSI/MSI-X currently.

Really? Oh that's interesting then. Do you know why they actually do that?

Do you have some example of PCI cards?

**Comment by sboeuf** [comment]
@Cordius any chance you could tackle the `MSI`/`MSI-X` error/warning messages? It'd be nice to have a PR from you since you have a pretty good idea on how to solve those.

**Comment by Cordius** [comment]
> 
> 
> @Cordius
> 
> > Well, it seems that NVIDIA GPUs use the INTx instead of MSI/MSI-X currently.
> 
> Really? Oh that's interesting then. Do you know why they actually do that?
> 
> Do you have some example of PCI cards?
I have a Tesla T4 card. Command `lspci` shows that the card uses the INTx irq, but when I use the card with cloud hypervisor, I find the irq isn't registered. 
However, I don't know why NV vstill uses the INTx.

**Comment by Cordius** [comment]
> 
> 
> @Cordius any chance you could tackle the `MSI`/`MSI-X` error/warning messages? It'd be nice to have a PR from you since you have a pretty good idea on how to solve those.  

Sorry, I have been attending a trainning these days, and have not try to handle the messages.

**Comment by sboeuf** [comment]
@Cordius 

I found some Nvidia documentation about the T4 card [here](https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/tesla-t4/t4-tensor-core-product-brief.pdf). On page 8, it says `MSI-X Supported` and `MSI Not Supported`, so I would expect `MSI-X` to be present.
Could you dump the output of the `lspci` command you get on the host regarding the T4 card?
I'd like to take a look at the information provided.

**Comment by Cordius** [comment]
> Could you dump the output of the `lspci` command you get on the host regarding the T4 card?
> I'd like to take a look at the information provided.  

```
[root@iZ8vb85pir06gbtnh3tn74Z ~]# lspci -s 3d:00.0 -vvv
3d:00.0 3D controller: NVIDIA Corporation Device 1eb8 (rev a1)
        Subsystem: NVIDIA Corporation Device 12a2
        Physical Slot: 0
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0
        Interrupt: pin A routed to IRQ 30
        NUMA node: 0
        Region 0: Memory at b7000000 (32-bit, non-prefetchable) [size=16M]
        Region 1: Memory at 38bfc0000000 (64-bit, prefetchable) [size=256M]
        Region 3: Memory at 38bff0000000 (64-bit, prefetchable) [size=32M]
        Capabilities: [60] Power Management version 3
                Flags: PMEClk- DSI- D1- D2- AuxCurrent=375mA PME(D0+,D1-,D2-,D3hot+,D3cold-)
                Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
        Capabilities: [68] #00 [0080]
        Capabilities: [78] Express (v2) Endpoint, MSI 00
                DevCap: MaxPayload 256 bytes, PhantFunc 0, Latency L0s unlimited, L1 <64us
                        ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset- SlotPowerLimit 25.000W
                DevCtl: Report errors: Correctable- Non-Fatal- Fatal- Unsupported-
                        RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop-
                        MaxPayload 256 bytes, MaxReadReq 512 bytes
                DevSta: CorrErr- UncorrErr- FatalErr- UnsuppReq- AuxPwr- TransPend-
                LnkCap: Port #0, Speed 8GT/s, Width x16, ASPM not supported, Exit Latency L0s <512ns, L1 <4us
                        ClockPM+ Surprise- LLActRep- BwNot- ASPMOptComp+
                LnkCtl: ASPM Disabled; RCB 64 bytes Disabled- CommClk-
                        ExtSynch- ClockPM+ AutWidDis- BWInt- AutBWInt-
                LnkSta: Speed 2.5GT/s, Width x16, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
                DevCap2: Completion Timeout: Range AB, TimeoutDis+, LTR+, OBFF Via message
                DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis-, LTR-, OBFF Disabled
                LnkCtl2: Target Link Speed: 8GT/s, EnterCompliance- SpeedDis-
                         Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
                         Compliance De-emphasis: -6dB
                LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete+, EqualizationPhase1+
                         EqualizationPhase2+, EqualizationPhase3+, LinkEqualizationRequest-
        Capabilities: [c8] MSI-X: Enable+ Count=6 Masked-
                Vector table: BAR=0 offset=00b90000
                PBA: BAR=0 offset=00ba0000
        Capabilities: [100 v1] Virtual Channel
                Caps:   LPEVC=0 RefClk=100ns PATEntryBits=1
                Arb:    Fixed- WRR32- WRR64- WRR128-
                Ctrl:   ArbSelect=Fixed
                Status: InProgress-
                VC0:    Caps:   PATOffset=00 MaxTimeSlots=1 RejSnoopTrans-
                        Arb:    Fixed- WRR32- WRR64- WRR128- TWRR128- WRR256-
                        Ctrl:   Enable+ ID=0 ArbSelect=Fixed TC/VC=01
                        Status: NegoPending- InProgress-
        Capabilities: [250 v1] Latency Tolerance Reporting
                Max snoop latency: 0ns
                Max no snoop latency: 0ns
        Capabilities: [258 v1] L1 PM Substates
                L1SubCap: PCI-PM_L1.2- PCI-PM_L1.1- ASPM_L1.2- ASPM_L1.1- L1_PM_Substates+
        Capabilities: [128 v1] Power Budgeting <?>
        Capabilities: [420 v2] Advanced Error Reporting
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP+ SDES+ TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF+ MalfTLP+ ECRC- UnsupReq- ACSViol-
                CESta:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr-
                CEMsk:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr+
                AERCap: First Error Pointer: 00, GenCap- CGenEn- ChkCap- ChkEn-
        Capabilities: [600 v1] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
        Capabilities: [900 v1] #19
        Capabilities: [bb0 v1] #15
        Capabilities: [bcc v1] Single Root I/O Virtualization (SR-IOV)
                IOVCap: Migration-, Interrupt Message Number: 000
                IOVCtl: Enable- Migration- Interrupt- MSE- ARIHierarchy+
                IOVSta: Migration-
                Initial VFs: 16, Total VFs: 16, Number of VFs: 0, Function Dependency Link: 00
                VF offset: 4, stride: 1, Device ID: 0000
                Supported Page Size: 00000573, System Page Size: 00000001
                Region 0: Memory at b8000000 (32-bit, non-prefetchable)
                Region 1: Memory at 000038bec0000000 (64-bit, prefetchable)
                Region 3: Memory at 000038bfd0000000 (64-bit, prefetchable)
                VF Migration: offset: 00000000, BIR: 0
        Capabilities: [c14 v1] Alternative Routing-ID Interpretation (ARI)
                ARICap: MFVC- ACS-, Next Function: 1
                ARICtl: MFVC- ACS-, Function Group: 0
        Kernel driver in use: nvidia
        Kernel modules: nvidia_vgpu_vfio, nvidia
```

**Comment by sboeuf** [comment]
@Cordius oh great!
So you see, your card support MSI-X because of what is listed here:
```
Capabilities: [c8] MSI-X: Enable+ Count=6 Masked-
                Vector table: BAR=0 offset=00b90000
                PBA: BAR=0 offset=00ba0000
```
It does support 6 vectors, and it's located on the BAR0 of this device.

Now the question is, why is it not working with `cloud-hypervisor`. Looking into the document I provided earlier, it says the card supports SR-IOV, and we can see that from `lspci` too.
But we don't support passing the physical function yet, there are still some details which need to be addressed.
Could you try passing a virtual function as the device that you're passing through? You have 16 VF on this card, just pick one and pass it the way you would pass a regular PCI device with `--device /sys/bus/pci/....`

**Comment by Cordius** [comment]
@sboeuf 

> So you see, your card support MSI-X because of what is listed here:
> 
> ```
> Capabilities: [c8] MSI-X: Enable+ Count=6 Masked-
>                 Vector table: BAR=0 offset=00b90000
>                 PBA: BAR=0 offset=00ba0000
> ```
> 
> It does support 6 vectors, and it's located on the BAR0 of this device.  

So I just don't need to care about the `pin A` ?
```
Interrupt: pin A routed to IRQ 30
```
Do you mean that it's no matter whether we register a handler for pin A or not ?  

> Could you try passing a virtual function as the device that you're passing through? You have 16 VF on this card, just pick one and pass it the way you would pass a regular PCI device with `--device /sys/bus/pci/....`  

Sorry I didn't get a PF driver, so I can't create a virtual function.

**Comment by sboeuf** [comment]
@Cordius 
>So I just don't need to care about the pin A ?

Exactly, because there's MSI-X, `cloud-hypervisor` will use it for interrupts.

>Do you mean that it's no matter whether we register a handler for pin A or not ?

The host kernel might have chosen to register INTx, it's not going to affect how `cloud-hypervisor` behaves since the device supports MSI-X.

>Sorry I didn't get a PF driver, so I can't create a virtual function.

What do you mean? Aren't you able to create a VF out of the PF?
Try something like:
```
echo 3 > /sys/bus/pci/devices/0000:3d:00.0/sriov_numvfs
```
This should create 3 VFs out of your card, and you should be able to see them from a new call into `lspci`.

Make sure you refer one of the 3 newly created device from the `cloud-hypervisor` CLI.

**Comment by Cordius** [comment]
> > Sorry I didn't get a PF driver, so I can't create a virtual function.
> 
> What do you mean? Aren't you able to create a VF out of the PF?
> Try something like:
> 
> ```
> echo 3 > /sys/bus/pci/devices/0000:3d:00.0/sriov_numvfs
> ```
> 
> This should create 3 VFs out of your card, and you should be able to see them from a new call into `lspci`.  

To create a VF out of  the PF, I need a proper PF driver otherwise I will only get a error like that:
```
nvidia 0000:3d:00.0: Driver doesn't support SRIOV configuration via sysfs
```
The driver I get from NVIDIA's site don't support SRIOV configuration.

**Comment by sboeuf** [comment]
>The driver I get from NVIDIA's site don't support SRIOV configuration.

Ok I understand.

So what happens when you pass the PF device directly into `cloud-hypervisor`? Maybe post some logs here.

**Comment by Cordius** [comment]
> So what happens when you pass the PF device directly into `cloud-hypervisor`? Maybe post some logs here.  

Just some warnings/errors mentioned by ![another issue](https://github.com/intel/cloud-hypervisor/issues/397)   

> Could not get region #8 info  

I think we don't handle the VGA region correctly because most of the devices don't have the VGA region. And for these devices with UEFI ROMs (which is an industry trend), we shouldn't try to access the VGA region. In the view of me, I prefer to omit this region.    

> Could not disable the MSI-X   

I have pushed 2 patches to solve the problem.

> Could not unset container   

I don't know what the root cause is yet.

**Comment by sboeuf** [comment]
@Cordius I changed the title of the current Github issue as the goal is to identify what is not working with the NVIDIA T4 card.

**Comment by Cordius** [comment]
@sboeuf 
> @Cordius I changed the title of the current Github issue as the goal is to identify what is not working with the NVIDIA T4 card.  

Well the T4 card passthrough works well except some warnings/errors mentioned above, I just didn't understand why you didn't handle the INTx before your explanation.

**Comment by sboeuf** [comment]
@Cordius 
>Well the T4 card passthrough works well except some warnings/errors mentioned above, I just didn't understand why you didn't handle the INTx before your explanation.

Oh I'm sorry I thought you had some trouble passing the card through since you mentioned it was only supporting INTx.
So you can confirm the card is working correctly when you pass it through the VM with `cloud-hypervisor`?
I'm curious what kind of test are you running inside the VM to validate the card works?

**Comment by Cordius** [comment]
@sboeuf   
> So you can confirm the card is working correctly when you pass it through the VM with `cloud-hypervisor`?
> I'm curious what kind of test are you running inside the VM to validate the card works?

I ran some cuda samples inside the vm and the samples passed.

**Comment by sboeuf** [comment]
@Cordius 
>I ran some cuda samples inside the vm and the samples passed.

Oh great :)

Do you think we can close this issue now?
