### ISSUE TITLE
RFC: Focus on musl builds

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#4356]
To simplify testing & release management. I'm proposing:

* Remove glibc builds from our releases. The musl/static build is only 0.8MiB bigger.
* Stop running integration testing on glibc. This would streamline our testing and give us a faster turnaround.
* Update documentation to point people to use binary or how to build musl build.

Not changing:

* GitHub actions still build test with glibc
* Accept patches to fix e.g. seccomp issues on glibc
* Core developers continuing to use glibc for convenience.

**Comment by liuw** [comment]
Do we expect users to deploy musl or glibc or both?

**Comment by sboeuf** [comment]
Simplification is always welcome, but why did you pick musl over glibc?

**Comment by rbradford** [comment]
> Simplification is always welcome, but why did you pick musl over glibc?

The only way to build a static binary is the musl toolchain (which is why we have it.) The static binary offers the best compatability across distributions. That is the one we should want our users to use.

**Comment by liuw** [comment]
There may be subtle differences between musl and glibc. If possible we should at least try running glibc integration tests periodically.

**Comment by likebreath** [comment]
> There may be subtle differences between musl and glibc.

I was wondering about the same thing. I didn't pick anything that's concerning from musl libc's documentation about its functional differences from glibc [1].

[1] https://wiki.musl-libc.org/functional-differences-from-glibc.html

>  If possible we should at least try running glibc integration tests periodically.

How about excluding glic tests from PR CI jobs while including them from the periodic CI job against `main` branch?

**Comment by liuw** [comment]
> > There may be subtle differences between musl and glibc.
> 
> I was wondering about the same thing. I didn't pick anything that's concerning from musl libc's documentation about its functional differences from glibc [1].
> 
> [1] https://wiki.musl-libc.org/functional-differences-from-glibc.html
> 

My worry is about the undocumented bugs and behaviours, but I admit it is nebulous and shouldn't be taken too seriously.

> > If possible we should at least try running glibc integration tests periodically.
> 
> How about excluding glibc tests from PR CI jobs while including them from the periodic CI job against `main` branch?

That works for me.

**Comment by michael2012z** [comment]
> The static binary offers the best compatability across distributions. That is the one we should want our users to use.

I like the idea to recommend static binary to users.

**Comment by alyssais** [comment]
> Stop running integration testing on glibc. This would streamline our testing and give us a faster turnaround.

Recommending the Musl binary to users makes sense, but many distributions build everything with Glibc, and are not in a position to mix and match libc implementations, so from a distributor's point of view, I'd appreciate it if cloud-hypervisor was still tested with Glibc.  (In Nixpkgs, we support both Musl and Glibc, and unusually, it is possible with Nixpkgs to mix and match, but most of our users are using Glibc and we don't vary the libc used per package — it's a setting for the user.)

**Comment by rbradford** [comment]
Thank you everyone for all the feedback. I am so pleased to hear from everyone using Cloud Hypervisor and in lots of different ways. Based on the feedback received we will keep everything as is - continuing to support both musl and glibc builds on x86_64 (on aarch64 only musl builds are supported.)
