### ISSUE TITLE
Unify address allocators to increase flexibility

### ISSUE THREAD

**Issue by NunoDasNeves** [cloud-hypervisor/cloud-hypervisor#4391]
Note that today, address allocation is done in ~4 different ways:
1. ram allocator - responsible for regions of regular ram, hotplug ram
2. system allocator - composed of io (x86), mmio hole, platform mmio memory regions, (plus it allocates irq numbers)
3. PCI segment allocators - passed in when allocating bars for a segment
4. Ad-hoc/hardcoded - e.g. create_vgic (aarch64) creates the GIC at a hardcoded address, within a region already reserved by the ram allocator - not sure if there are more examples of this

I think a new approach could improve:
- flexibility - e.g. allow a device tree (aarch64) to specify the guest machine layout. Or, even allow migration of VMs from other hypervisors with a different guest layout
- correctness - make it easier to verify that the various allocators aren't stomping on each other. This is currently only determinable by inspecting the initialization code for the allocators (easy to make a mistake).

I propose having a 'root' address allocator which functions as the source of truth (or at least the root of a hierarchy) for all address allocations.
If you want to allocate from a sub-region, ideally you specify it at the call site. This is a more flexible approach than creating baked-in layout areas like the mmio hole, platform mmio, etc...
For cases where it really is more convenient to create an allocator for a specific region (e.g. maybe PCI segments?), that region can first be reserved in the root allocator, and a new 'child' allocator created for allocating within the region.

Does this sound like an attractive idea? Interested to hear people's thoughts.

**Comment by liuw** [comment]
Hmm... Do you really need the root allocator to handle IRQ, PIO or PCI segment? They seem to be completely different from the memory address space.

**Comment by NunoDasNeves** [comment]
> Hmm... Do you really need the root allocator to handle IRQ, PIO or PCI segment? They seem to be completely different from the memory address space.

Yes, I think IRQ/PIO should be allocated separately, not bundled with memory addresses.
PCI segments should count - they are allocated in the memory address space starting after the last guest address (at memory_manager.start_of_device_area). Unless I'm misunderstanding something about PCI...

**Comment by NunoDasNeves** [comment]
While working on the code, I realized the lowest-friction way of addressing this issue is to continue using SystemAllocator, but let it manage the ram_allocator, so that is what this WIP series does.
TODO:
- Try and manage the PCI segments with SystemAllocator

**Comment by NunoDasNeves** [comment]
I realized the device_manager's mmio_bus is also doing allocations in the same address space. These aren't checked against the ram allocator or system allocator either... need to think about how to reconcile that.

**Comment by rbradford** [comment]
@NunoDasNeves I'm not sure I would try and do this. I tried to do this as part of the PCI segment enabling work - in particular having the PCI segments be allocated inside the main allocator and then having sub allocators for them. IIRC one of the issues I came across was the PCI BAR allocation not being able to allocate correctly because there is no way for that code to know what segment it was allocated on.

I think you will also have issues with things like `virtio-pmem` and `virtio-mem`.

What was the specific problem you were tying to solve?

**Comment by NunoDasNeves** [comment]
@rbradford 
> What was the specific problem you were tying to solve?

We want to pass a dtb to Cloud Hypervisor and initialize the devices/memory layout (at runtime) based on that.
The dtb is generated by a build system and includes a memory node, GIC, mmio devices, and virtio-mmio devices (we have some patches adding virtio-mmio support). It doesn't necessarily have the idea of an mmio hole or platform mmio region.

Essentially we want to just let the dtb dictate the entire layout - kind of similar to the 'restore' code path.
The fact that the mmio regions of the hardcoded layout are baked into the system allocator makes it difficult to do this.

**Comment by sboeuf** [comment]
> @rbradford
> 
> > What was the specific problem you were tying to solve?
> 
> We want to pass a dtb to Cloud Hypervisor and initialize the devices/memory layout (at runtime) based on that. The dtb is generated by a build system and includes a memory node, GIC, mmio devices, and virtio-mmio devices (we have some patches adding virtio-mmio support). It doesn't necessarily have the idea of an mmio hole or platform mmio region.
> 
> Essentially we want to just let the dtb dictate the entire layout - kind of similar to the 'restore' code path. The fact that the mmio regions of the hardcoded layout are baked into the system allocator makes it difficult to do this.

Wow that quite an important change. First thing that comes to mind is the complexity of achieving such goal based on the fact there are several assumptions in the code related to memory layout and I'm not sure how feasible it is to provide such mechanism to the end user.

But more important than the feasibility of this solution/design, what is the rationale behind it? I mean to say, why do you need the user to be able to choose where to place each component in the guest address space? Did you actually run in a situation where the choices made by Cloud Hypervisor were not fulfilling your expectations?

**Comment by liuw** [comment]
> > @rbradford
> > > What was the specific problem you were tying to solve?
> > 
> > 
> > We want to pass a dtb to Cloud Hypervisor and initialize the devices/memory layout (at runtime) based on that. The dtb is generated by a build system and includes a memory node, GIC, mmio devices, and virtio-mmio devices (we have some patches adding virtio-mmio support). It doesn't necessarily have the idea of an mmio hole or platform mmio region.
> > Essentially we want to just let the dtb dictate the entire layout - kind of similar to the 'restore' code path. The fact that the mmio regions of the hardcoded layout are baked into the system allocator makes it difficult to do this.
> 
> Wow that quite an important change. First thing that comes to mind is the complexity of achieving such goal based on the fact there are several assumptions in the code related to memory layout and I'm not sure how feasible it is to provide such mechanism to the end user.
> 
> But more important than the feasibility of this solution/design, what is the rationale behind it? I mean to say, why do you need the user to be able to choose where to place each component in the guest address space? Did you actually run in a situation where the choices made by Cloud Hypervisor were not fulfilling your expectations?

Yes. We agree this is an important change. That's why Nuno started this discussion here.

For the Azure Sphere project, we have the requirement to flexibly specify how the guest memory layout look like. The exact layout is of no interest to upstream.

When we work on this, what we find is -- like you said -- several assumptions in code. There is no coordination for all the allocators running in the system. There are hardcoded values in code. Things work by carefully placing them by hand and checked by human when coding.

The patches that allow DTB to dictate the layout is probably not upstreamable right now. But improving the status quo of Cloud Hypervisor's current design should be. We see the problems we run into as deficiencies. Instead of playing whack-a-mole with all the discrete values, there is maybe value to upstream in solving the deficiencies from their root.

We can go as simple as providing a `layout` struct, passing it around and removing all the discrete values in code, or as Nuno suggests, go further to unify some (or all) allocators under one true allocator.

As for complexity, I just looked at Nuno's example PR (this is without any DTB patches). It is not too bad. The system allocator has two new parameters and some functions are now replaced with the new one from the system allocator.

**Comment by sboeuf** [comment]
> > > @rbradford
> > > > What was the specific problem you were tying to solve?
> > > 
> > > 
> > > We want to pass a dtb to Cloud Hypervisor and initialize the devices/memory layout (at runtime) based on that. The dtb is generated by a build system and includes a memory node, GIC, mmio devices, and virtio-mmio devices (we have some patches adding virtio-mmio support). It doesn't necessarily have the idea of an mmio hole or platform mmio region.
> > > Essentially we want to just let the dtb dictate the entire layout - kind of similar to the 'restore' code path. The fact that the mmio regions of the hardcoded layout are baked into the system allocator makes it difficult to do this.
> > 
> > 
> > Wow that quite an important change. First thing that comes to mind is the complexity of achieving such goal based on the fact there are several assumptions in the code related to memory layout and I'm not sure how feasible it is to provide such mechanism to the end user.
> > But more important than the feasibility of this solution/design, what is the rationale behind it? I mean to say, why do you need the user to be able to choose where to place each component in the guest address space? Did you actually run in a situation where the choices made by Cloud Hypervisor were not fulfilling your expectations?
> 
> Yes. We agree this is an important change. That's why Nuno started this discussion here.
> 
> For the Azure Sphere project, we have the requirement to flexibly specify how the guest memory layout look like. The exact layout is of no interest to upstream.
> 
> When we work on this, what we find is -- like you said -- several assumptions in code. There is no coordination for all the allocators running in the system. There are hardcoded values in code. Things work by carefully placing them by hand and checked by human when coding.
> 
> The patches that allow DTB to dictate the layout is probably not upstreamable right now. But improving the status quo of Cloud Hypervisor's current design should be. We see the problems we run into as deficiencies. Instead of playing whack-a-mole with all the discrete values, there is maybe value to upstream in solving the deficiencies from their root.
> 
> We can go as simple as providing a `layout` struct, passing it around and removing all the discrete values in code, or as Nuno suggests, go further to unify some (or all) allocators under one true allocator.
> 
> As for complexity, I just looked at Nuno's example PR (this is without any DTB patches). It is not too bad. The system allocator has two new parameters and some functions are now replaced with the new one from the system allocator.

Fair enough. I mean it's totally okay to fix issues or deficiencies when you found them, but it's important to look at how you found them. If the use case itself doesn't make much sense for the usage Cloud Hypervisor has been designed for, then that might not be seen as an issue. Don't get me wrong I'm not against improvements, but where you might see deficiencies (by having things hardcoded) some others might see simplicity. Above all things, I think we've always tried to motivate changes with strong rationales ("perfect is the enemy of good") because each change can cause regression, which costs time to fix eventually.

**Comment by rbradford** [comment]
I'm not sure how changing the way dynamic allocations are made will help you with fixing specific locations for things. You can already do that with the existing allocators by specifying a desired address.

**Comment by NunoDasNeves** [comment]
> I'm not sure how changing the way dynamic allocations are made will help you with fixing specific locations for things. You can already do that with the existing allocators by specifying a desired address.
I tried that, but allocate_mmio_hole_addresses() and allocate_platform_mmio_addresses() restrict the fixed allocation to those regions - the desired addresses are not all necessarily within 'mmio_hole', etc...

It is possible to get around this by:
- Initializing the SystemAllocator with mmio hole and platform mmio regions covering the whole address space, so fixed allocations (which are the only type we need) just work
- Just not even use the SystemAllocator in our code path (maybe by putting `#cfg[not(something)]` wherever its used). In a way, since everything is fixed by the dtb, we don't really need the allocator..

**Comment by NunoDasNeves** [comment]
I closed the PR for now, posting my branch compared to main for future reference:
https://github.com/cloud-hypervisor/cloud-hypervisor/compare/main...NunoDasNeves:cloud-hypervisor:nudasnev/allocator
