### ISSUE TITLE
More flexible payload control

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#4445]
Some situations require multiple payloads to be loaded by the VMM in order for the guest to be usable.

These are the current payloads i'm aware of:

"Direct booting" use cases: 

* A UEFI firmware on aarch64 + a Linux kernel image + command line + (optional initramfs)
* A TDX firmware + kernel image + command line + (optional initramfs) (cf TDSHIM)
* Linux kernel (PVH or aarch64 Image) + command line  (+ optional initramfs)

But also single binary use cases

* hypervisor-fw via PVH
* TDVF
* OVMF via PVH on x86-64
* (Legacy firmware on x86-64) <-- not sure if this is still applicable

I'm proposing we integrate all those required options into a single `PayloadConfig` in the `VmConfig` struct with temporary (2 release transitions for the legacy version)

```rust
pub struct PayloadConfig {
    pub kernel: Option<PathBuf>,
    pub cmdline: Option<String>,
    pub initramfs: Option<PathBuf>,
    pub firmware: Option<PathBuf>,
}
```

This would then be exposed, as expected as, `--payload kernel=..., firmware=..., cmdline=...`

I hope that we can autodetect the TDX firmware from the binary file provided in `PayloadConfig::firmware` rather than requiring an extra parameter option.

During the transition we can map the old versions into the new version when the config is validated

**Comment by jongwu** [comment]
Thanks @rbradford for opening this. It's a big change. Some questions:

- If we remove "-kernel", how to maintain backward compatibility?
- squashing all of these payloads into one parameter may let it be too complex to use.
- the most different part is there is lack of widely used mechanism to pass kernel to firmware.

**Comment by rbradford** [comment]
> Thanks @rbradford for opening this. It's a big change. Some questions:
> 
>     * If we remove "-kernel", how to maintain backward compatibility?
> 

We will provide two releases of backward compatibility as per usual. This can be achieved by copying from the old version into the new version and using that to configure the boot.

>     * squashing all of these payloads into one parameter may let it be too complex to use.

Well on the contrary, it makes it much much easier to add to in the future without adding extra top-level parameters. It also makes it much simpler to detect if we are in API only mode or if we are booting directly into a payload. This is already complicated and adding TDX support made it more so and adding the firmware option you proposed made it even more complex. Instead if we make `payload: Option<PayloadConfig>` on `VmConfig` we can simply check for `None` to choose API booting mode.

> 
>     * the most different part is there is lack of widely used mechanism to pass kernel to firmware.

That's not what this PR is trying to solve. This is trying to stop the pollution of the top-level of the `VmConfig` with more options and more complexity of using API only mode. Once this is in place you can start to work on interpreting the `PayloadConfig` in different ways based on the configuration.

**Comment by sboeuf** [comment]
@rbradford I like the approach, this makes things explicit and at this point I think there's no other way to go. IIUC, we could also get rid of the `--tdx` parameter, right?

**Comment by rbradford** [comment]
> @rbradford I like the approach, this makes things explicit and at this point I think there's no other way to go. IIUC, we could also get rid of the `--tdx` parameter, right?

Yes! That's my hope.

**Comment by likebreath** [comment]
This (or any changes to the `VmConfig`) is a breaking change for live-upgrade. I wonder do we want to try to enable the live-upgrade support after the release next week (assuming no additional changes to `VmConfig` is needed for this issue)?

**Comment by rbradford** [comment]
> This (or any changes to the `VmConfig`) is a breaking change for live-upgrade. I wonder do we want to try to enable the live-upgrade support after the release next week (assuming no additional changes to `VmConfig` is needed for this issue)?

This and also all the recent change for unified binary. Let's try and re-enable it after the release....
