### ISSUE TITLE
BARs are marked as non-prefetchable, NVIDIA kernel driver expects prefetchable.

### ISSUE THREAD

**Issue by sdake** [cloud-hypervisor/cloud-hypervisor#4451]
See issues:
- https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4375 - more or less this is a PCI enumeration bug involving SRIOV devices.
- https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4353

During the investigation of https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4375, I discovered the host BAR definition to be altered from the guest BAR definition.https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4375#issuecomment-1207342235. Within the guest, the memory mapped bars are NON-PREFETCHABLE. Within the host, the memory-mapped bars are prefetchable.

I took a look at the NVIDIA kernel error report here:
https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/kernel-open/nvidia/nv-pci.c#L414-L421

This is called when:
https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/kernel-open/nvidia/nv-pci.c#L407 evaluates to false.

This evaluates to false when:
https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/kernel-open/nvidia/nv-pci.c#L358

Another way of stating the issue is that the NVIDIA kernel driver expects memory mapped bars to be prefetchable. If they are not, the nvidia driver craters with the loops we have seen during VFIO PCI passthrough. Cloud-Hypervisor marks the memory as non-prefetchable, so this is the cause of the nvidia kernel driver failure, as this is different than what is presented in the host. I don't know what the implications of prefetchable versus non-prefetchable are, however, I am going to take a look at the PCIE specification is determine what precisely that means. I am also going to try:

1. A hack override just to see if that gets the NVIDIA driver working in passthrough
2. Determine the reason why cloud-hypervisor marks the memory map as non-prefetchable, and if its a bug fix it.

Cheers,
-steve

**Comment by sdake** [comment]
A small patch, coupled with https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4443 results in:
```
https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4443
```

 I will publish the patch in 20-45 minutes.

Cheers,
-steve

**Comment by sdake** [comment]
I have filed a bug in https://github.com/NVIDIA/open-gpu-kernel-modules/issues/344 to request a little bit better failure handling in the NVIDIA kernel driver that what happens now.

**Comment by sdake** [comment]
Cloud-Hypervisor marks memory as nonprefetchable in `vfio.rs` because `vfio.rs` does not override the default prefetch state of `nonprefetchable`. It should always override based upon the state of the prefetch value in the BARs in the host, unless there is some security reason not to do so, that I don't understand.

@rbradford @sboeuf Would either of you comment if there is any security or reliability issue with using the host device BAR's prefetch values in the guest? It appears as if it was just a small overisght.

CHeers,
-steve

**Comment by rbradford** [comment]
Some feedback on your PR:

1. When contributing to a project it's always good to look at the existing style of commit messages. You need to include a "tag" like `pci: vfio` in your first line of commit messages.
2. If this fixes the issue then use `Fixes: #<nnnn>` in the commit message at the end. If it's just information use something like "See: #<nnnn>"

**Comment by sdake** [comment]
Thanks @rbradford. If you don't mind, I will reopen that PR and force push an update a per your guidance. Everything here and elsewhere is linked with it...

Thank you.
-steve

**Comment by sdake** [comment]
I see you have re-implemented the work. SGTM. Would you mind adding a co-author line.

Thank you
-steve

**Comment by rbradford** [comment]
> I see you have re-implemented the work. SGTM. Would you mind adding a co-author line.
> 
> Thank you -steve

Eh? I didn't reimplement anything. I added a second commit to the PR for testing (that used the original value of the prefetch flags) I had to create a second PR because Jenkins will ignore changes to Jenkinsfile file from unprivileged users and unfortunately we have only limited VFIO testing capability.

**Comment by sdake** [comment]
Duplicate of: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4375.

**Comment by sdake** [comment]
> > I see you have re-implemented the work. SGTM. Would you mind adding a co-author line.
> > Thank you -steve
> 
> Eh? I didn't reimplement anything. I added a second commit to the PR for testing (that used the original value of the prefetch flags) I had to create a second PR because Jenkins will ignore changes to Jenkinsfile file from unprivileged users and unfortunately we have only limited VFIO testing capability.

My bad, that came across wrong. I see now I misunderstood. Thanks!

Cheers,
-steve
