### ISSUE TITLE
test_serial_file is flaky

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#452]
I've had to restart several builds because this test has flaked out. Might just be the case that the timeouts need tweaking.

**Comment by sboeuf** [comment]
Does this still occurs?

**Comment by sboeuf** [comment]
@rbradford does this still happen? Do you have reference logs of failures too?

**Comment by rbradford** [comment]
Bump! Here is a failure on the master branch today: https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/job/cloud-hypervisor/job/master/2330/consoleFull

**Comment by rbradford** [comment]
I think I addressed the flakiness by waiting for the hypervisor process to cleanly shutdown in #833
