### ISSUE TITLE
virtio-console: Output to the PTY partially lost

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#4521]
Similarly to what was described on #3170, when the `virtio-console` device is connected to a PTY device, some of the output is lost.
This is because we should wait for the other end of the PTY device to be connected before trying to write some output to it. While it's disconnected, we must simply buffer the output.

**Comment by iggy** [comment]
> we must simply buffer the output

Is there a way to limit how much is buffered? It probably wouldn't be ideal to buffer infinitely in case an ill-behaved tool doesn't ever connect to the other end. The buffer could become a DoS vector.

**Comment by sboeuf** [comment]
> > we must simply buffer the output
> 
> Is there a way to limit how much is buffered? It probably wouldn't be ideal to buffer infinitely in case an ill-behaved tool doesn't ever connect to the other end. The buffer could become a DoS vector.

Yes we should pick a size for the buffer (maybe 1MiB?) to limit its size.

**Comment by sboeuf** [comment]
@iggy I've just applied this to the `SerialBuffer` (see #4533), we'll need to do the same for console.

**Comment by sboeuf** [comment]
Here is a branch that contains the patch to fix the issue of losing some of the PTY output: https://github.com/sboeuf/cloud-hypervisor-1/tree/fix_console_pty

But before posting a PR, I want to discuss about a few issues related to the PTY and our expectation to start flushing the output when the other end is connected.
- The design of the PR reuses the existing `virtio-console` thread. Until something is connected to the other end of the PTY, the `EPOLLHUP` event is always triggered, which is why we call `sleep()` before we loop again. By doing so, we prevent other events to be handled in a timely manner, which directly slows down the guest. On the other hand, if we reduce the `sleep()` time to a small value (or even 0), we end up with high CPU consumption given the thread is always processing the EPOLLHUP event. I found some sort of compromise with `sleep(1ms)`, but I'm really not happy with that kind of solution. One alternative could be to run another thread dedicated for the PTY fd, for which we could `sleep()` without interfering with other events. This would increase the complexity of the code though, as we would need some communication between these two threads.
- The whole design detecting the other end of the PTY being connected/disconnected relies on the presence of `EPOLLHUP`, but this gets totally broken if another process has a hold onto the PTY's file descriptor. This is exactly what happens with the PTY resize logic that is in place (and not working #4522). So we actually need to disable the code spawning the child process if we want the `virtio-console` thread to see the `EPOLLHUP` event.
- One last thing, I've been playing with QEMU and it seems it doesn't handle any of the issues we're trying to solve (missing output and terminal resize). I've tried with `-serial pty` and `-device virtio-serial-pci,id=virtio-serial0 -chardev pty,id=charconsole0 -device virtconsole,chardev=charconsole0,id=console0`, and in both cases I could observe the same behavior where QEMU didn't buffer any of the output waiting for the PTY to connect. Therefore I'm wondering if we should spend more time solving this issue.

/cc @rbradford

**Comment by sboeuf** [comment]
I figured a way to handle the problem related to the `sleep()`, using `EPOLLONESHOT` so that I can control not receiving a flood of `EPOLLHUP` events.
Here is the code: https://github.com/sboeuf/cloud-hypervisor-1/commits/fix_console_pty_2
Note that it still requires the PTY resizing process to be disabled.
Please let me know if you think this is reasonable and if I can send a PR for it.

**Comment by bryteise** [comment]
> Here is the code: https://github.com/sboeuf/cloud-hypervisor-1/commits/fix_console_pty_2

This looks pretty good to me, I think having a dedicated thread for the PTY fd should be something done when we see the full performance impact only as the complexity it introduces will be painful.

**Comment by sboeuf** [comment]
> > Here is the code: https://github.com/sboeuf/cloud-hypervisor-1/commits/fix_console_pty_2
> 
> This looks pretty good to me, I think having a dedicated thread for the PTY fd should be something done when we see the full performance impact only as the complexity it introduces will be painful.

So IIUC, you're okay with this code, meaning it's okay to drop the PTY resize (which doesn't work anyway)?

**Comment by sboeuf** [comment]
I've created https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4535 as it might be easier to discuss/review there directly.

**Comment by sboeuf** [comment]
Heads up, I've managed to keep the PTY resize logic without affecting the `EPOLLHUP` event (closing the PTY fds from the child process). The PR #4535 is ready for review :)
