### ISSUE TITLE
virtio-console: Handle console resize on PTY

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#4522]
Resizing the PTY doesn't work, it must be fixed.

**Comment by sboeuf** [comment]
@alyssais I've been trying to use the resize PTY feature, unfortunately it doesn't work for me. After adding some logs to the resize handler, I can see it's not called, meaning the SIGWINCH hasn't been delivered to the process. If I manually send a SIGWINCH to the process with `kill -28 12345` (assuming 12345 is the pid of the cloned process), I do get the log from the resize handler.
I've been trying with both `picocom` and `screen`, but in both case, when I resize my terminal, nothing happens.
I might be doing something wrong, which is why I'd like to get your input on how you tested the code was working? (reference PR introducing the feature is https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3106).

**Comment by rbradford** [comment]
I think you should go ahead and remove the logic for resize on a PTY as we do not know how to test it (I went back to the release where it was introduced and could not make it work.)

**Comment by sboeuf** [comment]
Ok will do!

**Comment by alyssais** [comment]
Hi, I can provide instructions for the resize PTY feature later today.

**Comment by alyssais** [comment]
Instructions: :) https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4591#issuecomment-1237864592
