### ISSUE TITLE
Cloud hypervisor v21.1+ seems not work in centos 7 with kernel `3.10.0-1160.45.1.el7.x86_64`

### ISSUE THREAD

**Issue by weixiao-huang** [cloud-hypervisor/cloud-hypervisor#4579]
**Describe the bug**

Cloud hypervisor v21.1+ seems not to work in centos 7 with kernel `3.10.0-1160.45.1.el7.x86_64` but v21.0 works. However, after upgrade to centos 7 with kernel `5.4.15-1.el7.elrepo.x86_64`, it works.

This bug seems to be introduced in [this commit](https://github.com/cloud-hypervisor/cloud-hypervisor/commit/507912385a416db65f7ea21ed85f0bb6f0f7f38d#diff-3b7188695d825bcc74e2595af0db2ccbbb8e0c3d5ef6b5ebbf23612732ec3198R133)

**To Reproduce**

According to the docs in https://github.com/cloud-hypervisor/cloud-hypervisor/tree/v21.1#run , we use these command

```
sudo su
yum install -y qemu-img
mkdir cloud-hypervisor && cd cloud-hypervisor
wget https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v21.1/cloud-hypervisor-static && chmod +x cloud-hypervisor-static
wget https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
qemu-img convert -p -f qcow2 -O raw focal-server-cloudimg-amd64.img focal-server-cloudimg-amd64.raw
wget https://github.com/cloud-hypervisor/rust-hypervisor-firmware/releases/download/0.3.2/hypervisor-fw
setcap cap_net_admin+ep ./cloud-hypervisor-static
```

Then we use 

```
./cloud-hypervisor-static \
	--kernel ./hypervisor-fw \
	--disk path=focal-server-cloudimg-amd64.raw \
	--cpus boot=4 \
	--memory size=1024M \
	--net "tap=,mac=,ip=,mask="
```

to run the VM and got the error below

```
thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: CheckExtensions(Capability missing: ImmediateExit)', vmm/src/vm.rs:750:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error booting VM: ResponseRecv(RecvError)
```

**Version**

v21.1 downloaded from https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v21.1/cloud-hypervisor-static && chmod +x cloud-hypervisor-static

**VM configuration**

see above

Guest OS version details:

see above

Host OS version details:

kernel:

```
[root@test-0003 cloud-hypervisor]# uname -a
Linux test-0003 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

os:

```
[root@test-0003 cloud-hypervisor]# cat /etc/*release
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.9.2009 (Core)
CentOS Linux release 7.9.2009 (Core)
```

**Logs**

```
cloud-hypervisor: 410.095µs: <vmm> INFO:vmm/src/lib.rs:1340 -- API request event: VmCreate(Mutex { data: VmConfig { cpus: CpusConfig { boot_vcpus: 4, max_vcpus: 4, topology: None, kvm_hyperv: false, max_phys_bits: 46, affinity: None }, memory: MemoryConfig { size: 1073741824, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None }, kernel: Some(KernelConfig { path: "./hypervisor-fw" }), initramfs: None, cmdline: CmdlineConfig { args: "" }, disks: Some([DiskConfig { path: Some("focal-server-cloudimg-amd64.raw"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, poll_queue: true, rate_limiter_config: None, id: None, disable_io_uring: false, pci_segment: 0 }]), net: Some([NetConfig { tap: None, ip: 192.168.249.1, mask: 255.255.255.0, mac: MacAddr { bytes: [46, 65, 31, 117, 219, 190] }, host_mac: None, iommu: false, num_queues: 2, queue_size: 256, vhost_user: false, vhost_socket: None, vhost_mode: Client, id: None, fds: None, rate_limiter_config: None, pci_segment: 0 }]), rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Null, iommu: false }, console: ConsoleConfig { file: None, mode: Tty, iommu: false }, devices: None, user_devices: None, vsock: None, iommu: false, sgx_epc: None, numa: None, watchdog: false, platform: None }, poisoned: false, .. }, Sender { .. })
cloud-hypervisor: 1.100716ms: <vmm> INFO:vmm/src/lib.rs:1340 -- API request event: VmBoot(Sender { .. })
thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: CheckExtensions(Capability missing: ImmediateExit)', vmm/src/vm.rs:750:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error booting VM: ResponseRecv(RecvError)
```

Linux kernel output:

None

**Comment by rbradford** [comment]
3.10 is simply too old - we require KVM features newer than that (which is what the error is telling you.)

**Comment by weixiao-huang** [comment]
But this kernel is build officially for `CentOS 7`. The kernel version built by red hat backport a lot of problem patches to make it stable. Since CentOS 7 should be supported before 2024, I think it may be necessary to support the popular `CentOS 7`  3.10 kernel before 2024.
Another option is that whether hypervisor could detect the kernel version to decision which feature should be supported for KVM?
Also, I think the supported minimum kernel version may be listed in the docs. At least `v21.0` could be run in `CentOS 7` 3.10 kernel but v21.1 failed, could we keep the compatibility for the same major version?

**Comment by rbradford** [comment]
I'm happy to update the documentation to reflect that there is a minimum kernel version (and we should probably also have a minimum recommended kernel version.)

The requirement for `KVM_CAP_IMMEDIATE_EXIT` came for a bug fix #3658 which is why is changed in a point release

**Comment by weixiao-huang** [comment]
But I wonder could cloud hypervisor support the popular CentOS 7 3.10 kernel? Since in my situation, we have upgraded some nodes from 3.10 kernel to 5.4, but there're still some important nodes keeping 3.10 kernel. So is it possible to support it in cloud hypervisor by solving https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3658 in another way to keep the compatibility?

**Comment by liuw** [comment]
> But I wonder could cloud hypervisor support the popular CentOS 7 3.10 kernel? Since in my situation, we have upgraded some nodes from 3.10 kernel to 5.4, but there're still some important nodes keeping 3.10 kernel. So is it possible to support it in cloud hypervisor by solving #3658 in another way to keep the compatibility?

Perhaps you can check how QEMU handles that situation on 3.10?

**Comment by sboeuf** [comment]
@liuw QEMU might not have the requirement about `ImmediateExit` capability.
@weixiao-huang The fix that was introduced is correct, and the project never stated it would try to work on old kernels such as 3.10. There's a huge gap in terms of features support when you compare 3.10 and 5.xx kernels, and Cloud Hypervisor never tried to bring some kind of backward compatibility for these old kernel versions.

**Comment by rbradford** [comment]
I thought about moving the error on capability to check to the pause time (as that is the only functionality that depends upon it) however I think that will just lead to issues being opened about being "unable to pause on CentOS 7".

**Comment by rbradford** [comment]
@liuw FYI QEMU solves this by signalling the vCPU thread to cause it to exit as if it were exiting from a non IO exit. But of course that is still racy and would make our exit managment logic even more complicated. And it would be untestable through the CI.

As such the requirement for `KVM_CAP_IMMEDIATE_EXIT` remains - both RHEL8 and Ubuntu 18.04 have 4.18 which I think means it is reasonable to require a minimum of 4.11.
