### ISSUE TITLE
Investigate VFIO/MSI disable issues

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#460]
The PR #449 should have nicely fixed/improved the way VFIO would disable MSI, but for some reasons it broke the VFIO MSI support, which needs to be investigated.

**Comment by Cordius** [comment]
Could you share the detail in this case?

**Comment by sboeuf** [comment]
Well I found out there's some sort of undefined behavior if we disable the interrupt range from VFIO but don't remove it from the KVM_GSI_ROUTING. One simple way to prevent from issues is to mask the interrupts right before we disable them. And also, right after we enable interrupts, it's a good practice to unmask them.
