### ISSUE TITLE
Need to document / add test for Fedora cloud booting

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#4674]
Fedora 36 (not sure when it started) now ships with a UEFI image that works great with rust-hypervisor-firmware. We should make sure we document that (cloud-init also works.) We could also add a test.

This is the image I tested:
https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-36-1.5.x86_64.raw.xz

**Comment by rbradford** [comment]
Adding a test for fedora is probably a bad idea from my experimentation:

1. It will negatively impact the testing time as this is a large image (5GiB uncompressed)
2. We need to go through hoops to create a new image with e.g. nc in to signal that the boot is completed (although we could replace that with bash's built in TCP support.)
3. It looks like we need to do the cloud init configuration in a different way

I think we should just stick with documenting it (i'm especially concerned about point 1.)

**Comment by sboeuf** [comment]
That's fine if you only document it, we already have a quite large test suite. About the image size, don't you think we could shrink it. I doubt we need to keep it at 5GiB for our testing needs.
