### ISSUE TITLE
Enable mshv in published releases / enable as default feature

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#4678]
We have v27.0 - is MSHV stable enough to turn on in published releases by default? Do we even consider adding mshv to default features.

**Comment by rbradford** [comment]
@liuw WDYT? Would you like to see `mshv` added to default features. Would simplify testing and release stuff.

**Comment by russell-islam** [comment]
I second that enabling mshv. think it would make sense to enable testing  in the CLH pipeline on MSHV as well.
