### ISSUE TITLE
qcow: error caculation of  the  l1_clusters in function create_for_size()

### ISSUE THREAD

**Issue by lv-mz** [cloud-hypervisor/cloud-hypervisor#4762]
There is a problem when caculating the number of clusters for L1 table  ，the previous calculation is as follows:

qcow/src/qcow.rs:253~262

/// Create a header for the given `size`.
    pub fn create_for_size(version: u32, size: u64) -> QcowHeader {
        let cluster_bits: u32 = DEFAULT_CLUSTER_BITS;
        let cluster_size: u32 = 0x01 << cluster_bits;
        // L2 blocks are always one cluster long. They contain cluster_size/sizeof(u64) addresses.
        let l2_size: u32 = cluster_size / size_of::<u64>() as u32;
        let num_clusters: u32 = div_round_up_u64(size, u64::from(cluster_size)) as u32;
        let num_l2_clusters: u32 = div_round_up_u32(num_clusters, l2_size);
        let l1_clusters: u32 = div_round_up_u32(num_l2_clusters, cluster_size);
        ...

It caculate l1_cluaters by "div_round_up_u32(num_l2_clusters, cluster_size)",  In fact, it should be divided by  "cluster_size/sizeof(u64)"  instead of  cluster_size.

**Comment by rbradford** [comment]
How did you discover this issue? This code is still unmodified from crosvm.

**Comment by lv-mz** [comment]
I
