### ISSUE TITLE
Add new features to make TSO, UFO, CHECKSUM, etc. configurable

### ISSUE THREAD

**Issue by ljrcore** [cloud-hypervisor/cloud-hypervisor#4792]
The host does not support offload capability at the moment, we need to turn off the offload switch of the vm NIC.

If CH can make the TSO, UFO, CHECKSUM features configurable, and turn them off in the default configuration it will make the CH network easier to use.

**Comment by rbradford** [comment]
Could you elaborate on what you mean with "the host does not support offload capability" ? What type of configuration are you using, virtio-net with macvlan, vhost-user-net or simple virtio-net?

**Comment by ljrcore** [comment]
> Could you elaborate on what you mean with "the host does not support offload capability" ? What type of configuration are you using, virtio-net with macvlan, vhost-user-net or simple virtio-net?

(1) If the vm sends TCP messages that exceed the MTU, the host cannot segment the TCP data and will drop packets.
(2) simple virtio-net.

Thanks.

**Comment by sboeuf** [comment]
> > Could you elaborate on what you mean with "the host does not support offload capability" ? What type of configuration are you using, virtio-net with macvlan, vhost-user-net or simple virtio-net?
> 
> (1) If the vm sends TCP messages that exceed the MTU, the host cannot segment the TCP data and will drop packets.

You can use `--net mtu=1500` where 1500 can be whatever value that fits your host, so the guest will be configured with the proper MTU. Also, please note that if you provide an existing tap (let's call it `mytap0`) with the following command `--net tap=mytap0`, Cloud Hypervisor will get the MTU that is supported by the TAP to set it to the guest.

**Comment by ljrcore** [comment]
> > > Could you elaborate on what you mean with "the host does not support offload capability" ? What type of configuration are you using, virtio-net with macvlan, vhost-user-net or simple virtio-net?
> > 
> > 
> > (1) If the vm sends TCP messages that exceed the MTU, the host cannot segment the TCP data and will drop packets.
> 
> You can use `--net mtu=1500` where 1500 can be whatever value that fits your host, so the guest will be configured with the proper MTU. Also, please note that if you provide an existing tap (let's call it `mytap0`) with the following command `--net tap=mytap0`, Cloud Hypervisor will get the MTU that is supported by the TAP to set it to the guest.

Yes, CH now supports configuring mtu, which is a very convenient feature. If CH supports configuring TSO, UFO, CHECKSUM and turning them off in the default options, this will make the CH network configuration even easier.

Thanks.

**Comment by ljrcore** [comment]
> > Yes, CH now supports configuring mtu, which is a very convenient feature. If CH supports configuring TSO, UFO, CHECKSUM and turning them off in the default options, this will make the CH network configuration even easier.
> 
> You need to explain this requirement further: How could one reproduce this problem you're seeing? Is it hardware specific? Is it kernel version specific? You say you're using "simple virtio-net" so then why are you getting these issues? Or are you using macvtap on the ethernet interface?
> 
> Many of these options you refer to are configurable via ethtool in the guest.

You are right. I am now in a scenario like this. I want to turn off TSO, UFO, CHECKSUM by default without setting the guest. and I can configure it in the "--net" option in CH when I need to turn it on.

The advantage of this is that I don't have to turn off TSO, UFO, CHECKSUM in guest as often, avoiding the tedium of configuring network parameters in guest and improving versatility. When I need it, I can easily turn it on via the "--net" option in CH. Overall, it improves performance and convenience. I look forward to CH having such features.

Thanks.

**Comment by sboeuf** [comment]
@ljrcore
Before talking about implementing such feature, we would like to understand the reason why you don't have TSO/UFO/CHECKSUM supported on your host machine. What is your host kernel version?
We are very surprised that you have a use case where you need to disable these options, and we'd like you to provide more details about the reason why you need this.
Thanks

**Comment by ljrcore** [comment]
> @ljrcore Before talking about implementing such feature, we would like to understand the reason why you don't have TSO/UFO/CHECKSUM supported on your host machine. What is your host kernel version? We are very surprised that you have a use case where you need to disable these options, and we'd like you to provide more details about the reason why you need this. Thanks

The hardware is a smart NIC from Broadcom and the Linux kernel version is 5.4.

Since the host hardware we are using has not yet developed these offload functions, we need to turn off the relevant offload switch of the vm NIC.

Thanks.

**Comment by zhuangel** [comment]
Hi @sboeuf @rbradford, I have file a PR for this issue, could you help to review this, thanks.

https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5029
