### ISSUE TITLE
How to use tracer::start() and tracer::end()

### ISSUE THREAD

**Issue by ljrcore** [cloud-hypervisor/cloud-hypervisor#4798]
I added "use tracer::trace_scoped" and used tracer::start() and tracer::end() in a function to limit the scope to a smaller one. Then use trace_scoped!("virtio-blk-1") to trace the elapsed time. At this point an error was reported. 
```
thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: Tracer { events: Mutex { data: {}, poisoned: false, .. }, thread_depths: {}, start: Instant { tv_sec: 8144, tv_nsec: 74283423 } }', tracer/src/tracer.rs:169:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error booting VM: ResponseRecv(RecvError)
```
Are there any caveats or more examples of how I should properly use tracer::start() and tracer::end()?
Thanks.

**Comment by ljrcore** [comment]
> > I added "use tracer::trace_scoped" and used tracer::start() and tracer::end() in a function to limit the scope to a smaller one. Then use trace_scoped!("virtio-blk-1") to trace the elapsed time. At this point an error was reported.
> > ```
> > thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: Tracer { events: Mutex { data: {}, poisoned: false, .. }, thread_depths: {}, start: Instant { tv_sec: 8144, tv_nsec: 74283423 } }', tracer/src/tracer.rs:169:40
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > Error booting VM: ResponseRecv(RecvError)
> > ```
> > 
> > Are there any caveats or more examples of how I should properly use tracer::start() and tracer::end()? Thanks.
> 
> Are you calling `tracer::start()` after an existing call to `tracer::start()` ? If you want to start tracing later/stop earlier then you need to move the calls; you cannot make duplicate calls.

I added the trace point this way and then recompiled CH.
```
diff --git a/vmm/src/device_manager.rs b/vmm/src/device_manager.rs
index 1b80c65b..6b1a3a0b 100644
--- a/vmm/src/device_manager.rs
+++ b/vmm/src/device_manager.rs
@@ -2030,7 +2030,9 @@ impl DeviceManager {
         };
 
         info!("Creating virtio-block device: {:?}", disk_cfg);
+        
+        tracer::start();
+        trace_scoped!("virtio-blk-1");
         let (virtio_device, migratable_device) = if disk_cfg.vhost_user {
             let socket = disk_cfg.vhost_socket.as_ref().unwrap().clone();
             let vu_cfg = VhostUserConfig {
@@ -2152,6 +2154,7 @@ impl DeviceManager {
                 virtio_block as Arc<Mutex<dyn Migratable>>,
             )
         };
+        tracer::end();
```
This error occurs when running CH.
```
cloud-hypervisor  \
>         --kernel ./linux-cloud-hypervisor/vmlinux \
>         --pmem file=./disk-focal-server-cloudimg-amd64.raw \
>         --cmdline "console=hvc0 root=/dev/pmem0p1 rw quiet" \
>         --serial null \
>         --console tty \
>         --memory size=512M \
>         --net "tap=,mac=,ip=,mask=" \
>         --disk path=/root/virtio-blk-test.raw,num_queues=1,queue_size=1024,direct=on
thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: Tracer { events: Mutex { data: {}, poisoned: false, .. }, thread_depths: {}, start: Instant { tv_sec: 2355, tv_nsec: 400547333 } }', tracer/src/tracer.rs:169:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error booting VM: ResponseRecv(RecvError)
```
How should I modify it correctly.
thanks.

**Comment by rbradford** [comment]
You can't call `tracer::start()` twice. If you want more fine-grained tracing you need to move the start/end not add extra ones.

**Comment by ljrcore** [comment]
> You can't call `tracer::start()` twice. If you want more fine-grained tracing you need to move the start/end not add extra ones.

It works. Thanks.

**Comment by rbradford** [comment]
> > You can't call `tracer::start()` twice. If you want more fine-grained tracing you need to move the start/end not add extra ones.
> 
> It works. Thanks.

Great - i'm glad it's working for you.
