### ISSUE TITLE
virtio-fs: Implement SLAVE_REQ support

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#481]
Implement missing DAX support. This means we need to add support for `VHOST_USER_PROTOCOL_F_SLAVE_REQ` to the vhost_user_backend crate, as we need to support some slave driven events.

**Comment by yangzhon** [comment]
@sboeuf 

In docs/fs.md,

By default, DAX is enabled with a cache window of 8GiB. You can specify a custom size (let's say 4GiB for this example) for the cache by explicitly setting DAX and the cache size:
--fs tag=virtiofs,sock=/tmp/virtiofs,num_queues=1,queue_size=512,dax=on,cache_size=4G

In fact, DAX is not supported, right? so we do not support cache=always mode in backend.

From our test in Kata with Ant Finance, if we add cache=always in backend and enabled DAX in vhost user fs device, the performance is very low when we tested fs shared from host in guest.

**Comment by sboeuf** [comment]
@yangzhon DAX (which introduces a shared memory region) is definitely supported by cloud-hypervisor. There might be some settings set wrong somewhere in the stack since Kata is another layer on top of it, but we do have support for proper shared memory region, which improves greatly the performances compared to using `cache=none` with DAX disabled.

Now of course you need to use `virtiofsd` from Redhat (the one written in C in the QEMU repo), since the one we're developing in Rust does not support the shared memory region feature yet.

**Comment by renzhengeek** [comment]
Hi,

> In fact, DAX is not supported, right? so we do not support cache=always mode in backend.

IIUC, DAX is used to bypass host pagecache, while cache=always is how the server (virtiofsd) requires client to do IO in guest, they are independent options.

> 
> From our test in Kata with Ant Finance, if we add cache=always in backend and enabled DAX in vhost user fs device, the performance is very low when we tested fs shared from host in guest.

I tested DAX+cache=none combination months ago, compared with 9p, one impressed result is the rand-read IOPS is much lower than 9p.

Your testing finding is interesting. Would you mind to share which IO pattern is worse and its numbers? Thanks.

**Comment by yangzhon** [comment]
@renzhengeek 

We only checked simple command like "ls" and "top" command in the backend filesystem from guest, and the command run very slowly in cache=always mode, which is worse than cache=none mode.

**Comment by renzhengeek** [comment]
> @yangzhon DAX (which introduces a shared memory region) is definitely supported by cloud-hypervisor. 

Hi, the last words in doc/fs.md seems easy to confuse people:
> The `dax` option must be removed in case the shared cache region is not enabled from the VMM. 

thought `the VMM` were cloud-hypervisor;)

**Comment by renzhengeek** [comment]
> @renzhengeek
> 
> We only checked simple command like "ls" and "top" command in the backend filesystem from guest, and the command run very slowly in cache=always mode, which is worse than cache=none mode.

So, I guess you used the rust-version virtiofsd, right?

I test with your options below:
> --fs tag=virtiofs,sock=/tmp/virtiofs,num_queues=1,queue_size=512,dax=on,cache_size=4G

and mount:
> mount -t virtio_fs virtiofs  /mnt -o rootmode=040000,user_id=0,
group_id=0,dax

and put qemu source tree in the shared dir, `ls` the source finishes quickly here.

**Comment by yangzhon** [comment]
> thought `the VMM` were cloud-hypervisor;)

Yes, cloud-hypervisor like Qemu, which is not only device model, but also VM monitor.

**Comment by yangzhon** [comment]
In that time, we used the virtiofsd from Qemu tree. 

Oh, we can try this again, thanks for reminder.

**Comment by liubogithub** [comment]
> Implement missing DAX support. This means we need to add support for `VHOST_USER_PROTOCOL_F_SLAVE_REQ` to the vhost_user_backend crate, as we need to support some slave driven events.

While I tried to implemented such a thing, I couldn't figure out how to make Server/PassthroughFs to access vhost_user slave side functions, can you please suggest?

**Comment by sboeuf** [comment]
@liubogithub 
>While I tried to implemented such a thing, I couldn't figure out how to make Server/PassthroughFs to access vhost_user slave side functions, can you please suggest? @sboeuf

I haven't looked into the details yet (got busy with other things), but the general idea is to modify the `vhost_user_backend` crate so that it can support receiving a slave fd that we can use from any vhost-user backend. Did you identify some blockers there?

**Comment by liubogithub** [comment]
> @liubogithub
> 
> > While I tried to implemented such a thing, I couldn't figure out how to make Server/PassthroughFs to access vhost_user slave side functions, can you please suggest? @sboeuf
> 
> I haven't looked into the details yet (got busy with other things), but the general idea is to modify the `vhost_user_backend` crate so that it can support receiving a slave fd that we can use from any vhost-user backend. Did you identify some blockers there?

Thanks for the reply.
OK, I can add a `slave_sock` in `vhost_user_backend` and make `VhostUserHandler` receive the slave fd from `master` and create a `Endpoint`, but `Server` is taking `Reader` and `Writer` from `Vring` directly, if I add a `VhostUserBackend` pointer to Server::handle_message(), it kind of breaks the current design, IOW, how do we expose `VhostUserBackend` to `Server` in a proper way?

**Comment by sboeuf** [comment]
@liubogithub 
First thing, you need to implement [`VhostUserMasterReqHandler`](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vhost_rs/src/vhost_user/master_req_handler.rs#L17) trait.

Once you got that implemented with your own structure, you will be able from `vhost_user_backend` to provide it to `src/bin/vhost_user_fs.rs`.

The last step is to let the Server be able to trigger a `map`, an `unmap` and a `sync`. In this case, I would suggest you define a new Trait in `vhost_user_fs` crate. This trait would have three functions `map()`/`unmap()`/`sync()` that `src/bin/vhost_user_fs.rs` would implement. The implementation of this new trait would be passed to the `Server` as this is the piece of code responsible for deciding if the file should be mapped or unmapped for instance. But thanks to the trait, it would not have to deal with the specifics of vhost-user, as it would not know anything about the slave fd and the rest.

**Comment by liubogithub** [comment]
After fighting with rust gramma and compiler for a few days, now I got `target/release/vhost_user_fs` work with the dax mode.

> @liubogithub
> First thing, you need to implement [`VhostUserMasterReqHandler`](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vhost_rs/src/vhost_user/master_req_handler.rs#L17) trait.
> 
> Once you got that implemented with your own structure, you will be able from `vhost_user_backend` to provide it to `src/bin/vhost_user_fs.rs`.
> 
> The last step is to let the Server be able to trigger a `map`, an `unmap` and a `sync`. In this case, I would suggest you define a new Trait in `vhost_user_fs` crate. This trait would have three functions `map()`/`unmap()`/`sync()` that `src/bin/vhost_user_fs.rs` would implement. The implementation of this new trait would be passed to the `Server` as this is the piece of code responsible for deciding if the file should be mapped or unmapped for instance. But thanks to the trait, it would not have to deal with the specifics of vhost-user, as it would not know anything about the slave fd and the rest.
> I didn't look into the details of `Server` and `Passthrough`, so I'm not sure which one should actually access the new trait to trigger a map/unmap.

Thanks for the input! 
I added a `SlaveFsCacheReq` in `vhost_rs/src/vhost_user/slave_fs_cache.rs` instead because it seems all master/slave negotiation parts have been put in `vhost_rs`.

**Comment by sboeuf** [comment]
@liubogithub oh nice!! I can't wait for the PR :)

**Comment by liubogithub** [comment]
@sboeuf FYI, I've just submitted a PR, this is probably a RFC version since I'm too new to writing rust code.

please let me know if any comments.

**Comment by rbradford** [comment]
@sboeuf @liubogithub is this fixed now?

**Comment by sboeuf** [comment]
@rbradford yes! let's close it
