### ISSUE TITLE
AMD SEV-SNP, OVMF and fw_cfg

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#4814]
The Confidential Pods project uses OVMF for AMD SEV-SNP support. That implementation requires `fw_cfg` to inject payloads into the guest.

There is no `fw_cfg` in Cloud Hypervisor. IIRC it was explicitly rejected.

With the new information available, what is the possible solution for supporting AMD SEV-SNP?

CC @jinankjain

**Comment by liuw** [comment]
> @liuw IIUC, you're saying the AMD SEV-SNP specification explicitly relies on `fw_cfg` to provide payloads to the guest. Can you point me to the location in the spec? I would have expected another mechanism to be supported to perform such operation.
> 
> For example, TDSHIM (the light version of the TDX firmware called TDVF) can inject payloads relying on the UEFI HOB (HandOff Block) standard. It defines a specific GUID with an associated structure so the firmware running in the guest can retrieve it.

No, SEV-SNP specification does not rely on `fw_cfg`. It is the current implementation (OVMF as the firmware) that has this dependency.

TD-SHIM does not support AMD SEV-SNP at all. There is nobody working on that.

So if OVMF is to be supported with Cloud Hypervisor, we either need to make changes to OVMF to not rely on fw_cfg, or we implement fw_cfg in Cloud Hypervisor.

**Comment by sboeuf** [comment]
> > @liuw IIUC, you're saying the AMD SEV-SNP specification explicitly relies on `fw_cfg` to provide payloads to the guest. Can you point me to the location in the spec? I would have expected another mechanism to be supported to perform such operation.
> > For example, TDSHIM (the light version of the TDX firmware called TDVF) can inject payloads relying on the UEFI HOB (HandOff Block) standard. It defines a specific GUID with an associated structure so the firmware running in the guest can retrieve it.
> 
> No, SEV-SNP specification does not rely on `fw_cfg`. It is the current implementation (OVMF as the firmware) that has this dependency.

Gotcha!

> 
> TD-SHIM does not support AMD SEV-SNP at all. There is nobody working on that.

Oh yes I know and I'm not expecting this would ever happen, but I was pointing at an example that didn't need to rely on `fw_cfg` to inject specific payloads.

> 
> So if OVMF is to be supported with Cloud Hypervisor, we either need to make changes to OVMF to not rely on fw_cfg, or we implement fw_cfg in Cloud Hypervisor.

Oh I would really encourage changes to happen in OVMF. We already went through that kind of discussion for TDX, allowing ACPI tables to be passed through a dedicated HOB rather than using `fw_cfg`. I think it would make lot of sense to discuss with the EDK2/AMD SEV maintainers about an acceptable alternative that wouldn't require `fw_cfg` support.

**Comment by jinankjain** [comment]
Any specific reasons for not implementing the fw-cfg interface? I am missing the background story here.

**Comment by sboeuf** [comment]
It's a QEMU specific protocol and it's not standardized anywhere. We've always tried to rely on well defined specifications such as ACPI, UEFI, etc...
