### ISSUE TITLE
CH nested on AMD on Azure underperforms vs Firecracker

### ISSUE THREAD

**Issue by DeciderWill** [cloud-hypervisor/cloud-hypervisor#4827]
We'd like to try use MSHV with CLH.

We cannot find any documentation or approaches to use MSHV. Is this an internal Azure capability? Looking at the CI process there is a Windows 11 IoT kernel being used for the tests.

We use Kata and CLH on multiple clouds. When running CLH with Azure and AMD CPUs we see 50-90% degradation in CPU performance when using nested KVM + AMD + CLH. 50% degradation with Firecracker and 80-90% degradation with Qemu and CLH. Intel only sees a 10% degradation. 

Results: [https://docs.google.com/spreadsheets/d/1-IDFj4OnqhJxl0gTAJUlETc9-lw_vdfLggbxPaBveKY/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1-IDFj4OnqhJxl0gTAJUlETc9-lw_vdfLggbxPaBveKY/edit?usp=sharing)

Our limited understanding is that MSHV can be run on a Linux machine and potentially could enhance performance when used on Azure VMs that are virtualized with HyperV.

HyperV appears to not be optimised for nested VMs on EPYC and Ryzen CPUs and we are looking for methods to boost performance.

Any pointers on MSHV or CLH performance on Azure AMD VMs would be of great help.

**Comment by liuw** [comment]
Hi, unfortunately you cannot use it yet because the hypervisor binaries cannot be easily distributed. :-(

That said, the architecture of MSHV means it has more exits than KVM, so it is unlikely that it will be more performant if KVM has all the bells and whistles enabled.

The degradation is more about nested KVM performance on Azure -- as you can see QEMU also suffers from the same fate.

**Comment by rbradford** [comment]
@liuw I don't know where you could document the unavailability of MSHV for external testing.

@DeciderWill It's pleasing to see there is very little overhead between baremetal and CH+Kata on the Intel machine SKUs.

As the VMM, Cloud Hypervisor does not do anything special when running nested (i.e. the layers of nesting are transparent to the VMM) so unfortunately there is nothing actionable there. I can see from your data that not running in a nested environment gives similar performance between the two different platforms.

**Comment by DeciderWill** [comment]
@liuw do you know the team working on HyperV nested AMD support? It's taking time to get this escalated through the relevant Azure support lines.

@rbradford agreed the baremetal performance is exciting

**Comment by liuw** [comment]
> @liuw do you know the team working on HyperV nested VM w/ AMD (or could find out)? It's taking time to get this escalated through the relevant Azure support lines.
> 

I will have a look.

**Comment by liuw** [comment]
The does not make sense to me. Why does Firecracker perform better?

The test is about CPU performance. Does Firecracker somehow enables more CPU features than Cloud Hypervisor?

<html>
<body>


Azure | AMD | Y | Y | D96ads_v5 Firecracker | 17823885 | 650
-- | -- | -- | -- | -- | -- | --
Azure | AMD | Y | Y | D96ads_v5 Kata CLH | 18255959 | 177


</body>
</html>

**Comment by DeciderWill** [comment]
Hi @liuw 

Agreed the results are surprising that Firecracker can achieve 650. We have run the tests multiple times and have received similar results.

Another Firecracker run: https://browser.geekbench.com/v5/cpu/18412840 (50% reduction in perf)

Interestingly when running Kata Firecracker and device mapper we see extremely poor performance again similar to Kata CLH: https://browser.geekbench.com/v5/cpu/18412050 (90% reduction in perf)

So outside of the HyperV issue looks like there is also sometime else to look at.

Comparing the Firecracker and Kata Firecracker run:
https://browser.geekbench.com/v5/cpu/compare/18412050?baseline=18412840

It appears that L1 Instruction Cache & L1 Data Cache is unavailable for KVM nested workloads on Azure AMD CPUs.

Unlikely CLH related, and more likely Kata but we can see a different outcome for the spec:
Kata: 1 Processor, 1 Core
Firecracker:  1 Processor, 1 Core, 2 Threads

**Comment by liuw** [comment]
> Hi @liuw
> 
> Agreed the results are surprising that Firecracker can achieve 650. We have run the tests multiple times and have received similar results.
> 
> Another Firecracker run: https://browser.geekbench.com/v5/cpu/18412840 (50% reduction in perf)
> 
> Interestingly when running Kata Firecracker and device mapper we see extremely poor performance again similar to Kata CLH: https://browser.geekbench.com/v5/cpu/18412050 (90% reduction in perf)
> 

This is interesting, so perhaps it is something to do with Kata's configuration.

To get apple to apple comparison, it may also worth running CH directly.

Also, can you share how you run geekbench?

**Comment by liuw** [comment]
> Comparing the Firecracker and Kata Firecracker run:
https://browser.geekbench.com/v5/cpu/compare/18412050?baseline=18412840

There is a huge difference in memory size.

**Comment by DeciderWill** [comment]
@liuw 

Agreed on Kata configuration, we'll promptly run tests with CH directly.

### Running Geekbench:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  runtimeClassName: kata-clh
  containers:
  - name: ubuntu
    image: ubuntu:latest
    resources:
      limits:
        cpu: "2"
        memory: "8Gi"
        ephemeral-storage: "10Gi"
      requests:
        cpu: "2"
        memory: "8Gi"
        ephemeral-storage: "10Gi"
```

Command to run within the pod:

```
apt-get update && apt install tar wget -y
wget https://cdn.geekbench.com/Geekbench-5.4.0-Linux.tar.gz
tar xf Geekbench-5.4.0-Linux.tar.gz
cd Geekbench-5.4.0-Linux
./geekbench5
```

We've also been testing Kata 3.0 + Dragonball, and interestingly 1.95GB appeared again for an 8GB request/limit - could be red herring. However, it's likely to be the default memory assigned by Kata. https://github.com/kata-containers/kata-containers/issues/5644 (Dragonball doesn't support Hotplugging for CPU and Memory)

Does Cloud Hypervisor support Hotplugging CPU/memory on AMD/HyperV?

**Comment by liuw** [comment]
I tried to find out exactly what Geekbench 5 does, but their web site is very vague. I only got:

> Geekbench 5's CPU benchmark measures performance in new application areas including Augmented Reality and Machine Learning, so you'll know how close your system is to the cutting-edge.

It seems to me it could be sensitive to the size of memory too. ML is memory hungry if I'm not mistaken.

> Does Cloud Hypervisor support Hotplugging CPU/memory on AMD/HyperV?

You mean KVM on Azure? Yes, CH supports CPU and memory hotplug.

**Comment by DeciderWill** [comment]
Each run has a breakdown of each test and the performance per test.

Documentation on specific tests: https://www.geekbench.com/doc/geekbench5-cpu-workloads.pdf

![image](https://user-images.githubusercontent.com/1247896/201349787-1e47554e-7f53-4501-81f2-5147bbb62fee.png)

![image](https://user-images.githubusercontent.com/1247896/201349727-815fe150-0e96-4d3a-9d7f-c2c09e02c87b.png)

**Comment by liuw** [comment]
Closing this as this is an issue with Azure, not an issue with Cloud Hypervisor.
