### ISSUE TITLE
Remove MemoryZoneConfig::file

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#4837]
This functionality adds a lot of complexity and I want to discuss if we should support it. Currently you can supply a file or a directory (creating a file if you do so) which will be used to back the RAM region for this zone.

However the hugepage flags are ignored so you cannot map in a file using huge pages (this would need different mmap flags) and there is no validation of this (in fact there is no `MemoryConfig::validate()`).

I think it would be very easy to make a mistake when combined with `shared=on` if you want to do templating but also support vhost-user as then all users would see the changes to the file. I think specific support for templating (perhaps using `userfaultd` or an explicit copy of the guest RAM) would be better solutions to templating.

**Comment by sboeuf** [comment]
I agree with the general idea that templating is a very specific feature and that should require some special handling. At the moment the way to use the feature is too implicit and I'm not sure a single person actually uses it.

**Comment by rbradford** [comment]
I'm proposing we go ahead and deprecate & later remove `MemoryZoneConfig`?

**Comment by rbradford** [comment]
@praveenkumr If you want to create a PR undeprecrating this / reverting the commit then I will approve it. But I would still like to understand the specific use case. Since `MAP_SHARED` is now the norm for anonymous mappings perhaps we could remove `MemoryZoneConfig::shared` as it only has meaning when `MemoryZoneConfig::file` is used.
