### ISSUE TITLE
Analyzing load_payload overhead

### ISSUE THREAD

**Issue by ljrcore** [cloud-hypervisor/cloud-hypervisor#4839]
By tracing CLH, I found that the overhead of load_payload is about 24ms. by further analysis and locating, it is the overhead generated here. ` vmm/src/vm.rs `
```rust
        let entry_addr = linux_loader::loader::elf::Elf::load(
            mem.deref(),
            None,
            &mut kernel,
            Some(arch::layout::HIGH_RAM_START),
        )
        .map_err(Error::KernelLoad)?;
```
The more detailed sources of overhead I don't quite understand. Any insight?

**Comment by liuw** [comment]
That's extremely slow. How did you get the measurement? Can you post your code somewhere?

**Comment by ljrcore** [comment]
> That's extremely slow. How did you get the measurement? Can you post your code somewhere?

I got the overhead analysis image in svg format by the method of [trace](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/tracing.md)([like this](https://i.niupic.com/images/2022/10/31/aa5K.png)). Among them, load_payload shows 25ms. I would like to know more details about the rationale for this overhead, or the function executed in the kernel.

Thanks

**Comment by liuw** [comment]
I have not played with tracing before. I would suggest you print some timestamps in code instead. It is extremely slow by modern standard to take milliseconds to load files.

Just by looking at the code, one guess is the time it measures may take into account joining the thread. The joining happens in `entry_point` which matches exactly where the measurement for `load_payload` ends.

Since it is running in parallel with other threads, even if it really takes 24ms for the whole thread to run it may not matter for the overall boot time.

**Comment by ljrcore** [comment]
My guess is that the large time consumption of load_payload is causing the extension of the entry_point end point. If the `load_payload` time can be shortened, then the overall CLH startup time will also be shortened. Therefore, I would like to find where the `load_payload` time consumption is. Also, I would like to know how to shorten the time consuming of `load_payload`.

Thanks

**Comment by liuw** [comment]
> My guess is that the large time consumption of `load_payload` is causing the extension of the `entry_point` end point. If the `load_payload` time can be shortened, then the overall CLH startup time will also be shortened. Therefore, I would like to find where the `load_payload` time consumption is. Also, I would like to know how to shorten the time consuming of `load_payload`.
> 

Please use timestamps to get an exact measurement for the code snippet you suspected that's using a lot of time.

**Comment by rbradford** [comment]
> I have not played with tracing before. I would suggest you print some timestamps in code instead. It is extremely slow by modern standard to take milliseconds to load files.

Loading the payload into guest RAM will result in EPT page faults and thus will take a lot longer than loading a file directly into a piece of `malloc()`ed memory. Using huge pages mitigates this as the number of faults is reduced. If we loaded the kernel into the memory before giving it to KVM we would not save any time as the page faults would just be moved to the boot time. By doing it here we can actually reduce the total boot time by doing it in parallel.

**Comment by ljrcore** [comment]
> > My guess is that the large time consumption of `load_payload` is causing the extension of the `entry_point` end point. If the `load_payload` time can be shortened, then the overall CLH startup time will also be shortened. Therefore, I would like to find where the `load_payload` time consumption is. Also, I would like to know how to shorten the time consuming of `load_payload`.
> 
> Please use timestamps to get an exact measurement for the code snippet you suspected that's using a lot of time.
> 
> Please also publish the code so that the upstream community can reproduce the issue easily.

I added this debug message to the `vmm/src/vm.rs`.
```
    #[cfg(target_arch = "x86_64")]
    fn load_kernel(
        mut kernel: File,
        cmdline: Option<Cmdline>,
        memory_manager: Arc<Mutex<MemoryManager>>,
    ) -> Result<EntryPoint> {
        info!("Loading kernel");
...
        debug!("point e-3-3");
        let entry_addr = linux_loader::loader::elf::Elf::load(
            mem.deref(),
            None,
            &mut kernel,
            Some(arch::layout::HIGH_RAM_START),
        )
        .map_err(Error::KernelLoad)?;
        debug!("point e-4");
...
    }
```
The log message is shown below.

**Comment by ljrcore** [comment]
> > I have not played with tracing before. I would suggest you print some timestamps in code instead. It is extremely slow by modern standard to take milliseconds to load files.
> 
> Loading the payload into guest RAM will result in EPT page faults and thus will take a lot longer than loading a file directly into a piece of `malloc()`ed memory. Using huge pages mitigates this as the number of faults is reduced. If we loaded the kernel into the memory before giving it to KVM we would not save any time as the page faults would just be moved to the boot time. By doing it here we can actually reduce the total boot time by doing it in parallel.

Loading the payload into guest RAM will result in EPT page failures. As a result, `load_kernel` will take longer. At this point, the `load_kernel` time consumption becomes a performance bottleneck for CLH startup. If the `load_kernel` time is reduced, e.g. using huge pages mitigates this as the number of faults is reduced, the overall CLH boot time will be reduced. Am I understanding this correctly?
Thanks

**Comment by liuw** [comment]
I did a quick test on my setup.

```
cloud-hypervisor: 41.862809ms: <payload_loader> ERROR:vmm/src/vm.rs:973 -- AAA
cloud-hypervisor: 41.947344ms: <vmm> INFO:vmm/src/device_manager.rs:2043 -- Creating virtio-block device: DiskConfig { path: Some("../focal-server-cloudimg-amd64.raw"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, rate_limiter_config: None, id: Some("_disk0"), disable_io_uring: false, pci_segment: 0 }
cloud-hypervisor: 42.131908ms: <vmm> INFO:vmm/src/device_manager.rs:2121 -- Using asynchronous RAW disk file (io_uring)
cloud-hypervisor: 42.159229ms: <vmm> INFO:virtio-devices/src/block.rs:459 -- Disk topology: DiskTopology { logical_block_size: 512, physical_block_size: 512, minimum_io_size: 512, optimal_io_size: 0 }
cloud-hypervisor: 42.196628ms: <vmm> INFO:vmm/src/device_manager.rs:2374 -- Creating virtio-rng device: RngConfig { src: "/dev/urandom", iommu: false }
cloud-hypervisor: 50.916925ms: <payload_loader> ERROR:vmm/src/vm.rs:981 -- BBB
```

It only took 9ms to load the reference kernel (45M in size). KVM is running nested on Azure.

**Comment by ljrcore** [comment]
Maybe the difference in the host environment is causing the difference in test results. Also, what is the 9ms overhead due to? Is it the EPT page faults?
Thanks

**Comment by rbradford** [comment]
> Maybe the difference in the host environment is causing the difference in test results. Also, what is the 9ms overhead due to? Is it the EPT page faults? Thanks

Yes, if you an older/slower system then it seems reasonable that loading the kernel would take 2x as long. And yes, the overhead is from the EPT page faults.

**Comment by ljrcore** [comment]
Thanks

**Comment by rbradford** [comment]
> @rbradford After commit [df7c728](https://github.com/cloud-hypervisor/cloud-hypervisor/commit/df7c728399783b909d3bfe51ae23cd0e7c594332), I test `load_payload` time is reduced to about 15ms. before that, I test load_payload time is about 30ms. Thanks

Great. It does make sense that that bug fix would improve the boot time there.
