### ISSUE TITLE
Windows.md contains dead link to networking.md

### ISSUE THREAD

**Issue by sdake** [cloud-hypervisor/cloud-hypervisor#4840]
**Describe the bug**
In the file https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/windows.md, a deadlink to networking.md is present. Would be awesome to see that file )

**To Reproduce**
Steps to reproduce the behaviour:
open webpage to:

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/windows.md
Click networking.md, and notice that the page 404s.

**Version**
main

Output of `cloud-hypervisor --version`:

Did you build from source, if so build command line (e.g. features):

**VM configuration**

What command line did you run (or JSON config data):

Guest OS version details:

Host OS version details:

**Logs**

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:

Linux kernel output:

**Comment by likebreath** [comment]
@sdake Thank you for reporting the issue. I did a quick search (bisect) and found the `networking.md` was removed during documentation relicensing #3480. It is a quite useful documentation. Would you have time to write a new one for the community?
