### ISSUE TITLE
ci: test_reboot is flaky

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#4849]
Several failures from the main builds and PR builds:

https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/main/1681/pipeline/
https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/main/1682/pipeline/
https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/main/1684/pipeline/
https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-4848/1/pipeline/

**Comment by rbradford** [comment]
More than flaky, seems like it pretty consistently fails.
