### ISSUE TITLE
add integration test for TPM device

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/cloud-hypervisor#4872]
https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4642 enables TPM driver for x86_64 architecture. Add an integration test for TPM driver following the documentation in the PR.

**Comment by rbradford** [comment]
@praveen-pk What's the timeline on this? We shouldn't really have functionality without integration testing (unless it is under a build feature.)

**Comment by praveen-pk** [comment]
@rbradford I will be out on vacation for a few weeks. I will try to enable an integration test for TPM by the end of this month after I get back from my vacation.

**Comment by praveen-pk** [comment]
`swtpm` program should be present in the Docker Container to be able to run a tpm test case. Unfortunately, `swtpm` package was not packaged in Ubuntu's 20.04 version. The options to move forward are:

1) Stick with 20.04, compile swtpm and all its dependencies during integration test setup.
2) Sitck with 20.04 and use PPA (Personal Package Archive) repository. These repositories are community maintained. Ex: https://launchpad.net/~smoser/+archive/ubuntu/swtpm.
3) Move Integration docker container to 22.04, which has swtpm package.

@rbradford, let me know which of the above options you prefer. I am currently working with Option 3, for adding TPM test case. This option could introduce breakage for other test cases. I have not tested this yet.

**Comment by sboeuf** [comment]
I'd lean towards option 3.

**Comment by rbradford** [comment]
Option 3 would be best but last time I tried to do this the SPDK repository didn't have support for 22.04. If it does now you will need to roll that forward too. Option 1 is doable and is the approach taken by other binary dependencies (e.g. SPDK nvme target.)

**Comment by praveen-pk** [comment]
https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5072 to migrate docker image used in Integration test to Ubuntu 22.04. Once this is merged, I will push the PR for the TPM test.

**Comment by praveen-pk** [comment]
PR https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5110
