### ISSUE TITLE
Replace use of phf in TPM device

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/cloud-hypervisor#4873]
Replacing `phf` with `HashMap` in TPM driver would help reduce the dependencies for the Project.

**Comment by liuw** [comment]
I think you can replace the string in code with a constant or enum and drop the need to use a hashmap.

**Comment by rbradford** [comment]
> I think you can replace the string in code with a constant or enum and drop the need to use a hashmap.

I thought the strings were part of the protocol but no, they're just for specifying the bitfield location. We also have the `bitflags` crate as a dependency which might also simplify a lot of this code.

**Comment by praveen-pk** [comment]
Thanks for the pointers, I will investigate these options and report back on the approach I choose.
