### ISSUE TITLE
Seccomp violation in cloudhypervisor

### ISSUE THREAD

**Issue by BharatNarasimman** [cloud-hypervisor/cloud-hypervisor#4874]
**Describe the bug**

This Seccomp violation happens intermittently in our tests during the VM boot,

Output when running cloudhypervisor with strace -f
(This looks like the epoll handler thread created for the virtio-fs corresponding to the tag "ip_file_path" below)

127444 rseq(0x7f7a4601dfe0, 0x20, 0, 0x53053053) = 0
127444 set_robust_list(0x7f7a4601d920, 24) = 0
127444 rt_sigprocmask(SIG_SETMASK, [INT TERM WINCH], NULL, 8) = 0
127444 sigaltstack(NULL, {ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}) = 0
127444 mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f7a45811000
127444 mprotect(0x7f7a45811000, 4096, PROT_NONE) = 0
127444 sigaltstack({ss_sp=0x7f7a45812000, ss_flags=0, ss_size=8192}, NULL) = 0
127444 prctl(PR_SET_NAME, "_fs5")       = 0
127444 sched_getaffinity(127444, 32, [0]) = 8
127444 prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) = 0
127444 prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, {len=140, filter=0x7f772c009910}) = 0
127444 epoll_create1(EPOLL_CLOEXEC)     = 227
127444 dup(225)                         = 228
127444 epoll_ctl(227, EPOLL_CTL_ADD, 209, {events=EPOLLIN, data={u32=1, u64=1}}) = 0
127444 epoll_ctl(227, EPOLL_CTL_ADD, 225, {events=EPOLLIN, data={u32=0, u64=0}}) = 0
127444 epoll_ctl(227, EPOLL_CTL_ADD, 77, {events=EPOLLHUP, data={u32=16, u64=16}}) = 0
127444 mprotect(0x7f7a38063000, 4096, PROT_READ|PROT_WRITE) = 10
127444 --- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7f7a47dccc5b, si_syscall=__NR_mprotect, si_arch=AUDIT_ARCH_X86_64} ---
127444 write(2, "\n==== Possible seccomp violation"..., 173) = 173
127444 rt_sigaction(SIGSYS, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f7a47cf0520}, NULL, 8) = 13
127444 --- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7f7a47cf05f3, si_syscall=__NR_rt_sigaction, si_arch=AUDIT_ARCH_X86_64} ---

**To Reproduce**
Steps to reproduce the behaviour:

**Version**

cloud-hypervisor v25.0-206-ge45e3df6

**VM configuration**

{'vm_config': '{"cpus":{"boot_vcpus":4,"max_vcpus":4},"memory":{"size":12884901888,"shared":true},"kernel":{"path":"<cleaned_out_path>/OVMF-CLOUDHV.fd"},"disks":[{"path":"<cleaned_out_path>/mysql_temp_volume_6_Inc0_actx_/work/eabd32e3c4833c4f.mysql_temp_volume_6_Inc0_actx_.default_vm_deployment_Inc16679484412057567_actx_3e83d0b9-b76d-bb40-ac87-9c7fb88d12cf.default_vm_deployment.raw"},{"path":"<cleaned_out_path>/Applications/mysql_temp_volume_6_Inc0_actx_/work/mysql_temp_volume_6_Inc0_actx_/default_vm_deployment_Inc16679484412057567_actx_3e83d0b9-b76d-bb40-ac87-9c7fb88d12cf/default_vm_deployment/cloud-init/nocloud_ds.iso"}],"net":[{"tap":"meru-tap1","mac":"2e:4d:f1:9f:d2:5a"}],"fs":[{"tag":"meru-mount-tag-1","socket":"/tmp/vmmd_sockets/virtiofsd-socket-3","num_queues":1,"queue_size":512},{"tag":"/secrets","socket":"/tmp/vmmd_sockets/virtiofsd-socket-4","num_queues":1,"queue_size":512},{"tag":"ip_file_path","socket":"/tmp/vmmd_sockets/virtiofsd-socket-5"}],"work_directory_path":"<cleaned_out_path>/work/Applications/mysql_temp_volume_6_Inc0_actx_/work","serial":{"mode":"Tty"},"console":{"mode":"Off"},"cmdline":{"args":"console=ttyS0"}}'},

Guest OS version details:

Ubuntu 22.04

Host OS version details:
Ubuntu 22.04

**Logs**

Cloud-hypervisor -v logs attached.

[chv.124254.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/9984235/chv.124254.log)

**Comment by likebreath** [comment]
Thank you for reporting the issue. Would you please send a PR to fix it. In general, you will need to find which thread the seccomp violation is from and add the missing syscall to the allowed list in [1][2]. Also you may find useful information from our document on seccomp [3].

[1] https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/vmm/src/seccomp_filters.rs
[2] https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/virtio-devices/src/seccomp_filters.rs
[3] https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/seccomp.md

**Comment by likebreath** [comment]
@BharatNarasimman I just noticed you were running an older version of Cloud Hypervisor. Please validate the issue with upstream version. Thank you.

**Comment by BharatNarasimman** [comment]
Thanks @likebreath  - I will test in the latest version as well and report. I am not sure why this is not reproing 100% and if that needs to be investigated further before adding this to the allowed list.

**Comment by rbradford** [comment]
@BharatNarasimman If you add `--decode-pids=comm` to strace you can see the thread name.
