### ISSUE TITLE
some scripts are directory-dependent

### ISSUE THREAD

**Issue by sdake** [cloud-hypervisor/cloud-hypervisor#4882]
**Describe the bug**
Attempting to run the integration tests fails locally when executed within the scripts directory. Some may find this confusing.

**To Reproduce**
```
git clone https://github.com/cloud-hypervisor/cloud-hypervisor
cd cloud-hypervisor/scripts
bash run_integration_tests_x86_64.sh
```

**Version**
commit 86c19816c612c3bec82f53b4b77ce005d1100edb

Output of `cloud-hypervisor --version`:
This is a repository issue, not an issue with the binary.

Did you build from source, if so build command line (e.g. features):
yes.

**VM configuration**

What command line did you run (or JSON config data):

Guest OS version details:

Host OS version details:

**Logs**

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:

Linux kernel output:

**Comment by rbradford** [comment]
That script is designed to be run by `dev_cli.sh`
