### ISSUE TITLE
Unstated integration test dependencies

### ISSUE THREAD

**Issue by sdake** [cloud-hypervisor/cloud-hypervisor#4883]
**Describe the bug**
Local execution of integration tests results in failures.

**To Reproduce**
```
bash scripts/run_integration_tests_x86_64.sh
```

results in:
```
  LEX     scripts/kconfig/lexer.lex.c
/bin/sh: 1: flex: not found
  YACC    scripts/kconfig/parser.tab.[ch]
/bin/sh: 1: bison: not found
make[2]: *** [scripts/Makefile.host:9: scripts/kconfig/lexer.lex.c] Error 127
```

**Version**
86c19816c612c3bec82f53b4b77ce005d1100edb

**Comment by liuw** [comment]
That's Linux kernel's dependency.

Is there a reason why you don't use the docker container to run the integration tests?

**Comment by sdake** [comment]
Sure, aware this is a Kernel dep. As I was working towards this work:

https://github.com/oifv-ai/oifv/pull/22

I recorded various problems I found with the integration testing. A few minutes after I filed this issue, I found:
```
scripts/dev_cli.sh tests --integration
```

I am aware the integration tests document a mechanism for using vhost-user-net within a VM. I have not been able to get this to work correctly, unfortunately, just by reading the code.

My goal is to add a simple command to oifv `oifvctl login` which:
1. creates a virtual machine if one does not exist
1. Logs in, via SSH, to the virtual machine locally

I have a [bash version](https://github.com/oifv-ai/oifv/blob/main/src/bin/oifvctl/run-chv.sh) that I could now integrate into the [oifv command line tool](https://github.com/oifv-ai/oifv/blob/main/src/bin/oifvctl/main.rs), although this bash version lacks vhost-user-net integration.

I thought displaying the various networking commands by running the integration tests would provide some clues.

If you wish, would welcome a look!

Cheers,
-steve

**Comment by rbradford** [comment]
That script can only be run indirectly via `dev_cli.sh`

**Comment by rbradford** [comment]
> I am aware the integration tests document a mechanism for using vhost-user-net within a VM. I have not been able to get this to work correctly, unfortunately, just by reading the code.

There is docs/vhost-user-net-testing.md  which has details of using vhost-user-net with OpenVSwitch.

**Comment by sdake** [comment]
> > I am aware the integration tests document a mechanism for using vhost-user-net within a VM. I have not been able to get this to work correctly, unfortunately, just by reading the code.
> 
> 
> 
> There is docs/vhost-user-net-testing.md  which has details of using vhost-user-net with OpenVSwitch.
> 
> 

Sure although the integration tests appear to show the usage of a vhost-user-net backend as a mac tap interface which is what I want.

**Comment by rbradford** [comment]
> > > I am aware the integration tests document a mechanism for using vhost-user-net within a VM. I have not been able to get this to work correctly, unfortunately, just by reading the code.
> > 
> > 
> > There is docs/vhost-user-net-testing.md  which has details of using vhost-user-net with OpenVSwitch.
> 
> Sure although the integration tests appear to show the usage of a vhost-user-net backend as a mac tap interface which is what I want.

The reference/testing backend doesn't support macvtap (`target/debug/vhost_user_net --help`)?  Are you getting confused with the virtio-net support?

**Comment by sdake** [comment]
@rbradford the code I am referencing:
[Create process vhost-user-net daemon process](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/tests/integration.rs#L211-L218)
[Test cases, that use vhost-user-net daemon process](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/tests/integration.rs#L2909-L2960).
[Matching net specification to cloud-hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/tests/integration.rs#L825)

Again, what I want to do:
1. connect from the host to the virtual machine with the minimal footprint maximum security model, using ssh.
2. I am aware of vsock, and have some work already there.

Cheers,
-steve

4.

**Comment by rbradford** [comment]
@sdake If you look at the code in `vhost_user_net/{lib.rs,main.rs}` there is no support for macvtap.

**Comment by rbradford** [comment]
If you want to run with vhost-user-net and the reference backend then you can just do this:

`target/debug/vhost_user_net --net-backend socket=/tmp/net-socket,tap=`

And then add 

`--net socket=/tmp/net-socket,vhost_user=on`

To have CH use it. It will use the default `192.168.249.1` ip just like `--net tap=`

**Comment by rbradford** [comment]
But this backend only really exists for testing vhost-user-net. I'd expect virtio-net would be fine for your use case.
