### ISSUE TITLE
virtiofsd instructions download binary from nonexistent location

### ISSUE THREAD

**Issue by joshtriplett** [cloud-hypervisor/cloud-hypervisor#491]
The documentation on https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/fs.md include instructions to download a virtiofsd binary, and those instructions reference an outdated URL.

Perhaps suggest how to build the daemon from source?

**Comment by sboeuf** [comment]
@joshtriplett Thanks for raising the issue. I will update the documentation as you suggested (explaining how to build it from source) since this is exactly what our CI does every day.
