### ISSUE TITLE
Test mshv+kvm release binary

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#4915]
Now that that release binary is built with both these features turned on (#4912) the integration testing should be extended to cover testing that dual binary. As the `mshv` and `kvm` features are used by the integration test suite to exclude tests that don't work on `mshv` we need a solution to allow the binary to build with both features but exclude certain tests

**Comment by rbradford** [comment]
This needs to be resolved as part of v29.0 or roll-back #4912 as we shouldn't ship a binary we don't test :-)

**Comment by weltling** [comment]
We'd be probably technically able to provide an image to run nested on Azure for tests. There might be legal questions, though. And another point is - it's still moving quite rapidly so the test stability might be not as expected. Probably the legal question is even a bigger point. We test the `mshv` part extensively, that's what i can add anyway.

I think it should be also possible to create a separate setup to be plugged into the Cloud Hypervisor test runs, now that `mshv` can run nested on Azure. This might be also better from the legal side, as no `mshv` image would have to be shared. Last time this topic was touched, AFAIR another point at that time was that only baremetal setup was possible. Now with the nested setup available, baremetal would be still not involved but even with the nested `mshv` the coverage would be already a good progress.

/cc @liuw @russell-islam @NunoDasNeves

**Comment by rbradford** [comment]
@weltling To be clear. I'm not saying that we need to test mshv on our CI. Rather we need to test the combined binary (right now we just test the kvm binary but offer the kvm+mshv binary for users to download.)

**Comment by weltling** [comment]
@rbradford thanks for the clarification, i see what you mean now. So this implies a change to the scripting part or perhaps set default features to `kvm,mshv` in `Cargo.toml`. I'd guess the former might be more convenient? Say if no `--hypervisor` is passed, the script has to enable both.

This probably would not exclude having some CI part with nested mshv plugged into the validation, but that would be a separate topic then.

Thanks
