### ISSUE TITLE
aarch64 static release binary is large

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#4916]
The aarch64 binary needs stripping:

```
marvin:~$ file cloud-hypervisor-static-aarch64 
cloud-hypervisor-static-aarch64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

**Comment by MrXinWang** [comment]
I remember the reason why we didn't strip aarch64 binary was: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2976#issuecomment-900960592. But I just checked the latest dockerfile in https://github.com/cross-rs/cross/tree/main/docker and it seems the base image has been updated for AArch64 so things might change now.

**Comment by MrXinWang** [comment]
@rbradford @sboeuf @michael2012z So I did some tests about the release binary stripping. The method is basically below patch based on https://doc.rust-lang.org/beta/cargo/reference/profiles.html#strip:
```
diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
index c4dab9e4..b8eff619 100644
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -23,6 +23,11 @@ jobs:
         with:
             toolchain: "1.62"
             target: x86_64-unknown-linux-musl
+      - name: Install cargo strip
+        uses: actions-rs/install@v0.1
+        with:
+            crate: cargo-strip
+            version: latest
       - name: Build
         uses: actions-rs/cargo@v1
         with:
@@ -35,8 +40,11 @@ jobs:
             toolchain: "1.62"
             command: build
             args: --all --release --no-default-features --features "kvm,mshv" --target=x86_64-unknown-linux-musl
-      - name: Strip cloud-hypervisor binaries
-        run: strip target/*/release/cloud-hypervisor
+      - name: Strip cloud-hypervisor binaries using cargo-strip
+        uses: actions-rs/cargo@v1
+        with:
+           command: strip
+           args: --target x86_64-unknown-linux-musl
       - name: Install Rust toolchain (aarch64-unknown-linux-musl)
         uses: actions-rs/toolchain@v1
         with:
@@ -49,6 +57,11 @@ jobs:
             use-cross: true
             command: build
             args: --all --release --target=aarch64-unknown-linux-musl
+      - name: Strip cloud-hypervisor binaries using cargo-strip (AArch64)
+        uses: actions-rs/cargo@v1
+        with:
+           command: strip
+           args: --target aarch64-unknown-linux-musl
       - name: Vendor
         working-directory: ../cloud-hypervisor-${{ github.event.ref }}
         run: |
diff --git a/Cargo.toml b/Cargo.toml
index 3e5eb778..cc4468cb 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -16,6 +16,7 @@ rust-version = "1.60"
 lto = true
 codegen-units = 1
 opt-level = "s"
+strip = "debuginfo"

 [dependencies]
 anyhow = "1.0.66"
```

With this method, the x86 released binary is 5.84 MB and aarch64 binary is 4.82 MB.

So we have the conclusion: Using this new method, the aarch64 release binary can be reduced (by quite a lot), but we see a "size regression" in x86 release binary compared to the current method we are using (`strip target/*/release/cloud-hypervisor`).

I would like to hear about how would you think about this. Thank you very much!

**Comment by rbradford** [comment]
With 1.59 there is no need to have `cargo strip` installed: https://doc.rust-lang.org/cargo/reference/profiles.html#strip (it's built into the toolchain.

I'm content with the idea of just moving to using `strip = true` in the `Cargo.toml`. Our minimum toolchain is already new enough (1.60)

**Comment by MrXinWang** [comment]
> With 1.59 there is no need to have `cargo strip` installed: https://doc.rust-lang.org/cargo/reference/profiles.html#strip (it's built into the toolchain.

Yes, this is true.

> 
> I'm content with the idea of just moving to using `strip = true` in the `Cargo.toml`. Our minimum toolchain is already new enough (1.60)

Thank you very much for the reply! https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4919 created.
