### ISSUE TITLE
error when using macvtap 

### ISSUE THREAD

**Issue by datong-new** [cloud-hypervisor/cloud-hypervisor#4917]
hello, I want to use the internet in VM, and some kind friends @rbradford  suggest using macvtap (https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4881#issuecomment-1313285513). 

When I follow the tutorial in https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/macvtap-bridge.md , unfortunately I encountered the following error:
```
Error booting VM: VmBoot(DeviceManager(CreateVirtioNet(TapError(IoctlError(Os { code: 25, kind: Uncategorized, message: "Inappropriate ioctl for device" })))))
```

My scripts are shown here:
```

# The MAC address must be attached to the macvtap and be used inside the guest
mac="c2:67:4f:58:28:cb"
# Host network adapter to bridge the guest onto
host_net="wlo1"

# Create the macvtap0 as a new virtual MAC associated with the host network
sudo ip link add link "$host_net" name macvtap0 type macvtap
sudo ip link set macvtap0 address "$mac" up
sudo ip link show macvtap0

# A new character device is created for this interface
tapindex=$(< /sys/class/net/macvtap0/ifindex)
tapdevice="/dev/tap$tapindex"

# Ensure that we can access this device
sudo chown "$UID.$UID" "$tapdevice"
sudo chmod -R 777 "$tapdevice"

sudo ./cloud-hypervisor \
        --kernel hypervisor-fw \
        --console off \
        --serial tty \
        --disk path=focal-server-cloudimg-amd64.raw \
        --cmdline "console=ttyS0 root=/dev/vda1 rw" \
        --cpus boot=4 \
        --memory size=1024M \
        --api-socket=/tmp/ch-socket \
        --net fd=3,mac=$mac 3<>$"$tapdevice"

```

**Comment by rbradford** [comment]
> hello, I want to use the internet in VM, and some kind friends @rbradford suggest using macvtap ([#4881 (comment)](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4881#issuecomment-1313285513)).
> 
> When I follow the tutorial in https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/macvtap-bridge.md , unfortunately I encountered the following error:
> 
> ```
> Error booting VM: VmBoot(DeviceManager(CreateVirtioNet(TapError(IoctlError(Os { code: 25, kind: Uncategorized, message: "Inappropriate ioctl for device" })))))
> ```
> 
> My scripts are shown here:
> 
> ```
> 
> # The MAC address must be attached to the macvtap and be used inside the guest
> mac="c2:67:4f:58:28:cb"
> # Host network adapter to bridge the guest onto
> host_net="wlo1"
> 
> # Create the macvtap0 as a new virtual MAC associated with the host network
> sudo ip link add link "$host_net" name macvtap0 type macvtap
> sudo ip link set macvtap0 address "$mac" up
> sudo ip link show macvtap0
> 
> # A new character device is created for this interface
> tapindex=$(< /sys/class/net/macvtap0/ifindex)
> tapdevice="/dev/tap$tapindex"
> 
> # Ensure that we can access this device
> sudo chown "$UID.$UID" "$tapdevice"
> sudo chmod -R 777 "$tapdevice"
> 
> sudo ./cloud-hypervisor \
>         --kernel hypervisor-fw \
>         --console off \
>         --serial tty \
>         --disk path=focal-server-cloudimg-amd64.raw \
>         --cmdline "console=ttyS0 root=/dev/vda1 rw" \
>         --cpus boot=4 \
>         --memory size=1024M \
>         --api-socket=/tmp/ch-socket \
>         --net fd=3,mac=$mac 3<>$"$tapdevice"
> ```

I see you're using a wifi ethernet device? Did any of the earlier commands fail? i.e. is the file `/dev/tapN` created?

**Comment by datong-new** [comment]
> I see you're using a wifi ethernet device? Did any of the earlier commands fail? i.e. is the file `/dev/tapN` created?

Thanks for your reply!
Yes, I am using Wi-Fi. No failure in the earlier command, and the /dev/tap5 has been created.

**Comment by rbradford** [comment]
@datong-new I have created a PR at #4937  which will help improve this by making it easier to see which ioctl triggered the error. Perhaps you could try building with that patch and trying again?

**Comment by datong-new** [comment]
> @datong-new I have created a PR at #4937 which will help improve this by making it easier to see which ioctl triggered the error. Perhaps you could try building with that patch and trying again?

Thanks for your help. I have rebuilt the newest code of the main branch, and the error messages are as follow:
```
Error booting VM: VmBoot(DeviceManager(CreateVirtioNet(TapError(IoctlError(2147767506, Os { code: 25, kind: Uncategorized, message: "Inappropriate ioctl for device" })))))
```

And what the number code 2147767506 meaning?

**Comment by liuw** [comment]
2147767506 is 0x800454D2. It is the IOCTL number.

**Comment by datong-new** [comment]
> It's `TUNGETIFF`. And it's one of the first `ioctl()` calls made at the start of `from_tap_fd()` so maybe the file descriptor is not a valid tap device
Can you successfully use this macvtap on your machine? I have tried two different machines and both failed with this error.

**Comment by rbradford** [comment]
> > It's `TUNGETIFF`. And it's one of the first `ioctl()` calls made at the start of `from_tap_fd()` so maybe the file descriptor is not a valid tap device
> 
> Can you successfully use this macvtap on your machine? I have tried two different machines and both failed with this error.

Were you using wifi in both cases?

**Comment by datong-new** [comment]
> > > > It's `TUNGETIFF`. And it's one of the first `ioctl()` calls made at the start of `from_tap_fd()` so maybe the file descriptor is not a valid tap device
> > > 
> > > 
> > > Can you successfully use this macvtap on your machine? I have tried two different machines and both failed with this error.
> > 
> > 
> > Were you using wifi in both cases?
> 
> I just tested it with main and the instructions in https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/macvtap-bridge.md and it worked fine with my wired ethernet connection (supporting macvlan/macvtap is driver dependent.)

I tested it with both wifi and wired connection, and both failed using macvtap. Finally I set the bridge manually, using the following commands:


```
sudo ./cloud-hypervisor \
        --kernel ./hypervisor-fw \
        --console off \
        --serial tty \
        --disk path=./focal-server-cloudimg-amd64.raw \
        --cmdline "root=/dev/vda1 console=hvc0" \
        --cpus boot=4 \
        --memory size=1024M \
        --api-socket=/tmp/ch-socket3

sudo ./ch-remote --api-socket=/tmp/ch-socket3 add-net tap=chtap1

## in the host machine
sudo brctl addbr br0
sudo brctl addif br0 eno2
sudo brctl stp br0 on
sudo ifconfig eno2 0
sudo dhclient br0
route -n
sudo ip link set dev chtap1 up
sudo brctl addif br0 chtap1
sudo iptables -P FORWARD ACCEPT # it is needed to connect to internet

## in the guest
sudo ip link set dev ens3 up
sudo dhclient ens3 # (or set static ip using this command:  sudo ip addr add ***.***.***.***/24 dev ens3)


```

**Comment by rbradford** [comment]
@datong-new I'm glad it's working for you. You never mentioned your host kernel config. Could it be possible that the driver wasn't available?

**Comment by datong-new** [comment]
> @datong-new I'm glad it's working for you. You never mentioned your host kernel config. Could it be possible that the driver wasn't available?

I am using Ubuntu 22.04.1 LTS and its kernel is Linux 5.15.0-56-generic x86_64 .

**Comment by adamliyi** [comment]
> > @datong-new I'm glad it's working for you. You never mentioned your host kernel config. Could it be possible that the driver wasn't available?
> 
> I am using Ubuntu 22.04.1 LTS and its kernel is Linux 5.15.0-56-generic x86_64 .

I tested with v6.2.0-rc7 kernel, on ARM64 system. Also get the same error when using macvtap. Looks this is still an issue to be fixed:

```
sudo ./target/release/cloud-hypervisor \
        --kernel ../linux-cloud-hypervisor/arch/arm64/boot/Image  \
        --disk path=$ROOTFS,iommu=on --disk path=/tmp/ubuntu-cloudinit.img \
        --cmdline "console=hvc0 root=/dev/vda1 rw" \
        --cpus boot=4   \
        --memory size=0,shared=on  \
        --memory-zone id=mem0,size=1G,shared=on,host_numa_node=0 \
        --net "fd=3,mac=c2:67:4f:53:29:cb" 3<>/dev/tap9 \
        --api-socket /tmp/cloud-hypervisor.sock
Error booting VM: VmBoot(DeviceManager(CreateVirtioNet(TapError(IoctlError(2147767506, Os { code: 25, kind: Uncategorized, message: "Inappropriate ioctl for device" })))))
```

**Comment by rbradford** [comment]
This is not something I have been able to reproduce. I propose two ways you can look into this. Either a.) Capture and attach the output from `strace -ff` b.) instrument your host kernel to find the exact place the error is being returned.

**Comment by adamliyi** [comment]
> This is not something I have been able to reproduce. I propose two ways you can look into this. Either a.) Capture and attach the output from `strace -ff` b.) instrument your host kernel to find the exact place the error is being returned.

@rbradford Thanks for replying. I did a little debugging with strace:

if set fd=3 (--net "fd=3,mac=c2:67:4f:53:29:cb" 3<>/dev/tap9), strace shows:
```

dup(3)                                  = 76
dup(29)                                 = 77
dup(76)                                 = 78
fcntl(78, F_GETFL)                      = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(78, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
ioctl(78, TUNGETIFF, 0xffff89e0a560)    = -1 ENOTTY (Inappropriate ioctl for device)

```
if set fd=300 (--net "fd=300,mac=c2:67:4f:53:29:cb" 300<>/dev/tap9)
```
Error booting VM: VmBoot(DeviceManager(CreateVirtioNet(DuplicateTapFd(Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }))))

strace:

dup(300)                                = -1 EBADF (Bad file descriptor)

```

Find a qemu patch: https://lists.gnu.org/archive/html/qemu-devel/2017-10/msg06217.html, it says:

"
There's no obvious guaranteed reliable way to detect that a FD genuinely is a
TAP device, as opposed to a UNIX socket, or pipe, or something else. Checking
the errno from probing vnet hdr flag though, does catch the big common cases.
ie calling TUNGETIFF will return EBADF for an invalid FD, and ENOTTY when FD is
a UNIX socket, or pipe which catches accidental collisions with FDs used for
stdio, or monitor socket.
"
Maybe FD 3 exists, but it is not a TAP device.

**Comment by adamliyi** [comment]
@rbradford , @datong-new , looks I found the root cause. If we start cloud-hypervisor with **sudo**, two processes were created, **3<>/dev/tapX** opens /dev/tapX and assign FD 3 to parent process, not the child process. The child process' FD 3 refers to some other file, not /dev/tapX. 

Run cloud hypervisor as root (no sudo) will work:

```
./target/release/cloud-hypervisor --kernel ../linux-cloud-hypervisor/arch/arm64/boot/Image --disk path=../focal-server-cloudimg-arm64.raw,iommu=on --disk path=/tmp/ubuntu-cloudinit.img --cmdline 'console=hvc0 root=/dev/vda1 rw' --cpus boot=4 --memory size=0,shared=on --memory-zone id=mem0,size=1G,shared=on,host_numa_node=0 --api-socket /tmp/cloud-hypervisor.sock --net fd=3,mac=c2:67:4f:53:29:cb 3<>/dev/tap9

```

Details bellow:
If start CLH with sudo:

```
sudo ./target/release/cloud-hypervisor \
        --kernel ../linux-cloud-hypervisor/arch/arm64/boot/Image  \
        --disk path=$ROOTFS,iommu=on --disk path=/tmp/ubuntu-cloudinit.img \
        --cmdline "console=hvc0 root=/dev/vda1 rw" \
        --cpus boot=4   \
        --memory size=0,shared=on  \
        --memory-zone id=mem0,size=1G,shared=on,host_numa_node=0 \
        --api-socket /tmp/cloud-hypervisor.sock \
        3<>/dev/tap9

```
Two processes were started:
```
root       36386   36371  0 05:30 pts/2    00:00:00 sudo ./target/release/cloud-hypervisor --kernel ../linux-cloud-hypervisor/arch/arm64/boot/Image --disk path=../focal-server-cloudimg-arm64.raw,iommu=on --disk path=/tmp/ubuntu-cloudinit.img --cmdline console=hvc0 root=/dev/vda1 rw --cpus boot=4 --memory size=0,shared=on --memory-zone id=mem0,size=1G,shared=on,host_numa_node=0 --api-socket /tmp/cloud-hypervisor.sock
root       36387   36386 80 05:30 pts/2    00:00:14 ./target/release/cloud-hypervisor --kernel ../linux-cloud-hypervisor/arch/arm64/boot/Image --disk path=../focal-server-cloudimg-arm64.raw,iommu=on --disk path=/tmp/ubuntu-cloudinit.img --cmdline console=hvc0 root=/dev/vda1 rw --cpus boot=4 --memory size=0,shared=on --memory-zone id=mem0,size=1G,shared=on,host_numa_node=0 --api-socket /tmp/cloud-hypervisor.sock

# parent process' fd 3 refers to /dev/tap9
$ sudo ls -l /proc/36386/fd 
lrwx------ 1 root root 64 Feb 24 05:32 3 -> /dev/tap9

# child process' fd 3 refers to other things
sudo ls -l /proc/36387/fd
lrwx------ 1 root root 64 Feb 24 05:38 3 -> 'anon_inode:[eventfd]'
```
