### ISSUE TITLE
Unable to use Firecracker Kernel with cloud-hypervisor due to KernelMissingPvhHeader error

### ISSUE THREAD

**Issue by alexellis** [cloud-hypervisor/cloud-hypervisor#4930]
**Describe the bug**

Unable to use Firecracker Kernel with cloud-hypervisor due to KernelMissingPvhHeader error.

I'm currently using Firecracker to explore providing secure CI for GitHub Actions, however PCI pass-through support is not available and I want to explore GPU support where a GPU is dedicated to a single build at a time.

What would it take to make the finely-tuned Firecracker Kernel config that we have compatible with cloud-hypervisor?

It'd be ideal if we didn't have to create and maintain two sets of Kernels to support both projects, which as I understand from marketing materials share a common core around rust-vmm

**To Reproduce**
Steps to reproduce the behaviour:

Build a Kernel with the configuration from the Firecracker project

https://github.com/firecracker-microvm/firecracker/tree/main/resources/guest_configs

Try to load it with cloud-hypervisor:

```
cloud-hypervisor: 1.384021492s: <vmm> ERROR:/home/runner/.cargo/git/checkouts/vfio-3ea6ca0c73c7450b/bf7c9b9/crates/vfio-ioctls/src/vfio_device.rs:756 -- Could not get region #8 info
Error booting VM: VmBoot(KernelMissingPvhHeader)
```

**Version**

Output of `cloud-hypervisor --version`:

```
cloud-hypervisor v27.0.0
```

(from a binary release)

**Comment by liuw** [comment]
Please build the kernel with `CONFIG_PVH=y`

**Comment by alexellis** [comment]
Thanks for the response.

Would this cause any backwards compatibility issues for Firecracker meaning two kernels are required?

How important is this setting, and does it cause issues for an aarch64 Kernel? `KCFLAGS="-Wa,-mx86-used-note=no"`

**Comment by liuw** [comment]
> Thanks for the response.
> 
> Would this cause any backwards compatibility issues for Firecracker meaning two kernels are required?
> 

No. The same kernel can be used by both.

> How important is this setting, and does it cause issues for an aarch64 Kernel? `KCFLAGS="-Wa,-mx86-used-note=no"`

Not important to ARM64.

**Comment by alexellis** [comment]
I'm also having issues booting a disk image and could use a pointer over at: https://github.com/cloud-hypervisor/cloud-hypervisor/discussions/4931

Thanks for responding.

Perhaps there could be a migration guide for Firecracker users?
