### ISSUE TITLE
qcow: error in caculating the number of refcount table entries in function alloc_refblocks()

### ISSUE THREAD

**Issue by lv-mz** [cloud-hypervisor/cloud-hypervisor#5034]
**Describe the bug**
I want to know how qcow file to process the reference count table ,so i found the function alloc_refblocks().  However, this function makes me confused about the calculation of the number of entries in the reference count table, as follows:

QcowFile::rebuild_refcounts():
```
// Allocate clusters for refblocks.
        // This needs to be done last so that we have the correct refcounts for all other
        // clusters.
        fn alloc_refblocks(
            refcounts: &mut [u16],
            cluster_size: u64,
            refblock_clusters: u64,
            pointers_per_cluster: u64,
        ) -> Result<Vec<u64>> {
            **let refcount_table_entries = div_round_up_u64(refblock_clusters, pointers_per_cluster);**
            let mut ref_table = vec![0; refcount_table_entries as usize];
            ...
```

Here, the number of entries in the reference counter table is obtained by dividing refblock_clusters by pointers_per_cluster，
and refblock_cluster and pointers_per_cluster are the parameters of  the function，which can obtained by :

QcowFile::rebuild_refcounts():
 ```
        let refcount_bits = 1u64 << header.refcount_order;
        let refcount_bytes = div_round_up_u64(refcount_bits, 8);
        **let refcount_block_entries = cluster_size / refcount_bytes;**
        let pointers_per_cluster = cluster_size / size_of::<u64>() as u64;
        let data_clusters = div_round_up_u64(header.size, cluster_size);
        let l2_clusters = div_round_up_u64(data_clusters, pointers_per_cluster);
        let l1_clusters = div_round_up_u64(l2_clusters, pointers_per_cluster);
        let header_clusters = div_round_up_u64(size_of::<QcowHeader>() as u64, cluster_size);
        let max_clusters = data_clusters + l2_clusters + l1_clusters + header_clusters;
        let mut max_valid_cluster_index = max_clusters;
        **let refblock_clusters = div_round_up_u64(max_valid_cluster_index, refcount_block_entries);**
```
According to my understanding, refblock_clusters  here represents the number of clusters occupied by all refcount
blocks ([https://github.com/qemu/qemu/blob/master/docs/interop/qcow2.txt]), which should be the number of entries in refcount table. So  it should not divide by pointers_per_cluster  again，which will result in incorrect reference count length.

If there is any problem, please let me ，thanks.

**Comment by sboeuf** [comment]
Looking into the [spec](https://github.com/qemu/qemu/blob/master/docs/interop/qcow2.txt), I think you missed the fact that reference counting is performed through a 2-level table. The first level is a list of pointers to the second level. The second level is a list of blocks (where each block is the size of one cluster), but each block contains multiple entries. The amount of entries is calculated based on the `refcount_order` (4 for qcow2) which means `refcount_bits` is always 16. So an entry is only 2 bytes, which means one block of 4096 (if cluster_size is 4096) can contain 256 entries.

From my understanding, `refblock_clusters` gives us the number of blocks/clusters that are needed in the second level of the reference table. That's why the maximum amount of clusters is divided by the amount of entries that can be referenced in a refblock. And then we must calculate the amount of clusters that are needed in the first level of the reference table. But because each entry is a pointer, we divide `refblock_clusters` by `pointers_per_cluster`.

**Comment by sboeuf** [comment]
Ah okay I see the question! Well to be honest I think you're right. From my understanding, the function `alloc_refblocks()` returns a reference table that should have `refblock_clusters` entries. Therefore, `refcount_table_entries` should not be divided by `pointers_per_cluster` but instead should simply be `refblock_clusters`.

Here is a quick patch:
```diff
diff --git a/qcow/src/qcow.rs b/qcow/src/qcow.rs                                                                                                                                                                  │
index 40c2e16f..27199b8b 100644                                                                                                                                                                                   │
--- a/qcow/src/qcow.rs                                                                                                                                                                                            │
+++ b/qcow/src/qcow.rs                                                                                                                                                                                            │
@@ -773,10 +773,8 @@ impl QcowFile {                                                                                                                                                                              │
             refcounts: &mut [u16],                                                                                                                                                                               │
             cluster_size: u64,                                                                                                                                                                                   │
             refblock_clusters: u64,                                                                                                                                                                              │
-            pointers_per_cluster: u64,                                                                                                                                                                           │
         ) -> Result<Vec<u64>> {                                                                                                                                                                                  │
-            let refcount_table_entries = div_round_up_u64(refblock_clusters, pointers_per_cluster);                                                                                                              │
-            let mut ref_table = vec![0; refcount_table_entries as usize];                                                                                                                                        │
+            let mut ref_table = vec![0; refblock_clusters as usize];                                                                                                                                             │
             let mut first_free_cluster: u64 = 0;                                                                                                                                                                 │
             for refblock_addr in &mut ref_table {                                                                                                                                                                │
                 loop {                                                                                                                                                                                           │
@@ -901,7 +899,6 @@ impl QcowFile {                                                                                                                                                                               │
             &mut refcounts,                                                                                                                                                                                      │
             cluster_size,                                                                                                                                                                                        │
             refblock_clusters,                                                                                                                                                                                   │
-            pointers_per_cluster,                                                                                                                                                                                │
         )?;                                                                                                                                                                                                      │
                                                                                                                                                                                                                  │
         // Write updated reference counts and point the reftable at them.
```

Is this what you had in mind as a proper fix?

**Comment by lv-mz** [comment]
> Ah okay I see the question! Well to be honest I think you're right. From my understanding, the function `alloc_refblocks()` returns a reference table that should have `refblock_clusters` entries. Therefore, `refcount_table_entries` should not be divided by `pointers_per_cluster` but instead should simply be `refblock_clusters`.
> 
> Here is a quick patch:
> 
> ```diff
> diff --git a/qcow/src/qcow.rs b/qcow/src/qcow.rs                                                                                                                                                                  │
> index 40c2e16f..27199b8b 100644                                                                                                                                                                                   │
> --- a/qcow/src/qcow.rs                                                                                                                                                                                            │
> +++ b/qcow/src/qcow.rs                                                                                                                                                                                            │
> @@ -773,10 +773,8 @@ impl QcowFile {                                                                                                                                                                              │
>              refcounts: &mut [u16],                                                                                                                                                                               │
>              cluster_size: u64,                                                                                                                                                                                   │
>              refblock_clusters: u64,                                                                                                                                                                              │
> -            pointers_per_cluster: u64,                                                                                                                                                                           │
>          ) -> Result<Vec<u64>> {                                                                                                                                                                                  │
> -            let refcount_table_entries = div_round_up_u64(refblock_clusters, pointers_per_cluster);                                                                                                              │
> -            let mut ref_table = vec![0; refcount_table_entries as usize];                                                                                                                                        │
> +            let mut ref_table = vec![0; refblock_clusters as usize];                                                                                                                                             │
>              let mut first_free_cluster: u64 = 0;                                                                                                                                                                 │
>              for refblock_addr in &mut ref_table {                                                                                                                                                                │
>                  loop {                                                                                                                                                                                           │
> @@ -901,7 +899,6 @@ impl QcowFile {                                                                                                                                                                               │
>              &mut refcounts,                                                                                                                                                                                      │
>              cluster_size,                                                                                                                                                                                        │
>              refblock_clusters,                                                                                                                                                                                   │
> -            pointers_per_cluster,                                                                                                                                                                                │
>          )?;                                                                                                                                                                                                      │
>                                                                                                                                                                                                                   │
>          // Write updated reference counts and point the reftable at them.
> ```
> 
> Is this what you had in mind as a proper fix?

@sboeuf， Should we consider the unmber of clusters occupied by the reference table, like what function max_refcount_clusters()  does:

```
let refcount_clusters = max_refcount_clusters(
            header.refcount_order,
            cluster_size as u32,
            (num_clusters + l1_clusters + num_l2_clusters + header_clusters) as u32,
        );
```

```
fn max_refcount_clusters(refcount_order: u32, cluster_size: u32, num_clusters: u32) -> u64 {
    // Use u64 as the product of the u32 inputs can overflow.
    let refcount_bytes = (0x01 << u64::from(refcount_order)) / 8;
    let for_data = div_round_up_u64(
        u64::from(num_clusters) * refcount_bytes,
        u64::from(cluster_size),
    );
    let for_refcounts = div_round_up_u64(for_data * refcount_bytes, u64::from(cluster_size));
    for_data + for_refcounts
}
```

and

```
let refcounts = RefCount::new(
            &mut raw_file,
            header.refcount_table_offset,
            refcount_clusters,
            refcount_block_entries,
            cluster_size,
        )
        .map_err(Error::ReadingRefCounts)?;
```

**Comment by sboeuf** [comment]
> > Ah okay I see the question! Well to be honest I think you're right. From my understanding, the function `alloc_refblocks()` returns a reference table that should have `refblock_clusters` entries. Therefore, `refcount_table_entries` should not be divided by `pointers_per_cluster` but instead should simply be `refblock_clusters`.
> > Here is a quick patch:
> > ```diff
> > diff --git a/qcow/src/qcow.rs b/qcow/src/qcow.rs                                                                                                                                                                  │
> > index 40c2e16f..27199b8b 100644                                                                                                                                                                                   │
> > --- a/qcow/src/qcow.rs                                                                                                                                                                                            │
> > +++ b/qcow/src/qcow.rs                                                                                                                                                                                            │
> > @@ -773,10 +773,8 @@ impl QcowFile {                                                                                                                                                                              │
> >              refcounts: &mut [u16],                                                                                                                                                                               │
> >              cluster_size: u64,                                                                                                                                                                                   │
> >              refblock_clusters: u64,                                                                                                                                                                              │
> > -            pointers_per_cluster: u64,                                                                                                                                                                           │
> >          ) -> Result<Vec<u64>> {                                                                                                                                                                                  │
> > -            let refcount_table_entries = div_round_up_u64(refblock_clusters, pointers_per_cluster);                                                                                                              │
> > -            let mut ref_table = vec![0; refcount_table_entries as usize];                                                                                                                                        │
> > +            let mut ref_table = vec![0; refblock_clusters as usize];                                                                                                                                             │
> >              let mut first_free_cluster: u64 = 0;                                                                                                                                                                 │
> >              for refblock_addr in &mut ref_table {                                                                                                                                                                │
> >                  loop {                                                                                                                                                                                           │
> > @@ -901,7 +899,6 @@ impl QcowFile {                                                                                                                                                                               │
> >              &mut refcounts,                                                                                                                                                                                      │
> >              cluster_size,                                                                                                                                                                                        │
> >              refblock_clusters,                                                                                                                                                                                   │
> > -            pointers_per_cluster,                                                                                                                                                                                │
> >          )?;                                                                                                                                                                                                      │
> >                                                                                                                                                                                                                   │
> >          // Write updated reference counts and point the reftable at them.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this what you had in mind as a proper fix?
> 
> @sboeuf， Should we consider the unmber of clusters occupied by the reference table, like what function max_refcount_clusters() does:
> 
> ```
> let refcount_clusters = max_refcount_clusters(
>             header.refcount_order,
>             cluster_size as u32,
>             (num_clusters + l1_clusters + num_l2_clusters + header_clusters) as u32,
>         );
> ```
> 
> ```
> fn max_refcount_clusters(refcount_order: u32, cluster_size: u32, num_clusters: u32) -> u64 {
>     // Use u64 as the product of the u32 inputs can overflow.
>     let refcount_bytes = (0x01 << u64::from(refcount_order)) / 8;
>     let for_data = div_round_up_u64(
>         u64::from(num_clusters) * refcount_bytes,
>         u64::from(cluster_size),
>     );
>     let for_refcounts = div_round_up_u64(for_data * refcount_bytes, u64::from(cluster_size));
>     for_data + for_refcounts
> }
> ```
> 
> and
> 
> ```
> let refcounts = RefCount::new(
>             &mut raw_file,
>             header.refcount_table_offset,
>             refcount_clusters,
>             refcount_block_entries,
>             cluster_size,
>         )
>         .map_err(Error::ReadingRefCounts)?;
> ```

The best is for you to send a PR if you have something specific in mind. This will be easier for everybody to review.
