### ISSUE TITLE
Replacing clap with something smaller?

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#5065]
Release build of Cloud Hypervisor is around 3.6M right now.

Per https://github.com/rosetta-rs/argparse-rosetta-rs, clap's binary size is ~600k. That's a lot overhead just for parsing some arguments.

Cloud Hypervisor is probably not using any fancy features clap offers. Something simpler can maybe decrease the binary size by quite a bit.

**Comment by likebreath** [comment]
It does sound significant for the size of clap to be over 600k. Do you have a tentative alternative crate in mind to try and estimate the benefits and efforts?

**Comment by liuw** [comment]
> It does sound significant for the size of clap to be over 600k. Do you have a tentative alternative crate in mind to try and estimate the benefits and efforts?

I'm playing with `argh` which is supposed to optimize for size. Experimenting with `performance-metrics` right now since that one only has four options -- not too difficult to convert.

**Comment by liuw** [comment]
I ported `performance-metrics` to `argh`.

```
-rwxr-xr-x 1 wei wei 2.8M Jan  6 18:32 p1
-rwxr-xr-x 1 wei wei 2.5M Jan  6 19:40 p2
```

The binary size goes from 2.8M to 2.5M. That's 0.3M reduction.

Code is here https://github.com/liuw/cloud-hypervisor/tree/argh-perf-metrics. I verify that new binary works with dev_cli.sh.

**Comment by liuw** [comment]
The downside is there isn't a straightforward way of adding `-V` or `--version` options. CrosVM uses a `version` subcommand.

**Comment by rbradford** [comment]
@liuw This looks like a nice idea. I would go ahead and look at `ch-remote` next as that has a slightly different structure with subcommands. Does this change have a positive impact on the number of dependencies / build time?

**Comment by liuw** [comment]
For performance-metrices, the total number of crates built goes down from 78 to 69; time goes down from 34.57s to 31.58s.

**Comment by liuw** [comment]
For ch-remote

```
-rwxr-xr-x 1 wei wei 719K Jan  7 16:18 ch-remote1
-rwxr-xr-x 1 wei wei 475K Jan  7 18:34 ch-remote2
```

Code is at https://github.com/liuw/cloud-hypervisor/tree/argh.

**Comment by sboeuf** [comment]
This sounds like a good idea given this would reduce both binary size and number of dependencies!
That being said, I'm a bit concerned about how much user visible impacts this will have. Moving to this crate must be assessed with care as it could bring a lot of CLI breaking changes.
And second thing to bear in mind is the stability of this crate compared to clap. They didn't reach 1.0.0 yet, which means they might introduce a bunch of breaking changes until they reach it.

**Comment by liuw** [comment]
Some caveats I discovered.

1. `--option=value` is not supported. It needs to be `--option value`. Breaking change.
2. `-vvvvv` needs to be written as `-v -v -v -v -v`. Breaking change.
3. Help strings are not as flexible, since they come from docstring directly.

See the patch to rewrite `ch-remote`. It contains hunks to integration tests to deal with known issues.

As for breaking changes between versions, I am not too concerned. `Clap` introduced some from 3.x to 4.x. It is not immune to that either. `argh` is used by CrosVM, so I expect things not to be in a constantly changing state.

**Comment by rbradford** [comment]
> As for breaking changes between versions, I am not too concerned. `Clap` introduced some from 3.x to 4.x. It is not immune to that either. `argh` is used by CrosVM, so I expect things not to be in a constantly changing state.

I think @sboeuf was concerned about us breaking our compatibility guarantee by changing the command line interface rather than issues with the crate itself (yes moving to clap 4.x required quite a few changes.)

**Comment by rbradford** [comment]
Overall i'm less concerned about us breaking the CLI API than the HTTP API.

**Comment by liuw** [comment]
#5086
