### ISSUE TITLE
Print nesting/hypervisor status & address space size

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#5067]
Twice users have had issues with VMs when running nested under QEMU due to the default behaviour of setting the physical address size to 40 even if the underlying hardware has a smaller address size. This then cause page faulting errors:

See: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/456
and: https://github.com/kata-containers/kata-containers/issues/5997

Perhaps we could provide a warning if:

* Physical address size is detected as 40
* We see the hypervisor bit set
* The CPUID identifiers the hypervisor as KVM (likely QEMU)

**Comment by sboeuf** [comment]
That's a good idea. I'd go with option 3.
Relying on 40 is a bit too specific, and the hypervisor bit means we'll generate this warning for all nested use cases, which might be too much.

**Comment by rbradford** [comment]
> That's a good idea. I'd go with option 3. Relying on 40 is a bit too specific, and the hypervisor bit means we'll generate this warning for all nested use cases, which might be too much.

My intent was to warn on the logical AND of all three.

**Comment by sboeuf** [comment]
I wouldn't rely on 40, but up to you.

**Comment by rbradford** [comment]
> I wouldn't rely on 40, but up to you.

40 is the default QEMU address space size. It is it's default hardcoded nature that that has caused the problems (we by comparison look at the physcial address size provided by the host and proxy it through to the guest.) Now of course the user could indeed be running on a platform with a real 40 bit address space and have told QEMU to pass it through. But the point of this is to provide a guess in the situation that the use hasn't configured the address space in QEMU correctly.

**Comment by rbradford** [comment]
I've been thinking about this and i've decided against a warning like that. Instead i'm thinking about `info!()` level statements printing the hypervisor state (including hypervisor string from cpuid) and address space size. This would still provide interesting details for helping to debug this stuff.
