### ISSUE TITLE
fs: Document values for dax enabled

### ISSUE THREAD

**Issue by jcvenegas** [cloud-hypervisor/cloud-hypervisor#508]
In Kata Configuration the is a configuration there is an config:
```
virtio_fs_cache = "always"
```

This is used by clh implmenetation to enable via cli options, in the case of http api there is no a option but this should is possible to modify virtiofs guest values,  this values could be choose via benchmark and documented or just provide a flag to enable via http api.

**Comment by sboeuf** [comment]
@jcvenegas could you clarify what's the issue is and what would be the right approach to fix it?
I thought that you could translate `virtio_fs_cache = "always"` into `dax=on,cache_size=8G` and `virtio_fs_cache = "none"` into `dax=off`?

**Comment by sboeuf** [comment]
@jcvenegas I think #515 fixed the issue that you described here. Please close the issue if that's the case, otherwise please clarify what's missing.
