### ISSUE TITLE
CI: Windows Server 2022 guest for x86_64

### ISSUE THREAD

**Issue by weltling** [cloud-hypervisor/cloud-hypervisor#5126]
Currently, there's Windows Server 2019 used as the base for the Windows guest on the CI. As there's a Server 2022 already around, it seems to make sense to integrate it into the test workflow. As Windows Server 2019 has yet some years of support ahead of it, it is suggested to integrate a  pass with Windows Server 2022 it addition to 2019.

The question would be, whether it is possible resource wise and how to do it without impacting the CI performance. If resource are available, perhaps adding a stage to Jenkinsfile so it can execute in parallel could be the solution for not impacting the performance. Perhaps there are other options? 

Thanks

**Comment by sboeuf** [comment]
Well I would advise for simplicity here. If you can make Windows Server 2022 to work with Cloud Hypervisor, let's move the CI to this newer version.

**Comment by rbradford** [comment]
Further, since downloading the image is the long pole on the Windows tests I don't think we can afford to download two images. Testing with Windows Server 2022 would be good welcome task for new contributors. The instructions are in docs/windows.md

**Comment by weltling** [comment]
As a possible approach, could be embedding the guest image into the host image something considerable? It seems the Jenkins run takes place on Azure, so such a host image customization could be done. Such a customized host image could also contain more optimizations (like pre-installed dependencies, etc.).

Thanks

**Comment by rbradford** [comment]
> As a possible approach, could be embedding the guest image into the host image something considerable? It seems the Jenkins run takes place on Azure, so such a host image customization could be done. Such a customized host image could also contain more optimizations (like pre-installed dependencies, etc.).

That doesn't work as we'd have to keep the host image up to date. Currently we just track the default version which gets updates. Further, all you're doing is moving the download time to VM creation time. The VM reference image would be stored in the same in-region Azure bucket as the Windows currently is.

**Comment by weltling** [comment]
> That doesn't work as we'd have to keep the host image up to date. Currently we just track the default version which gets updates. Further, all you're doing is moving the download time to VM creation time. The VM reference image would be stored in the same in-region Azure bucket as the Windows currently is.

Downloads within Azure is usually fast, but the location is indeed relevant. Why I mention this is that there are also options to have host images automatically refreshed, like [Image Gallery](https://azure.microsoft.com/de-de/blog/azure-shared-image-gallery-now-generally-available/). Though, that might cause additional costs and is actually an additional effort for the maintenance, but on the other side can help save some time by avoiding fetches.

Perhaps as another idea to have both - one could have both versions after the PR has been merged, but use only the latest for PR.

Thanks
