### ISSUE TITLE
mshv: Fix TPM support in mshv hypervisor

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/cloud-hypervisor#5132]
**Describe the bug**
`test_tpm` fails with the following error when run with mshv hypervisor
```
cloud-hypervisor: 18.157200s: <vcpu0> ERROR:vmm/src/cpu.rs:1019 -- VCPU generated error: VcpuRun(Failed to run vcpu: Unsupported instruction: "movsw [rdi], [rsi]" Movsw Movsw_m16_m16

Caused by:
    0: Unsupported instruction: "movsw [rdi], [rsi]" Movsw Movsw_m16_m16
    1: "movsw [rdi], [rsi]" Movsw Movsw_m16_m16)
```

**To Reproduce**
Steps to reproduce the behaviour:

```
$  ./target/debug/cloud-hypervisor --version
cloud-hypervisor v29.0.0
```
Did you build from source, if so build command line (e.g. features):

Yes. 
```
$ cargo build --features mshv
```

*** Run ***
Comment out https://github.com/cloud-hypervisor/cloud-hypervisor/blob/477332a94a3a44b099491c902d573d594a220a65/tests/integration.rs#L6762 line and run the following:
```
./scripts/dev_cli.sh tests --integration  --hypervisor mshv -- --test-filter test_tpm
```

**Comment by liuw** [comment]
The missing instructions need to be implemented in the emulator.

**Comment by liuw** [comment]
`movs` is already emulated. The work here is to add a new variant.
