### ISSUE TITLE
Bump MSRV v1.62

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#5140]
Cargo clippy v1.68 started to enforce to use #[derive(Default)] for enums, while it is a nightly feature for our MSRV (v1.60). See #5139.

The `derive_default_enum` feature has been stabilized since Rust v1.62 (https://github.com/rust-lang/rust/pull/94457). Shall we bump our MSRV to v1.62?

**Comment by rbradford** [comment]
Yes, this is allowed by our policy:

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/Cargo.toml#L11-L18
