### ISSUE TITLE
Integration test "test_vfio" is constantly failing

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#5190]
The VFIO test has been constantly failing since we re-enabled the bare-metal x86-64 workers yesterday (7ccf58a0192da9baea65da81d559ba149b19d0c4). The first failure was job [137](https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/cloud-hypervisor/branches/main/runs/137/nodes/50/steps/213/log/?start=0) which shows the following error:

```
[2023-02-09T15:47:35.448Z] ==== Start ssh command output (FAILED) ====
[2023-02-09T15:47:35.448Z] 
[2023-02-09T15:47:35.448Z] command="grep -c VFIOTAG /proc/cmdline"
[2023-02-09T15:47:35.448Z] auth="PasswordAuth {
[2023-02-09T15:47:35.448Z]     username: "cloud",
[2023-02-09T15:47:35.448Z]     password: "cloud123",
[2023-02-09T15:47:35.448Z] }"
[2023-02-09T15:47:35.448Z] ip="172.18.0.3"
[2023-02-09T15:47:35.448Z] output=""
[2023-02-09T15:47:35.448Z] error="Connection(Os { code: 113, kind: HostUnreachable, message: "No route to host" })"
```

It looks like an issue related to the network setup on the host machine. I will take a closer look next week.

**Comment by rbradford** [comment]
This would be a good one for @rmstoi to look into.

**Comment by rbradford** [comment]
I tracked this down to just the `test_vfio` test which is the test that nests Cloud Hypervisor inside Cloud Hypervisor. So it's possible that we have an issue with nesting.

**Comment by rbradford** [comment]
On my desktop I tested simple nested CH using direct kernel boot and that works fine using the latest kernel so I don't think we have a general nesting issue but we could still have an issue with the way the test_vfio nesting works.

**Comment by rmstoi** [comment]
@rbradford does vfio test pass on your host? how do you run it? I run

`scripts/dev_cli.sh tests --integration-vfio`

and get an error:
`
mke2fs 1.45.5 (07-Jan-2020)
__populate_fs: Could not allocate block in ext2 filesystem while writing file "vmlinux"
mkfs.ext4: Could not allocate block in ext2 filesystem while populating file system
`

**Comment by likebreath** [comment]
> does vfio test pass on your host? how do you run it? I run
> 
> `scripts/dev_cli.sh tests --integration-vfio`
> 
> and get an error: `mke2fs 1.45.5 (07-Jan-2020) __populate_fs: Could not allocate block in ext2 filesystem while writing file "vmlinux" mkfs.ext4: Could not allocate block in ext2 filesystem while populating file system`

@rmstoi As I mentioned earlier to you, the right way to approach the issue is bisecting and the first step of bisecting is identifying a commit that works. Based on `Jenkinsfile` change history [1], the `VFIO` worker was fully working from commit: https://github.com/cloud-hypervisor/cloud-hypervisor/commit/19661d36afdc6170c3ffb1976faf3d14f3571ef7. Also, I tested this commit and can confirm the `test_vfio` integration test works fine with this commit. 

**Note**: if you are still seeing the `mke2fs` error with this commit, try to verify if this test is "fully" reverted to this commit on your system. To do this, you will need to go back to the `test_vfio` source code and the scripts that run this test (e.g. `dev_cli.sh` and `run_integration_tests_vfio.sh`).

[1] https://github.com/cloud-hypervisor/cloud-hypervisor/commits/main/Jenkinsfile

**Comment by rbradford** [comment]
> @rbradford does vfio test pass on your host? how do you run it? I run
> 
> `scripts/dev_cli.sh tests --integration-vfio`
> 

This requires the specific hardware - don't confused this with the `test_vfio` test which uses Cloud Hypervisor nested within another. `test_vfio` has in the past be run on the Azure workers (so another layer of nesting - but was disabled due to KVM on KVM on HyperV issues.)

**Comment by rmstoi** [comment]
@likebreath Thanks for the pointers, I've been now able to successfully run vfio test by removing workloads and using commit [19661d3](https://github.com/cloud-hypervisor/cloud-hypervisor/commit/19661d36afdc6170c3ffb1976faf3d14f3571ef7)

**Comment by likebreath** [comment]
The integration test that is now failing and under debugging is: `test_vfio`. This test was failing since at least #5207.

I just renamed this issue to clarify.

**Comment by likebreath** [comment]
@rmstoi Can you please update the current status of this issue? Thanks.

**Comment by likebreath** [comment]
@rmstoi Thank you for fixing one of the issues related to `test_vfio`. The test is still failing (due to a different failure fixed with #5527)[1]:
```
[2023-06-20T16:29:19.429Z] ---- vfio::test_vfio stdout ----
[2023-06-20T16:29:19.429Z] mke2fs 1.45.5 (07-Jan-2020)
[2023-06-20T16:29:19.429Z] __populate_fs: Could not allocate block in ext2 filesystem while writing file "vmlinux"
[2023-06-20T16:29:19.429Z] mkfs.ext4: Could not allocate block in ext2 filesystem while populating file system

[2023-06-20T16:29:19.429Z] thread 'vfio::test_vfio' panicked at 'mkfs.ext4 command generated an error', tests/integration.rs:8084:13
```

I remember it is related to #5263 and can be reproduced locally. Of course, you should bisect to confirm.

[1] https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/main/386/pipeline/210

**Comment by rmstoi** [comment]
The mkfs error is due to the fact that kernel size has grown and size 2g given to mkfs.ext4 in the vfio test is insufficient now. The vmlinux becoming larger is caused by commit d5ce855649ceb7926a3982d45deeb94a91d5322e (Update kernel from 5.15.12 to 6.1.6). For example, at commit 496f9322 (a previous commit to d5ce855649ceb7926a3982d45deeb94a91d5322e) vmlinux size is 53M. At commit d5ce855649ceb7926a3982d45deeb94a91d5322e vmlinux size becomes 621M. On the tip of the main branch vmlinux size is 632M.

**Comment by rmstoi** [comment]
Now that kernel size has been reduced, vfio test shows different error,  seems like some connectivity issue.

```
command="grep -c VFIOTAG /proc/cmdline"
ip="172.18.0.3"
output=""
error="Connection(Os { code: 113, kind: HostUnreachable, message: "No route to host" })"
==== End ssh command outout ====
thread 'vfio::test_vfio' panicked at 'called `Result::unwrap()` on an `Err` value: Connection(Os { code: 113, kind: HostUnreachable, message: "No route to host" })', tests/integration.rs:8274:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1113:23
   4: integration::vfio::test_vfio::{{closure}}
             at ./tests/integration.rs:8272:17
   5: std::panicking::try::do_call
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
   6: __rust_try
   7: std::panicking::try
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
   8: std::panic::catch_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
   9: integration::vfio::test_vfio
             at ./tests/integration.rs:8262:17
  10: integration::vfio::test_vfio::{{closure}}
             at ./tests/integration.rs:8156:20
  11: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
==== child killed by signal: 9 ====

[   13.484577] cloud-hypervisor-notify-booted.sh[1565]: /usr/bin/cloud-hypervisor-notify-booted.sh: connect: Connection refused
[   13.485038] cloud-hypervisor-notify-booted.sh[1565]: /usr/bin/cloud-hypervisor-notify-booted.sh: line 4: /dev/tcp/172.18.0.1/8000: Connection refused

```

**Comment by likebreath** [comment]
@rmstoi Now the failure is the same as what's being reported from this issue initially. Make sure that you can reproduce it locally, and then bisect. 

Please share here when you locate the breaking commit. Thanks.
