### ISSUE TITLE
Use a more recent kernel for the default kernel configs

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#521]
`resources/linux-5.0-config` is (as its name implies) 5.0 based while `resources/linux-virtio-fs-virtio-iommu-config` is 5.3-rc1` based.
5.5-rc1 just got released, so we should at least switch to 5.4 for our kernel configs.

**Comment by sboeuf** [comment]
@sameo I agree but our current 5.3 custom kernel branch carries both `virtio-fs` and `virtio-iommu` patches. This means we have to wait for the maintainers to update the series of patches, otherwise we will loose support for these virtio features by moving to 5.4.

**Comment by sameo** [comment]
> @sameo I agree but our current 5.3 custom kernel branch carries both `virtio-fs` and `virtio-iommu` patches. This means we have to wait for the maintainers to update the series of patches, otherwise we will loose support for these virtio features by moving to 5.4.

I agree re the `virtio-iommu-config` one, but I think we should move our 5.0 config to either a 5.4 or ideally a 5.5-rc1, which contains the evged Makefile change.

**Comment by sboeuf** [comment]
Oh yes that's actually a good idea. But what's the plan from a CI perspective, do you want to build 2 different kernels and then choose the right one based on each test?

**Comment by sameo** [comment]
No, I'd definitely prefer to have one kernel for all our CI. Once the virtio-fs and virtio-iommu patches are updated against 5.5-rc1, we could at least have both our configs be based on that version?

**Comment by rbradford** [comment]
I was thinking about this the other day. We should just ship the one config, the one we test, which is currently the 5.5rc1 one.
