### ISSUE TITLE
Offer GO client

### ISSUE THREAD

**Issue by tamalsaha** [cloud-hypervisor/cloud-hypervisor#5218]
I was able to generate go client from the openapi v3 schema. https://github.com/tamalsaha/cloud-hypervisor-go-client

Any chance the upstream project will host it or support Go client?

**Comment by likebreath** [comment]
Hi @tamalsaha Thank you for opening the issue. I think this is something out-of-the-scope of the Cloud Hypervisor project. As you know, it is mostly about how to consume CH APIs from the client side. Kata is the biggest consumer for our openapi spec which maintains its own go-lang client code [1]. You may want to talk with the Kata community if you think it is better to maintain the go-lang client code out of the Kata tree.

Closing the issue now. Please re-open if you want to keep the discussions.

**Comment by iggy** [comment]
@likebreath You made a `[1]` reference, but didn't actually put a link to anything.

**Comment by likebreath** [comment]
@iggy Good catch. Comment updated above with the link. Thanks!
