### ISSUE TITLE
reconsider default or manual text on serial vs console

### ISSUE THREAD

**Issue by fdr** [cloud-hypervisor/cloud-hypervisor#5242]
**Describe the bug**

The documentation seems to be of two minds on virtio-console. @rbradford suggested I open an issue cataloging the issue [from slack.](https://cloud-hypervisor.slack.com/archives/CJJ878PEY/p1677623959299309?thread_ts=1677623523.558799&cid=CJJ878PEY) 

* the examples often use `serial tty`
* `serial` is often necessary when using firmware boot and stock OS images to get boot messages
* ...but serial is seen in the "legacy" device section and is not the default
* ...however, when the host controls the kernel (instead of firmware boot), it has adequate control to make virtio-console work as intended and decrease boot times

@rbradford seemed to think that perhaps the default was mis-selected in the past, being perhaps too optimistic about the rate of adoption of the `console=hvc0` kernel option. I suggested this could be resolved with careful documentation tweaks, since virtio-console could obtain boot messages for the fast-booting/'serverless' mode of using cloud-hypervisor. Now that I understand the matter I am not impeded from doing anything I want to do, but perhaps this difficulty can be smoothed out for others that come later.

**Version**

Applies as of cloud-hypervisor 30.0

**VM configuration**

Use of rust-hypervisor firmware and cloud-hypervisor defaults results in no boot messages, which is problematic for debugging broken cloud-init configuration.

**Comment by likebreath** [comment]
> **Describe the bug**
> 
> The documentation seems to be of two minds on virtio-console. @rbradford suggested I open an issue cataloging the issue [from slack.](https://cloud-hypervisor.slack.com/archives/CJJ878PEY/p1677623959299309?thread_ts=1677623523.558799&cid=CJJ878PEY)
> 
> * the examples often use `serial tty`
> * `serial` is often necessary when using firmware boot and stock OS images to get boot messages
> * ...but serial is seen in the "legacy" device section and is not the default
> * ...however, when the host controls the kernel (instead of firmware boot), it has adequate control to make virtio-console work as intended and decrease boot times

Right, I can see the confusions. My understanding is that the `virtio-console` is set as default mostly for performance reasons with the intention to benefit common users. The documentation is kind of developer orientated (may unintentionally). Like many other developers, `-serial tty` is my default choice for development as it provides early/more kernel logs.

> @rbradford seemed to think that perhaps the default was mis-selected in the past, being perhaps too optimistic about the rate of adoption of the `console=hvc0` kernel option. 

My reservation on changing the default to `--serial tty` is that it may cause unintentional performance hit for existing users. An alternative can be not providing default at all (e.g. making serial/console option required)

> I suggested this could be resolved with careful documentation tweaks, since virtio-console could obtain boot messages for the fast-booting/'serverless' mode of using cloud-hypervisor. Now that I understand the matter I am not impeded from doing anything I want to do, but perhaps this difficulty can be smoothed out for others that come later.

It would be lovely if you can help with improving our documentation (in general).

**Comment by fdr** [comment]
> My reservation on changing the default to --serial tty is that it may cause unintentional performance hit for existing users. An alternative can be not providing default at all (e.g. making serial/console option required)

Fair enough, but consider this: you are probably going to lose *new* users who are not invested in the project and cannot debug cloud-init errors and wonder why they're getting so little output, as this is one of the first things everyone has to do to obtain internet access, ssh, or even a user with a password.

**Comment by rbradford** [comment]
From the discussion it looks like we're sticking with the status quo.
