### ISSUE TITLE
Validate OpenAPI generation is not broken

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#527]
As fixed by https://github.com/cloud-hypervisor/cloud-hypervisor/pull/525, the definition of the OpenAPI can be broken with some subtle changes. It would be interesting to validate the YAML is never broken through our CI.
The easiest way would be to install `docker` in order to run openAPI generator in a docker container.

**Comment by sameo** [comment]
I agree we should be running that check.

```
The easiest way would be to install docker in order to run openAPI generator in a docker container.

```

Which container image does the generator need? Why does it need to be running in a container?

**Comment by sboeuf** [comment]
From the [list](https://github.com/OpenAPITools/openapi-generator#1---installation) of ways to build/install the open API generator, it seems Docker is the easiest because they published a specific image `openapitools/openapi-generator-cli` on Docker Hub.
Thanks to the containerization, we wouldn't need to install a bunch of utilities specific to this binary, which means we wouldn't increase our CI time too much.

I wonder if this should be part of the integration CI, or if we want to run it from Travis. I think Travis could be a good choice since we don't need anything related to virtualization.

**Comment by sameo** [comment]
This is a 133MB docker image, so it should be a quick download. We should try adding this to our travis steps, yes.

**Comment by rbradford** [comment]
Our Travis build is already pretty slow (mostly due to installing cargo audit). Perhaps we could do it in parallel or use the new GitHub actions?

**Comment by sboeuf** [comment]
Ok, so I will add Docker, and as suggested by @rbradford I'll take a look at how we can leverage Github actions to do so.

**Comment by sboeuf** [comment]
As discussed offline with @rbradford, the idea behind Github action is to avoid putting more burden on Travis since it's running pretty slow already.
But an even more efficient solution would be to run the script run by Travis on each Azure VM run by Jenkins. This way, when the build fails because of these checks, we don't run the integration tests for no reason (save some build time). And in case the build runs till the end, because each VM is 48cores, installing `cargo audit` and other things like checking OpenAPI validity should take less time.
