### ISSUE TITLE
aarch64: VFIO fails on 64KiB page size system

### ISSUE THREAD

**Issue by peng6662001** [cloud-hypervisor/cloud-hypervisor#5292]
I refer to the command from [vfio.md](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vfio.md) to start the VM on Ampere Altra server:
```
../cloud-hypervisor --api-socket /tmp/cloud-hypervisor.sock --kernel ../Image --disk path=/tmp/osdisk.img --console off --serial tty --cmdline 'console=hvc0 root=/dev/vda1 rw' --cpus boot=1 --device path=/sys/bus/pci/devices/0003:04:00.0/ --memory size=512M
```
It returns error:
```
cloud-hypervisor: 154.505510ms: <vmm> ERROR:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/ea8f710/crates/vfio-ioctls/src/vfio_device.rs:786 -- Could not get region #8 info
cloud-hypervisor: 294.621808ms: <vmm> ERROR:pci/src/vfio.rs:1527 -- Could not remove the userspace memory region: Failed to remove user memory: Invalid argument (os error 22)
Error booting VM: VmBoot(DeviceManager(VfioMapRegion(CreateUserMemoryRegion(CreateUserMemory(Invalid argument (os error 22))))))
```
But it's good when I check it with qemu:
```
./qemu-system-aarch64 \
        -machine virt,gic-version=3 -cpu host -enable-kvm\
        -bios QEMU_EFI.fd \
        -kernel Image -append "root=/dev/vda1 nokaslr console=ttyAMA0" \
        -drive if=none,file=debian-sid-nocloud-arm64-daily.qcow2,format=qcow2,id=hd \
        -device virtio-blk-pci,drive=hd \
        -nographic \
        -net user,hostfwd=tcp::2222-:22 -net nic \
        -smp 4 \
        -m 3G \
        -device vfio-pci,host=0003:04:00.0


lspci -nn
00:00.0 Host bridge [0600]: Red Hat, Inc. QEMU PCIe Host bridge [1b36:0008]
00:01.0 Ethernet controller [0200]: Red Hat, Inc. Virtio network device [1af4:1000]
00:02.0 SCSI storage controller [0100]: Red Hat, Inc. Virtio block device [1af4:1001]
00:03.0 Non-Volatile memory controller [0108]: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983 [144d:a808]

Samsung Electronics Co Ltd NVMe SSD Controller is the vfio device.
```

version:cloud-hypervisor v30.0-34-g64924d5c-dirty

**Comment by michael2012z** [comment]
I will take a look and be back later.

**Comment by michael2012z** [comment]
Hi, @peng6662001 

Sorry, my test environment for VFIO was broken, it may be a few days before I can bring it back.

I searched my command history for testing VFIO, which happened at least a year ago. All my tests were done with firmware, not direct kernel. I cannot remember whether using UEFI a requirement or not. 

Can you try to boot from EDK2 and see if the problem is still there?

**Comment by peng6662001** [comment]
Hi, @michael2012z 
The ommand to start VM:
```
../cloud-hypervisor --api-socket /tmp/cloud-hypervisor.sock --kernel ../CLOUDHV_EFI.fd --disk path=/tmp/osdisk.img --console off --serial tty --cmdline 'console=hvc0 root=/dev/vda1 rw' --cpus boot=1 --device path=/sys/bus/pci/devices/0003:04:00.0/ --memory size=512M
```

I got the same result:
```
cloud-hypervisor: 158.579279ms: <vmm> ERROR:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/ea8f710/crates/vfio-ioctls/src/vfio_device.rs:786 -- Could not get region #8 info
cloud-hypervisor: 298.834930ms: <vmm> ERROR:pci/src/vfio.rs:1527 -- Could not remove the userspace memory region: Failed to remove user memory: Invalid argument (os error 22)
Error booting VM: VmBoot(DeviceManager(VfioMapRegion(CreateUserMemoryRegion(CreateUserMemory(Invalid argument (os error 22))))))
```
If I remove `--device path=/sys/bus/pci/devices/0003:04:00.0/`,the VM can start.

**Comment by michael2012z** [comment]
Hi, @peng6662001  

@jongwu and I tested different PCI devices (a VGA device and a NIC device) on different machines, the VFIO all worked well. We cannot reproduce the failure you have seen.

But we haven't the same NVMe device you tested.

Can you test some other devices and see if the same problem exist as well?

**Comment by peng6662001** [comment]
@michael2012z 
I try USB device with the command:
```
modprobe -r vfio_pci
modprobe -r vfio_iommu_type1
modprobe vfio_iommu_type1 allow_unsafe_interrupts
modprobe vfio_pci

echo 0004:03:00.0 > /sys/bus/pci/devices/0004\:03\:00.0/driver/unbind
echo 1912 0014 > /sys/bus/pci/drivers/vfio-pci/new_id
ls /dev/vfio/
```
But the result is same:
```
../cloud-hypervisor --api-socket /tmp/cloud-hypervisor.sock --kernel ../CLOUDHV_EFI.fd --disk path=/home/dom/cloud-hypervisor/focal-server-cloudimg-arm64.raw --console off --serial tty --cmdline 'console=hvc0 root=/dev/vda1 rw' --cpus boot=1 --device path=/sys/bus/pci/devices/0004:03:00.0/ --memory size=512M
cloud-hypervisor: 219.112247ms: <vmm> ERROR:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/ea8f710/crates/vfio-ioctls/src/vfio_device.rs:786 -- Could not get region #8 info
cloud-hypervisor: 439.276814ms: <vmm> ERROR:pci/src/vfio.rs:1527 -- Could not remove the userspace memory region: Failed to remove user memory: Invalid argument (os error 22)
Error booting VM: VmBoot(DeviceManager(VfioMapRegion(CreateUserMemoryRegion(CreateUserMemory(Invalid argument (os error 22))))))
```

I can't find NIC device on Ampere Altra,and the server shut down when I tested using a VGA device.

**Comment by michael2012z** [comment]
Can you try capture some log by appending the parameters `--serial file=serial.log --log-file ch.log -v -v -v` ?

And what version is your host kernel and guest kernel? Does it help if you use the guest kernel config https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/resources/linux-config-aarch64 ?

**Comment by adamliyi** [comment]
Hi @michael2012z @peng6662001 , for the error message:
```
cloud-hypervisor: 154.505510ms: <vmm> ERROR:/usr/local/rust/git/checkouts/vfio-3ea6ca0c73c7450b/ea8f710/crates/vfio-ioctls/src/vfio_device.rs:786 -- Could not get region #8 info
```
Region 8 looks to be **VFIO_PCI_VGA_REGION_INDEX** (https://github.com/torvalds/linux/blob/master/include/uapi/linux/vfio.h#L617)

Also qemu checks "vdev->features & VFIO_FEATURE_ENABLE_VGA" before get region info from region 8. (https://github.com/qemu/qemu/blob/master/hw/vfio/pci.c#L2674)

**Comment by adamliyi** [comment]
Hi @michael2012z , @peng6662001
It is interesting the error happens when host OS page size is 64KB. When I change host kernel to 4KB page, this error disappear.

It looks the error happens in kernel kvm function: __kvm_set_memory_region() (https://github.com/torvalds/linux/blob/master/virt/kvm/kvm_main.c#L1939). Kernel checks if guest_phys_addr, memory_size, userspace_addr align to PAGE_SIZE. When "memory_size: 0x2000", it does not align to 64K (0x10000).

But how to fix it?

**Comment by michael2012z** [comment]
@adamliyi Thank you for the investigation. 

Yes, changing the page size to 64KB, now I can reproduce the problem. I will look into the issue and come back with more discussion.

**Comment by michael2012z** [comment]
The failure happened here: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/41880919a0a4eb0e4fe4007337ac886128906c43/pci/src/vfio.rs#L1503

I tried to print the memory region, one of the regions was like:

```
cloud-hypervisor: 1.157683s: <vmm> INFO:pci/src/vfio.rs:1511 -- mem_region = UserMemoryRegion {
    slot: 5,
    guest_phys_addr: 17589030166528,
    memory_size: 57344,
    userspace_addr: 281473232203776,
    flags: 3,
}
```

The region size is `memory_size: 57344` (0xE000, or 56KB). Any region size that is smaller than PAGE_SIZE (64KB in this case) will trigger the error at https://github.com/torvalds/linux/blob/master/virt/kvm/kvm_main.c#L1939 .  In @adamliyi 's test, this size was even smaller (0x2000).

@rbradford @sboeuf Is this an error of in setting/calculating the region size?

**Comment by michael2012z** [comment]
I am wondering if the same failure was seen on X86_64. But I don't have any device on my desktop that can play vfio. And the vfio integration test happened to break (https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5374).

**Comment by adamliyi** [comment]
@michael2012z , Thanks for response. We also found bellow 4 test cases failed when host OS page size is 4KB, but they pass when host OS page size is 64KB:

- test_virtio_fs_multi_segment_hotplug
- test_virtio_fs_hotplug
- test_virtio_fs
- test_virtio_fs_multi_segment

Is it possible we also run ARM64 CI test with 64KB host OS page size?

**Comment by michael2012z** [comment]
> Is it possible we also run ARM64 CI test with 64KB host OS page size?

Not for now. Arm64 CI is deployed on a physical server. And we have only one server in CI.

**Comment by migrantjob** [comment]
We had the same problem in the same environment， we tried to fix this problem , but at the same time it caused the VFIO transparent transmission Mylos network card to appear to hang up。We made the following changes in the pci/src/vfio.rs file in CLH v30:
`+    #[cfg(target_arch = "aarch64")]
+    fn align_64k(address: u64)-> u64 {
+        (address + 0xffff) & 0xffff_ffff_ffff_0000
+    }
+
     fn align_4k(address: u64) -> u64 {
         (address + 0xfff) & 0xffff_ffff_ffff_f000
     }
@@ -1378,13 +1383,28 @@ impl VfioPciDevice {
                     let mut current_offset = 0;
                     for (range_offset, range_size) in inter_ranges {
                         if range_offset > current_offset {
+
+                            let bar_size;
+
+                            if cfg!(target_arch = "aarch64") {
+                                bar_size = Self::align_64k(range_offset - current_offset);
+                            } else {
+                                bar_size = Self::align_4k(range_offset - current_offset);
+                            }
+
                             sparse_areas.push(VfioRegionSparseMmapArea {
                                 offset: current_offset,
-                                size: range_offset - current_offset,
+                                //size: range_offset - current_offset,
+                                size: bar_size,
                             });
                         }
 
-                        current_offset = Self::align_4k(range_offset + range_size);
+                        if cfg!(target_arch = "aarch64") {
+                            current_offset = Self::align_64k(range_offset + range_size);
+                        } else {
+                            current_offset = Self::align_4k(range_offset + range_size);
+                        }
+
                     }
 
                     if region_size > current_offset {`
Our modification can prevent CLH from throwing an error, but it conflicts with the VFIO mechanism and causes a new problem, which occurs when the network card is transparently transmitted:
`[ 0.521503] mlx5_core 0000:00:05.0: Rate limit: 127 rates are supported, range: 0Mbps to 97656Mbps
[ 62.435712] mlx5_core 0000:00:05.0: mlx5_cmd_eq_recover:264:(pid 1): Recovered 1 EQEs on cmd_eq
[ 62.436971] mlx5_core 0000:00:05.0: wait_func_handle_exec_timeout:1051:(pid 1): cmd[0]: CREATE_EQ(0x301) recovered after timeout`

**Comment by peng6662001** [comment]
@jongwu I've updated and rebuilt the code, but the VM still won't boot with vfio,what do I do?
There are some log:
```
cloud-hypervisor: 139.270010ms: <vmm> ERROR:/root/.cargo/git/checkouts/vfio-3ea6ca0c73c7450b/89f8e77/crates/vfio-ioctls/src/vfio_device.rs:786 -- Could not get region #8 info
[   60.386901] nvme nvme0: I/O 24 QID 0 timeout, completion polled                                                                                                                                                 
[  121.827069] nvme nvme0: I/O 25 QID 0 timeout, completion polled                                                                                                                                                 
[  121.827270] nvme nvme0: Shutdown timeout set to 8 seconds                                                                                                                                                       
[  183.267017] nvme nvme0: I/O 26 QID 0 timeout, completion polled                                                                                                                                                 
[  244.706995] nvme nvme0: I/O 27 QID 0 timeout, completion polled                                                                                                                                                 
[  306.146904] nvme nvme0: I/O 24 QID 0 timeout, completion polled                                                                                                                                                 
[  306.147173] nvme nvme0: 1/0/0 default/read/poll queues
[  367.586892] nvme nvme0: I/O 25 QID 0 timeout, completion polled
[  429.026925] nvme nvme0: I/O 26 QID 0 timeout, completion polled
[  490.466978] nvme nvme0: I/O 27 QID 0 timeout, completion polled
```

**Comment by jongwu** [comment]
@peng6662001 -, Yeah, I can reproduce it. nvme shows up but can't work. Let me TAL.

**Comment by jongwu** [comment]
Hi @peng6662001,

I find the root cause that the MMIO map region for BAR0 overlap MSIX-CAP then it won't trap to VMM when access MSIX-CAP in guest.

I send a RFC patch to fix it.  Can you help test https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5469? Thanks.

**Comment by peng6662001** [comment]
@jongwu Please wait a moment.

**Comment by peng6662001** [comment]
@jongwu I have verified the patch,it works fine.

**Comment by peng6662001** [comment]
@jongwu The VM failed to start when I modify the pages to 4K.Please the log
```
cloud-hypervisor: 196.700360ms: <vmm> ERROR:/root/.cargo/git/checkouts/vfio-3ea6ca0c73c7450b/89f8e77/crates/vfio-ioctls/src/vfio_device.rs:786 -- Could not get region #8 info
cloud-hypervisor: 355.501680ms: <vmm> ERROR:pci/src/vfio.rs:1561 -- Could not remove the userspace memory region: Failed to remove user memory: Invalid argument (os error 22)
cloud-hypervisor: 527.232040ms: <vmm> INFO:vmm/src/lib.rs:1786 -- VM exit event

```

**Comment by jongwu** [comment]
Hi @peng6662001,

I update the patch. Can you test again? Thanks!

**Comment by peng6662001** [comment]
@jongwu I retested CONFIG_ARM64_4K_PAGES=y and CONFIG_ARM64_64K_PAGES=y separately and all VMs work fine.

**Comment by migrantjob** [comment]
We had the same problem and we tried to solve it. For performance problems, I suggest that you can learn from the method of MSI-X redirection in QEMU to solve it.https://lists.gnu.org/archive/html/qemu-devel/2018-02/msg01021.html

**Comment by jongwu** [comment]
Thanks @migrantjob -, I'm just looking into QEMU.

**Comment by migrantjob** [comment]
> @jongwu I've updated and rebuilt the code, but the VM still won't boot with vfio,what do I do? There are some log:
> 
> ```
> cloud-hypervisor: 139.270010ms: <vmm> ERROR:/root/.cargo/git/checkouts/vfio-3ea6ca0c73c7450b/89f8e77/crates/vfio-ioctls/src/vfio_device.rs:786 -- Could not get region #8 info
> [   60.386901] nvme nvme0: I/O 24 QID 0 timeout, completion polled                                                                                                                                                 
> [  121.827069] nvme nvme0: I/O 25 QID 0 timeout, completion polled                                                                                                                                                 
> [  121.827270] nvme nvme0: Shutdown timeout set to 8 seconds                                                                                                                                                       
> [  183.267017] nvme nvme0: I/O 26 QID 0 timeout, completion polled                                                                                                                                                 
> [  244.706995] nvme nvme0: I/O 27 QID 0 timeout, completion polled                                                                                                                                                 
> [  306.146904] nvme nvme0: I/O 24 QID 0 timeout, completion polled                                                                                                                                                 
> [  306.147173] nvme nvme0: 1/0/0 default/read/poll queues
> [  367.586892] nvme nvme0: I/O 25 QID 0 timeout, completion polled
> [  429.026925] nvme nvme0: I/O 26 QID 0 timeout, completion polled
> [  490.466978] nvme nvme0: I/O 27 QID 0 timeout, completion polled
> ```

I'm very interested in your question, because we have the same problem, but I don't really understand why you are triggering this issue at NVME, can you show your CLH boot parameters?

**Comment by peng6662001** [comment]
@BlueSeaSailor 
`../cloud-hypervisor --api-socket /tmp/cloud-hypervisor.sock --kernel ../Image --disk path=/tmp/osdisk.img --console off --serial tty --cmdline 'console=hvc0 root=/dev/vda1 rw' --cpus boot=1 --device path=/sys/bus/pci/devices/0003:04:00.0/ --memory size=512M`

**Comment by BlueSeaSailor** [comment]
@jongwu I've updated the patch 626df3f for MSI-X relocation and rebuilt the code, but the VM still won't boot with vfio, what do I do? The VM will hang up at the mlx5_core(The vfio device) init. The CLH CLH boot parameters.
./cloud-hypervisor-v32/target/release/cloud-hypervisor \
	--kernel $LINUX/arch/arm64/boot/Image \
	--console off \
	--serial tty \
	--disk path=./debian-buster-5.4.210.bsk.4-arm64-uefi.raw\
	--cmdline "console=ttyAMA0 root=/dev/vda2 nokaslr " \
    --balloon size=0G,deflate_on_oom=on \
    --cpus boot=4,max=16 \
    --seccomp false \
	--memory size=0,hotplug_method=virtio-mem,shared=on \
    --memory-zone id=mem0,size=4G,hotplug_size=60G,host_numa_node=0,shared=on \
    --numa guest_numa_id=0,memory_zones=mem0 \
    --api-socket /tmp/ch-socket \
    --log-file v32-clh-log -v -v -v \
    --device path=/sys/bus/pci/devices/0000:01:00.2/ \

**Comment by jongwu** [comment]
@BlueSeaSailor -, Thanks for your test.

I make a mistake in the last change that I suppose the msix cap position pins to 0xb0 but it's not true. Maybe it's the reason for your case. Now, I remove this premise by getting its position dynamically and update the PR.  I tested it locally for nvme and e1000e (no mlx for me) and both works fine. 

Can you verify it again? Thanks.

**Comment by BlueSeaSailor** [comment]
> @BlueSeaSailor -, Thanks for your test.
> 
> I make a mistake in the last change that I suppose the msix cap position pins to 0xb0 but it's not true. Maybe it's the reason for your case. Now, I remove this premise by getting its position dynamically and update the PR. I tested it locally for nvme and e1000e (no mlx for me) and both works fine.
> 
> Can you verify it again? Thanks.

Sorry just noticed now.  I tested it again and it works fine. Thank you very much.
