### ISSUE TITLE
Validate behavior between CLI and HTTP API

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#535]
The main goal here is to come up with some proper tests to ensure the behavior we get from a JSON payload (HTTP API) matches the expected behavior from the CLI.

If we look at the current codebase, we need two layers of unit testing:
- Create some tests that would use one JSON payload and one `VmParams` structure, so that after a `serde.Deserialize()` and a `VmConfig::parse()`, we would obtain the same output, which would be an identical `VmConfig` structure.
- Create some test at the CLI layer itself. This means we would need to refactor the `main()` function a bit so that it would call into functions to generate the `clap::App`. Based on these changes, we would perform some tests validating that a certain CLI entry would give us the expected `VmParams`.

But as suggested by @sameo we could also take a slightly different approach that would simplify the writing of these tests. The idea is to move the parsing layer one level up. Instead of having the CLI being generated into a `VmParams`, which then gets translated into a `VmConfig` on one side. And instead of having the JSON payload being translated into a `VmConfig` by serde on the other side. We could have the CLI being translated into a JSON payload, which then would be directly translated into a `VmConfig` thanks to `serde.Deserialize()`.
This way, we would make both the CLI and the HTTP API converge earlier. That means we would have only one layer to test, that is validating a specific CLI entry would be translated into the expected JSON payload. If we can validate that a specific CLI entry matches our expectations regarding the JSON payload, then we validated the behavior between CLI and HTTP API.

**Comment by rbradford** [comment]
I think @sameo's proposal sounds good, it might be a blit slower but not on any critical path. The consolidated testing would be a big win.
