### ISSUE TITLE
Should virtio-device support dirty pages marking?

### ISSUE THREAD

**Issue by fenggeyeyin** [cloud-hypervisor/cloud-hypervisor#5356]
Now in migrating , virtio devices like block have not mark dirty pages in IOtrhead after virtio w access to RAM . This will induce ram migration loss, becouse only VCPU trheads writed pages are migrated.  

Should this be fixed ? How?

**Comment by rbradford** [comment]
vm-memory  crate is used to track dirty pages that the virtio devices write to.
