### ISSUE TITLE
Upgrade to upstream vfio-user crate

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#5365]
According to #5340 ("build: Bump vfio_user from `afbbd57` to `70a73ac`"), the upstream vfio-user crate is no longer working with Cloud Hypervisor, particularly observed as integration test failure of `test_vfio_user`.

**Comment by likebreath** [comment]
Quote from https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5340#issuecomment-1503463503: 
> I suspect this is new to the crate using newer structs to match current vfio-user than the version that the nvme device from the SPDK snapshot uses.

@rbradford  I did a quick look at the diffs (mainly from from https://github.com/rust-vmm/vfio-user/pull/6), it looks like the changes primarily focused on `server` side fixes while CH uses the `client` side implementations. Two questions hope you can help with:

1. IIUC, the only change that affects "client" side is `server: Add missing field to DeviceGetInfo` (https://github.com/rust-vmm/vfio-user/pull/6/commits/db7f653fc3d5f55058ceb1d17f971b11fa119a1e). However, I don't see corresponding changes from the `libvfio-user` side (both spec and implementation) : https://github.com/nutanix/libvfio-user/blob/master/include/vfio-user.h#L104-L110. Can you provide some pointers about why this new field `cap_offset` is required?

2. Similarly, I don't see why we need to change the minor version from `1` to `0`? The libvfio-user implimentation seems to suggest the opposite: https://github.com/nutanix/libvfio-user/blob/master/include/libvfio-user.h#L63-L64.

**Comment by rbradford** [comment]
@likebreath These changes were made to accommodate the latest version of the qemu enabling. However you're right it looks like they are using a divergent version of the spec: 

https://github.com/oracle/qemu/commit/5a4124c85d2a5c76ca855e78a674cffe34d0c049#diff-8f5860f332368dbbc8c0e69bb8f451df6112201a0d731a19dfd7545626f757c6R735

@jlevon @tmakatos Do you have some insight into what's going on here? Is there a better version of QEMU to use for developing/testing the vfio-user crate against?

**Comment by tmakatos** [comment]
AFAIK you should be using the latest version John Johnson sent to qemu-devel, I believe it's this one: https://marc.info/?l=qemu-devel&m=167531672212779&w=2

**Comment by rbradford** [comment]
> AFAIK you should be using the latest version John Johnson sent to qemu-devel, I believe it's this one: https://marc.info/?l=qemu-devel&m=167531672212779&w=2

Thank you @tmakatos. Looks like we were using an older branch. The `vfio-user` crate has now been updated and tracks a protocol version that is compatible with `libvfio-user` crate as well the version embedded in the updated QEMU fork.

**Comment by likebreath** [comment]
This issue was completed via https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5394.
