### ISSUE TITLE
vfio integration test fails in pristine environment

### ISSUE THREAD

**Issue by rmstoi** [cloud-hypervisor/cloud-hypervisor#5375]
**Describe the bug**

vfio test depends on focal server cloudimg hyperfisor-fw files, therefore it cannot run independently. It should download needed depenencies as other integration tests do.

**To Reproduce**
```
$ scripts/dev_cli.sh tests --integration-vfio

cp /root/workloads/focal-server-cloudimg-amd64-custom-20210609-0.raw /root/workloads/vfio
cp: cannot stat '/root/workloads/focal-server-cloudimg-amd64-custom-20210609-0.raw': No such file or directory
cp /root/workloads/hypervisor-fw /root/workloads/vfio
cp: cannot stat '/root/workloads/hypervisor-fw': No such file or directory
+ cp /root/workloads/vmlinux /root/workloads/vfio

thread 'vfio::test_vfio' panicked at 'copying of OS source disk image failed: Os { code: 2, kind: NotFound, message: "No such file or directory" }', test_infra/src/lib.rs:335:14
stack backtrace:

```
**Version**
v31.0-17-g41880919

**Comment by rbradford** [comment]
The image used for the VFIO integration tests has, in the past, been a special custom image with the NVIDIA proprietary drivers installed in. `--integration-vfio` is designed to only be run on a specific machine with specific hardware.
