### ISSUE TITLE
Test failures on Gentoo Linux

### ISSUE THREAD

**Issue by jsmolic** [cloud-hypervisor/cloud-hypervisor#5388]
Hi,
Following up on our D-Bus integration efforts (https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5306) I've made a cloud-hypervisor package for Gentoo and added it to the repository: https://packages.gentoo.org/packages/app-emulation/cloud-hypervisor

However, there are issues with tests, namely nearly all tests are failing with similar error:
```
---- common_parallel::test_multiple_network_interfaces stdout ----
thread

 'common_parallel::test_multiple_network_interfaces' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', test_infra/src/lib.rs:774:43
```
`cargo test --release --frozen` is the command executed to run tests. Since almost all tests are failing, maybe we need to pass additional arguments to cargo or the environment is not set up correctly?

**To Reproduce**
Steps to reproduce the behaviour: `FEATURES="test" emerge cloud-hypervisor` in Gentoo (if needed I can help set up test environment)

**Version**

31.0

`cargo build --release --frozen` is used to compile the source. I'm attaching the full [build.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/11271328/build.log)
Thanks, Jakov

**Comment by rbradford** [comment]
The integration tests make so many assumptions about the environment they are run in the only reasonable way to run them is through the container and the easy way to to that is `scripts/dev_cli.sh`. Are you trying to run outside of this method?

**Comment by rbradford** [comment]
It would be a lot of work - if you look at the `resources/Dockerfile` use can see all the dependencies that are needed. I don't think it's viable to maintain a second environment.

**Comment by jsmolic** [comment]
I had a look at how NixOS does this and it seems that they only run tests for binary targets. Doing the same in Gentoo package works, and since other tests don't appear to be feasible to run under this environment, I'll leave only binary targets tests running. Thanks for your help.
