### ISSUE TITLE
Failed to start VM with console mode TTY

### ISSUE THREAD

**Issue by zhuangel** [cloud-hypervisor/cloud-hypervisor#5389]
**Describe the bug**
Failed to start VM with console mode TTY, panicked at this line:

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/vmm/src/sigwinch_listener.rs#L252

**To Reproduce**
Start VM, then crashed because of read failed, then invoke seccomp in following dump.

**Version**

cloud-hypervisor v31.1

**VM configuration**

curl --unix-socket </path/to/sock> -i   \
     -X PUT 'http://localhost/api/v1/vm.create'  \
     -H 'Accept: application/json'               \
     -H 'Content-Type: application/json'         \
     -d '{
        "console":{"iommu":false,"mode":"Tty"},
        "cpus":{"boot_vcpus":1,"kvm_hyperv":false,"max_vcpus":1},
        "disks":[{"path":"</path/to/disk>"}],
        "iommu":false,
        "memory":{"hotplug_method":"Acpi","hotplug_size":1342177280, "hugepages":false,"mergeable":false,"prefault":false,"shared":false,"size":536870912},
        "payload":{
            "cmdline":"console=hvc0 root=/dev/pmem0p1 rw quiet",
            "kernel":"</path/to/kernel>"
        },
        "pmem":[{"discard_writes":true,"file":"</path/to/pmem>","iommu":false}],
        "rng":{"iommu":false,"src":"/dev/urandom"},
        "serial":{"iommu":false,"mode":"Off"},
        "watchdog":false
    }'

Guest OS version details:
NA

Host OS version details:
linux 5.4.119

**Logs**
Stdout/Stderr:

thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }', vmm/src/device_manager.rs:1949:26

        ==== Possible seccomp violation ====
                                            Try running with `strace -ff` to identify the cause and open an issue: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/new

Strace log:

[pid 213152] write(3, "cloud-hypervisor: ", 18) = 18
[pid 213152] write(3, "25", 2)          = 2
[pid 213152] write(3, ".", 1)           = 1
[pid 213152] write(3, "777534", 6)      = 6
[pid 213152] write(3, "s", 1)           = 1
[pid 213152] write(3, ": <", 3)         = 3
[pid 213152] write(3, "vmm", 3)         = 3
[pid 213152] write(3, "> ", 2)          = 2
[pid 213152] write(3, "INFO", 4)        = 4
[pid 213152] write(3, ":", 1)           = 1
[pid 213152] write(3, "vmm/src/cpu.rs", 14) = 14
[pid 213152] write(3, ":", 1)           = 1
[pid 213152] write(3, "713", 3)         = 3
[pid 213152] write(3, " -- ", 4)        = 4
[pid 213152] write(3, "Creating vCPU: cpu_id = ", 24) = 24
[pid 213152] write(3, "0", 1)           = 1
[pid 213152] write(3, "\n", 1)          = 1
[pid 213152] ioctl(23, KVM_CREATE_VCPU, 0) = 27
[pid 213152] mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_SHARED, 27, 0) = 0x7fb6b219a000
[pid 213152] dup(20)                    = 28
[pid 213152] write(3, "cloud-hypervisor: ", 18) = 18
[pid 213152] write(3, "25", 2)          = 2
[pid 213152] write(3, ".", 1)           = 1
[pid 213152] write(3, "778194", 6)      = 6
[pid 213152] write(3, "s", 1)           = 1
[pid 213152] write(3, ": <", 3)         = 3
[pid 213152] write(3, "vmm", 3)         = 3
[pid 213152] write(3, "> ", 2)          = 2
[pid 213152] write(3, "INFO", 4)        = 4
[pid 213152] write(3, ":", 1)           = 1
[pid 213152] write(3, "vmm/src/pci_segment.rs", 22) = 22
[pid 213152] write(3, ":", 1)           = 1
[pid 213152] write(3, "90", 2)          = 2
[pid 213152] write(3, " -- ", 4)        = 4
[pid 213152] write(3, "Adding PCI segment: id=", 23) = 23
[pid 213152] write(3, "0", 1)           = 1
[pid 213152] write(3, ", PCI MMIO config address: 0x", 29) = 29
[pid 213152] write(3, "e8000000", 8)    = 8
[pid 213152] write(3, ", device area [0x", 17) = 17
[pid 213152] write(3, "150000000", 9)   = 9
[pid 213152] write(3, "-0x", 3)         = 3
[pid 213152] write(3, "3fff4fffffff", 12) = 12
[pid 213152] write(3, "\n", 1)          = 1
[pid 213152] dup(22)                    = 29
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 30
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 31
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 32
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 33
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 34
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 35
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 36
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 37
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 38
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 39
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 40
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 41
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 42
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 43
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 44
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 45
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 46
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 47
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 48
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 49
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 50
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 51
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 52
[pid 213152] eventfd2(0, EFD_NONBLOCK)  = 53
[pid 213152] dup(21)                    = 54
[pid 213152] dup(54)                    = 55
[pid 213152] dup(21)                    = 56
[pid 213152] dup(28)                    = 57
[pid 213152] dup(1)                     = 58
[pid 213152] ioctl(58, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 213152] ioctl(58, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 213152] ioctl(58, SNDCTL_TMR_START or TCSETS, {B38400 -opost -isig -icanon -echo ...}) = 0
[pid 213152] ioctl(58, TCGETS, {B38400 -opost -isig -icanon -echo ...}) = 0
[pid 213152] ioctl(1, TCGETS, {B38400 -opost -isig -icanon -echo ...}) = 0
[pid 213152] fcntl(58, F_DUPFD_CLOEXEC, 3) = 59
[pid 213152] pipe2([60, 61], O_CLOEXEC) = 0
[pid 213152] clone3({flags=CLONE_CLEAR_SIGHAND, exit_signal=0, stack=NULL, stack_size=0}, 88) = -1 EINVAL
[pid 213152] clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLDstrace: Process 213180 attached
, child_tidptr=0x7fb6b15849d0) = 213180
[pid 213180] set_robust_list(0x7fb6b15849e0, 24) = 0
[pid 213152] close(61)                  = 0
[pid 213152] read(60,  <unfinished ...>
[pid 213180] rt_sigaction(SIGHUP, {sa_handler=SIG_DFL, sa_mask=[HUP], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fb6b15bc400}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
......
[pid 213180] syscall_0x1b4(0, 0x1, 0, 0x7fb6b15802fc, 0x7fb6b1d692f0, 0x52) = -1 ENOSYS
[pid 213180] openat(AT_FDCWD, "/proc/self/fd", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 62
[pid 213180] fstat(62, {st_mode=S_IFDIR|0500, st_size=0, ...}) = 0
[pid 213180] getdents64(62, 0x7fb6ac00fcd0 /* d_reclen 19 bytes underflow */ /* 1+ entries */, 32768) = 217
[pid 213180] --- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7fb6b164980b, si_syscall=__NR_getdents64, si_arch=AUDIT_ARCH_X86_64} ---
[pid 213180] +++ killed by SIGSYS +++
[pid 213152] <... read resumed>"", 1)   = 0
[pid 213151] <... futex resumed>)       = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
[pid 213152] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=213180, si_uid=0, si_status=SIGSYS, si_utime=0, si_stime=0} ---
[pid 213151] futex(0x7fb6b15849d0, FUTEX_WAIT, 213152, NULL <unfinished ...>
[pid 213152] close(60)                  = 0
[pid 213152] close(59)                  = 0
[pid 213152] write(2, "thread '", 8)    = 8
[pid 213152] write(2, "vmm", 3)         = 3
[pid 213152] write(2, "' panicked at '", 15) = 15
[pid 213152] write(2, "called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: \"failed to fill whole buffer\" }", 114) = 114
[pid 213152] write(2, "', ", 3)         = 3
[pid 213152] write(2, "vmm/src/device_manager.rs", 25) = 25
[pid 213152] write(2, ":", 1)           = 1
[pid 213152] write(2, "1949", 4)        = 4
[pid 213152] write(2, ":", 1)           = 1
[pid 213152] write(2, "26", 2)          = 2
[pid 213152] write(2, "\n", 1)          = 1
[pid 213152] getcwd("", 512)            = 79
[pid 213152] --- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x7fb6b1672fa2, si_syscall=__NR_getcwd, si_arch=AUDIT_ARCH_X86_64} ---
[pid 213152] write(2, "\n==== Possible seccomp violation ====\nTry running with `strace -ff` to identify the cause and open an issue: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/new\n", 173) = 173
[pid 213152] rt_sigaction(SIGSYS, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fb6b1b60c20}, NULL, 8) = 0
[pid 213152] rt_sigprocmask(SIG_UNBLOCK, [SYS], NULL, 8) = 0
[pid 213152] rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [INT TERM WINCH], 8) = 0
[pid 213152] getpid()                   = 213151
[pid 213152] gettid()                   = 213152
[pid 213152] tgkill(213151, 213152, SIGSYS) = 0
[pid 213152] rt_sigprocmask(SIG_SETMASK, [INT TERM WINCH], NULL, 8) = 0
[pid 213152] --- SIGSYS {si_signo=SIGSYS, si_code=SI_TKILL, si_pid=213151, si_uid=0} ---
[pid 213151] <... futex resumed>)       = ?
[pid 213178] <... read resumed>"", 15167488) = 0
[pid 213154] <... recvfrom resumed> <unfinished ...>) = ?
[pid 213153] <... futex resumed>)       = ?
[pid 213154] +++ killed by SIGSYS +++
[pid 213178] +++ killed by SIGSYS +++
[pid 213153] +++ killed by SIGSYS +++
[pid 213152] +++ killed by SIGSYS +++
+++ killed by SIGSYS +++

Linux kernel output:
NA

**Comment by rbradford** [comment]
This is the code that is triggering the panic:

```
                // SAFETY: FFI call. Trivially safe.
                if unsafe { libc::isatty(libc::STDOUT_FILENO) } == 1 {
                    self.listen_for_sigwinch_on_tty(stdout.try_clone().unwrap())
                        .unwrap();
                }
```

**Comment by zhuangel** [comment]
> Google suggests the error message is for deserialization.
> 
> Is this a regression? I.e. did it work before for you?

Yes, I am using this configuration to do some basic test, it runs well on v30.0.

**Comment by alyssais** [comment]
Sorry about that.  I had tested on older kernels like the one you're running, but I must have neglected to test with seccomp enabled.
