### ISSUE TITLE
Add test to check tsc deadline timer

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#54]
We should add a test to validate that CPUID feature `tsc_deadline_timer` has been enabled from inside our cloud-hypervisor VM. The problem we need to solve is to find how this feature can be enabled on Azure instances because unfortunately the Azure VM does not expose it.

**Comment by rbradford** [comment]
Superseded by #512 as tsc_deadline_timer is always required now.
