### ISSUE TITLE
VM snapshots contain unallocated memory ranges

### ISSUE THREAD

**Issue by gorbak25** [cloud-hypervisor/cloud-hypervisor#5410]
**Describe the bug**
When cloud hypervisor creates an snapshot it writes all memory from the guest even if most of it is not allocated. 
![image](https://user-images.githubusercontent.com/1352848/234566160-93465a47-0076-46fc-8197-42116f3d1f14.png)

**To Reproduce**
1. Start a VM with 100GB of memory with ballooning and free page reporting enabled
2. The resident size of the cloud-hypervisor process should be around 2GB
3. Snapshot the VM
4. Notice that the snapshot takes ages and takes up 100G of space
5. Sparsity the snapshot to verify how much of the space is actually needed
6. Notice that the sparsified snapshot takes up only a few GB's of space
 
**Version**
cloud-hypervisor v28.3.0

**VM configuration**
```
   /usr/bin/cloud-hypervisor-static \
    --api-socket socket_dir/ch.sock \
    --rng src=/dev/urandom \
    --seccomp log \
    --console off \
    --serial tty \
    --net "tap=tapbk0" \
    --kernel vmlinux-6.2-x86_64.bin \
    --cmdline "root=/dev/vda rw rootflags=discard ip=dhcp console=ttyS0 kernel.panic=-1 damon_reclaim.enabled=Y damon_reclaim.min_age=30000000 damon_reclaim.wmarks_low=0 damon_reclaim.wmarks_high=1000 damon_reclaim.wmarks_mid=1000" \
    --memory size=${allocated_memory}K \
    --cpus boot=${allocated_cores},max=${allocated_cores} \
    --disk path=/dev/${BLOCK_DEV_NAME} \
    --balloon free_page_reporting=on,deflate_on_oom=on
```

**Comment by zhuangel** [comment]
@gorbak25 I have proposed an [optimization](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5288) to reduce the size of the snap file, but this optimization requires turning on dirty log at the start of your VM, which will degrade virtual machine performance.

**Comment by gorbak25** [comment]
@zhuangel Why is dirty page logging required? I think this feature may be implemented by calling [mincore](https://man7.org/linux/man-pages/man2/mincore.2.html) on the guest memory and placing holes into the sparse memory dump.

**Comment by zhuangel** [comment]
> @zhuangel Why is dirty page logging required? I think this feature may be implemented by calling [mincore](https://man7.org/linux/man-pages/man2/mincore.2.html) on the guest memory and placing holes into the sparse memory dump.

Great! no impact to the running VM, could also reduce the memory dump file size.

**Comment by likebreath** [comment]
> I think this feature may be implemented by calling [mincore](https://man7.org/linux/man-pages/man2/mincore.2.html) on the guest memory and placing holes into the sparse memory dump.

Sounds interesting. Would you like to send a PR for this feature?

**Comment by zhuangel** [comment]
Hi @gorbak25 @likebreath, I file PR to optimize snap image with mincore, could you please help to review it, thanks.

**Comment by leighst** [comment]
Was this actually completed? Sounds like @zhuangel's change was not accepted?

**Comment by likebreath** [comment]
> Was this actually completed? Sounds like @zhuangel's change was not accepted?

Good catch. It should have been marked as `no planned`, given there was no suitable solutions being proposed.

**Comment by laughinghan** [comment]
Kernel hacking newbie here but wouldn’t proc_pid_maps and possibly the pagemap, not mincore, be appropriate for determining which pages are mapped? Looks like #5464 was dropped bc mincore is about which pages are resident in RAM (ie not swapped out), rather than which are mapped
