### ISSUE TITLE
aarch64: Booting with NVMe vfio-user device fails

### ISSUE THREAD

**Issue by peng6662001** [cloud-hypervisor/cloud-hypervisor#5426]
I reference [example-nvme-device](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vfio-user.md#example-nvme-device) to start VM on Ampere Altra:
```
/root/workloads/cloud-hypervisor-static-aarch64 \
    --memory size=1G,shared=on \
    --disk path=/root/ch_files/osdisk.img \
    --kernel /root/workloads/Image \
    --cmdline "root=/dev/vda1 console=hvc0"
```
The VM returns error immediately.
```
thread 'vcpu0' panicked at 'Failed cloning interrupt's EventFd: Os { code: 24, kind: Uncategorized, message: "No file descriptors available" }', vmm/src/interrupt.rs:82:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
cloud-hypervisor: 316.205732ms: <vcpu0> ERROR:vmm/src/cpu.rs:1039 -- vCPU thread panicked
thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', vmm/src/device_manager.rs:4445:35
Failed to join on VMM thread: Any { .. }
```
please check the full log:
[ch.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/11419465/ch.log)

The qemu runs well with the command in [spdk.md](https://github.com/nutanix/libvfio-user/blob/c08f20634159d977df8f551d07617a8c6b2fea64/docs/spdk.md#start-the-guest)
```
./build/qemu-system-aarch64 \
        -machine virt -cpu host -accel kvm \
        -bios QEMU_EFI.fd \
        -kernel Image -append "root=/dev/vda1 nokaslr console=ttyAMA0" \
        -drive if=none,file=debian-sid-nocloud-arm64-daily.qcow2,format=qcow2,id=hd \
        -device virtio-blk-pci,drive=hd \
        -nographic \
        -net user,hostfwd=tcp::2222-:22 -net nic \
        -device virtio-balloon-pci,id=balloon0,bus=pcie.0 \
        -smp cpus=8 \
        -m 4G \
        -object memory-backend-file,id=mem0,size=4G,mem-path=/dev/hugepages,share=on,prealloc=yes -numa node,memdev=mem0 \
        -device vfio-user-pci,socket=/tmp/nvme-vfio-user/cntrl

On VM
lspci
00:04.0 Non-Volatile memory controller: Nutanix, Inc. Virtual NVMe Controller
```

**Comment by michael2012z** [comment]
Were you using a wrong image "~/images/focal-server-cloudimg-**amd64**.raw" ?

**Comment by peng6662001** [comment]
@michael2012z Sorry,the right command is:
```
/root/workloads/cloud-hypervisor-static-aarch64 \
    --memory size=1G,shared=on \
    --disk path=/root/ch_files/osdisk.img \
    --kernel /root/workloads/Image \
    --cmdline "root=/dev/vda1 console=hvc0" \
    --user-device socket=/tmp/nvme-vfio-user/cntrl
```

**Comment by michael2012z** [comment]
Hi, @peng6662001 Was the test on a 64KiB-Page kernel? How about the test result if you use a 4KiB-Page kernel?

**Comment by peng6662001** [comment]
Hi @michael2012z ,This test was on 4K-pages kernel,spdk inited fail on 64K-pages kernel,so I didn't run the script on 64K-pages.

**Comment by michael2012z** [comment]
@peng6662001 In CI integration test, there is a similar [case](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/tests/integration.rs#L6463) to test vfio-user.

I haven't tested vfio-user with the instructions on the doc page on AArch64 machine. Do you mind doing some more test to identify the root cause:

Was the test OK if you run `./scripts/dev_cli.sh tests --integration -- --test-filter test_vfio_user` ?

In the test, CH boots with firmware (`--kernel CLOUDHV_EFI.fd`), not the direct kernel. Can you try it?

**Comment by peng6662001** [comment]
@michael2012z I have tried `./scripts/dev_cli.sh tests --integration -- --test-filter test_vfio_user`,it passed:
I added some log:
```
Dom,/usr/local/bin/spdk-nvme/rpc.py nvmf_create_subsystem nqn.2019-07.io.spdk:cnode -a -s test                                                                                                                     
Dom,/usr/local/bin/spdk-nvme/rpc.py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode test                                                                                                                           
Dom,/usr/local/bin/spdk-nvme/rpc.py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode -t VFIOUSER -a /tmp/chjr0c2s/test-vfio-user/nvme-vfio-user -s 0
==== Start cloud-hypervisor command-line ====                                                            
                                                                                                         
"target/aarch64-unknown-linux-gnu/release/cloud-hypervisor" "--api-socket" "/tmp/chjr0c2s/cloud-hypervisor.sock" "--cpus" "boot=1" "--memory" "size=512M,shared=on,hugepages=on" "--kernel" "/root/workloads/CLOUDH
V_EFI.fd" "--serial" "tty" "--console" "off" "--disk" "path=/tmp/chjr0c2s/osdisk.img" "--disk" "path=/tmp/chjr0c2s/cloudinit" "--net" "tap=,mac=12:34:56:78:90:01,ip=192.168.1.1,mask=255.255.255.0" "-v"          
                                                                                                                                                                                                                   
==== End cloud-hypervisor command-line ====
Dom,pkill -f nvmf_tgt
test common_parallel::test_vfio_user ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 111 filtered out; finished in 74.22s
```
Why is there no "--user-device socket=/tmp/nvme-vfio-user/cntrl" in the command to start the VM?

I tried another command to test vfio-user with CLOUDHV_EFI.fd:
```
cp /root/workloads/focal-server-cloudimg-arm64-custom-20210929-0.raw /tmp/osdisk.img
/home/dom/cloud-hypervisor/cloud-hypervisor/target/aarch64-unknown-linux-gnu/release/cloud-hypervisor \
    --memory size=1G,shared=on \
    --disk path=/tmp/osdisk.img \
    --disk path=/root/ch_files/cloudinit \
    --kernel /root/workloads/CLOUDHV_EFI.fd     \
    --cmdline "root=/dev/vda1 console=hvc0" \
    --net tap=,mac=12:34:56:78:90:01,ip=192.168.1.1,mask=255.255.255.0 \
    --user-device socket=/tmp/nvme-vfio-user/cntrl -v
```
It returned error:
```
cloud-hypervisor: 9.108448ms: <vmm> INFO:vmm/src/cpu.rs:789 -- Request to create new vCPUs: desired = 1, max = 1, allocated = 0, present = 0
cloud-hypervisor: 9.178288ms: <vmm> INFO:vmm/src/cpu.rs:736 -- Creating vCPU: cpu_id = 0
cloud-hypervisor: 9.313009ms: <vmm> INFO:vmm/src/pci_segment.rs:90 -- Adding PCI segment: id=0, PCI MMIO config address: 0x30000000, device area [0x100000000-0x3ffeffffffff
cloud-hypervisor: 11.189859ms: <vmm> INFO:vmm/src/device_manager.rs:2156 -- Creating virtio-block device: DiskConfig { path: Some("/tmp/osdisk.img"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, rate_limiter_config: None, id: Some("_disk0"), disable_io_uring: false, pci_segment: 0 }
cloud-hypervisor: 11.739182ms: <vmm> INFO:vmm/src/device_manager.rs:2234 -- Using asynchronous RAW disk file (io_uring)
cloud-hypervisor: 11.792302ms: <vmm> INFO:virtio-devices/src/block.rs:560 -- Disk topology: DiskTopology { logical_block_size: 512, physical_block_size: 512, minimum_io_size: 512, optimal_io_size: 0 }
cloud-hypervisor: 11.883303ms: <vmm> INFO:vmm/src/device_manager.rs:2156 -- Creating virtio-block device: DiskConfig { path: Some("/root/ch_files/cloudinit"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, rate_limiter_config: None, id: Some("_disk1"), disable_io_uring: false, pci_segment: 0 }
cloud-hypervisor: 12.168264ms: <vmm> INFO:vmm/src/device_manager.rs:2234 -- Using asynchronous RAW disk file (io_uring)
cloud-hypervisor: 12.229704ms: <vmm> INFO:virtio-devices/src/block.rs:560 -- Disk topology: DiskTopology { logical_block_size: 512, physical_block_size: 512, minimum_io_size: 512, optimal_io_size: 0 }
cloud-hypervisor: 12.314145ms: <vmm> INFO:vmm/src/device_manager.rs:2331 -- Creating virtio-net device: NetConfig { tap: None, ip: 192.168.1.1, mask: 255.255.255.0, mac: MacAddr { bytes: [18, 52, 86, 120, 144, 1] }, host_mac: None, mtu: None, iommu: false, num_queues: 2, queue_size: 256, vhost_user: false, vhost_socket: None, vhost_mode: Client, id: Some("_net2"), fds: None, rate_limiter_config: None, pci_segment: 0, offload_tso: true, offload_ufo: true, offload_csum: true }
cloud-hypervisor: 15.648362ms: <vmm> INFO:vmm/src/device_manager.rs:2504 -- Creating virtio-rng device: RngConfig { src: "/dev/urandom", iommu: false }
cloud-hypervisor: 175.013323ms: <vmm> INFO:vmm/src/lib.rs:1786 -- VM exit event
```
The VM runs well without `--user-device socket=/tmp/nvme-vfio-user/cntrl`

**Comment by michael2012z** [comment]
I tried to follow this page to test vfio-user: [vfio-user.md](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vfio-user.md) 

The first GPIO test failed too, on both X86 and Arm: [example-gpio-device](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vfio-user.md) 

`cloud-hypervisor: 2.790865ms: <vmm> INFO:vmm/src/lib.rs:1786 -- VM exit event`

Not sure if the function has been broken from some time.

**Comment by michael2012z** [comment]
@peng6662001 vfio-user with SPDK should work in this way:
```
# Start vfio-user server
/usr/local/bin/spdk-nvme/nvmf_tgt -i 0 -m 0x1

# Start Cloud Hypervisor
target/aarch64-unknown-linux-gnu/release/cloud-hypervisor --api-socket /tmp/chzpLBh6/cloud-hypervisor.sock --cpus boot=1 --memory size=512M,shared=on --kernel /root/workloads/CLOUDHV_EFI.fd --serial tty --console off --user-device socket=/tmp/chzpLBh6/test-vfio-user/nvme-vfio-user/cntrl,id=vfio_user0 --disk path=/tmp/chzpLBh6/osdisk.img --disk path=/tmp/chzpLBh6/cloudinit --net tap=,mac=12:34:56:78:90:01,ip=192.168.1.1,mask=255.255.255.0 -v
```

Attention:
- `--kernel` must be the firmware. Direct kernel doesn't work.
- `--memory` must has `shared=on`.

**Comment by peng6662001** [comment]
Hi @michael2012z ,the vm still starts fail.
My script for vfio-user:
```
rm ~/images/test-disk.raw
truncate ~/images/test-disk.raw -s 128M
mkfs.ext4  ~/images/test-disk.raw
killall reactor_0
sleep 2
#spdk_dir=./usr/local/bin/spdk-nvme
spdk_dir=./build/bin
#$spdk_dir/nvmf_tgt -i 0 -e 0xFFFF -m 0x1 &
$spdk_dir/nvmf_tgt -i 0 -m 0x1 &
sleep 2
sudo ./scripts/rpc.py nvmf_create_transport -t VFIOUSER
sudo rm -rf /tmp/nvme-vfio-user
sudo mkdir -p /tmp/nvme-vfio-user
sudo ./scripts/rpc.py bdev_aio_create ~/images/test-disk.raw test 512
sudo ./scripts/rpc.py nvmf_create_subsystem nqn.2019-07.io.spdk:cnode -a -s test
sudo ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode test
sudo ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode -t VFIOUSER -a /tmp/nvme-vfio-user -s 0
sudo chown $USER.$USER -R /tmp/nvme-vfio-user
```
My command to start VM:
```
cp /root/workloads/focal-server-cloudimg-arm64-custom-20210929-0.raw /tmp/osdisk.img

/home/dom/cloud-hypervisor/cloud-hypervisor/target/aarch64-unknown-linux-gnu/release/cloud-hypervisor \
        --api-socket /tmp/cloud-hypervisor.sock \
        --cpus boot=1 \
        --memory size=512M,shared=on \
        --kernel /root/workloads/CLOUDHV_EFI.fd \
        --serial tty --console off \
        --user-device socket=/tmp/nvme-vfio-user,id=vfio_user0 \
        --disk path=/root/ch_files/osdisk.img \
        --disk path=/root/ch_files/cloudinit \
        --net tap=,mac=12:34:56:78:90:01,ip=192.168.1.1,mask=255.255.255.0 \
        --log-file log.txt -v
```
I get some logs:
```
cloud-hypervisor: 7.251007ms: <vmm> INFO:vmm/src/pci_segment.rs:90 -- Adding PCI segment: id=0, PCI MMIO config address: 0x30000000, device area [0x100000000-0x3ffeffffffff
cloud-hypervisor: 8.895489ms: <vmm> INFO:vmm/src/device_manager.rs:2156 -- Creating virtio-block device: DiskConfig { path: Some("/root/ch_files/osdisk.img"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, rate_limiter_config: None, id: Some("_disk0"), disable_io_uring: false, pci_segment: 0 }
cloud-hypervisor: 9.245169ms: <vmm> INFO:vmm/src/device_manager.rs:2234 -- Using asynchronous RAW disk file (io_uring)
cloud-hypervisor: 9.286969ms: <vmm> INFO:virtio-devices/src/block.rs:560 -- Disk topology: DiskTopology { logical_block_size: 512, physical_block_size: 512, minimum_io_size: 512, optimal_io_size: 0 }
cloud-hypervisor: 9.355289ms: <vmm> INFO:vmm/src/device_manager.rs:2156 -- Creating virtio-block device: DiskConfig { path: Some("/root/ch_files/cloudinit"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, rate_limiter_config: None, id: Some("_disk1"), disable_io_uring: false, pci_segment: 0 }
cloud-hypervisor: 9.492609ms: <vmm> INFO:vmm/src/device_manager.rs:2234 -- Using asynchronous RAW disk file (io_uring)
cloud-hypervisor: 9.521249ms: <vmm> INFO:virtio-devices/src/block.rs:560 -- Disk topology: DiskTopology { logical_block_size: 512, physical_block_size: 512, minimum_io_size: 512, optimal_io_size: 0 }
cloud-hypervisor: 9.586129ms: <vmm> INFO:vmm/src/device_manager.rs:2331 -- Creating virtio-net device: NetConfig { tap: None, ip: 192.168.1.1, mask: 255.255.255.0, mac: MacAddr { bytes: [18, 52, 86, 120, 144, 1] }, host_mac: None, mtu: None, iommu: false, num_queues: 2, queue_size: 256, vhost_user: false, vhost_socket: None, vhost_mode: Client, id: Some("_net2"), fds: None, rate_limiter_config: None, pci_segment: 0, offload_tso: true, offload_ufo: true, offload_csum: true }
cloud-hypervisor: 11.760531ms: <vmm> INFO:vmm/src/device_manager.rs:2504 -- Creating virtio-rng device: RngConfig { src: "/dev/urandom", iommu: false }
cloud-hypervisor: 12.414412ms: <serial-manager> INFO:vmm/src/serial_manager.rs:303 -- KILL_EVENT received, stopping epoll loop
cloud-hypervisor: 107.249741ms: <vmm> INFO:vmm/src/lib.rs:1786 -- VM exit event
```
If I remove `--user-device socket=/tmp/nvme-vfio-user,id=vfio_user0` from the command,the VM starts fine.

**Comment by michael2012z** [comment]
What version is your SPDK on?

If you are using a recent version, could you try the same one that the CI is using: 6301f8915de32baed10dba1eebed556a6749211a . I think this version should work anyhow.

In AArch64 CI, we built SPDK from that version in the container environment. 

I am not sure if something has been broken since the version.

**Comment by peng6662001** [comment]
@michael2012z I have reset spdk code to 6301f8915de32baed10dba1eebed556a6749211a,it failed to build
```
spdk/libvfio-user/samples/client.c:831:9: error: ‘MD5_Init’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  831 |         MD5_Init(&md5_ctx);
      |         ^~~~~~~~
spdk/libvfio-user/samples/client.c:832:9: error: ‘MD5_Update’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  832 |         MD5_Update(&md5_ctx, buf, fake_guest_data->bar1_size);
      |         ^~~~~~~~~~
```
I don't know how to fix it.

I go into docker of ubuntu20.04,rebuild and run spdk.Then the VM works fine.
I mount /dev/nvme0n1 to ~/temp and do some IO operation,there is no problem.

**Comment by HuangShijie2023** [comment]
> I reference [example-nvme-device](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vfio-user.md#example-nvme-device) to start VM on Ampere Altra:
> 
> ```
> /root/workloads/cloud-hypervisor-static-aarch64 \
>     --memory size=1G,shared=on \
>     --disk path=/root/ch_files/osdisk.img \
>     --kernel /root/workloads/Image \
>     --cmdline "root=/dev/vda1 console=hvc0"
> ```
> 
> The VM returns error immediately.
> 
> ```
> thread 'vcpu0' panicked at 'Failed cloning interrupt's EventFd: Os { code: 24, kind: Uncategorized, message: "No file descriptors available" }', vmm/src/interrupt.rs:82:18
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> cloud-hypervisor: 316.205732ms: <vcpu0> ERROR:vmm/src/cpu.rs:1039 -- vCPU thread panicked
> thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', vmm/src/device_manager.rs:4445:35
> Failed to join on VMM thread: Any { .. }
> ```
> 
> please check the full log: [ch.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/11419465/ch.log)
> 
> The qemu runs well with the command in [spdk.md](https://github.com/nutanix/libvfio-user/blob/c08f20634159d977df8f551d07617a8c6b2fea64/docs/spdk.md#start-the-guest)
> 
> ```
> ./build/qemu-system-aarch64 \
>         -machine virt -cpu host -accel kvm \
>         -bios QEMU_EFI.fd \
>         -kernel Image -append "root=/dev/vda1 nokaslr console=ttyAMA0" \
>         -drive if=none,file=debian-sid-nocloud-arm64-daily.qcow2,format=qcow2,id=hd \
>         -device virtio-blk-pci,drive=hd \
>         -nographic \
>         -net user,hostfwd=tcp::2222-:22 -net nic \
>         -device virtio-balloon-pci,id=balloon0,bus=pcie.0 \
>         -smp cpus=8 \
>         -m 4G \
>         -object memory-backend-file,id=mem0,size=4G,mem-path=/dev/hugepages,share=on,prealloc=yes -numa node,memdev=mem0 \
>         -device vfio-user-pci,socket=/tmp/nvme-vfio-user/cntrl
> 
> On VM
> lspci
> 00:04.0 Non-Volatile memory controller: Nutanix, Inc. Virtual NVMe Controller
> ```

The root cause of the Cloud_Hypervisor failure is : 
    "dup" system call failed,  the number of opened files is over  rlimit(RLIMIT_NOFILE).

**Comment by HuangShijie2023** [comment]
After we changed the RLIMIT_NOFILE by "ulimit -n 2048"
The cloud_hypervisor can works now.

Should we change the Cloud_hypervisor code  to extend the RLIMIT_NOFILE?

**Comment by liuw** [comment]
> After we changed the RLIMIT_NOFILE by "ulimit -n 2048" The cloud_hypervisor can works now.
> 
> Should we change the Cloud_hypervisor code to extend the RLIMIT_NOFILE?

Please investigate why you need so many files in the first place? Perhaps there is a leak somwhere?

**Comment by likebreath** [comment]
> > After we changed the RLIMIT_NOFILE by "ulimit -n 2048" The cloud_hypervisor can works now.
> > Should we change the Cloud_hypervisor code to extend the RLIMIT_NOFILE?
> 
> Please investigate why you need so many files in the first place? Perhaps there is a leak somwhere?

The SPDK-NVMe backend needs 512 FDs (sent from the VMM) for enabling irq. For this reason, we had to sent FDs in multiple batches from our vfio-user implementation (#3445).

**Comment by peng6662001** [comment]
@likebreath 
I found that the number of fds is 167 on VM without spdk,and 683 on VM with spdk.
Can the number of fds be reduced for SPDK-NVME backend?Please show me the code.

**Comment by likebreath** [comment]
> I found that the number of fds is 167 on VM without spdk,and 683 on VM with spdk. 

This looks to be consistent with the 512 FDs required by the SPDK-NVMe backend.

> Can the number of fds be reduced for SPDK-NVME backend?Please show me the code.

This is a question to the SPDK community. Here is the patch that made SPDK-NVMe backend require 512 FDs: https://github.com/spdk/spdk/commit/a9ff16810793db8ebf235966770a50825bbec6a1.

You may want to try the latest SPDK-NVMe backend and see if the required number of FDs are reduced.

**Comment by peng6662001** [comment]
Ref:[Cloud-hypervisor-vfio-user](https://github.com/AmpereComputing/ampere-lts-kernel/wiki/Cloud-hypervisor-vfio-user)
