### ISSUE TITLE
Startup failure problem caused by memory zone splitting for hugepages

### ISSUE THREAD

**Issue by wfly1998** [cloud-hypervisor/cloud-hypervisor#5463]
**Describe the bug**

The function `MemoryManager::create_memory_regions_from_zones` can split a memory zone for ram regions.  But if there is a memory zone using **hugepages** and it is splited into some regions with **misaligned** sizes, the startup will fail with the error:

```
Error booting VM: VmBoot(MemoryManager(SharedFileSetLen(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })))
```

**To Reproduce**

Just run Cloud Hypervisor with the following command:

```bash
cloud-hypervisor \
        --memory size=0 \
        --memory-zone id=zone0,size=512M \
        --memory-zone id=zone1,size=3G,hugepages=on,hugepage_size=1G \
        --kernel hypervisor-fw
```

In this case, the `ram_regions` are:

- `0x 00000000 ~ 0x c0000000 (3G)`
- `0x100000000 ~ 0x120000000 (512M)`

And the memory region (splited) are:

- MemoryZone (`id=zone0,size=512M`)
  - `0x 00000000 ~ 0x 20000000 ( 512M)`
- MemoryZone (`id=zone1,size=3G,hugepages=on,hugepage_size=1G`)
  - `0x 20000000 ~ 0x c0000000 (2560M)` 👈 **HERE**
  - `0x100000000 ~ 0x120000000 (512M)`

Then an error will be raised here:

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/41e5384f1508b878b8fa54c60f309ef1c5b8c5bb/vmm/src/memory_manager.rs#L1272

**Version**

The latest commit on branch `main` with target `x86_64-unknown-linux-musl`:

```bash
$ cargo build --target=x86_64-unknown-linux-musl -j `nproc` --release

$ ./target/x86_64-unknown-linux-musl/release/cloud-hypervisor --version
cloud-hypervisor v32.0-9-g41e5384f
```

**Comment by wfly1998** [comment]
I tried to solve this problem by calling `mmap` for the whole zone directly and calling `kvm_set_user_memory_region` a zone as multiple slots, but it seems that the `GuestRegionMmap` in `vm-memory` crate needs to be refactored 😢

So I want to discuss it and see if there is any idea to solve the problem.

**Comment by rbradford** [comment]
The problem is that the splitting logic doesn't take into consideration that that the region for 1GiB huge pages must be 1GiB aligned. A compromise could be to only every split the first zone and instead always allocate later zones after the 4GiB limit.

**Comment by wfly1998** [comment]
> The problem is that the splitting logic doesn't take into consideration that that the region for 1GiB huge pages must be 1GiB aligned. A compromise could be to only ever split the first zone and instead always allocate later zones after the 4GiB limit.

Sounds feasible, I will try it out and submit a pull request if it works.
