### ISSUE TITLE
functionality to manage a pool of cloud-hypervisor processes

### ISSUE THREAD

**Issue by brkp** [cloud-hypervisor/cloud-hypervisor#5483]
Previously discussed [over at Slack](https://cloud-hypervisor.slack.com/archives/CJJ878PEY/p1685452618581869).

We're interested in contributing and maintaining a feature to Cloud Hypervisor that allows managing a pool of `cloud-hypervisor` processes (runners) through a simple shim layer. We believe this can improve the workflow for people who prefer not to use complex solutions that may be too heavy.

Our idea is to provide it as a separate entry point for the cloud-hypervisor program, which can be enabled with a feature flag at compile time. This way, we won't add unnecessary code for users who don't want to use this feature. To invoke the manager, you would use the following command:

```sh
$ ./cloud-hypervisor manager [manager options]
```

Cloud-Hypervisor Manager, when needed, will spawn itself as a runner in the regular (non-manager) mode and will relay API calls based on a unique identifier assigned to each runner (possibly PID).

Please let us know if you have any feedback, interest, or concerns regarding this proposal.

**Comment by likebreath** [comment]
Thank you for starting this discussion. Very interesting topic.

Why do you want to reuse the same binary target (e.g. "cloud-hypervisor") for this management layer? Isn't it cleaner to have a dedicate binary target that can reuse existing code base as crates?

Like mentioned in the slack discussion chat, have you checked `virtink` and see if it has anything in common you want to leverage? 

/cc @fengye87

**Comment by rbradford** [comment]
I think having this functionality is a fine idea. I'm not convinced that it is a good idea to roll it into the Cloud Hypervisor binary. I think this would be better as a `ch-manager` binary.

1. How will you start VMM processes, forking from the manager process. This is probably quite a challenge to manage in terms of seccomp rules and for keeping track of those processes.
2. For updates and long running VMs you want to be able to attach/detach the VMM processes from the manager process so you can update the two parts separately
3. Development as a separate binary will be easier - there is a good "stateless" equivalent in the form of https://github.com/intel/ccloudvm which doesn't even require the manager process to be running all the time.

**Comment by brkp** [comment]
> Why do you want to reuse the same binary target (e.g. "cloud-hypervisor") for this management layer? Isn't it cleaner to have a dedicate binary target that can reuse existing code base as crates?

The initial idea was that having them be joint would eliminate the issue of managing two binaries but after more consideration, it certainly makes more sense to implement this as an external binary since the code size increase (and the indirect memory consumption increase for each process) is not justified. Furthermore, as you noted, it would lead to a cleaner solution.

> Like mentioned in the slack discussion chat, have you checked virtink and see if it has anything in common you want to leverage?

Yeah, we experimented with `virtink` a little bit, and it's a great project since it integrates with the existing Kubernetes ecosystem! But unfortunately, we don't use Kubernetes internally, so sadly, it's a no-go in our case.

---

> How will you start VMM processes, forking from the manager process. This is probably quite a challenge to manage in terms of seccomp rules and for keeping track of those processes.

I meant that the manager would `fork` and execute itself (`argv[0]`) using something like `execvpe` to start a new runner (in normal? mode). This new runner can then be managed, attached, or detached from the manager process at will since it is now an external process that we can communicate with through its external API. Please let me know if there's something I'm missing or if you meant something different.

> For updates and long running VMs you want to be able to attach/detach the VMM processes from the manager process so you can update the two parts separately

This is a great point, thank you for the insight!

---

With all that said, I think we're going to put this feature on hold for the time being to see if we can manage by trying something internally. Really appreciate the response.

Also, I was wondering if there are any documented readings that detail the design decisions or ideas that shaped Cloud-Hypervisor into what it is today. For instance, aside from the obvious reasons (such as a more straightforward codebase to reason about, simpler seccomp management, etc.), why does CLH only support running a single VMM? Any input on this would be greatly appreciated. Thank you.

**Comment by sdake** [comment]
@brkp regarding cloud-hypervisor only running a single VMM, my take is that is how any proper hypervisor should operate. One virtualized environment per vmm process. There are perhaps 15-20 VMMs I have awareness of. There are many I don't. I can only think of few that don't use a 1:N mapping. These are older designs.

If you had meant, instead, that why does cloud-hypervisor have limited vertical integration, I would consider that to be a matter of project maturity and perhaps even goals. 

Thank you,
-steve
