### ISSUE TITLE
test_ovs_dpdk is very flaky

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#5533]
This is leading to lots of failures on PRs as well as main builds:

https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/cloud-hypervisor/branches/main/runs/380/nodes/45/steps/145/log/?start=0
https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-5531/2/pipeline
https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-5531/1/pipeline

This happens on both aarch64 and x86-64

**Comment by rveerama1** [comment]
As those logs are not available and recently there are fixes/improvements in tests. Also on migration work #5532 test_live_migration_ovs_dpdk was disabled due to vhost crate issue https://github.com/rust-vmm/vhost/issues/217. I am closing this now, please reopen it when it occurs again.
