### ISSUE TITLE
Switch back to the `clap` crate

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#5550]
As discussed in today's community meeting, we decided to switch back to use the `clap` crate considering the `argh` crate is practically not maintained. We will keep the current CLI syntax, and explore potential ways to reduce the size overhead of using `clap` (say disabling unused features).

**Comment by liuw** [comment]
The current version of Clap (4.x) has disallowed multiple occurrences of an argument except for the flags.

Old version supported that https://docs.rs/clap/2.29.0/clap/struct.Arg.html#method.multiple.

That function no longer exists in 4.3.11.

That means we will break command line options again.

**Comment by liuw** [comment]
I had this WIP patch to switch main back to clap https://github.com/cloud-hypervisor/cloud-hypervisor/compare/main...liuw:cloud-hypervisor:clap

I did not get around changing the test cases yet. Posting it here just in case people find it useful.

**Comment by rveerama1** [comment]
> I had this WIP patch to switch main back to clap [main...liuw:cloud-hypervisor:clap](https://github.com/cloud-hypervisor/cloud-hypervisor/compare/main...liuw:cloud-hypervisor:clap)
> 
> I did not get around changing the test cases yet. Posting it here just in case people find it useful.

@liuw I started this work before my vacation and had issues with rebase. Then I continued again after my vacations.

I have noticed following commits which are related to `clap` -> `argh`.

612621bb464a0f3f1a48f8b31944b573779c58b9

a807b91f8647e08037de7132ae6656828bf9977b

b8172408f824fd6e7301a4d837183e755ff0649d

b0a2ce0598334018d0e44bdc544c04a40e044909

a0922930b19cd9160da09b59a3c2f205db7bc30c

d1ec65873ead779d63112515b030d5c82737f626

54e9ed9932a479e7d4548306113a6d98a8d6ba15

111225a2a562a465838219a82611b82393308ae7

fe4905612930ebe72ad6819a0e75ee70005ed6b1

d5558aea2a4205564b00ee8796a8ab47879df337

1ba995d952f8a8fdae7dc37707d54959f18f73a0

9e6301be704f1af662c66052867bc48390dac8a4

I started reverting them despite facing many challenges while reverting. Except  a commit d5558aea2a4205564b00ee8796a8ab47879df337 (reverted except ch-remote dbus changes).

Here is my branch with reverted commits https://github.com/cloud-hypervisor/cloud-hypervisor/compare/main...rveerama1:cloud-hypervisor:issue_5550_lat 

Here is the commit which partially reverted https://github.com/cloud-hypervisor/cloud-hypervisor/compare/main...rveerama1:cloud-hypervisor:issue_5550_lat#diff-63d1396be1ac9ea69f289c785b13472bba3f5d2cdd81082bb22e9c62bfa6b4f7R1012. It requires D-Bus related additions to clap way of handling inputs.

Please take a look and let me know about my approach to continue further.

**Comment by rbradford** [comment]
@rveerama1 I wouldn't do it it by reverting - just port it back.

**Comment by liuw** [comment]
I agree with Rob. Porting those again to clap is better. You can use the code in my WIP branch if it is helpful to you.
