### ISSUE TITLE
VM crashes with PCI VF device attached in VFIO passthrough mode 

### ISSUE THREAD

**Issue by kvmrdy82** [cloud-hypervisor/cloud-hypervisor#5581]
Hi team,

I am seeing a VM crash when trying to access a PCI VF attached to the VM in passthrough mode.

Host Arch: AArch64 (Running linux-4.14.207)
VM Arch: AArch64 (Running linux-4.14.207)

**Cloud Hypervisor Version**
./cloud-hypervisor-static-aarch64 --version
cloud-hypervisor v33.0.0

**Details**

I have luanched a VM with the following command, attaching a network PCI VF 0002:01:00.4.

`./cloud-hypervisor-static-aarch64 --memory size=1024M --kernel ./Image --console off --serial tty  --disk path=./rootfs_image --cmdline "console=ttyAMA0 root=/dev/vda" --device path=/sys/bus/pci/devices/0002\:01\:00.4/`

Inside the VM, loaded our network driver which uses the above PCI VF to create an network interface, **lbk3**. I tried to up the interface as follows:

`ifconfig lbk3 up`

With the above command, the VM crashes with the below error.

`cloud-hypervisor: 190.077599s: <vcpu0> ERROR:vmm/src/cpu.rs:1060 -- VCPU generated error: VcpuRun(Failed to run vcpu: VCPU error Error(38)Caused by:VCPU error Error(38))`

On the host side, I see the following error:
`[346883.550907] kvm [15763]: load/store instruction decoding not implemented`

It is working well with QEMU with the below command.
`./qemu-system-aarch64 -enable-kvm -m 1024 -cpu host -M virt,gic-version=3 -kernel ./Image  -append "console=ttyAMA0 root=/dev/vda " -nographic -hda ./rootfs_image  -device vfio-pci,host=0002:01:00.4`

So I assume something is missing with cloud hypervisor. Can you please help me debug the issue. I am attaching more logs here, please let me know if you need anymore information.

Thanks
Venkat

**Logs**

While launching the VM:

cloud-hypervisor: 123.546142ms: <vmm> **ERROR:/cargo/git/checkouts/vfio-3ea6ca0c73c7450b/89f8e77/crates/vfio-ioctls/src/vfio_device.rs:786 -- Could not get region #8 info**
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.207-10.3.9.0-2 (root@localhost.localdomain) (gcc version 7.3.0) #5 SMP PREEMPT Thu Jun 29 10:14:18 PDT 2023
[    0.000000] Boot CPU: AArch64 Processor [432f0b21]
[    0.000000] Machine model: linux,dummy-virt
[    0.000000] earlycon: pl11 at MMIO 0x0000000009000000 (options '')
[    0.000000] bootconsole [pl11] enabled
[    0.000000] efi: Getting EFI parameters from FDT:
[    0.000000] efi: UEFI not found.

## lspci output of the PCI VF 0002:01:00.4 on host before launching the VM

        Control: I/O- Mem- BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        NUMA node: 0
        Region 2: [enhanced] Memory at 840208000000 (32-bit, non-prefetchable) [disabled] [size=32M]
        Region 4: [enhanced] Memory at 01230000 (32-bit, non-prefetchable) [disabled] [size=64K]
        Capabilities: [70] Express (v2) Endpoint, MSI 00
                DevCap: MaxPayload 128 bytes, PhantFunc 0, Latency L0s <64ns, L1 <1us
                        ExtTag- AttnBtn- AttnInd- PwrInd- RBE+ FLReset+ SlotPowerLimit 0.000W
                DevCtl: Report errors: Correctable- Non-Fatal- Fatal- Unsupported-
                        RlxdOrd- ExtTag- PhantFunc- AuxPwr- NoSnoop- FLReset-
                        MaxPayload 128 bytes, MaxReadReq 128 bytes
                DevSta: CorrErr- UncorrErr- FatalErr- UnsuppReq- AuxPwr- TransPend-
                LnkCap: Port #0, Speed unknown, Width x0, ASPM not supported
                        ClockPM- Surprise- LLActRep- BwNot- ASPMOptComp-
                LnkCtl: ASPM Disabled; RCB 64 bytes Disabled- CommClk-
                        ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
                LnkSta: Speed unknown, Width x0, TrErr- Train- SlotClk- DLActive- BWMgmt- ABWMgmt-
                DevCap2: Completion Timeout: Not Supported, TimeoutDis-, LTR-, OBFF Not Supported
                         AtomicOpsCap: 32bit- 64bit- 128bitCAS-
                DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis-, LTR-, OBFF Disabled
                         AtomicOpsCtl: ReqEn-
                LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete-, EqualizationPhase1-
                         EqualizationPhase2-, EqualizationPhase3-, LinkEqualizationRequest-
        Capabilities: [b0] MSI-X: Enable- Count=202 Masked-
                Vector table: BAR=2 offset=00080000
                PBA: BAR=2 offset=000f0000
        Capabilities: [100 v1] Vendor Specific Information: ID=00a2 Rev=2 Len=040 <?>
        Capabilities: [140 v1] Advanced Error Reporting
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                CESta:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr-
                CEMsk:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr-
                AERCap: First Error Pointer: 00, ECRCGenCap- ECRCGenEn- ECRCChkCap- ECRCChkEn-
                        MultHdrRecCap- MultHdrRecEn- TLPPfxPres- HdrLogCap-
                HeaderLog: 00000000 00000000 00000000 00000000
        Capabilities: [170 v1] Alternative Routing-ID Interpretation (ARI)
                ARICap: MFVC- ACS-, Next Function: 0
                ARICtl: MFVC- ACS-, Function Group: 0
        Kernel driver in use: vfio-pci

## **lspci** output inside the VM:

        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0
        Region 2: Memory at 20000000 (64-bit, non-prefetchable)
        Region 4: Memory at <ignored> (64-bit, non-prefetchable) [size=32M]
        Expansion ROM at <unassigned> [disabled] [size=64K]
        Capabilities: [70] Express (v2) Endpoint, MSI 00
                DevCap: MaxPayload 128 bytes, PhantFunc 0, Latency L0s <64ns, L1 <1us
                        ExtTag- AttnBtn- AttnInd- PwrInd- RBE+ FLReset+ SlotPowerLimit 0.000W
                DevCtl: Report errors: Correctable- Non-Fatal- Fatal- Unsupported-
                        RlxdOrd- ExtTag- PhantFunc- AuxPwr- NoSnoop- FLReset-
                        MaxPayload 128 bytes, MaxReadReq 128 bytes
                DevSta: CorrErr- UncorrErr- FatalErr- UnsuppReq- AuxPwr- TransPend-
                LnkCap: Port #0, Speed unknown, Width x0, ASPM not supported
                        ClockPM- Surprise- LLActRep- BwNot- ASPMOptComp-
                LnkCtl: ASPM Disabled; RCB 64 bytes Disabled- CommClk-
                        ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
                LnkSta: Speed unknown, Width x0, TrErr- Train- SlotClk- DLActive- BWMgmt- ABWMgmt-
                DevCap2: Completion Timeout: Not Supported, TimeoutDis-, LTR-, OBFF Not Supported
                DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis-, LTR-, OBFF Disabled
                         AtomicOpsCtl: ReqEn-
                LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete-, EqualizationPhase1-
                         EqualizationPhase2-, EqualizationPhase3-, LinkEqualizationRequest-
        Capabilities: [b0] MSI-X: Enable+ Count=202 Masked-
                Vector table: BAR=2 offset=00080000
                PBA: BAR=2 offset=000f0000
        Capabilities: [100 v1] Vendor Specific Information: ID=00a2 Rev=2 Len=040 <?>
        Capabilities: [140 v1] Advanced Error Reporting
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                CESta:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr-
                CEMsk:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr-
                AERCap: First Error Pointer: 00, ECRCGenCap- ECRCGenEn- ECRCChkCap- ECRCChkEn-
                        MultHdrRecCap- MultHdrRecEn- TLPPfxPres- HdrLogCap-
                HeaderLog: 00000000 00000000 00000000 00000000
        Capabilities: [170 v1] Alternative Routing-ID Interpretation (ARI)
                ARICap: MFVC- ACS-, Next Function: 0
                ARICtl: MFVC- ACS-, Function Group: 0

**Comment by michael2012z** [comment]
The `Could not get region` error may not be the critical error for the problem. It was discussed in a previous issue:
https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5292#issuecomment-1504878298

**Comment by kvmrdy82** [comment]
'Could not get region' might not be a problem as per the comments in #5292. I think the error is confusing, it could have been warning or info message instead.

**Comment by rbradford** [comment]
Your host/guest kernel is extremely old at 4.14.  I expect your problem comes from this message: `" [346883.550907] kvm [15763]: load/store instruction decoding not implemented"` which also matches the -ENOSYS returned to Cloud Hypervisor

From 4.14 code:

```
	/*
	 * Prepare MMIO operation. First decode the syndrome data we get
	 * from the CPU. Then try if some in-kernel emulation feels
	 * responsible, otherwise let user space do its magic.
	 */
	if (kvm_vcpu_dabt_isvalid(vcpu)) {
		ret = decode_hsr(vcpu, &is_write, &len);
		if (ret)
			return ret;
	} else {
		kvm_err("load/store instruction decoding not implemented\n");
		return -ENOSYS;
	}
```

I know the README.md says the minimum supported version is 4.11 (this was probably appropriate for x86-64 at some point) but this is obviously not appropriate for aarch64.

**Comment by kvmrdy82** [comment]
Ok, I will try with 5.15 kernel. Thank you.

**Comment by kvmrdy82** [comment]
It works with 5.15 kernel. Thank you for your help.
