### ISSUE TITLE
Getting started documentation is missing a `--disk` flag

### ISSUE THREAD

**Issue by Undef-a** [cloud-hypervisor/cloud-hypervisor#5585]
**Describe the bug**
The getting started documentation contains the following command repeated throughout:
```
./cloud-hypervisor \
	--kernel ./hypervisor-fw \
	--disk path=focal-server-cloudimg-amd64.raw path=/tmp/ubuntu-cloudinit.img \
	--cpus boot=4 \
	--memory size=1024M \
	--net "tap=,mac=,ip=,mask="
```
However the command fails because `--disk` only accepts one disk. As a result the new user gets the following output.
```
Unrecognized argument: path=/tmp/ubuntu-cloudinit.img
```
Simply adding a `--disk` before the second `path=` fixes the issue.

**To Reproduce**
Steps to reproduce the behaviour:
Follow the "Getting Started" instructions.

**Version**
v33.0

**Comment by likebreath** [comment]
Thank you for reporting the issue. Do you mean the "get-started" section of the "Quick Start" blog on our website [1]? I can see it is not updated with the latest CLI interfaces.

[1] https://www.cloudhypervisor.org/docs/prologue/quick-start/
