### ISSUE TITLE
Support AMD Sev-Snp on MSHV

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/cloud-hypervisor#5639]
This issue is to track adding Sev-Snp support on MSHV. There will be on going PRs.

- [ ] SNP feature guard
- [ ] IGVM parser and IGVM feature guard
- [ ] Support IGVM file as a payload
- [ ] Make memory/arch module to support IGVM file
- [ ] Change IO path to support Sev-SNP
- [ ] Handle GHCB Exits in hypervisor crates

**Comment by russell-islam** [comment]
https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5628

**Comment by likebreath** [comment]
Thanks for opening the issue. It would be good to have a list of outstanding tasks, and track their progress here.

**Comment by jinankjain** [comment]
I think there are duplicates now: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4761. Should we close this one?

**Comment by jinankjain** [comment]
@likebreath could you please add me to the CLH org? So, it would be easier for @russell-islam to assign issues to me directly?

**Comment by likebreath** [comment]
> @likebreath could you please add me to the CLH org? So, it would be easier for @russell-islam to assign issues to me directly?

@jinankjain I am not a admin of the Cloud Hypervisor organization. @rbradford or @liuw  Can you please help here? Thanks.

**Comment by rbradford** [comment]
> > @likebreath could you please add me to the CLH org? So, it would be easier for @russell-islam to assign issues to me directly?
> 
> @jinankjain I am not a admin of the Cloud Hypervisor organization. @rbradford or @liuw Can you please help here? Thanks.

I did this yesterday!
