### ISSUE TITLE
Significant multiple vCPU boot time performance regression

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#5646]
See boot_time_16_vcpus_ms graph here: https://www.cloudhypervisor.org/metrics/

Booting with 16 vCPUs goes from 255ms to 553ms (i.e it doubles).

The change that triggered this is:

```
commit 57fdaa3a39fc9536ffd2665c470c33476dbdd931
Author: Jianyong Wu <jianyong.wu@arm.com>
Date:   Thu Jun 15 11:41:59 2023 +0800

    arch: x86_64: Populate the APIC Id
    
    Program the APIC ID (CPUID leaf 0x1 EBX) with the CPU id. This resolves
    an issue where the EDKII firmware expects the APIC ID to vary per-CPU.
    
    Fixes: #5475
    Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
```

**Comment by rbradford** [comment]
CC @jongwu

**Comment by jongwu** [comment]
Hi @rbradford -,

I test it using metrics script in CH.
With this patch:

> Test 'boot_time_ms' running .. (control: test_timeout = 2s, test_iterations = 10, overrides: )
> Test 'boot_time_ms' .. ok: mean = 100.61170000000001, std_dev = 3.4464616652445135
> Test 'boot_time_pmem_ms' running .. (control: test_timeout = 2s, test_iterations = 10, overrides: )
> Test 'boot_time_pmem_ms' .. ok: mean = 106.82939999999999, std_dev = 2.5399075258757002
> Test 'boot_time_16_vcpus_ms' running .. (control: test_timeout = 2s, test_iterations = 10, overrides: )
> Test 'boot_time_16_vcpus_ms' .. ok: mean = 231.49779999999996, std_dev = 8.852088790788313
> Test 'boot_time_16_vcpus_pmem_ms' running .. (control: test_timeout = 2s, test_iterations = 10, overrides: )
> Test 'boot_time_16_vcpus_pmem_ms' .. ok: mean = 243.0571, std_dev = 18.59628753515067

Compared with removing this patch:

> Test 'boot_time_ms' running .. (control: test_timeout = 2s, test_iterations = 10, overrides: )
> Test 'boot_time_ms' .. ok: mean = 103.05059999999999, std_dev = 4.147512006010349
> Test 'boot_time_pmem_ms' running .. (control: test_timeout = 2s, test_iterations = 10, overrides: )
> Test 'boot_time_pmem_ms' .. ok: mean = 105.5999, std_dev = 2.583060024467104
> Test 'boot_time_16_vcpus_ms' running .. (control: test_timeout = 2s, test_iterations = 10, overrides: )
> Test 'boot_time_16_vcpus_ms' .. ok: mean = 228.6917, std_dev = 8.943063211785988
> Test 'boot_time_16_vcpus_pmem_ms' running .. (control: test_timeout = 2s, test_iterations = 10, overrides: )
> Test 'boot_time_16_vcpus_pmem_ms' .. ok: mean = 256.24710000000005, std_dev = 12.865777803537581

From the test, it seems that there is no significant performance regression for boot time.

**Comment by rbradford** [comment]
Thanks @jongwu - it's possible this is nested (or even nested on Azure) specific - the jump is very obvious in the metrics UI.

**Comment by jongwu** [comment]
Hi @rbradford -, do you mean that the test is in a nested virtualization environment? Does "cpuid" instruction takes more time in nested virtualization?

**Comment by rbradford** [comment]
> Hi @rbradford -, do you mean that the test is in a nested virtualization environment? Does "cpuid" instruction takes more time in nested virtualization?

Yes, our testing runs inside Azure VMs. Yes cpuid will take time as it is will trap and need to be emulated.

**Comment by likebreath** [comment]
> (or even nested on Azure) specific -

Actually, our metrics tests are running on a baremetal machine. So the performance regression is not related to nested virtualization. 

I just manually ran the test again on the metrics CI machine, and compared main branch d38e951234e4574b99df5aa45afc006624f636ea and main branch d38e951234e4574b99df5aa45afc006624f636ea + revert 57fdaa3a39fc9536ffd2665c470c33476dbdd931. I see the same performance regression on 16 vCPUs as reported in this post.

@jongwu Would you please do a similar experiments and share more about your testing environment? Say `lscpu` and `host kernel` information from your host machine. Thank you.

**Comment by rbradford** [comment]
> > (or even nested on Azure) specific -
> 
> Actually, our metrics tests are running on a baremetal machine. So the performance regression is not related to nested virtualization.

My mistake - I forgot that metrics ran bare metal. My general point still holds - calling CPUID excessively will cause performance regressions since it is a serializing instruction (i.e. it will ensure all instructions before the cpuid appear to execute before the cpuid)

> CPUID can be executed at any privilege level to serialize instruction execution. Serializing instruction execution guarantees that any modifications to flags, registers, and memory for previous instructions are completed before the next instruction is fetched and executed.

https://c9x.me/x86/html/file_module_x86_id_45.html

**Comment by jongwu** [comment]
Hi @likebreath -, I tested on an old x86_64 desktop. Machine info from lscpu:

> 
> Architecture:                    x86_64
> CPU op-mode(s):                  32-bit, 64-bit
> Byte Order:                      Little Endian
> Address sizes:                   39 bits physical, 48 bits virtual
> CPU(s):                          8
> On-line CPU(s) list:             0-7
> Thread(s) per core:              2
> Core(s) per socket:              4
> Socket(s):                       1
> NUMA node(s):                    1
> Vendor ID:                       GenuineIntel
> CPU family:                      6
> Model:                           60
> Model name:                      Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
> Stepping:                        3
> CPU MHz:                         1028.931
> CPU max MHz:                     4000.0000
> CPU min MHz:                     800.0000
> BogoMIPS:                        7182.76
> Virtualization:                  VT-x
> L1d cache:                       128 KiB
> L1i cache:                       128 KiB
> L2 cache:                        1 MiB
> L3 cache:                        8 MiB
> NUMA node0 CPU(s):               0-7
> Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
> Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
> Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
> Vulnerability Meltdown:          Mitigation; PTI
> Vulnerability Mmio stale data:   Unknown: No mitigations
> Vulnerability Retbleed:          Not affected
> Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
> Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
> Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS No
>                                  t affected
> Vulnerability Srbds:             Mitigation; Microcode
> Vulnerability Tsx async abort:   Not affected
> Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr
>                                   sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good n
>                                  opl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ss
>                                  se3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave a
>                                  vx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnm
>                                  i flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dthe
>                                  rm ida arat pln pts md_clear flush_l1d
