### ISSUE TITLE
Repo Release tag does not match actual released version

### ISSUE THREAD

**Issue by MyStarInYourSky** [cloud-hypervisor/cloud-hypervisor#5663]
**Describe the bug**
When viewing releases in this repo, the releases are named `<majorversion>.<minorversion>`, however when checking the version in the binary itself with the `-V` flag, the version is reported as `<majorverison>.<minorversion>.<patchversion>`

This makes it quite annoying when doing automated installs using configuration management such as Ansible as you cannot compare versions directly.

**To Reproduce**
Steps to reproduce the behaviour:
1) View release in the repo.
2) Compare release version with version reported by binary

**Version**
v33.0

Output of `cloud-hypervisor --version`: `cloud-hypervisor v33.0.0`

Did you build from source, if so build command line (e.g. features): Binaries provided were used.

**VM configuration**

What command line did you run (or JSON config data): `n/a`

Guest OS version details: `n/a`

Host OS version details: `n/a`

**Logs**

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:

Linux kernel output:

**Comment by likebreath** [comment]
Thank you for reporting the issue. The main problem is that Rust cargo file requires to use 3-digits versions, while we only want 2-digits versions and the last digit is not being used (e.g. always 0) [see #2561].  Is there anyway that you can workaround it with Ansible for this situation? Sorry about the inconvenience.

**Comment by rbradford** [comment]
Changing this might regress other users who have an adaptation in place to handle mapping 3 digits to to two. So we won't change this now.
