### ISSUE TITLE
Custom image NVIDIA problem

### ISSUE THREAD

**Issue by oksanassss** [cloud-hypervisor/cloud-hypervisor#5684]
Hi ,  tried use gpu-nvida  on  custom image.  I followed the steps in the document(https://github.com/cloud-hypervisor/cloud-hypervisor/blob/2571e59438597f53aa4993cd70d6462fe1364ba7/docs/custom-image.md?plain=1#L213).

But I have a error.  
Version : cloud-hypervisor v34.0-1-gca155a79
my error : 

```
cloud@cloud:~$ nvidia-detector 
None
cloud@cloud:~$ nvidia-smi 
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

How can ı use nvidia on my image.

**Comment by rbradford** [comment]
Use `rust-hypervisor-firmware` or `OVMF` and boot into a full image without using direct kernel boot. You can then install the nvidia tools and proprietary drivers. Those instructions are for developers to reference on how to create custom images.
