### ISSUE TITLE
virtio-vsock doesn't work with v6.3+ guest

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#5691]
I noticed that the Virtio-VSOCK feature stops working if a v6.3+ guest kernel is booted with the v33.0 CH.

This is due to the kernel commit [71dc9ec9ac7d](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=71dc9ec9ac7d3eee785cdc986c3daeb821381e20) ("virtio/vsock: replace virtio_vsock_pkt with sk_buff"), and CH's virtio-vsock backend crate has none support for parsing the new struct sk_buff. In that case, the endless WARN log "WARN --- <vsock> virtio-devices/src/vsock/device.rs:146 -- vsock: RX queue error: BufDescMissing" is easily triggered with documented steps in the [docs/vsock.md](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vsock.md). 

I'd like to know your thoughts on addressing this bug, an important issue here is how to get the CH backend to maintain compatibility in parsing different formats for guests with unspecified kernel versions.

_Originally posted by @lkml-likexu in https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3822#issuecomment-1683300234_

**Comment by stefano-garzarella** [comment]
it looks like the same issue we fixed in rust-vmm's vsock crate: https://github.com/rust-vmm/vm-virtio/issues/204

**Comment by skaegi** [comment]
FWIW this kernel change has now been back-ported to 6.1.63 -- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.63&id=baddcc2c71572968cdaeee1c4ab3dc0ad90fa765 -- and so causing problems when older version of CLH (in our case v33) are used.
