### ISSUE TITLE
Mutiple-thread support issue for  vhost-user backend

### ISSUE THREAD

**Issue by yangzhon** [cloud-hypervisor/cloud-hypervisor#571]
@sboeuf @rbradford @bjzhjing 

When we enable multiple-thread for multiple-queue in the vhost device and backend, we found we need to change vhost_user_backend crate, which will impact among blk, net and fs backend. What's more, those three virtio devices have different virt-queue definitions. So, if we want to enable MQ in vhost user device and backend, we had better look for a better solution. thanks.

**Comment by sboeuf** [comment]
@yangzhon I'm sure there are plenty of improvements to bring to `vhost_user_backend` crate, and since you identified some blockers, would you mind sending a PR to fix the crate?

**Comment by bjzhjing** [comment]
@sboeuf I have code draft to add multi-thread support for vhost-user-net backend, and have discussed with @yangzhon last week, there are some changes needed to make it work for all backends sharing the lib code, this is also one reason I do not add multi-thread for vhost-user-net backend in PR #409, we agree it's better to open a new PR for backend. I will open it later once code ready.

**Comment by sboeuf** [comment]
@bjzhjing 
>there are some changes needed to make it work for all backends sharing the lib code.

Yes I understand that, that's why I'm suggesting that you or @yangzhon send a PR to update the `vhost_user_backend` crate so that we can properly support multi-threads when using multiple queues.

**Comment by yangzhon** [comment]
@bjzhjing ,

https://github.com/cloud-hypervisor/cloud-hypervisor/pull/409/commits/d9e50f2ea2032f67cd62baf4a658ff9de000813a

This patch did not add multiple-thread support, please update it. thanks.

**Comment by bjzhjing** [comment]
@yangzhon I think we could close this one since issue #628 is opened for the same thing.

**Comment by sboeuf** [comment]
@bjzhjing what's the status on this? Any progress?

**Comment by bjzhjing** [comment]
@sboeuf Yes, I think it's good, for I've seen throughput improvement for vhost-user-net backend, I will push the code today.

**Comment by rbradford** [comment]
Fixed in #785
