### ISSUE TITLE
Error while using Raw disk in O_DIRECT mode w/ 4k block size.

### ISSUE THREAD

**Issue by thomasbarrett** [cloud-hypervisor/cloud-hypervisor#5722]
I am attempting to use cloud hypervisor to start a virtual machine with a disk with a 4k block size.  I get the following error:
```
Error booting VM: VmBoot(DeviceManager(DetectImageType(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })))
```

Digging into the issue, I noticed that the `detect_image_type` reads a 512 byte block to detect the image type. I changed the Sector size and alignment to 4096, but still saw the same error.

I wrote a small test program to try to read a sector from the disk, and did not see the issue. Any ideas what this could be?
```rust
use std::fs::OpenOptions;
use std::os::unix::fs::OpenOptionsExt;
use std::io::Read;

fn main() -> std::io::Result<()> {
    let mut f = OpenOptions::new().read(true).write(true).custom_flags(libc::O_DIRECT).open("/dev/nvme1n1")?;
    #[repr(align(4096))]
    struct Sector {
        data: [u8; 4096],
    }
    let mut s = Sector { data: [0; 4096] };

    f.read_exact(&mut s.data)?;

    Ok(())
}
```

note: I cannot use VFIO passthrough because this is a NVMe/OF disk, not a NVMe/PCI disk.

**Comment by thomasbarrett** [comment]
Figured out what the issue was. The detect_image_type function was making a call to `vhd::is_fixed_vhd`, which was making a non-4096 byte aligned read. Unless someone has a better idea, I will put up a PR to add a `type=qcow2|raw|vhdx` option when attaching a disk.

**Comment by thomasbarrett** [comment]
https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5723/files

**Comment by peng6662001** [comment]
@thomasbarrett Could you please share the function to make a disk with 4k block size?Is it `./scripts/rpc.py bdev_aio_create`?
