### ISSUE TITLE
Feature Request: Rate Limiting Groups

### ISSUE THREAD

**Issue by thomasbarrett** [cloud-hypervisor/cloud-hypervisor#5726]
For use in a public cloud, it would be nice for cloud-hypervisor to have rate limiting groups [similar to QEMU](https://github.com/qemu/qemu/blob/master/docs/throttle.txt) so that it is possible to throttle the cumulative I/O bandwidth / IOPs of all block devices attached to a virtual machine (e.g. [AWS per-instance EBS bandwidth limitations](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html)). I see that individual virtio-blk and virtio-net devices can be throttled with cloud-hypervisor, but I don't see a solution for throttling groups of block devices. 

The proposed syntax for this feature is:
```
--rate-limit-group name=<name>,bw_size=<bytes>,bw_one_time_burst=<bytes>, bw_refill_time=<ms>,ops_size=<io_ops>, ops_one_time_burst=<io_ops>,ops_refill_time=<ms>
--disk rate-limit-group=<name>
--disk rate-limit-group=<name>
--disk rate-limit-group=<name>
```

For backwards compatibility and convenience: if a block device is directly configured with a rate-limit, then a new throttling group should be created. The automatic group name should be derived from the name of the device.
```
--disk bw_size=<bytes>,bw_one_time_burst=<bytes>, bw_refill_time=<ms>,ops_size=<io_ops>, ops_one_time_burst=<io_ops>,ops_refill_time=<ms>
```

**Comment by rbradford** [comment]
This UI seems fine - you could create the automatic group name derived from the name of the device.

**Comment by thomasbarrett** [comment]
Yeah I like that a lot. Updated the description above.

**Comment by thomasbarrett** [comment]
Put out a preliminary PR that implements this feature.
https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6022

**Comment by thomasbarrett** [comment]
🎉
