### ISSUE TITLE
Ensure all integration tests use guest.wait_vm_boot()

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#5738]
Looks like some tests weren't included when this was introduced - check that all tests that can use this do for the boot (and I guess reboot too.)

**Comment by rmstoi** [comment]
@rbradford 

Typo in the title

>  vm_wait_boot

should be
wait_vm_boot

Unfortunately I cannot fix it myself.

**Comment by rmstoi** [comment]
@rbradford I checked all integration tests, the remaining that are not using wait_vm_boot are
```
test_vfio
_test_net_hotplug
test_initramfs
```
Replacing thread::sleep in those with guest.wait_vm_boot() causes error and tests fail.
I think this issue can be closed and remaining work continue with #5127
