### ISSUE TITLE
vCPU is resized failed on aarch64 platform

### ISSUE THREAD

**Issue by peng6662001** [cloud-hypervisor/cloud-hypervisor#5785]
**Describe the bug**
The vCPU doesn't change after resize with ch-remote on Ampere Altra. 

**To Reproduce**
On Guest
```
lscpu 
CPU(s):                          4
On-line CPU(s) list:             0-3
```
On Host
```
target/aarch64-unknown-linux-gnu/release/ch-remote --api-socket /tmp/cloud-hypervisor.sock resize --cpus 8
Error running command: Server responded with an error: InternalServerError: ApiError(VmResize(CpuManager(VcpuCreate(Failed to create Vcpu: Device or resource busy (os error 16)

root@adam-ubuntu:/home/dom/cloud-hypervisor/cloud-hypervisor# target/aarch64-unknown-linux-gnu/release/ch-remote --api-socket /tmp/cloud-hypervisor.sock resize --cpus 2
No response

root@adam-ubuntu:/home/dom/cloud-hypervisor/cloud-hypervisor# target/aarch64-unknown-linux-gnu/release/ch-remote --api-socket /tmp/cloud-hypervisor.sock resize --cpus 8
Error running command: Server responded with an error: InternalServerError: ApiError(VmResize(CpuManager(VcpuPendingRemovedVcpu)))
```
On Guest
```
lscpu
CPU(s):                          4
On-line CPU(s) list:             0-3

reboot

lscpu
CPU(s):                          2
On-line CPU(s) list:             0,1
```

**Version**

target/aarch64-unknown-linux-gnu/release/cloud-hypervisor --version
cloud-hypervisor v34.0-100-g09a9cce9

**VM configuration**
```
target/aarch64-unknown-linux-gnu/release/cloud-hypervisor \
        --cpus boot=4,max=8 \
        --memory size=4G \
        --kernel /root/workloads/Image \
        --cmdline "root=/dev/vda1 ro console=tty1 console=ttyS0 console=hvc0" \
        --disk path=/root/workloads/osdisk.img \
        --api-socket /tmp/cloud-hypervisor.sock \
        --rng src=/dev/random
```
Guest OS version details:
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
```

Host OS version details:
```
cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
```

**Logs**

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:
[log.txt](https://github.com/cloud-hypervisor/cloud-hypervisor/files/12655543/log.txt)
Linux kernel output:

**Comment by rbradford** [comment]
It looks like it failed to start the CPUs:

```cloud-hypervisor: 26.026217s: <vmm> ERROR:vmm/src/lib.rs:970 -- Error when resizing VM: CpuManager(VcpuCreate(Failed to create Vcpu: Device or resource busy (os error 16)```

@michael2012z @MrXinWang

**Comment by michael2012z** [comment]
Sorry I am travelling. I will try to look into the issue around the weekend.

**Comment by MrXinWang** [comment]
I am under the impression that arm64 still doesn't support vcpu hotplug (the `test_cpu_hotplug()` is x86 only), I guess that would be the reason?

**Comment by peng6662001** [comment]
When I start VM with hypervisor-fw,then resize the CPU to 2.
VM prints: 
```
[  133.079812] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PRES.CPLK], AE_NOT_FOUND (20221020/psargs-330)
[  133.082050] ACPI Error: Aborting method \_SB.CPUS.CSCN due to previous error (AE_NOT_FOUND) (20221020/psparse-529)
[  133.084123] ACPI Error: Aborting method \_SB.GEC.ESCN due to previous error (AE_NOT_FOUND) (20221020/psparse-529)
[  133.086326] ACPI Error: Aborting method \_SB.GED._EVT due to previous error (AE_NOT_FOUND) (20221020/psparse-529)
[  133.088413] acpi-ged ACPI0013:00: IRQ method execution failed
```

**Comment by peng6662001** [comment]
@rbradford I find `CONFIG_HOTPLUG_CPU=y` and `CONFIG_ACPI_HOTPLUG_CPU=y`,should I check others?

**Comment by rbradford** [comment]
> @rbradford I find `CONFIG_HOTPLUG_CPU=y` and `CONFIG_ACPI_HOTPLUG_CPU=y` in the config file,should I check others?

Maybe support has landed since we added the aarch64 support - there will almost certainly be more changes required than just removing some of the conditional code compilation.

**Comment by rbradford** [comment]
Here is the last update from one of the CH aarch64 maintainers - https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1125#issuecomment-1016301429

**Comment by MrXinWang** [comment]
Hi @rbradford, thanks for noticing! I think I would clarify some of my points :)

Firstly,
> Here is the last update from one of the CH aarch64 maintainers - https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1125#issuecomment-1016301429

Yes this latest update status still holds now. AFAICT the **virtual** CPU hotplug is still a WIP in the Linux kernel mailing list, I think @jongwu is constantly following the status on that one (so please correct me if I am making any mistakes).

Secondly,
> @rbradford I find CONFIG_HOTPLUG_CPU=y and CONFIG_ACPI_HOTPLUG_CPU=y in the config file,should I check others?

@peng6662001 , these two Kconfig option **does not** necessarily mean the **virtual** CPU hotplug, I think they mean CPU online/offline, which
- In baremetal Linux is used for the **physical** CPU hotplug, which Arm64 supports (assuming the PSCI is available).
- In KVM virtual machine, means the **virtual** CPU hotplug, and we unfortunately **do not** support now (see my comment above).

Let me know if I made my points cleared. @michael2012z @jongwu please feel free to add more information.

**Comment by jongwu** [comment]
@peng6662001 -, ACPI_HOTPLUG_CPU is meaningless on Arm. Virtual Cpu Hotplug(not for online/offine) support is still in review for kernel part which blocks us from enabling this feature on CH. So, just forget this for now.

**Comment by peng6662001** [comment]
@jongwu Thanks for your reply.
