### ISSUE TITLE
Create a do-not-merge label that prevents PR from being merged by mistake

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#58]
I think we should look into the existing Github plugins that would allow us to prevent PRs to be merged if someone set the `do-not-merge` label.

We also need to create the label but this is trivial.

**Comment by sboeuf** [comment]
This has been implemented. We have Jenkins checking for `[DNM]` or `[WIP]`, which results in preventing the CI from running. And because the CI didn't run, the PR cannot be merged.

**Comment by parushyata** [comment]
[not ready for review]
