### ISSUE TITLE
Add ability to query build-time features using a CLI option and/or new API

### ISSUE THREAD

**Issue by jodh-intel** [cloud-hypervisor/cloud-hypervisor#5817]
Given that CH can be built with various cargo features, it would be useful to provide ways to query how a CH binary has been built.

Ideally, this information would be available as a CLI option and an API call:

## CLI option

```bash
$ cloud-hypervisor --list-features
kvm
tdx
foo
```

The above would clearly be the simplest, but I'm wondering if it would be better to have a slightly more elaborate output showing all features and whether they are enabled or not. Something like:

```
$ cloud-hypervisor --list-features
kvm: enabled
tdx: enabled
foo: builtin
bar: disabled
```

Doing this would provide more information to the caller. For example, they'd know if the version of CH they are using is "too old" as it simply wouldn't list newer features. Including a "builtin" value would also allow the caller to determine if a feature was removed and is now part of the "core" of CH.

## Capabilities API

A new `/vmm.capabilities` API, similar to `vm.info`, that would return the details listed in the CLI section above. 

Either or both of these ways of viewing the build-time features would be of great benefit to the [Kata Containers team](https://github.com/kata-containers/kata-containers) as it would allow for simpler and clearer error messages if the user's  version of CH did not provide the features needed for particular Kata scenarios.

**Comment by rbradford** [comment]
Could we include it under `--version` and also whatever API end point we have that has the version in it?

**Comment by likebreath** [comment]
> Could we include it under `--version` and also whatever API end point we have that has the version in it?

Reusing  `--version` for this purpose could be confusing in certain cases. I like the idea to augment the `/vmm.ping` endpoint with the feature information. It will also be very easy to consume (in JSON format).

@jodh-intel I am assuming the above API would be enough and CLI option is not particularly needed for Kata's use case, right?

**Comment by jodh-intel** [comment]
>  I like the idea to augment the /vmm.ping endpoint with the feature information.

+1.

> @jodh-intel I am assuming the above API would be enough and CLI option is not particularly needed for Kata's use case, right?

Yes, Kata would primarily use the API. But I think that if this feature is added it would also be very useful to users to expose it via a CLI option too.

> > Could we include it under --version and also whatever API end point we have that has the version in it?

> Reusing --version for this purpose could be confusing in certain cases. 

Unless we only listed the features if the user _also_ specified `--verbose` (`--version -v`).

**Comment by rveerama1** [comment]
I have some comments https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5820#issuecomment-1748521809 . Please take a look.
