### ISSUE TITLE
Only advertise AMX feature bits to guest when the AMX cpu feature is enabled

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#5833]
Original reported by @zhangylc from https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5800#issuecomment-1757530912: 

> Without "amx" feature, the guest cannot start with guest montioned above.
> 
> > system version: openEuler release 22.03 LTS
> > kernel version: 5.10.0-136.49.0.127.oe2203sp1.x86_64
> 
> I modified the cpuid to disable "amx" feature, then the guest can start and migrate successfully.
> 
> ```rust
>     let entries = cpuid.as_mut_slice();
>     let mut value = 0;
>     for entry in entries.iter_mut() {
>         if entry.function == 0x07 && (0 == entry.index) {
>             value = entry.edx;
>         }
>     }    
>    ...
>     CpuidPatch::set_cpuid_reg(
>         &mut cpuid,
>         0x7,
>         Some(0),
>         CpuidReg::EDX,
>         value & !(1 << 22) & !(1 << 24) & !(1 << 25),
>     );
> ```

**Comment by rbradford** [comment]
What's our plan for a.) removing the compile time feature flag b.) removing the cpu config option?
