### ISSUE TITLE
KSM merges no pages

### ISSUE THREAD

**Issue by jpds** [cloud-hypervisor/cloud-hypervisor#5873]
**Describe the bug**

I have `cloud-hypervisor` deployed on a number of machines and then virtual machines running from the same rootfs image.

All machines are also configured to set memory with: `--memory mergeable=on,shared=on,size=1024M`.

However, I do not see any pages being merged on any of the hosts:

```
$ grep . /sys/kernel/mm/ksm/*
/sys/kernel/mm/ksm/full_scans:0
/sys/kernel/mm/ksm/max_page_sharing:256
/sys/kernel/mm/ksm/merge_across_nodes:1
/sys/kernel/mm/ksm/pages_shared:0
/sys/kernel/mm/ksm/pages_sharing:0
/sys/kernel/mm/ksm/pages_to_scan:100
/sys/kernel/mm/ksm/pages_unshared:0
/sys/kernel/mm/ksm/pages_volatile:0
/sys/kernel/mm/ksm/run:1
/sys/kernel/mm/ksm/sleep_millisecs:20
/sys/kernel/mm/ksm/stable_node_chains:0
/sys/kernel/mm/ksm/stable_node_chains_prune_millisecs:2000
/sys/kernel/mm/ksm/stable_node_dups:0
/sys/kernel/mm/ksm/use_zero_pages:0
```

I've also tried adjusting the `pages_to_scan` value, but nothing changes. The same issue was observed at https://github.com/astro/microvm.nix/pull/40

**Version**

Output of `cloud-hypervisor --version`: v32.1.0

Did you build from source, if so build command line (e.g. features):

**VM configuration**

What command line did you run (or JSON config data):

```
/nix/store/vl6m6cjhyzzlsz7jc60faxkjpyr8697s-cloud-hypervisor-32.1/bin/cloud-hypervisor --cpus boot=2 --watchdog --console null --serial tty --kernel /nix/store/dc6qmalzs44bmha4yb9xzww8c8xfj9sc-linux-6.1.59-dev/vmlinux --initramfs /nix/store/mpkqw5yhl79wp57750rphpl8p69sdrd4-initrd-linux-6.1.59/initrd --cmdline console=ttyS0 reboot=t panic=-1 loglevel=4 init=/nix/store/51jdncfy1y9p2aamrcnbgfjm2insx86r-nixos-system-vm1-23.05pre-git/init regInfo=/nix/store/ann1a5vy6k9qwnhip0g2c7bz7z47k8a1-closure-info/registration --seccomp true --memory mergeable=on,shared=on,size=512M --fs tag=ro-store,socket=vm1-virtiofs-ro-store.sock --api-socket vm1.sock --net tap=vm-vm1,mac=...
```

Guest OS version details: NixOS 23.05

Host OS version details: NixOS 23.05

Linux kernel output: 6.1.59

**Comment by liuw** [comment]
The `full_scans` value is zero. My understanding is that KSM never did a pass on the mergeable areas, even though `run` was set to one.

I don't think this is related to Cloud Hypervisor (yet).

**Comment by jongwu** [comment]
ksm have no effect on shared memory which is decided by ksm implementation. However virtio-fs need memory set to shared. That's say, if you want to use virtio-fs, don't expect that ksm work well. It's not releated with CH as @liuw said.

**Comment by astro** [comment]
Does that mean KSM works with `--memory shared=off`?

**Comment by likebreath** [comment]
> Does that mean KSM works with `--memory shared=off`?

Yes, it should be. We have an integration test for KSM. Please take it as a reference for manually testing KSM with Cloud Hypervisor on your system: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/tests/integration.rs#L7212-L7217

**Comment by rbradford** [comment]
From the docs - https://docs.kernel.org/admin-guide/mm/ksm.html

> KSM only merges anonymous (private) pages, never pagecache (file) pages. KSM's merged pages were originally locked into kernel memory, but can now be swapped out just like other user pages (but sharing is broken when they are swapped back in: ksmd must rediscover their identity and merge again).

So marking the pages as `shared=on` prevents KSM from working.
