### ISSUE TITLE
Migrate docker container image from ubuntu 20.04 to 22.04

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#5878]
Originally posted by @rveerama1 from #5877:

> Migration attempt has been done few times already in following PRs. https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5072, https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5449, https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5456, https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5487 and dropped due to various reasons. One main reason was failure of the test named `live_migration::live_migration_sequential::test_live_migration_ovs_dpdk` https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5532.
>
> After analyzing those PRs I would like to approach this issue step by step.
>
> 1. Migrate to Ubuntu 22.04 with minimal changes where all the tests will be passed and CI will be happy.
> 2. Upgrade SPDK to latest or stable version.
> 3. Upgrade virtiofsd to latest or stable version.
> 4. Upgrade any other dependencies to latest or stable version based on how CI proceeds with tests or any other specific requirements.

**Comment by rveerama1** [comment]
I see some docker related information on jenkins.

https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/cloud-hypervisor/branches/PR-5877/runs/1/nodes/173/steps/177/log/?start=0

```

[2023-10-25T11:14:21.723Z] DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
[2023-10-25T11:14:21.723Z]             Install the buildx component to build images with BuildKit:
[2023-10-25T11:14:21.723Z]             https://docs.docker.com/go/buildx/
```

**Comment by likebreath** [comment]
> I see some docker related information on jenkins.
> 
> https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/cloud-hypervisor/branches/PR-5877/runs/1/nodes/173/steps/177/log/?start=0
> 
> ```
> 
> [2023-10-25T11:14:21.723Z] DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
> [2023-10-25T11:14:21.723Z]             Install the buildx component to build images with BuildKit:
> [2023-10-25T11:14:21.723Z]             https://docs.docker.com/go/buildx/
> ```

This is a separate issue and should be interfere with your migration here. 

Basically, the docker builder being used in our CI is now marked as deprecated since docker v23.0, and we should update `dev_cli.sh` to adopt the new way of building containers with `BuildKit`. More details are here: https://docs.docker.com/engine/deprecated/#legacy-builder-for-linux-images

**Comment by rveerama1** [comment]
https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5877 merged. Closing it.
