### ISSUE TITLE
guest OS crashed when it remove disk

### ISSUE THREAD

**Issue by grass-lu** [cloud-hypervisor/cloud-hypervisor#5886]
**Describe the bug**
guest OS crashed when it remove disk

root@cloud:~# cloud-hypervisor: 975.999106s: <vmm> ERROR:vmm/src/lib.rs:1105 -- Error when removing device from the VM: DeviceManager(UnknownDeviceId("id=_disk2"))

==== Possible seccomp violation ====
                                    Try running with `strace -ff` to identify the cause and open an issue: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/new
                          Bad system call (core dumped)

**To Reproduce**
1、start vm
./cloud-hypervisor --kernel ./hypervisor-fw --disk path=focal-server-cloudimg-amd64.raw --cpus boot=4,max=16 --memory size=1024M,hotplug_size=8192M --net tap=,mac=,ip=192.168.10.2,mask=255.255.255.0 --cmdline console=ttyS0 root=/dev/vda1 rw --api-socket /tmp/ch-socket --serial tty --console off
2、add disk
./ch-remote --api-socket /tmp/ch-socket add-disk path=cloud.img
3、remove disk
./ch-remote --api-socket /tmp/ch-socket remove-device "_disk2"
4、 guest os crashed
cloud-hypervisor: 975.999106s: <vmm> ERROR:vmm/src/lib.rs:1105 -- Error when removing device from the VM: DeviceManager(UnknownDeviceId("id=_disk2"))

==== Possible seccomp violation ====
                                    Try running with `strace -ff` to identify the cause and open an issue: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/new
                          Bad system call (core dumped)

**Version**

Output of `cloud-hypervisor --version`:

Did you build from source, if so build command line (e.g. features):
[root@ceasphere-node-1 cloud-hypervisor]# ./cloud-hypervisor --version
cloud-hypervisor v35.0-dirty

**VM configuration**

What command line did you run (or JSON config data):

Guest OS version details:
Ubuntu 20.04.6 LTS cloud ttyS0

root@cloud:~# uname -ar
Linux cloud 5.4.0-164-generic #181-Ubuntu SMP Fri Sep 1 13:41:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Host OS version details:

**Logs**

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:

Linux kernel output:

**Comment by grass-lu** [comment]
this is the console output：
cloud-hypervisor: 975.999106s: ERROR:vmm/src/lib.rs:1105 -- Error when removing device from the VM: DeviceManager(UnknownDeviceId("id=_disk2"))

==== Possible seccomp violation ====
Try running with strace -ff to identify the cause and open an issue: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/new
Bad system call (core dumped)

**Comment by rbradford** [comment]
> this is the console output： cloud-hypervisor: 975.999106s: ERROR:vmm/src/lib.rs:1105 -- Error when removing device from the VM: DeviceManager(UnknownDeviceId("id=_disk2"))
> 
> ==== Possible seccomp violation ==== Try running with strace -ff to identify the cause and open an issue: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/new Bad system call (core dumped)

That's all output from the VMM not the guest.

**Comment by grass-lu** [comment]
guest os  don't have some output

**Comment by grass-lu** [comment]
the branch stable/v32.x is good , disk hotplug  work good.
the guest message:
root@ubuntu:~# [   92.264555] pci 0000:00:04.0: [1af4:1042] type 00 class 0x018000
[   92.265417] pci 0000:00:04.0: reg 0x10: [mem 0xe7f00000-0xe7f7ffff]
[   92.267419] pci 0000:00:04.0: BAR 0: assigned [mem 0xc0000000-0xc007ffff]
[   92.268532] virtio-pci 0000:00:04.0: enabling device (0000 -> 0002)
[   92.270904] virtio_blk virtio3: [vdb] 20971520 512-byte logical blocks (10.7 GB/10.0 GiB)

**Comment by grass-lu** [comment]
the vm's command line  add arg "--seccomp false", remove device is ok.

**Comment by likebreath** [comment]
> the vm's command line add arg "--seccomp false", remove device is ok.

Then it means you had a seccomp violation. You can either use `strace` or `--seccomp log` + dmesg to understand which syscall is causing the violation.

**Comment by grass-lu** [comment]
[    3.693235] audit: type=1400 audit(1699090397.874:2): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lsb_release" pid=506 comm="apparmor_parser"
[    3.693610] audit: type=1400 audit(1699090397.874:3): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe" pid=507 comm="apparmor_parser"
[    3.693612] audit: type=1400 audit(1699090397.874:4): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe//kmod" pid=507 comm="apparmor_parser"
[    3.695396] audit: type=1400 audit(1699090397.874:5): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/snapd/snap-confine" pid=505 comm="apparmor_parser"
[    3.695397] audit: type=1400 audit(1699090397.874:6): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/snapd/snap-confine//mount-namespace-capture-helper" pid=505 comm="apparmor_parser"
[    3.698970] audit: type=1400 audit(1699090397.878:7): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/sbin/tcpdump" pid=509 comm="apparmor_parser"
[    3.699659] audit: type=1400 audit(1699090397.878:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/bin/man" pid=511 comm="apparmor_parser"
[    3.699661] audit: type=1400 audit(1699090397.878:9): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_filter" pid=511 comm="apparmor_parser"
[    3.699663] audit: type=1400 audit(1699090397.878:10): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_groff" pid=511 comm="apparmor_parser"
[   59.981491] pci 0000:00:04.0: [1af4:1042] type 00 class 0x018000
[   59.981609] pci 0000:00:04.0: reg 0x10: [mem 0xe7f00000-0xe7f7ffff]
[   59.982433] pci 0000:00:04.0: BAR 0: assigned [mem 0xc0000000-0xc007ffff]
[   59.982716] virtio-pci 0000:00:04.0: enabling device (0000 -> 0002)
[   59.984089] virtio_blk virtio3: [vdb] 20971520 512-byte logical blocks (10.7 GB/10.0 GiB)
