### ISSUE TITLE
Add GitHub check for copyright header on added files

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#5887]
A PR was landed that added a new file that didn't have copyright header. A good solution for checking this is reuse - https://github.com/fsfe/reuse-action

**Comment by rmstoi** [comment]
@rbradford do you remember the PR number?

Would be good example to test against.

**Comment by rbradford** [comment]
We need to be "reuse" clean first before we even consider the PR check.

**Comment by rmstoi** [comment]
`reuse lint` reports many issues:

* files with copyright information: 212 / 342
* files with license information: 193 / 342

I've created workflow to run reuse lint.

https://github.com/rmstoi/cloud-hypervisor/tree/reuse
https://github.com/rmstoi/cloud-hypervisor/actions/runs/8525504956/job/23352598589

All of the reported issues would need to be fixed first. I've attached the output of reuse lint.
[reuse-lint.txt](https://github.com/cloud-hypervisor/cloud-hypervisor/files/14839498/reuse-lint.txt)

**Comment by likebreath** [comment]
> `reuse lint` reports many issues:
> 
> * files with copyright information: 212 / 342
> * files with license information: 193 / 342
> 
> I've created workflow to run reuse lint.
> 
> https://github.com/rmstoi/cloud-hypervisor/tree/reuse https://github.com/rmstoi/cloud-hypervisor/actions/runs/8525504956/job/23352598589
> 
> All of the reported issues would need to be fixed first. I've attached the output of reuse lint. [reuse-lint.txt](https://github.com/cloud-hypervisor/cloud-hypervisor/files/14839498/reuse-lint.txt)

Thank you for looking into this and sharing the result. 

Looks like the major part of files missing license/copyright information are non source code files, say .md/.yaml/.toml/.sh, etc. The following source files was also reported as missing license, while I believe most of them are only missing `SPDX-License-Identifier`. We can take a closer look at them first:

```
The following files have no licensing information:
* arch/src/aarch64/uefi.rs
* arch/src/x86_64/mpspec.rs
* block/src/qcow/mod.rs
* block/src/qcow/qcow_raw_file.rs
* block/src/qcow/refcount.rs
* block/src/qcow/vec_cache.rs
* devices/src/legacy/cmos.rs
* devices/src/legacy/i8042.rs
* fuzz/fuzz_targets/qcow.rs
* hypervisor/src/arch/aarch64/gic.rs
* hypervisor/src/arch/aarch64/mod.rs
* hypervisor/src/arch/x86/msr_index.rs
* hypervisor/src/kvm/aarch64/gic/mod.rs
* net_gen/src/lib.rs
* pci/src/bus.rs
* pci/src/configuration.rs
* pci/src/device.rs
* pci/src/lib.rs
* virtio-devices/src/balloon.rs
* virtio-devices/src/mem.rs
* virtio-devices/src/rng.rs
```
