### ISSUE TITLE
Support Crucible Block Devices

### ISSUE THREAD

**Issue by Smithx10** [cloud-hypervisor/cloud-hypervisor#5896]
[OxideComputer](https://github.com/oxidecomputer) has created a Replicated Block Device service called [Crucible](https://github.com/oxidecomputer/crucible).    

VMMs can interact with it via it's rust client.  An example of this can be found [here](https://github.com/oxidecomputer/propolis/blob/master/lib/propolis/src/block/crucible.rs) in [Propolis](https://github.com/oxidecomputer/propolis) OxideComputer's  VMM UserSpace for Illumos Bhyve.

**Comment by rbradford** [comment]
Thank you for sharing this. I think this can be solved with a vhost-user-block backend without adding anything to Cloud Hypervisor itself.

**Comment by iggy** [comment]
@rbradford do you know of any examples of stand-alone vhost-user-block backends that aren't dpdk?

**Comment by rbradford** [comment]
@rbradford We have a reference rust one in this repository but beyond that - no.
