### ISSUE TITLE
Allow injecting NMI into the guest

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#5909]
Trigger the guest crash dump (or invoke whatever NMI handler in guest) for analysis.

**Comment by up2wing** [comment]
I'm glad to do this, assign this to me plz.

**Comment by liuw** [comment]
@up2wing thanks for stepping up!

**Comment by rbradford** [comment]
@liuw Can you further elaborate on the use case for this please?

**Comment by liuw** [comment]
> @liuw Can you further elaborate on the use case for this please?

I didn't notice this. Sorry.

The use case is that people can configure the guest to collect kdump when an NMI is triggered. The guest will reboot into a kdump kernel, collect a dump, and save it to disk for later analysis.
