### ISSUE TITLE
Significant boot-time performance drop when `io_uring` feature is enabled

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#5922]
With enabling `io_uring` feature (219716c3f199fff0f6b1d708d35b6779e8de68e7) for metrics tests, the boot time on single vCPU + virtio-block was increased from ~100ms to ~150ms (e.g. ~50% higher) [1]. 

This is not necessary a regression since we `io_uring` has been built-in since it was added and now is a default feature (after commit 6fdba7ca11acf3c557e74019d4d1eb067bf929a0). But we still need to look into this and see if we can avoid such performance drop while enabling `io_uring` feature.

[1] https://www.cloudhypervisor.org/metrics/

**Comment by rbradford** [comment]
I investigated this before - this is due to the probing of what functionality is supported.

**Comment by likebreath** [comment]
That's great to know. The current probing on `io_uring` is quite extensive. I believe we can simplify it, say only verify if related syscall is available from `/proc/kallsyms`?

**Comment by rbradford** [comment]
> That's great to know. The current probing on `io_uring` is quite extensive. I believe we can simplify it, say only verify if related syscall is available from `/proc/kallsyms`?

Unfortunately the IORING_OP_READV/WRITEV were only added later so they cannot be identified from the syscall alone.
