### ISSUE TITLE
VM booted fail when the number of vcpu exceeds 127

### ISSUE THREAD

**Issue by peng6662001** [cloud-hypervisor/cloud-hypervisor#5973]
**Describe the bug**
Virtual machines booted with CLOUDHV_EFI.fd fail on aarch64 when the number of vcpu exceeds 127,but /root/workloads/Image is good.

**To Reproduce**
**Version**

Output of `cloud-hypervisor --version`:
```
cloud-hypervisor v36.0-48-gaf06adfd
```

Did you build from source, if so build command line (e.g. features):
```
cargo build
```

**VM configuration**

What command line did you run (or JSON config data):
```
./cloud-hypervisor-static-aarch64 --cpus boot=128 --memory size=64G --kernel /root/workloads/CLOUDHV_EFI.fd --disk path=/home/dom/images/ubuntu22.04.raw --disk path=ubuntu-cloudinit.img --net fd=3,mac=c2:67:4f:53:29:cb
```

Guest OS version details:
`Ubuntu 22.04.3 LTS`

Host OS version details:
`Ubuntu 22.04.3 LTS`

**Logs**

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:
[log_128.txt](https://github.com/cloud-hypervisor/cloud-hypervisor/files/13411858/log_128.txt)

Linux kernel output:

**Comment by cicdteam** [comment]
this is a kernel limitation, you need a custom kernel if you want to use more CPUs

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/resources/linux-config-x86_64#L361

**Comment by peng6662001** [comment]
Hi @cicdteam I find error in log_128.txt
```
cloud-hypervisor: 812.464186ms: <vcpu0> DEBUG:devices/src/legacy/uart_pl011.rs:263 -- === New baudrate: 0 (clk: 24000000Hz, ibrd: 39, fbrd: 0) ===
cloud-hypervisor: 812.545585ms: <vcpu0> DEBUG:devices/src/legacy/uart_pl011.rs:263 -- === New baudrate: 38400 (clk: 24000000Hz, ibrd: 39, fbrd: 4) ===


Synchronous Exception at 0x00000000FB921340
```
It's edk2's log:
```
edk2/ArmPlatformPkg/PrePeiCore/AArch64/ArchPrePeiCore.c:26:    CharCount = AsciiSPrint (Buffer,sizeof (Buffer),"Synchronous Exception at 0x%X\n\r", LR);
```
The kernel hasn't started.
