### ISSUE TITLE
[Help wanted] Is there any prebuilt `OVMF.fd` can be used to start Windows-2022?

### ISSUE THREAD

**Issue by TimePrinciple** [cloud-hypervisor/cloud-hypervisor#6011]
**Describe the bug**
In the `windows.md`, which documents that to start Windows from Qemu requires a suitable `OVMF.fd`, I wonder where I can find one to start a Windows VM. 

**Guest OS**
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by rbradford** [comment]
And #6018 fixes the issue you reported about the windows.md documentation.

**Comment by Jinof** [comment]
OVMF_FW_URL=$(curl --silent https://api.github.com/repos/cloud-hypervisor/edk2/releases/latest | grep "browser_download_url" | grep -o 'https://.*[^ "]')
curl -LO $OVMF_FW_URL
