### ISSUE TITLE
Very slow memory allocation when memory first needed in a nested VM.

### ISSUE THREAD

**Issue by skaegi** [cloud-hypervisor/cloud-hypervisor#6060]
We're seeing very slow "initial" memory allocation when running CLH v37 (but don't think this is a new problem) when using nested virtualization -- we're not hot plugging here and just allocating pre-existing memory space for the first time. Once the memory has been formally allocated in the guest and is freed (so it can be used by other processes) allocation in the guest for that memory remains very fast as we expect.

**To Reproduce**
To reproduce artificially and focus just on the problem you can use a simple tool like eatmemory or roll your own like...
```
(Alpine, bust easy enough to adapt...)
apk add git make gcc musl-dev sudo && cd ~ && git clone https://github.com/julman99/eatmemory.git && cd eatmemory && make install
time eatmemory -t 0 2G
```

We originally saw this problem as the guest was allocating disk cache while downloading and unpacking docker images so something like...
```
cd ~ && curl -Ls -O https://github.com/kata-containers/kata-containers/releases/download/3.2.0/kata-static-3.2.0-amd64.tar.xz
time tar xJ -f kata-static-3.2.0-amd64.tar.xz && rm -rf /opt
```
... will also work but is less focused.

In terms of result, what we're seeing with "eatmemory" is...
```
(On the CLH Guest VM (Nested)-- running on top of another VM)
~/eatmemory # time eatmemory -t 0 2G
Currently total memory: 8353619968
Currently avail memory: 7964655616
Eating 2147483648 bytes in chunks of 1024...
Done, sleeping for 0 seconds before exiting...
real	0m 28.39s
user	0m 5.48s
sys	0m 22.89s

(On the underlying Host -- VM based)
~/eatmemory # time eatmemory -t 0 2G
Currently total memory: 33507655680
Currently avail memory: 26315927552
Eating 2147483648 bytes in chunks of 1024...
Done, sleeping for 0 seconds before exiting...
real	0m 3.01s
user	0m 0.46s
sys	0m 2.54s

---

For comparison on bare metal... (and slightly faster hardware)

(On the CLH Guest VM (NOT Nested)-- running on top of bare metal)
~/eatmemory # time eatmemory -t 0 2G
Currently total memory: 8353619968
Currently avail memory: 7964168192
Eating 2147483648 bytes in chunks of 1024...
Done, sleeping for 0 seconds before exiting...
real    0m 2.70s
user    0m 0.42s
sys     0m 2.26s

(On the underlying Host -- bare metal based)
~/eatmemory # time eatmemory -t 0 2G
Currently total memory: 33225068544
Currently avail memory: 11840684032
Eating 2147483648 bytes in chunks of 1024...
Done, sleeping for 0 seconds before exiting...
real    0m 1.27s
user    0m 0.48s
sys     0m 0.78s
```

**Version**

cloud-hypervisor v37.0.0

**VM configuration**

We're using Kata Containers 3.2.0 with a containerd shim updated to use CLH v37 (but see this in older CLH versions too)
2 vcpu with 8GB Ram
Default memory settings for Kata -- using "acpi" and "shared" -- See [1](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/clh.go#L511) and [2](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go#L36)

Guest OS version details:
Ubuntu 20.04 -- Kernel 6.1.69 (from source)

Host OS version details:
Ubuntu 20.04 -- Kernel 5.4.0-169-generic (from canonical)

**Logs**
Don't have anything interesting here but can generate as needed.

Using `strace` is also not helping us a ton to narrow this down...
```
(CLH Guest VM (Nested))
~/eatmemory # time strace -c eatmemory -t 0 2G
Currently total memory: 8353619968
Currently avail memory: 7965204480
Eating 2147483648 bytes in chunks of 1024...
Done, sleeping for 0 seconds before exiting...
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 50.07    0.216601           2     74910           munmap
 49.32    0.213333           2     74912           mmap
  0.58    0.002522           3       743           brk
  0.02    0.000084          84         1           nanosleep
  0.00    0.000020           5         4           writev
  0.00    0.000000           0         2           mprotect
  0.00    0.000000           0         1           ioctl
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         2           sysinfo
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           set_tid_address
------ ----------- ----------- --------- --------- ----------------
100.00    0.432560           2    150578           total
real	0m 30.22s
user	0m 5.55s
sys	0m 24.59s

(Host VM - strace of cloud-hypervisor process)
root@kube-cf431inl06scgp3lmpt0-gen2lon-workers-0000d89f:/# strace -c -f -p 183199
strace: Process 183199 attached with 17 threads
...
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 99.98   26.855756      227591       118           epoll_pwait
  0.01    0.001532          12       118           io_submit
  0.00    0.001329           9       140           io_getevents
  0.00    0.000954           5       170           write
  0.00    0.000624           9        67           read
  0.00    0.000178          14        12           futex
  0.00    0.000109           5        20           recvfrom
  0.00    0.000060          10         6           recvmsg
  0.00    0.000045           3        12           epoll_ctl
  0.00    0.000025           4         6           close
  0.00    0.000022          22         1           writev
  0.00    0.000022           3         6           getpid
  0.00    0.000020           3         6           dup
------ ----------- ----------- --------- --------- ----------------
100.00   26.860676                   682           total

```
While memory allocation is running we see two processors at close to 100% use.

**Comment by rbradford** [comment]
Nested virtualisation would be a lot slower for anything that requires a VM exit (a VMX VM exit rather than a visible KVM exit), such as touching a new page, as it needs to go back to the L0 hypervisor code before going into the L1 hypervisor code. Using 2MiB huge pages should mitigate this somewhat - how about repeating with 2MiB hugepages?

**Comment by skaegi** [comment]
Thanks @rbradford. Huge pages definitely work but create other problems for us  in terms of our monitoring and how the kubelet sees things - e.g. we're using clh with kata in k8s in a pretty mature solution. Switching to huge pages is a significant change for us and I was looking/hoping for something simpler where I might tune the memory manager or similar. 

Do you think that a change to the CLH memory manager is possible or is this a case where we should accept it and plan to use huge pages for the nested VM case. I wanted to at least create the issue and ask as I imagine nested VM cases are going to increasingly become the norm and was interesting what the CLH team thought.

**Comment by rbradford** [comment]
> Thanks @rbradford. Huge pages definitely work but create other problems for us in terms of our monitoring and how the kubelet sees things - e.g. we're using clh with kata in k8s in a pretty mature solution. Switching to huge pages is a significant change for us and I was looking/hoping for something simpler where I might tune the memory manager or similar.
> 
> Do you think that a change to the CLH memory manager is possible or is this a case where we should accept it and plan to use huge pages for the nested VM case. I wanted to at least create the issue and ask as I imagine nested VM cases are going to increasingly become the norm and was interesting what the CLH team thought.

The performance cost comes from KVM (and the hardware) - you would see it with any VMM. A good paper that explains the costs of why nested VM traps are expensive is this paper: https://www.doc.ic.ac.uk/~lvilanov/publications/files/isca19_svt.pdf

Huge pages help because they *significantly* reduce the number of "page faults" (EPT faults really) required.
