### ISSUE TITLE
Feature request: `virtio-sound` a.k.a. `virtio-snd` support

### ISSUE THREAD

**Issue by volkertb** [cloud-hypervisor/cloud-hypervisor#6065]
The VirtIO specification includes a paravirtualized sound device called `virtio-sound` our `virtio-snd`.

It would be useful to have support for this device type in Cloud Hypervisor.

I understand that Cloud Hypervisor primarily has cloud workloads in mind, but even within that context, there are use cases for streaming audio between hosts and guest VMs.

Thank you for considering.

**Comment by rbradford** [comment]
Could you share a use case where sound is required for a cloud computing workload?

**Comment by volkertb** [comment]
One thing that comes to mind: cloud gaming. Things like what Google tried with Stadia. Stadia may have been discontinued but the concept of VM-hosted cloud gaming is still very much alive.

Also perhaps remote (cloud-hosted) desktop sessions.

And maybe also certain video conferencing setups.

I'm pretty sure others can come up with more. :slightly_smiling_face:

**Comment by rbradford** [comment]
I don't think you need virtio-sound for any of those use cases (it can be achieved through the sound server inside the guest e.g. pulseaudtio) and  although providing a virtio sound device is easy; the hard part is exposing it in a useful way. This is the same reason why we don't support any display device, the virtio side is straightforward but exposing it in a useful way bloats the VMM (e.g a VNC server, SSL stack, etc, etc).

Using vfio-user you can implement any PCI device you like with any implementation/backend.

**Comment by YanVugenfirer** [comment]
VDI is a use case for a sound device in the VM.
Another use case is automotive or Android emulation in the cloud.

If you don't want to bloat the VMM, expose virtio device - but allow the implementation of the backend as a plugin or with vhost-user.
