### ISSUE TITLE
Can you publish `api_client` to crates.io?

### ISSUE THREAD

**Issue by Burning1020** [cloud-hypervisor/cloud-hypervisor#6076]
Hi there, do you have any plan to publish [api_client](https://github.com/cloud-hypervisor/cloud-hypervisor/tree/main/api_client) to crates.io? Thanks.

**Comment by rbradford** [comment]
No, I don't think so - that crate is only used to simplify some structure of the code. It's not for consumption outside Cloud Hypervisor. What would be your use case for that?
