### ISSUE TITLE
Kernel update issues with CI

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#611]
The VFIO and virtio-fs tests are failing on the CI: https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/job/cloud-hypervisor/job/PR-608/1/consoleFull

This looks like it is due to the kernel update.

@sboeuf can you investigate?

**Comment by sboeuf** [comment]
@rbradford virtio-fs maintainers updated the virtiofsd's CLI, which is why both virtio-fs and VFIO tests were failing. #614 should fix this!
