### ISSUE TITLE
Quick start guide example with multiple --disk arguments is invalid after release v36.0

### ISSUE THREAD

**Issue by oneumyvakin** [cloud-hypervisor/cloud-hypervisor#6130]
**Describe the bug**
Quick start guide contains command line exmaple with multiple --disk arguments which is invalid for version v36.0 and later.

**To Reproduce**
1. Open quick start guide https://www.cloudhypervisor.org/docs/prologue/quick-start/
2. Download release v36.0 or later
3. Try documentation example:
```
$ ./cloud-hypervisor \
	--kernel ./hypervisor-fw \
	--disk path=focal-server-cloudimg-amd64.raw --disk path=/tmp/ubuntu-cloudinit.img \
	....
```

**ACTUAL RESULT**
error: the argument '--disk <disk>...' cannot be used multiple times

**EXPECTED RESULT**
Update quick start guide to don't use --disk argument multiple times: 
```
$ ./cloud-hypervisor \
	--kernel ./hypervisor-fw \
	--disk path=focal-server-cloudimg-amd64.raw path=/tmp/ubuntu-cloudinit.img \
	....
```

**Version**

Output of `cloud-hypervisor --version`:
./cloud-hypervisor --version
cloud-hypervisor v37.0.0

**Comment by rveerama1** [comment]
@oneumyvakin Thanks for the report. I will update it.

**Comment by rveerama1** [comment]
https://github.com/cloud-hypervisor/cloud-hypervisor.github.io/pull/328
