### ISSUE TITLE
Use Github Actions for Running Integration Tests

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#6231]
We are moving away from Jenkins for our CI infrastructure, and starts to migrate to use Github Actions. The benefits of using GH actions include:

* Less maintenance (say no need to run and maintain a Jenkins controller)
* More seamless integration with GitHub with finer-grained control over each individual workers/jobs
* Easier integration of bare-metal systems (as self-hosted runners) for special tests

Thanks to the work done by @rbradford, @rveerama1, and @fidencio. We now have many workers migrated already, including:

- [x] `x86_64` worker (Azure VM)
- [x] `amd` worker (Azure VM)
- [x] `aarch64` worker (bare-metal)
- [x] `VFIO` worker (bare-metal) (main branch only)
- [x] `SGX` worker (bare-metal)  (main branch only)

Outstanding workers to finish include:

- [x] `metrics` worker (bare-metal)  (main branch only)
- [x] `rate-limiter` worker (bare-metal)  (main branch only)
- [x] `windows guest` worker on `aarch64` (Bare-metal)
- [x] `windows guest` worker on `x86_64` (Azure VM)
- [x] `cloud-hypervisor-dependabot-approver` from old subscription to new subscription

**Comment by likebreath** [comment]
@rveerama1 is actively working on the outstanding workers. The `metrics` worker and `rate-limiter` worker are based on Intel-sponsored bare-metal machines and we should be able to handle that.

There are more work to be done for the `windows guest` workers, since we are also switching the Azure subscription at the same time. It would be definitely very helpful to have someone from Microsoft side to help, particularly ones with "Azure" knowledge.
@liuw @weltling @russell-islam @jinankjain Will any of you can help this work or put someone suitable from your side in contact?

**Comment by weltling** [comment]
@likebreath with regard to Windows guest, please let me know which help is needed. Do I understand correctly, that we now also moving away from the baremetal aarch64 approach? Also, if switching the Azure subscription, all the storage accounts will be gone, also those with Windows guest VHDs. Please poke on slack we can chat through the open tasks, perhaps that's the simplest.

Thanks!

**Comment by likebreath** [comment]
> @likebreath with regard to Windows guest, please let me know which help is needed. 

I think the migration of Windows guest workers are pretty much done, I will let @rveerama1 to comment if he needs additional support on this front.

> Do I understand correctly, that we now are also moving away from the baremetal aarch64 approach?

No, we are going to have the same coverage on Windows guest tests, e.g. both x86_64 on Azure VM and aarch64 on bare-metal. The x86_64 one was done by @rveerama1 yesterday.

> Also, if switching the Azure subscription, all the storage accounts will be gone, also those with Windows guest VHDs. Please poke on slack we can chat through the open tasks, perhaps that's the simplest.
> 

These private Windows images are already migrated to the new subscription by @rbradford and @rveerama1. This is why we have Windows guest tests on x86_64. 

> Thanks!

@weltling We definitely need support for maintaining the Windows guest workers. I am planning to create a slack channel for `CI` related discussions to include all main contact of points for the various CI workers we are running. Will you be the best person to be added as the main contact of the point for Windows guest workers?

**Comment by weltling** [comment]
@likebreath thanks for the updates and explanations. Also correct, please contact me with regard to any Windows guest related matters. I've been taking care of preparing Windows guest images and some other topics in the past, so I'll continue on that in the future. 

Thanks

**Comment by rveerama1** [comment]
> These private Windows images are already migrated to the new subscription by @rbradford and @rveerama1. This is why we have Windows guest tests on x86_64.

One thing needs to be done next is adding windows guest tests in aarch64. To access azure connection string we might need to move ARM tests to merge queue. Lot of reorganization going on the workers side from Rob.

Two more tasks needs to be done.
1) I submitted WIP PR for metrics runner. But we have to setup metrics publishing environment under new subscription in Azure and provide the key to workflow.
2) Dependbot approver setup under new subscription.

**Comment by likebreath** [comment]
> > These private Windows images are already migrated to the new subscription by @rbradford and @rveerama1. This is why we have Windows guest tests on x86_64.
> 
> One thing needs to be done next is adding windows guest tests in aarch64. To access azure connection string we might need to move ARM tests to merge queue. 

To be clear, we will just need to move the Windows guest worker on aarch64 to merge queue. The normal aarch64 worker will stay on PR.

> Lot of reorganization going on the workers side from Rob.
> 
> Two more tasks needs to be done.
> 
> 1. I submitted WIP PR for metrics runner. But we have to setup metrics publishing environment under new subscription in Azure and provide the key to workflow.
> 2. Dependbot approver setup under new subscription.

One more thing to add is ideally we would want to have similar pre-checks to skip integration jobs like we have from Jenkins below. It might not be as easy since Github Action does not allow early exit.

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/18a4d732b94f50d51aaacdd261d49725e32fab37/Jenkinsfile#L489-L530
