### ISSUE TITLE
Add reboot and shutdown to the events emitted on event monitor

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#6274]
It seems extremely useful to me to have these events emitted when the VM is rebooted or shutdown (by e.g. ACPI or i8042)

**Comment by rbradford** [comment]
CC @alexellis

**Comment by alexellis** [comment]
Thank you. This would make a huge difference in usability for tasks, batch-jobs, and for CI where a VM may have an automated life-cycle.

**Comment by alexellis** [comment]
Hi @rbradford is this available in a release?

**Comment by rbradford** [comment]
> Hi @rbradford is this available in a release?

Yes - we made v39.0 on the 27th.
