### ISSUE TITLE
Add multithreading MQ to vhost-user-net backend

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#628]
With #409 merged we now support MQ in virtio-net and vhost-user-net (device side) but the backend needs to have MQ multithreading enabled.

**Comment by bjzhjing** [comment]
Actually, @yangzhon has opened issue #571 days ago, sorry, I forgot to mention that in the meeting. I think we could close the previous one, and track the open issue with this number.

**Comment by sboeuf** [comment]
@bjzhjing let's not close #571 as it's the generic issue that will track we add the MT/MQ support to `vhost_user_backend` crate.
But we still need specific issues for `vhost-user`/`-net`/`-blk`/`-fs`.

**Comment by bjzhjing** [comment]
@sboeuf  Sure, I see.

**Comment by rbradford** [comment]
Fixed in #785
