### ISSUE TITLE
 Unable to start virtual guest according to the steps described in the document

### ISSUE THREAD

**Issue by xianghaohyman** [cloud-hypervisor/cloud-hypervisor#629]
Here is the command  lines to start the virtual guest:
./cloud-hypervisor/target/release/cloud-hypervisor \
	--kernel ./linux-cloud-hypervisor/arch/x86/boot/compressed/vmlinux.bin \
	--console off \
	--serial tty \
	--disk path=clear-31890-kvm.img \
	--cmdline "console=ttyS0 reboot=k panic=1 nomodules i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd root=/dev/vda3" \
	--cpus boot=4 \
	--memory size=1024M \
	--net "tap=,mac=,ip=,mask=" \
	--rng

and , run the comlines , I get the debug info:
 [  414.833720] rcu: 	 (t=103256 jiffies g=-1047 q=102)
[  414.833720] NMI backtrace for cpu 2
[  414.833720] CPU: 2 PID: 649 Comm: hwrng Not tainted 5.0.0 #1
[  414.833720] Call Trace:
[  414.833720]  <IRQ>
[  414.833720]  dump_stack+0x4d/0x65
[  414.833720]  nmi_cpu_backtrace+0x9b/0xa0
[  414.833720]  ? lapic_can_unplug_cpu+0xa0/0xa0
[  414.833720]  nmi_trigger_cpumask_backtrace+0xb9/0xf0
[  414.833720]  arch_trigger_cpumask_backtrace+0x14/0x20
[  414.833720]  rcu_dump_cpu_stacks+0x92/0xc2
[  414.833720]  rcu_check_callbacks+0x485/0x610
[  414.833720]  ? account_system_time+0x3a/0x60
[  414.833720]  update_process_times+0x2a/0x50
[  414.833720]  tick_sched_handle+0x33/0x40
[  414.833720]  tick_sched_timer+0x37/0x70
[  414.833720]  ? tick_sched_do_timer+0x60/0x60
[  414.833720]  __hrtimer_run_queues+0xde/0x150
[  414.833720]  hrtimer_interrupt+0x111/0x240
[  414.833720]  smp_apic_timer_interrupt+0x59/0xa0
[  414.833720]  apic_timer_interrupt+0xf/0x20
[  414.833720]  </IRQ>
[  414.833720] RIP: 0010:iowrite16+0x32/0x40
[  414.833720] Code: 89 f2 77 26 48 81 fe 00 00 01 00 76 08 0f b7 d6 89 f8 66 ef c3 55 48 c7 c6 e5 74 e0 81 48 89 d7 48 89 e5 e8 10 fe ff ff 5d c3 <66> 89 3e c3 66 2e 0f 1f 84 00 00 00 00 00 48 81 fe ff ff 03 00 48
[  414.833720] RSP: 0000:ffffc9000154be68 EFLAGS: 00010292 ORIG_RAX: ffffffffffffff13
[  414.833720] RAX: ffffffff814389c0 RBX: ffff88803dae1a80 RCX: 0000000000000100
[  414.833720] RDX: ffffc900001ed000 RSI: ffffc900001ed000 RDI: 0000000000000000
[  414.833720] RBP: ffffc9000154be70 R08: 0000000000000001 R09: ffff88803df75f80
[  414.833720] R10: 0000000000000001 R11: 0000000000000000 R12: 0000000000000001
[  414.833720] R13: ffff88803df75f80 R14: 0000000000000040 R15: ffff88803de01d80
[  414.833720]  ? vp_synchronize_vectors+0x60/0x60
[  414.833720]  ? vp_notify+0x11/0x20
[  414.833720]  virtqueue_kick+0x26/0x40
[  414.833720]  virtio_read+0xe5/0x100
[  414.833720]  hwrng_fillfn+0x1e/0x130
[  414.833720]  kthread+0xfb/0x130
[  414.833720]  ? hwrng_attr_current_store+0xc0/0xc0
[  414.833720]  ? __kthread_bind+0x30/0x30
[  414.833720]  ret_from_fork+0x35/0x40

and , how to enter the guest ??? i am very confused , looking forward to your any help...

**Comment by rbradford** [comment]
I just tested and this works for me.

What git revision are you using?
What's your host OS and kernel version?
What's your host CPU? (/proc/cpuinfo)

**Comment by rbradford** [comment]
The most similar panic I could find was this QEMU bug: https://bugs.launchpad.net/qemu/+bug/1750229

I've validated the instructions on both F31 baremetal and Ubuntu 16.04 Azure.

**Comment by rbradford** [comment]
Also your kernel seems to have taken 414 (!) seconds to get to this point which looks kinda bad.

**Comment by xianghaohyman** [comment]
> I just tested and this works for me.
> 
> What git revision are you using?
> What's your host OS and kernel version?
> What's your host CPU? (/proc/cpuinfo)

Hi,  thank you for your reply
OS runs inside a VMware virtual machine
git version： 1.8.3.1
kernel version:   Linux  3.10.0-957.21.3.el7.x86_64 
OS ： CentOS Linux release 7.6.1810 (Core) 
cpu  model name	: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

**Comment by xianghaohyman** [comment]
> I just tested and this works for me.
> 
> What git revision are you using?
> What's your host OS and kernel version?
> What's your host CPU? (/proc/cpuinfo)

and...
Must it run on a physical host?

**Comment by xianghaohyman** [comment]
> I just tested and this works for me.
> 
> What git revision are you using?
> What's your host OS and kernel version?
> What's your host CPU? (/proc/cpuinfo)

hi，
Does cloud-hypervisor support nested virtualization?
Failed to run cloud-hypervisor on vmware virtual machine and kvm virtual machine？
Finally, cloud-hypervisor Runs successfully on a physical machine...

**Comment by sameo** [comment]
@xianghaohyman Cloud Hypervisor supports nested virtualization, but we only ever tested the kvm on kvm use case. Do you have more details on the vmware version you're using?

**Comment by rbradford** [comment]
@xianghaohyman Please run "lscpu" inside your VMWare guest and on your host (to verify that the address space of the guest cpu is no larger than that of the host.)

**Comment by rbradford** [comment]
No response from reporter.
