### ISSUE TITLE
vhost-user-{net/block}  easy activation

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#630]
Using vhost-user gives security improvements over virtio with in-process (with scope of lots more) 

- [x] Unify vhost-user-net and vhost-user-block binary commandline style so that it does not conflict with cloud-hypervisor
- [x] Refactor backends into their own crates
- [x] Pull "main" functions for vhost-user-block and vhost-user-net into cloud-hypervisor main binary
- [x] Unify --vhost-user-blk into --disk (might rename to --block)
- [x] Unify --vhost-user-net into --net
- [x] Spawn `/proc/$pid/exe` if no backend specified for vhost-user-net and vhost-user-blk
- [ ] Make vhost-user default for net and block

**Comment by sameo** [comment]
Looks good overall. I wonder about one thing, though: When we say:

> Pull "main" functions for vhost-user-block and vhost-user-net into cloud-hypervisor main binary

are we also saying that the vhost-user-{net/block} binaries won't be usable as standalone components? i.e. will they only be runnable through the `cloud-hypervisor` binary?

**Comment by rbradford** [comment]
There will be a single "cloud-hypervisor" binary. You could run them as they are currently run (with the new binary name and slightly different parameter), or through self activation.

**Comment by rbradford** [comment]
@sameo I'm also taking this opportunity to refactor the backends into their own crates which will make it very straightforward for someone to use the backends outside of the Cloud Hypervisor project.

**Comment by sameo** [comment]
> @sameo I'm also taking this opportunity to refactor the backends into their own crates which will make it very straightforward for someone to use the backends outside of the Cloud Hypervisor project.

That's what I was worried about, thanks. I see that you added this to the TODO list, so this all looks fine to me.

**Comment by sameo** [comment]
cc @slp

**Comment by rbradford** [comment]
I'm closing this issue as i've opened #775 to handle making it a default.
