### ISSUE TITLE
[RFC] devices: pvmemcontrol, control guest physical memory proterties

### ISSUE THREAD

**Issue by Dummyc0m** [cloud-hypervisor/cloud-hypervisor#6318]
I'm working on memory passthrough for lightweight VMs. We've come up with an approach that's guest driven and tries to keep the VM slim proactively. Memctl is the name of the device/driver that communicates between the guest and vmm to control the host backing of guest memory.

Yuanchu Xie <yuanchu@google.com>
Pasha Tatashin <pasha.tatashin@soleen.com> @soleen

---

Memctl provides a way for the guest to control its physical memory
properties, and enables optimizations and security features. For
example, the guest can provide information to the host where parts of a
hugepage may be unbacked, or sensitive data may not be swapped out, etc.

Memctl allows guests to manipulate its gPTE entries in the SLAT, and
also some other properties of the memory map the back's host memory.
This is achieved by using the KVM_CAP_SYNC_MMU capability. When this
capability is available, the changes in the backing of the memory region
on the host are automatically reflected into the guest. For example, an
mmap() or madvise() that affects the region will be made visible
immediately.

There are two components of the implementation: the guest Linux driver
and Virtual Machine Monitor (VMM) device. A guest-allocated shared
buffer is negotiated per-cpu through a few PCI MMIO registers, the VMM
device assigns a unique command for each per-cpu buffer. The guest
writes its memctl request in the per-cpu buffer, then writes the
corresponding command into the command register, calling into the VMM
device to perform the memctl request.

The synchronous per-cpu shared buffer approach avoids the kick and busy
waiting that the guest would have to do with virtio virtqueue transport.

We provide both kernel and userspace APIs
Kernel API
long memctl_vmm_call(__u64 func_code, __u64 addr, __u64 length, __u64 arg,
		     struct memctl_buf *buf);

Kernel drivers can take advantage of the memctl calls to provide
paravirtualization of kernel stacks or page zeroing.

User API
From the userland, the memctl guest driver is controlled via ioctl(2)
call. It requires CAP_SYS_ADMIN.

ioctl(fd, MEMCTL_IOCTL, struct memctl_buf *buf);

Guest userland applications can tag VMAs and guest hugepages, or advise
the host on how to handle sensitive guest pages.

Supported function codes and their use cases:
MEMCTL_FREE/REMOVE/DONTNEED/PAGEOUT. For the guest. One can reduce the
struct page and page table lookup overhead by using hugepages backed by
smaller pages on the host. These memctl commands can allow for partial
freeing of private guest hugepages to save memory. They also allow
kernel memory, such as kernel stacks and task_structs to be
paravirtualized.

MEMCTL_UNMERGEABLE is useful for security, when the VM does not want to
share its backing pages.
The same with MADV_DONTDUMP, so sensitive pages are not included in a
dump.
MLOCK/UNLOCK can advise the host that sensitive information is not
swapped out on the host.

MEMCTL_MPROTECT_NONE/R/W/RW. For guest stacks backed by hugepages, stack
guard pages can be handled in the host and memory can be saved in the
hugepage.

MEMCTL_SET_VMA_ANON_NAME is useful for observability and debugging how
guest memory is being mapped on the host.

Sample program making use of MEMCTL_SET_VMA_ANON_NAME and
MEMCTL_DONTNEED:
https://github.com/Dummyc0m/memctl-set-anon-vma-name/tree/main
https://github.com/Dummyc0m/memctl-set-anon-vma-name/tree/dontneed

Guest kernel driver
https://github.com/Dummyc0m/linux-memctl

The VMM implementation is being proposed for Cloud Hypervisor:
https://github.com/Dummyc0m/cloud-hypervisor/

**Comment by liuw** [comment]
I'm curious about the thread model here. Is the host kernel trusted?

**Comment by liuw** [comment]
> 
> The VMM implementation is being proposed for Cloud Hypervisor: https://github.com/Dummyc0m/cloud-hypervisor/

I had a quick look at the code. The virtual device is rather self-contained. I do wonder if using a magic I/O port without a proper discovery mechanism will fly in upstream Linux kernel community.

**Comment by likebreath** [comment]
>I do wonder if using a magic I/O port without a proper discovery mechanism will fly in upstream Linux kernel community.

Along this line, have you considered to add the memctl as a virtio device?

**Comment by Dummyc0m** [comment]
> I'm curious about the threat model here. Is the host kernel trusted?

It is. The goal is to contain untrusted workloads, while maintaining reasonable performance and cooperate with the container manager. I'll dig a bit more into the threat model.

> > The VMM implementation is being proposed for Cloud Hypervisor: https://github.com/Dummyc0m/cloud-hypervisor/
> 
> I had a quick look at the code. The virtual device is rather self-contained. I do wonder if using a magic I/O port without a proper discovery mechanism will fly in upstream Linux kernel community.

I lack experience in this area. Can you point me to a way to do this with a proper discovery mechanism? It might actually simplify things.





> > I do wonder if using a magic I/O port without a proper discovery mechanism will fly in upstream Linux kernel community.
> 
> Along this line, have you considered to add the memctl as a virtio device?

I have done an implementation with of a virtio device and communication with virtqueues, but to have synchronous calls the guest spins in a cpu_relax loop while it waits for the virtio thread on the host to wake up and process the request. When only calling madvise on a single page, the overhead added is significant on the order of ~40us, when the madvise call takes ~5us.

**Comment by liuw** [comment]
> > I'm curious about the threat model here. Is the host kernel trusted?
> 
> It is. The goal is to contain untrusted workloads, while maintaining reasonable performance and cooperate with the container manager. I'll dig a bit more into the threat model.
> 
> > > The VMM implementation is being proposed for Cloud Hypervisor: https://github.com/Dummyc0m/cloud-hypervisor/
> > 
> > 
> > I had a quick look at the code. The virtual device is rather self-contained. I do wonder if using a magic I/O port without a proper discovery mechanism will fly in upstream Linux kernel community.
> 
> I lack experience in this area. Can you point me to a way to do this with a proper discovery mechanism? It might actually simplify things.
> 

I'm no expert on this either, but this is how it can be done on x86 and ARM.

On x86 you can put that device into an ACPI table, but what table to put in is an open question. You may be able to use an OEM table for that, but I'm not sure.

On ARM you can define a device tree binding. Your driver can match against the compatibility string.

**Comment by Dummyc0m** [comment]
> 
> I'm no expert on this either, but this is how it can be done on x86 and ARM.
> 
> On x86 you can put that device into an ACPI table, but what table to put in is an open question. You may be able to use an OEM table for that, but I'm not sure.
> 
> On ARM you can define a device tree binding. Your driver can match against the compatibility string.

Gotcha. I was given the suggestion to make the device a PCI device like pvpanic. Does that sound alright?
Should I wait a few more days for more comments?

**Comment by liuw** [comment]
> > I'm no expert on this either, but this is how it can be done on x86 and ARM.
> > On x86 you can put that device into an ACPI table, but what table to put in is an open question. You may be able to use an OEM table for that, but I'm not sure.
> > On ARM you can define a device tree binding. Your driver can match against the compatibility string.
> 
> Gotcha. I was given the suggestion to make the device a PCI device like pvpanic. Does that sound alright? Should I wait a few more days for more comments?

PCI device sounds fine. You probably want to wait a few more days to see if others have more comments.

**Comment by liuw** [comment]
@Dummyc0m I'm wondering where you're at with this?

**Comment by Dummyc0m** [comment]
Thanks for the ping. I'm about to push an update redoing the device as a PCI device.

**Comment by Dummyc0m** [comment]
Update:

I've done away with the magic IO port and weird init sequence and restructured the device and driver to be PCI devices. I've never worked with PCI devices (and very limited experience with peripherals in general), so I don't know if the scheme I cooked up is reasonable. Please advise.

A few things:
I noticed that the PciDevice trait extends the BusDevice trait, and it seems to be a decision from the beginning of time. Why are the reads/writes not dispatched to the PciDevice impls themselves but to the BusDevice trait impls? I feel like I've made a hack here that's not very pretty. It would be good for multiple vcpus to operate concurrently on the same {Pci,Bus}Device, right?

On the kernel side, io{read,write}64 don't seem to be available as symbols with CONFIG_64BIT on x86. I'm not sure if I'm doing something wrong or there's an improvement to be made here.

The chv changes are here:
https://github.com/cloud-hypervisor/cloud-hypervisor/compare/main...Dummyc0m:cloud-hypervisor:memctl-pci

Kernel driver:
https://github.com/Dummyc0m/linux-memctl/commit/4e32bdc0abeedc90d485c8060474202ae415ae5e

**Comment by Dummyc0m** [comment]
> > Update:
> > I've done away with the magic IO port and weird init sequence and restructured the device and driver to be PCI devices. I've never worked with PCI devices (and very limited experience with peripherals in general), so I don't know if the scheme I cooked up is reasonable. Please advise.
> > A few things: I noticed that the PciDevice trait extends the BusDevice trait, and it seems to be a decision from the beginning of time. Why are the reads/writes not dispatched to the PciDevice impls themselves but to the BusDevice trait impls? I feel like I've made a hack here that's not very pretty. It would be good for multiple vcpus to operate concurrently on the same {Pci,Bus}Device, right?
> 
> I'm not sure why that code was structured like that, but I agree that allowing concurrent accesses is good.
> 
> What's the difference you see with and without concurrent accesses?
I don't have any tests or benchmarks actually. So if you push back against the change I can defer it :)

> 
> > On the kernel side, io{read,write}64 don't seem to be available as symbols with CONFIG_64BIT on x86. I'm not sure if I'm doing something wrong or there's an improvement to be made here.
> 
> There is a header `linux/io-64-nonatomic-lo-hi.h`, which contains non-atomic implementations of the io{read/write}64 variants. It breaks down a 64-bit operation into two 32-bit operations. You will be getting two traps into Cloud Hypervisor, since one 64-bit operation is now two 32-bit operations. If you don't care about atomicity you may be able to use that. A bunch of drivers use that.
> 
> I took a brief look at your code. It reads from and writes to a memory location. It is not invoking any side effect AIUI, so using the non-atomic variants should be fine.
I was actually assuming the writes handled by the BusDevice were 8 bytes, I can change that though. 4 bytes is more than enough for the command register.

**Comment by liuw** [comment]
> > > Update:
> > > I've done away with the magic IO port and weird init sequence and restructured the device and driver to be PCI devices. I've never worked with PCI devices (and very limited experience with peripherals in general), so I don't know if the scheme I cooked up is reasonable. Please advise.
> > > A few things: I noticed that the PciDevice trait extends the BusDevice trait, and it seems to be a decision from the beginning of time. Why are the reads/writes not dispatched to the PciDevice impls themselves but to the BusDevice trait impls? I feel like I've made a hack here that's not very pretty. It would be good for multiple vcpus to operate concurrently on the same {Pci,Bus}Device, right?
> > 
> > 
> > I'm not sure why that code was structured like that, but I agree that allowing concurrent accesses is good.
> > What's the difference you see with and without concurrent accesses?
> 
> I don't have any tests or benchmarks actually. So if you push back against the change I can defer it :)
> 

My understanding is this change will benefit other devices as well. You can run some I/O tests which exercise multiple queues to see the before and after number. That may give you some hints on how helpful the change is.

If the numbers show a significant improvement over the old code, we can spend more time refining the idea.

> > > On the kernel side, io{read,write}64 don't seem to be available as symbols with CONFIG_64BIT on x86. I'm not sure if I'm doing something wrong or there's an improvement to be made here.
> > 
> > 
> > There is a header `linux/io-64-nonatomic-lo-hi.h`, which contains non-atomic implementations of the io{read/write}64 variants. It breaks down a 64-bit operation into two 32-bit operations. You will be getting two traps into Cloud Hypervisor, since one 64-bit operation is now two 32-bit operations. If you don't care about atomicity you may be able to use that. A bunch of drivers use that.
> > I took a brief look at your code. It reads from and writes to a memory location. It is not invoking any side effect AIUI, so using the non-atomic variants should be fine.
> 
> I was actually assuming the writes handled by the BusDevice were 8 bytes, I can change that though. 4 bytes is more than enough for the command register.

Then 4-byte read and write should be good.

> 
> Let me know if the device looks fishy in any way. I'm trying to avoid embarrassing myself on LKML, but if it looks okay I'll send it there too.

I myself don't work on device driver so much nowadays, so I cannot say one way or another. I'm pretty sure people on LKML will have comments one way or another.

A minor comment is there is a header file `include/linux/pci_ids.h`. People will probably ask you to move the constants there.

**Comment by Dummyc0m** [comment]
Regarding the allowing concurrent accesses change, other devices would have to handle their own locking to see improvements. Are you referring to virtio-net multiqueue?

**Comment by liuw** [comment]
> Regarding the allowing concurrent accesses change, other devices would have to handle their own locking to see improvements. Are you referring to virtio-net multiqueue?

Yes, virtio-net.

**Comment by rbradford** [comment]
> > Regarding the allowing concurrent accesses change, other devices would have to handle their own locking to see improvements. Are you referring to virtio-net multiqueue?
> 
> Yes, virtio-net.

With e.g. virtio-net multiqueue there would be very little contention in terms of `Bus/PciDevice` as each queue pair has it's own thread - writes by the driver to the queue to signal that there is work to do (notify) will go directly through an `EventFd` to the target thread due to the use of ioeventfd. `Bus/PciDevice` is only used for initial setup with virtio devices.

**Comment by liuw** [comment]
> > > Regarding the allowing concurrent accesses change, other devices would have to handle their own locking to see improvements. Are you referring to virtio-net multiqueue?
> > 
> > 
> > Yes, virtio-net.
> 
> With e.g. virtio-net multiqueue there would be very little contention in terms of `Bus/PciDevice` as each queue pair has it's own thread - writes by the driver to the queue to signal that there is work to do (notify) will go directly through an `EventFd` to the target thread due to the use of ioeventfd. `Bus/PciDevice` is only used for initial setup with virtio devices.

Ah, yes. To verify the effect one has to hack the code a bit to skip the eventfd. Never mind then.

**Comment by liuw** [comment]
@Dummyc0m I have a hack https://github.com/liuw/cloud-hypervisor/commit/37eba08b8036019dda3a7ab3e3aa3f5cc49d62da if you want to see the difference. This change forces virtio devices to go through the dispatching logic inside Cloud Hypervisor.

**Comment by rbradford** [comment]
Looking through this device - why not make it a virtio device and put the requests inside inside descriptors in the queue? It even uses a guest allocated buffer - just like virtio? It also sounds like it overlaps a lot with virtio-mem - would it be possible to extend that instead?

**Comment by Dummyc0m** [comment]
@rbradford I could never get the virtio transport to have a roundtrip of < 5 microseconds, and this is nice to have because madvising a single page is around ~4 microseconds depending on the machine. In order to have a synchronous request/response I had to cpu_relax in the guest while waiting for the corresponding response on the queue to show up, and that can take a variable 50-100 micros.

**Comment by Dummyc0m** [comment]
I switched to using 4-byte read and writes and posted the driver at
https://lore.kernel.org/virtualization/20240514020301.1835794-1-yuanchu@google.com/

**Comment by Dummyc0m** [comment]
Per request from gregkh, I renamed the device to pvmemcontrol. Also the device endianness was not defined previously. Now it's clearly little endian. The chv fork repo has been updated, and LKML posting moved from RFC to PATCH v1:

https://lore.kernel.org/lkml/20240518072422.771698-1-yuanchu@google.com/

**Comment by liuw** [comment]
@Dummyc0m the code to CH is merged. Can we close this issue now?
