### ISSUE TITLE
kernel panic on out-of-bounds guest IRQ when starting vm with vfio device

### ISSUE THREAD

**Issue by up2wing** [cloud-hypervisor/cloud-hypervisor#6353]
**Describe the bug**
kernel panic when starting a vm with vfio device on AMD:

**To Reproduce**
Steps to reproduce the behaviour:
Repeat starting vm with vfio device on AMD machine.

**Version**
Output of `cloud-hypervisor --version`: v38.0-150-gd3e4f9cc

Did you build from source, if so build command line (e.g. features):

**VM configuration**

What command line did you run (or JSON config data):
./cloud-hypervisor -v --api-socket api.sock --cpus boot=1 --memory size=1G --disk path=jammy.raw --kernel vmlinux --serial tty,file=s.log --console off --seccomp false --cmdline "console=ttyS0 root=/dev/vda1 rw" --device path=/sys/bus/pci/devices/0000:0a:00.0

Guest OS version details:
ubuntu jammy
Host OS version details:

**Logs**

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:

Linux kernel output:
crash> bt
PID: 175044  TASK: ffff88b759442a00  CPU: 30  COMMAND: "vcpu0"
 #0 [ffff88b416eb7150] machine_kexec at ffffffff81099a37 
 #1 [ffff88b416eb7268] __crash_kexec at ffffffff811feb8b 
 #2 [ffff88b416eb7388] crash_kexec at ffffffff812009b5 
 #3 [ffff88b416eb73b0] oops_end at ffffffff8103adbb 
 #4 [ffff88b416eb73d8] die at ffffffff8103afd2 
 #5 [ffff88b416eb7408] do_general_protection at ffffffff8103564e 
 #6 [ffff88b416eb7440] general_protection at ffffffff82601068 
    [exception RIP: svm_update_pi_irte+390]
    RIP: ffffffffa0595076  RSP: ffff88b416eb74f8  RFLAGS: 00010246
    RAX: 0000000000000000  RBX: 91e001940002ab94  RCX: ffffffffa0595076
    RDX: 0000000000000000  RSI: 0000000000000004  RDI: 91e001940002ab98
    RBP: ffff88b416eb76c0   R8: ffffed1682dd6ee0   R9: ffffed1682dd6ee0
    R10: ffffed1682dd6edf  R11: ffff88b416eb76ff  R12: ffff88b571993800
    R13: ffffc9000eded000  R14: ffff88b416eb7698  R15: 000000000000005b
    ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
 #7 [ffff88b416eb76c8] svm_update_pi_irte at ffffffffa05958bd  [kvm_amd]
 #8 [ffff88b416eb76f8] kvm_arch_irq_bypass_add_producer at ffffffffa06f8c02  [kvm]
 #9 [ffff88b416eb7730] __connect at ffffffffa06280b4  [irqbypass]
#10 [ffff88b416eb7758] irq_bypass_register_consumer at ffffffffa062855f  [irqbypass]
#11 [ffff88b416eb7798] kvm_irqfd at ffffffffa06cad82  [kvm]
#12 [ffff88b416eb7858] kvm_vm_ioctl at ffffffffa06c7078  [kvm]
#13 [ffff88b416eb7c18] do_vfs_ioctl at ffffffff814aecfb 
#14 [ffff88b416eb7db0] ksys_ioctl at ffffffff814af5b1 
#15 [ffff88b416eb7f00] __x64_sys_ioctl at ffffffff814af8e3 
#16 [ffff88b416eb7f28] do_syscall_64 at ffffffff81003d82 
#17 [ffff88b416eb7f50] entry_SYSCALL_64_after_hwframe at ffffffff826000a4 
    RIP: 00007fa118d737cb  RSP: 00007fa118735538  RFLAGS: 00000246
    RAX: ffffffffffffffda  RBX: 00007fa11401e9b4  RCX: 00007fa118d737cb
    RDX: 00007fa118735540  RSI: 000000004020ae76  RDI: 0000000000000019
    RBP: 0000000000000001   R8: 000000000000000c   R9: 000000000000004d
    R10: 0000000000000000  R11: 0000000000000246  R12: 00007fa11401e9b4
    R13: 00007fa118735658  R14: 0000000000000000  R15: 00007fa118735718
    ORIG_RAX: 0000000000000010  CS: 0033  SS: 002b

**Comment by likebreath** [comment]
@up2wing To be clear, the kernel panic happens from the host OS, right?

**Comment by up2wing** [comment]
> @up2wing To be clear, the kernel panic happens from the host OS, right?

Yes, host kernel panics.
