### ISSUE TITLE
Consider dropping versionize

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#6370]
Firecracker have dropped it - https://github.com/firecracker-microvm/firecracker/pull/4230 and we have never taken advantage of the versioning in Cloud Hypervisor. I think we should just serde instead and take manual steps if we need to allow cross version migration (e.g. temporary custom logic to use multiple versions of the same field.) If we use json for the encoding we can take advantage of empty fields (and thus use default values) - or we could rewrite the state data upon migration / snapshot restore if necessary.

This would break live migration but due to various fixes live migration is not supported from v38.x - if we make a prompt decision we could enable this before the next release and take advantage of the existing breakage.

**Comment by rbradford** [comment]
It's also worth noting we use our own fork for versionize_derive and are stuck on an old version of versionize.

**Comment by up2wing** [comment]
I noticed there is same dicussion on rust-vmm:
https://github.com/rust-vmm/kvm-bindings/pull/101

**Comment by rbradford** [comment]
We already have a mix with serde for the kvm state (so not all our state is covered by versionize.)

**Comment by likebreath** [comment]
I think this is a good move. Let's see if we can migrate to use kvm-bindings crates before the next release (if https://github.com/rust-vmm/kvm-bindings/pull/101 can be landed in the near future).
