### ISSUE TITLE
Fedora VM hangs on boot

### ISSUE THREAD

**Issue by maburlik** [cloud-hypervisor/cloud-hypervisor#6439]
**Describe the bug**

I have been hitting sporadic boot hang issues for a while when launching back-to-back cloud-hypervisor VMs. This mostly happens with the Fedora 37 base image, and can happen on a fresh boot or reboot.

I've hit this with cloud-hypervisor v35.0, and continue to hit it since recently upgrading to v38.0.

Fresh boot:

cloud-hypervisor logs:
[chv.1582604111319321.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/15203820/chv.1582604111319321.log)

stdout log:
[chv.stdout.1582604111319321_2024-04-28T09-33-36.496.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/15203821/chv.stdout.1582604111319321_2024-04-28T09-33-36.496.log)

**To Reproduce**
Steps to reproduce the behaviour:

Launch 4 VMs, reboot them, tear them down, and recreate back to back in succession x100 iterations.

**Version**

Output of `cloud-hypervisor --version`:
> cloud-hypervisor v38.0

Did you build from source, if so build command line (e.g. features):
Yes, built from source from tag v38.0

**VM configuration**

What command line did you run (or JSON config data):

JSON config:
```
{"cpus":{"boot_vcpus":2,"max_vcpus":2},"memory":{"size":1073741824,"shared":true},"payload":{"kernel":"/home/proj/myagent/_work/_temp/out/release/proj/bin/serv.code/OVMF-CLOUDHV-DEBUG.fd"},"disks":[{"path":"/home/proj/myagent/_work/_temp/out/src/test/e2e_test/test-data/vm_ssh_test_2_fedora/vm_ssh_test_2/fedora_reboot.vm_ssh_test_2.raw"},{"path":"/home/proj/myagent/_work/_temp/out/src/test/e2e_test/test-data/vm_ssh_test_2_fedora/vm_ssh_test_2/cloud-init/nocloud_ds.iso"}],"net":[{"tap":"proj_ptap_6b60","mac":"52:69:6b:5f:d8:ac"}],"fs":[{"tag":"/secrets","socket":"/tmp/serv_sockets/virtiofsd-socket-484"},{"tag":"proj_mount_tag_242","socket":"/tmp/serv_sockets/virtiofsd-socket-485"},{"tag":"proj_mount_tag_243","socket":"/tmp/serv_sockets/virtiofsd-socket-486"},{"tag":"proj_vm_diagnostics","socket":"/tmp/serv_sockets/virtiofsd-socket-487"}],"serial":{"mode":"Tty"},"console":{"mode":"Off"},"vsock":{"cid":124,"socket":"/tmp/serv_sockets/proj-vm-guest-socket-124.vsock"},"watchdog":true}
```

Guest OS version details:

Fedora 37: https://mirrors.rit.edu/fedora/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.raw.xz

Host OS version details:

```
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Logs**

Shown above.

**Comment by rbradford** [comment]
Hi, thanks for opening this issue - this looks like the virtiofs daemon you are using is not accepting the connection: 

```
cloud-hypervisor: 125.332215s: <_fs6> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(failed to reconnect vhost-user backend: IoError(Custom { kind: Other, error: "failed reconnecting vhost-user backend: VhostUserGetFeatures(VhostUserProtocol(SocketBroken(Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" })))" }))
cloud-hypervisor: 125.332844s: <vmm> INFO:vmm/src/lib.rs:1125 -- VM exit event
cloud-hypervisor: 125.332898s: <vmm> INFO:virtio-devices/src/device.rs:334 -- Resuming virtio-fs
cloud-hypervisor: 125.332707s: <_fs4> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(failed to reconnect vhost-user backend: IoError(Custom { kind: Other, error: "failed reconnecting vhost-user backend: VhostUserGetFeatures(VhostUserProtocol(SocketBroken(Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" })))" }))
cloud-hypervisor: 185.441257s: <_fs3> ERROR:virtio-devices/src/vhost_user/vu_common_ctrl.rs:411 -- Failed connecting the backend after trying for 1 minute: VhostUserProtocol(SocketConnect(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))
cloud-hypervisor: 185.441584s: <_fs3> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(failed to reconnect vhost-user backend: IoError(Custom { kind: Other, error: "failed connecting vhost-user backend VhostUserConnect" }))
cloud-hypervisor: 185.449764s: <_fs5> ERROR:virtio-devices/src/vhost_user/vu_common_ctrl.rs:411 -- Failed connecting the backend after trying for 1 minute: VhostUserProtocol(SocketConnect(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))
cloud-hypervisor: 185.450342s: <_fs5> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(failed to reconnect vhost-user backend: IoError(Custom { kind: Other, error: "failed connecting vhost-user backend VhostUserConnect" }))
```

Tagging @slp as he knows about virtiofs

**Comment by maburlik** [comment]
@rbradford we are still hitting the issue mentioned above in the course of sysrq-trigger type reboots.
```
Error running worker: HandleEvent(failed to reconnect vhost-user backend: IoError(Custom { kind: Other, error: "failed connecting vhost-user backend VhostUserConnect" }))
```

@rjsilvams had created the issue below that called out some of the moving parts, where we are restarting virtiofsd in automation because on a typical reboot, cloud-hypervisor closes the virtiofs client to virtiofsd.
https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6601

We are trying to gather clues why this is happening, namely because it is causing the rebooting VM to hang, along with other rebooting cloud-hypervisor-based VMs on the system at the same time.

The scenario goes like this and repeats for an hour, to stress the below:
1. Four cloud-hypervisor VMs are booted with multiple virtiofsd-based volumes attached, each.
2. We do three types of reboots back-to-back to validate equivalent reboot handling, and to stress each reboot variant: reboot using cloud-hypervisor reboot REST API, regular reboot command over remote ssh command, then sysrq-trigger reboot over remote ssh command.
3. For each reboot variant, we reboot each of the deployed cloud-hypervisor VMs and await for them to return, validating healthy state by communicating with an agent over vsock.
4. Most of the time reboots go through without problem because our automation detects virtiofsd server process terminations and restarts virtiofsd processes when cloud-hypervisor terminates the clients to these servers.

On occasion, the reboot hangs and we observe the error mentioned above. Often times, we see multiple rebooting VMs hit this issue at the same time, which blocks the reboots of multiple VMs.
```
cloud-hypervisor: 451.035702s: <_vsock7> DEBUG:virtio-devices/src/vsock/unix/muxer.rs:226 -- vsock: muxer.send[rxq.len=0]: [5, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 8, 82, 105, 119, 4, 71, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0]
cloud-hypervisor: 451.036001s: <_vsock7> DEBUG:virtio-devices/src/vsock/device.rs:112 -- vsock: raising IRQ
cloud-hypervisor: 451.036057s: <_vsock7> DEBUG:virtio-devices/src/vsock/device.rs:126 -- vsock: epoll_handler::process_rx()
cloud-hypervisor: 451.036097s: <_vsock7> DEBUG:virtio-devices/src/vsock/device.rs:112 -- vsock: raising IRQ
cloud-hypervisor: 451.849263s: <_fs6> ERROR:virtio-devices/src/vhost_user/vu_common_ctrl.rs:411 -- Failed connecting the backend after trying for 1 minute: VhostUserProtocol(SocketConnect(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))
cloud-hypervisor: 451.849392s: <_fs6> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(failed to reconnect vhost-user backend: IoError(Custom { kind: Other, error: "failed connecting vhost-user backend VhostUserConnect" }))
cloud-hypervisor: 451.849668s: <_disk0_q0> INFO:virtio-devices/src/epoll_helper.rs:216 -- KILL_EVENT received, stopping epoll loop
cloud-hypervisor: 451.850116s: <__rng> INFO:virtio-devices/src/epoll_helper.rs:216 -- KILL_EVENT received, stopping epoll loop
cloud-hypervisor: 451.850258s: <_net2_qp0> INFO:virtio-devices/src/epoll_helper.rs:216 -- KILL_EVENT received, stopping epoll loop
cloud-hypervisor: 451.850272s: <_net2_ctrl> INFO:virtio-devices/src/epoll_helper.rs:216 -- KILL_EVENT received, stopping epoll loop
cloud-hypervisor: 451.850638s: <_vsock7> INFO:virtio-devices/src/epoll_helper.rs:216 -- KILL_EVENT received, stopping epoll loop
cloud-hypervisor: 451.850758s: <_fs4> ERROR:virtio-devices/src/vhost_user/vu_common_ctrl.rs:411 -- Failed connecting the backend after trying for 1 minute: VhostUserProtocol(SocketConnect(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))
cloud-hypervisor: 451.850860s: <_disk1_q0> INFO:virtio-devices/src/epoll_helper.rs:216 -- KILL_EVENT received, stopping epoll loop
cloud-hypervisor: 451.850880s: <_fs4> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(failed to reconnect vhost-user backend: IoError(Custom { kind: Other, error: "failed connecting vhost-user backend VhostUserConnect" }))
VMM thread exited with error: Error shutting down VMM: Resume(Resume(Error resuming vhost-user backend: VhostUserSetVringEnable(VhostUserProtocol(SocketBroken(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })))))
```

**Comment by maburlik** [comment]
@rbradford Is it possible that for some variants of reboot that the client to virtiofsd does not terminate? Is there a way to force this disconnect?

**Comment by maburlik** [comment]
> Hi, thanks for opening this issue - this looks like the virtiofs daemon you are using is not accepting the connection:
> 
> ```
> cloud-hypervisor: 125.332215s: <_fs6> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(failed to reconnect vhost-user backend: IoError(Custom { kind: Other, error: "failed reconnecting vhost-user backend: VhostUserGetFeatures(VhostUserProtocol(SocketBroken(Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" })))" }))
> cloud-hypervisor: 125.332844s: <vmm> INFO:vmm/src/lib.rs:1125 -- VM exit event
> cloud-hypervisor: 125.332898s: <vmm> INFO:virtio-devices/src/device.rs:334 -- Resuming virtio-fs
> cloud-hypervisor: 125.332707s: <_fs4> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(failed to reconnect vhost-user backend: IoError(Custom { kind: Other, error: "failed reconnecting vhost-user backend: VhostUserGetFeatures(VhostUserProtocol(SocketBroken(Os { code: 104, kind: ConnectionReset, message: \"Connection reset by peer\" })))" }))
> cloud-hypervisor: 185.441257s: <_fs3> ERROR:virtio-devices/src/vhost_user/vu_common_ctrl.rs:411 -- Failed connecting the backend after trying for 1 minute: VhostUserProtocol(SocketConnect(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))
> cloud-hypervisor: 185.441584s: <_fs3> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(failed to reconnect vhost-user backend: IoError(Custom { kind: Other, error: "failed connecting vhost-user backend VhostUserConnect" }))
> cloud-hypervisor: 185.449764s: <_fs5> ERROR:virtio-devices/src/vhost_user/vu_common_ctrl.rs:411 -- Failed connecting the backend after trying for 1 minute: VhostUserProtocol(SocketConnect(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))
> cloud-hypervisor: 185.450342s: <_fs5> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(failed to reconnect vhost-user backend: IoError(Custom { kind: Other, error: "failed connecting vhost-user backend VhostUserConnect" }))
> ```
> 
> Tagging @slp as he knows about virtiofs

This symptom of the VhostUserConnect error was happening as a side effect of a timeout on the management side, which was terminating the virtiofsd processes. We can close this. Thank you for your feedback.
