### ISSUE TITLE
Make dependabot only send security update PRs

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#6442]
One of the difficulties discussed on stable releases maintenance is that the dependencies upped the MSRV, making it hard to backport changes to older CH releases.

There is a way to make dependabot to do security update only PRs.

https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

**Comment by rbradford** [comment]
I think I would only want to do this for our stable branches rather than our main branch - I think there is value in keeping current with the main branch.

**Comment by liuw** [comment]
Sure. Are the stable branches configured as such already?

**Comment by likebreath** [comment]
> Sure. Are the stable branches configured as such already?

No. Stable branches do not have depdendabot setup.
