### ISSUE TITLE
Cleanup "fixed" device I/O port allocations

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#647]
Currently we have GED, ACPI, MemoryManager and CpuManager on fixed I/O port locations throughout the range. There's no canonical list of free I/O port ranges but we should try and put these into a sane range (potentially sequentially) from each other so as avoid conflicts like the one shown up in #644.

**Comment by sboeuf** [comment]
But how can we ever be sure we won't end up with the same case, where a driver assumes an I/O port should be at a specific address.
Unfortunately there's no mechanism like PCI BAR reprogramming with I/O ports.

**Comment by rbradford** [comment]
We can't :-( The other option is to move from I/O ports to MMIO addresses and then we can allocate them like we allocate other MMIO devices (or MMIO regions for PCI devices.) MMIO doesn't have as a good performance an I/O ports and it slightly more work but it would resolve this issue.

**Comment by sboeuf** [comment]
I think the performance of PIO vs MMIO is not a problem here, as these devices (GED, cpu and memory hotplug) won't be triggered on the "hotpath", therefore I wouldn't take this argument into account here.
And since we can pick any range we want on MMIO (which will solve the issue long term), I think you spotted the right solution to the problem here.

**Comment by rbradford** [comment]
For a 5% latency cost what throughput % do we see? I'm not sure that a "one-size" fits all queue size is necessary though...

**Comment by sameo** [comment]
> For a 5% latency cost what throughput % do we see? I'm not sure that a "one-size" fits all queue size is necessary though...

I guess this one was meant to be for #646 ?

**Comment by sameo** [comment]
Since we fully control the MMIO range and since the IO port address space is filled with non standardized ranges, moving to MMIO sounds sane to me. And I agree with @sboeuf, performance does not really matter for those devices.
