### ISSUE TITLE
CloudHypervisor crashed after shutting down VM

### ISSUE THREAD

**Issue by jinankjain** [cloud-hypervisor/cloud-hypervisor#6485]
**Describe the bug**
Notice a bug while shutting a CloudHypervisor guest:

```
[   44.056049] reboot: Power down
fatal runtime error: IO Safety violation: owned file descriptor already closed
Aborted (core dumped)
```

**To Reproduce**
Steps to reproduce the behaviour:

Started a guest using following command:

```
./target/debug/cloud-hypervisor --kernel ./hypervisor-fw --disk path=focal-server-cloudimg-amd64.raw path=/tmp/ubuntu-cloudinit.img --cpus boot=4 --memory size=1024M --serial tty --console off 
```

After guest boots up run `sudo poweroff` from inside the guest.

**Version**

Output of `cloud-hypervisor --version`:

Did you build from source, if so build command line (e.g. features):

branch bfe0106

**VM configuration**

What command line did you run (or JSON config data):

Guest OS version details:

Standard ubuntu 20.04 image

Host OS version details:

```
Linux radler 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

```

**Comment by liuw** [comment]
My usual test guest is focal, too. I couldn't reproduce this issue on my side. My host is Debian.

I notice your host is new. There is nothing in the tree that looks suspicious. Can you bisect?

**Comment by jinankjain** [comment]
Yeah, I can give bisection a try, but I don't have a good working version actually because recently I upgraded by machine to 24.04 and that comes with 6.8 host kernel.

**Comment by liuw** [comment]
> Yeah, I can give bisection a try, but I don't have a good working version actually because recently I upgraded by machine to 24.04 and that comes with 6.8 host kernel.

So this only happens after you upgrade to 24.04? Can you update your Rust toolchain and clear the build cache (`cargo clean`) to see if that makes a difference?

**Comment by jinankjain** [comment]
Already did that but the issue still persists.

**Comment by liuw** [comment]
Then it is perhaps a latent bug exposed by changes in libc or dependent library.

`strace` can perhaps tell you which fd gets closed twice. Using gdb to inspect the core dump may get you more information, too.

**Comment by liuw** [comment]
Are you using the beta compiler? The check seems to be recent https://github.com/rust-lang/rust/commit/1ba00d9cb2fcf.

The said commit doesn't seem to exist in Rust stable.

```
$ cd rust.git; git describe --contains 1ba00d9cb2fcf; popd
fatal: cannot describe '1ba00d9cb2fcfef464b6a188fa3a7543c66eecaa'
```

**Comment by jinankjain** [comment]
Indeed, I am using a nightly compiler to build on my dev machine. I can give it a try with a stable compiler toolchain and see if I can still repro this issue.

**Comment by liuw** [comment]
Okay, I can see the same with the nightly compiler. I think the more stringent check is exposing a latent bug in our code.
