### ISSUE TITLE
Ratio of cores:sockets has changed for default topology

### ISSUE THREAD

**Issue by smit-gardhariya** [cloud-hypervisor/cloud-hypervisor#6497]
**Describe the bug**
CLH vm with KVM takes more time compared to MSHV to boot with multi-vcpu guest for v38 version. Hence, the boot-time performance is degraded with testcase boot_time_16_vcpus_ms. I am testing on INTEL arch.

There is a change in default behavior for CPU topology for KVM guest between CLH v32 and Latest version.

I am raising this bug to verify what should be the default behavior w.r.t CPU topology when we dont pass anything explicitly which is what above mentioned testcase does exactly.

MSHV Guest on CLH v38 
```
Core(s) per socket:              16
Socket(s):                       1
```

KVM Guest on CLH v32:
```
target/x86_64-unknown-linux-gnu/release/cloud-hypervisor --cpus boot=16 --memory size=1G --disk path=./osdisk.img --disk path=./cloudinit --kernel ./vmlinux --cmdline "root=/dev/vda1 console=hvc0 rw systemd.journald.forward_to_console=1"

lscpu
===========
Thread(s) per core:              1
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
```

KVM Guest on Latest v39:
```
target/x86_64-unknown-linux-gnu/release/cloud-hypervisor --cpus boot=16 --memory size=1G --disk path=./osdisk.img path=./cloudinit --kernel ./vmlinux --cmdline "root=/dev/vda1 console=hvc0 rw systemd.journald.forward_to_console=1"

Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       16
NUMA node(s):                    1
```

Boot-time performance for above mentioned testcase

With CLH v32
`{
  "git_human_readable": "v32.0",
  "git_revision": "42ca292dce4292f0f69bd7cecd7db09eee3b64bb",
  "git_commit_date": "Thu May 18 10:09:15 2023 -0700",
  "date": "Thu May 30 08:59:09 UTC 2024",
  "results": [
    {
      "name": "boot_time_16_vcpus_ms",
      "mean": 223.2306,
      "std_dev": 9.297366779900655,
      "max": 236.97600000000003,
      "min": 211.82799999999997
    }
  ]
}
`

With latest CLH - v39
`{
  "git_human_readable": "v39.0-101-gd3cd2556",
  "git_revision": "d3cd25566b8c58bbdf61298fcfd21cf25c0350db",
  "git_commit_date": "Thu May 30 00:34:05 2024 +0000",
  "date": "Thu May 30 08:54:06 UTC 2024",
  "results": [
    {
      "name": "boot_time_16_vcpus_ms",
      "mean": 519.4962999999999,
      "std_dev": 12.556197808652112,
      "max": 540.433,
      "min": 503.01699999999994
    }
  ]
}`

**To Reproduce**
Run test boot_time_16_vcpus_ms with CLH latest version and v32

**Version**
Output of `cloud-hypervisor --version`: 39.0.0

Did you build from source, if so build command line (e.g. features):
cargo build --no-default-features --features kvm,mshv --all --release --target x86_64-unknown-linux-gnu

**VM configuration**
64 vCPUs and 256GB Memory

What command line did you run (or JSON config data): Run test with dev_cli
`./dev_cli.sh tests --hypervisor kvm --metrics -- -- --test-filter boot_time_16_vcpus_ms
`

Guest OS version details:
Default focal image from CLH test framework

Host OS version details:
Intel Machine with below OS details

VERSION="2.0.20240425"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"

**Logs**
NA

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:
NA

Linux kernel output:
Linux mariner-kvm 5.15.153.1-2.cm2 #1 SMP Thu Apr 25 16:39:35 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rbradford** [comment]
I believe this is the same root cause as #5646 - calling cpuid is a serialising instruction - the MSHV hypervisor backend involves fewer calls to host cpuid (the most host CPUs the bigger the impact.

I am surprised that the default topology changed - I would have hoped an integration test would have caught that.

**Comment by jinankjain** [comment]
@rbradford I think the default topology integration tests always passes the topology along with it. That's why we did not catch the fact that the default topology has changed.

**Comment by rbradford** [comment]
@smit-gardhariya In the future please don't put two different issues in the same bug - i've changed the title to refer to the more active issue raised here.
