### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by lisongqian** [cloud-hypervisor/cloud-hypervisor#6507]
We have very comprehensive test cases but the code coverage information is imperfect. We need to adapt the test cases for code information and export the correct code coverage information.

 In the feature, we will work on the following list:
- [x] Export code coverage information from unit tests and integration tests (#6508)
- [ ] Add a code coverage script(#6528)
- [ ] Complete code coverage document

**Comment by liuw** [comment]
This is good work. We can use the coverage data to further guide what tests to develop.

Out of interest, why improvement over the existing coverage number after you fix the SIGKILL issue?

**Comment by likebreath** [comment]
This is great. Thank you for stepping up for this work.

**Comment by lisongqian** [comment]
> Out of interest, why improvement over the existing coverage number after you fix the SIGKILL issue?

The coverage information collected by LLVM will be exported to files after the end of process and terminating the process will skip this operation. We need to make the process end normally.
