### ISSUE TITLE
Encounter resume VDPA error while resuming devices in the device tree

### ISSUE THREAD

**Issue by lisongqian** [cloud-hypervisor/cloud-hypervisor#6516]
The device manager will execute a resume to wake up the device worker thread in Drop, but currently, VDPA devices don't completely support resume. We will encounter a Resume error when dropping the device manager.

**Comment by likebreath** [comment]
Reporting errors for not supporte features is the right behavior. A related test failure from #6508 was due to seccomp violations and should be fixed accordingly as explained here [1].

[1] https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6508#issuecomment-2153101863
