### ISSUE TITLE
EVENT_IDX support to virtio-block

### ISSUE THREAD

**Issue by elainewu1222** [cloud-hypervisor/cloud-hypervisor#6580]
I found EVENT_IDX feature was once supported for virtio-block (see commit https://github.com/cloud-hypervisor/cloud-hypervisor/commit/4366dd92ac9a603b92d2b75c5d2773a281fd0e85 and issue https://github.com/cloud-hypervisor/cloud-hypervisor/issues/786), however in current main that feature is gone. 
Is there any reason for not supporting EVENT_IDX anymore? That can bring noticeable improvement for block IO perf.

**Comment by elainewu1222** [comment]
Hi @rbradford, I have raised a pr for supporting this: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6605.
It's all good for my benchmark, with a 76% performance improvement.
But since I only test it in my situation, it may still need some work. Pls have a look on it.

**Comment by rbradford** [comment]
You can see the improvement after #6605 landed in the graphs here:

https://www.cloudhypervisor.org/metrics/ in particular the single queue block read/write througput and IOPs.
