### ISSUE TITLE
landlock config should be part of VMConfig

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/cloud-hypervisor#6617]
**Describe the bug**
landlock config should be part of `VMConfig` instead of `vmm-config`. Moving landlock config to `VMConfig`, allows users to pass customer paths to `landlock-rules` during `vm.create` request.

**To Reproduce**

**Version**

Output of `cloud-hypervisor --version`: `v40.0-83-g330e1aac`

Did you build from source, if so build command line (e.g. features):

` cargo build --features kvm,mshv`
**VM configuration**

```
{
    "cpus": {
      "boot_vcpus": 2,
      "max_vcpus": 2
    },
    "memory": {
      "size": 1073741824
    },
    "payload": {
      "kernel": "/testdir/hypervisor-fw"
    },
    "disks": [
      {
        "path": "/testdir/jammy-server-cloudimg-amd64.raw"
      },
    ],
    "serial": {
      "mode": "Tty"
    },
    "console": {
      "mode": "Pty"
    },
    "landlock_enable": true,
    "landlock_config": [
      {
        "path": "/tmp/disk1",
        "access": "rw"
      },
      {
        "path": "/tmp/disk2",
        "access": "rw"
      }
    ]
}
```
What command line did you run (or JSON config data):

Guest OS version details: Jammy

**Comment by praveen-pk** [comment]
@rbradford in https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6214, you suggested Landlock config should be part of `vmm-config`. In our AKS usecase, we may have to pass additional paths via landlock-rules. Unfortunately, passing all the additional paths via cmdline is not an option for us.

The current workflow starts cloud-hypervisor process with minimal arguments (`-v --api-socket /path/to/socket`) and passes all VM config during `vm.create` request in the form of JSON. To retain this flow, I'd like to move landlock config to VMConfig. 

Please let me know if you have any concerns with this change.

**Comment by liuw** [comment]
Has adding more parameters when launching Cloud Hypervisor been considered? Why is that not an option?

**Comment by rbradford** [comment]
Seems reasonable to me to move it to `VmConfig` - it means you don't need to add extra command line parameters with e.g. restore and live migration and puts it in the JSON configuration.

**Comment by praveen-pk** [comment]
> Has adding more parameters when launching Cloud Hypervisor been considered? Why is that not an option?

Generally speaking cloud-hypervisor process is started with minimal arguments, Ex: `-v --api-socket /path/to/socket`. All other configuration is passed via `vm.create` request. This is the case with Libvirt as well.

Of course, adding additional cmdline parameters is an option too. But, workflows (AKS and Libvirt) have code in place to generate custom json to be passed to `vm.create` based on the guest's configuration. This change will allow this code logic to remain, without requiring them to reimplement how to start cloud-hypervisor process.

**Comment by praveen-pk** [comment]
> Seems reasonable to me to move it to `VmConfig` - it means you don't need to add extra command line parameters with e.g. restore and live migration and puts it in the JSON configuration.

Agreed. Infact, I modifed the live migration test to just this. In this only the source VM has landlock cmdline options passed. The destination will enable Landlock based on VMConfig from source.
