### ISSUE TITLE
Unable to create virtual machine with more than ~2.8G of RAM on arm64

### ISSUE THREAD

**Issue by thomasbarrett** [cloud-hypervisor/cloud-hypervisor#6632]
**Describe the bug**
I have been unable to create virtual machine with more than ~2.8G of RAM on arm64. Happy to provide more details / dig into this further, but wanted to see if this was a known limitation first. The virtual machine boots successfully, but `/proc/meminfo` still only reports 2.8G of RAM`

**To Reproduce**
Start a virtual machine with `--memory size=8G` on an arm64 host. Run `cat /proc/meminfo`

**Version**
cloud-hypervisor v40.0.0

**VM configuration**
sudo cloud-hypervisor --serial tty --console pty  --memory size=8G --kernel /var/lib/cloud-hypervisor/hypervisor-fw --disk path=/var/lib/cloud-hypervisor/jammy-server-cloudimg-arm64.raw 

Guest OS version details:
Ubuntu 22.04

Host OS version details:
Ubuntu 22.04

**Comment by liuw** [comment]
@jinankjain have you seen this?

**Comment by liuw** [comment]
What if you do direct kernel boot? That helps us understand if the issue is in the firmware or the kernel.

**Comment by jinankjain** [comment]
No I haven't seen such a issue when trying to boot with MSHV.

**Comment by liuw** [comment]
> No I haven't seen such a issue when trying to boot with MSHV.

Are you using direct kernel boot or hyperivsor-fw?

**Comment by jinankjain** [comment]
Direct kernel boot, hypervisor-fw does not boot yet with MSHV.

**Comment by thomasbarrett** [comment]
I just tested with direct kernel boot and was able to spin up a virtual machine with 720G of RAM. I will look deeper into rust-hypervisor-fw and see what I can find.

**Comment by thomasbarrett** [comment]
I added a debug log to rust-hypervisor-fw to print the fdt table. Looks like it is only detecting a single memory region entry
```
[INFO] Memory region 2048MiB@0x40000000
[INFO] Booting with FDT
```

**Comment by thomasbarrett** [comment]
With my PR, I was able to boot a virtual machine with up to 126 GiB of RAM
```
sudo cloud-hypervisor --serial tty --console pty  --memory size=126G,hugepages=on,hugepage_size=1G --kernel /var/lib/cloud-h
ypervisor/hypervisor-fw --disk path=/var/lib/cloud-hypervisor/jammy-server-cloudimg-arm64.raw
```

However, I was still not able to boot a virtual machine with 127 GiB of RAM. The process hangs with 100% CPU on vcpu0.
```
[INFO] Memory region 2048MiB@0x40000000
[INFO] Memory region 128000MiB@0x100000000
[INFO] Booting with FDT
[INFO] Found PCI device vendor=8086 device=d57 in slot=0
[INFO] Found PCI device vendor=1af4 device=1043 in slot=1
[INFO] Found PCI device vendor=1af4 device=1042 in slot=2
[INFO] Found PCI device vendor=1af4 device=1044 in slot=3
[INFO] PCI Device: 0:2.0 1af4:1042
[INFO] Bar: type=MemorySpace32 address=0x2ff80000 size=0x80000
[INFO] Bar: type=MemorySpace32 address=0x0 size=0x0
[INFO] Bar: type=MemorySpace32 address=0x0 size=0x0
[INFO] Bar: type=MemorySpace32 address=0x0 size=0x0
[INFO] Bar: type=MemorySpace32 address=0x0 size=0x0
[INFO] Bar: type=MemorySpace32 address=0x0 size=0x0
[INFO] Updated BARs: type=MemorySpace32 address=2ff80000 size=80000
[INFO] Updated BARs: type=MemorySpace32 address=0 size=0
[INFO] Updated BARs: type=MemorySpace32 address=0 size=0
[INFO] Updated BARs: type=MemorySpace32 address=0 size=0
[INFO] Updated BARs: type=MemorySpace32 address=0 size=0
[INFO] Updated BARs: type=MemorySpace32 address=0 size=0
[INFO] Virtio block device configured. Capacity: 4612096 sectors
[INFO] Found EFI partition
[INFO] Filesystem ready
[WARN] Error loading default entry: File(NotFound)
[INFO] Using EFI boot.
[INFO] Found bootloader: \EFI\BOOT\BOOTAA64.EFI
[INFO] Executable loaded
Failed to set MokListRT: Unsupported
TPM logging failed: Unsupported
Could not create MokListRT: Unsupported
Failed to set MokListXRT: Unsupported
TPM logging failed: Unsupported
Could not create MokListXRT: Unsupported
TPM logging failed: Unsupported
Could not create MokListTrustedRT: Unsupported
Something has gone seriously wrong: import_mok_state() failed: Unsupported
TPM logging failed: Unsupported
Could not create variable: Unsupported
Failed to set MokListRT: Unsupported
TPM logging failed: Unsupported
Could not create MokListRT: Unsupported
Failed to set MokListXRT: Unsupported
TPM logging failed: Unsupported
Could not create MokListXRT: Unsupported
TPM logging failed: Unsupported
Could not create MokListTrustedRT: Unsupported
Something has gone seriously wrong: import_mok_state() failed: Unsupported
TPM logging failed: Unsupported
```

**Comment by thomasbarrett** [comment]
Fixed by https://github.com/cloud-hypervisor/rust-hypervisor-firmware/pull/346
