### ISSUE TITLE
Question re: MemoryManager and arch_memory_regions()

### ISSUE THREAD

**Issue by ymjing** [cloud-hypervisor/cloud-hypervisor#6665]
Hi CHV team, I'm poking around and trying to understand how CHV manages guest memory.

At this moment I want to load two regions into guest memory:
1.  BIOS image - loaded at `0xFFE0_0000`; size = 0x20_0000 (reset vector located at `0xFFFF_FFF0`)
2. VMSA page - loaded at `0xFFFF_FFFF_F000`, size = 0x1000

For (1) the naive BIOS loader looks like [this](https://github.com/cloud-hypervisor/cloud-hypervisor/commit/8fa75aedfe5300ed7d01acf86160bcfea32a77ad#diff-9c91c6326e9d86ef107a59aed3f13a9bb91790f9f4be1668d22cda12a28bc28c)

But I get an error from MemoryManager that the address is not available.

So far I was able to get (1) working by adding the following to `src/x86_64/mod.rs:arch_memory_regions()` **AND** setting the guest mem to be larger than 4GB (`0xffe0_0000` is at the end of 4GB):
```rust
        (
            GuestAddress(0xffe0_0000), // RAM_64BIT_START - 2MB
            0x20_0000,                 // 2MB
            RegionType::Ram,
        ),
```

But this means I'd need 256TB guest memory for (2) to work. So probably `arch_memory_regions()` is not what I should modify. Please let me know the correct way to load data into guest memory

**Comment by likebreath** [comment]
What `arch_memory_regions()` defines is the common guest memory layout, where you can find  more details from `arch/x86_64/layout.rs`. IIUC, the two guest memory regions you want to add are not for general use cases, e.g. only for supporting loading and booting from certain firmware image. 

I'd suggest you allocate these two memory regions on the code path where you need to use them (say before you need to load the special firmware image) and guard it with appropriate feature gate. A good API to use for this purpose is: `vmm::memory_manager::MemoryManager::add_ram_region`. A good reference is  how memory regions are allocated for loading TDVF sections [1]. 

[1]  https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/vmm/src/vm.rs#L1823-L1839

**Comment by ymjing** [comment]
Thanks Bo; `add_ram_region` works well for me. Closing this for now.
