### ISSUE TITLE
Kernel building script in readme doesn't work

### ISSUE THREAD

**Issue by MrJackQiao** [cloud-hypervisor/cloud-hypervisor#6730]
**Describe the bug**
After running every command in [building you kernel](https://github.com/cloud-hypervisor/cloud-hypervisor?tab=readme-ov-file#building-your-kernel) in the readme, only `vmlinux` for x86 is present at `linux-cloud-hypervisor/arch/x86/boot/compressed/vmlinux.bin`. The `Image` kernel image for AArch64 is not present at `linux-cloud-hypervisor/arch/arm64/boot/Image`

**Environment**
OS: Ubuntu 22.04.3 LTS
Linux kernel: 6.8.0-40-generic
rustc 1.81.0 (eeb90cda1 2024-09-04)

**To Reproduce**
Follow every step in [building you kernel](https://github.com/cloud-hypervisor/cloud-hypervisor?tab=readme-ov-file#building-your-kernel) 

```bash
$ cp linux-config-x86_64 .config  # x86-64
$ cp linux-config-aarch64 .config # AArch64
# Do native build of the x86-64 kernel
$ KCFLAGS="-Wa,-mx86-used-note=no" make bzImage -j `nproc`
# Do native build of the AArch64 kernel
$ make -j `nproc`
```
Are those four commands ordered intentionally?

I have tried running the commands in the following order, but it didn't work either.
```bash
$ cp linux-config-x86_64 .config  # x86-64
# Do native build of the x86-64 kernel
$ KCFLAGS="-Wa,-mx86-used-note=no" make bzImage -j `nproc`
$ cp linux-config-aarch64 .config # AArch64
# Do native build of the AArch64 kernel
$ make -j `nproc`
```

**Comment by MrJackQiao** [comment]
Every command executes and returns no error. However, the AArch64 kernel image `Image` is not present at `linux-cloud-hypervisor/arch/arm64/boot/Image`, which, I think, should be generated by 
```bash
# Do native build of the AArch64 kernel
$ make -j `nproc`
```

**Comment by liuw** [comment]
You can try `find -name Image -type f` to see where it is. Keep in mind if you try to build an ARM64 kernel on an x86 build host, you need to configure your cross compilation tool chain correctly. There are numerous articles online on how to do that.
