### ISSUE TITLE
Potential block device performance regression from #6605

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#6738]
I noticed there is around 60% performance regression on the block device from a2438700e44880c2ce7980a8afd7ee33f1e91191 (#6605) as shown from our metrics CI graph [1]. More especially, the following tests are reporting performance regressions: `block_read_MiBps`, `block_write_MiBps`, `block_random_read_MiBps`, and `block_randowm_write_MiBps`.

[1] https://www.cloudhypervisor.org/metrics/

**Comment by liuw** [comment]
Is cbc940d2e2244a5e the culprit?

Azure has the L series VMs which expose NVMe drives.

**Comment by rbradford** [comment]
@likebreath Those graphs show an improvement in performance for that commit as higher is better - i.e. the throughput went up.

**Comment by likebreath** [comment]
> @likebreath Those graphs show an improvement in performance for that commit as higher is better - i.e. the throughput went up.

Aha. That's right. It is an improvements! That makes sense with the corresponding change.
