### ISSUE TITLE
Post 0.5 deprecated cleanup

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#678]
- [ ] "Lazy" cpu syntax
- [ ] `--vhost-user-blk` and related code
- [ ] `--vhost-user-net` and related code
- [ ] ~~Remove `vhost_user_blk` backend binary~~
- [ ] ~~Remove `vhost_user_net` backend binary~~

**Comment by rbradford** [comment]
@slp Are you okay with us removing the old binaries? You've been doing a lot of work around vhost-user-block so I thought you might be using that one.

**Comment by slp** [comment]
@rbradford Yes, we're using vhost_user_blk and vhost_user_fs (not vhost_user_net, at least for the moment), so it'd be really nice to be able to keep them.

**Comment by rbradford** [comment]
@slp okey dokey i've updated the items here.

**Comment by slp** [comment]
@rbradford Thanks!
