### ISSUE TITLE
test_tpm fails with updated Jammy image

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#6782]
After updating the jammy image test test_tpm test fails with the following message:

`VMM thread exited with error: Error rebooting VM: DeviceManager(CreateTpmDevice(Failed to create TPM Device : Init(Failed while initializing tpm Emulator: RunControlCmd(Control Cmd returned error code : 31))`

I'm disabling the test for now but @praveen-pk or @liuw are the experts on this who can fix.

**Comment by praveen-pk** [comment]
@rbradford, ack. I will handle this bug.

**Comment by praveen-pk** [comment]
By running the test manually, confirmed TPM device works fine on Jammy. This could be a test issue, digging further.

**Comment by rbradford** [comment]
> By running the test manually, confirmed TPM device works fine on Jammy. This could be a test issue, digging further.

Make sure you grab the updated image - which has e.g. new kernel etc and pair it with the version of the swtpm in the dev container.

**Comment by praveen-pk** [comment]
Found the issue:

While using latest Jammy image (jammy-server-cloudimg-amd64-custom-20241004-0.raw), I see:

```
EFI stub: ERROR: Failed to allocate usable memory for kernel.
EFI stub: ERROR: efi_relocate_kernel() failed!
EFI stub: ERROR: efi_main() failed!
VMM thread exited with error: Error rebooting VM: DeviceManager(CreateTpmDevice(Failed to create TPM Device : Init(Failed while initializing tpm Emulator: RunControlCmd(Control Cmd returned error code : 31))))
```

Above happens when guest start with **512M** memory. When started with **1024M** memory the guest progresses to boot.

Interestingly, the older jammy image (jammy-server-cloudimg-amd64-custom-20230119-0.raw) boots fine even while using 512M memory.

**Comment by rbradford** [comment]
Thanks for investigating this and figuring it out!
