### ISSUE TITLE
Drop musl toolchain support

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#6807]
Since it is now possible to build static binaries with the gnu toolchain the original motivation for supporting the musl build has been mitigated. In order to reduce the maintenance overhead (in particular complex issues like #6790) I would like to drop musl support.

Way forward:

- [ ] Obtain consensus - listen for objections
- [ ] For x86-64: Make CI builds for gnu toolchain use static builds
- [ ] For aach64: Switch CI to use gnu toolchain
- [ ] For aach64: Make CI builds with gnu toolchain use static builds
- [ ] Adjust release builds process to build static binaries using gnu toolchain
- [ ] Drop CI steps for musl

The static glibc release binary is ~4.8MiB unstripped.

**Comment by alyssais** [comment]
What does dropping support mean, exactly? Being able to build Cloud Hypervisor with musl is very important to me. I don't mind what's used for building the binaries distributed by the Cloud Hypervisor project, but it would be nice to keep it in CI if possible so to avoid it regressing…

**Comment by iggy** [comment]
Alpine (at least) wouldn't be able to support cloud-hypervisor if this happens. They require packages to be built in their CI system (i.e. can't just put the static binary in a package).

**Comment by phip1611** [comment]
> Since it is now possible to build static binaries with the gnu toolchain

Can you please elaborate, @rbradford? After a quick search on Google, Phoronix, and so on, I couldn't find anything. From experience, glibc makes trouble when linking it statically and there are technical hurdles along the way? Did that change, recently?

**Comment by rbradford** [comment]
> > Since it is now possible to build static binaries with the gnu toolchain
> 
> Can you please elaborate, @rbradford? After a quick search on Google, Phoronix, and so on, I couldn't find anything. From experience, glibc makes trouble when linking it statically and there are technical hurdles along the way (I mainly know this from stories being told)? Did that change recently?
> 
> All I can find is [this Rust PR from 2022](https://github.com/rust-lang/rust/pull/86374). I'm confused over your "now 
possible"

Try it for yourself! I think it was enabled some time in 2020

```
$ mkdir -p .cargo; echo -e '[build]\nrustflags = ["-C", "target-feature=+crt-static"]\ntarget = "x86_64-unknown-linux-gnu"' > .cargo/config.toml; cargo build --target x86_64-unknown-linux-gnu;
$ ldd target/x86_64-unknown-linux-gnu/debug/cloud-hypervisor`
	statically linked
```

**Comment by rbradford** [comment]
It sounds like there is still value in keeping the musl support - it was originally added to provide for static binaries but it looks like it is being used beyond that. Thanks everyone for the feedback!
