### ISSUE TITLE
I want to build CLH but don't rust good

### ISSUE THREAD

**Issue by egernst** [cloud-hypervisor/cloud-hypervisor#682]
To facilitate building the latest cloud-hypervisor, it would be helpful to have an option to build the VMM from within a container environment, to avoid the need to create a rust development environment and aid in reproducible builds.

Is this on the roadmap? 

For my particular scenario, I want to quickly make a dev build (not --release, which AFAIU includes debug symbols).

Thanks folks!

**Comment by sameo** [comment]
I am working on a container for building the project, but (more importantly to me at least) running our integration and unit tests.
