### ISSUE TITLE
Add support for building kernel in CI scripts

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#6834]
@rbradford It seems like CH v42 is now downloading the guest kernel instead of building it. Should we add the mechanism to tell CH test framework whether it need to build it or use the pre-compiled binaries

I need to enable some kernel config for kernel crash to work and generate dump file.

Something like, 

To build guest kernel
`./scripts/dev_cli.sh tests --hypervisor mshv --build_guest_kernel --integration -- -- --exact common_parallel::test_kernel_crash_dump`

To Use precompiled binaries
`./scripts/dev_cli.sh tests --hypervisor mshv --integration -- -- --exact common_parallel::test_kernel_crash_dump`

CC @jinankjain

_Originally posted by @smit-gardhariya in https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6726#issuecomment-2464203792_

**Comment by rbradford** [comment]
@TimePrinciple - did you want to tackle this?

**Comment by TimePrinciple** [comment]
> @TimePrinciple - did you want to tackle this?

Noted, I will take care of this 👌
