### ISSUE TITLE
Containerized build and tests

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#684]
Reproducing our CI locally can be painful and erratic as it's designed to be running on top of a specific version of Ubuntu.
We should build and maintain a dedicated container for that purpose.

## Goals

* Use the container to build the cloud-hypervisor artifacts (cloud-hypervisor binaries and CI dependencies)
* Use the container to run the CI locally

### Longer term
 * Run the CI through this container

which means we have to find a way to automatically update the container.

**Comment by sameo** [comment]
cc @egernst

**Comment by egernst** [comment]
FYI: https://github.com/kata-containers/packaging/blob/master/static-build/cloud-hypervisor/docker-build/build.sh
