### ISSUE TITLE
cloud-hypervisor edk2 fork has broken submodule links

### ISSUE THREAD

**Issue by maburlik** [cloud-hypervisor/cloud-hypervisor#6841]
**Describe the bug**
Latest cloud-hypervisor edk2 fork tag from Jan 2024 no longer builds due to outdated submodule url.

Tags:
https://github.com/cloud-hypervisor/edk2/tags

Please see:
https://github.com/tianocore/edk2/commit/95d8a1c255cfb8e063d679930d08ca6426eb5701

More context:
https://github.com/tianocore/edk2/issues/6398

Could you please create a new tag that contains this fix?

**Comment by TimePrinciple** [comment]
Hi there! 

How can I help with this, which tag should we update to 🤔

**Comment by maburlik** [comment]
> Hi there!
> 
> How can I help with this, which tag should we update to 🤔

Hello @TimePrinciple. It looks like latest edk2 already has the fix:
https://github.com/tianocore/edk2/commit/95d8a1c255cfb8e063d679930d08ca6426eb5701

To get past this, need to consume the latest edk2 and apply the cloud-hypervisor supplementary change against the head, produce the new tag.

**Comment by TimePrinciple** [comment]
> > Hi there!
> > How can I help with this, which tag should we update to 🤔
> 
> Hello @TimePrinciple. It looks like latest edk2 already has the fix: [tianocore/edk2@95d8a1c](https://github.com/tianocore/edk2/commit/95d8a1c255cfb8e063d679930d08ca6426eb5701)
> 
> To get past this, need to consume the latest edk2 and apply the cloud-hypervisor supplementary change against the head, produce the new tag.

Noted, maybe we need advice from @rbradford , I've gong through the git history of current `cloud-hypervisor/edk2`, I have difficulty in determining which are `cloud-hypervisor supplementary chage`.

**Comment by maburlik** [comment]
> > > Hi there!
> > > How can I help with this, which tag should we update to 🤔
> > 
> > 
> > Hello @TimePrinciple. It looks like latest edk2 already has the fix: [tianocore/edk2@95d8a1c](https://github.com/tianocore/edk2/commit/95d8a1c255cfb8e063d679930d08ca6426eb5701)
> > To get past this, need to consume the latest edk2 and apply the cloud-hypervisor supplementary change against the head, produce the new tag.
> 
> Noted, maybe we need advice from @rbradford , I've gong through the git history of current `cloud-hypervisor/edk2`, I have difficulty in determining which are `cloud-hypervisor supplementary changes`.

My understanding of the maintenance loop of this fork is that the latest head is taken from tianocore edk2, and this commit is cherry-picked on top of the head:
https://github.com/cloud-hypervisor/edk2/commit/ffab6553e9ff58add699cacced01d7f2e2339983

@rbradford do you have an idea when this may be possible to check in? Or should I create my own fork?

**Comment by rbradford** [comment]
This is done now!
