### ISSUE TITLE
[Feature request] VLAN bridging to a VLAN aware bridge

### ISSUE THREAD

**Issue by RaitoBezarius** [cloud-hypervisor/cloud-hypervisor#6856]
I'd like to make use of VLAN aware bridges (https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-42/Layer-2/Ethernet-Bridging-VLANs/VLAN-aware-Bridge-Mode/) and decide the VLAN on the `--net tap,vlan=xyz` like QEMU provides.

I'm not exactly sure what does it entail and if this is feasible, but this would be a great feature to ease the transition from QEMU to here.

**Comment by liuw** [comment]
Can you give me an example? It seems to me QEMU used to have a vlan option, but it has been removed. That `vlan` option doesn't do what people think it does.

Quoting `docs/about/removed-features.rst`

```
``-net ...,vlan=x`` (removed in 3.0)
''''''''''''''''''''''''''''''''''''

The term "vlan" was very confusing for most users in this context (it's about
specifying a hub ID, not about IEEE 802.1Q or something similar), so this
has been removed. To connect one NIC frontend with a network backend, either
use ``-nic ...`` (e.g. for on-board NICs) or use ``-netdev ...,id=n`` together
with ``-device ...,netdev=n`` (for full control over pluggable NICs). To
connect multiple NICs or network backends via a hub device (which is what
vlan did), use ``-nic hubport,hubid=x,...`` or
``-netdev hubport,id=n,hubid=x,...`` (with ``-device ...,netdev=n``) instead.
```

**Comment by RaitoBezarius** [comment]
Heh, I think I am wrong. Putting a VLAN on a tap is a matter of using `iproute2` and I assume this would work transparently after that. Closing in the meantime.
