### ISSUE TITLE
vfio: Support PCI extended configuration space

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#716]
We need to investigate how complex it would be to support exposing the Extended Capabilities from PCI configuration space.
Right now, if passing a PCI device with extended caps like these:
```
        Capabilities: [100 v1] Advanced Error Reporting
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP+ SDES- TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF+ MalfTLP+ ECRC- UnsupReq- ACSViol-
                CESta:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr-
                CEMsk:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr+
                AERCap: First Error Pointer: 00, GenCap- CGenEn- ChkCap- ChkEn-
        Capabilities: [140 v1] Device Serial Number 68-05-ca-ff-ff-15-84-5c
```
we cannot find them from the guest.

I observed the guest is not even trying to access the PCI config space over `0x100` which is the start of the extended caps list. This might mean that Linux won't even try to access anything over this offset since the device is not attached to a PCIe root complex.

**Comment by chao-p** [comment]
To enable guest to access >0x100 bytes, MMCFG needs to be presented.

**Comment by sboeuf** [comment]
>To enable guest to access >0x100 bytes, MMCFG needs to be presented.
@chao-p could you elaborate on that?

FYI, we already have an MCFG table allowing for MMIO access of the PCI config space.

**Comment by chao-p** [comment]
> > To enable guest to access >0x100 bytes, MMCFG needs to be presented.
> > @chao-p could you elaborate on that?
> 
> FYI, we already have an MCFG table allowing for MMIO access of the PCI config space.

OK, I'm not aware that. Extended caps reside in space>0x100 and can only be accessed through MMIO.

**Comment by sboeuf** [comment]
>OK, I'm not aware that. Extended caps reside in space>0x100 and can only be accessed through MMIO.

Yes I know they are placed after the offset `0x100`, but I traced the MMIO traps and I don't see the guest trying to access the PCI config space after `0x100`.
That's why I think something is missing from a guest perspective. Is it because we don't use a RootComplex (we have a PCI host bridge) that the guest won't even try to access potential extended caps?

**Comment by chao-p** [comment]
> > OK, I'm not aware that. Extended caps reside in space>0x100 and can only be accessed through MMIO.
> 
> Yes I know they are placed after the offset `0x100`, but I traced the MMIO traps and I don't see the guest trying to access the PCI config space after `0x100`.
> That's why I think something is missing from a guest perspective. Is it because we don't use a RootComplex (we have a PCI host bridge) that the guest won't even try to access potential extended caps?

Different caps have different condition check before performing the configuration access. If it's AER capability as showed above, I see no condition, but you say you did not see the trap, that sounds interesting. Is it because we wrongly set not to trap MMIO for MCFG?

**Comment by sboeuf** [comment]
>Different caps have different condition check before performing the configuration access. If it's AER capability as showed above, I see no condition, but you say you did not see the trap, that sounds interesting. Is it because we wrongly set not to trap MMIO for MCFG?

Well I can see MMIO accesses to the PCI config space, but it never goes past 0x100. That's why I'm thinking the guest is not even trying.
