### ISSUE TITLE
Provide commit ID version information

### ISSUE THREAD

**Issue by jcvenegas** [cloud-hypervisor/cloud-hypervisor#729]
When using `cloud-hypervisor` in master branch would be great to know what is the version that I am using specially because I will see always the same version (the last in the bump) but actually is the latest release + an offset 

What I would like to see is:
```
./cloud-hypervisor --version
cloud-hypervisor 0.5.0 commit adsfas9f8dsf213
```

**Comment by sameo** [comment]
@likebreath Do you think you could look at that issue?

**Comment by likebreath** [comment]
> @likebreath Do you think you could look at that issue?

Of course. Thanks for letting me know. @sameo
