### ISSUE TITLE
vhost-user backends should relisten

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#732]
After losing the connection between the VMM and the backend the backend should relisten unless `exit_on_disconnect=true` is provided to the backend.

**Comment by sboeuf** [comment]
Based on the discussion [here](https://patchwork.kernel.org/patch/11375813/), vhost-user maintainers expect the backend's lifetime to match the VM's lifetime, but if the VMM disconnect from the socket, the backend will simply terminate.
So if we really want to support rebooting with vhost-user backend attached to our VMM, we should investigate how we could maintain the socket connection over reboot.
/cc @rbradford

**Comment by rbradford** [comment]
If we add this option it makes virtio-fs (using our backend) useful with VMs that need to reboot.

**Comment by sboeuf** [comment]
Oh yes we can definitely change our virtio-fs Rust backend so that it supports an extra option `--keep-listening`.

**Comment by rbradford** [comment]
I don't think we're going to make this change.
