### ISSUE TITLE
Port codebase over latest vm-memory refactor

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#735]
Move Cloud-Hypervisor code to rely onto the latest vm-memory PR: https://github.com/rust-vmm/vm-memory/pull/68

**Comment by bonzini** [comment]
Do you have a corresponding `vm-virtio` issue already? In the last version of rust-vmm/vm-memory#68 I have also added GuestMemoryBackend which should also make all the generics in virtio more concise.

**Comment by sboeuf** [comment]
No I don't but the point is to showcase this is gonna work with CH, and then we'll try to push this to vm-virtio.
