### ISSUE TITLE
Can not use an already created TAP

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#738]
When starting Cloud Hypervisor, we may want to pass it an already created TAP interface:

```
# sudo ip tuntap add name ich0 mode tap multi_queue
```

And then:

```
$ ./cloud-hypervisor/target/release/cloud-hypervisor \
	--kernel ./hypervisor-fw \
	--disk path=clear-31890-kvm.img \
	--cpus boot=4 \
	--memory size=1024M \
	--net tap=ich0 \
	--rng
```

That fails with:

```
VM: VmBoot(DeviceManager(CreateVirtioNet(OpenTap(TapOpen(CreateTap(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))))))
```

**Comment by jsastriawan** [comment]
Thanks for accommodating our request. Joko

**Comment by sboeuf** [comment]
I investigated this issue and here is the explanation.
First thing, if your tap interface does not have the `multi_queue` option:
```
# sudo ip tuntap add name ich0 mode tap
```
the VM starts properly as expected.

Second thing, in case you do want `multi_queue` for your tap interface, it is a matter of letting the device know that you created a multiqueue TAP with the following option:
```
--net tap=ich0,num_queues=4
```
In this case I took the simple example of 4 queues, which means 2 pairs of TX/RX queues.

Let me know if that solves the issue for you, and please close the issue if it does.

**Comment by jsastriawan** [comment]
Would you update the documentation on pre-configured tap for both multi_queue and without multi_queue too? Just to make sure end user will be able to use the correct tap instatiation options for the right --net options.

**Comment by sboeuf** [comment]
@jsastriawan yes let me add that to the PR.
