### ISSUE TITLE
vhost-user-net backend needs to support using existing tap interface

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#742]
And we need to do the same checks that the virtio-net backend does: #741

**Comment by rbradford** [comment]
I just tested this and this does work so I simply misread the code.

**Comment by rbradford** [comment]
I was wrong again, it just silently accepts the argument and then ignores it and creates a new interface with it's own name.

**Comment by bjzhjing** [comment]
I add patches in local branch, but cargo build could not complete for it's failed to connect to github.com, network error, will try it tomorrow or next week.
