### ISSUE TITLE
test_vfio test stability and performance

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#753]
This test was moved from the main test run to being run on it's own afterwards with the result being ignored (see #749) as it was proving flaky when run on the agents.

It currently takes 5m32 to run which is very long (for context the rest of the tests take 7m35 to complete.)

Need to look at ways to improve the test performance and reliability.

**Comment by rbradford** [comment]
Currently the tests use a DAX virtiofs filesystem to store the rootfs in ~/workloads/vfio (which on Azure happens to be a slow disk vs the tmpfs.)

We should try moving the vfio workloads directory to /tmp and see if that improves things. 

If it does we could go one step further and add a second disk to the L1 and then pass that block device through as a block device. We could even go even further and try and use VFIO to pass the root in bypassing the L1 kernel.

**Comment by sboeuf** [comment]
@rbradford one way I know to improve this test is by using `hugepages`. This highly improves the boot time, especially for the L2 VM.

**Comment by sboeuf** [comment]
@rbradford I think we can close this now.

**Comment by rbradford** [comment]
Yup i'm pretty happy things are stable now!
