### ISSUE TITLE
vhost_user::connection::tests::create_listener randomly fails

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#759]
Based on https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/job/cloud-hypervisor/job/PR-756/4/ and https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/job/cloud-hypervisor/job/PR-756/6/, we can see the unit test vhost_user::connection::tests::create_listener randomly, causing the CI to fail (even when the PR has nothing to do with this).

**Comment by sboeuf** [comment]
Ok so basically the first thing is that we run our unit tests multi-threaded since this is the default for `cargo test` . Based on this, we have both `create_listener()` and `accept_connection()` tests being run in parallel. They don't use the same socket path, so no problem there, the issue is way more sneaky than that. Because these two tests run through two threads from the same process, they share the file descriptors.
Now look at `accept_connection()` [here](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vhost_rs/src/vhost_user/connection.rs#L519-L522). It does close manually a file descriptor by invoking the `unsafe libc::close()` function. That means it can close randomly, any other file descriptor being used by other threads.
When the concurrency between the threads makes the `create_listener()` run simultaneously with `accept_connection()`, there's a case where the file descriptor given to `create_listener()` to bind to is the same as the file descriptor that is manually closed. When the fd is closed before the bind happens, the bind simply fails with `-EBADF `.
Here is the log I have from the `strace` I ran while it failed https://gist.github.com/sboeuf/50a5e7f63e1694326308e9d9796644d8

**Comment by sboeuf** [comment]
Now, if my understanding is correct, that means we can simply remove the part where the fd is closed manually. But I wanted some feedback because it seems this is the kind of issue we might run into in the future and I'd like to make sure we don't spend too much time doing that since it's "only" unit tests. So I think it'd be better if we were running these tests single threaded it is barely slower than multithreaded.

**Comment by rbradford** [comment]
I would recommend just deleting this bit of the test, not sure it is really that interesting or valuable: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vhost_rs/src/vhost_user/connection.rs#L519-L524
