### ISSUE TITLE
Risk of memory overcommit

### ISSUE THREAD

**Issue by liubogithub** [cloud-hypervisor/cloud-hypervisor#763]
The current `make_virtio_fs_devices` is using `MmapRegion` to provide a mmap, but `MmapRegion` is using `PROT_READ|PROT_WRITE`, which means guest could fault in pages whenever they want.

[make_virtio_fs_devices](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vmm/src/device_manager.rs#L1095)
```        
fn make_virtio_fs_devices(&mut self) -> DeviceManagerResult<Vec<(VirtioDeviceArc, bool)>> {
   ...             
   let mmap_region = MmapRegion::new(fs_cache as usize)
                            .map_err(DeviceManagerError::NewMmapRegion)?;
                        let addr: u64 = mmap_region.as_ptr() as u64;
```

However, this is different from how qemu handles it, [vuf_device_realize](https://gitlab.com/virtio-fs/qemu/-/blob/virtio-fs-dev/hw/virtio/vhost-user-fs.c#L501)
```
static void vuf_device_realize(DeviceState *dev, Error **errp) 
{
...
    if (fs->conf.cache_size) {
        /* Anonymous, private memory is not counted as overcommit */
        cache_ptr = mmap(NULL, fs->conf.cache_size, PROT_NONE,
                         MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
        if (cache_ptr == MAP_FAILED) {
            error_setg(errp, "Unable to mmap blank cache");
            return;
        }

        memory_region_init_ram_ptr(&fs->cache, OBJECT(vdev),
                                   "virtio-fs-cache",
                                   fs->conf.cache_size, cache_ptr);
    }
```

As the comment mentioned, overcommit is avoided by using PROT_NONE.

@sboeuf

**Comment by sboeuf** [comment]
@liubogithub you're right, using `PROT_NONE` would be safer. And it's only when the guest ask for reading some files that the VMM (on behalf of the backend) would `mmap()` some specific pages as `PROT_READ` and/or `PROT_WRITE`.

The fix has to be submitted to the `rust-vmm/vm-memory` repo. Do you want to take care of this?

**Comment by sboeuf** [comment]
@liubogithub I opened https://github.com/rust-vmm/vm-memory/issues/74 to get some feedback before we decide to proceed further.

**Comment by liubogithub** [comment]
Thanks for fixing it promptly.
