### ISSUE TITLE
Make "vhost_user=true" default for --net/--disk/--fs

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#775]
At some point in the future we should turn this on by default.

**Comment by sboeuf** [comment]
@rbradford I agree but we need to be on parity with virtio-net/blk backends.
We can already do it for `--fs`.

**Comment by rbradford** [comment]
Yes there are lots of feature gaps so this is just to track to remember to do it in the future.

**Comment by rbradford** [comment]
Do we still think we should do this? I'm not so sure now.

**Comment by sboeuf** [comment]
If @sameo is fine with it, let's close this.
