### ISSUE TITLE
Replace all use of RwLock with Mutex

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#777]
On Linux (release builds) `Mutex<T>`  always outperforms `RwLock<T>`:

See https://www.slideshare.net/mitsunorikomatsu/performance-comparison-of-mutex-rwlock-and-atomic-types-in-rust slide 13

**Comment by slp** [comment]
The paper is interesting, but I'd say its conclusion only applies when the critical section is extremely small, as it is in the paper's benchmark. When the critical section is significant in length, and especially if it contains syscalls, the cost of lock management should be mostly irrelevant in comparison. The pressure on the lock and the proportion of reader vs. writers should also be considered.

To further illustrate this point, I modified the benchmark referenced in the paper to include a syscall in the critical section [1]. Running this one, we can see RwLock wins in every scenario, except in the zero readers one (a situation where using RwLock would be pointless) where we have a tie (the difference is much lower than the deviation):
```
==== num_reader: 20, num_writer: 0 ====
mutex    =>   mean:   249.57, std_dev:     8.10
rwlock   =>   mean:    45.00, std_dev:     1.00

==== num_reader: 19, num_writer: 1 ====
mutex    =>   mean:   257.00, std_dev:     9.42
rwlock   =>   mean:    56.29, std_dev:     2.75

==== num_reader: 18, num_writer: 2 ====
mutex    =>   mean:   255.86, std_dev:     7.24
rwlock   =>   mean:    75.71, std_dev:     6.07

==== num_reader: 16, num_writer: 4 ====
mutex    =>   mean:   258.57, std_dev:     8.54
rwlock   =>   mean:    87.00, std_dev:     3.83

==== num_reader: 12, num_writer: 8 ====
mutex    =>   mean:   257.00, std_dev:     5.83
rwlock   =>   mean:   125.43, std_dev:     4.83

==== num_reader: 8, num_writer: 12 ====
mutex    =>   mean:   250.00, std_dev:     6.83
rwlock   =>   mean:   170.71, std_dev:     4.75

==== num_reader: 4, num_writer: 16 ====
mutex    =>   mean:   252.29, std_dev:     4.35
rwlock   =>   mean:   218.29, std_dev:     8.56

==== num_reader: 0, num_writer: 20 ====
mutex    =>   mean:   259.57, std_dev:     8.54
rwlock   =>   mean:   259.71, std_dev:     3.55
```

[1] https://github.com/slp/rust-lock-bench.git

**Comment by rbradford** [comment]
Thanks @slp. So looks like we need to maybe switch some of our `Mutex<T>`s to `RwLock<T>`s where we are in a situation with syscalls in our critical sections. For now i'll close this issue though.
