### ISSUE TITLE
virtio-fs: Fill gaps for vhost-user-fs backend in Rust

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#779]
As part of Cloud-Hypervisor project, we started implementing vhost-user backends in Rust. In case of virtio-fs (vhost-user-fs), the official backend maintained by the maintainers is `virtiofsd`, and there are still some gaps before we can switch to the new Rust backend as the default.

List of gaps to address:
- [x] Implement DAX support with `map()`/`unmap()` (will be merged soon with #698)
- [x] Implement `sync()`
- [x] Implement `fs_io`
- [x] Support mount namespace and pivot root (isolation of what the backend can access on the host)

**Comment by slp** [comment]
I think another missing piece is providing the same command line arguments, so it can be really used as a drop-in replacement. I intend to work on this soon.

Probably, there'll be some other minor gaps that will pop up when users start testing it, but those are hard to list in advance.

**Comment by dagrh** [comment]
I've just added a seccomp pull (based on slp's sandboxing pull)
 https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1104/
