### ISSUE TITLE
Add "poll_queue" to --disk

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#787]
For `vhost_user=true` this should be passed through to the backend being invoked otherwise it should be used for virtio-block. Depends on #786

**Comment by rbradford** [comment]
CC @slp

**Comment by slp** [comment]
@rbradford I'm looking into this. Which properties from `DiskConfig` should appear in `cloud-hypervisor.yaml`? I see some of them are there while others don't, but can't find a pattern...

**Comment by rbradford** [comment]
@slp they should carry the same see #791 ?
