### ISSUE TITLE
15M (0x100000 - 0x1000000) Guest memory may be wasted when running customer kernel

### ISSUE THREAD

**Issue by uMartinXu** [cloud-hypervisor/cloud-hypervisor#803]
When running Cloud-hypervisor with the customized Linux kernel according to Cloud-hypervisor readme, the kernel image was loaded to 0x1000000 by default, which means the 15M (0x100000 - 0x1000000) Guest memory may be wasted. Since Cloud-hypervisor doesn't support the traditional x86 ISA device which uses the memory for DMA.  

According to the comments in code
https://github.com/rust-vmm/linux-loader/blob/master/src/loader/mod.rs: line 257

// if the vmm does not specify where the kernel should be loaded, just
// load it to the physical address p_paddr for each segment.

vmm in Cloud-hypervisor doesn't specify where the kernel should be loaded. see below code in https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vmm/src/vm.rs: line394

        let entry_addr = match linux_loader::loader::Elf::load(
            mem.deref(),
            None,
            &mut self.kernel,
            Some(arch::layout::HIGH_RAM_START),
        )  

using below command to check the p_paddr for each segment
Notes: vmlinux.bin is built according to cloud-hypervisor readme. 

readelf -l –segments vmlinux.bin​

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000200000 0xffffffff81000000 0x0000000001000000
                 0x0000000000e1d358 0x0000000000e1d358  R E    0x200000
  LOAD           0x0000000001200000 0xffffffff82000000 0x0000000002000000
                 0x0000000000095000 0x0000000000095000  RW     0x200000
  LOAD           0x0000000001400000 0x0000000000000000 0x0000000002095000
                 0x0000000000024000 0x0000000000024000  RW     0x200000
  LOAD           0x00000000014b9000 0xffffffff820b9000 0x00000000020b9000
                 0x0000000000d47000 0x0000000000d47000  RWE    0x200000
  NOTE           0x000000000101d304 0xffffffff81e1d304 0x0000000001e1d304
                 0x0000000000000054 0x0000000000000054         0x4

the text segments start from 0x1000000(16M) by default

That means the custom kernel will be loaded by Cloud Hypervisor to 0x1000000 by default.

Kernel ELF image text segment p_paddr is decided by kernel configuration
CONFIG_PHYSICAL_START
which is 0x1000000 by default. 

To fix the issue, we can change the kernel configuration 
CONFIG_PHYSICAL_START​
or we can specify kernel load address when calling
linux_loader::loader::Elf::load() in vmm

**Comment by rbradford** [comment]
I agree that the kernel gets loaded at 16MiB. But i've compared the contents of /proc/meminfo and see no difference so why is this a problem?

**Comment by rbradford** [comment]
Even with a kernel with a start address of 0x1000000 the kernel relocates itself and runs from 0x100000

See /proc/iomem

```00100000-3fffffff : System RAM
  01000000-01a01d00 : Kernel code
  01c00000-01e7bfff : Kernel rodata
  02000000-020ac7bf : Kernel data
  02225000-027fffff : Kernel bss


```

**Comment by uMartinXu** [comment]
> Even with a kernel with a start address of 0x1000000 the kernel relocates itself and runs from 0x100000
> 
> See /proc/iomem
> 
> ```
>   01000000-01a01d00 : Kernel code
It is still 16M. :)

**Comment by uMartinXu** [comment]
I also checked again and my kernel is not relocated to 1M, still 16M. :)

> I agree that the kernel gets loaded at 16MiB. But i've compared the contents of /proc/meminfo (with a kernel start address of 1MiB vs 16MiB) and see no difference so why is this a problem?
The potential problem is:
If you boot the kernel with limited memory, it may fail, since the bottom 15m memory is not used.  

Besides, I am afraid that this area of memory may not actually be used by Kernel as other normal memory.  According to
https://lwn.net/Articles/753273/
Looks like this area of memory was used by DMA operation by some legacy ISA bus.
I Need deep dive on it.  Not a kernel memory management expert :)

**Comment by rbradford** [comment]
> > Even with a kernel with a start address of 0x1000000 the kernel relocates itself and runs from 0x100000
> > See /proc/iomem
> > ```
> >   01000000-01a01d00 : Kernel code
> > ```
> 
> It is still 16M. :)

Oh yeh :-)

**Comment by rbradford** [comment]
> The potential problem is:
> If you boot the kernel with limited memory, it may fail, since the bottom 15m memory is not used.

So the problem statement is that you're trying to use a VM with <= 16MiB ram?

**Comment by uMartinXu** [comment]
You are right. Actually, I am trying to evaluate the memory overhead of Cloud Hypervisor. And try to figure what is the smallest Guest memory the VM needs to boot a Kernel. I worked out a small kernel Image(vmlinux.bin) which is about 2-3M and found that if I set the Guest Memory less then 16M, it always fail when loading the image into Guest memory. Since the boottom 15M memory is not used. :)

**Comment by sboeuf** [comment]
@rbradford is there a technical reason why we don't specify the default kernel start address as `0x100000`?
Just asking because if that's something easy and doable, sounds like we should do it.

**Comment by rbradford** [comment]
@sboeuf We can easily change the .config. Changing the address we use in the VMM needs linux-loader being fixed: https://github.com/rust-vmm/linux-loader/issues/12

**Comment by sboeuf** [comment]
@rbradford can you think of a single reason why we shouldn't go with 1M as the default?

**Comment by rbradford** [comment]
@sboeuf I think our default kernel configuration should have "normal" or even "recommended" defaults. As I look through I this I see we don't have KASLR on which is something we should actually turn on.

If someone wants to run CH with a tiny amount of ram for the VM (like 16MiB) they're going to have to tweak not only the CH defaults (1024 entry virtio queues will use up a lot of RAM) but also the kernel.

I don't actually see a legitimate issue here just that when @uMartinXu changed his kernel configuration to make it small he omitted to change the base

**Comment by sboeuf** [comment]
@uMartinXu based on @rbradford 's feedback, do you think we can now close this issue?

**Comment by uMartinXu** [comment]
Actually, using the customer kernel, the user can adjust CONFIG_PHYSICAL_START to decide the start address. So I am OK to close it. 

But I am still not persuaded by the reason why we have to use 16M as the default start address.
Even after I go through the kernel configure comments about CONFIG_PHYSICAL_START.

Anyway, thanks for your comments. :)
