### ISSUE TITLE
Calling /vmm/shutdown on a paused VM freezes all subsequent API calls

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#817]
Steps to reproduce:

1. `PUT 'http://localhost/api/v1/vm.create'`
1. `PUT 'http://localhost/api/v1/vm.boot'`
1. `PUT 'http://localhost/api/v1/vm.pause'`
1. `PUT 'http://localhost/api/v1/vmm.shutdown'`

The last step fails, i.e. the VMM does not seem to be down (The process is still running).
However the VMM will not reply to any subsequent API call.

**Comment by russell-islam** [comment]
@likebreath I was planning to look into this issue. Do you have any findings so far?

**Comment by likebreath** [comment]
@russell-islam Thanks for your interest on looking into this issue.  I haven't devoted much time on this issue (mainly looked into the stack trace a bit). No big findings so far. I will come back to this issue later this week (around Thursday).

This bug should be easily reproduced. Please go ahead and look deeper into this issue. Any questions or updates, please don't hesitate to share. :)

**Comment by russell-islam** [comment]
@likebreath  I was investigating more into this. I am having progress. I will keep updated the findings soon. Please feel free to look other bugs, I will take care of this one.

**Comment by likebreath** [comment]
@russell-islam Sounds great. Look forward to your PR. Thanks a lot.
