### ISSUE TITLE
Add readonly mode to virtio-pmem

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#827]
It would be nice to be able to open the backing file for virtio-pmem read only. This need CLI and config struct changes as well as opening the file read only.

**Comment by rbradford** [comment]
There is no "readonly" flag in virtio-pmem itself so for correct functioning the filesystem that is mounted from pmem would need to be "ro"

**Comment by sboeuf** [comment]
@rbradford 
>There is no "readonly" flag in virtio-pmem itself so for correct functioning the filesystem that is mounted from pmem would need to be `ro`

Yes exactly, I checked on my side too, but there's no virtio `readonly` feature... So we really need to make sure our virtio-pmem backend opens the backing file as read only.
I mean to say, we need the kernel command line to include `ro`, but this is not enough if we think the guest can take control of the kernel, so we should ensure that our backend also doesn't open the file with incorrect permissions.

Therefore, even if not supported by `virtio-pmem`, we should introduce a new `readonly` option.

**Comment by rbradford** [comment]
We now have a "discard_writes" option which has a similar effect to making it read only.
