### ISSUE TITLE
Factorize internal API code

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#828]
We mostly handle 3 sort of internal API commands:

1. No payload for both input and output, this is the so-called VM action commands (e.g. `VmBoot`, `VmPause`, etc).
2. Single input payload, no output payload, e.g. `VmCreate` or `VmResize`.
3. No input, single payload output, e.g. `VmInfo`

For each of those 3 patterns, we should have e.g. macros to factorize all the common code.

**Comment by rbradford** [comment]
I think we can close this. The API code isn't perfect but there is nothing actionable here and the code has changed a bit since this was written up.
