### ISSUE TITLE
[not a 'issue', but discussion]Any plans or tracks on ARM support? 

### ISSUE THREAD

**Issue by crystaldust** [cloud-hypervisor/cloud-hypervisor#831]
Hi, community, I see there are some commits about ARM, is there any plans or tracks like what rust-vmm did on ARM support(https://github.com/rust-vmm/kvm-ioctls/issues/8)? We've got some ARM servers and would like to try cloud-hypervisor on them. If there is something track on 'what is missing on ARM', that would be helpful for us to make some implementations and maybe contribute it back to the community.

**Comment by sboeuf** [comment]
Hi @crystaldust , thanks for you interest in cloud-hypervisor! We don't have a clear roadmap regarding the support for ARM, but you're more than welcome to contribute some patches to make this happen :)

**Comment by crystaldust** [comment]
Thanks @sboeuf I'll first try to build cloud-hypervisor on ARM devices and see what is missing, then maybe we can figure out a list or plan on ARM support, closing the issue.
