### ISSUE TITLE
load_kernel() cleanup

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#885]
The `load_kernel()` function loads the kernel and its commandline, but also calls into `configure_system()` for setting a few platform specific items (zero page, e820 table, mptable, etc).
It would be cleaner if we could decouple the system configuration part from the kernel+cmdline loading one. It would allow us e.g. to load initramfs images without having to embed it into `load_kernel()` as those 2 operations are not related.

**Comment by andreeaflorescu** [comment]
This seems related to: https://github.com/rust-vmm/linux-loader/issues/15

**Comment by rbradford** [comment]
After removing support for ! CONFIG_PVH this code can be simplified.

**Comment by rbradford** [comment]
I've reviewed the code after the removal of the non-PVH code and I think this a lot cleaner.
