### ISSUE TITLE
vhost-user-fs: implement method to handle VHOST_USER_SLAVE_FS_IO request

### ISSUE THREAD

**Issue by eryugey** [cloud-hypervisor/cloud-hypervisor#892]
As described in https://github.com/cloud-hypervisor/vhost/issues/10 , currently vhost-user-fs device is unable to handle VHOST_USER_SLAVE_FS_IO request.

This is the qemu commit that implements this function
https://gitlab.com/virtio-fs/qemu/commit/6a1016b7d2253e8f2f5f62e0b845b2389be22bd2

**Comment by sboeuf** [comment]
Thanks for opening this issue @eryugey 
If you're working on it, please let me know, I'll assign the issue to you.

**Comment by liubogithub** [comment]
I'll look into it.

**Comment by liubogithub** [comment]
the pr #916 is only for vhost-user-fs backend, FS_IO support for virtiofs rust daemon will be a separate one.
