### ISSUE TITLE
vhost-user-blk: backend does not exit while guest shutdown

### ISSUE THREAD

**Issue by bjzhjing** [cloud-hypervisor/cloud-hypervisor#894]
Trying with master branch, start guest by connecting to vhost_user_blk backend. Then, issue command: shutdown -h now, guest quit, but the vhost_user_blk backend process is still running there.

**Comment by rbradford** [comment]
I just tested this with master works for me.

**Comment by bjzhjing** [comment]
I pull to the latest master, try it again, the issue still there. 
Here is the command I used to start vhost_user_blk backend.
```
./cloud-hypervisor/target/release/vhost_user_blk \
        --block-backend "image=/root/test,sock=/tmp/vublk.sock,num_queues=1,rdonly=false,direct=false"
```
Here is the disk parameter to start guest
```
--disk "path=/home/cathy/clear-31890-kvm.img,vhost_user=true,num_queues=1,queue_size=128,wce=true"
```

**Comment by rbradford** [comment]
> I pull to the latest master, try it again, the issue still there.
> Here is the command I used to start vhost_user_blk backend.
> 
> ```
> ./cloud-hypervisor/target/release/vhost_user_blk \
>         --block-backend "image=/root/test,sock=/tmp/vublk.sock,num_queues=1,rdonly=false,direct=false"
> ```
> 
> Here is the disk parameter to start guest
> 
> ```
> --disk "path=/home/cathy/clear-31890-kvm.img,vhost_user=true,num_queues=1,queue_size=128,wce=true"
> ```

You didn't specify the socket so it's spawning it's own. Your backend is never shutdown because it's never connected to.

**Comment by bjzhjing** [comment]
Ah, yes, sorry, I wrongly paste the command which I used to re-create the spawning case failure. But once I add the socket back, it's failed to start the guest with message "VMM thread failed VmReboot(DeviceManager(CreateVhostUserBlk(VhostUserCreateMaster(VhostUserProtocol(SocketConnect(Os { code: 2, kind: NotFound, message: "No such file or directory" }))))))". I will close this one later once I could verify in my local env.

**Comment by rbradford** [comment]
That's the expected behaviour. If the VM reboots it closes the connection which causes the backend to exit (this is also the behaviour you said you were expecting in the initial version of this issue.)

See #732  for the option that needs to be implemented to make it relisten.

**Comment by bjzhjing** [comment]
While start guest with socket and vhost-user enabled, I need to specify clear image in vhost-user-blk backend, which I'm not aware of it. Thanks @rbradford for telling me this.
Verify and close it.
