### ISSUE TITLE
Apply seccomp filters

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#925]
This issue is a sub-issue from #14, specific to using seccomp in order to harden the VMM's security.
Seccomp filters must be applied on each and every thread managed by the VMM. In case of Cloud-Hypervisor, this means the VMM main thread, every vCPU thread, and every virtio device thread must be assessed and filtered accordingly.

Both crosvm and Firecracker have their own way to apply seccomp, and this is due to the design of each VMM. Because Firecracker doesn't have to manage each virtio thread separately, they end up with the VMM and vCPU threads only. That's why they can simply use a common filter for both, depending on the level of security required by the user (`None`, `Basic` or `Advanced`). Crosvm is behaving differently, as it has one dedicated thread per device. That's why each device has its own policy (filter). One thing to notice though, these policies are defined through some specific files that are loaded at runtime. This means the files need to be present on the system where crosvm is running.

Based on this analysis, and since Cloud-Hypervisor is closer to crosvm in terms of threading design, it makes sense to apply different filters for each and every thread, as they have very different needs.
That being said, I think we should not adopt the `file` policy design, but instead have those filters hardcoded into the Cloud-Hypervisor code.
Looking at the `seccomp` crate from Firecracker, I think Cloud-Hypervisor should import it as the basic block to generate and apply seccomp filters.
As a first step, we should give the user a simple option `--seccomp on|off`, so that we can simply turn it on or off. I would like this option to be turned on by default as we want the VMM to be as secure as possible by default.

About the implementation steps, we should first establish a list of all the syscalls that could be needed if each and every device was enabled from the VMM. This will give us a loose profile to build a first filter.
Then we need to come up with a finer grain filter, based on the presence/absence of each device. This means we need to identify the set of syscalls needed by each device, and make a union of all the syscalls and generate a filter based on it. This generated filter needs to be applied to the VMM thread and the vCPUs threads.
Last step, we should identify for each device, what is the filter needed to let the device run correctly in its own thread. We need to implement this directly in vm-virtio as each device implementation should be able to apply the filters when running the threads.

One note about the filters, I would prefer if we don't define them as files. I know this provides some flexibility and convenience when we want to quickly modify them, but I think the most important is to take care of it transparently. And by having the filters defined in the code itself, our users won't have any issues making sure the files are present.

**Comment by andreeaflorescu** [comment]
> Both crosvm and Firecracker have their own way to apply seccomp, and this is due to the design of each VMM. Because Firecracker doesn't have to manage each virtio thread separately, they end up with the VMM and vCPU threads only. That's why they can simply use a common filter for both, depending on the level of security required by the user (`None`, `Basic` or `Advanced`).

Firecracker also wants to apply different filters on different threads. This is not the reason why we use none, basic and advanced. We have some improvements in mind. You can check them all here: https://github.com/firecracker-microvm/firecracker/issues/1177

> That being said, I think we should not adopt the `file` policy design, but instead have those filters hardcoded into the Cloud-Hypervisor code.

FYI, the file approach is actually super nice and it helps when running in production. If you forgot to whitelist something, you don't need to redeploy, you just need to pass another filter.

> Looking at the `seccomp` crate from Firecracker, I think Cloud-Hypervisor should import it as the basic block to generate and apply seccomp filters.

P.S. our plan is to make seccomp a crate as well and publish it to crates.io: https://github.com/firecracker-microvm/firecracker/issues/844

> As a first step, we should give the user a simple option `--seccomp on|off`, so that we can simply turn it on or off. I would like this option to be turned on by default as we want the VMM to be as secure as possible by default.
> 

> Last step, we should identify for each device, what is the filter needed to let the device run correctly in its own thread. We need to implement this directly in vm-virtio as each device implementation should be able to apply the filters when running the threads.

The implementation should take into consideration that each VMM can take the vm-virtio crate and extend it for their own use. It would be interesting to know which part will end up in rust-vmm and which will be in the vmm specific code.

> One note about the filters, I would prefer if we don't define them as files. I know this provides some flexibility and convenience when we want to quickly modify them, but I think the most important is to take care of it transparently. And by having the filters defined in the code itself, our users won't have any issues making sure the files are present.

**Comment by sboeuf** [comment]
@andreeaflorescu 
>Firecracker also wants to apply different filters on different threads. This is not the reason why we use none, basic and advanced. We have some improvements in mind. You can check them all here: firecracker-microvm/firecracker#1177

Nice!

>FYI, the file approach is actually super nice and it helps when running in production. If you forgot to whitelist something, you don't need to redeploy, you just need to pass another filter.

I agree this is very convenient, but as a first step, and since CH doesn't support any seccomp right now, I would like something simple. And I think relying on external files can come as a second step, where the file could override the default filters usually applied by the VMM.

>P.S. our plan is to make seccomp a crate as well and publish it to crates.io: firecracker-microvm/firecracker#844

Cool!

>The implementation should take into consideration that each VMM can take the vm-virtio crate and extend it for their own use. It would be interesting to know which part will end up in rust-vmm and which will be in the vmm specific code.

Yes exactly, that's the hard part because we're talking in terms of threads for seccomp, which is totally different than the way the code is organized and used from each VMM.

**Comment by andreeaflorescu** [comment]
> Yes exactly, that's the hard part because we're talking in terms of threads for seccomp, which is totally different than the way the code is organized and used from each VMM.

I thought a bit about this problem (really, just a bit :)) ). We could find a way for components to declare their used syscalls and have some sort of "collector" at a higher level that also applies the filters.

**Comment by sboeuf** [comment]
>I thought a bit about this problem (really, just a bit :)) ). We could find a way for components to declare their used syscalls and have some sort of "collector" at a higher level that also applies the filters.

Yes the idea of collecting is good, but the question is about who should be collecting? Because if you look at Firecracker, the VMM thread should collect to apply the right filters in case `virtio-blk` is used for instance. But in case of CH, the `virtio-blk` dedicated thread should collect and apply those.

**Comment by rbradford** [comment]
Status so far:

Threads isolated:

- [x] HTTP API thread
- [x] VMM
- [ ] Signal handler thread
- [ ] vCPU threads
- [ ] virtio-block
- [ ] virtio-net
- [ ] virtio-console
- [ ] virtio-iommu
- [ ] virtio-mem
- [ ] virtio-pmem
- [ ] virtio-rngs
- [ ] virtio-vsock
