### ISSUE TITLE
vhost_user_blk: failed to boot from vhost_user_blk backend while event_idx enabled

### ISSUE THREAD

**Issue by bjzhjing** [cloud-hypervisor/cloud-hypervisor#928]
While run test for PR #887 ,  there is one problem noticed that it would fail to boot from vhost_user_blk backend with event_idx enabled, that is to say, the CI test cases test_boot_from_vhost_user_blk and test_vhost_user_blk_self_spawning keeps failed. If event_idx is disabled for vhost_user_blk backend, those two test cases will pass. 

Here is how the problem reproduced in local. 

1. git clone the branch [bjzhjing:refactor-backends-worker-thread](https://github.com/bjzhjing/cloud-hypervisor/tree/refactor-backends-worker-thread)

1. remove the temporary change with event_idx by issue command: git reset --hard HEAD~1   

  

1. run following command to start vhost_user_blk backend

```
./cloud-hypervisor/target/release/cloud-hypervisor \
        --block-backend "image=clear-31890-kvm.img,sock=/tmp/vublk.sock,num_queues=1,rdonly=false,direct=false
```

4. run following command to start guest

```
./cloud-hypervisor/target/release/cloud-hypervisor \
        --cpus boot=1 \
        --memory size=512M,file=/dev/shm   \
        --kernel hypervisor-fw \
        --console off \
        --serial tty \
        --cmdline "console=ttyS0 reboot=k panic=1 nomodules i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd root=/dev/vda3" \
        --disk "vhost_user=true,socket=/tmp/vublk.sock,num_queues=1,queue_size=128,wce=true" \
        --net "mac=52:54:00:02:d9:01,ip=192.168.100.1" 
```
Then, you will the following panic message, which is printed by hypervisor-fw.
`PANIC: panicked at 'index out of bounds: the len is 16 but the index is 33', src/block.rs:241:26`

If you do not see the failure for the first time, you could repeat step 3-4, to see if it happens.

EDIT: Additionally, this problem could be reproduced with hypervisor-fw in local environment, but not vmlinux. However, in CI integration test environment, this issue appears for both hypervisor-fw and vmlinux.

**Comment by bjzhjing** [comment]
cc @slp @rbradford

**Comment by bjzhjing** [comment]
@slp @rbradford  While add event_idx support in vhost_user_block backend, should we update src/block.rs in hypervisor-firmware accordingly ?

**Comment by rbradford** [comment]
@bjzhjing it's an optional feature and we don't need to support it there, it should only be turned on if both sides have negotiated it.

**Comment by rbradford** [comment]
@bjzhjing You shouldn't open bugs about issues that are only seen in your PR. I just validated with master and everything works.

`target/debug/cloud-hypervisor  --block-backend image=/home/rob/workloads/clear-32360-kvm.img,sock=/tmp/vublk.sock,num_queues=1,rdonly=false,direct=false`

`target/debug/cloud-hypervisor         --cpus boot=1         --memory size=512M,file=/dev/shm           --kernel ~/src/rust-hypervisor-firmware/target/target/release/hypervisor-fw         --console off         --serial tty --disk "vhost_user=true,socket=/tmp/vublk.sock,num_queues=1,queue_size=128,wce=true" `

```
rob@artemis:~/src/cloud-hypervisor (master)$ target/debug/cloud-hypervisor         --cpus boot=1         --memory size=512M,file=/dev/shm           --kernel ~/src/rust-hypervisor-firmware/target/target/release/hypervisor-fw         --console off         --serial tty --disk "vhost_user=true,socket=/tmp/vublk.sock,num_queues=1,queue_size=128,wce=true"         
Cloud Hypervisor Guest
	API server: /run/user/1000/cloud-hypervisor.11387
	vCPUs: 1
	Memory: 512 MB
	Kernel: Some(KernelConfig { path: "/home/rob/src/rust-hypervisor-firmware/target/target/release/hypervisor-fw" })
	Initramfs: None
	Kernel cmdline: 
	Disk(s): Some([DiskConfig { path: None, readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: true, vhost_socket: Some("/tmp/vublk.sock"), wce: true, poll_queue: true }])
L
Starting..
Setting up 4 GiB identity mapping
Page tables setup
Found PCI device vendor=8086 device=d57 in slot=0
Found PCI device vendor=1af4 device=1042 in slot=1
Found PCI device vendor=1af4 device=1044 in slot=2
PCI Device: 0:1.0 1af4:1042
Bar: type=MemorySpace32 address=e7f80000
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=Unused address=0
Virtio block device configured. Capacity: 17909679 sectors
Found EFI partition
Filesystem ready
Jumping to kernel
[FAILED] Failed to start QEMU Guest Agent.
See 'systemctl status qemu-guest-agent.service' for details.
[  OK  ] Started Network Service.
         Starting Network Name Resolution...
[  OK  ] Started Network Name Resolution.
[  OK  ] Reached target Network.
[  OK  ] Reached target Host and Network Name Lookups.
         Starting Permit User Sessions...
[  OK  ] Started Permit User Sessions.
[  OK  ] Started Getty on tty1.
[  OK  ] Started Serial Getty on ttyS0.
[  OK  ] Reached target Login Prompts.
[  OK  ] Started Login Service.
[  OK  ] Reached target Multi-User System.
[  OK  ] Reached target Graphical Interface.

clr-d939a5aef7da424e93cab61b38490896 login: 
```

Make sure you're running the latest released hypervisor-fw (or build it from source) versions older than 0.2.1 (September 2019) incorrectly negotiate all features that are supported by the device.

**Comment by bjzhjing** [comment]
@rbradford I build rust-hypervisor-firmware from the source code to reproduce the issue and verify the fix. After I add the patch to move next_head at head of DriverState, I've tested it with cloud-hypervisor master branch, it also works.

**Comment by rbradford** [comment]
I'm telling you that this bug is invalid because it only happens on your PR. You must have made some mistake that breaks it there. Trying to hack around it in the firmware is not the correct solution.
