### ISSUE TITLE
vm-pci crate

### ISSUE THREAD

**Issue by liujing2** [cloud-hypervisor/cloud-hypervisor#94]
# Crate Name
vm-pci

# Short Description
vm-pci acts as a base crate focusing on PCI mechanism in rust-vmm. It follows 'vm-device' crate as the high level device interface, and defines common traits and structures to describe the behavior of PCI buses and devices.
vm-pci crate can be used by any PCI device implementation as well as devices using PCI as transportation mechanism, like virtio-pci.

# Why is this crate relevant to the rust-vmm project?
Both cloud-hypervisor and crosvm have PCI related implementation inside the 'devices' crate, servicing for legacy PCI devices, virtio-pci devices and vfio devices. As more PCI devices being added, and different use cases for different request, we need a separate crate to abstract and decouple the transportation layer and service as API for any implementation, to have users realize, setup and manage their PCI devices.

# Design 

## Relationship of vm-pci crate and vm-device crate
- `trait PciDevice` implements `trait Device`, and extends more PCI related behaviors. 
- Each PCI device instance need implement the `PciDevice` trait.
- `struct PciBus` represents a legacy PCI bus, implementing `trait Device` which describes what PCI bus needs to do.

### PciDevice trait
- Define common config_register_r/w methods for config space handling.
- Other essential APIs like irq setting, msi setting, etc.
```
pub trait PciDevice: Device {
    /// Read the configuration register according to register index.
    fn config_register_read(&self, reg_idx: usize) -> u32;
    /// Write the configuration register according to register index and offset.
    fn config_register_write(&mut self, reg_idx: usize, offset: GuestAddress, data: &[u8]);
    /// Other necessary APIs 
    fn assign_pin_irq(&mut self, irq_num: u32, irq_pin: Pin);
...
}
```
### PCI configuration 
- This describes legacy PCI config space.
- Include the capability list.
- get_bar_from_addr() is used to get the BAR index when VM exit.
- Each PCI device instance need a PciConfiguration structure.
```
pub struct PciConfiguration  { 
    registers: [u32, 64],  // Dynamically allocate for PCI
    writable_bits: [u32, 64], // writable bits for each register.
    bar_used: [bool; 6],
    // Contains the byte offset and size of the last capability.
    last_capability: Option<(usize, usize)>,
}

impl PciConfiguration {
    // O(n) 1<=n<=6 method to map a BAR index by an address.
    fn get_bar_from_addr(&self, addr: GuestAddress) -> u32;
    ...
}

```
### PciBus struct
- Act as a PCI bus, including all the `PciDevice` instances belong to the bus.
- Implement `Device` trait. 
- PciBus handles config address register directly by read() and write().

```
pub struct PciBus {
    pub devices: Vec<Arc<Mutex<dyn PciDevice>>>,
    pub config_address_reg: u32, 
}

impl Device for PciBus {
    fn read(&self, addr: GuestAddress, data: &mut [u8]) {
            let value: u32 = match addr {
                // Read config address register.
                0xcf8...0xcfb => self.config_address_reg,
                // Parse BDF and read config space register.
                0xcfc...0xcff => [...]
             }
             ...
    }
    fn write(&mut self, addr: GuestAddress, data: &[u8]) {...}
    [...]
}
```

### PciBar trait
- The principle is each bar instance has different behaviours, each device can have several BARs instances. For example, AC97 is a legacy PCI audio device has two bars for mixer and master configurations. But mixer and master read() are different because mixer only allows 16-bit read operation.
- The BARs regions are registered in `vm-device::DeviceManager`, together with `Device` instance.
```
pub trait PciBar: Send {
    // Called after allocating mmio address for the bar
    fn set_address(&mut self, addr: GuestAddress);
    fn get_address(&self) -> GuestAddress;
    fn size(&self) -> GuestUsize;
    fn region_type(&self) -> PciBarRegionType;

    /// Read the data from the address specified by the Bar with offset.
    fn read_bar(&self, offset: GuestAddress, data: &mut [u8]);
    /// Write the data to the address specified by the Bar with offset.
    fn write_bar(&mut self, offset: GuestAddress, data: &[u8]);
}
```

### Dummy PCI Device
```
// Dummy device has a MSIx bar
struct PciBarMSIx {
    addr: GuestAddress,
    size: GuestUsize,
    reg_idx: usize,
    region_type: PciBarRegionType,
    prefetchable: PciBarPrefetchable,
}

impl PciBar for PciBarMSIx {...}

pub struct DummyPciDevice {
    name: String,
    config: PciConfiguration,
    bars: Vec<Arc<Mutex<dyn PciBar>>>,
}

impl PciDevice for DummyPciDevice {
    [...]
}

impl Device for DummyPciDevice {
    // Redirect to read bar
    fn read(&self, addr: GuestAddress, data: &mut [u8]) {
        // Find the Bar idx by @addr.
        let bar_idx = self.config.get_bar_idx_from_addr(addr);
        // Get the offset from the address specified by this Bar
        let offset = addr - self.bars[bar_idx].lock().expect("failed to require lock").addr();
        // Call Bar's read method.
        self.read_bar(bar_idx).lock().expect().read_bar(offset,data);
    }
    [...]
}
```
### MSIx design (Sebastien?)

**Comment by sboeuf** [comment]
This can be closed as it is handled on rust-vmm directly.
