### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#95]
There have been a lot of changes to the command line behaviour we should check that the README is still correct.

**Comment by sboeuf** [comment]
Yes that's true, here are a few things that comes to mind:
- multiple disks, networks, ... are supported and we should show how to use them
- memory and pmem `size=` now supports `K`, `M`, `G` suffixes
- add a dedicated doc for `pmem`, and show how to use it

**Comment by sameo** [comment]
And a networking setup document as well. Maybe under `docs`, as a separate piece of documentation.

**Comment by sboeuf** [comment]
@sameo @rbradford do you think we can close this one? Or do we still expect more updates?

**Comment by sameo** [comment]
We should close that one.
