### ISSUE TITLE
Initramfs does not work with vmlinux

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#963]
Based on #873 the VMM can boot from an initramfs. But this only works with `bzImage`, as using `vmlinux` produces the following error:
```
Cloud Hypervisor Guest
        API server: /run/user/1000/cloud-hypervisor.21077
        vCPUs: 1
        Memory: 512 MB
        Kernel: Some(KernelConfig { path: "/home/sebastien/git_projects/virtio-fs/linux/vmlinux" })
        Initramfs: Some(InitramfsConfig { path: "/home/sebastien/workloads/alpine_initramfs.img" })
        Kernel cmdline: console=hvc0 quiet TEST_STRING=axz34i9rylotd8n50wbv6kcj7f2qushme1pg
        Disk(s): None
[    0.684850] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    0.685073] Kernel Offset: disabled
[    0.685192] ---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0) ]---
```

**Comment by sboeuf** [comment]
This issue will be solved once https://github.com/rust-vmm/linux-loader/pull/29 will be merged and pulled from Cloud-Hypervisor.

**Comment by sboeuf** [comment]
Just to correct what's incorrect, rust-vmm/linux-loader#29 does not fix the problem for the good reason. Because it breaks PVH boot, and because the VMM falls back to LinuxBoot, the initramfs can be loaded.
But when PVH is enabled, there's no support for initramfs, so instead the right fix is to make sure we fall back onto LinuxBoot when we try to boot from initramfs.

**Comment by aljimenezb** [comment]
@sboeuf I have been waiting for https://github.com/cloud-hypervisor/cloud-hypervisor/pull/873 to be merged so I can add the initramfs support in PVH boot as well. We can re-purpose this issue with that task, rename it, and assign it to me. 

PVH boot support is currently behind an optional feature, so this should only be a problem in tests that enable all features.

**Comment by sboeuf** [comment]
@aljimenezb go for it :)
