### ISSUE TITLE
virtio-mem support resizable allocations

### ISSUE THREAD

**Issue by teawater** [cloud-hypervisor/cloud-hypervisor#965]
https://github.com/cloud-hypervisor/cloud-hypervisor/pull/837#issuecomment-593347305
Resizable allocation can decrease the virtual memory allocation in initialization of virtio-mem.
Then customer can set a bigger virtio-mem hotplug size without set "/proc/sys/vm/overcommit_memory".

**Comment by teawater** [comment]
I think add it should first add resizable allocations to vm-memory.

**Comment by rbradford** [comment]
Fixed by #1694
