### ISSUE TITLE
vhost-user-vsock application

### ISSUE THREAD

**Issue by stefano-garzarella** [cloud-hypervisor/cloud-hypervisor#972]
I'm working on [vhost-user-vsock](https://github.com/stefano-garzarella/cloud-hypervisor/tree/vhost-user-vsock) application reusing `vhost_user_backend` and `vm-virtio` crates from Cloud Hypervisor.

The main purpose of `vhost-user-vsock` application is to allow [QEMU](https://github.com/stefano-garzarella/qemu/tree/vhost-user-vsock) to provide the hybrid vsock over AF_UNIX in the host.

Maybe it could be also useful for Cloud Hypervisor, moving the vsock code in another process.

Do you think it makes sense to merge it in Cloud Hypervisor? (the alternative could be rust-vmm)

Thanks,
Stefano

**Comment by sboeuf** [comment]
Hi @stefano-garzarella, I think the initiative makes a lot of sense. From Cloud-Hypervisor perspective, we're definitely trying to use vhost-user as much as possible, so it'd be great to have a `vhost-user-vsock` backend.
I think that given the fact rust-vmm is a bit behind regarding virtio and vhost-user, Cloud-Hypervisor is probably the best location for this for now.
And longer term, I hope we can move this to `rust-vmm`.

**Comment by stefano-garzarella** [comment]
@sboeuf thanks for your feedback!
It is almost complete and I'll send a PR here when I'll finish.

**Comment by gdamjan** [comment]
would this allow for native vsock on the host side? (without the unix domain socket emulation from firecracker). I'd like to see that in cloud-hypervisor.

**Comment by sboeuf** [comment]
@gdamjan 
>would this allow for native vsock on the host side? (without the unix domain socket emulation from firecracker).

Not as it is, but the support for native vsock on the host could be added, it's just a matter of implementation.

>I'd like to see that in cloud-hypervisor.

It's not part of our plan since the native vsock support on the host involves the virtqueues to be processed in the kernel, adding some attack surface.

I'm curious why you need native vsock on the host?

**Comment by rbradford** [comment]
> @sboeuf thanks for your feedback!
> It is almost complete and I'll send a PR here when I'll finish.

I think this makes sense elsewhere as those crates are now available in rust-vmm.

**Comment by stefano-garzarella** [comment]
> I think this makes sense elsewhere as those crates are now available in rust-vmm.

Yep, we have a GSoC and Outreachy students that we will work on it in the next months.
