### ISSUE TITLE
virtio-mem device start address is not align with block size

### ISSUE THREAD

**Issue by uMartinXu** [cloud-hypervisor/cloud-hypervisor#973]
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/6a934c32ee0d5a332998d38f1dc785854fca36d8/vmm/src/memory_manager.rs#L251-L253
Above bit operation only works when the VIRTIO_MEM_DEFAULT_BLOCK_SIZE is the power of 2 .
I did not find any comments from Virtio-mem that the block size must be the power of 2. Correct me :) . 
I verified it by changing VIRTIO_MEM_DEFAULT_BLOCK_SIZE into 6M, virito-mem device will reports error that the virtio-mem start address doesn't align with block size when resize the memory.

**Comment by rbradford** [comment]
As I said on on the PR I don't see why the user would make such a change.
