### ISSUE TITLE
Current integration test cannot reproduce the seccomp issue?

### ISSUE THREAD

**Issue by teawater** [cloud-hypervisor/cloud-hypervisor#994]
https://github.com/cloud-hypervisor/cloud-hypervisor/issues/986
This issue affect master with some days but ci didn't say anything.
Did I miss something?

**Comment by rbradford** [comment]
Your host OS is probably different with a different version of libc making different syscalls.

**Comment by teawater** [comment]
> Your host OS is probably different with a different version of libc making different syscalls.

The lost syscall is open.   Does any vmm can run without open /dev/kvm?

**Comment by sboeuf** [comment]
@teawater on my OS the syscall used was `openat()`.

**Comment by sboeuf** [comment]
I'm closing the issue as it's been fixed already.
